### ISSUE TITLE
MacBook 5,1: no wifi, no sound, no brightness control

### ISSUE THREAD

**Issue by airman1951** [dortania/OpenCore-Legacy-Patcher#101]
Successfully installed 11.3b3 on my MB5,1 using moderate SMSBIOS replacement. Missing wifi, sound, display control, see attached screenshots.

![Screenshot 2021-03-14 at 09 45 57](https://user-images.githubusercontent.com/77781242/111066383-0dcb9d80-84bf-11eb-9cd5-8789e79fa0e2.png)
![Screenshot 2021-03-14 at 09 46 40](https://user-images.githubusercontent.com/77781242/111066384-0efcca80-84bf-11eb-8a5b-8e0e5c343f07.png)
![Screenshot 2021-03-14 at 09 48 39](https://user-images.githubusercontent.com/77781242/111066385-0f956100-84bf-11eb-817c-6f4141dbd1b7.png)
![Screenshot 2021-03-14 at 09 50 24](https://user-images.githubusercontent.com/77781242/111066386-102df780-84bf-11eb-98c0-3a38231f0c93.png)
[Build-Folder.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6136545/Build-Folder.zip)

**Comment by tiziodcaio** [comment]
The sound isn't implemented yet isn't a bug

**Comment by tiziodcaio** [comment]
Graphics works?

**Comment by airman1951** [comment]
As you can see the display is recognized as a 21In. I changed the resolution from default to 1280x800 to have the display working.  Of course no acceleration, so Maps and other apps that require metal don't work. The main problem at this point is wifi: it seems related to a wrong or missing kext.

**Comment by tiziodcaio** [comment]
Pls remove the sound section, it doesn't be added yet...

**Comment by tiziodcaio** [comment]
I think the brightness could be implemented with brightnesskeys.kext but not sure

**Comment by khronokernel** [comment]
@airman1951 Hello, few things:

* Brightness is tied to GPU Acceleration for out patcher, so unfortunately will not be support until GPU acceleration patches land in the patcher(ETA is unknown currently)
* Audio is currently being developed [here](https://github.com/dortania/OpenCore-Legacy-Patcher/pull/75), so no support currently
* Wifi on the MacBook5,x series is a BCM94322 series chipset, and unfortunately the native IO82011 framework we hook into does not support the chipset correctly. Note BCM933224 chipsets are supported by the patcher. I clarified the docs regarding your wifi here: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/444819b6a0dbb54b0deded7b4d165a21b87a78b6

I will open a dedicated issue regarding your network chipset support for tracking

**Comment by khronokernel** [comment]
@airman1951 Please test this build:

* [OpenCore-RELEASE-v0.6.8.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6137298/OpenCore-RELEASE-v0.6.8.zip)

It has the old IO80211 patch from Mojave as mentioned here: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/102

**Comment by airman1951** [comment]
HI,
It works perfectly! I’m writing from the brand new BS installation by OCLP. Thanks a lot!

**Comment by khronokernel** [comment]
Perfect! I actually already added this support in 0.0.18's release so it's there for others as well

**Comment by airman1951** [comment]
Hi Khronokernel,
If you need more testers for the Legacy GPU Acceleration Patches, my MacBook 5,1 is fully available.
Kudos for your great work!
Nando.
