### ISSUE TITLE
MBP9,2 SMC still try update 

### ISSUE THREAD

**Issue by CuchoM** [dortania/OpenCore-Legacy-Patcher#107]
I've tested in my MBP9,2 and didn't work: Apple still tried to update my SMC, this was blocked by Opencore, everything is working fine, just boot time increased a little.
<img width="1440" alt="111447737-a0f61480-8705-11eb-9b4a-b2a9d985b1c7" src="https://user-images.githubusercontent.com/72659668/111453220-3ea01280-870b-11eb-8568-638abe434c2c.png">

**Comment by khronokernel** [comment]
Duplicate: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/104
