### ISSUE TITLE
MacPro3,1 Kernal Panic using .004

### ISSUE THREAD

**Issue by jaybanger1** [dortania/Opencore-Legacy-Patcher#11]
I was able to successfully create and patch my USB. Once the MacPro is booted, I choose the EFI and it presents me with the picker, where I choose external Install Big Sur. The boot process starts at which time I see the verbose, then it panics. I will upload the panic log, for reference. Thanks
[panic-2020-12-04-205029.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/5645674/panic-2020-12-04-205029.txt)

**Comment by khronokernel** [comment]
Has the CPU been upgraded with a model that supports SSE4.2?

**Comment by jaybanger1** [comment]
Great Question, the CPU's have been upgraded I am unsure if they support SSE4.2. I can re-boot into Catalina, and see the exact CPU's that are in there.

**Comment by jaybanger1** [comment]
Here is a copy of my efi file that was autogenerated by the patcher.
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5645725/EFI.zip)

**Comment by jaybanger1** [comment]
Is there an SSE4.2 workaround like "MouSSE" for machines without that instruction set?

https://forums.macrumors.com/threads/mp3-1-others-sse-4-2-emulation-to-enable-amd-metal-driver.2206682/

**Comment by khronokernel** [comment]
Oh sorry I meant SSE4.1 in my earlier message, and no there's no SSE4.1 emulator. So you'll need to upgrade the CPU if it doesn't support that instruction set

**Comment by jaybanger1** [comment]
Then thats a problem as it looks like the only SSE4 compatible in intel processors are:

Intel
Silvermont processors (SSE4.1, SSE4.2 and POPCNT supported)
Goldmont processors (SSE4.1, SSE4.2 and POPCNT supported)
Goldmont Plus processors (SSE4.1, SSE4.2 and POPCNT supported)
Tremont processors (SSE4.1, SSE4.2 and POPCNT supported)
Penryn processors (SSE4.1 supported, except Pentium Dual-Core and Celeron)
Nehalem processors and Westmere processors (SSE4.1, SSE4.2 and POPCNT supported, except Pentium and Celeron)
Sandy Bridge processors and newer (SSE4.1, SSE4.2 and POPCNT supported, include Pentium and Celeron)
Haswell processors and newer (SSE4.1, SSE4.2, POPCNT and LZCNT supported)

an none there work in MacPro3,1. 

MacPro 3,1 only supports Harpertown and Wolfdale processors. 👎 

So Mac Pro 3,1  is not supported if that is our issue here.

**Comment by khronokernel** [comment]
MacPro3,1 has Penryn support as well, I know a few people who've done the CPU upgrade and are running Big Sur rn

Anyways, this issue is now out of scope of this patcher as your hardware setup doesn't match our minimum hardware requirement
