### ISSUE TITLE
stuck at "about 13 minutes remaining

### ISSUE THREAD

**Issue by fridgeboy5000** [dortania/OpenCore-Legacy-Patcher#115]
its really weird but always if I try it it says "about 13 minutes remaining" and my cursor disappears

**Comment by khronokernel** [comment]
Need more information to be able to diagnose the issue, see here for recommended info:

https://dortania.github.io/OpenCore-Legacy-Patcher/DEBUG.html#filing-an-issue-with-us

**Comment by Ribero** [comment]
I got the same situation here and it often get stuck at 12 minutes left. I let it run during all night and in the morning it was still stuck here. I retried another time and the mac rebooted at 12 minutes before the end with a non working big sur install (see #100 ). Could be the same situation. What Mac are you using ?

**Comment by khronokernel** [comment]
This issue was resolved on Discord, the fault was a bad SD Card adapter
