### ISSUE TITLE
Mac Does not Boot

### ISSUE THREAD

**Issue by Mrsheep561** [dortania/OpenCore-Legacy-Patcher#1150]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

After changing the smbios spoofing level to minimal my Macbookpro14,3 does not boot.

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

Check the docs and issues tab

**Comment by martijnvandenboom** [comment]
What Mac are you using? 

iMac (Retina 5K, 27-inch, Late 2015)
Model Identifiers: iMac17,1

What version of OCLP are you using?
2.3.1

What OS version do you have installed or are trying to install?

Installed: Sequoia 15.3.2 (24D81)

What exactly is the problem you are facing? 

After installing OCLP 2.3.1 to disk my iMac refuses to boot. At boot I press the Option key to get the menu I choose the blue OCLP icon. Normally it proceeds with the apple logo but now it shows a circle with a diagonal.

Luckily with my old USB stick with OCLP 2.2.0 I booted of my USB. That worked fine. Then I mounted my EFI removed the OC folder and replaced it with the one from my USB stick. So now my iMac boots again but with 2.2.0
Use the tool: MountEFI
Available on GitHub: https://github.com/corpnewt/MountEFI

Now I have installed the OCLP 2.3.1 version to disk again.
And I have attempted to edit the OCLP config.plist file:
<key>Vault</key>
<string>None</string>

But couldn’t find the: vault.plist or vault.sig
So also couldn’t rename them

After the reboot I have to conclude that deactivating "OpenCore Vaulting" didn’t work for me.
It only gave me an empty entirely black screen for approx. 10 mins and then I decided to power down.
To repeat my previous steps and revert back to the good old version 2.2.0

Now this is the third time I try to install: OCLP 2.3.x
So I am even afraid my system will not be able to upgrade to the next macOS version 15.4.

It means I cannot install the latest version of OCLP to disk. Will there be a definite fix for booting macOS with 2.3.x?
