### ISSUE TITLE
Is it possible to patch legacy USB 1.1 automatically?

### ISSUE THREAD

**Issue by mikezang** [dortania/OpenCore-Legacy-Patcher#1151]
### Machine Model

Macmini3,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

![IMG_7273](https://github.com/user-attachments/assets/cce06688-d237-4b12-93d8-d4b0c5e15956)
Though I installed Montery and Sonoma, then updateed Sequoia with the same USBHub, wired keyboard and mouse, I can't use those wired keyboard and mouse, I also tried several other USB HUBs, I still can't use my keyboard and mouse!
I have suggestion, is it possible to patch USB 1.1 automatically without click button "OK"? so that we can use wireless keyboard and mouse....

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

![IMG_7273](https://github.com/user-attachments/assets/c3ee03ff-bc05-4df4-a7bd-9a6a18a5fa88)
I installed Sequoia on External SSD, now I only can use it.
I updated to Sonoma 14.7.2 to Internal SSD, now I can't patch USB 1.1! I can only try reboot and try again, sometimes the wired keyboard and mouse maybe work by chance, but I am not sure when the next chance will come...

**Comment by mikezang** [comment]
![Sonoma14 7](https://github.com/user-attachments/assets/ae5cb75b-9835-46de-83da-ad8c20d9a6a4)
![Sonoma14 7 1](https://github.com/user-attachments/assets/3d7d5861-d824-48e1-bc9a-9d98bfc17810)

**Comment by mikezang** [comment]
![Sequoia15 0](https://github.com/user-attachments/assets/458d1367-e4cf-48b1-b3ec-a63450499e23)
![Sequoia15 1](https://github.com/user-attachments/assets/dbd471f3-d2fe-4a70-8fb3-5e740cc8e2c0)

**Comment by JonnyTech** [comment]
#1021
