### ISSUE TITLE
need a reinstall after random reboot (OS is slow and 'Window path Name' back color is gray.)

### ISSUE THREAD

**Issue by Tetonne** [dortania/OpenCore-Legacy-Patcher#1153]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

issueBug report on intel Ventura on imac16.1
OS is slow and 'Window path Name' back color is gray.
in window a huge grey bar where path name is written;

Need to apply Root dormania again

- Starting Patch Process
- Determining Required Patch set for Darwin 22
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Mounted Universal-Binaries.dmg
- Running sanity checks before patching
- Running patches for iMac16,1
- Running Preflight Checks before patching
- Found SkylightPlugins folder, removing old plugins
- Cleaning Auxiliary Kernel Collection
- Removing AppleIntelBDWGraphicsFramebuffer.kext
- Relocating VMwareGfx.kext kext to /Library/Relocated Extensions
- Relocating DPSReflector.kext kext to /Library/Relocated Extensions
- Finished Preflight, starting patching
- Installing Patchset: Monterey GVA
- Handling Installs in: /System/Library/PrivateFrameworks
- Installing: AppleGVA.framework
- Installing: AppleGVACore.framework
- Installing Patchset: Monterey OpenCL
- Handling Installs in: /System/Library/Frameworks
- Installing: OpenCL.framework
- Installing Patchset: Intel Broadwell
- Handling Installs in: /System/Library/Extensions
- Adding AuxKC support to AppleIntelBDWGraphics.kext
- Installing: AppleIntelBDWGraphics.kext
- Adding AuxKC support to AppleIntelBDWGraphicsFramebuffer.kext
- Installing: AppleIntelBDWGraphicsFramebuffer.kext
- Found existing AppleIntelBDWGraphicsGLDriver.bundle, overwriting...
- Found existing AppleIntelBDWGraphicsMTLDriver.bundle, overwriting...
- Found existing AppleIntelBDWGraphicsVADriver.bundle, overwriting...
- Found existing AppleIntelBDWGraphicsVAME.bundle, overwriting...
- Found existing AppleIntelGraphicsShared.bundle, overwriting...
- Writing patchset information to Root Volume
- Checking if RSRMonitor is needed
- Found kext with GPUCompanionBundles: AppleIntelBDWGraphics.kext
- Adding monitor: /System/Volumes/Preboot/4E60E527-0D02-4D52-935C-.../cryptex1/current/OS.dmg
- Installing com.dortania.opencore-legacy-patcher.auto-patch.plist
- com.dortania.opencore-legacy-patcher.auto-patch.plist checksums match, skipping
- Installing com.dortania.opencore-legacy-patcher.macos-update.plist
- com.dortania.opencore-legacy-patcher.macos-update.plist checksums match, skipping
- Installing com.dortania.opencore-legacy-patcher.rsr-monitor.plist
- com.dortania.opencore-legacy-patcher.rsr-monitor.plist checksums match, skipping
- Building new Auxiliary Kernel Collection
- Forcing Auxiliary Kernel Collection usage
- Unmounting root volume
- Patching complete

Please reboot the machine for patches to take effect

After reboot
Need to active again : Rogue Amoeba Software and Dominic Feira always those ones

Reboot
And this is solved

it solve for 1 or 20 days
unknown event that need to apply patch again
this issue was on previous release too.

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

always happen after a reboot (not every reboot)

**Comment by Tetonne** [comment]
- Starting Patch Process
- Determining Required Patch set for Darwin 22
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Mounted Universal-Binaries.dmg
- Running sanity checks before patching
- Running patches for iMac16,1
- Running Preflight Checks before patching
- Found SkylightPlugins folder, removing old plugins
- Cleaning Auxiliary Kernel Collection
  - Removing AppleIntelBDWGraphicsFramebuffer.kext
  - Relocating VMwareGfx.kext kext to /Library/Relocated Extensions
  - Relocating DPSReflector.kext kext to /Library/Relocated Extensions
- Finished Preflight, starting patching
- Installing Patchset: Monterey GVA
- Handling Installs in: /System/Library/PrivateFrameworks
  - Installing: AppleGVA.framework
  - Installing: AppleGVACore.framework
- Installing Patchset: Monterey OpenCL
- Handling Installs in: /System/Library/Frameworks
  - Installing: OpenCL.framework
- Installing Patchset: Intel Broadwell
- Handling Installs in: /System/Library/Extensions
  - Adding AuxKC support to AppleIntelBDWGraphics.kext
  - Installing: AppleIntelBDWGraphics.kext
  - Adding AuxKC support to AppleIntelBDWGraphicsFramebuffer.kext
  - Installing: AppleIntelBDWGraphicsFramebuffer.kext
  - Found existing AppleIntelBDWGraphicsGLDriver.bundle, overwriting...
  - Found existing AppleIntelBDWGraphicsMTLDriver.bundle, overwriting...
  - Found existing AppleIntelBDWGraphicsVADriver.bundle, overwriting...
  - Found existing AppleIntelBDWGraphicsVAME.bundle, overwriting...
  - Found existing AppleIntelGraphicsShared.bundle, overwriting...
- Writing patchset information to Root Volume
- Checking if RSRMonitor is needed
  - Found kext with GPUCompanionBundles: AppleIntelBDWGraphics.kext
  - Adding monitor: /System/Volumes/Preboot/4E60E527-0D02-4D52-935C-6584FA4C27F1/cryptex1/current/OS.dmg
- Installing com.dortania.opencore-legacy-patcher.auto-patch.plist
  - com.dortania.opencore-legacy-patcher.auto-patch.plist checksums match, skipping
- Installing com.dortania.opencore-legacy-patcher.macos-update.plist
  - com.dortania.opencore-legacy-patcher.macos-update.plist checksums match, skipping
- Installing com.dortania.opencore-legacy-patcher.rsr-monitor.plist
  - com.dortania.opencore-legacy-patcher.rsr-monitor.plist checksums match, skipping
- Building new Auxiliary Kernel Collection
- Forcing Auxiliary Kernel Collection usage
- Unmounting root volume
- Patching complete

Please reboot the machine for patches to take effect

**Comment by Tetonne** [comment]
additional information
Adguard (genuine and serialized) extension need to be accepted after 1st reboot after 2nd dormania ventura is ok but for how long. Bug make iMac very slow but it's ok

**Comment by Tetonne** [comment]
Thanks for you answer. ok I can confirm It work here on my
iMac 21,5 pouces, fin 2015 Processeur 1,6 GHz Intel Core i5 double cour Graphisme Intel HD Graphics 6000 1536 Mo Mémoire 8 Go 1867 MHz DDR3 macos Ventura 13.7.1
except that I have to install it again.

iMac16,1 Could be added to the list :-) Hope solution will be found to make it stable (not install again when grey bar appears.
Happy dev
BEst regards

**Comment by crystall1nedev** [comment]
To get support, join the [OpenCore Patcher Paradise](https://discord.gg/rqdPgH8xSN) Discord server.
