### ISSUE TITLE
Mouse stop working

### ISSUE THREAD

**Issue by torvid98** [dortania/OpenCore-Legacy-Patcher#1154]
### Machine Model

MacBook5,1

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I tryed to use SONOMA patcher on my MAC PRO 5.1 and it worde fine. But suddenly mouse click stopped working.
I can use the mouse but I can not use mouse click.  I restart Mac and mouse work again. But stop working again. What can I du to make the mouse work? 

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

I have tryed to disconeck items. But no luck

**Comment by crystall1nedev** [comment]
To get support, join the [OpenCore Patcher Paradise](https://discord.gg/rqdPgH8xSN) Discord server.
