### ISSUE TITLE
Blocking `displaypolicyd` on MacBookPro9,1 to allow GPU Switching

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#116]
Currently to get GPU switching to work reliably with MacBookPro9,1 users are required to either kill or outright disable `displaypolicyd`. This solution isn't ideal as the daemon may re-enable itself after an OS update, and it's not as intuitive for new users.

We've attempted to block the process with [RestrictEvents](https://github.com/acidanthera/RestrictEvents), however the binary seems to continue running regardless. Will need to look into either why `displaypolicyd` misbehaves or find another method to block this binary in macOS.

For more information on this issue, see the following thread: [MacBookPro9,1 boots to black screen #3](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/3)

**Comment by jbdamiano** [comment]
The displaypolicyd could not be disabled
🗂  ~
🚀 sudo launchctl disable system/com.apple.displaypolicyd

🗂  ~
🚀 sudo launchctl print-disabled system/com.apple.displaypolicyd
disabled services = {
	"com.apple.CSCSupportd" => true
	"com.apple.ftpd" => true
	"com.apple.mdmclient.daemon.runatboot" => true
	"fans" => false
	"com.openssh.sshd" => false
	"com.apple.displaypolicyd" => true
	"com.apple.bootpd" => true
	"com.apple.ftp-proxy" => true
}

🗂  ~
🚀 reboot

------

sudo launchctl print-disabled system/com.apple.displaypolicyd
disabled services = {
	"com.apple.CSCSupportd" => true
	"com.apple.ftpd" => true
	"com.apple.mdmclient.daemon.runatboot" => true
	"fans" => false
	"com.openssh.sshd" => false
	"com.apple.bootpd" => true
	"com.apple.ftp-proxy" => true
}

In each reboot you have to do a sudo pkill displaypolicyd

**Comment by cgrazy** [comment]
I've patched the RestrictEvents.kext by myself, added that to the config.plist and after the reboot displaypolicyd process is not seen in activity monitor, graphics switch is working: Intel HD Graphics after the reboot, when opening photoshop 2020 the graphics switches to NVIDIA, after closing photoshop Intel is used again. No clue if that's just by accident :-D
[RestrictEvents.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6200667/RestrictEvents.kext.zip)

**Comment by khronokernel** [comment]
@cgrazy Interesting, did you only edit this section or where there other parts you needed to adjust in RestrictEvents?:
https://github.com/acidanthera/RestrictEvents/blob/master/RestrictEvents/RestrictEvents.cpp#L34-L38

We simply added `/usr/libexec/displaypolicyd` there, however that didn't work for us.

@dennes544 Can you test cgrazy's kext above? You tested Dhinak's build but reported that it failed, would like to see if this build is any different

**Comment by dennes544** [comment]
@khronokernel in Dhinak's build actually was `/usr/libexec/displaypolicyd`, checked it in iHex

will test @cgrazy build in half of a hour or so

**Comment by dennes544** [comment]
@jbdamiano but, I’ve checked that, and after disabling that daemon, after reboot I got intel graphics, and switch to nvidia in photoshop

**Comment by cgrazy** [comment]
@khronokernel I'm using that statement: 
		static const char *procBlacklist[] {
			"/System/Library/CoreServices/ExpansionSlotNotification",
			"/System/Library/CoreServices/MemorySlotNotification",
			"/usr/libexec/firmwarecheckers/eficheck/eficheck",
            "/usr/libexec/displaypolicyd",
		};

**Comment by dennes544** [comment]
@cgrazy please execute this `sudo launchctl enable system/com.apple.displaypolicyd`, reboot and check graphics switching

@khronokernel checked, doesnt work (at least for me). Before check, just to be sure, i re-enabled daemon, after reboot switching didnt work, until i've killed displaypolicyd

**Comment by khronokernel** [comment]
Hrrmm, @dennes544 @cgrazy can you both upload your EFIs as-is with RestrictEvents? Wondering if I'm missing something obvious

**Comment by dennes544** [comment]
@khronokernel [EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6200861/EFI.zip)

**Comment by khronokernel** [comment]
@dennes544 RestrictEvents is a Lilu plugin, so it must come *after*. So that means the kext is failing linking as-is and so does nothing

**Comment by cgrazy** [comment]
after re-enabling the deamon and a reboot: 
[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6200869/EFI.zip)
![Screenshot 2021-03-24 at 23 38 50](https://user-images.githubusercontent.com/66645171/112392890-781fe180-8cfa-11eb-8fa3-d97cd17b4cd2.png)

**Comment by dennes544** [comment]
@khronokernel Oh, didn't know that, give me a second

**Comment by dennes544** [comment]
@khronokernel Sorry for my mistake, its actually working.

Before you close this issue, i have one more question.

Can i use original serial number, uuid and other parametrs, and just change mbp9,1 to mbp11,3?

**Comment by khronokernel** [comment]
@dennes544 Yeah, under Patcher Settings select "Moderate" SMBIOS patching. By default we keep it minimal to but everyone has their own preference so the options there to mess with. Kexts are ofc adjusted in the patcher to ensure proper operation

**Comment by dennes544** [comment]
@khronokernel ok, thank you and your team very much for your work!

**Comment by dennes544** [comment]
@khronokernel built oclp from last commit, and graphics change doesnt work again, and displaypolicyd is not the case. checked its not running and to be sure tried to kill. Efi attached

[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6201021/EFI.zip)

**Comment by khronokernel** [comment]
@dennes544 What GPU is active currently, the Nvidia? If so, can you check what is holding the GPU active? iirc iStat Menus will tell you what process is using the dGPU, don't remember what other ways there are to check

**Comment by dennes544** [comment]
@khronokernel couldn't find it in iStats menus, but here is screenshot System Monitor

![image](https://user-images.githubusercontent.com/4429342/112398023-52073b00-8d14-11eb-882d-79e5ec09e298.png)

**Comment by dennes544** [comment]
@khronokernel, and yes, active nvidia

**Comment by dennes544** [comment]
Replaced *-Override.kext with those, from past issue, and its started to work

[Overrides.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6201150/Overrides.zip)

**Comment by khronokernel** [comment]
@dennes544 Try the latest from main:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2338468817/artifacts/49335375

**Comment by dennes544** [comment]
@khronokernel Yep, working now, thanks! :)
