### ISSUE TITLE
AppleHDA - MacBook Pro 17" Mid 2009 MacBook 5,2 ioreg output

### ISSUE THREAD

**Issue by mushroomnz** [dortania/OpenCore-Legacy-Patcher#117]
[ioreg.txt](https://github.com/dortania/bugtracker/files/6211251/ioreg.txt)
As mentioned in bottom of this page [ https://dortania.github.io/OpenCore-For-Legacy-Macs/post-install/audio.html] , have provided the ioreg output from 10.11.6 with working Audio

**Comment by khronokernel** [comment]
Thank you for the IOReg, we'll try to implement it into AppleALC
