### ISSUE TITLE
MacPro3,1 Boot Loop

### ISSUE THREAD

**Issue by c-o-pr** [dortania/OpenCore-Legacy-Patcher#118]
**System:** MacPro3,1 running 10.15.7 19H524 based on Dosdude Patcher and CatalinaOTAswufix. System includes GTX-680 and macOS-supported PCIe USB3 and eSATA cards. System drive is connected by internal SATA.

**Goal:** Intend to install Big Sur on USB SSD via OCLP but never get OC fully loaded.

**OpenCore-patcher 0.0.19**
OC built with defaults except for Debug mode
OC drive connected directly to Mac's front USB port

**Summary:**
Choosing OCLP icon from boot-menu appears to hang. This behavior has been reported by one other MacPro3,1 user on "Macrumors Big Sur on Unsupported Mac" thread. 

**Details:** 
- OC debug output shows very slow progress, approx half-second per log line output.
- OC drive access LED shows drive is being read continuously, so unclear if logging is bottleneck or maybe USB is running 1.0 mode? Idk 
- After many minutes of progress, Mac spontaneously resets to boot chime and begins reloading OC. Eventually it will reset again, in a loop (well, 3 times took 20 minutes so didn't wait for a 4th to complete).

Attached OC Build folder and OC debug output from OC drive EFI partition.

Let me know what else I can provide, or suggestions on how to proceed.

TIA

/wire

[c-o-pr OCLP DEBUG MacPro3,1 10.15.7 Dosdude Patcher.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6216611/c-o-pr.OCLP.DEBUG.MacPro3.1.10.15.7.Dosdude.Patcher.zip)

**Comment by khronokernel** [comment]
> Choosing OCLP icon from boot-menu appears to hang. This behavior has been reported by one other MacPro3,1 user on "Macrumors Big Sur on Unsupported Mac" thread.

Fixed with this commit: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/eeeb222896beda8d59e88d83b9bd703a29869f36

**Comment by c-o-pr** [comment]
This commit allows me to get OCLP loaded and choose the Big Sur installer. 
Thank you

Leads to another roadblock, midway through the Big Sur 10.11.3 installation the system apparently goes to sleep and won't wake up. Nursing the mouse / kb makes no difference.

Maybe should try using Terminal and pmset before install?

Should I open a new issue, or continue to comment on this one.

/wire

**Comment by khronokernel** [comment]
I'll reopen this issue, very odd regarding the sleep and then no wake again. I would recommend the pmset trick and see if that helps

**Comment by newkton1** [comment]
I have seen this too today and reported with screenshots under CMP3,1 freeze thread here.

**Comment by khronokernel** [comment]
Assuming resolved as no responce

**Comment by Coquinmaou** [comment]
Installer hangs after about half way progress bar on both MacPro 5.1 and MarcPro 3.1. Used version 0.2.1

**Comment by Coquinmaou** [comment]
nstaller hangs after about half second reboot way progress bar on both MacPro 5.1 and MarcPro 3.1. Used version 0.2.1
