### ISSUE TITLE
iMac14,1 kernel panic after sleep

### ISSUE THREAD

**Issue by family1232009** [dortania/OpenCore-Legacy-Patcher#119]
Today, my iMac 21.5" Late 2013 was unresponsive to keyboard, mouse and power button after sleep. I unplugged it for a few minutes and after that it turned on, then I get an error message: "**You need to restart your computer. Hold down the Power button for several seconds or press the Restart button**." It rebooted again and then macOS boots ok.

This is the kernel panic report
https://pastebin.com/ZbJxwY9e

**Comment by khronokernel** [comment]
> Today, my iMac 21.5" Late 2013 was unresponsive to keyboard, mouse and power button after sleep.

How long was this sleep? Look like the machine entered hibernation, which we currently have an open issue here: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/72

What version of OCLP did you run? If you're unsure, you can run the following in terminal:

```
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:OCLP-Version
```

For tests, I have a few below: 
* [OpenCore-CTS.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6217831/OpenCore-CTS.zip)
* [OpenCore-CTS+HF.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6217832/OpenCore-CTS%2BHF.zip)
* [OpenCore-HF.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6217833/OpenCore-HF.zip)

**Comment by family1232009** [comment]
> How long was this sleep?

10-15 hours, hibernation is disabled (hibernatemode=0)
OCLP 0.0.19

Several days have passed and this issue was no longer there, my iMac sleeps and wakes up well.
You can close the thread, anyway if the issue comes again I will inform you :)

**Comment by khronokernel** [comment]
Sounds good to me, just respond to this issue and I will reopen
