### ISSUE TITLE
Mac Pro 3,1 with No USB Support

### ISSUE THREAD

**Issue by aec360** [dortania/Opencore-Legacy-Patcher#12]
Hello. My install using 0.0.3, 0.04, and 0.0.5 all get to the installation screen for my drive but do not allow me to use a keyboard or mouse because there is no USB support. I am attaching a photo of the installation screen. I am hoping that you will fix this issue with Mac Pro 3,1 machines. Please assist.
![IMG_0384](https://user-images.githubusercontent.com/43285143/101232608-5a554080-3667-11eb-895e-cfdfa63dfa5e.jpeg)

**Comment by khronokernel** [comment]
Hello, are you able to upload the EFI folder the patcher created? Also can you elaborate a bit more on what devices you're using and what Usb controller you're using(ie. on board ports or external PCIe card)

**Comment by aec360** [comment]
1. [EFI copy.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5646441/EFI.copy.zip)
2. Onboard Ports AND External PCIe card (Inateck KT4004).

**Comment by khronokernel** [comment]
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5646444/EFI.zip)

Try this EFI

**Comment by aec360** [comment]
Will try now.

**Comment by aec360** [comment]
Hello, @khronokernel. I am getting occasional Kernel Panics and I am attaching two of them. Sometimes, I actually get to the installer with no USB Support. With your new EFI, I have not yet gotten back to the installer.
[panic-2020-12-04-205029.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/5646499/panic-2020-12-04-205029.txt)
[panic-2020-12-04-210105.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/5646500/panic-2020-12-04-210105.txt)

**Comment by khronokernel** [comment]
Hmm, are you able to remove the 3rd arty USB card and test? Curious if it's interfering

**Comment by aec360** [comment]
> Hmm, are you able to remove the 3rd arty USB card and test? Curious if it's interfering

Absolutely! That has been out for hours.

**Comment by aec360** [comment]
**Update**: We had an existing Catalina install that we put into a 4,1 flashed to 5,1 Mac Pro, booted into your patcher, successfully upgraded the drive using the standard Big Sur Patcher, mounted the EFI partition from the drive we upgraded, copied the EFI file that YOU sent me to the corresponding EFI partition on the drive that we upgraded, then pulled the drive out of the 4,1/5,1 and put it into the aforementioned 3,1, the picker showed up on the drive, it went through the verbose flurry, and then eventually came to the login screen, and we were able to actually log in. Nonetheless, we could not make any of this happen directly on the 3,1. P.S. The drive was previously using DosDude's Catalina Patcher. We removed EVERYTHING from the EFI folder and replaced it with the EFI file you sent me and we were golden. Hopefully, this is helpful.

**Comment by aec360** [comment]
And, of course, I had to go through all of this with the OEM video card.

**Comment by aec360** [comment]
@khronokernel, it booted into Big Sur that first night and has not booted back in sense. It actually worked with two SSDs and has not worked since.

**Comment by jaybanger1** [comment]
@aec360  you forgot to post that you removed the out of date OEM Bluetooth card. Now it boots every time no problem. We only haven't tested it with a newer AMD RX video card. However all is working with full metal support with your Nvidia GTX 760 card.
