### ISSUE TITLE
macpro5,1 (2010) BigSur does not boot (panic)

### ISSUE THREAD

**Issue by woefi** [dortania/OpenCore-Legacy-Patcher#122]
**Describe the bug**
I have a vanilla BS 11.2.3 Install on an SSD (empty EFI), which works on my MacBookPro9,2 in combination with a USB-Key of OCLP0019.
I failed to boot my macpro51 with this SSD (after installing OCLP on its EFI)

**Steps to reproduce the behavior:**
1. Boot Mojave on mp51 (nvme in pcie-slot)
2. Open OpenCore Legacy Patcher.app; change PatcherSettings: Verbose=ON and Debug=ON; Build EFI; Install EFI on SATA-SSD
3. with SIP disabled, bless the EFI partition of the SATA-SSD (as in dortania/oclp/troubleshoot)
4. reboot
5. OpenCore Picker shows up, select SATA-SSD (BigSur11.2.3)
6. Verbose-text spills the screen, pauses at "AppleKeyStore:10708:268: operation failed" ...then moves on
7. Panic after 5 to 10 minutes: "Mac OS version: 20D91 Kernel version... ...Panic diags file available: YES (0x0)..."

**Screenshots**
![1 oc bootpicker IMG_8252](https://user-images.githubusercontent.com/70533823/113154790-a9d40380-9238-11eb-801d-d6e9df82b59b.jpeg)
![2 start verbose IMG_8254](https://user-images.githubusercontent.com/70533823/113154795-ab9dc700-9238-11eb-9cc6-27ad5efbc671.jpeg)
![3 dsmos IMG_8260](https://user-images.githubusercontent.com/70533823/113154798-ac365d80-9238-11eb-9101-9014b576adc2.jpeg)
![4 panic IMG_8264](https://user-images.githubusercontent.com/70533823/113154804-ad678a80-9238-11eb-822c-8709937a4560.jpeg)

**Build Folder**
0019 debug:
[opencore-2021-03-31-123916.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6236980/opencore-2021-03-31-123916.txt)
[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6236999/EFI.zip)
[panic report.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6237118/panic.report.txt)

**Hardware**
 - OS Running: macOS 10.14.6, Mojave)
 - OS Patching: macOS 11.2.3, Big Sur)
 - Model Patching: MacPro5,1
MacPro5,1 (2010), single 6core W3680; BootROM144 cleaned by tsiAlex, SIP off, with or without NVMe (Mojave), USB3 card, RAM: 3x16GB; unflashed Sapphire pulse RX 580; original WIFI/BT

**Additional context**
System (11.2.3) was originally installed by MacBookPro9,2 (OCLP0012, 0018) via USB connection (USB-Key -> OCLP-only; USB-Cable -> SATA-SSD-empty efi) and was booting fine with the corresponding OCLP USB Key.

**Comment by woefi** [comment]
I have edited the post to include the panic report.txt if this helps.

**Comment by khronokernel** [comment]
Thank you, I see for some reason the wifi patches are breaking the boot process. Could you run the below program and run File -> SaveAs and send me the output? Will tell me a bit more about how the wifi card is configured. Wondering if there's a typo in the pathing:

https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip?raw=true

**Comment by woefi** [comment]
Sorry, 302 does not work on Mojave.. will download 210...

**Comment by woefi** [comment]
[KingMoPro.ioreg.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6237166/KingMoPro.ioreg.zip)

**Comment by khronokernel** [comment]
Thank you! I see the issue, we incorrectly assumed MacPro5,1 used a BCM943224 chipset when in reality they shipped with a BCM94322. Fix the logic in this commit:

https://github.com/dortania/OpenCore-Legacy-Patcher/commit/898b10f932fe6434becb71fbd763f10512b87712

**Comment by woefi** [comment]
originally this SSD had 11.0.1 for mbp92 with a micropatcher and wifi patches, which worked with oclp0009, after over-installing from recovery.
But since 11.1 I reinstalled completely from scratch, meaning I erased the SSD.

**Comment by woefi** [comment]
thank you!
If you need someone to test, let me know, I have: 
MacPro5,1
MacBookPro9,1
iMac14,1 with 3rd party nvme
MacBookPro8,1 with upgraded WIFI/BT4 (bcm94331pciebt4cax)

**Comment by woefi** [comment]
Another problem on this system now: 

It now boots, but the screen turns off when it should display the login-screen.
(4k-monitor connected to the RX 580 via DP cable)

I can tell it is successfully booted, because Airport has a connected device with its name; I can turn it savely off by pressing on the wired keyboard: ctrl+eject, then <enter> and the power light goes off.
