### ISSUE TITLE
MacPro5,1 screen shuts off right before login

### ISSUE THREAD

**Issue by woefi** [dortania/OpenCore-Legacy-Patcher#123]
**Describe the bug**
I'm booting an already successful install of BS 11.2.3 with OCLP 0020 debug (latest commit for MP51 Wifi)
I am seeing all the verbose output, but at the last "mile" when I shortly hear my GPU fans initiate and right before the login-screen usually appears, the screen goes into power saving mode. 

**To Reproduce**
• The system boots up, I hear the chime.
• Opencore picker comes up, I choose the BS partition, which is already selected (no other hdd inside).
• Then all the verbose output rolling through.
• After a rather short time I hear GPU fans (AMD rx580) spin up, as usual before the login screen
• Then the screen turns black and shuts off. No login screen.
• But the System is booted successfully: I can verify this by typing in my password and after waiting a few seconds by pressing ctrl+ejectkey and then return (which usually brings up the "do you want to shutdown"-dialog and shuts down)
The power light goes off, as expected.

**Build Folder**
[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6242757/EFI.zip)

[opencore-2021-04-01-085909.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6242751/opencore-2021-04-01-085909.txt)

**Hardware (please complete the following information):**
OS Running: macOS 10.14.6, Mojave)
OS Patching: macOS 11.2.3, Big Sur)
Model Patching: MacPro5,1
MacPro5,1 (2010), single 6core W3680; BootROM144 cleaned by tsiAlex, SIP off, installed USB3 card, booting from SATA-SSD in Slot 1; RAM: 3x16GB; unflashed Sapphire pulse RX 580; original WIFI/BT

**Comment by woefi** [comment]
The last line I see on screen before it gets black is: IOConsoleUsers: gIOLockState 3

![IOConsoleUsers gIO IMG_8309](https://user-images.githubusercontent.com/70533823/113299524-3fd16200-92fd-11eb-87b5-edab6a2fd262.jpeg)

**Comment by khronokernel** [comment]
Very odd, both MacPro5,1 and MacPro7,1 (model being spoofed) shouldn't have any AppleGraphicsDevicePolicy issues causing black screens. My recommendation would be to add `agdpmod=ignore` in your config.plist under `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args`

To access the EFI, you will need to mount it via terminal or [MountEFI](https://github.com/corpnewt/MountEFI) though seeing as you pulled the debug log you seem already familiar with the process

**Comment by woefi** [comment]
Thanks, but it did not help.
Same behaviour.

![Bildschirmfoto 2021-04-01 um 18 06 49](https://user-images.githubusercontent.com/70533823/113322543-1b817f80-9315-11eb-9261-932baa3d7e10.png)

**Comment by woefi** [comment]
I checked with the macrumors thread "opencore on the macpro" [https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/](url) and the config.plist they use only has boot-args: -no_compat_check and nothing else...

I don't want to mix up two different methods and I like the universal OCLP way, but maybe this could help? What do you think?

**Comment by khronokernel** [comment]
That's actually slightly off, as the first page has a config.plist with no SMBIOS spoof which OCLP relies on for OTA updates

Down the thread, I found the prebuilt images people have been using and it includes the following:

```
-lilubetaall -wegbeta agdpmod=pikera shikigva=80 unfairgva=1 mbasd=1 -wegtree -no_compat_check no32exec=0
```

And here I see the old bugger, so I would recommend swapping `ignore` for `pikera`

**Comment by woefi** [comment]
still the same, though. 
Does it have to do with the ports on the card?  My Sapphire pulse rx 580 has 2 DisplayPort and 2 HDMI. My 4k Display is connected by DP. I use exactly the same setup on my PC (opencore67 w macos 10.14 and 11)

**Comment by khronokernel** [comment]
Very odd, my other recommendation is to try and disable WhateverGreen in hopes of fixing the issue. It will break DRM most likely but worth seeing if that's the issue. Simply open the config.plist and add `-wegoff` to boot-args as previously done with  agdpmod args

**Comment by volsk** [comment]
Same issue on Mac Pro 5.1 with two different Nvidia cards. Logging into the machine via  screen sharing or SSH works.

**Comment by woefi** [comment]
reading through the manual opencore method in the macrumors-thread, I noticed you have to find out what the path to your graphics card is, (using gfxutil) for me, the lower PCIe x16 Slot is: PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0). But this device-property can't be found in the OCLP generated config.plist.

So I wonder, if this speciality of macpros (PCIe-Slots with various graphics configurations) is not considered in OCLP?
Or does it not matter, because you are dealing with an artificially unsupported mac and not some Hackintosh... So you only need a "light" config.

**Comment by woefi** [comment]
this of course is only in the Advanced section, "Enabling Hardware Acceleration".

**Comment by volsk** [comment]
> reading through the manual opencore method in the macrumors-thread, I noticed you have to find out what the path to your graphics card is, (using gfxutil) for me, the lower PCIe x16 Slot is: PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0). But this device-property can't be found in the OCLP generated config.plist.
> 
Anything we can to help debug?

**Comment by khronokernel** [comment]
> So I wonder, if this speciality of macpros (PCIe-Slots with various graphics configurations) is not considered in OCLP?
> Or does it not matter, because you are dealing with an artificially unsupported mac and not some Hackintosh... So you only need a "light" config

Adding properties via DeviceProperties is mainly recommend for configurations with multiple GPUs as you can selectively set properties per card. However for this situation, using a boot-arg like with OCLP just applies generally to all GPUs.

However if you have a direct link I would appreciate it, I am not all to familiar

**Comment by khronokernel** [comment]
> I went back to 0.18 and everything works again. But I'm happy to experiment and debug. Just don't know where to start. Anything we can to help debug?

Interesting, can you upload the configuration from 0.0.18?

**Comment by volsk** [comment]
> > I went back to 0.18 and everything works again. But I'm happy to experiment and debug. Just don't know where to start. Anything we can to help debug?
> 
> Interesting, can you upload the configuration from 0.0.18?
Of course. See attached. Please note that I went back to the full 0.0.18 build. Not just the config.

[config.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6249954/config.plist.zip)

**Comment by khronokernel** [comment]
Yeah diffing between 0.0.18 and 0.0.20, I see no difference for GPU support. Main ones are:

* Wifi Device ID spoof changed to IO80211Mojave (Highly doubt it affects)
* HibernateMode set to Auto (Unlikely to affect)
* PlatformFeature set to `-1`(use default instead of forcing `0` from before)
  * https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleFeatures.h

My recommendation is to try toe 0.0.20 config and see if setting the following changes anything:

* Setting PlatformInfo -> SMBIOS -> PlatformFeature to `0`
* Disable IO80211Mojave and AirPortBrcm4331 under Kernel -> Add (Simply set Enabled to false)

Otherwise quite confusing why 0.0.18 works but not newer

**Comment by woefi** [comment]
Could it be oc 67 vs oc 68?

**Comment by khronokernel** [comment]
0.0.14+ is using 0.6.8, though 0.0.14-0.0.18 are using [7bb41aa](https://github.com/acidanthera/OpenCorePkg/commit/7bb41aa)(Hibernation fix commit) while 0.0.19 are using [9cd61bb](https://github.com/acidanthera/OpenCorePkg/commit/9cd61bb)(new boot picker) and 0.0.20 is using [a57d8df](https://github.com/acidanthera/OpenCorePkg/commit/d1d55ff402e17ecc706100c5537422412e955ad8)(fix CPU reading on Nvidia chipsets)


Looking at the change log of each:

<details>
<summary>Changelog info</summary>

```
# 7bb41aa
- Switched to VS2019 toolchain for Windows builds
- Reduced legacy boot install interaction effort
- Increased OpenCanopy rendering performance
- Reduced OpenCanopy mouse pointer input lag
- Fixed that cursor bounds could be different from OpenCanopy's
- Improved builtin picker rendering performance
- Added Memory Type decoding for SMBIOS in `Automatic` mode
- Properly support setting custom entries as default boot options
- Fixed creating log file when root file system is not writable
- Fixed `DisableSingleUser` not being enabled in certain cases
- Added `ForceBooterSignature` quirk for Mac EFI firmware
```
```
# 9cd61bb
- Switched to VS2019 toolchain for Windows builds
- Reduced legacy boot install interaction effort
- Increased OpenCanopy rendering performance
- Added OpenCanopy Shut Down and Restart buttons
- Reduced OpenCanopy mouse pointer input lag
- Fixed that cursor bounds could be different from OpenCanopy's
- Improved builtin picker rendering performance
- Added Memory Type decoding for SMBIOS in `Automatic` mode
- Properly support setting custom entries as default boot options
- Fixed creating log file when root file system is not writable
- Fixed `DisableSingleUser` not being enabled in certain cases
- Added `ForceBooterSignature` quirk for Mac EFI firmware
- Fixed OpenCanopy sometimes cutting off shown boot entries
- Further improved CPU frequency calculation on legacy CPUs
- Fixed SMBIOS SMC version encoding sequence
- Added TSC frequency reading from Apple Platform Info
- Added TSC frequency reading for Apple devices with nForce chipsets
- Added `Base` and `BaseSkip` lookup for ACPI patches
- Fixed ACPI table magic corruption during patching
- Fixed unnatural OpenCanopy and FileVault 2 cursor movement
- Fixed OpenCanopy interrupt handling causing missed events and lag
- Improved OpenCanopy double-click detection 
- Reduced OpenCanopy touch input lag and improved usability
- Improved keypress responsiveness in OpenCanopy and builtin pickers
- Improved non-repeating key detection in OpenCanopy and builtin pickers
- Fixed Escape preventing OpenCanopy fade up until released, on some systems
- Fixed fast repeat then stall issue with key handling on some PS/2 systems
- Added accurate Shift+Enter/Shift+Index detection when using PollAppleHotKeys
- Added CTRL-held indicator to builtin picker
- Replaced VerifyMsrE2 with ControlMsrE2 also allowing unlock on some firmwares
- Fixed OpenCanopy flicker when refreshing the entry view
- Added OpenCanopy TAB navigation support
- Added OpenCanopy graphical password interface
- Added OpenCanopy pulsing animation to signal timeout
- Added OpenCanopy 'set default' indicator
- Fixed OpenCanopy not aborting timeout on pointer click
- Fixed OpenCanopy intro animation not scaling with UIScale
- Add OpenCanopy boot entry label scrolling (fixes missing long labels)
- Added tabbable Shutdown and Restart buttons to builtin picker
- Fixed in-firmware shutdown for some systems running OpenDuet
- Added Zero as alias hotkey for Escape, to force show picker if hidden
```

```
# a57d8df
- Switched to VS2019 toolchain for Windows builds
- Reduced legacy boot install interaction effort
- Increased OpenCanopy rendering performance
- Added OpenCanopy Shut Down and Restart buttons
- Reduced OpenCanopy mouse pointer input lag
- Fixed that cursor bounds could be different from OpenCanopy's
- Improved builtin picker rendering performance
- Added Memory Type decoding for SMBIOS in `Automatic` mode
- Properly support setting custom entries as default boot options
- Fixed creating log file when root file system is not writable
- Fixed `DisableSingleUser` not being enabled in certain cases
- Added `ForceBooterSignature` quirk for Mac EFI firmware
- Fixed OpenCanopy sometimes cutting off shown boot entries
- Further improved CPU frequency calculation on legacy CPUs
- Fixed SMBIOS SMC version encoding sequence
- Added TSC frequency reading from Apple Platform Info
- Added TSC frequency reading for Apple devices with nForce chipsets
- Added `Base` and `BaseSkip` lookup for ACPI patches
- Fixed ACPI table magic corruption during patching
- Fixed unnatural OpenCanopy and FileVault 2 cursor movement
- Fixed OpenCanopy interrupt handling causing missed events and lag
- Improved OpenCanopy double-click detection 
- Reduced OpenCanopy touch input lag and improved usability
- Improved keypress responsiveness in OpenCanopy and builtin pickers
- Improved non-repeating key detection in OpenCanopy and builtin pickers
- Fixed Escape preventing OpenCanopy fade up until released, on some systems
- Fixed fast repeat then stall issue with key handling on some PS/2 systems
- Added accurate Shift+Enter/Shift+Index detection when using PollAppleHotKeys
- Added 'set default' indicator to builtin picker
- Replaced VerifyMsrE2 with ControlMsrE2 also allowing unlock on some firmwares
- Fixed OpenCanopy flicker when refreshing the entry view
- Added OpenCanopy TAB navigation support
- Added OpenCanopy graphical password interface
- Added OpenCanopy pulsing animation to signal timeout
- Added OpenCanopy 'set default' indicator
- Fixed OpenCanopy not aborting timeout on pointer click
- Fixed OpenCanopy intro animation not scaling with UIScale
- Add OpenCanopy boot entry label scrolling (fixes missing long labels)
- Added tabbable Shutdown and Restart buttons to builtin picker
- Fixed in-firmware shutdown for some systems running OpenDuet
- Added Zero as alias hotkey for Escape, to force show picker if hidden
- Added =/+ key as alias for CTRL to set default OS
- Added additional support for configuring correct key repeat behaviour with KeySupport mode
```

</details>
<br>

We can see the main differences that would affect macOS:
```
- Further improved CPU frequency calculation on legacy CPUs
- Fixed SMBIOS SMC version encoding sequence
- Added TSC frequency reading from Apple Platform Info
```

However this is quite odd, as nothing here seems to be harmful to the boot process regarding GPU output

**Comment by khronokernel** [comment]
Assuming that 0.0.19 is the initial cause of issues, then the main culprits could be:

* SMC-Spoof.kext + Associated Kext patch
  * Very unlikely an SMC version number would affect GPU support
* HibernateMode set to Auto
  * Extremely unlikely, as this just handles hibernation keys and images
* PlatformInfo -> SMBIOS -> PlatformFeature
  * Unlikely however there are some GPU related properties so perhaps
* OpenCore 0.6.8 commit [9cd61bb](https://github.com/acidanthera/OpenCorePkg/commit/9cd61bb)

Knowing this, I have more reason to believe PlatformFeature would be the culprit as the other possible culprits do not make any sense in my honest opinion

**Comment by volsk** [comment]
I tried several commits and through trial and error I've found
f006ee4 - Works
04a039c - Fix GPU Switching in MacBookPro9,1 - Does not work

**Comment by khronokernel** [comment]
@-@
Oh my lord ofc it's displaypolicyd issues. Thank you for reporting this! I know where the bug is now will fix in 5min and push

**Comment by khronokernel** [comment]
Should be resolved now, do test and report back if broken. Will reopen the issue if required, however I'm quite sure that out custom RestrictEvents build was the issue. For those needing the .app, a build is provided below:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2408247237/artifacts/51288170

**Comment by woefi** [comment]
This finally worked for me! Thank You!
