### ISSUE TITLE
cMP3,1 freezes with dead mouse and keyboard 

### ISSUE THREAD

**Issue by newkton1** [dortania/OpenCore-Legacy-Patcher#124]
Immediately after using a wired Apple keyboard to select the OCLP efi icon (see screenshot), the wired USB mouse and keyboard are dead and the install cannot proceed.

cMP3.1 attempting to install 11.3 beta 6 from freshly built patched USB stick.

Is this the missing USB 1.1 drivers issue?
![Freeze at efi screen](https://user-images.githubusercontent.com/13056263/113386265-d74db800-93c4-11eb-9637-b49050596158.jpg)

**Comment by khronokernel** [comment]
This was resolved already in main, you can grab a prebuilt binary here:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2405143552/artifacts/51199862
