### ISSUE TITLE
Macbook Pro 4,1 crash on boot again (UGA & GOP)

### ISSUE THREAD

**Issue by cboukouv** [dortania/OpenCore-Legacy-Patcher#125]
Coming back to issue #84 I have tested (the version proposed and the latest)  and with both I have the same problem. With the latest one I tried to boot in debug mode and I attach the opencore log, in case it helps. When I boot Catalina with dosdude1's patch I don't have this problem, although some text is displayed in the first stage of booting the MBP4,1.

[opencore-2021-03-27-165811.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6252096/opencore-2021-03-27-165811.txt)

**Comment by khronokernel** [comment]
Resolved here: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/118

For latest build, see here:
https://github.com/dortania/OpenCore-Legacy-Patcher/actions/runs/713574182

**Comment by cboukouv** [comment]
Thank you! I confirm it works. BTW keyboard illumination is working, while with dosdude1's patched Catalina it wasn't (had to use a utility for that). And the screen brightness although it cannot be adjusted, at least it is at the maximum level it boots, whereas in Catalina I had to use Brightness Slider to make it bright (now I use it to reduce the brightness). Now only WiFi and GPU acceleration are missing to be perfect.
