### ISSUE TITLE
MacBook4,1 USB & Internal Trackpad/Keyboard not working

### ISSUE THREAD

**Issue by HexagonWin** [dortania/OpenCore-Legacy-Patcher#126]
**Describe the bug**
On the MacBook4,1, the Internal Keyboard, trackpad, and the usb ports (2 of them all) doesn't work.
The installer is unable to boot with an usb flashdrive, and the installer must be created in the internal hdd/ssd to boot. (I guess this is because of the usb not working) After boot, the language selection pops up, but can't be selected because none of the input devices work.

**To Reproduce**
1. Make a new partition in the internal drive.
2. Use the tools to create it an installer drive.
3. Install OCLP on the EFI and check the problem.

**Screenshots**
I can't post a screenshot of it, as it will just show the language selection.
![bigsurbigbook](https://user-images.githubusercontent.com/67452729/113472387-eb191d00-949d-11eb-84a2-dd33f63d4b7a.jpg)

**Build Folder**
It's the MacBook4,1 default. I didn't edit anything except verbose boot.

**Hardware (please complete the following information):**
 - OS Running (macOS 10.14.6, Mojave RMC Patcher)
 - OS Patching (macOS 11.2.3, Big Sur)
 - Model Patching (MacBook4,1)

**Additional context**
Thanks!

**Comment by khronokernel** [comment]
Unfortunately seeing all the current USB issues RMC's team needs to work around, it's not possible for us with how OCLP is setup:

https://github.com/rmc-team/macos-patcher/tree/master/resources/patch/MacBook4%2C1

My recommendation would be to use a patcher that supports BaseSystem patching, as currently OCLP relies on using completely vanilla installers and Recovery images for its native-esque support. I don't follow patcher development from other members so you will need to do a bit of research to see if anyone's able to integrate.

Regarding docs, we will update them to show USB and such as non-functional
