### ISSUE TITLE
Fixed Backlight Control on iMac 12,1 with Nvidia Quadro

### ISSUE THREAD

**Issue by fabienpascal** [dortania/OpenCore-Legacy-Patcher#127]
**Describe the bug**
Backlight control isn't working

**To Reproduce**
Press F1 and F2 won't adjust backlight. Backlight is at 100%

**Screenshots**

![Screen Shot 2021-04-04 at 1 26 05 PM](https://user-images.githubusercontent.com/53749821/113499541-6257bb00-9549-11eb-9e23-be997b049d24.png)
![Screen Shot 2021-04-04 at 1 25 56 PM](https://user-images.githubusercontent.com/53749821/113499543-64217e80-9549-11eb-8aa4-f9ce613d17a6.png)

**Build Folder**
Attached is the config.plist

**Hardware (please complete the following information):**
 - macOS 11.2.3, Big Sur)
 - iMac 12,1

**Additional context**
I actually fixed the issue by adding the missing AppleBacklightFixup.kext file to the OCLP EFI/OC/Kexts folder, and then adjusting a few entries in OpenCore Configurator to edit the config.plist. Sharing the details (kext file and config.plist here for whoever find it useful.

[BackLight Fix OCLP.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6254020/BackLight.Fix.OCLP.zip)

**Comment by khronokernel** [comment]
Ah found the issue, for some reason iMac12,x skip the backlight patch but iMac11,x don't. Fixed in main

**Comment by fabienpascal** [comment]
@khronokernel Thank you :)
