### ISSUE TITLE
Audio on Windows 10 UEFI

### ISSUE THREAD

**Issue by fabienpascal** [dortania/OpenCore-Legacy-Patcher#128]
**Describe the bug**
No audio on Windows 10 UEFI

**To Reproduce**
N/A

**Screenshots**
OpenCore Configurator:
![Screen Shot 2021-04-04 at 1 28 52 PM](https://user-images.githubusercontent.com/53749821/113499581-b367af00-9549-11eb-8bae-b63020d34fd3.png)

**Build Folder**
Attached the asml files for the iMac 12,1 and 12,2 for whoever find it useful

**Hardware (please complete the following information):**
 - Windows 10 Pro 20H2
 - iMac 12,1

**Additional context**

[ASML Config.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6254024/ASML.Config.zip)
Attached the asml files to be put in EFI/OC/ACPI and the reference config.plist I edited on my machine.

**Comment by khronokernel** [comment]
Unfortunately Windows support would be out of scope with this patcher, I don't even have Windows installed an any of my machines and debugging is unrealistic for our team as it's not something we're familiar with. 

However I do believe Howeitworks has some resources to fix Audio support on UEFI windows for 2011 Macs, I would take a peak at their site and repo:

* [howeitworks.com](http://howeitworks.com/valor)

* [Repo](https://onedrive.live.com/?authkey=%21AIgUt2CcdxJTZuo&id=96BBB207261AA1B5%21344&cid=96BBB207261AA1B5)

**Comment by fabienpascal** [comment]
@khronokernel Thanks.
I actually fix it as described above. If your patcher can detect the mac ID, you can pull the ASML files I have attached, and add the config info to the config.plist via your patcher? if not it is fixed on my end. This was more for sharing purposes. :)
