### ISSUE TITLE
Documentation:  Conflicting recommendations regarding which macOS versions the patcher can use

### ISSUE THREAD

**Issue by zardini123** [dortania/OpenCore-Legacy-Patcher#130]
In the README in the first paragraph, we users are notified this patcher can be used on/for older macOS versions.  Quote:
> Designed around Big Sur support, however can be used on older OSes.

At the end of the preamble, we are instead instructed that if we want to use a older macOS version, we should look elsewhere with a different patcher.  Quote:
> Note 2: Currently OpenCore Legacy Patcher only supports macOS 11, Big Sur installs. For older OSes, please use dosdude1's patchers

In the patcher guide, it is implied when downloading macOS installer that there are no restrictions in macOS version.
Quote from https://dortania.github.io/OpenCore-Legacy-Patcher/INSTALLER.html#downloading :
> As you can see, we get a nice list of macOS installers. If you need a particular versions of macOS, you can select it by typing the number next to it. For this example we'll choose 10

The "Note 2" in the README is what personally throws me in a loop about what patchers dortania developers think we should use for each macOS version.  I was thinking with how good OpenCore's support is I could run this patcher for installing macOS Mojave on a Early 2009 iMac, but Note 2 makes me concerned.

**Comment by khronokernel** [comment]
README is fairly clear, the patcher is designed around Big Sur support for older machine but can be used on other OSes if desired. 

The paragraph below is about .app support:
> Application supports running on macOS Mavericks (10.9) and newer
> Supports macOS Lion (10.7) and newer if python 3.6 or higher is manually installed, simply run the OpenCore-Patcher.command located in the repo

Could you elaborate where the information is conflicting?

**Comment by zardini123** [comment]
Hi!  Wow, that was a fast reply.  I accidentally submitted the issue before I was finished typing, so please take a moment and read the edits.  Thank you so much!

**Comment by zardini123** [comment]
After thinking about it again, I think the conflicting part about Note 2 is the use of word "support."  It could imply that the patcher only is able to patch macOS 11, or the developers are only targeting the patcher for use with Big Sur, but other OS's are possible.  I think a possible rewrite of that note to remove conflict would be:
> Note 2: Currently OpenCore Legacy Patcher is designed for installing macOS 11, Big Sur.  It is still possible to use the patcher with older OSes, but there is no developer support if issues arise.  For a more targeted patcher for your desired OS, it is recommended to use dosdude1's patchers.

Let me know what you think!

**Comment by khronokernel** [comment]
Ah I see the concerns, will update the docs but a quick run down:

> In the patcher guide, it is implied when downloading macOS installer that there are no restrictions in macOS version.
> Quote from https://dortania.github.io/OpenCore-Legacy-Patcher/INSTALLER.html#downloading :

This was just copy pasted from our other work, [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/). A corrected entry would most likely be "select macOS Big Sur or newer" to future proof for macOS 12 I have no real concerns with having support day 1 on June 7th at least regarding booting. Acceleration depends how generous Apple is

> The "Note 2" in the README is what personally throws me in a loop about what patchers dortania developers think we should use for each macOS version. I was thinking with how good OpenCore's support is I could run this patcher for installing macOS Mojave on a Early 2009 iMac, but Note 2 makes me concerned.

This is regarding .app support, as we're a simple python script we hold no real baggage like Swift based interfaces.

Edit:

> After thinking about it again, I think the conflicting part about Note 2 is the use of word "support." It could imply that the patcher only is able to patch macOS 11, or the developers are only targeting the patcher for use with Big Sur, but other OS's are possible. I think a possible rewrite of that note to remove conflict would be:

I think that's slightly off as note 2 references where the patcher can physically be run, less so of OpenCore itself however I see what you're trying to say. Will update within the hour and close this issue

**Comment by zardini123** [comment]
> This is regarding .app support, as we're a simple python script we hold no real baggage like Swift based interfaces. So can run virtually anywhere

> I think that's slightly off as note 2 references where the patcher can physically be run, less so of OpenCore itself

So "support" in Note 2 means that the patcher application is only intended to be ran on macOS Big Sur?  Being its a python script, shouldn't it run anywhere that python's supported?

Or is your comment regarding the python script regarding a different note on the README?

**Comment by khronokernel** [comment]
> So "support" in Note 2 means that the patcher application is only intended to be ran on macOS Big Sur? Being its a python script, shouldn't it run anywhere that python's supported?

- .app for 10.7+
- OpenCore for Big Sur

**Comment by zardini123** [comment]
> > So "support" in Note 2 means that the patcher application is only intended to be ran on macOS Big Sur? Being its a python script, shouldn't it run anywhere that python's supported?
> 
> * .app for 10.7+
> * OpenCore for Big Sur

Ahh its starting to make sense now.  Thank you for all the assistance and clarification!  I sincerely appreciate it.
