### ISSUE TITLE
IO80211HighSierra.kext does not work any longer on Catalina and Mojave (since 0.0.19)

### ISSUE THREAD

**Issue by Ausdauersportler** [dortania/OpenCore-Legacy-Patcher#131]
**Describe the bug**
Injecting this extension on iMac11,x or 12,x with Atheros WiFi does not work any longer using Catalina or Mojave. Apparently you have changed the extension (only a few bytes and the copyright message Dortania). But this was enough :-) 

**To Reproduce**
1. Created EFI with OCLP 0.0.21 for iMac12,1 (no SecureBoot for Catalina)
2. Booted into Big Sur (everything works)
3. Booted into Catalina (system startup is fine, WiFi does not work)
4. changed extension back (without changing the config.plist) with older version having an Apple Copyright from 0.0.18 or before to get functionality back

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.15.7, Catalina 19H1026)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. iMac11,.3 spoofing to iMacPro1,1)

**Additional context**
I know, not supported now but since you already plan to extend support better now, than later...

**Comment by khronokernel** [comment]
```
Error - kext com.apple.iokit.IO80211HighSierra declares a dependency on com.apple.kpi.private. Only Apple kexts may declare a dependency on com.apple.kpi.private.
```

Apparently Apple parses Copyright for the kexts? Absolutely insane but easy enough to fix, just very odd that Big Sur does not error out
