### ISSUE TITLE
Xserve2,1 being reported as not compatible model in opencore patcher builder

### ISSUE THREAD

**Issue by huntertrainboy** [dortania/OpenCore-Legacy-Patcher#135]
When building in the opencore legacy patcher, I try to change the model to Xserve2,1 and get told it is unsupported, even though it is a supported model in the documentation.
![IMG_6974](https://user-images.githubusercontent.com/13009151/114251128-e9ec6200-996d-11eb-8bed-bb46a5baea0a.jpg)

**Comment by khronokernel** [comment]
Requires 0.0.22, see below for build:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2462355472/artifacts/52899742
