### ISSUE TITLE
SSD Write and Read Spead Reduced so MacBook Pro 2012 working so slow

### ISSUE THREAD

**Issue by ahmetozcan999** [dortania/OpenCore-Legacy-Patcher#137]
I installed Big Sur but my ssd working so slow. Ssd is working good on Catalina.
In Catalina write 380MB/S Read 470 MB/S but in Big Sur both of 85MB/S
I return Catalina and it is working fast again
Both of Big Sur and Catalina same file system GUID and APFS
How can I solve this problem

**Comment by khronokernel** [comment]
Hello, could you elaborate on the hardware setup? ie. model (ie. MacBookPro10,1), SSD used, OCLP version used, etc

**Comment by Ausdauersportler** [comment]
Got the same message on the micropatcher page, too.

**Comment by khronokernel** [comment]
After testing with other users, we cannot replicate. This seems to be an issue on your machine
