### ISSUE TITLE
BOOT folder and BOOTx64.efi not automatically created using OCLP 0.0.22

### ISSUE THREAD

**Issue by lulujyc** [dortania/OpenCore-Legacy-Patcher#138]
**Describe the bug**
When building OpenCore using OCLP 0.0.22 for MacBookPro10,1 the BOOT folder is not created. Until manually creating the folder and copying BOOTx64.efi from OpenCore 0.6.8 Release package, Mac's boot picker will not recognize the OpenCore EFI partition.

**To Reproduce**
1. Create an OpenCore boot folder for MBP10,1
2. Open the created EFI folder
3. The BOOT folder is not found

**Screenshots**
N/A

**Build Folder**
N/A

**Hardware (please complete the following information):**
 - OS Running 10.15.7
 - OS Patching 11.2.3
 - Model Patching MBP10,1

**Additional context**
N/A

**Comment by khronokernel** [comment]
BOOTx64.efi is replaced with System/Library/CoreServices/boot.efi, are you sure you installed this correctly to your EFI as well?

**Comment by lulujyc** [comment]
> 
> 
> BOOTx64.efi is replaced with System/Library/CoreServices/boot.efi, are you sure you installed this correctly to your EFI as well?

Thanks for your reply! Yes this efi exists in the EFI directory, but the mac doesn't find boot device for some reason until I manually add BOOTx64.efi.

**Comment by khronokernel** [comment]
Hmm, well explanation on why we don't use BOOTx64.efi is to avoid overwriting Windows/Linux boot loaders. Additionally, we've had many reports that Ivy bridge machines including MacBookPro10,1 have had successes with the S/L/C/boot.efi method:

https://dortania.github.io/OpenCore-Legacy-Patcher/TESTED.html

Could try resetting NVRAM? Additionally, what drive is OpenCore on and what format?

**Comment by lulujyc** [comment]
> 
> 
> Hmm, well explanation on why we don't use BOOTx64.efi is to avoid overwriting Windows/Linux boot loaders. Additionally, we've had many reports that Ivy bridge machines including MacBookPro10,1 have had successes with the S/L/C/boot.efi method:
> 
> https://dortania.github.io/OpenCore-Legacy-Patcher/TESTED.html
> 
> Could try resetting NVRAM? Additionally, what drive is OpenCore on and what format?

Resetting NVRAM doesn't work for me. I've installed OpenCore on a USB stick and is formatted with HFS (GPT).
The machine has a very early version of Boot ROM... Shipped with Lion or something
If that's the case (early version Boot ROM doesn't support the S/L/C boot method) maybe adding an option to switch between the two boot methods might work for more people? Just guessing...
Thanks for your help!

**Comment by khronokernel** [comment]
> The machine has a very early version of Boot ROM... Shipped with Lion or something

I see, most likely it's a FAT32 limitation of the firmware that Apple later resolved. I do agree there should be an option, as it's not always applicable to have the latest boot rom as well as extreme edge cases where even latest firmwares may not play nicely. Will add support in a little bit

**Comment by lulujyc** [comment]
> 
> 
> > The machine has a very early version of Boot ROM... Shipped with Lion or something
> 
> I see, most likely it's a FAT32 limitation of the firmware that Apple later resolved. I do agree there should be an option, as it's not always applicable to have the latest boot rom as well as extreme edge cases where even latest firmwares may not play nicely. Will add support in a little bit

Thank you!
