### ISSUE TITLE
Hide the OpenShell.efi entry in the OC boot picker

### ISSUE THREAD

**Issue by family1232009** [dortania/OpenCore-Legacy-Patcher#139]
Is it possible to disable OpenShell.efi or make it auxiliary in the next releases, or do we need it?

![Снимок экрана 2021-04-11 в 02 12 56](https://user-images.githubusercontent.com/44340726/114285023-5e59fa80-9a6d-11eb-8902-f37b93b5f8ce.png)

**Comment by khronokernel** [comment]
We have it present for debugging purposes with users, so we do have it enabled on non-vaulted configurations. We'd prefer it still enabled as it makes our end much easier however can have it set as Auxiliary to true to hide it by default
