### ISSUE TITLE
iMacs / MacPro with AMD Polaris cards will need iMacPro1,1 SMBIOS 

### ISSUE THREAD

**Issue by Ausdauersportler** [dortania/Opencore-Legacy-Patcher#14]
Tried to run your patcher on my iMac 2010 with an AMD RX480 GPU. To enable 4K HEVC and 4K H.264 we used (as the MacPro users) OpenCore to spoof the iMacPro1,1 ID.

Without this you could only get 4K H.264 by patching AppleGVA.framework - which does not work currently with Big Sur either. 

Any plans to add this?

**Comment by Ausdauersportler** [comment]
Hi, again!

I spend some time to check out the current 0.0.9 OLCP version with iMac 11,2 - 11,3 - 12,2 .

pro:

- Atheros WiFi patch is working
- VoodooHDA.kext for sound is working (although sound is not really great)

contra:

- CatalinaBC5701Ethernet.kext does not load (while working fine when patched with the micropatcher)
- external display ports are not initialised and external screen remain black with model iMac15,1 

quick fixes:
changing System ProductName/System Serial Number/MLB  from iMac15,1 to iMacPro1,1 using macserial values enables external screen with modded NVIDIA and AMD cards  

notes:
iMac 11,x would really win if you move to iMacPro1,1 and get the Ethernet working. sleep ist working properly out of the box right now.

iMac 12,x are a more complex animal because these will need the HD3000 kexts activated back from High Sierra and the AppleMCCSControl.kexk from Catalina (all files can be found in the micropatcher iMac fork) to make sleep working

**Comment by Ausdauersportler** [comment]
forked your patcher and implemented it [here](https://github.com/Ausdauersportler/Opencore-Legacy-Patcher)

**Comment by khronokernel** [comment]
Added in main
