### ISSUE TITLE
The script to download macos doesn't work in el Capitan and older.

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#141]
**Describe the bug**
It gave the error: Could not find a default catalog url for this OS version.

**To Reproduce**
1. Type the script "mkdir ~/macOS-installer && cd ~/macOS-installer && curl -O https://raw.githubusercontent.com/munki/macadmin-scripts/main/installinstallmacos.py && sudo python installinstallmacos.py"
2. See error

**Build Folder**
Not relative

**Hardware:**
 - OS Running (ie. macOS 10.11.6, El Capitan)
 - OS Patching (ie. macOS 11.2.3, Big Sur) (not relative)
 - Model Patching (ie. MacBook5,1)

I suggest to add GibMacOS support in the guide

(More infos [here](https://github.com/munki/macadmin-scripts/issues/85))

**Comment by khronokernel** [comment]
GibMacOS has been known to give botched Big Sur installers, more specifically with signature issues. We had the same issue on OCLP and had to switch to cURL to avoid breaking the files. Unfortunately it's very hit or miss regarding this signature bug so for most users GibMacOS may work, however I'd rather not write guides for multiple tools when only 1 is required. Can add a comment in the guide to use the `--catalogurl` as the author offered

Potentially we may offer macOS download support in OCLP in the future to avoid the reliance on other tools as well as simplify the experience of the end-user experience. Not top priority however. CC @dhinakg

**Comment by tiziodcaio** [comment]
Thx
