### ISSUE TITLE
Upgraded BCM94322 in iMac8,1 producing incorrect build

### ISSUE THREAD

**Issue by wim1732** [dortania/OpenCore-Legacy-Patcher#142]
On build - Detected Wifi Card: 14E4:432B

However build produced configuration with IO80211ElCap.kext, should be IO80211Mojave.kext.

Checked in "build.py", checks for wifi_vendor should be "14E4" not "E414" as bytes swapped.

Having changed now produces correct build.

**Comment by khronokernel** [comment]
Ah thank you for reporting! Will fix that shortly
