### ISSUE TITLE
Big Sur install freezing open core 0.0.22 and macOS_11.2.1-20D75

### ISSUE THREAD

**Issue by shanekarl** [dortania/OpenCore-Legacy-Patcher#144]
**Describe the bug**
The Big Sur installer is freezing when it starts to boot on Mac Pro 3,1 w/ NVIDIA GeForce GTX 680 2 GB graphics card. I am installing Install_macOS_11.2.1-20D75 w/ OpenCore version 0.0.22

**To Reproduce**
Boot SanDisk flash drive (loaded with bigsur and open core patcher) by holding down option key - select EFI boot, select install macOS Big Sur, screen changes to apple with progress bar and freezes.

**Screenshots**
![IMG_7003](https://user-images.githubusercontent.com/82462284/114581675-88661500-9c45-11eb-88b4-ed6517e62f17.jpg)
![IMG_7004](https://user-images.githubusercontent.com/82462284/114581699-8dc35f80-9c45-11eb-9515-be0619812103.jpg)
![IMG_7005](https://user-images.githubusercontent.com/82462284/114581708-8f8d2300-9c45-11eb-8794-4fbf2648ff96.jpg)

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (Catalina 10.15.7 - loaded using DosDude patcher)
 - Model Patching (ie. MacPro3,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

[Shane’s Mac Pro.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6305032/Shane.s.Mac.Pro.zip)

**Additional context**

**Comment by khronokernel** [comment]
Hello, what happens when you enable verbose booting as described in the debugging section of the guide? This should help show where there may be an issue

https://dortania.github.io/OpenCore-Legacy-Patcher/DEBUG.html

Additionally, I see you're using the stock Bluetooth card. Do know that currently the stock bluetooth module us unsupported in Big Sur as mentioned here:

https://dortania.github.io/OpenCore-Legacy-Patcher/MODELS.html

We recommend removing the card and testing again

**Comment by shanekarl** [comment]
I pulled the bluetooth card and got much further....

I ran a new IORegistryExplorer from Catalina before wiping the drive and starting the installer attached here:

[Shane’s Mac Pro 2-0.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6306437/Shane.s.Mac.Pro.2-0.zip)

Whats weird now is when I get into the installer and go into disk utility to format my drive for a clean install, i see two copies of the same drive, see screenshots. I only have a single 512 SSD in the system so there are not two drives.

![IMG_7016](https://user-images.githubusercontent.com/82462284/114614437-1b18ab00-9c6a-11eb-9baf-cccecbb53692.jpg)
![IMG_7017](https://user-images.githubusercontent.com/82462284/114614447-1f44c880-9c6a-11eb-8030-0734788c8a26.jpg)

After running the install on either of the two drives (same drive) and rebooting I no longer have a choice to boot to the HardDrive. If i boot to the install os big sur, it starts the install from scratch. If i boot to EFI a startup.nsh script runs so fast i can't take a photo then i get the following screen:

![IMG_7020](https://user-images.githubusercontent.com/82462284/114614743-85315000-9c6a-11eb-9c59-1f746c208a46.jpg)
![IMG_7022](https://user-images.githubusercontent.com/82462284/114614755-88c4d700-9c6a-11eb-8306-068a84b9d2fa.jpg)

**Comment by shanekarl** [comment]
Just one additional update... I reinstalled Catalina and tried an upgrade v/ wiping the drive and at the end of the install I had the same issue where it will not boot.

**Comment by shanekarl** [comment]
I solved the issue.... When upgrading from Cataina or installing from scratch my Mac Pro 3,1 could not boot apfs drives.

I downloaded the dosdude1 apfs rom patcher and after that I was able to run the install and boot afterwords.
