### ISSUE TITLE
Fix of "Cleaning" and EFI's unmount added

### ISSUE THREAD

**Issue by OKonnel** [dortania/OpenCore-Legacy-Patcher#145]
Dear Khronokernel and friends, I corrected a problem in the "Build.py" file, but I am afraid to modify the file in Github because I don't know if I am authorized to do so and for the sake of fair play I want to warn. This is my first time participating in development, even though I'm not a Developer and don't know Phyton. If I was not supposed to participate and/or I am wrong, I hope you will understand and you will not want me badly, as I operated to help the Community and I have dedicated my time.

So! Today I realized that the "dot_clean" command did not work (the "._.duplicate" files remain, as can see opening EFI partition in Terminal)  until I removed the two quotes that was before and after the braces of '{mount_path}' in the "Build.py" file.

After verifying that works, I realized that the EFI partition remains mounted and therefore, by transferring the Build EFI also to my another device (the SD Card in the iMac SD slot), the "dot_clean" command not works. A 2nd or 3rd partition, etc., in fact, will be called "EFI\ 1, EFI\ 2, EFI\ 3, ecc.
I also made sure that after the "dot_clean" command the EFI partition immediately unmounted and that the OCLP interface provided also this info. So, I introduced also a new command (to unmount the EFI) that I attach here. .
All everything works correctly now and the "dot_clean" command always will work, also if you want to transfer the EFI build to another disk partition, since different EFI will never be mounted at the same time in /Volumes (and on Desktop).

Regardless, I think it's not okay, for the newbies, to see EFI partitions on Desktop, as they could cause harm. For the more experienced, however, when necessary, just issue the command `sudo diskutil mount disk0s1` or other disk name acknowledged with "diskutil list".

 Below is the fix and addition I made and which I suggest to include in the file.

`print("- Cleaning install location")`
`subprocess.run(f"dot_clean {mount_path}".split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)`
`print("- Unmounting EFI partition")`
`subprocess.run(f"diskutil umount {mount_path}".split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)`
`print("- OpenCore transfer complete")`

**Comment by khronokernel** [comment]
Seems reasonable with me, thanks for the fixes! Will add them shortly
