### ISSUE TITLE
Requirements for implementing a GUI

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#146]
With OCLP, to add a GUI we'd like to have it operate separately from the patcher itself and instead call the program when required. To do so, the patcher will need to be adjusted to support command line arguments correctly.

## Patcher Requirements

* [x] Support command line args
  * [x] `--build`: Build OpenCore
    * `--model xxxx`: override default model detection
      * ex: `--model iMac11,2`
    * `--metal_gpu xxxx`: override default GPU detection (ie. Nvidia, AMD)
      * ex: `--metal_gpu Nvidia` 
    * `--smbios_spoof xxxx`: set spoofing mode (ie. minimal, moderate, advanced)
      * ex: `--smbios_spoof Moderate` 
    * `--verbose`: enable verbose booting
    * `--debug_oc`: enable debug OpenCore
    * `--debug_kext`: enable debug kexts
    * `--skip_wifi`: skip wifi patch
    * `--hide_picker`: hide OpenCore's picker
    * `--disable_sip`: disables SIP
    * `--disable_smb`: disables SecureBootModel
    * `--vault`: enable OpenCore vaulting
  * [x] `--patch_sys_vol`: patches root volume with detected hardware
    * `--custom_repo xxxx`: Sets custom repo for volume patches
      * ex: `--custom_repo https://github.com/dortania/Apple-Binaries-OCLP/archive/refs/heads/main.zip` 
* [x] Support same directory building with binary
  * Current implementation builds in a randomized var folder on each run, making difficult to work with external programs

## GUI Requirements

* [ ] Pass command line args to binary
  * Patcher binary to be located under `OpenCore-Patcher.app/Contents/Resources/Opencore-Patcher`
  * Build folder for OCLP binaries will be under `OpenCore-Patcher.app/Contents/Resources/Build-Folder/OpenCore-RELEASE`(or DEBUG if DEBUG build was set)
* [ ] List disks with FAT32 partitions to install OpenCore onto
* [ ] Detect SMBIOS model and allow override
  * Requires detection of OpenCore as well
    * `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product`

**Comment by khronokernel** [comment]
# Concept Designs for GUI

## Program Start

<img width="919" alt="Screen Shot 2021-04-13 at 3 55 12 PM" src="https://user-images.githubusercontent.com/48863253/114626240-a5fca400-9c70-11eb-9a46-2a2e89c5ed3a.png">

## Settings screen

<img width="633" alt="Screen Shot 2021-04-13 at 3 44 11 PM" src="https://user-images.githubusercontent.com/48863253/114626457-fb38b580-9c70-11eb-8af3-b087d08035f1.png">


## Build then install screen

<img width="633" alt="Screen Shot 2021-04-13 at 3 44 34 PM" src="https://user-images.githubusercontent.com/48863253/114626507-0d1a5880-9c71-11eb-8a1a-08303e4df231.png">

<img width="701" alt="Screen Shot 2021-04-13 at 3 44 40 PM" src="https://user-images.githubusercontent.com/48863253/114626528-15729380-9c71-11eb-8fbc-78651e1a84fa.png">

**Comment by AlexSakha** [comment]
👍😊
