### ISSUE TITLE
Infinite booting into recovery mode

### ISSUE THREAD

**Issue by BertNase** [dortania/OpenCore-Legacy-Patcher#148]
I use an Late 2013 Mac 14,2 (currenty running Big Sur 11.2.3 patched with micropatcher 0.5.1). Tried to move over to open core by using OCLP 0.0.22. Patched the stick using OCLP and used as in description and prepared an external SSD for test installation. After booting into the stick, selecting EFI and after reboot going to "Install Big Sur".  After that it came up again into recovery mode and has installed Yosemite on the external SSD. This runs in a loop. 

I tried to do NVRAM reset, uninstall open core and start over again but I'm ending in a loop again. That means, the info in the troubleshooting guide doesn't work.

**Comment by khronokernel** [comment]
Recovery mode occurs when the signature of any drive booted through OpenCore is broken. We require signature verification to support delta updates however this means booting OSes where the signature may have been broken will redirect the machine to boot the first recovery partition detected. 

This means while installing, you must've booted an OS with a broken signature or your preboot volume has broken signatures within it. This issue would result exactly the same on a supported Mac, and therefore is expected. 

Are you sure that you were only booting into drives with clean signatures? ie. Only OpenCore, the macOS Installer and the external SSD?

**Comment by BertNase** [comment]
Thanx khronokernel. To be honest I don't know what broken signature means. How can I check for it?

I booted my unsupported Mac which has Big Sur 11.2.3 with micropatcher 0.5.1 installed. I formatted the USB stick and created the bootable USB stick with same Big Sur 11.2.3 installer I have on my mac. The SSD to which I tried to install is brand new and also formatted as it should. Installed OC on the USB stick and booted the stick then. Started the EFI and afterwards the Big Sur installer. That's all.

Really no idea where something could be broken here.

**Comment by tahitibub** [comment]
FYI, I had the same issue but I managed to resolve it zapping the PRAM at each boot.

**Comment by igarsol** [comment]
I also have the same issue. PRAM reset does not work for me, to resolve it then i switch to OCLP 0.1.0 (clean installation in new partition) and tested OTA from BigSur 11.2.3 to 11.3.0.
iMac 12,2 with upgraded GPU K3100m.
Thank you to all  OLCP TEAM for this hard work!! Now testing, everything works fine!!
