### ISSUE TITLE
MacBook5,1 ioreg

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#149]
As said [here](https://dortania.github.io/OpenCore-Legacy-Patcher/DONATE.html), I give to you my ioreg file (MacBook5,1; ssd changed; ram upgrade to 8 gb)
[MacBook5,1.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6311104/MacBook5.1.zip)

**Comment by khronokernel** [comment]
Awesome thank you! Really appreciate these dumps

**Comment by tiziodcaio** [comment]
ehi @khronokernel what about adding me to the [donate](https://dortania.github.io/OpenCore-Legacy-Patcher/DONATE.html) page??? Now I will test the GPU patches

**Comment by tiziodcaio** [comment]
good evening
