### ISSUE TITLE
MacBookPro10,1 semi-bricked during 11.1 beta 2 upgrade

### ISSUE THREAD

**Issue by traviswparker** [dortania/Opencore-Legacy-Patcher#15]
This has happened twice now, so I can confirm it is the 11.1 beta 2 update causing it:

Mid-2012 Retina MBP 15" (MacBookPro10,1). Erased and installed Big Sur 11.0.1 GM using OpenCore.

I received the macOS 11.1 beta 2 update and installed it. During the update process, an Apple logo with a progress bar appears. At about 25% the MacBook shuts down and will not start back up. Pressing the power key causes fan spin but I get no chime or backlight. It will power off if I hold the power key, but the machine will not POST. 

I tried NVRAM clear, SMC reset, and SMC bypass, no good. The only way I could get it out of this state was to take the bottom off and disconnect the battery. Seems like the 11.1 beta 2 sees the SMBIOS reporting MacBookPro11,2 and tries something it should not do. My guess would be attempting a firmware update or perhaps an RTC issue as disconnecting the battery clears it up. Once it boots, it completes the update and runs 11.1 beta 2 fine.... but if you don't have the proper pentalobe bit, you are in trouble.

I previously upgraded from 11.0.1 to 11.1 beta 1 using OpenCore and did not encounter this problem.

**Comment by ustalo** [comment]
I have MBP Mid 2012 11.1 Beta (20C5061b) instal with barrykn / big-sur-micropatcher
![Screenshot 2020-12-08 at 09 15 46](https://user-images.githubusercontent.com/16178306/101447291-f9af5780-3935-11eb-9b17-9804bd3e2bc3.png)

**Comment by traviswparker** [comment]
Yes if you create an installer, boot from that and do an in-place reinstall it won’t attempt any kind of firmware update. However, OTA upgrades may not be safe. 

Apparently the 11.0 release was completely bricking some supported 13” 2013/2014 MBPs, so Apple released 11.0.1 to block those models from getting the update. It is possible the 11.1 betas are trying to update firmware to fix that and failing on a spoofed MacBookPro11,2

**Comment by BenSova** [comment]
That's been the thing with Open Core since the start. macOS 11.0.1b1 proposed the same challenge when the new boot chime, and it semi-bricked a couple of Macs that used Open Core. I thought khronokernel fixed this though. Maybe not.

**Comment by traviswparker** [comment]
Update: booting from the 11.1b2 installer and doing an upgrade will cause it too. Seems to be an issue triggered by the boardID OpenCore is spoofing.

**Comment by dhinakg** [comment]
Hi, can you rebuild your EFI using 0.6.4 and then set BlacklistAppleUpdate to true in the config.plist? This issue is probably because we have it set to false for some reason

**Comment by traviswparker** [comment]
Yeah I’ll try that tomorrow.

**Comment by traviswparker** [comment]
Nope. Didn’t block it. Had to disconnect battery again. Whatever it tries to do, it does it from the running OS, not from EFI. 

I’m just gonna leave the screws out... It has magnets holding the bottom on anyway.

**Comment by traviswparker** [comment]
Well that’s interesting. The first time I tried the update to 11.1 RC, it still soft-bricked. After disconnecting/reconnecting the battery and powering back up, it acted like it was going through the OTA process but apparently failed. 

Software Update said an update was still available. It downloaded and applied it again... this time there was no soft-brick and the update process seems to be doing a lot more (based on the verbose boot output)

**Comment by mreckhof** [comment]
If you need any confirmations of fix, I went to 11.1 fine after running patcher 0.0.7 on MacBookPro10,1.

**Comment by Bustycat** [comment]
This happened to my MacBookPro9,2 too when installing macOS 11.1 (20C69) with OpenCore 0.6.4 made by Legacy Patcher 0.0.7.

**Comment by traviswparker** [comment]
I’m erasing my MacBookPro10,1 and trying a fresh install using an OpenCore build from main. 

So far no soft-brick. It may hang, but after a hard power off it boots and continues the install.

**Comment by Bustycat** [comment]
Saw a workaround on Mac Rumors as injecting BIOSVersion as 999.0.0.0.0. Would the patcher developers test further and consider it?

**Comment by stonegray** [comment]
> Saw a [workaround](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29425353) on Mac Rumors as injecting BIOSVersion to 999.0.0.0.0. Would the patcher developers test further and consider it?

This seems like a reasonable solution. I'm going to start playing with this and see what happens.
