### ISSUE TITLE
Default settings of OCLP depending of the device

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#152]
It's possible to disable SIP and SecureBootModel by default in the macs which need video/(audio) patches?

**Comment by khronokernel** [comment]
Based on previous user data, people preferred having OTA updates over audio patches. This was our main reason (up to now) for enabling SIP, etc by default on all configurations. We did add brightness control support in 0.0.23 however we doubt the overall sentiment changes tbh as overall usage is still quite unappealing.

Internally we always had the plan to only disable SIP, etc by default once accel patches are public. So unless user demand changes towards wanting brightness control over delta updates, we'll be keeping the system as-is.

Ofc this is not set in stone, this can be easily changed in the future

**Comment by khronokernel** [comment]
Decided to ask up front in the community:
https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29779425

Will decide what our plans are for 0.0.23's release

**Comment by tiziodcaio** [comment]
Yes, this was a low priority suggestion... Make as you wish
