### ISSUE TITLE
MacPro 5,1, cannot enable FileVault

### ISSUE THREAD

**Issue by wladkolc** [dortania/OpenCore-Legacy-Patcher#153]
**Describe the bug**
Cannot enable FileVault2, I have using OCLP 0.0.22 with BigSur 11.2.3. 

ERROR:
FileVault Failed, Incorrect password

**To Reproduce**
1. Installed OpenCore Legacy Patcher to NVM EFI disk0s1
2. Clean install BigSur 11.2.3
3. Enable FileVault

**Hardware (please complete the following information):**
 - OS running macOS 11.2.3, Big Sur
 - OS patching macOS 11.2.3, Big Sur
 - Model Patching MacPro5,1
 
**Additional context**
Related error in console:
error	09:58:45.652790+0200	efilogin-helper	Invalid display 0x00000000
error	09:58:46.203202+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14520. Result: (114, 92, 152)
error	09:58:46.244195+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14641. Result: (255, 127, 106)
error	09:58:46.244352+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14641. Result: (255, 202, 181)
error	09:58:46.297707+0200	efilogin-helper	[_syrah_soundResourcesOperations_block_invoke:1297]: _ScreenReaderGetEFIAudioFileData returned empty data
error	09:58:47.549751+0200	efilogin-helper	[_resourcesFromCompletedOperations:1894]: ERROR: sound data is missing !
error	09:58:47.824125+0200	diskmanagementd	[openEFILConnection_block_invoke_2:136]: Connection invalidated

**Comment by khronokernel** [comment]
Hello, your issue is a little confusing with the little information provided. Can you elaborate more on exact steps taken? For example, did you enable FileVault during user setup or did you manually go into settings? Additionally, you say you couldn't enable FileVault however you got an incorrect password error. So did you enable FileVault and was unable to sign in or are you referring to a different step?

**Comment by wladkolc** [comment]
Hi, there is no offer during clean installation. Only enable after installation throught settings -> security icon -> filevault tab -> turn in filevault -> create recovery key and do not use my icloud account (both choices results same output) -> continue and waiting. Output is error window with filevault failed, incorrect password. Iam not entering any password before, only one to unlock one to change settings. It is same as login and operating system accept it.

**Comment by vit9696** [comment]
`_ScreenReaderGetEFIAudioFileData returned empty data` ← this sounds like an issue with macOS installation.

**Comment by wladkolc** [comment]
i have downloaded installation from appstore and created bootable installer with createinstallmedia command.

**Comment by khronokernel** [comment]
> this sounds like an issue with macOS installation.

Agreed, reinstall macOS with a clean install and run again with no extra user data transferred over

**Comment by wladkolc** [comment]
I have downloaded new installation with macadmin scripts, downloaded latest OCLP 0.10 and made clean install. Now there are new errors.

error	13:27:57.556483+0200	diskmanagementd	[openEFILConnection_block_invoke_2:136]: Connection invalidated
error	13:27:59.847368+0200	efilogin-helper	0 is not a valid connection ID.
error	13:27:59.848284+0200	efilogin-helper	Connection to 'pboard' server had an error: <dictionary: 0x7fff800735e0> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7fff80073748> { length = 18, contents = "Connection invalid" }
}
error	13:27:59.848387+0200	efilogin-helper	Failed to set up CFPasteboardRef 'DefaultAsciiKeyboardLayoutPasteboard'. Error: <dictionary: 0x7fff800735e0> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7fff80073748> { length = 18, contents = "Connection invalid" }
}
error	13:28:00.484379+0200	efilogin-helper	Invalid display 0x00000000
error	13:28:05.639092+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14520. Result: (114, 92, 152)
error	13:28:05.671467+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14641. Result: (255, 127, 106)
error	13:28:05.671586+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14641. Result: (255, 202, 181)
error	13:28:05.716514+0200	efilogin-helper	[_syrah_soundResourcesOperations_block_invoke:1297]: _ScreenReaderGetEFIAudioFileData returned empty data
error	13:28:06.962073+0200	efilogin-helper	[_resourcesFromCompletedOperations:1894]: ERROR: sound data is missing !
error	13:28:07.223057+0200	diskmanagementd	[openEFILConnection_block_invoke_2:136]: Connection invalidated

**Comment by wladkolc** [comment]
now i have tried to download older version of bigsur, but it looks same...then this issue is not resolved yet...

**Comment by vit9696** [comment]
Does anything change with different kind of spoofing? Does FV2 work on Catalina/Mojave?

**Comment by khronokernel** [comment]
@wladkolc Could you elaborate more on the hardware used? ie. SSDs and other drives installed as well as any other non-stock upgrades done to the machine?

Regarding testing other SMBIOS, you can switch to full SMBIOS spoofing via OpenCore Legacy Patcher's `"Patcher Settings" -> "Set SMBIOS Mode" -> "Moderate"`. Then rebuild OpenCore and install onto a USB to easily boot without modifying the internal drive's ESP

Additionally, another common SMBIOS used in the community was iMacPro1,1. You can try the below build as well to see if this resolves the issue. I also provided one last build with serials being spoofed in case Apple does have issue using the original MacPro5,1 serials
* [OpenCore-iMP11-CustomSerial.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6343845/OpenCore-iMP11-CustomSerial.zip)

* [OpenCore-iMP11.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6343829/OpenCore-iMP11.zip)

**Comment by wladkolc** [comment]
No, different spoofing results same output. Previously I had Catalina installed on NVMe, but now when i try to install it to NVMe it shows be, that Catalina cannot be installed on this drive. FileVault last worked on High Sierra, cause of non native GPU, macOS not allowed me to enable FileVault on Catalina/Mojave...OK, I will try @khronokernel recommendations. I have one internal HDD with OCLP installed and one Corsair 1TB NVMe in PCIe raid slot inserted.

**Comment by khronokernel** [comment]
@wladkolc Non-native GPU? Again, could you please elaborate on the hardware installed? ie. model of SSDs, GPUs installed, wifi cards upgraded, etc

We cannot make proper decisions without a full picture on what's being worked on

**Comment by wladkolc** [comment]
Not helped, with moderate spoofing and iMP11 package is same result.

MacPro (Mid 2012)
6-Core Intel Xeon 3,33GHz
24GB 1066 DDR3
Asus Radeon RX 5500 XT 8GB ( I have old Apple 5890 for booting)
Corsair Force MP510 1TB installed Big Sur in PCIe 4x slot on small board
Hitachi 1TB HDD OCLP installed and data partitions for backup
WIFI card was not changed (AirPort Extreme  (0x14E4, 0x8E))
added USB 3.0 host controller VEN 0x1912 DEV 0x0014

Thanks you

**Comment by khronokernel** [comment]
> ( I have old Apple 5890 for booting)

Are you able to remove the 5890? The machine should still auto boot Big Sur

If this works, we can add some extra checks in OCLP to disable unsupported GPUs once booted

**Comment by wladkolc** [comment]
Sorry, my bad explanation. I have 5890 removed and inserting it only when i need to repair boot. I have Asus Radeon 5500XT in machine. Only this one

**Comment by cdf** [comment]
In response to @vit9696's inquiry off thread: I've tested FileVault on the Mac Pro 5,1 both in Catalina and Big Sur. No issues. This is with hybridization (board ID only) spoofing, which we've been using over on [MacRumors](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/) with much success for quite some time. I believe OCLP now also offers a similar configuration.

**Comment by khronokernel** [comment]
> I believe OCLP now also offers a similar configuration.

Correct, OCLP actually uses your hybrid approach by default (ie. only changing `BoardProduct`, `BID` and `BIOSVersion`) however this can be overrided in patcher settings to do full SMBIOS replacement (either with or without original serials)

**Comment by wladkolc** [comment]
Hi, I have tried again your package OpenCore-iMP11-CustomSerial.zip. Reinstalled clean Catalina, enabled FileVault, upgraded to Big Sur. Now Filevault is enabled and everything is working. Mac is acting as iMac Pro 2017. Can you tell me how can i create same package, when there will be update? I have tried to specify model as imacpro1,1 but, oclp choice build open core offer is gone. Maybe oclp-cli will do this work? Thank you.
