### ISSUE TITLE
"Trackpad is recognized as a mouse in MacBook5,1" isn't correct

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#155]
**Describe the bug**
I tried the OCLP 0.0.21 on my old MacBook5,1 (SBM and SIP disabled, no video patches yet), and it work perfectly.
Here some screenshots:

![Schermata 2021-04-17 alle 21 26 07](https://user-images.githubusercontent.com/61084118/115124737-16cef380-9fc4-11eb-8b73-7ea6066d64cb.png)
![Schermata 2021-04-17 alle 21 23 15](https://user-images.githubusercontent.com/61084118/115124738-19314d80-9fc4-11eb-905f-093404302b93.png)

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.11.6, El Capitan)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. MacBook5,1)

**Comment by khronokernel** [comment]
Ah thank you for verifying! Will update the docs accordingly
