### ISSUE TITLE
MacPro5,1, cannot enable FileVault not resolved after reinstallation of two versions.

### ISSUE THREAD

**Issue by wladkolc** [dortania/OpenCore-Legacy-Patcher#156]
I have downloaded new installation with macadmin scripts, downloaded latest OCLP 0.1.0 and made clean install. Now there are new errors.

error	13:27:57.556483+0200	diskmanagementd	[openEFILConnection_block_invoke_2:136]: Connection invalidated
error	13:27:59.847368+0200	efilogin-helper	0 is not a valid connection ID.
error	13:27:59.848284+0200	efilogin-helper	Connection to 'pboard' server had an error: <dictionary: 0x7fff800735e0> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7fff80073748> { length = 18, contents = "Connection invalid" }
}
error	13:27:59.848387+0200	efilogin-helper	Failed to set up CFPasteboardRef 'DefaultAsciiKeyboardLayoutPasteboard'. Error: <dictionary: 0x7fff800735e0> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7fff80073748> { length = 18, contents = "Connection invalid" }
}
error	13:28:00.484379+0200	efilogin-helper	Invalid display 0x00000000
error	13:28:05.639092+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14520. Result: (114, 92, 152)
error	13:28:05.671467+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14641. Result: (255, 127, 106)
error	13:28:05.671586+0200	efilogin-helper	[-[EFILuminantColorEngine copyColorForLocation:luminanceLevel:]:146]: Colors computed: 14641. Result: (255, 202, 181)
error	13:28:05.716514+0200	efilogin-helper	[_syrah_soundResourcesOperations_block_invoke:1297]: _ScreenReaderGetEFIAudioFileData returned empty data
error	13:28:06.962073+0200	efilogin-helper	[_resourcesFromCompletedOperations:1894]: ERROR: sound data is missing !
error	13:28:07.223057+0200	diskmanagementd	[openEFILConnection_block_invoke_2:136]: Connection invalidated

_Originally posted by @wladkolc in https://github.com/dortania/OpenCore-Legacy-Patcher/issues/153#issuecomment-822397139_

**Comment by khronokernel** [comment]
Please do not spam our issues tab with multiple issues...
If we find it's an issue with OCLP we will reopen your issue. We currently have other work to do so haven't looked heavily. We will reopen your issue when we have time and can verify it's an issue on our end. So please respect the repo and the developers involved, we do not need fragmentation of information

**Comment by wladkolc** [comment]
Sorry, dont know about these steps.. thanks a lot
