### ISSUE TITLE
Macmini5,1 connected to HDMI TV does not have sound through HDMI

### ISSUE THREAD

**Issue by ccabaleiro** [dortania/OpenCore-Legacy-Patcher#159]
Hi!

Great! I could have OpenCore installed and it is working quite well on my Macmini5,1 ! Good job!

One issue is that sound through HDMI is not an option in System Preferences / Sound / Output (see screen shot).

![Screen Shot 2021-04-20 at 19 10 44](https://user-images.githubusercontent.com/74385657/115470089-29d40480-a20c-11eb-9e11-0cf8bcbef58e.png)

Any suggestions to solve this issue?

Regards and thank you for providing more life to this (as Apple thinks) old machine !

**Comment by khronokernel** [comment]
Likely a limitation of the missing graphics acceleration, as of right now we do not have them public however we hope to have public betas somewhat soon
