### ISSUE TITLE
Bad spoofing iMac 14,2 to iMacPro1,1 instead iMac15,1 and consequent issues

### ISSUE THREAD

**Issue by OKonnel** [dortania/OpenCore-Legacy-Patcher#160]
Bad spoofing iMac 14,2 27’’ CPU i9 Quad Core 3,5 GHz - GTX 780M to iMacPro1,1 instead iMac15,1 and consequent issues.
Using the OCLP 0.1.1 this morning, I think I found the bug that caused DRM movies to crash on Apple TV (and perhaps Photo Booth malfunction as well).
The main OCLP window claims to recognise my iMac14,2 but, then as you can see from attached screenshots of Terminal and "config.plist", but OCLP:
**a)** spoofing my iMac14,2 into -> iMacPro1,1 (Mac -7BA5B2D9E42DDD94) instead of into -> iMac15,1 in "config.plist"
**b)** OCLP also adds a "dual GPU patch" as it detects an
"iGPU: 8086:0412"
"dGPU: 10DE:119E".
So, editing "config.plist" manually and spoofing to iMac 15.1 (Mac-42FD25EABCABB274), Apple TV works fine EVEN without adding "shikigva = 256" in DeviceProperties... And now perhaps the mystery of the Photo Booth malfunction is also revealed. The third attachment, in fact, shows that Photo Booth thinking it works with the Intel HD 5000 graphics card and make confusion about the Quartz's files effects and DRM or both. (In Safe Mode PB always works well).

Hope to be helpful, even though I don't understand why OCLP is wrong and I don't know how to fix the OCLP code to create a proper Mac's model spoofing and a correct recognition and settings of graphic card. "iMac 14.2 IORegistry.zip" also added in attach. [Useful clarification: with manual spoofing to iMac15,1 I tried to export a 4k H264 movie with Final Cut Pro and it worked fine, with OR without "shikigva = 256" added in DeviceProperties of “config.plist”]

![OCLP creating EFI Build](https://user-images.githubusercontent.com/81856309/115556244-c05a0180-a2b0-11eb-837a-8dca54f512cd.jpg)
![OCLP bad spoofing](https://user-images.githubusercontent.com/81856309/115556251-c4861f00-a2b0-11eb-9be2-c3426039cde6.jpg)
[Photo Booth monitoring.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6350887/Photo.Booth.monitoring.txt)
[iMac 14.2 IORegistry.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6350917/iMac.14.2.IORegistry.zip)

**Comment by khronokernel** [comment]
Fixed the issue regarding the incorrect print statements and incorrect SMBIOS, however it seems you forgot to go into Patcher Settings and enable DRM support. It's disabled by default and opts for QuickSync support

Though saying that DRM works fine again with iMac15,1 actually goes against your previous comments in this issue: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/158

However if you're saying the latest OCLP with iMac15,1 is fine then the latest commit should work for you without requiring the DRM Patches enabled:
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/e3e9be01a257eedfd0bed494dd07a7e3f9859666
