### ISSUE TITLE
Black screen after waking up on iMac11,3 (K3100M) + immediately after OS loaded (K610M)

### ISSUE THREAD

**Issue by campodit** [dortania/OpenCore-Legacy-Patcher#162]
**Describe the bug**

K3100M:
Black screen after waking up even with "sudo pmset -a hibernatemode 0"
No external display -> solved by adding agdpmod=vit9696 in boot-args

K610M:
Black screen immediately after OS loaded (only mouse pointer)

**To Reproduce**

Installed OpenCore Legacy Patcher to EFI disk0s1
Clean install BigSur 11.2.3
Patcher settings -> Force Nvidia

**Build Folder**
OpenCore Build with OCLP 0.1.1

**Hardware:**
OS running macOS 11.2.3, Big Sur
OS patching macOS 11.2.3, Big Sur
Model Patching iMac11,3
 - K3100M_V3 by nikey22
 - K610M by nikey22

[Archive.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6353318/Archive.zip)

**Comment by Ausdauersportler** [comment]
Solution has been described here:

https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/post-28406927

**Comment by campodit** [comment]
Hi, thank you for your answer,
Do you advise to modify/replace the kext or to inject it through OpenCore?

**Comment by Ausdauersportler** [comment]
Neither way. I would try to set and test apdpmod=pikera as mentioned in the post on the first lines. 
You can always prevent the black screen (on boot)  by pressing alt/option on boot on 11,3 and 12,x. 

About reporting a black screen (this is alway a little bit vague):
Can you set screen sharing to true and try to login remotely to check what is really broken (the screen or something different more severe). 

Writing back from iMac11,1 (with aggpmod=vit9696) without any of your problems, except a black screen after a PRAM reset, external screen is working all the time. (You may also have a broken GPU, not the correct BIOS fitting to the VRAM type etc. Can you prove somehow your hardware is working properly with a different macOS version?)

**Comment by campodit** [comment]
Ok so I did some tests,
The GPU K610M works because I can boot on high sierra with and without OCLP
I always use the alt on boot for K610M because I know there is a delay for the boot-screen initialization with mod rom by nick
The iMac11,3 however boots with WX4130 under OCLP Big Sur (Force AMD patcher settings) and works fine, exit from standby after suspending activity ok.
I have the same problem with iMac11,1 :
K610M -> Black screen immediately after OS loaded
I had already tried apdpmod=pikera and it doesn't change anything
Bootrom is up to date

**Comment by Ausdauersportler** [comment]
iMac 11,1 needs agpdmod=vit9696 to overcome the black screen after a PRAM reset. The internal LCD will come up really late than. iMac11,1 have a total eclipse after PRAM reset, i.e. the screen does not come back until using a poached AGC or the vit9696 setting with OC (at least according to my own test with an K5000M in an iMac11,1).

Before you wrote about problems with the K610M in an iMac11,3. These two systems behave really different when it comes to this particular problem. 

Sorry, but you need to be really precise when expecting fitting answers. So please describe exactly which behavior you experience when using which card in which system.

AMD cards do not have those problems. It is only visible with NVIDIA cards in iMac11,x and 12,x.

**Comment by khronokernel** [comment]
Forgot to mention I fixed this:
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/797b56b9f957c182dc2ba2c0e45101e12f6500b2

@Ausdauersportler Besides iMac11,1+Nvidia with agdpmod=vit9696, is there any other models/GPU combinationsthat would benefit from the boot-arg?

**Comment by khronokernel** [comment]
Oh I realize I omitted iMac11,3, just pushed a fix for them

**Comment by Ausdauersportler** [comment]
Since the adaption of OCLP accelerates I have asked exactly this question on the forum thread and I am waiting for answers. 
Just assuming that all iMac11.x and iMac12,x using an NVIDIA card would need it. I am wondering that we had no complaints about that before, this was one of the most prominent problems for people after the GPU change even with Sierra and High Sierra.

**Comment by campodit** [comment]
I don't know if this can interest you but when I do a clean install of my iMac11,3 (bootable key 11.2.3 + last OCLP 0.1.1 build + vit9696 fix) with K3100M (end of install ok, no black screen problem) and then directly switch the K3100M with K610M, I get black screen and vice versa : clean install with K610M inside -> Ok, I reinstall directly the K3100M without modifying system and OCLP -> black screen with mouse pointer... it's probably normal because of the agdp ?
So my initial black screen problem with the K610M was not really a problem.. I did a clean install K610M inside the iMac to solve it.

However the problem of waking up after clicking on "suspend activity" is still there with the K3100M
With the K610M, everything works fine
I tested several rom K3100M (BFR, V3 V4 by nikey22) but it doesn't change anything

**Comment by Ausdauersportler** [comment]
After changing the GPU do a PRAM reset in any case to clear things up. Check if you get a black screen then.

**Comment by campodit** [comment]
Done, including in the OC boot picker (space bar -> reset nvram)

**Comment by campodit** [comment]
Interchanging card on same system and OCLP (K3100M in iMac during clean install) :
K3100M / k3000M / GTX 880M —> Ok
K610M —> black screen

For out of sleep problem (even with sudo pmset -a hibernatemode 0)
I’ve tested K3100M —> black screen 
GTX 880M —> black screen
K3000M —> Ok
K610M —> Ok

**Comment by Ausdauersportler** [comment]
1. About the GPU change:
This „use-case“ is of no interest at all. No normal user will install a macOS version and change a GPU afterwards and then wondering that the system is not really working. 

2. About sleep problems
I owned (or simply had it in my hands) and tested through the last 12 month nearly every NVIDIA and every AMD GPU installable and listed on the iMac GPU thread. Unfortunately after nearly 10 years of life in a gaming laptop some of these card may simply be partly damaged. Unless you can prove that your cards do generate a black screen in a different system under the same conditions (is it a 11,3 or 11,1 after all) while the same type of card works normally for other users (and I would strongly assume this because we would be drown in „sleep is broken“ messages) I would stop any further investigation of your (highly probable) hardware problems now.

**Comment by internetzel** [comment]
agdpmod=vit9696 is causing black backlit macOS screen on my iMac11,1 in Catalina only - it's working normally in Mojave and Big Sur. I've got an AMD RX480 graphics card installed in that machine.
No displays (internal or external) are recognized in Catalina when agdpmod=vit9696 is set.
I'm using OCLP 0.1.1 .

**Comment by Ausdauersportler** [comment]
Note form the former patcher development: This setting (AGC patch) should only be applied when using an NVIDIA GPU.
