### ISSUE TITLE
Tips to fix the Build.py file for proper operation using the DRM option with 14,2 iMacs

### ISSUE THREAD

**Issue by OKonnel** [dortania/OpenCore-Legacy-Patcher#164]
I am attaching here my fixes for "Build.py" regarding the DRM support (in order to view purchased movies on Apple TV and more).
The addition "shikigva = 256" in DeviceProperties is correct, but spoofing to iMacPro1,1 is not. (Note: Khronokernel attached a correct "config.plist" zipped to my first issue report about, and left a correct spoofing on iMac15,1 as can see in that file [.](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/158#issuecomment-823280130) It was thanks to this file if I understood and fixed the issue.)
As can see in my modified code, I have also completed the info that appears during the creation of the Build when activating the DRMs option.
Yesterday and today I did a lot of tests; with Final Cut Pro I had no problems exporting with H264 Codecs and also with other Codecs; Videoproc Test recognizes well hardware acceleration; Photoshop also recognizes the acceleration and the VDA DecoderChecker utility says: "Hardware acceleration is fully supported".
[Now I will spend myself to looking for a way to make Photo Booth work too which in my opinion, given the fact that in Safe Mode it works very well, in normal mode not working because it uses acceleration's parts (Kext etc.) fotr Intel HD 5000 graphic card, as could appear examining its log. But if anyone has any suggestions on this problem, they can write me separately to give me some ideas which I will then experiment with until I find a solution...]

`# Check for upgraded GPUs on iMacs`
`if self.constants.drm_support is True:`
`	print("- Spoofing to iMac15,1 & NVIDIA DRM support")`
`	spoofed_model = "iMac15,1"`
`	spoofed_board = "Mac-42FD25EABCABB274"`
`else:`
`    print("- Spoofing to iMac15,1")`
`    spoofed_model = "iMac15,1"`
`      spoofed_board = "Mac-42FD25EABCABB274"`

[Build.py.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6357556/Build.py.zip)
![Building-0 1 1](https://user-images.githubusercontent.com/81856309/115701371-03c37700-a368-11eb-8fc3-71c8414679da.jpg)

**Comment by khronokernel** [comment]
```
# Check for upgraded GPUs on iMacs
if self.constants.drm_support is True:
print("- Spoofing to iMac15,1 & NVIDIA DRM support")
spoofed_model = "iMac15,1"
spoofed_board = "Mac-42FD25EABCABB274"
else:
print("- Spoofing to iMac15,1")
spoofed_model = "iMac15,1"
spoofed_board = "Mac-42FD25EABCABB274"
```

I fail to see why you would need a check in the first place then, as it's always iMac15,1.

Additionally, are you saying you required shikigva=256 with iMac15,1? This is an unsupported configuration that may break other parts of the OS unknowingly. The reason we set iMacPro1,1 is due to how Nvidia's decoder expects a dGPU only setup:

https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/kern_shiki.hpp#L79-L81

This does expose a flaw in how OCLP handles your GPU, so I just pushed a fix to disable the iGPU correctly
