### ISSUE TITLE
MacBookAir4,1 does not sleep, ever

### ISSUE THREAD

**Issue by ccabaleiro** [dortania/OpenCore-Legacy-Patcher#165]
MacBookAir4,1 with Big Sur working better than I expected, but it does not go to sleep, no matter if closing the lid or selecting Sleep at login page - the machine just ignores and continues on.

**Comment by khronokernel** [comment]
This is the current limitation of 0.1.0 due to missing acceleration, 0.1.1 has GPU acceleration for legacy GPUs

**Comment by ccabaleiro** [comment]
That will be great!  Any idea when 0.1.1 will be released?

Thanks!

**Comment by ccabaleiro** [comment]
> This is the current limitation of 0.1.0 due to missing acceleration, 0.1.1 has GPU acceleration for legacy GPUs

That will be great! Any idea when 0.1.1 will be released?

Thanks
