### ISSUE TITLE
Macbook Air 3,2 worth a try?

### ISSUE THREAD

**Issue by houser42** [dortania/OpenCore-Legacy-Patcher#174]
Hello,

I have a Macbook Air late 2010 3,2, It has  the NVIDIA GeForce 320M.
I assume if it not on the list it will not work but a quick question might be ok to ask?

Would be happy to give it a try if there is any chance in hell to breathe future into this old friend.
Any chance and point in giving it a go? Many thanks.

**Comment by khronokernel** [comment]
"Worth it" is subject to different opinions, I recommend discussing on forums or discords. This repo's issue tab should be dedicated to patcher issues or enhancements, less that of personal dilemmas

**Comment by Ausdauersportler** [comment]
Read the [docs](https://dortania.github.io/OpenCore-Legacy-Patcher/MODELS.html), try and report back on forum or discord channels.

**Comment by houser42** [comment]
Apologies.
I truly appreciate the work you guys do.
Not easy for a retired vet to know the appropriate channels and use of lingo at all times.
No need to reply to this, just wanted to apologize for the lack of etiquette right away.
