### ISSUE TITLE
iMac 8,1 early 2008 native el capitan 10.11.6 clean IOReg dump

### ISSUE THREAD

**Issue by NeutroGe** [dortania/OpenCore-Legacy-Patcher#175]
Please find the below attached IOREG dump as requested on support page:

[iMac 8,1 early 2008 native el capitan clean IOReg dump.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6395552/iMac.8.1.early.2008.native.el.capitan.clean.IOReg.dump.zip)

Thanks for all your great work!

**Comment by khronokernel** [comment]
Ah thank you so much! Really appreciate the IOReg
