### ISSUE TITLE
UUID has been changed + Impossible to access to the Discord server

### ISSUE THREAD

**Issue by tahitibub** [dortania/OpenCore-Legacy-Patcher#181]
**UUID change**
Hi,
I managed to install macOS BigSur on an old iMac8,1 thanks to OCLP 0.1.1.
Thank you for this fantastic boot loader !
However, I realized the patcher changed my iMac's UUID (also changed the model, the firmware version and the SMC version) which causes trouble to iCloud.
I checked the config.plist file on the EFI partition, but I didn't find the new UUID inside.
Is it possible to put the old UUID somewhere ?

**Access to discord server**
I don't manage to access the discord server (https://discord.gg/UbM8U75E).
Is there another link in order to access it ?

Many thanks
Regards

**Comment by Ausdauersportler** [comment]
The change of SMC and firmware version is intended to protect your system from getting unwanted updates. It uses a different SMBIOS to enable native installation of Big Sur. So all this can be rarely an issue.
When using the default (light) version of spoofing using you own serials your should have no iCloud issues other than your system type has changed. Every macOS version installed on your iMac generates it‘s own new UUID.  

You would have an iCloud issue IF you cannot connect any longer or Apple has banned your ID from accessing iCloud services at all.

The discord server link is no longer valid...though. The inviter has to send out an updated one.

**Comment by tahitibub** [comment]
Thank you very much for this explanation !
I'll close this (non) issue.
Regards
