### ISSUE TITLE
iMac 7,1 with upgraded CPU (T9300) stays at prohibited sign saying support.apple.com/mac/startup

### ISSUE THREAD

**Issue by imac71** [dortania/OpenCore-Legacy-Patcher#182]
Hi,
I tried to install Big Sur on my 2007 20inch iMac (7,1) with upgraded CPU (T9300) and 4GB of RAM.
OpenCore booted successfully but under Big Sur icon was NO NAME, so I clicked it and it showed apple logo, then it was loading, and finally prohibited sign showed up :(

Can somebody help?

The same Big Sur installer with different OC folder worked flawlessly on 2009 MBP.

Sorry for my bad English :/

**Comment by Ausdauersportler** [comment]
Sorry, this is not the user forum. Please join this [Discord server](https://discord.gg/rqdPgH8xSN) to get help.

**Comment by imac71** [comment]
Oh sorry.

**Comment by Ausdauersportler** [comment]
No, problem! Who knows, at the end this might become an issue. Please double check the [docs](https://dortania.github.io/OpenCore-Legacy-Patcher/). Just in case you missed a point.

**Comment by khronokernel** [comment]
This was resolved a week ago in 0.1.2

**Comment by imac71** [comment]
I can't see 0.1.2 version in releases..

**Comment by imac71** [comment]
On 0.1.2 same thing happens :(

**Comment by khronokernel** [comment]
@imac71 Please provide kernel panic info, ie. enable Verbose and Kext Debug in patcher settings, rebuild EFI and retry

Additionally you could attempt to remove the Bluetooth mule, that's know to be problematic on iMac7,1 and MacPro3,1

**Comment by imac71** [comment]
Wouldn't be a problem if verbose photo will by taken by phone?

**Comment by khronokernel** [comment]
That's alright with me, verbose panic should be displayed on screen with Kext Debug and Verbose modes enabled in Patcher Settings

**Comment by imac71** [comment]
uploading photos to google drive

**Comment by imac71** [comment]
https://drive.google.com/file/d/13Cj1ngtR-MQGEJ2YNxGM8NzgdLDykPct/view?usp=sharing

**Comment by imac71** [comment]
Can you review this photos, please?

**Comment by imac71** [comment]
?

**Comment by imac71** [comment]
?

**Comment by khronokernel** [comment]
Commenting "?" repeatedly does not speed up the process...
You are not the centre of attention and we have other work to do including our personal lives, see every other issue in the repo, we don't magically fix issues in an hour. So please, respect the developers involved. When we have time to investigate, we will

Final warning, repeated spam will result in this issue being locked

**Comment by imac71** [comment]
I’m really sorry, I was just too excited to run Big Sur on my iMac :(

**Comment by educovas** [comment]
Don't use 11.3 with the iMac, 11.3 is having some issues with booting and AMD GPUs. instead just use 11.2.3 and it should work.

**Comment by imac71** [comment]
Thank You Very Much, I will try it out tomorrow!

**Comment by khronokernel** [comment]
Oh assuming the iMac was on 11.3, this would be related to this issue:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/110
Closing as duplicate

**Comment by imac71** [comment]
11.2.3 does the same thing....

**Comment by imac71** [comment]
I will remove the Bluetooth module tomorrow, and I will let you know. Thanks!

**Comment by educovas** [comment]
You can try this OCLP before removing the Bluetooth module: https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2701544072/artifacts/59543888

It has a work-around for the Bluetooth issue and you can see if it changes something.

**Comment by imac71** [comment]
What should I do?

**Comment by educovas** [comment]
For now you just have to wait, the devs know about this issue and they are working on it. Because they don't have access to an iMac7,1, it's probably gonna take a while until this issue gets fixed.

**Comment by imac71** [comment]
Thanks for the reply!

**Comment by imac71** [comment]
Did 0.1.5 fix my iMac issue?

**Comment by educovas** [comment]
Probably not, but you can try it.

auto dark and light mode and Music app fullscreen are known issues.
auto dark mode never worked on non-metal IIRC

**Comment by imac71** [comment]
On 0.1.5 same thing happens, again..
Is there a 0.1.6 to try out?

**Comment by educovas** [comment]
No updates regarding this issue, it's probably not a priority because the devs don't have access to an iMac7,1 to fix it quickly so, it's probably gonna take some time.

**Comment by imac71** [comment]
Any news?

**Comment by Ausdauersportler** [comment]
The process will only work the other way around. The owners of hardware like yours would have to test each new version of OCLP (there are nightly builds available via Discord) and should report success. As @educovas pointed out no one owns an iMac7,1 to accelerate or test new developments. 

Your particular question does not accelerate the development here.

**Comment by imac71** [comment]
How about now?

**Comment by khronokernel** [comment]
I will be blunt, I will never fix this issue unless someone either does the research and presents findings on a fix or ships me an iMac to my front door to work on it myself. We have so many more important issues to work on including graphics acceleration, Monterey support, etc

Please respect us developers and stop being so childish expecting the world to revolve around you
