### ISSUE TITLE
Build Error on OCLP 0.1.2

### ISSUE THREAD

**Issue by Ivantroniks** [dortania/OpenCore-Legacy-Patcher#183]
**Describe the bug**
Hi...
If you build starting from OCLP 0.1.1 there is no problem, but if you build starting from OCLP 0.1.2 this happens ...

**To Reproduce**
Build starting from OCLP 0.1.2 

**Screenshots**

![Captura de Pantalla 2021-05-02 a la(s) 3 19 39 p m](https://user-images.githubusercontent.com/76612048/116828241-afd04380-ab5a-11eb-92fb-4b3258a451eb.png)

**Hardware (please complete the following information):**
 - OS Running- macOS 11.2.3
 - OS Patching -macOS 11.2.3
 - Model Patching MacPro3,1 with nvme card
...
 
This is a capture building starting from OCLP 0.1.1

![Captura de Pantalla 2021-05-02 a la(s) 3 32 38 p m](https://user-images.githubusercontent.com/76612048/116828451-038f5c80-ab5c-11eb-8a58-eca8b142ecdc.png)

**Comment by khronokernel** [comment]
@Ivantroniks Hello, could you upload an IOReg? File -> SaveAs:
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true

**Comment by Ivantroniks** [comment]
Sure
here it is

[Mac Pro 3,1.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6412282/Mac.Pro.3.1.zip)

**Comment by khronokernel** [comment]
So a bit confused, the second image you upload also have NVMe detection so it's clearly 0.1.2. So does OCLP only sometimes crash with 0.1.2?

**Comment by Ivantroniks** [comment]
Yes, it only fails if you build with the mac booting from OCLP 0.1.2
