### ISSUE TITLE
unable to determine current location at this time

### ISSUE THREAD

**Issue by ramram2000** [dortania/OpenCore-Legacy-Patcher#184]
after instal big sur 11.3 on my mid2012 mbp 10.1 , ( by open-core legacy patcher) 
location services unable to determine my current location.

its enable and many times i disabled and reenable it from setting/privacy&seurity... also i reseted NVRAM & PRAM many times... deleted and make new profile on mac network ...
on Catakina there was not this problem with my own home WiFi.

i read many forums about this trouble
most of them said this coz of my wifi problem

plz guide and help me  about this

thx sir

**Comment by khronokernel** [comment]
Cannot replicate on a MacBookPro9,2 with same wireless module. Can you go into macOs's System Report, Run File -> Save and send the output file?

Additionally, what region is your Mac currently set to? ie. Canada, USA, France, etc

**Comment by ramram2000** [comment]
i live in Iran (tehran)
but i selected USA in my region

i uploaded my system report as .spx in this link
https://filebin.net/qil3g4dc43250zzr

**Comment by khronokernel** [comment]
> Country Code:	US

I see your wireless card opted for US as well, you can set `brcmfx-country=XX` to change the country code to other regions. For Iran, I believe it's `IR`

So in your config.plist, open it up and look for boot-args. In the entry, add `brcmfx-country=IR` and reboot. Then check System Profiler -> Network -> Wifi and see if the country code correctly updated

If you're unfamiliar how to get your config.plist, you'll need to find the drive you install OpenCore on and mount it with [MountEFI](https://github.com/corpnewt/MountEFI). Then, go into EFI/OC/config.plist and edit from there

**Comment by ramram2000** [comment]
thx 
but im unfamiliar 
i found  EFI/OC/config.plist
help me how to add    
<img width="939" alt="Screen Shot 2021-05-03 at 23 49 26" src="https://user-images.githubusercontent.com/83423439/116922317-70911800-ac6a-11eb-96a6-73888c689430.png">
"brcmfx-country=IR"   in   boot-args

**Comment by ramram2000** [comment]
i linked my   EFI/OC/config.plist   here. 
plz open it and edit it and send me it again if you can. thanks you

https://filebin.net/5ttm8h6duw6bduaz

**Comment by Ribero** [comment]
I'm also interested of changing the country code.
There is another section where `boot-args` parameter appears:

```
<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
    <array>
        <string>boot-args</string>
    </array>
<key>FA4CE28D-B62F-4C99-9CC3-6815686E30F9</key>
```

But I'm not yet sure how to exactly add `brcmfx-country=COUNTRYCODE`. It also seems possible to replace the country code by `#a` to unlock all channels (but it looks like it disable DFS with some routers). I Still have to dig a bit.

**Comment by khronokernel** [comment]
@Ribero you want to change this section:
```xml
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>SystemAudioVolume</key>
				<data>
				Rg==
				</data>
				<key>boot-args</key>
				<string>keepsyms=1 debug=0x100</string>
				<key>csr-active-config</key>
				<data>
				AAAAAA==
				</data>
				<key>run-efi-updater</key>
				<string>No</string>
			</dict>
```
So `<string>keepsyms=1 debug=0x100</string>` becomes `<string>keepsyms=1 debug=0x100 brcmfx-country=COUNTRYCODE</string>`. I will add it to OCLP as end-user configurable at some point

**Comment by ramram2000** [comment]
> @Ribero you want to change this section:
> 
> ```
> 			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
> 			<dict>
> 				<key>SystemAudioVolume</key>
> 				<data>
> 				Rg==
> 				</data>
> 				<key>boot-args</key>
> 				<string>keepsyms=1 debug=0x100</string>
> 				<key>csr-active-config</key>
> 				<data>
> 				AAAAAA==
> 				</data>
> 				<key>run-efi-updater</key>
> 				<string>No</string>
> 			</dict>
> ```
> 
> So `<string>keepsyms=1 debug=0x100</string>` becomes `<string>keepsyms=1 debug=0x100 brcmfx-country=COUNTRYCODE</string>`. I will add it to OCLP as end-user configurable at some point

its great.thnks. it worked. i can changded my Wifi country code from us ...
but the point is , when i wanna chang to IR  ( Iran ) , its shows my location as unknow
but when i put X2 or X3 , it works ...

as you know i live in Iran. my location services in my mac still unable determine current location even the X2 or X3 country code...
