### ISSUE TITLE
MacBook Pro 5,4 15” mid 2009 no sound

### ISSUE THREAD

**Issue by MichaelFilipan** [dortania/OpenCore-Legacy-Patcher#185]
On the mid 2009 MacBook Pro 15” the sound does not work. In System Preferences the Mac shows no output device. Connecting headphones or speakers through the 3.5 mm jack also doesn’t work. Only way to get audio to work is through bluetooth, I tried with AirPods.

**Comment by khronokernel** [comment]
Send IOReg, File->SaveAs:
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true

**Comment by MichaelFilipan** [comment]
[MacBook Pro 15" mid 2009 .zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6416408/MacBook.Pro.15.mid.2009.zip)

**Comment by khronokernel** [comment]
Could you please upload from a native OS without OpenCore?

**Comment by MichaelFilipan** [comment]
[MacBook Pro 15" mid 2009  2.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6416454/MacBook.Pro.15.mid.2009.2.zip)

Is this better?

**Comment by khronokernel** [comment]
That's still running Big Sur through OpenCore
