### ISSUE TITLE
MacBook Pro 5,4 15” mid 2009 Keyboard Backlight

### ISSUE THREAD

**Issue by MichaelFilipan** [dortania/OpenCore-Legacy-Patcher#186]
On my mid 2009 MacBook Pro 15” the keyboard backlight doesn’t work. When trying to change the brighntess the pop up window appears but the squares at the bottom don’t get filled up and the keyboard doesn’t light up.

**Comment by khronokernel** [comment]
Known issue:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
