### ISSUE TITLE
windows 10 install can someone explain the command in terminal what do I put in there better example.

### ISSUE THREAD

**Issue by motor-cyber** [dortania/OpenCore-Legacy-Patcher#188]
**Describe the bug**
A clear and concise description of what the issue is. 

**To Reproduce**
1. Open app or .command '...'
2. Enter '....'
3. See error

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.15.7, Catalina)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. MacPro5,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**
can someone explain the command in terminal for making a bootable usb

**Comment by khronokernel** [comment]
Documentation is on the website, if you feel it can be improved then send a pull request
https://dortania.github.io/OpenCore-Legacy-Patcher/WINDOWS.html
