### ISSUE TITLE
Big Sur 11.3.1: Wifi network max speed reduced

### ISSUE THREAD

**Issue by Ribero** [dortania/OpenCore-Legacy-Patcher#189]
On a MacBook Pro 10,1 with upgraded WiFi card the connection speed to a 5ghz network was set at 867Mb on BS 11.3 which is the maximum allowed by the wifi hotspot I connect to.

After upgrading to 11.3.1:

- The maximum rate I can connect to the same hotpot is now 400mb (probably like #170)
- I'm facing the BT + Wifi 2.4Ghz issue (cf #173) (It looks like it worked as expected in 11.3)

I'm using OLCP 0.1.2 (no additional/specifc config)
my Wifi card (`ioreg -r -n ARPT | grep IOName`) = `pci14e4,43ba` (BCM43602 802.11ac Wireless)

**Comment by khronokernel** [comment]
> The maximum rate I can connect to the same hotpot is now 400mb (probably like #170)

Hmm, can you try disabling AirportBrcmFixup in your config.plist? Wondering if only the BCM4360(non-02) variant should use it

**Comment by Ribero** [comment]
Well, well, well
I double checked and tried to another hotspot (same brand, same model) and I was able to catch it at 867Mb.
Then I forced this hotspot to provide only 2.4Ghz and I was still able to connect and use BT... The problem is not consistent.

I need to do the test at office as hotspot their are more difficult to connect to and only in 2.4Ghz.

Sorry I may have raised a non issue.

**Comment by khronokernel** [comment]
No worries, if you find it to be an OCLP issue then just mention. Will reopen accordingly

**Comment by mav2010** [comment]
Even though this is closed: I had the same issue. I upgraded the Wifi/Bluetooth Card in my MacBook Pro 10,1 to the same card as mentioned above: (ioreg -r -n ARPT | grep IOName) = pci14e4,43ba (BCM43602 802.11ac Wireless)

Running OpenCore Legacy Patcher in standard mode, it enabled the AirportBrcmFixup even though it is not needed. And then I also faced the 400 MBit/s maximum connection speed issue. Setting AirportBrcmFixup to Disabled in the config.plist after building, I am back to the expected 1.300 MBit/s maximum connection speed.

Can you possibly introduce a detection that does not enable AirportBrcmFixup, when the above mentioned WiFi Card is detected. I think quite a lot of people have done that upgrade to obtain AC connectivity.
