### ISSUE TITLE
Sleep Wake failure in EFI with MacBook Pro early 2013

### ISSUE THREAD

**Issue by TheMac6ine** [dortania/Opencore-Legacy-Patcher#19]
Hello, i have the same issue like in #7  I used version 0.0.7 and when my MacBook 10.1 is to long in in standby, i think more than 24 hour it crashes.

`Sleep Wake failure in EFI

Failure code:: 0x00000000 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time: 2020-12-10 06:16:09.275 +0100
OS Version: ??? ??? (Build ???)
Architecture: x86_64
Report Version: 32

Data Source: Stackshots
Shared Cache: EDB59884-BECA-35C6-A628-15DA943D22A5 slid base address 0x7fff200ba000, slide 0xba000

Event: Sleep Wake Failure
Duration: 0.00s
Steps: 1

Boot args: -v keepsyms=1 debug=0x100 agdpmod=pikera chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 43s

Process: swd [299]
Architecture: x86_64
Footprint: 376 KB
Time Since Fork: 0s
Num samples: 1 (1)

Thread 0x8ae 1 sample (1) priority 4 (base 4)
<thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
1 start + 1 (libdyld.dylib + 87601) [0x7fff203e3631] 1
1 ??? [0x10ddf7454] 1
1 ??? [0x10ddf71e8] 1
1 __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 143386) [0x7fff203b601a] 1
*1 ??? [0xffffff80002621f6] 1
*1 ??? [0xffffff8000969ceb] 1
*1 ??? [0xffffff8000873d11] 1
*1 ??? [0xffffff80002851c9] 1
*1 ??? [0xffffff80002bbf0d] (running) 1

Binary Images:
0x7fff20393000 - 0x7fff203c1fff libsystem_kernel.dylib (7195.50.7) <41068F5C-74E3-3C98-9256-6A18364FB5BA> /usr/lib/system/libsystem_kernel.dylib
0x7fff203ce000 - 0x7fff20408fff libdyld.dylib (832.7.1) <0C66AB9F-E22C-3286-B76B-DA4008698CD2> /usr/lib/system/libdyld.dylib
Model: MacBookPro11,2, BootROM 427.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,7 GHz, 16 GB, SMC 2.3f36
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGT650MItem, NVIDIA GeForce GT 650M, spdisplays_pcie_device, 1 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1669)
Bluetooth: Version 8.0.1f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD512E, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.4`

**Comment by GigaDroid** [comment]
Same problem here. It's related to issues with AppleIntelCPUPowerManagement.kext which can be fixed by enabling Drop CpuPm and Drop Cpu0Ist. Not sure if this has some other side effects as my battery doesn't seem to last as long as it did before but maybe I'm just imagining this.

**Comment by traviswparker** [comment]
I added those to the ACPI-Delete section but I’m still getting full shutdowns and S/W Failure in EFI if my 2012 rMBP sleeps for too long. Seems hibernation is not being handled properly. HibernateMode is Auto.

**Comment by houser42** [comment]
Seeing the same on a Macbook Pro 10,2
As far as I can tell it is so far only when hibernating on battery. fwiw.

**Comment by traviswparker** [comment]
I think I have mostly eliminated the problem with a custom config.plist. The trick was to remove a lot of stuff you don't need on the MacBookPro 10,x series. I can `pmset hibernatemode 25` and `pmset sleepnow` on battery, wait for the fans to stop ensure it has hibernated, and wake without a crash. It is definitely resuming from hibernate based on the brief hang when waking up.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!--OpenCore 0.6.4 config-->
<dict>
	<key>ACPI</key>
	<dict>
		<key>Patch</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>XHC1 to SHC1</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>WEhDMQ==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>U0hDMQ==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data></data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>EHC1 to EH01</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>RUhDMQ==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>RUgwMQ==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data></data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>EHC2 to EH02</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>RUhDMg==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>RUgwMg==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data></data>
			</dict>
		</array>
	</dict>
	<key>Misc</key>
	<dict>
		<key>BlessOverride</key>
		<array/>
		<key>Boot</key>
		<dict>
			<key>ConsoleAttributes</key>
			<integer>0</integer>
			<key>HibernateMode</key>
			<string>Auto</string>
			<key>HideAuxiliary</key>
			<false/>
			<key>PickerAttributes</key>
			<integer>1</integer>
			<key>PickerAudioAssist</key>
			<false/>
			<key>PickerMode</key>
			<string>External</string>
			<key>PickerVariant</key>
			<string>Auto</string>
			<key>PollAppleHotKeys</key>
			<true/>
			<key>ShowPicker</key>
			<false/>
			<key>TakeoffDelay</key>
			<integer>0</integer>
			<key>Timeout</key>
			<integer>5</integer>
		</dict>
		<key>Debug</key>
		<dict>
			<key>AppleDebug</key>
			<true/>
			<key>ApplePanic</key>
			<true/>
			<key>DisableWatchDog</key>
			<false/>
			<key>DisplayDelay</key>
			<integer>0</integer>
			<key>DisplayLevel</key>
			<integer>2147483650</integer>
			<key>SerialInit</key>
			<false/>
			<key>SysReport</key>
			<false/>
			<key>Target</key>
			<integer>3</integer>
		</dict>
		<key>Entries</key>
		<array/>
		<key>Security</key>
		<dict>
			<key>AllowNvramReset</key>
			<true/>
			<key>AllowSetDefault</key>
			<true/>
			<key>ApECID</key>
			<integer>0</integer>
			<key>AuthRestart</key>
			<false/>
			<key>BootProtect</key>
			<string>Bootstrap</string>
			<key>BlacklistAppleUpdate</key>
			<true/>
			<key>DmgLoading</key>
			<string>Signed</string>
			<key>EnablePassword</key>
			<false/>
			<key>ExposeSensitiveData</key>
			<integer>15</integer>
			<key>HaltLevel</key>
			<integer>2147483648</integer>
			<key>PasswordHash</key>
			<data></data>
			<key>PasswordSalt</key>
			<data></data>
			<key>ScanPolicy</key>
			<integer>0</integer>
			<key>SecureBootModel</key>
			<string>x86legacy</string>
			<key>Vault</key>
			<string>Optional</string>
		</dict>
		<key>Tools</key>
		<array>
			<dict>
				<key>Arguments</key>
				<string></string>
				<key>Auxiliary</key>
				<true/>
				<key>Name</key>
				<string>OpenShell.efi</string>
				<key>Comment</key>
				<string>OpenShell.efi</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>OpenShell.efi</string>
				<key>RealPath</key>
				<false/>
				<key>TextMode</key>
				<false/>
			</dict>
		</array>
	</dict>
	<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<dict>
				<key>DefaultBackgroundColor</key>
				<data>AAAAAA==</data>
				<key>UIScale</key>
				<data>Ag==</data>
			</dict>
			<key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
			<dict>
				<key>rtc-blacklist</key>
				<data></data>
			</dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>boot-args</key>
				<string></string>
				<key>run-efi-updater</key>
				<string>No</string>
				<key>csr-active-config</key>
				<data>AAAAAA==</data>
			</dict>
		</dict>
		<key>Delete</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<array>
				<string>UIScale</string>
				<string>DefaultBackgroundColor</string>
			</array>
			<key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
			<array>
				<string>rtc-blacklist</string>
			</array>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<array>
				<string>boot-args</string>
			</array>
		</dict>
		<key>WriteFlash</key>
		<true/>
	</dict>
	<key>PlatformInfo</key>
	<dict>
		<key>Automatic</key>
		<true/>
		<key>CustomMemory</key>
		<false/>
		<key>Generic</key>
		<dict>
			<key>AdviseWindows</key>
			<false/>
			<key>SystemMemoryStatus</key>
			<string>Auto</string>
			<key>MaxBIOSVersion</key>
			<true/>
			<key>MLB</key>
			<string>M0000000000000001</string>
			<key>ProcessorType</key>
			<integer>0</integer>
			<key>ROM</key>
			<data>ESIzRFVm</data>
			<key>SpoofVendor</key>
			<true/>
			<key>SystemProductName</key>
			<string>MacBookPro11,2</string>
			<key>SystemSerialNumber</key>
			<string>W00000000001</string>
			<key>SystemUUID</key>
			<string>00000000-0000-0000-0000-000000000000</string>
		</dict>
		<key>UpdateDataHub</key>
		<true/>
		<key>UpdateNVRAM</key>
		<true/>
		<key>UpdateSMBIOS</key>
		<true/>
		<key>UpdateSMBIOSMode</key>
		<string>Create</string>
	</dict>
	<key>UEFI</key>
	<dict>
		<key>APFS</key>
		<dict>
			<key>EnableJumpstart</key>
			<true/>
			<key>GlobalConnect</key>
			<false/>
			<key>HideVerbose</key>
			<true/>
			<key>JumpstartHotPlug</key>
			<false/>
			<key>MinDate</key>
			<integer>0</integer>
			<key>MinVersion</key>
			<integer>0</integer>
		</dict>
		<key>ProtocolOverrides</key>
		<dict>
			<key>AppleAudio</key>
			<false/>
			<key>AppleBootPolicy</key>
			<true/>
			<key>AppleDebugLog</key>
			<true/>
			<key>AppleEvent</key>
			<true/>
			<key>AppleFramebufferInfo</key>
			<false/>
			<key>AppleImageConversion</key>
			<false/>
			<key>AppleImg4Verification</key>
			<false/>
			<key>AppleKeyMap</key>
			<false/>
			<key>AppleRtcRam</key>
			<false/>
			<key>AppleSecureBoot</key>
			<false/>
			<key>AppleSmcIo</key>
			<false/>
			<key>AppleUserInterfaceTheme</key>
			<false/>
			<key>DataHub</key>
			<false/>
			<key>DeviceProperties</key>
			<false/>
			<key>FirmwareVolume</key>
			<false/>
			<key>HashServices</key>
			<false/>
			<key>OSInfo</key>
			<false/>
			<key>UnicodeCollation</key>
			<false/>
		</dict>
		<key>Quirks</key>
		<dict>
			<key>ExitBootServicesDelay</key>
			<integer>0</integer>
			<key>IgnoreInvalidFlexRatio</key>
			<false/>
			<key>ReleaseUsbOwnership</key>
			<false/>
			<key>RequestBootVarRouting</key>
			<true/>
			<key>TscSyncTimeout</key>
			<integer>0</integer>
			<key>UnblockFsConnect</key>
			<false/>
		</dict>
		<key>ReservedMemory</key>
		<array/>
	</dict>
</dict>
</plist>
```

**Comment by houser42** [comment]
Thanks for that @traviswparker 
Not sure if that was the intention, but as I was having problems with crashing when waking up I tried your entire config.plist on my Macbook Pro retina mid 2012 10,2/A1398. Seems to work great so far so many thanks for that! Should I tweak anything for my Macbook Pro if it appears to work fine?
Thanks again!

**Comment by traviswparker** [comment]
If you used the config.plist as is, your mac’s serial number and uuid will be wrong. That will break iMessage and other stuff. I removed mine for obvious reasons. It’s meant to be used as the source to build your personalized install from.

**Comment by houser42** [comment]
Thanks @traviswparker !
I just put it on a test system to see if it helped with the hibernation crashes and it did, so happy.
If you can suggest what the minimum of instances to put back I’d appreciate it.
If not I’ll experiment and hopefully manage.
Again thanks regardless!

**Comment by traviswparker** [comment]
You need to copy the unique stuff in the platform info section from your old config.plist. serial, MLB, and uuid keys I think.

**Comment by houser42** [comment]
Alright, thanks very much, will give it a go. Appreciate the info..

**Comment by GigaDroid** [comment]
@traviswparker I'm trying to adopt the latest sample.plist to work with my Macbook. Could you tell me what exactly you changed?

**Comment by khronokernel** [comment]
Resolved in main: https://github.com/dortania/Opencore-Legacy-Patcher/commit/1af51825603908fd981d98841c8a1a300b72441d
