### ISSUE TITLE
iMac7,1 Volume Control issues in Big Sur

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#191]
With macOS Sierra and newer, IOAudioFamily can no longer control the volume output of iMac7,1's internal speakers. Previously, the fix was to back port IOAudioFamily and AppleHDA:

* https://github.com/dosdude1/macos-catalina-patcher/tree/master/macOS%20Catalina%20Patcher/macOS%20Post%20Install/patchedkexts/volControl

Currently this solution is fugly as we're opening up OCLP to more linking issues down the line, however for the small user base requiring these patches I feel it's not worth investing heavy development time into finding an AppleALC patch

**Comment by imac71** [comment]
How are you going to fix the sound when its not even booting?

**Comment by khronokernel** [comment]
@imac71 We have several iMac7,1 users with working machine which one of them reported the audio issue. Please do not derail this topic, this is not a casual forum
