### ISSUE TITLE
Battery Service Recommended Error

### ISSUE THREAD

**Issue by ramram2000** [dortania/OpenCore-Legacy-Patcher#198]
my mac battery cycle is 276
it was normal and there was no any battery service recommended error in Catalina before installing Big Sur

i tested many ways to clean that like pressing  ctrl+option+power or the others like reseting vram and and and....!
but still it shows error ms
<img width="660" alt="Screen Shot 2021-05-06 at 9 36 37 AM" src="https://user-images.githubusercontent.com/83423439/117308946-fae6a100-ae4f-11eb-983d-a8044153d880.png">
g

can clean it by config codes ?
is there any way ?

thnks guys
![Uploading Screen Shot 2021-05-06 at 9.36.37 AM.png…]()

**Comment by Ausdauersportler** [comment]
Are your sure your old battery is an issue with OCLP?

https://www.maketecheasier.com/fix-service-battery-warning-mac/

https://support.apple.com/en-us/HT201585

**Comment by khronokernel** [comment]
Is this error replicable with reinstallation? Currently looks to be a simple Apple bug, as others on supported Macs receive this error before. Closing as out of scope for us
