### ISSUE TITLE
Allow user-configurable CPUFriend usage

### ISSUE THREAD

**Issue by Inspector42** [dortania/OpenCore-Legacy-Patcher#199]
**Describe the bug**
OCLP 0.1.2 created configuration on target system with no adjustments of settings or model leads to limitation of core frequency of HD7950 Graphic Card patched/flashed with EBC Mac-Firmware.
Disabling CPUFriend and associated data provider re-enables full speed.
Booting with BIOS switch on GPU set to position 2 (original PC BIOS) increases core frequency to default 850Mhz of Mac Edition HD7950 while showing card as HD7xxx in "About this Mac" and no boot screen when CPUFriend remains enabled.

**To Reproduce**

- Run OCLP app on MacPro3,1 with HD7950 that has been patched firmware using [netkas script](http://forum.netkas.org/index.php?PHPSESSID=hhfedq7qfko5oudr5brqnlfoerrsp8p2&topic=5619.0) to enable boot screen
![Image 07 05 21 at 13 08](https://user-images.githubusercontent.com/14858052/117441249-5dfe3380-af35-11eb-93f8-907711380774.jpeg)

- Install OpenCore to internal boot drive (see attached config.plist in Archive.zip)
- Restart
- Run LuxMark 3.1 (shows GPU specified core frequency @930Mhz)
- Monitor core frequency with either IOReg or iStatMenu --> shows core frequency @501Mhz under load, 300 MHz idle
- Memory frquency is 1250 MHz under load and 150 MHz idle
- LuxMark score is in the 7500 rage

![Image 07 05 21 at 16 34](https://user-images.githubusercontent.com/14858052/117472624-61a3b180-af59-11eb-906b-1411b50b6505.jpeg)
- Mount EFI, edit config.plist in OC folder (set "enabled" to "No" for CPUFriend and CPUFriendDataProvider in the Kernel--Add Section for Item 10 and 11) - I use "Plist Editor" for that.
- Save config.plist and reboot
- Run LuxMark again
- This time score is above 9900 and GPU frequency goes to 930Mhz in iStatsMenu or ioreg.
   It seems thought as if there are 4 stages used (300, 501, 880 and 930) depending on load, which corresponds to the 4 power stages defined in ACPI_SMC_Platfrom_Plugin/Content/Resources/MacPro3,1.plist under _IOPlatformThermalProfile-CtrlLoopArray-Item 1-MetaStateArray._ even though is should not be using that because of SMBIOS Model-ID set to MacPro7,1. However as there is no plist-file for MacPro7,1 in _ACPI_SMC_PlatformPlugin_ and _X86PlatformPluginFamiliy_ is not used there might be a magic default setting that kicks in and makes it work.

![Image 07 05 21 at 12 59](https://user-images.githubusercontent.com/14858052/117440353-3d81a980-af34-11eb-9b82-8d5bb45f7fe8.jpeg)

It should be noted that LuxMark score on El Capitan (natively booted) only reaches meager 1970, but the driver does not read GPU frequency.
I have also tried to have CPUFriend loaded right after Lilu, however that did not change the limit in frequency.
**Screenshots**
See attached LuxMark 

**Build Folder**
Release Version 0.12

**Hardware (please complete the following information):**
 - macOS 10.15.7, Catalina (19H1030)
 - MacPro 3,1 2x2.8GHz, 8GB RAM DDR2-800
 - WIFI BroadCom BCM94360CD
 - Spoofed to MacPRo7,1

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer]

- IORegistryExplorer Profile Included in attached 

[Archive.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6442715/Archive.zip)

**Additional context**
Update: Replaced uploaded ioreg file as it was corrupted. Also delete comment about _X86PlatformPlugin_ as MacPro uses _IOPlatformPluginFamily (ACPI_SMC_Platfrom_Plugin)_ and added information about frequency stages observable.

**Comment by khronokernel** [comment]
> This time score is above 9900 and GPU frequency goes to 930Mhz in iStatsMenu or ioreg.
> It seems thought as if there are 4 stages used (300, 501, 880 and 930) depending on load, which corresponds to the 4 power stages defined in ACPI_SMC_Platfrom_Plugin/Content/Resources/MacPro3,1.plist under IOPlatformThermalProfile-CtrlLoopArray-Item 1-MetaStateArray. even though is should not be using that because of SMBIOS Model-ID set to MacPro7,1. > However as there is no plist-file for MacPro7,1 in ACPI_SMC_PlatformPlugin and X86PlatformPluginFamiliy is not used there might be a magic default setting that kicks in and makes it work.

Thank you for this in-depth issue, has plenty documented and tested. The reason that these 4 stages appear is that CPUFriendProvider is simply ACPI_SMC_PlatformPlugin's MacPro3,1 data re-encoded to be injectable:

* [Original Apple Data](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Plists/PlatformPlugin/MacPro3%2C1/MacPro3_1.plist)
* [Re-encoded for CPUFriend](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Plists/PlatformPlugin/MacPro3%2C1/Info.plist)

So overall, this actually does very much seem to be expected behaviour. However as this does limit performance, I can add an option in patcher settings to allow users to override whether or not CPUFriend is injected

**Comment by Inspector42** [comment]
Thanks for the quick response.
I meanwhile managed to also take a closer look at Intel SpeedStep. Although I have not figured out how to monitor CPU frequency on MacPro3,1, HWMonitor shows CPU Voltages and Currents.
I have run Prime95 to fully load the CPU and compared that with values when just showing the desktop (idle).
Voltages and currents are practically identical with CPUFriend or without CPUFriend both in idle as well as in full load condition. Also CPU temperatures are very close.

The only thing that makes me wonder is why the Xeon E5462 is listed with a VID from 0.850V-1.3500V and my machine is always in the mid rage with a difference of 0.05V between idle and full load independent of CPUFriend.
Hence I will keep CPUFriend disabled for now but having that as an option in the configuration menu of OCLP would make things easier.

I have not cross checked if this phenomenon also happens in macOS 11 as I am waiting for my second SSD to arrive so that I can keep the working boot drive with macOS 10.15.7 untouched.
