### ISSUE TITLE
iMac 2011 reboots after USB.

### ISSUE THREAD

**Issue by jaydengamble6** [dortania/Opencore-Legacy-Patcher#2]
Ok when I booted from the USB and installed Big Sur of course it reboots I go back to the USB and pick macOS Installer, but it gets the apple logo and then reboots every time.

Edit: Just going to say I know the performance wont be great but I'll mostly use it for Spotify and some general browsing and probably tweak it a bit myself.

**Comment by khronokernel** [comment]
Are you booting through OpenCore each time? The USB needs to be plugged in for the whole process

**Comment by jaydengamble6** [comment]
> Are you booting through OpenCore each time? The USB needs to be plugged in for the whole process

Yes I am, Also the USB hadn't been taken out the whole time.

**Comment by khronokernel** [comment]
Hmmm odd, can you send me the EFI folder the patcher created?

**Comment by jaydengamble6** [comment]
> Hmmm odd, can you send me the EFI folder the patcher created?

Ok I should have the EFI attached.
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5632087/EFI.zip)

**Comment by jaydengamble6** [comment]
Im going to wipe my USB and generate a new EFI and I'll report back if thats done it.

**Comment by jaydengamble6** [comment]
![16070165491321692408369020819117](https://user-images.githubusercontent.com/75391793/101065493-23126100-358d-11eb-8954-94c2e3d46c23.jpg)
Getting further this time.

**Comment by jaydengamble6** [comment]
![1607019921539738894631882232642](https://user-images.githubusercontent.com/75391793/101071778-f6624780-3594-11eb-874b-d1a427afbd64.jpg)
It's working now thanks for the help.

**Comment by khronokernel** [comment]
Great to hear! Very odd issue however, will keep note if other users have issues as well
