### ISSUE TITLE
Patcher can over-write wrong EFI

### ISSUE THREAD

**Issue by mreckhof** [dortania/Opencore-Legacy-Patcher#20]
It appears that the patcher currently assumes that the selected disk is mounted to /Volumes/EFI.  If you already have something mounted to /Volumes/EFI (such as the host system you're creating the USB from), it can install to the wrong EFI.

Propose either checking the mount point after mounting to get where the system put it (likely /Volumes/EFI\ 1) or just forcing a mount point like /Volumes/OCP-EFI.

**Comment by MikeBeaton** [comment]
Similar, I think: I wanted to install the built OC image to `disk0s8` not `disk0s1` but there doesn't seem to be any option to do so? (So I  just did `cp -r` of the `EFI` folder inside the `Build-Folder` directory into the root path of the correct mounted volume which I wanted to use, by hand, instead.)

**Comment by mreckhof** [comment]
I re-wrote the disk selection and mount pieces to be more flexible and less likely to cause issues.  If folks think this is the right solution, let me know and I'll put in a proper merge request.

1.  The disk selection process filters out any logical partitions and only shows physical partitions.
2.  The name of the physical disk is shown
3. The disk selection requires you to specify the proper slice and doesn't assume slice 1.
4. A "likely candidate" is marked (partition type EFI).  I intentionally avoided using the word 'recommended'.
5. The mount point changes to /Volumes/OCLP-EFI to avoid anything already mounted as /Volumes/EFI


```
Loading diskutil...(This may take some time)

/dev/disk0: WDBRPG0010BNC-WRSN
                TYPE           NAME      SIZE   IDENTIFIER
                 EFI            EFI  200.0 MB   disk0s1 (*)
          Apple_APFS                 931.3 GB   disk0s2

/dev/disk1: WDS200T3X0C-00SJG0
                TYPE           NAME      SIZE   IDENTIFIER
                 EFI            EFI  200.0 MB   disk1s1 (*)
          Apple_APFS                   1.8 TB   disk1s2

(*) Likely Candidate

Please select the disk IDENTIFIER you want to install OpenCore to (ie. disk1s1): disk0
Please select the disk IDENTIFIER you want to install OpenCore to (ie. disk1s1): disk1
Please select the disk IDENTIFIER you want to install OpenCore to (ie. disk1s1): disk1s1
Trying to mount disk1s1
Volume EFI on disk1s1 mounted

Press any key to continue: 

% df
Filesystem     512-blocks       Used  Available Capacity iused       ifree %iused  Mounted on
/dev/disk3s5s1 3906619488   42900856 2367589752     2%  568913 19532528527    0%   /
devfs                 686        686          0   100%    1188           0  100%   /dev
/dev/disk3s4   3906619488       2088 2367589752     1%       3 19533097437    0%   /System/Volumes/VM
/dev/disk3s2   3906619488     732896 2367589752     1%    1288 19533096152    0%   /System/Volumes/Preboot
/dev/disk3s6   3906619488     220992 2367589752     1%     358 19533097082    0%   /System/Volumes/Update
/dev/disk3s1   3906619488 1493390008 2367589752    39% 2681506 19530415934    0%   /System/Volumes/Data
/dev/disk2s1   1953115488  177990688 1774720152    10%    1267  9765576173    0%   /Volumes/Data
map auto_home           0          0          0   100%       0           0  100%   /System/Volumes/Data/home
/dev/disk3s5   3906619488   42900856 2367589752     2%  568974 19532528466    0%   /System/Volumes/Update/mnt1
/dev/disk1s1       403266      15130     388136     4%       0           0  100%   /Volumes/OCLP-EFI
```

**Comment by khronokernel** [comment]
Resolved in main
