### ISSUE TITLE
No hardware acceleration 9600M GT

### ISSUE THREAD

**Issue by vdm-alt** [dortania/OpenCore-Legacy-Patcher#201]
Hi! Thanks for your project. It works. However, I ran into a problem. Very low speed 9600M GT (only 3 FPS in Cinebench R 15). In the course of work, the absence of some files is indicated (GeForce.kext, IOAcceleratorFamily2.kext, IOGraphicsFamily.kext.) Maybe this is the case. When patches are applied, the keyboard backlight stops working (there is a reaction to pressing the buttons). But this is not so important. (MBP5.1)

**Comment by khronokernel** [comment]
We've verified with MacBookPro5,3 that both the 9600M and 9400M do function with plenty other Tesla cards working. I recommend double checking you installed the acceleration patches and that the latest release works as well

Additionally, none of those kexts you've listed are required for graphics acceleration. Keyboard backlight is also known issue:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
