### ISSUE TITLE
No Audio on MacBook Pro 5,4 ( missing CS4206 codec in AppleALC kext)

### ISSUE THREAD

**Issue by indiawallah71** [dortania/OpenCore-Legacy-Patcher#202]
I have recently installed Big Sur 11.2.3 on my MacBook Pro ( mid 2009) using OCLP  0.1.2.

 It is not really a big issue as such as I can connect BT speakers and have sound.

I did a bit of digging into the info.plist of the most recent AppleALC kext and in the IOKitPersonalties I could not find the codecs for my particular model ( CirrusLogic CS4206). The other 2 types of Cirrus Logic codecs were there but not for my computer and I guess a few others from Macs of varying kinds from around 2009/10. 

It is beyond my knowledge of being able to do something to update the kext in any way but just wanted to point out my finding and hope someone with the ability can inject the AppleALC kext with an updated info.plist

![Screenshot 2021-05-08 at 14 47 11](https://user-images.githubusercontent.com/83871148/117541571-6d9c7b80-b00c-11eb-86a1-59d6b6bf8312.png)

**Comment by khronokernel** [comment]
This was already resolved in 0.1.3:
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/85e07614606d94598363eede3a9ad9058788cccb

**Comment by indiawallah71** [comment]
Thanks for letting me know. I have have just updated to OCLP 0.1.3 and am very happy to now have sound working. Very much appreciate the effort you and the other devs have put into getting our old Macs running the latest OS.
