### ISSUE TITLE
iMac14,1 and MacBookPro9,2 IOReg dumps

### ISSUE THREAD

**Issue by family1232009** [dortania/OpenCore-Legacy-Patcher#204]
Hi, 
here are my ioreg dump files: 
iMac14,1 (I switched from a standard HDD to SSD Samsung 860 EVO SATA III)
MacBookPro9,2 (ram upgraded to 8gb and HDD changed to SSD Samsung 850 EVO SATA III)

macOS Catalina 10.15.4

[iMac14,1 Catalina.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6446453/iMac14.1.Catalina.zip)
[MacBookPro9,2 Catalina.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6446454/MacBookPro9.2.Catalina.zip)

**Comment by khronokernel** [comment]
Thank you for these, really makes our lives easier determining and writing hardware logic!
