### ISSUE TITLE
iMac9,1 Audio Not Working

### ISSUE THREAD

**Issue by RustyBl0ck** [dortania/OpenCore-Legacy-Patcher#205]
Can I please get help with my iMac9,1 not getting internal speakers working, external audio port, internal microphone? I tried executing OCLP 0.1.3 and get no result. Thanks!

**Comment by khronokernel** [comment]
Will assume you're using an old commit, ensure you're using one with `9b89b62` as the AppleALC binary was updated. Quick link to the .app:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2686873229/artifacts/59230742

User verified with their 20" iMac9,1 that this works
