### ISSUE TITLE
Infinite Login GPU Radeon 6750m 

### ISSUE THREAD

**Issue by vinnizann** [dortania/OpenCore-Legacy-Patcher#209]
Infinite Login after post-install volume patch

Set patcher settings
Enable Verbose Mode:				Currently True
Enable OpenCore DEBUG:			Currently False
Enable Kext DEBUG:				Currently False
Assume Metal GPU Always:			Currently None
Assume Upgraded Wifi Always:		Currently False
Set ShowPicker Mode:				Currently True
Set Vault Mode:					Currently False
Set SIP and SecureBootModel:		SIP: False SBM: False
Set SMBIOS Mode:				Currently Minimal
DRM Preferences:					Currently False
Set Generic Bootstrap:				False
Set Acceleration Patches:			True
Assume Legacy GPU:				False
Allow OpenCore on native Models:	False

OpenCore-legacy-Patcher 0.1.2

 - OS Running ie. macOS 11.2.3, Big Sur
 - OS Patching ie. macOS 11.2.3, Big Sur
 - Model Patching MacbookPro8,2

The bug happens with the dedicated GPU is enabled.
When I deactivate the dGPU, the OS works normally
I believe that this flaw has to do with the GPU I am using.
The GPU is AMD Radeon HD 6750M 1024MB

![Captura de Tela 2021-05-09 às 12 35 40](https://user-images.githubusercontent.com/83914921/117578108-19a09e00-b0c3-11eb-8e96-fe6d75d9c148.png)

**Comment by khronokernel** [comment]
> OpenCore-legacy-Patcher 0.1.2

Expected, there's no TeraScale 2 patches in there. 0.1.3 has the patches though still being tested. Can grab a build below:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2691137862/artifacts/59309896

**Comment by khronokernel** [comment]
Decided to revert support as unstable

**Comment by vinnizann** [comment]
thx for reply
