### ISSUE TITLE
NVMe Power Management Patches only offered when not installed

### ISSUE THREAD

**Issue by jgleigh** [dortania/OpenCore-Legacy-Patcher#212]
When I build OC before adding the NVMe patch, it will correctly include it. If I then re-build OC with the patch running, it will not detect the NVMe drive and fail to include the patch. I've gone back and forth multiple times between these two states.

First time building OC with OCLP 0.1.2: ![Screen Shot 2021-05-10 at 8 40 21 PM](https://user-images.githubusercontent.com/654130/117755102-763daf00-b1d0-11eb-894b-379e0ec4edf2.png)

Second time after NVMe patch has been installed: ![Screen Shot 2021-05-10 at 8 35 43 PM](https://user-images.githubusercontent.com/654130/117755143-8a81ac00-b1d0-11eb-9ee3-0ebc9e892195.png)

MacPro5,1
OCLP 0.1.2
Samsung EVO 970
MacOS 11.2.3

**Comment by khronokernel** [comment]
Hello, can you send an IOReg before and after running OC? File -> SaveAs:
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip

Additionally, could you see if 0.1.3 also experiences this issue?
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2705356887/artifacts/59635582

**Comment by jgleigh** [comment]
The IOReg dumps appear to be identical.
[Mac Pro 2010 - NVMe fix installed.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6456558/Mac.Pro.2010.-.NVMe.fix.installed.zip)
[Mac Pro 2010 - NVMe fix removed.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6456559/Mac.Pro.2010.-.NVMe.fix.removed.zip)

The behavior with 0.1.3 is slightly different.
![Screen Shot 2021-05-10 at 9 37 29 PM](https://user-images.githubusercontent.com/654130/117759654-fb2cc680-b1d8-11eb-998e-e934bc8d7ba7.png)

**Comment by jgleigh** [comment]
Don't know if you still need this, but here is the gfxutil dump.
[gfxutil-dump.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6462954/gfxutil-dump.txt)
