### ISSUE TITLE
Sound and usb iMac 2008 24"

### ISSUE THREAD

**Issue by Luuuu15** [dortania/OpenCore-Legacy-Patcher#214]
Hello,

Thank you for your patch for old Mac !!
i have successfully installed Big Sur 11.3.1 on an iMac 2008 24" with OCLP 0.1.2.
But I have some issues with the usb ports (they don't work), and the sound is always on, at the max volume...
i tested some functionalities, everything work except these both.

Sincerely

**Comment by Luuuu15** [comment]
Hi, 
i updated the EFI to OCLP 0.1.4, and USB ports works, but now sound doesn't work at all...
![Capture d’écran 2021-05-12 à 11 34 55](https://user-images.githubusercontent.com/84011222/117953831-b6a74500-b316-11eb-8413-bcfcbde76f26.png)

**Comment by khronokernel** [comment]
Did you re-run the post-install patches? We moved audio support into the system volume patches to help alleviate the audio issues

**Comment by Ausdauersportler** [comment]
This was quite unexpected :-) But for systems needing the graphics patches the easy way. Possibly one should add a note to the docs about this.

**Comment by khronokernel** [comment]
@Ausdauersportler It's simply for iMac7,1 and iMac8,1, rest of the machines still have AppleALC

**Comment by Luuuu15** [comment]
Okay i reinstall post-install patches and finally : it works ! 
Tomorrow I will install Big Sur on my main hard drive because it’s very slow on an external one…
Thank you so much !

**Comment by khronokernel** [comment]
Great to hear!
