### ISSUE TITLE
Error in OC generation from 0.1.3 & 0.1.4 for iMac 11,3

### ISSUE THREAD

**Issue by kennycyw** [dortania/OpenCore-Legacy-Patcher#216]
iMac 27" 11,3 with RX480 and upgraded wifi ac & BT 4.2, booting from OC 0.1.2 on SD for Big Sur 11.2.3

Cannot build OC from OCLP Patcher 0.1.3 or 0.1.4 with the following error:
IndexError: Last Index out of range
[10351] Failed to execute script Open-Patcher

**Comment by khronokernel** [comment]
Are you able to upload an IOReg?
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip
File -> SaveAs

**Comment by kennycyw** [comment]
This is it:

[iMac 2010.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6478974/iMac.2010.zip)

**Comment by kennycyw** [comment]
[iMac 2010.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6479005/iMac.2010.zip)

Oh, accidentally close this issue.
