### ISSUE TITLE
MacPro 5,1 nvme volume unrecognized by (EFI) picker

### ISSUE THREAD

**Issue by jaybanger1** [dortania/Opencore-Legacy-Patcher#22]
I am able to boot into the Big Sur installer via my USB drive and install onto any internal sata based drive on the internal bus, as well as start the install on my PCI nvme drive, however when installing onto the pci nvme, the installer gets to the point where it reboots and the picker is unable to see the pci based nvme drive as a boot option to continue the install. Are there any Kext or plist options to enable this?

**Comment by khronokernel** [comment]
MacPro5,1's firmware was updated to have NVMe support in 2018 with Mojave, however your machine might be running an older build. 2 works arounds would be:

- Install Mojave normally and have the firmware upgraded
- Add NvmExpressDxe.efi to your OpenCore setup

For the latter, I have an EFI here that'll do the trick:

* [EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5693369/EFI.zip)

You will need to mount the EFI partition of the USB, either rerun the patcher's install to the USB and replace the contents of the EFI partition when its mounted or you can mount it manually via [MountEFI](https://github.com/corpnewt/MountEFI)

**Comment by jaybanger1** [comment]
Awesome, thank you. I'll try adding that to my EFI and reply shortly with the results. I did in fact do the firmware update, so inside of Mac OS desktop or in the installer the drive shows no problem. It's only in the EFI picker that I am not seeing it. So I suspect that the EFI needs that kext. Thank you.

**Comment by jaybanger1** [comment]
That addition to the EFI did the trick. Nvme was recognized immediately, after boot. I was able to complete the install, afterward no problem. Now if I can get the update to 11.1 to complete I'll be good. Thanks for the help!

**Comment by jaybanger1** [comment]
The update to 11.1 still never completed via software update. An by not complete I mean it would say update complete then restart, and it would still be on 11.01. I ended up downloading the Big Sur installer from the App Store (12gb download) and ran that directly on my boot volume. It, completed without a hitch and I am now on 11.1, an all is good.

**Comment by houser42** [comment]
Hello,
I think I am seeing something similar or same, so hope it is ok to post in this thread.
I am having partial success with a MacPro 5,1.
It is firmware upgraded to 5,1 from a 4,1 and then firmware upgraded running Mojave.
It has a sata SSD and a non Mac Asus Radeon card that  supports metal.
Was previously running Mojave and also the Dosdude Catalina patcher with no issues, including graphics.

So now with the PLP 0.0.18 it boots and runs fine for a while, but I do not see the EFI at startup and also, a crash happens after a long while. Can not pin it down so far.

Before I submit any logs, could you suggest  the recommended EFI/kext combo for my rig please?
Just the vanilla 0.0.18 or should I try something like the EFI in this thread?
@jaybanger1 if you have something that works could you share your working EFI please?
Many thanks!

**Comment by aec360** [comment]
Hello. I only used the EFI in the thread and it’s been working fine since I tried it. 

Best Regards,

Anthony E. Carter, Jr.

**Comment by houser42** [comment]
> Hello. I only used the EFI in the thread and it’s been working fine since I tried it. Best Regards, Anthony E. Carter, Jr.
> […](#)

Thanks I appreciate the reply! 
So you just replaced the entire EFI in the build folder and uploaded that?
Many thanks!
