### ISSUE TITLE
Lid sensor broken on MBP8,2 and MBP8,3

### ISSUE THREAD

**Issue by lulujyc** [dortania/OpenCore-Legacy-Patcher#224]
**Describe the bug**
The Mac is still awake and the internal screen is still powered on after a lid close

**To Reproduce**
1. Close the lid

**Screenshots**
N/A

**Build Folder**
N/A

**Hardware (please complete the following information):**
 - OS Running macOS 11.3.1, Big Sur
 - OS Patching ^^
 - Model Patching MacBookPro8,1

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**
Disabled dGPU via NVRAM, if this makes a difference

**Comment by NOTNlCE** [comment]
Similar to #220 - this issue does not affect demux modded machines, indicating it is likely a dGPU disabling issue.

**Comment by MrMacintoshBlog** [comment]
I also have an 8,2 and can confirm that the LCD backlight stays on when the lid is closed and the mac does not go to sleep.

11.2.3 & 11.3.1 with and without gpu disabled via NVRAM setting.

**Comment by khronokernel** [comment]
To avoid fragmentation, I'd prefer if the below issue could be considered the main MacBookPro8,2/3 issue thread:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/220
