### ISSUE TITLE
Mac Pro 5,1 with Unflashed card does not show OpenCore picker or full boot process.

### ISSUE THREAD

**Issue by jaydengamble6** [dortania/OpenCore-Legacy-Patcher#225]
**Describe the bug**
Sorry if this is something that is an easy fix or not I'm new to Mac Pro's. When I power on my Mac it chimes and then it stays on a black screen with no OpenCore Picker then after a while it goes to macOS and I can't boot into another OS because of this.

**To Reproduce**
1. Turn on Mac Pro
2. Black screen for a min
3. Apple Logo shows when fully booted and no picker.

**Build Folder**

[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6485951/EFI.zip)

**Hardware (please complete the following information):**
 - OS Running (macOS 11.2.3, Big Sur)
 - OS Patching (macOS 11.2.3, Big Sur)
 - Model Patching (MacPro5,1)
 - GPU (GTX 650)
 - RAM (12GB 1333 MHz DDR3)
 - CPU (Intel Xeon CPU W3680 @ 3.33GHz)

[IORegistryExplorer Save Output
](https://drive.google.com/file/d/1J54EwEQGyg4YOKfQdF5JpNpoACtzp-mB/view?usp=sharing)

**Comment by vit9696** [comment]
GTX 650 needs to be flashed with GOP first. Not necessarily Mac-compatible GOP, but at least some sort of GOP through Windows. You can use [GOPUpd](https://www.win-raid.com/t892f16-AMD-and-Nvidia-GOP-update-No-requests-DIY.html#msg15730) or similar tools.

**Comment by jaydengamble6** [comment]
> GTX 650 needs to be flashed with GOP first. Not necessarily Mac-compatible GOP, but at least some sort of GOP through Windows. You can use [GOPUpd](https://www.win-raid.com/t892f16-AMD-and-Nvidia-GOP-update-No-requests-DIY.html#msg15730) or similar tools. You should look for the latest version on the last pages of the thread. For Kepler GPUs like yours you will need NVFlash 5.127.

Thank you very much, Now I can use the OpenCore Picker and see the full boot process!
