### ISSUE TITLE
Quick Look windows missing Close and Resize buttons after Post-Install Volume Patch is applied

### ISSUE THREAD

**Issue by neogomo** [dortania/OpenCore-Legacy-Patcher#226]
**Quick Look windows missing Close and Resize buttons after Post-Install Volume Patch is applied through OCLP. (tested on Big Sur 11.2.3/11.3.1 with OCLP 0.1.2/0.1.4/0.1.5, MacBookPro4,1 with Nvidia 8600M GT)**

Clicking where they normally should appear does work, though. (resizing and closing behaviour of the window is as expected)

Before Post-Install Volume Patch is applied:

![11 3 1-oclp-0 1 5](https://user-images.githubusercontent.com/13170043/118565116-e371b700-b771-11eb-8966-3e2b29e07a09.jpg)

After Post-Install Volume Patch is applied:

![11 3 1-oclp-0 1 5-post-volume-patched](https://user-images.githubusercontent.com/13170043/118565138-ebc9f200-b771-11eb-8a0b-5180a34035c8.jpg)

**Comment by khronokernel** [comment]
Updated our Legacy Acceleration issue here:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/226

Will be investigating fixes, appreciate the report
