### ISSUE TITLE
Sleep and wake problem in iMac 2010 27"

### ISSUE THREAD

**Issue by kennycyw** [dortania/OpenCore-Legacy-Patcher#228]
Got three different internal SSDs (one for HS, one for Cat, one for Big Sur) in my iMac 2010 27" with RX480 4GB and updated WIfi/BT 4.2.
Use OCLP 0.1.2 on SD card to boot Big Sur 11.2.3 in internal SSD. (Can't use 0.1.3 and 0.1.4 due to error in creating OCLP.)

On prolonged deep sleep (overnight) in Big Sur, the OCLP bootpicker will show up on screen with fans in high gears and hot temperature in the morning with loss of the Big Sur disk in the BootPicker. Even when I boot then into Catalina, the Big Sur disk can't be found in Finder nor MacsFanControl. Only a shutdown and cold restart could bring back the Big Sur disk in OCLP BootPicker for proper booting. Short sleep is cool and quiet with no such problem.

That also doesn't happen with OCLP 0.1.1 or OC 0.6.8. The sleep & wake fully function.

**Comment by khronokernel** [comment]
@kennycyw Could you please upload the EFI 0.1.1 generated as well as 0.1.2's?

Additionally, could you test 0.1.5 below regarding crashing?
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2755736143/artifacts/60941243

**Comment by kennycyw** [comment]
[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6500345/EFI.zip)
0.1.1 seemed to work.
0.1.2 and 0.1.5 beta not.
Testing the latest 0.1.5 release ...
Applied only the AMD GPU patch.
SIP & SecureBoot remain enabled as default. 
Minimal SMBIOS patching.

**Comment by khronokernel** [comment]
@kennycyw The 0.1.1 folder you upload is a 0.1.5 configuration as I can see in the config.plist's `Build-Version` entry. Could you upload the 0.1.1 configuration?

**Comment by kennycyw** [comment]
[EFI 0.1.1 & 0.1.5.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6505203/EFI.0.1.1.0.1.5.zip)

O.1.5 release version still got the crash to BootPicker with loss of the Big Sur disk after overnight sleep.
Wondering whether it is the Hibernation issue ...
I am reverting to OCLP 0.1.1 to see whether it really cures the condition since prior to that with OC 0.6.8 (not OCLP) from Ausdauersportler with his iMac Micropatcher, no long sleep problem.

**Comment by kennycyw** [comment]
Confirmed that for long sleep, OC 0.1.1 worked while the later versions not.

With OC 0.1.1, there was no crash and the LCD screen remained black overnight, and waking up had no issue on pressing mouse button or keyboard. However, the fans were running (audible though not in high gear) and the computer back was warm. It seemed it was not in low energy mode.

For short sleep under OCLP (all versions) by choosing Sleep in Apple menu, both the LCD screen and fans were turned off immediately and the iMac remained completely silent and cool for yet an undetermined short period of time before the likely crash in versions 0.1.2 and onwards to the OCLP BootPicker screen.

**Comment by kennycyw** [comment]
I tested OCLP 0.1.5 again. 
Now my BS can be booted only with SecureBoot disabled (since I had booted into HS with corruption of the disk seal of the BS root recovery volume)
Now after a long sleep, I found on waking up by mouse click, the HS logon screen would be shown instead of the OCLP Bootpicker. The fans are silent and the iMac is only slightly warm. From that I can restart to OCLP and then BS again.
There should be a crash with restart to my default HS internal SSD. Anyway, that's better than the previous crash back into OCLP Bootpicker with no BS. However, not sure whether the change is related to the SecureBoot status.

The next hurdle is to overcome the system hanging in the mid 2nd stage of booting and installation from 11.2.3 to 11.3.1.
Wondering whether a moderate SMBOS patch or directly to 11.4 would do ...
Will try when the full InstallAssist.pkg out.

**Comment by Ausdauersportler** [comment]
Updating to 11.3 or 11.3.1 hangs in stage2 on all iMac11,x - A reboot normally cures this. You can enable verbose to observe where it hangs exactly. 
I had no time to cross check your particular problems of my identical iMac11,3 with RX480. Still using an older OCLP version.

**Comment by kennycyw** [comment]
With OCLP 0.1.5 running BS 11.4, there is problem with deep sleep and waking now for my iMac 2010 RX480. No crashing and stay quiet and cool overnight.
