### ISSUE TITLE
12,2 imac won't boot with nvidia patch

### ISSUE THREAD

**Issue by WillD7545** [dortania/OpenCore-Legacy-Patcher#229]
12,2 imac with 765m will boot with OC built from another mac using the 12,2 stock profile. It hangs up if using OC built to recognize nvidia metal card.

**Comment by khronokernel** [comment]
Could you provide the EFI folder built both times?

**Comment by WillD7545** [comment]
[Archive.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6497778/Archive.zip)

**Comment by khronokernel** [comment]
I see this is 0.1.4, does 0.1.5 make a difference? Also where does OpenCore hang? Did you troubleshoot by enabling verbose?

**Comment by WillD7545** [comment]
![IMG_20210517_210240](https://user-images.githubusercontent.com/9771582/118579417-aac2e500-b753-11eb-875a-97a5c637b059.jpg)
Built with 0.1.5

**Comment by khronokernel** [comment]
Hmm interesting, as I'm diffing between old variants of the EFI, could you reupload with 0.1.5? Makes it a bit easier to understand where the issue may lie

Additionally, would be helpful to upload an IOReg (File -> SaveAs):
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip

**Comment by WillD7545** [comment]
[0.1.5.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6497894/0.1.5.zip)

**Comment by khronokernel** [comment]
Hmm quite odd, does brightness control work with the iMac regarding the working EFI?

**Comment by WillD7545** [comment]
No, it does not.

**Comment by WillD7545** [comment]
The 765m does have a Nick[D]vB bios, but it is fairly old. I assumed it would still work, could that contribute to the problem?

**Comment by khronokernel** [comment]
Hmm, I have a few ideas of where the issue could be. I don't believe the VBIOS is the issue for reference. 

Currently I believe I see the issue, could you try this build? You'll need to have python 3 installed (Run OpenCore-Patcher.command):

[Archive.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6497974/Archive.zip)

**Comment by WillD7545** [comment]
![IMG_20210517_220959](https://user-images.githubusercontent.com/9771582/118584677-178ead00-b75d-11eb-9a25-424c65a3ab1c.jpg)
0.1.6

**Comment by WillD7545** [comment]
[Uploading 0.1.6.zip…]()

**Comment by khronokernel** [comment]
Hmm, how familiar are you with mounting the EFI Partition and manually moving config's over? Can you try the below EFI:

[OpenCore-No-shikigva.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6504886/OpenCore-No-shikigva.zip)

To mount the EFI Partition, simply use [MountEFI](https://github.com/corpnewt/MountEFI) and drop the EFI and System folder onto the root of the drive

**Comment by WillD7545** [comment]
![IMG_20210519_102055](https://user-images.githubusercontent.com/9771582/118839402-11e3b500-b88c-11eb-913f-493bf9814351.jpg)
Here's where it hung up with the provided EFI.

**Comment by Ausdauersportler** [comment]
Recently there has been a new version of the 765M BIOS [posted](https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/post-29664785) including brightness control with OpenCore - it should work with OCLP.

**Comment by khronokernel** [comment]
Closing as likely resolved by new VBIOS
