### ISSUE TITLE
Getting error when opening open core patcher

### ISSUE THREAD

**Issue by porcherie** [dortania/Opencore-Legacy-Patcher#23]
When I start open core patcher I get this error
`/Users/francesco/Downloads/Opencore-Legacy-Patcher-0.0.7/OpenCore-Patcher.command ; exit;
francesco@Francescos-MacBook-Pro ~ % /Users/francesco/Downloads/Opencore-Legacy-Patcher-0.0.7/OpenCore-Patcher.command ; exit;
NVRAM: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product': (iokit/common) data was not found
No OpenCore detected
Current Model: MacBookPro10,2`

and then it continues to the normal prompt to select one of the options. 
I never managed to install Big Sur with open core, so I am wondering now if it might be because this error,
I am on a MacBookpro 10,2 with upgraded wifi card.
All is working well with BenSova patcher, but I really want to use this patcher because superior on many things.
Any help??

**Comment by startergo** [comment]
```
Downloads/Opencore-Legacy-Patcher-main/Resources/BuildOpenCore.py", line 26, in <module>
    if opencore_model not in ("NVRAM: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product': (iokit/common) data was not found"):
TypeError: 'in <string>' requires string as left operand, not bytes
```
cMP5,1

**Comment by porcherie** [comment]
> ```
> Downloads/Opencore-Legacy-Patcher-main/Resources/BuildOpenCore.py", line 26, in <module>
>     if opencore_model not in ("NVRAM: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product': (iokit/common) data was not found"):
> TypeError: 'in <string>' requires string as left operand, not bytes
> ```
> 
> 
> cMP5,1
> 
> 
> ```
> nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product
> 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product	MacPro5,1
> ```

Thanks for the answer, but I don't understand what you mean!😅

**Comment by startergo** [comment]
> > ```
> > Downloads/Opencore-Legacy-Patcher-main/Resources/BuildOpenCore.py", line 26, in <module>
> >     if opencore_model not in ("NVRAM: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product': (iokit/common) data was not found"):
> > TypeError: 'in <string>' requires string as left operand, not bytes
> > ```
> > 
> > 
> > cMP5,1
> > ```
> > nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product
> > 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product	MacPro5,1
> > ```
> 
> 
> Thanks for the answer, but I don't understand what you mean!😅

Oh it is not an answer. I have similar issue. I can't run it.

**Comment by khronokernel** [comment]
> /Users/francesco/Downloads/Opencore-Legacy-Patcher-0.0.7/OpenCore-Patcher.command ; exit; francesco@Francescos-MacBook-Pro ~ % /Users/francesco/Downloads/Opencore-Legacy-Patcher-0.0.7/OpenCore-Patcher.command ; exit; NVRAM: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product': (iokit/common) data was not found No OpenCore detected Current Model: MacBookPro10,2

That is correct, the printing is a bug and resolved in your p3 rewrite branch. But that error is unrelated to anything, it's simply used to detect if you're already booting OpenCore or not

> Downloads/Opencore-Legacy-Patcher-main/Resources/BuildOpenCore.py", line 26, in <module>
    if opencore_model not in ("NVRAM: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product': (iokit/common) data was not found"):
TypeError: 'in <string>' requires string as left operand, not bytes

py3 is currently not supported by the patcher's main branch, py3 support will drop in the near future and we have a preview on the py3 branch however its currently not done
