### ISSUE TITLE
Cannot patch system disk on a partition that has a name including space

### ISSUE THREAD

**Issue by lulujyc** [dortania/OpenCore-Legacy-Patcher#230]
**Describe the bug**
Cannot patch system disk for pre-2011 Macs on a partition that has a partition name including space

**To Reproduce**
1. Format a partition with a name including space, e.g. "Install macOS Big Sur"
2. Patch legacy display error
3. See error

**Screenshots**
Mostly a "cp" error

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running 11.3.1
 - OS Patching 11.3.1
 - Model Patching N/A

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**

**Comment by khronokernel** [comment]
This was addressed in 0.1.5 no? Also can you please send the error

**Comment by lulujyc** [comment]
> 
> 
> This was addressed in 0.1.5 no? Also can you please send the error

Sorry I just tested, yes it's a problem of mine. Specifically, the bug happens only if I use the non-app approach (i.e. using the OpenCore-Patcher.command directly). If using the APP approach, no error happens. Sorry for taking your time.
