### ISSUE TITLE
Graphics problems on UEFI-booted Windows 10 on MBP8,2 and 8,3 with Soft-disabled dGPU

### ISSUE THREAD

**Issue by lulujyc** [dortania/OpenCore-Legacy-Patcher#231]
**Describe the bug**
When booting a Windows 10 UEFI installation via OpenCore or Mac's native picker on 2011 dGPU-disabled Macs, the OS cannot load the HD 3000 graphics driver due to bug that Intel didn't solve. Thus, disabling the dGPU entry in ACPI is required for having a Windows 10 UEFI installation. Legacy installations, or UEFI installations with dGPU enabled, do not have such problems.

**To Reproduce**
1. Disable dGPU via NVRAM
2. Install Windows 10 via UEFI
3. See error

**Screenshots**
N/A

**Build Folder**
N/A

**Hardware (please complete the following information):**
 - OS Running N/A
 - OS Patching N/A
 - Model Patching MacBookPro8,3

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**
A Windows-specific DSDT patch might be required to solve this problem. Many from the OCLP Discord also report having such bugs, making them unable to use Windows 10. This is out of my reach so I'm posting here to see if anyone's interested to create the DSDT. For reference, MBP8,1, which is also using HD 3000, do not have such problems on Windows 10 even if it's UEFI-booted. So the problem could be very possibly related to the presence of the dGPU in the ACPI. According to some reports, deMUXed 8,2 have such problems as well.

**Comment by khronokernel** [comment]
Windows doesn’t respect ACPI’s _STA variable and thus there’s nothing we can do to disable the dGPU. Windows will always see the device both in ACPI and PCI plane

Feel free to PR other work-arounds however as we don’t have affected machines and primarily work on macOS support, this would be considered out of scope

**Comment by lulujyc** [comment]
> Windows doesn’t respect ACPI’s _STA variable and thus there’s nothing we can do to disable the dGPU. Windows will always see the device both in ACPI and PCI plane
> 
> Feel free to PR other work-arounds however as we don’t have affected machines and primarily work on macOS support, this would be considered out of scope

Ok thank you!
