### ISSUE TITLE
Black screen on the installation

### ISSUE THREAD

**Issue by welovemarcel** [dortania/OpenCore-Legacy-Patcher#233]
Hello !
I've black screen some seconds after the installation start.
The computer:
MB: ASUS PROART Z490-CREATOR 10G
CPU: INTEL CORE I9-10850K
GPU: None, i would like to use intel graphics in a first time before getting a GPU.

I'am not an expert but I tried to did my best for the install and very interested to make it works.

Thanks !

I attached my UEFI folder and the oc [.txt]
[opencore-2021-05-20-155236.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6516654/opencore-2021-05-20-155236.txt)
[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6516659/EFI.zip)

**Comment by khronokernel** [comment]
This project is for unsupported Macs, not PCs
