### ISSUE TITLE
Unable to Run Only Metal-capable Apps on GPU Acceleration Patches

### ISSUE THREAD

**Issue by jeremiasmanninen** [dortania/OpenCore-Legacy-Patcher#234]
Hey!

I don't know does The Legacy GPU Acceleration Patches for non-Metal GPUs support Metal capable apps. App store lets me download them but I am unable to open them (eg. Vectonator, Pastel). Should they work?

If not I thought at least to point out that would be a great thing if someone would be able to solve it. 😄

**Comment by jeremiasmanninen** [comment]
Couldn't either open the Apple Developer app.

**Comment by Ausdauersportler** [comment]
Long story short: 
Patching back graphics acceleration to Big Sur enables only OpenGL based programs to run fast. You will not get now or in any time in future a metal emulator for your old system. You can only exchange the GPU in some models (iMacs 2009 to Mid 2012 and MacPro) with a metal capable version.
