### ISSUE TITLE
Apps not listed to access Camera and Mic

### ISSUE THREAD

**Issue by ccabaleiro** [dortania/OpenCore-Legacy-Patcher#237]
In Preferences / Security & Privacy, no app is listed in Camera and Microphone devices, although I have Chrome installed and tried a Google Meet with it.  The browser asks user to use the devices, but even after acceptance, no permission is granted by the system.

This issue was detected in Macmini5,1 and MacBookAir4,1.

**Comment by khronokernel** [comment]
Please read the guide, non-Metal GPU issues are discussed including work arounds:
https://dortania.github.io/OpenCore-Legacy-Patcher/

**Comment by ccabaleiro** [comment]
It worked ! Sorry for not paying attention to the Workarounds section...
