### ISSUE TITLE
Documentation: Is SMBIOS changed after patching (and therefore have issues with iServices)?

### ISSUE THREAD

**Issue by zardini123** [dortania/OpenCore-Legacy-Patcher#238]
After reading through the documentation and README a couple times I cannot tell if its guaranteed that the patcher will change the SMBIOS of the old Mac.  Does the patcher override the SMBIOS to a more recent SMBIOS?  For example with an Early 2009 iMac (iMac9,1), would it become something more recent (i.e. iMac17,1)?

If the SMBIOS is changed, does one have to log out of all iCloud services before patching?  According to some forum posts I've read before, one should log out of all iServices before SMBIOS changing to avoid possible issues with Apple.

**Comment by khronokernel** [comment]
When you boot OpenCore, yes the SMBIOS is changed
However we only support clean installs and upgrades so don't see a situation where you'd need to sign out of iCloud on the machine

**Comment by zardini123** [comment]
Ah gotcha, so upgrades -- even though they change the SMBIOS -- won't require iCloud sign in/out?  Why is it that then people recommend sign in/out for Hackintoshes when changing SMBIOS?

Thank you!
