### ISSUE TITLE
Cannot run OpenCore-Patcher.command

### ISSUE THREAD

**Issue by dakanji** [dortania/OpenCore-Legacy-Patcher#239]
**Describe the bug**
Attempt to run OpenCore-Patcher.command fails on my MacPro3,1. Last tested OCLP with OC 0.6.8 (that worked)

**To Reproduce**
- Run `/path/to/OCLegacyMacPatcher/OpenCore-Patcher.command`
- Get error below:
```
$ /path/to/OCLegacyMacPatcher/OpenCore-Patcher.command
Traceback (most recent call last):
  File "/path/to/OCLegacyMacPatcher/OpenCore-Patcher.command", line 11, in <module>
    from Resources import Build, ModelArray, PCIIDArray, Constants, SysPatch, Utilities, CliMenu, DeviceProbe
  File "/path/to/OCLegacyMacPatcher/Resources/SysPatch.py", line 19, in <module>
    class PatchSysVolume:
  File "/path/to/OCLegacyMacPatcher/Resources/SysPatch.py", line 39, in PatchSysVolume
    def elevated(self, *args, **kwargs) -> subprocess.CompletedProcess[Any]:
TypeError: 'type' object is not subscriptable
```

**Hardware:**
 - OS Running (macOS 10.14)
 - OS Patching (N/A - Didn't get so far)
 - Model Patching (MacPro3,1)

**Other Info**
OCLP is synced with Commit d20d997

**Comment by dhinakg** [comment]
What version of Python is this?@

**Comment by dakanji** [comment]
Apparently either 3.8.8 or 3.9.2 
```
$ python --version
Python 2.7.16
$ python3 --version
Python 3.8.8
$ /usr/local/bin/python3 --version
Python 3.9.2
```

**Comment by khronokernel** [comment]
On my personal MacPro3,1 running Mojave, this cannot be replicated either with Python 3.9.5 from python.org or with our precompiled binaries from Github Actions. Try updating python3:

https://www.python.org

**Comment by dakanji** [comment]
I use homebrew and after running this to upgrade python to 3.8.10 and 3.9.5, I still have the same issue.

**Comment by dakanji** [comment]
Discovered the issue. You are basically not supporting Python 3.8

- /path/to/OCLegacyMacPatcher/OpenCore-Patcher.command
  - Does not work as using Python 3.8 on my setup
- python3 /Users/dayo/Documents/GitRepos/OCTools/OCLegacyMacPatcher/OpenCore-Patcher.command
  - DDoes not work as using Python 3.8 on my setup
- /usr/local/bin/python3 /Users/dayo/Documents/GitRepos/OCTools/OCLegacyMacPatcher/OpenCore-Patcher.command
  - Works as using Python 3.9 on my setup

Might want to make this 3.x version requirement clear if not already done

**Comment by khronokernel** [comment]
> Might want to make this 3.x version requirement clear if not already done

Ah thank you, yes will ensure the documentation correctly reflects

**Comment by dakanji** [comment]
> will ensure the documentation correctly reflects

If there are only a one or two 3.9 specific items, will be a lot better to try to maintain 3.8 compatibility

**Comment by khronokernel** [comment]
Well the question is, who's running the .command file? We only endorse the usage for macOS 10.7 and 10.8 as our build server can't create compatible binaries for such old OSes. For 10.9 all the way through 11, we recommend users use our rebuild binaries either from our [nightly link](https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher.app.zip) or [releases](https://github.com/dortania/OpenCore-Legacy-Patcher/releases) which has zero python dependancy from the OS itself.

If there's more uses than what I mentioned, we can consider refactoring for python 3.8 support

**Comment by dakanji** [comment]
> we can consider refactoring for python 3.8 support

Was not suggesting any major effort to maintain that version.
Just only if there is only one or two commands which would not be a major issue.

As for usage, convenient to work on the command line and keep a local git version up to date.
Not a biggie to specifically run 3.9 for me now that I know.
