### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by startergo** [dortania/Opencore-Legacy-Patcher#24]
I realized that using python 3.8.5 creates more errors than even native python 2.7. See here:
https://github.com/dortania/Opencore-Legacy-Patcher/issues/23#issuecomment-745262469
Using python 2.7.16 I was able to run  the application by navigating to 
```
/Users/<user>/Downloads/Opencore-Legacy-Patcher-main/App/OpenCore-Patcher.app/Contents/MacOS/OpenCore-Patcher.command
```
and running the command directly. But when installing to an EFI on USB. I get these errors:
```
Coping OpenCore onto Volumes/EFI
Cleaning EFI folder
Traceback (most recent call last):
  File "/Users/<user>/Downloads/Opencore-Legacy-Patcher-main/App/OpenCore-Patcher.app/Contents/MacOS/OpenCore-Patcher.command", line 160, in <module>
    BuildOpenCore.MoveOpenCore()
  File "/Users/<user>/Downloads/Opencore-Legacy-Patcher-main/App/OpenCore-Patcher.app/Contents/MacOS/Resources/BuildOpenCore.py", line 376, in MoveOpenCore
    rmtree("/Volumes/EFI/EFI")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 273, in rmtree
    os.remove(fullname)
OSError: [Errno 2] No such file or directory: '/Volumes/EFI/EFI/BOOT/._.disk_label'
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
There is also a syntax error in the beginning "coping" should be "copying"

**Comment by khronokernel** [comment]
> I realized that using python 3.8.5 creates more errors than even native python 2.7. See here:
#23 (comment)

Correct, py3 support is currently being worked on

> But when installing to an EFI on USB. I get these errors:

Is the EFI clean? We have no file called `._.disk_label`, seems to be some left over on your USB from a previous setup that `shutil` is unable to clean up. A clean install should be able to fix this, however will leave it open and see what I can do about `shutil` unable to see hidden files

**Comment by startergo** [comment]
> however will leave it open and see what I can do about `shutil` unable to see hidden files

I cleaned the hidden folders/files And it went through. Still though I cannot open the app by double clicking. It just opens for a second and disappears. I can only run it as 
```
/Users//Downloads/Opencore-Legacy-Patcher-main/App/OpenCore-Patcher.app/Contents/MacOS/OpenCore-Patcher.command
```

**Comment by khronokernel** [comment]
The build app is non functional outside our dev environment, users are not meant to run it. Will remove it from the repo as it seems like a common error
