### ISSUE TITLE
nvidia gt710 black screen on BigSur, cMP

### ISSUE THREAD

**Issue by Jonathan-50** [dortania/OpenCore-Legacy-Patcher#243]
Using two gt710's (GK208B, Kepler 2.0) on both the cMP3,1 and cMP5,1 one at a time.

oclp 0.1.5 with the respective efi folder for each machine, starting with 11.2.2 and then "ota" update to 11.3.1
installation and updates using mac flashed gtx680 (GK104), then swapped for either of the gt710's.

At the end of the BigSur boot process I get a black screen with a mouse pointer that reacts to mouse movement, but no Finder/Desktop. Abrupt movement of the mouse makes the pointer larger, as expected.

The only difference is that on the cMP5,1 the oclp boot picker and "white over black" progress bar can be seen, whereas on the cMP3,1 they can't.

Both gt710's work fine with Mojave on hdmi and dvi outputs.

**Comment by Ausdauersportler** [comment]
**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Comment by Jonathan-50** [comment]
Yes, of course, here they are:
[EFI_MP31_oclp015.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6530972/EFI_MP31_oclp015.zip)
[EFI_MP51_oclp015.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6530975/EFI_MP51_oclp015.zip)

**Comment by khronokernel** [comment]
I have an HP GT710 (GOP, stock VBIOS) with a stock MacPro3,1 running Big Sur, running the latest firmware with zero firmware mods. 11.3.1 works fine with the machine, so I believe there's an issue with your hardware configuration such as a missing GOP on the GT710 (see [here](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/225))

> the only difference is that on the cMP5,1 the oclp boot picker and "white over black" progress bar can be seen, whereas on the cMP3,1 they can't.

This was resolved with v0.1.6. Can grab the lates build below:

https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher.app.zip

**Comment by Jonathan-50** [comment]
I have two (2) gt710's. One of them is from an HP desktop. 
They both work fine on El Capitan and Mojave. None of them can reach the Desktop on BigSur.
