### ISSUE TITLE
Cant login to Big Sur after reboot to macOS HS

### ISSUE THREAD

**Issue by peacefulagain** [dortania/OpenCore-Legacy-Patcher#245]
Hi there^^ I have done all the things via FAQ and it was working like a charm. I got 15 inch MacBook Pro.
After I have disabled dGPU and reboot, the system was fully working, but for a moment (I got external SONY display)I had to work with High Sierra (another APFS container). Alas, after that I can't login to Big Sur, just see my user account and when enter my password it just blink and "enter ur pass again". The same thing was when Im trying to reboot after patches but not disabled dGPU. Seems to me that dGPU was enabled by HS))

![Screen Shot 2021-05-24 at 23 44 25](https://user-images.githubusercontent.com/84744078/119405849-9601c680-bcea-11eb-8a19-cc0df55e9a87.png)
Big Sur is 11.2.3 - Im impressed how fast it is) Hope u can add dGPU support for AMD6750.

**Comment by khronokernel** [comment]
Known issue, we've been investigating TeraScale 2 support for some time now
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
