### ISSUE TITLE
Unable to update to Mac OS to 11.1

### ISSUE THREAD

**Issue by jaybanger1** [dortania/Opencore-Legacy-Patcher#25]
I have several hard drives running the patcher. I was able to update the os on one using 004, now with 007 I am not. I can go through the install process but it still says version 11.01 and is presenting me with the update. Is this by design?

**Comment by khronokernel** [comment]
When running 0.0.7, can you try resetting NVRAM before starting the update? We fixed BlackListAppleUpdate in our patcher with 0.0.7 however old variables left in NVRAM could cause issues
