### ISSUE TITLE
Magic Mouse & Apple Trackpad are no recognised at boot (OC Picker and Login screen)

### ISSUE THREAD

**Issue by OKonnel** [dortania/OpenCore-Legacy-Patcher#251]
I just realized, with OCLP Build 0.1.6 (OpenCore is 0.7.0) that the Magic Mouse and Apple Trackpad are no longer recognized at startup, in the Opencore Picker screen and not even in the login screen to Big Sur (with FileVault). So, they work fine in Big Sur and even if I boot the iMac into Recovery Mode. I tried resetting SMC and PRAM and also modifying UEFI -> AppleInput, in "config.plist", using "Auto" instead of "Builtin", but without success. Some idea? They always worked great before. Thanks so much. (Note: I'm not sure if they started to malfunction with OCLP Build 0.1.6 or even some other previous Main Build).

iMac14,2 27" late 2013 3,5GHz i7 24GB NVIDIA GeForce GTX 780M 4GB CrucialMX500 2TB SSD int. & Big Sur 11.4 (20F71) OCLP 0.1.6 Apple128GB SSD int. with macOS Catalina just upgraded with 2021.003 Security Patch.

**Comment by khronokernel** [comment]
> (Note: I'm not sure if they started to malfunction with OCLP Build 0.1.6 or even some other previous Main Build).

Could you please verify whether this occurs with 0.1.5? I don't believe OpenCorePkg 0.7.0 changed anything significant regarding input support, though if this is a bug either with us or OpenCore it would be great to know when it stopped working

**Comment by khronokernel** [comment]
Additional note, does the Mac's built in boot picker support your mouse and keyboard? If no, then there's no way OpenCore would be able to handle input from the devices if the machine's firmware doesn't recognize the input devices

**Comment by OKonnel** [comment]
> Additional note, does the Mac's built in boot picker support your mouse and keyboard?

Magic Mouse and Apple Wireless Keyboard were included in the purchase with iMac14,2. So, the boot selector (ALT-Option) has always worked with these Input Sources, even with the Apple Trackpad and with any version of macOS (from 10.9 up to 11.3.1).
Perhaps the problem was caused by the Big Sur 11.4 update or by Catalina's latest "Security Update 2021.003"? (Firmware overwrited?…) (Catalina is on the other internal Apple SSD and not in a Volume Partition).
I hope there is a way to OCLP force the Mac to immediately recognise wireless devices again in Boot Selector and/or in OCLP Picker, as always so far. Otherwise it would be impossible, at boot, to use a wireless keyboard to press CMD+R, or press ALT-Option to EFI-boot select, etc!!!. Currently, in fact, I am forced to use the Apple USB keyboard :(

Important
Now Catalina's System Information says:
Boot ROM Version 431.0.0.0.0
Previously the EFI Version was 146.0.0.0.0 (as seen from a screenshot of Big Sur, in attach)
Now, even on Big Sur "Revision 431.0.0.0.0" appears if I restart without EFI OC folders.
So! After the update to Catalina Security Update 2021-003 I saw that file "IM142.scap" appeared in EFI/APPLE/FIRMWARE/. At internal of this file it reads. at the first lines:
Model: IM142
EFI Version: 431.0.0.0.0
Built by: root @ bb-g8-pdb148
Dates: Mon Feb 22 17:34:19 PST 2021
Revision: 431 (B&I)
ROM Version: F000_B00
Build Type: Official Build, Release
Compiler: clang-1205.0.19.59.6

![01 Before 2021-003 Security Update](https://user-images.githubusercontent.com/81856309/119941537-0762a300-bf91-11eb-9734-104b6d590288.png)
![02 After 2021-003 Security Update](https://user-images.githubusercontent.com/81856309/119941561-0fbade00-bf91-11eb-83fc-ec717812a71f.png)

**Comment by OKonnel** [comment]
After many other attempts, I finally **solved** the problem like this. Without following this procedure exactly I was getting no results and I was desperate. OpenCore 0.1.6 works.
**1)** At boot press ALT-Option key
**2)** Select OpenCore EFI -> click and immediately press Space Bar to bring up the OCLP EFI Utilities
**3)** Click on "Reset NVRAM". The Mac reboot.
**4)** At the Gong press and hold CMD + P + R Keys
**5)** After the second Gong immediately turn off the Mac
**6)** Only now (i.e. AFTER the PRAM reset) unplug the Mac power cable, wait more than 15 seconds, reconnect the cable, wait 5 seconds before turning the Mac back on.
**Important**! In the meantime, remove the batteries of the wireless Mouse, TrackPad, Keyboard!
**7)** At the Gong press ALT-Option
**8)** When OpenCore EFI appears and the System's Disk (and others disks) insert the batteries and turn on the Wireless Mouse, TrackPad, Keyboard which will be recognised again.

**Comment by Ausdauersportler** [comment]
Ups, according to this [post](https://eclecticlight.co/2020/11/16/which-firmware-should-your-mac-be-using-version-5/) the 431.0.0.0.0 was meant for iMac14,4 and iMac15,1. So it looks to me you  got really an unwanted firmware update (although I cannot be really 100% sure if Apple could have delivered a new one for your 14,2 using the same version number).
Using OCLP your system is getting the iMac15,1 identity, right?

**Comment by OKonnel** [comment]
Quite right! OpenCore correctly spoofs my iMac to 15.1.
However, in order to update Catalina to 2021-003, I had completely removed OpenCore EFI from the Internal Drive and put it back after rebooting from Big Sur. (Obviously, to log back into Big Sur, I temporarily used OC EFI from the USB Key).
