### ISSUE TITLE
Macbook Air 3,2 - partial success

### ISSUE THREAD

**Issue by houser42** [dortania/OpenCore-Legacy-Patcher#252]
Hello,

I assume it is too early to ask about this, but wanted to share the partial success anyway FWIW.
Just a note that an old friend, a Macbook Air 3,2 from late 2010 is working pretty great with Big Sur 11.4, once booted.
It has the Nvidia GeForce 320M.
Once booted it is pretty flawless (apart from sleep/wake and some mainly cosmetic things that are reported for other models also) but I can not for the life of me get it to boot by itself from the EFI and pressing the alt key is required for each boot and when installing. 

I have tried some alternative methods, like the ones for old Mac Pros from the same year to set the boot but it will not take so far.
Including this one booting-with-a-non-flashed-gpu from the wiki. Perhaps it can be adapted?
https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html#booting-with-a-non-flashed-gpu
AH well. Like I wrote, I assume it is too early to ask about this, but wanted to share the partial success anyway.
Any links or hints on how to set the bootdrive on a MacBook Air 3,2 is of course much appreciated.
Many thanks for your hard work regardless!

**Comment by khronokernel** [comment]
> but I can not for the life of me get it to boot by itself from the EFI and pressing the alt key is required for each boot and when installing.

Hm, you could try pressing Ctrl+ENTER when you're selecting a boot option in the Mac's picker. Otherwise unsure

Appreciate the feedback regarding results! Will add this to our site shortly

**Comment by houser42** [comment]
Thanks @khronokernel !
Yes, I am quite surprised how useful the old Macbook Air 3,2 can be with the right expectations on Big Sur.
Very happy with that. Makes sense in these times to try and keep using old gear for various obvious reasons and Planet Earth being chief among them. So you are on a ethically sensible path I guess..
Ctrl+ENTER to select boot disk was the first things I tried but it requires an alt-boot whatever I do so far.
If you find time at some point to comment on ways to set boot via some OLP tweak, I'd be happy to test it FWIW.
AH well. Thanks again for a really very useful bit of code in OLP!
