### ISSUE TITLE
MacBook 5,3 appstore apps don't open 

### ISSUE THREAD

**Issue by sasuke4uchiwa** [dortania/OpenCore-Legacy-Patcher#253]
MacBook Pro mid 2009 5,3 macOS Big Sur 
opencore patcher 0.1.5
I successfully installed it on my machine but it seems some apps installed from App Store it's not working like messenger/twitter/infuse 7

**Comment by Luuuu15** [comment]
Hi, 
I have the same issue on iMac 8,1 11.3.1, tested with Notability and Twitter : it crashes immediately after launching the app...

**Comment by khronokernel** [comment]
Due to lack of Metal support, search for older variants of these kexts without Metal reliance
