### ISSUE TITLE
Testing USB3 XHCI booting with nanoTech ExpressCard34

### ISSUE THREAD

**Issue by hvdschmitt** [dortania/OpenCore-Legacy-Patcher#254]
Made a USB stick from OCLP 0.1.6.
With this, continued tests with my MBP5,2 (17", mid 2009, Nvidia 9600M GT in use), and the 2-port nanoTECH ExpressCard 34 USB 3.0.
Booted OCLP stick from the Apple boot selector, and it seems to hang before it can proceed to the OCLP boot picker.

Then enabled OpenCore debug and Verbose mode, and looked at the OpenCore protocol written to the EFI of the stick.
- when booting while the ExpressCard is plugged in, it hangs when connecting drivers (1st attachment)
- when booting with ExpressCard taken out, it proceeds normal to the OCLP boot picker and can boot my BS drive (from one of the native USB ports) (2nd attachment)

The drivers are in place on the EFI/OC.

The ExpressCard works well from the booted BS. It then uses the driver AppleUSBXHCIFL1100. Unfortunately I'm not sure about the chipset it uses (several different answers found); but it seems natively supported without extra drivers installed.

Just wanted to report. It is of no urgency for me at all, can live without it; just booting via OCLP from USB3 looks very attractive.
Thanks for all your excellent OCLP support for my almost 12 year old machine - and for the unsupported machines of the many other macrumors users.

(First tests made on May 24th, but repeated it with the present state of OCLP just minutes ago)

[opencore-2021-05-24-140843.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6564715/opencore-2021-05-24-140843.txt)
[opencore-2021-05-24-142343.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6564716/opencore-2021-05-24-142343.txt)
![Bildschirmfoto 2021-05-24 um 16 02 38](https://user-images.githubusercontent.com/82234458/120071317-02841900-c08f-11eb-960a-497d459fad0a.png)
![Bildschirmfoto 2021-05-24 um 16 56 22](https://user-images.githubusercontent.com/82234458/120071325-0fa10800-c08f-11eb-9e15-220cf445ccf8.png)
![Bildschirmfoto 2021-05-24 um 16 57 03](https://user-images.githubusercontent.com/82234458/120071335-1760ac80-c08f-11eb-87ed-0675bb002c69.png)

**Comment by khronokernel** [comment]
> when booting while the ExpressCard is plugged in, it hangs when connecting drivers (1st attachment)

Hm unfortunate, would it be possible to try a debug build of XhciDxe with Debug OpenCore? Hoping it'll shed some light as to where the issue might lie

[XhciDxe.efi.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6577512/XhciDxe.efi.zip)

**Comment by hvdschmitt** [comment]
Thank you for the debug build of the driver.

I was using it with the expresscard plugged in. Then booted the OCLP without an SSD connected to the expresscard (first two protocols) and then with an SSD (third protocol). 

They all look similar. Hanging after Created CMD ring / EVENT ring.

Tried a bit to understand the driver using hopper disassembler but not enough yet; later could experiment with some patching also. Especially if it happens only in my setup.

[opencore-2021-06-02-155601.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6586442/opencore-2021-06-02-155601.txt)
[opencore-2021-06-02-160114.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6586444/opencore-2021-06-02-160114.txt)
[opencore-2021-06-02-171256.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6586445/opencore-2021-06-02-171256.txt)

**Comment by khronokernel** [comment]
Hmm unfortunate. Source code for XhciDxe is here:
https://github.com/tianocore/edk2/tree/master/MdeModulePkg/Bus/Pci/XhciDxe
I do recommend opening an issue with Acidanthera themselves as they maintain OpenCorePkg and bundle XhciDxe there:
https://github.com/acidanthera/bugtracker

Fortunately not much we can do on our end as-is, hopefully they'll be able to provide better insight
