### ISSUE TITLE
Mac mini (Mid 2011) (5,1)

### ISSUE THREAD

**Issue by csweering** [dortania/OpenCore-Legacy-Patcher#255]
Extremely happy, with the instructions and functionality, the minor point is that the video sometimes has trouble keeping up with the things I do. supper Airdrop is working :-) 

A bigger problem I encounter is the Internet connection MAX 165 Mbps vs MacbookAir  292 Mbps
I have all the tinks I can find like reset SMC  / NVRAM WiFi and Ethernet (CAT5) not better as Wifi

Any help is welcome 

PS is this normal   
System Firmware Version:	**9999.999.999.999.999**
SMC Version (system):	**9.9999**

**Comment by sharad-paghadal** [comment]
@csweering I have Mid 2011, Mac mini and facing issue with graphics. Upon fixing it by given method, it landed me into login screen loop. Can you please help me with that?

**Comment by csweering** [comment]
Sure love to help, can you tell me the things you have done, until now?

**Comment by khronokernel** [comment]
> A bigger problem I encounter is the Internet connection MAX 165 Mbps vs MacbookAir 292 Mbps

Unlikely issue with patcher, you'd need to investigate further yourself regarding Big Sur user configuration as we have no affected hardware or reports of lower speeds with the BCM94331 wireless or the BCM57765 Ethernet controllers
> PS is this normal

Correct, used to ensure firmware updates are not applied to unsupported models

**Comment by csweering** [comment]
I have done exactly this, but I have a 5.1 and you have a 5.2 that can make a lot of difference I'm afraid, so I don't know what I'm saying will help you, have you also done an SMC reset to be sure ???

**Comment by sharad-paghadal** [comment]
@csweering Did you run [this](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-achieve-gpu-acceleration-on-2011-15-and-17-macbook-pros) command?
