### ISSUE TITLE
Support Custom SMBIOS for Sandy Bridge iGPU Drivers

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#256]
Currently in OpenCore Legacy Patcher, we hard code the supported board IDs into AppleIntelSNBGraphicsFB. This creates issues down the line when we decide to change board IDs for broader OS support.

To work around this, we should implement hex editing upon root patching to ensure the correct SMBIOS is always used. Additionally can provide original board IDs as back up for users debugging with SMBIOS spoofing disabled

Code flow:

- Detect Sandy Bridge iGPU
- Detect current and original board-id
- Find AppleIntelSNBGraphicsFB-Clean.kext
- Duplicate to AppleIntelSNBGraphicsFB.kext
- Hex patch Mac-XXX with current board ID, original board-id and expected board ID if not set

**Comment by flagersgit** [comment]
Would it be possible to use the stock kext and use OC's kext patch functionality instead? Or is the `AppleIntelSNBGraphicsFB` kext not in a patchable cache?

**Comment by khronokernel** [comment]
Implemented via https://github.com/dortania/OpenCore-Legacy-Patcher/commit/ee77f76c3a1b1ec4a92dbd2f31ca28d0ee75f1d3
