### ISSUE TITLE
apps can't use microphone

### ISSUE THREAD

**Issue by Syf-X** [dortania/OpenCore-Legacy-Patcher#257]
chrome / discord and other apps are not showing up in confidentiality / microphone 
I can't allow them to acces to the mic 
I'm currently using a 2011 macbook pro 13"

**Comment by khronokernel** [comment]
Please check over our guide for troubleshooting, we document many of the issues users might face:
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html
