### ISSUE TITLE
Cannot Read GPU Die temperature using HWMonitor

### ISSUE THREAD

**Issue by paltrowlalic** [dortania/OpenCore-Legacy-Patcher#258]
Hi, when I was using dosdude1's Catalina patcher with some fakeSMC kext files and HWMonitor, I was able to get the GPU Die temperature reading. Since I moved on to BS using OCLP it seems not working anymore. Does OCLP include any fakeSMC kext file and if the answer is yes, is it possible that some related settings are not correct? Thanks for the help in advance!!
My machine is iMac12,2 (mid 2011 27'). Big Sur 11.4. OCLP0.1.2. GPU - NVIDIA K4100M

![image](https://user-images.githubusercontent.com/19687506/120531102-2bc9df80-c3d6-11eb-9e1b-d0d42175255a.png)

**Comment by Ausdauersportler** [comment]
No, it does not include these extensions, you would have add them on your own and modify manually the config.plist file generated with the OCLP app to load them.

**Comment by paltrowlalic** [comment]
Hi @Ausdauersportler , so the kext fileS should go to /EFI/OC/Kexts/ folder and I need to add sth in config.plist file? Thanks.

**Comment by Ausdauersportler** [comment]
Exactly!

**Comment by paltrowlalic** [comment]
Thanks! I will try and close the ticket.
