### ISSUE TITLE
keyboard brightness / backlight

### ISSUE THREAD

**Issue by edgarki** [dortania/OpenCore-Legacy-Patcher#260]
Hi all,

After successful install big sur 11.4 on a macbookpro5,3 mid 2009, i've reach a keyboard backlight not working. If you try to change the light intensity pressing keyboard option, no backlight works and the same if you try to do it on system preferences > keyboard where there is no option for keyboard brightness.

**Comment by Ausdauersportler** [comment]
This is most likely a known [issue](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#keyboard-backlight-broken).

**Comment by edgarki** [comment]
thanks! lab-tick works here
