### ISSUE TITLE
Control center not showing properly right after patching (Clean Install)

### ISSUE THREAD

**Issue by danimourinho** [dortania/OpenCore-Legacy-Patcher#261]
I have installed Big Sur 11.4 clean install in my MacBook Pro 13inch 2010 and noticed that the control centre doesn't show the volume and brightness bars properly. (Check Screenshot). Before patching, the control centre shows everything as it should.
![Screenshot 2021-06-03 at 10 37 01](https://user-images.githubusercontent.com/36760297/120623952-19908580-c458-11eb-9023-263c8ba65b55.png)

**Comment by educovas** [comment]
Known issue as you can see here: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
The sliders doesn't show properly but they do work if you click where they should be.
