### ISSUE TITLE
No mouse or keyboard support in VNC/Remote Desktop/Apple Remote management, with legacy GPU patch

### ISSUE THREAD

**Issue by vale21** [dortania/OpenCore-Legacy-Patcher#262]
**Describe the bug**
I have a Mac Mini 3,1. Acceleration working with monitor attached (many thanks, great!), but if I try to connect to the Mac via Apple Remote Desktop, I can see the desktop, but mouse and keyboard inputs are not forwarded to the target Mac. They are simply ignored.
I also tried with VNC, still no luck.

The Mac mini is used as a headless server, and I tried with display connected, and also both with and without a dummy dongle (see [here](https://macminicolo.net/blog/files/build-a-dummy-dongle-for-a-headless-mac-mini.html)). No luck in all three cases.

A USB mouse connected to the Mac Mini works even in remote desktop (you move the mouse, the remote screen updates). But just if there is something connected to the MiniDisplayPort (either real monitor, or dummy dongle). Conversely, neither the USB mouse makes the cursor move (!)

**To Reproduce**

Connect to the Mac with Apple Remote Desktop, or VNC

**Screenshots**

Screenshots are meaningless, you see the screen, but mouse cursor does not move

**Build Folder**

Tried with 0.1.5 and 0.1.6

**Hardware (please complete the following information):**
 - OS Running - Was running stock El Capitan before patching
 - OS Patching - Big Sur 11.4 (Fresh install)
 - Model Patching - Macmini3,1

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

[macmini.ioreg.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6592965/macmini.ioreg.zip)

**Additional context**

**Comment by khronokernel** [comment]
Updated issue to correctly reflect issue:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
