### ISSUE TITLE
Hackintosh Support

### ISSUE THREAD

**Issue by tahaklkt-osxinfo** [dortania/OpenCore-Legacy-Patcher#263]
Hello. I want to try this patch on my intel hd 3000 hackintosh. Can i init my graphics card with this patch in hackintosh ?

**Comment by lulujyc** [comment]
Best way is to try it yourself. Make sure SIP is fully disabled and run the (3) patch. In theory it will work.

**Comment by tahaklkt-osxinfo** [comment]
@lulujyc oh okay thanks. I will try this method.

**Comment by tahaklkt-osxinfo** [comment]
@lulujyc ![20210604_195653.jpg](https://user-images.githubusercontent.com/63608875/120837143-091efe80-c56f-11eb-8149-54784d4cbbdb.jpg)  How can I fix this ?

**Comment by dhinakg** [comment]
Root volume patching isn't supported on hackintoshes at this time.

**Comment by Doregon** [comment]
@dhinakg What would be required to make root volume patching supported on Hackintoshes? I have a Sandy Bridge system that runs OSX-KVM but I’d like to transition to bare-metal for at least a bit of a performance boost (plus more memory). I’ll be glad to contribute if I can!
