### ISSUE TITLE
black interface elements

### ISSUE THREAD

**Issue by PatrickBK** [dortania/OpenCore-Legacy-Patcher#264]
**Describe the bug**
I have black elements in the UI of several apps and MacOS itself. The installation is fast enough, it's stable yet the black elements in the interface make to hard to use for my daughter ;-)

**To Reproduce**
1. Open app Safari
2. see black interface elements

other option
1. Open about this Mac

yet other option
1. Open any part of system preferences

**Screenshot**
attached
![Schermafbeelding 2021-06-04 om 15 34 58](https://user-images.githubusercontent.com/526917/120810533-6e60f880-c54b-11eb-9e37-a8b2cb38366b.png)
![Schermafbeelding 2021-06-04 om 15 42 29](https://user-images.githubusercontent.com/526917/120810692-8d5f8a80-c54b-11eb-8a78-484ca7c7cd6c.png)
![Schermafbeelding 2021-06-04 om 15 43 52](https://user-images.githubusercontent.com/526917/120810886-baac3880-c54b-11eb-998c-9e0d4bfcd61f.png)

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 11.3, Big Sur)
 - Model Patching (ie. MacMini5,3)

in-depth hardware logs attached too
[Mac Mini van Sanjeena.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6598894/Mac.Mini.van.Sanjeena.zip)

**Comment by PatrickBK** [comment]
Big Sur 11.4 after the update doesn't have the problem but I have to run the patcher to get a speedier desktop. After patching, the desktop is speedier, transparency is enabled and the black elements are there again.
![Schermafbeelding 2021-06-05 om 19 52 27](https://user-images.githubusercontent.com/526917/120900904-d7be3580-c637-11eb-8b89-69871e2b93d6.png)

**Comment by lulujyc** [comment]
The issue cannot be replicated with my HD 3000 platform. Please try to make sure to use the latest patcher available, or it might be a Mac mini-specific problem?

**Comment by PatrickBK** [comment]
I used 0.1.6 which is the latest if I'm not mistaken so maybe it is a Mac mini specific issue. How can I be constructive in finding a solution?

**Comment by lulujyc** [comment]
> I used 0.1.6 which is the latest if I'm not mistaken so maybe it is a Mac mini specific issue. How can I be constructive in finding a solution?

If such condition is available, you might want to try changing the monitor as well as changing the output port. Although it might not be related to the problem (at all), you might want to try creating a new partition to install a fresh installation of Big Sur on.

**Comment by PatrickBK** [comment]
> > I used 0.1.6 which is the latest if I'm not mistaken so maybe it is a Mac mini specific issue. How can I be constructive in finding a solution?
> 
> If such condition is available, you might want to try changing the monitor as well as changing the output port. Although it might not be related to the problem (at all), you might want to try creating a new partition to install a fresh installation of Big Sur on.

A fresh install on a second ssd did't help and neither did using another display.

System Information demonstrates perfectly how irritating the issue is :-)

![Schermafbeelding 2021-06-07 om 11 51 39](https://user-images.githubusercontent.com/526917/120996669-d2233580-c786-11eb-8333-04e16f6da635.png)

**Comment by miguelabreuss** [comment]
Hi, i'm not an expert on the patch process and stuff, actually I end up in here looking for solve some graphic issues with my installation of Big Sur 11.4 on a Macbook Pro (late 2011) 13", with Intel HD Graphics 3000. But I had some problem with black spots like yours on my external screen, and I could solve it by doing a new calibration of the monitor. Maybe you can give it a try.

Best regards.

**Comment by KrutavShah** [comment]
I just tried my MBP 15 2011, no black squares on HD 3000 but wake from sleep and backlight PWM don’t work yet.

**Comment by ivanusevanton** [comment]
I have a similar problem on macbookpro 8.1 (macOS 11.4, OCLP 0.1.7) with built-in display. Some programs have color artifacts, others have black squares and / or missing controls instead of buttons. Color calibration did not solve the problem, after calibration there are even more color artifacts.
![IMG_1910](https://user-images.githubusercontent.com/85948874/122355181-5e3d1600-cf5a-11eb-8824-069f4638059a.jpg)
![IMG_1920_edited_1623913714](https://user-images.githubusercontent.com/85948874/122355292-71e87c80-cf5a-11eb-8154-77f1fd25c406.jpg)

**Comment by khronokernel** [comment]
Updated issue here to properly reflect status:

https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
