### ISSUE TITLE
Support Firewire booting in Catalina and later

### ISSUE THREAD

**Issue by internetzel** [dortania/OpenCore-Legacy-Patcher#267]
Apple disabled Firewire booting from Catalina on by not including the Firewire kernel extensions into the prelinked kernel any longer.
Presumably that's because of the security issues with DMA from the Firewire devices to the host memory.
But that's also the very reason for wanting that feature back, as it enables using a hard disk and especially an SSD at higher access speed, transfer rates and at very low CPU load.

For that purpose OpenCore can be used to "inject" the Mojave versions of the following kexts:
- IOFireWireFamily.kext, including AppleFWOHCI.kext
- IOFireWireSBP2.kext
- IOFireWireSerialBusProtocolTransport.kext

Those four extensions are open source and the Mojave and Catalina versions seem identical, except for some compilation issue fixes.
The Big Sur version seems to have received some DMA management related updates, but nevertheless the Mojave versions work well there (I'm currently booted typing this using those Mojave extensions in Big Sur).

I suspect one could as well inject those four kernel extensions from the OS version that is being booted, if possible and if the missing OSBundleRequired property doesn't matter.

I'd suggest offering the injection of those four kernel extensions as an option to the user, displaying a warning about the potential security risks.
The option might be omitted for the few Macs that cannot have Firewire, namely those that have neither native Firewire nor Thunderbolt ports (where the Thunderbolt Firewire adapter can be used). That's true for at least the following devices:
- MacBook5,1
- MacBook6,1
- MacBook7,1
- MacBookAir1,1
- MacBookAir2,1
- MacBookAir3,1
- MacBookAir3,2

**Comment by khronokernel** [comment]
Hello, thanks so much for researching and testing FireWire boot support! Will implement this shortly

**Comment by internetzel** [comment]
Using latest Action build I can now build into both Catalina and Big Sur with my hard drive connected via FireWire.

Thank you very much!

**Comment by Ausdauersportler** [comment]
Confirmation 2/2: 

Using the latest nightly build of OCLP 0.1.7 I can enable FireWire booting and boot into an (High Sierra, had to choose SecureBootModel Disabled) from an external enclosure using an iMac11,3. 

This is insanely great :-)
