### ISSUE TITLE
OCLP v0.1.6 hangs on its selection (iMac 2010 27" RX480)

### ISSUE THREAD

**Issue by kennycyw** [dortania/OpenCore-Legacy-Patcher#269]
iMac mid 2010 27" RX480 Big Sur 11.4, with OCLP on SD card.
OCLP v0.1.5 works with no problem (AMD patch with minimal setting)
v0.1.6 can also generate the EFI error-free, and shows up in Apple Bootpicker.
However, it hangs with a text screen upon selection without going into the OC Bootpicker.

![IMG_1790](https://user-images.githubusercontent.com/83110946/120916556-e0b51280-c6dc-11eb-82ed-5552e0f20963.jpg)

**Comment by Ausdauersportler** [comment]
Hi Kenny!

OCLP 0.1.6 works fine on my twin system (iMac11,3 with RX480 mobile). Heading to 0.1.7 dev version to check the firewire stuff.

Greetings!

**Comment by kennycyw** [comment]
I wonder whether the newly added XHCI PCI booting function in OCLP v0.1.6 could be the cause as I have done a USB 3 hack of my iMac:
https://forums.macrumors.com/threads/usb-3-wifi-ac-bt4-2-for-imac-27-mid-2010.2269396/

**Comment by khronokernel** [comment]
@kennycyw Try enabling UEFI -> Quirks -> ForgeUefiSupport in your config.plist (under EFI/OC/config.plist, where OCLP builds your EFI)

**Comment by kennycyw** [comment]
> @kennycyw Try enabling UEFI -> Quirks -> ForgeUefiSupport in your config.plist (under EFI/OC/config.plist, where OCLP builds your EFI)

Thanks. It does solve the OCLP Bootpicker problem. Marvellous !

While v0.1.6 adds XHCI UEFI driver for 3rd Party USB 3.0 Controllers for Boot Support from OpenCore Picker, it doesn't work with my PCIe USB 3 ports (Fresco Logic FL1100 chipset). 
When I put in a bootable USB finger in the USB 3 port, the OCLP BootPicker will hang with a white screen or freezing screen. Only when I remove the USG finger will the OCLP Picker resume normal working with possible mouse/keyboard movement.
Anyway, it is good that it doesn't necessitate a force shutdown.
Otherwise, the USB 3 works normally in Big Sur.
But for this I may have asked for too much ;-)

**Comment by hvdschmitt** [comment]
Similar (but not identical) here: using a 2-port nanoTECH USB3.0 expresscard34 with an MBP5,2. The chipset is FL1100 I believe. The card works well from booted BS, using driver AppleUSBXHCIFL1100.

I've now also set the ForgeUefiSupport, and the driver does proceed without hanging, whether an SSD with BS is plugged into one of the USB3.0 ports or not. But the OC boot picker doesn't show the SSD. It does show it when the SSD is connected to an on-board USB2 port.

I'm running OCLP 0.1.6 with DEBUG on and I'm using a debug build of the driver XhciDxe.efi (thanks again khronokernel for this). Attached is the protocol on the OCLP stick upto the point where the OC boot picker comes up.

[opencore-2021-06-07-170449.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6611140/opencore-2021-06-07-170449.txt)
![Bildschirmfoto 2021-06-07 um 18 45 07](https://user-images.githubusercontent.com/82234458/121068577-bf335400-c7cc-11eb-9385-67a6c82a2db6.png)
![Bildschirmfoto 2021-06-07 um 20 06 41](https://user-images.githubusercontent.com/82234458/121068601-c5293500-c7cc-11eb-8f35-8b42839b8fe5.png)
