### ISSUE TITLE
Keeps freezing at this screen

### ISSUE THREAD

**Issue by dabymartinez** [dortania/Opencore-Legacy-Patcher#27]
![image](https://user-images.githubusercontent.com/70119578/102363892-e29ae600-3f83-11eb-89f3-d7ae162409ee.jpg)

macmini 3,1  (2009 model) trying to boot into big sur installer

**Comment by Kameechewa** [comment]
This program isn't made for non-Apple hardware. You're going to have to follow the guide here https://dortania.github.io/OpenCore-Install-Guide/
