### ISSUE TITLE
Imessage Slow only when scrolling

### ISSUE THREAD

**Issue by jherm810** [dortania/OpenCore-Legacy-Patcher#274]
I am running Big Sur with the latest drivers on my 2011 macbook pro. Imessage is super sluggish and choppy when scrolling but the animation when i send a message is a crisp 60 fps. Its literally only slow when i scroll and nothing else.

**Comment by khronokernel** [comment]
Known issue, Catalyst scaling:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
