### ISSUE TITLE
MacPro5,1 with macOS Monterey hangs and Kernel Panic

### ISSUE THREAD

**Issue by jaydengamble6** [dortania/OpenCore-Legacy-Patcher#275]
When I attempt to boot my Monterey USB it just hangs at 'using 16384 buffer headers and 10240 cluster IO buffer headers' and when I reboot it says the the system kernel panicked even though there was nothing else to suggest that it had.

1. Boot into Monterey USB
2. Wait a few seconds
3. Hangs

**Screenshots**
![PXL_20210608_160446768.MP.jpg](https://user-images.githubusercontent.com/75391793/121219484-a5047f00-c87b-11eb-9596-b87cdcba1bab.jpg)

(Uploading EFI in a minute)

 - OS Running (macOS 11.4, Big Sur)
 - OS Patching (macOS 12.0, Monterey)
 - Model Patching (MacPro5,1)

↓I'll do this too when I'm in Big Sur↓

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Comment by khronokernel** [comment]
Duplicate:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/110

Monterey just made the issue worse, more machines are now affected more often. Work around is to reboot a few more times until it works. Cold boots can aid as well

**Comment by jaydengamble6** [comment]
@khronokernel I've tried to reboot like over 10-20 times and the only thing that happened was that it got down by around by 8 more lines. I'm also not using an NVME drive, I'm using a HDD, and I'm quite surprised if its a PCI issue as I only have a GTX 650 (GOP Flashed). Cold boots also didn't do much aswell.
