### ISSUE TITLE
Imac 7,1 stuck on booting the big sur installer 

### ISSUE THREAD

**Issue by DylanHP** [dortania/OpenCore-Legacy-Patcher#276]
![7DBD001C-3DEB-410F-95E9-02268FF6C984](https://user-images.githubusercontent.com/46071804/121230864-09c9d480-c890-11eb-8405-a57b0348be98.jpeg)
I continue to have this error trying to install mac os big sur on imac 7,1 whit upgraded perylin cpu. This error apperars after the boot selection first I select the efi whit opencore logo than the big sur install and after it charges almost to full this error appear.
Can anyone help me thanks in forward to anyone answering.

**Comment by Matts-Tech** [comment]
Same thing happens with my iMac8,1 as well.  There seems to be an issue with booting Big Sur on these older iMac models.
