### ISSUE TITLE
macOS Monterey: Boot issue after restart,  newUserClient failed: 0 0xe00002be 0x1000003bf

### ISSUE THREAD

**Issue by sharad-paghadal** [dortania/OpenCore-Legacy-Patcher#278]
**Describe the bug**
![IMG_2165](https://user-images.githubusercontent.com/20950495/121307075-3bd54800-c91d-11eb-918b-1ef05c7bd8f1.PNG)

**To Reproduce**
1. After installation everything is working, but after restart, getting this error on booting

**Screenshots**
![IMG_2166](https://user-images.githubusercontent.com/20950495/121306794-e436dc80-c91c-11eb-9267-49432372d8ae.PNG)

**Hardware (please complete the following information):**
 - macOS 12 (Monterey beta)
 - macmini5,2

**Additional context**
I think it may be because of I have 2 partition on my ssd
1. macOS Bigsur
2. macOS Monterey

May be that can be the problem, but since I've all setup in Bigsur drive, can not full format the whole ssd and try.

But if that is the reason for sure, I can erase full ssd.

**Comment by lulujyc** [comment]
This is due to the lack of graphical acceleration of the legacy HD 3000 gpu.

**Comment by sharad-paghadal** [comment]
In that case,I’m curious to know how jt booted and installed at first time. Until I restarted everything was working perfectly

**Comment by lulujyc** [comment]
> In that case,I’m curious to know how jt booted and installed at first time. Until I restarted everything was working perfectly

It's a race condition issue (reference: oclp devs).

**Comment by khronokernel** [comment]
Known issue, currently investigating:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/271
