### ISSUE TITLE
MacBookPro3,1 Issues

### ISSUE THREAD

**Issue by Kameechewa** [dortania/Opencore-Legacy-Patcher#28]
So with 0.0.8 I was finally able to install Big Sur. The installation was incredibly slow, expected, but still felt off. During the Big Sur setup screen it was very laggy. It would freeze for about 10 seconds and then be choppy for a few seconds while letting me move the mouse and then freeze again. 

What's broken:
Wifi
Bluetooth
Sound
Brightness

The computer also idles very hot.

**Comment by khronokernel** [comment]
Sounds and brightness issues are unfortunately expected, as the MacBookPro3,1 was before Apple switched to Nvidia based chipsets and so very little testing has been done. 

Wifi and bluetooth are an odd issue, as I believe they shipped with an Atheros AR5418 chipset which we support in the patcher pretty well.

To best diagnose these issues, can you send me an [IOReg](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip) running a natively supported OS(ie. El Capitan) as well as Big Sur? Simply open the app, then File -> SaveAs and send the .ioreg file it generates

If you're unable to run El Capitan, any other OS with semi proper support like one of dosdude's patchers should work

**Comment by Kameechewa** [comment]
I'm so sorry. I've been using the wrong model all along. I really have a 7,1, not a 3,1. However, now we're back to my original issue #18. When booting from the EFI on the flashdrive it tells me the Mac is not supported.
