### ISSUE TITLE
Support AQC107 10G NIC in macOS 11 and 12

### ISSUE THREAD

**Issue by mko-io** [dortania/OpenCore-Legacy-Patcher#280]
**Describe the bug**
I'm successfully install the latest macOS 12 beta1, but the my 3rd party AQC107 NIC still doesn't work same as big sur.

macOS 11 and 12 has builtin support for AQC107 driver, but require a few binary kernel patch

<img width="989" alt="Screen Shot 2021-06-10 at 01 56 37" src="https://user-images.githubusercontent.com/10137567/121405548-c2c30880-c98f-11eb-93b2-d737a50c9c31.png">

**Hardware (please complete the following information):**
 - Model Patching (ie. MacPro5,1)

I don't know how to patch the root directory, so it would be good to let OCLP has this patch as an option

thanks for your works

**Comment by khronokernel** [comment]
Oh seems reasonable, however do you know the device IDs affected by this? If not, simply sending an IOReg with this patch will do:

https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip

File -> SaveAs and send output

**Comment by khronokernel** [comment]
Closing as no response
