### ISSUE TITLE
Improve compatibility

### ISSUE THREAD

**Issue by Ivantroniks** [dortania/OpenCore-Legacy-Patcher#281]
**Describe the bug**

Hello excellent job with OCLP, to improve compatibility with catalina, I don't know if it will be possible to change the MinKernel from 20 to 19 in config.plist so that these kexts work in catalina:

-4331 Wifi Patch(Tested on MacBook6,1 “Catalina”)
	*AirportBrcmFixup.kext
	*AirportBrcmFixup.kext/Contents/PlugIns/AirPortBrcmNIC_Injector.kext (kext already disabled in 0.1.7)

-AppleIntelPIIXATA.kext (Tested on iMac8,1 and MacPro3,1 “Catalina”)

Thanks..

**Comment by khronokernel** [comment]
MacBook6,1's wireless card is supported natively, you'd need to disable our fake ID which cannot be done per OS on our side. However we have updated AppleIntelPIIXATA.kext to correctly reflect which OSes to apply
