### ISSUE TITLE
Hangs or dark screen at boot selection screen if thunderbolt docks are attached

### ISSUE THREAD

**Issue by tckoo1411** [dortania/OpenCore-Legacy-Patcher#284]
**Describe the bug**
If Akitio thunder dock is plugged in and powered on, will show dark screen or hangs at boot selection screen. When unplugged, will be able to proceed as normal. Also, both esata plug-in and usb plug in are not detected as bootable at boot screen.  

Tried with Kanex KTU20 can repeat the same error. With or without usb device plug in, will black screen or hang at boot selection screen. 

**Screenshots**
Akitio thunderbolt dock uses FL1100 chipset.
![Screenshot 2021-06-10 at 11 40 37 AM](https://user-images.githubusercontent.com/85660271/121461073-b915c100-c9e0-11eb-853f-87a472a4e78c.png)

Kanex KTU20 thunderbolt to usb 3 uses ASM1042.

**Hardware (please complete the following information):**
 - OS Patching : macOS 11.4, Big Sur
 - model : iMac 12,2
 - Model patching : using OCLP 0.16 

Thanks.

**Comment by lulujyc** [comment]
What is your boot disk? I have an NVMe boot disk and when TB devices are connected at boot, the Mac will simply not detect the NVMe boot disk. This is a firmware issue (with my MBP8,3 at least, persisted until the very last revision of the Boot ROM shipped with HS) and will be unlikely to be resolved soon. Hope that helps!

**Comment by khronokernel** [comment]
Please send OpenCore Debug log:
https://dortania.github.io/OpenCore-Legacy-Patcher/DEBUG.html#debugging-yourself

**Comment by khronokernel** [comment]
Closing as no response
