### ISSUE TITLE
MBP8,2 and MBP8,3: Non-working dual-GPU switch with TeraScale2 and HD3000

### ISSUE THREAD

**Issue by lulujyc** [dortania/OpenCore-Legacy-Patcher#286]
**Describe the bug**
The Dual-GPU MUX switch is not working (i.e. forced to either dGPU or iGPU and needs a reboot (changing NVRAM variables) to switch.

On High Sierra or on Catalina with Dosdude1 patches, the MUX switch is functional (although TeraScale2 acceleration is broken in Catalina), meaning that the machine on default use HD 3000 for power saving while moving to dGPU when graphics intensify apps are utilizing resources.  However, on OCLP TeraScale2 branch-patched Big Sur installations without extra NVRAM variables, the machine is forced on the dGPU on default, with no ways to switch to the iGPU unless the dGPU is soft-disabled.

**To Reproduce**
1. Patch a pre-existing BS installation using TeraScale 2 testing branch
2. See error

**Screenshots**
N/A

**Build Folder**
Just latest

**Comment by dhinakg** [comment]
Known issue, see #108

**Comment by lulujyc** [comment]
> Known issue, broken for everyone. see #108

Thanks for your reply! However, when tested on 2012 MBP 15, the dual GPU switching is not broken. Also, 2009/2010 dual GPU Macs don't seem to experience such issues.
