### ISSUE TITLE
Certain wireless routers do not show up and cannot be connected to (MacbookPro9,2)

### ISSUE THREAD

**Issue by v4ltages** [dortania/OpenCore-Legacy-Patcher#289]
**Describe the bug**
I was able to connect to my wireless router in Catalina but after installing Big Sur on my MacbookPro9,2 via OCLP, im unable to see it or connect to it even with its SSID.

**To Reproduce**
1. Install Catalina on MacbookPro9,2 and check all wireless connections
2. Setup a Big Sur install USB and configure it with OCLP for a MacbookPro9,2
3. Boot onto the USB and enter Big Sur recovery
4. Check all wireless connections to see if anything is missing
5. Try manually connecting to the wireless network via its SSID
6. Install Big Sur and after that, check if any wireless networks are missing
7. Try again manually connecting to the wireless network via its SSID
8. Reset all networking configuration (.plist's etc)

**Hardware (please complete the following information):**
 - OS Running (macOS 10.15.7, Catalina)
 - OS Patching (macOS 11.4 20F71, Big Sur)
 - Model Patching (MacbookPro9,2)
 - Networking (BCM5701)

**Comment by dhinakg** [comment]
Are all networks missing, or just yours?

**Comment by v4ltages** [comment]
My own network is missing and noticed a few other networks as well that are missing.

**Comment by khronokernel** [comment]
As no one else is able to replicate as well as no information to go off of like specific network information (WPA, etc), we recommend using a forum to general discussions as currently we developers cannot work off this information. MacRumors is a generally good place to check:

https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/
