### ISSUE TITLE
OpenCanopy.efi

### ISSUE THREAD

**Issue by Bustycat** [dortania/Opencore-Legacy-Patcher#29]
I am not sure about if OpenCanopy.efi should work with OpenCore generated by Legacy Patcher as the driver is included, but it does not work for my MacBookPro9,2. I followed the [guide](https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui) but the OpenCore boot screen is still not graphical.

**Comment by khronokernel** [comment]
By default our patcher has OpenCanopy disabled for performance reasons, if you've manually set it up I'd recommend ensuring you have everything configured correctly. We use the same OpenCore release binaries as Acidanthera's 0.6.4 package so there's no technical limitation on the part of the patcher

We've also verified OpenCanopy does in fact work on legacy Macs, however machines before Nvidia chipsets(ie. 2008 or earlier) are untested. Any additional concerns for OpenCanopy should be reported to Acidanthera, as we don't maintain OpenCorePkg

**Comment by MikeBeaton** [comment]
@Bustycat Did you ever get this to work? I commented back in the line `BuildOpenCore.BuildGUI()` in the main OCLP patcher file before re-running it, then copied in the `Resources` dir from the `OcBinaryData` project (as per the guide you've also linked) into the newly built OC folders, and it's worked on my MacBookPro10,2.
