### ISSUE TITLE
Assume Upgraded WiFi Always not available on 1.7

### ISSUE THREAD

**Issue by grzegorz914** [dortania/OpenCore-Legacy-Patcher#290]
**Describe the bug**
The option Assume Upgraded WiFi Always is not available on 1.7 Patcher

**Screenshots**
![Zrzut ekranu 2021-06-13 o 06 35 13](https://user-images.githubusercontent.com/28867813/121795478-af26d480-cc11-11eb-84b9-f82bd8a931b3.png)

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 12 Monterey)

**Comment by khronokernel** [comment]
Intentional, users misunderstood this setting when OpenCore will already detect the hardware correctly regardless. Please build on machine to get best hardware detection

**Comment by grzegorz914** [comment]
Im build on machine which already have installed OCLP, what if I want to upgrade OCLP and don't have other same machine without OCLP installed? 
This option was very helpful, may be get other Name for this option to better understand for what is it.

**Comment by dhinakg** [comment]
OCLP already has proper detection to ensure we don't mistakenly think you have the spoofed card when booted into Big Sur
