### ISSUE TITLE
External apple displays do not display correctly in System Preferences

### ISSUE THREAD

**Issue by boxy-boy** [dortania/OpenCore-Legacy-Patcher#291]
The Apple Cinema Display and Apple Cinema HD Display appear as generic displays, and also do not have any brightness control options. 
![Screen Shot 2021-06-12 at 11 07 42 PM](https://user-images.githubusercontent.com/69577030/121797185-808a0900-cbd3-11eb-860d-a4b411a7e8a8.png)

**Comment by boxy-boy** [comment]
okay, the brightness slider *magically* appeared but the icon still isn't right

**Comment by khronokernel** [comment]
Cinema Display icon appears on my Mac Pro, sounds like macOS bug not loading the icon:
 
![Screen Shot 2021-06-13 at 2 32 12 PM](https://user-images.githubusercontent.com/48863253/121821138-43b22680-cc54-11eb-95c1-a1b9390714e7.png)

Closing as cannot replicate
