### ISSUE TITLE
OCLP 0.1.6 has similar failure on both Big Sur 11.2.3 and Catalina 10.15.7 on MacPro5,1

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#294]
**Describe the bug**
While I was attempting to install Big Sur 11.4 with a bootable USB generated by OCLP 0.1.6 for a `MacPro5,1` I ran into a problem that I believed to be lumped into the [PCI race condition situation](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/110#issuecomment-851554590). After even stepping back to Big Sur 11.2.3 I had essentially the same error or a very similar looking error. 
![compared](https://p153.p0.n0.cdn.getcloudapp.com/items/8LuoPeY9/ef966079-7b92-40a2-937f-596056aef03c.jpg?v=ee38352e98ac9155cfd15f54ae272972)

I then decided to throw in the towel for moving to Big Sur for the time being and then booted back into Catalina 10.15.7. I was told that OCLP should be fine in booting Catalina so I went back into that system and I found very similar looking error, could someone please advise as to whether or not this is the same or a related issue and what this could indicate?:

I ultimately went back into OC 0.6.4 from a previous manual setup and the Catalina 10.15.7 system worked fine again, but I'd very much like to troubleshoot whatever may be going on here and perhaps even isolate the issue to get Big Sur 11.2 starting up.

**Hardware:**
 - OS Running: Big Sur 11.2.3 & Catalina 10.15.7
 - Patch executed on Catalina 10.15.7
 - Model Patching: MacPro5,1
 - ioreg-210 output: [macpro51.zip](https://p153.p0.n0.cdn.getcloudapp.com/items/GGuWReB1/87dd1bbe-e60e-45e0-b884-d4ec16ddece1.zip)

**Comment by khronokernel** [comment]
Unrelated, those are OpenCore and boot.efi logs. PCI Race condition is XNU based

**Comment by ylluminate** [comment]
I was not saying that these are related to the PCI Race condition issue, but rather that these may be another issue related since I'm having seemingly the same or similar points of failure in both Big Sur and Catalina on boot with the OCLP generated EFI - and thus perhaps a bug specific to my system based on some hardware. Make sense?
