### ISSUE TITLE
imac 12,2 unable to login after install the Post-Install Volume Patch and reboot.

### ISSUE THREAD

**Issue by beeopreeve** [dortania/OpenCore-Legacy-Patcher#295]
**Describe the bug**
imac 12,2 unable to login after install the Post-Install Volume Patch and reboot.

**To Reproduce**
After install the Post-Install Volume Patch and reboot.
Login page type in password.
Screen gone black for 5 second
Screen return to login page, does not login for me

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
macOS 11.4, Big Sur
 - Model Patching (imac 12,2)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**

**Comment by sharad-paghadal** [comment]
It's because of no support of TeraScale-2 in main branch.

Solution:
Merge main and TeraScale-2 branch in your local and then perform same tasks.

**Comment by khronokernel** [comment]
This is already in mainline with 0.1.7
