### ISSUE TITLE
FileVault does not work when root patches are installed

### ISSUE THREAD

**Issue by Lars-Br** [dortania/OpenCore-Legacy-Patcher#297]
Unlike the requirement that SIP be disabled, the missing FileVault support on systems that need root patches for graphics acceleration (now including HD 4000 systems) is a really serious problem, because it means you cannot really use your portable Mac anywhere where it might be stolen (or, you cannot save any private data on that Mac).
Has it already been found out that it is definitely impossible to ever enable FileVault on root-patched systems, or is this a current limitation that might be resolved in the future?

**Comment by lulujyc** [comment]
It is impossible (as of now and likely in the future as well) and is a known problem.

**Comment by khronokernel** [comment]
FileVault could never be supported on a root patched volume without compromising heavily on security with extremely dangerous hacks, stay on Big Sur as you'll still get 3 more years of security updates anyways or sell the machine and invest in something newer if you absolutely require Monterey support
