### ISSUE TITLE
No more keyboard backlight 

### ISSUE THREAD

**Issue by Reeno13** [dortania/OpenCore-Legacy-Patcher#299]
Hi,
I've just used the OpenCore patch for installing Big Sur (11.4) on my MacBook Pro 13" Mid-2010 (MacbookPro 7,1), and the keyboard backlight doesn't work anymore.

- The F5 and F6 keys are both well detected but the icon displayed is always like level off (an empty bar, something like that [https://imgur.com/a/c0i5JWO](url))?
- In System Preferences/Keyboard pane, there is no option about backlight like I don't have a backlight keyboard 
- In Control Center, there is no Keyboard Brightness settings.

Before patching with OpenCore, I used dosdude1 Patch with Catalina and the keyboard backlight worked (and the controls too). 
First I applied OpenCore patch v0.1.6 but today I try v0.1.7 and the result is the same.
I also try to reset SMC or to fix it with the LED CMS App proposed by YouTube RoyMacs, but no result too.

Please tell me if something can fix this.

Thank you

Reeno

**Comment by khronokernel** [comment]
Duplicate:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by Reeno13** [comment]
> Duplicate:
> #108

Thank you khronokernel for your quick answer. I missed this problem report when I looked on the Github page.
