### ISSUE TITLE
MacBookPro9,1 boots to black screen

### ISSUE THREAD

**Issue by dennes544** [dortania/OpenCore-Legacy-Patcher#3]
MacBookPro9,1, NVIDIA GeForce GT 650M boots to black screen with Big Sur 11.0.1 installer. After verbose boot it shows mouse cursor for a second, the blackscreen and backlight disables

NVRAM is cleared before trying to boot

**Comment by khronokernel** [comment]
Hmmm odd, can you send me the EFI folder the patcher created?

**Comment by dennes544** [comment]
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5631986/EFI.zip)

I used firstly 0.0.3 release(had same issue), then tried to use last commit version (0.0.4), where you fixed PCI paths. In archive efi folder generated by 0.0.4

**Comment by dennes544** [comment]
on 0.0.4 error still persists btw. before installing opencore to efi, i manually deleted old files from efi (just to be sure)

**Comment by khronokernel** [comment]
I believe I found an issue, right now the patcher uses MacBookPro11,2 as the new SMBIOS however this actually is a bit broken as your machine is a dual GPU model while this SMBIOS is a single GPU machine. I added a new EFI below that uses MacBookPro11,3 with a proper iGPU+dGPU setup, please report back if this resolved your issue
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5632014/EFI.zip)

**Comment by dennes544** [comment]
will reply in 5-10 mins

**Comment by dennes544** [comment]
Nope, still same black screen

**Comment by dennes544** [comment]
I can try to boot my big sur installation patched by micropatcher and the get bootlog, will this be helpful?

**Comment by dennes544** [comment]
[boot.log](https://github.com/dortania/Opencore-Legacy-Patcher/files/5632184/boot.log)

I think found reason, search "kernel: GFX0-0x1ac-A::_doControl(23) not gated" and further

**Comment by dennes544** [comment]
Tried to boot without WhateverGreen, still no luck

**Comment by khronokernel** [comment]
[EFI.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5637175/EFI.zip)

As mentioned in issue #6, very likely AGDP is at fault. When you have some free time, test this build out

**Comment by dennes544** [comment]
Still same black screen, even if added -no_compat_check as mentioned in #6

**Comment by WTannen** [comment]
I'm trying to install Big Sur on my mid-2012 MacBook Pro (dual GPU) using OpenCore Legacy Patcher v0.0.6 and I'm having the same issue that dennes544 reported here. After booting from the USB stick and selecting the EFI Boot Option I get the verbose boot, the mouse shows cursor for a second and then the blackscreen and backlight disables

Am I missing something or is it a bug with the patcher?

**Comment by TinyHim** [comment]
Having same issue on my MacBook Pro9,1 (dual gpu)
Have tried both the 0.0.6 Release package, as well as the master.

**Comment by doogiecode** [comment]
Chiming in to say I'm having the same issue on my MBP 9,1 (NVIDIA GeForce GT 650M). Would be glad to help troubleshoot.

In case any of this helps: naïvely shooting in the dark using [this page](https://dortania.github.io/GPU-Buyers-Guide/misc/bootflag.html#amd-boot-arguments) (which I know is more geared toward Hackintoshes), I first tried adding `agdpmod=vit9696` to the `boot-args` right after `agdpmod=pikera`. Nothing seemed to change on boot, still a black screen. I then tried appending `nv_disable=1` for no GPU acceleration. This got me past the black screen and into the Big Sur installer, but of course, I could tell the graphics were under the weather.  Was cool to see the spoofed `MacBookPro11,2` after running `sysctl hw.model` in the terminal, but I decided I didn't want to do the install.

(Furthermore: I also tried booting into my Catalina install with OpenCore using these args, and instead of booting my OS it booted the recovery partition, also without GPU acceleration. I'm new to this, so I'm not sure if this is typical OpenCore behavior somehow. And furthermore beyond that: once I removed the thumb drive and tried booting my Catalina disk again without OpenCore, the progress under the Apple logo was making no progress after several minutes. This is strange to me, because before I tweaked the arguments it was booting fine though verbose, and I wouldn't guess any of the new arguments I put in would cause an indefinite boot delay. After I reset the PRAM to clear the arguments, my Catalina install is now working again as usual, so I've got that going for me, which is nice.)

**Comment by jbdamiano** [comment]
With pikera I have a black screen on boot
If I replace pikera with vit9696 I don't have a blank scrren on boot but the system doesn't recover from sleep mode, I have a black screen

**Comment by jbdamiano** [comment]
I added agdpmod=vit9696 before agdpmod=pikera. The system boot normally

I have always the sleep issue. I close the lip, wait a couple of minutes and reopen it. The screen remains black. But If I attach an external screen, It is working correctly. On internal screen I can guess the displayed window like the brightness is at minimum.

**Comment by jbdamiano** [comment]
I have always the same issue on the last version
In fact by looking in the log file when the problem occurs during the boot is with this traces in displaypolicyd,1:0.0.log
```
2021-03-17 09:06:27.784989+0100: PolicyEngine started: 7800020000000000, Time: Wed Mar 17 09:06:27 2021
2021-03-17 09:06:28.107067+0100: NOTICE: kAGDCCallbackCapability: 0x0 []
2021-03-17 09:06:28.613517+0100: NOTICE: Vendor portmap 0x7f0000 mst 0x700000 ddc 0xe0000 aux 0x700000
2021-03-17 09:06:28.987413+0100: NOTICE: Features policyd 0x20000000 kernel 0x0
2021-03-17 09:06:28.988744+0100: NOTICE: FB AGDC state FB[0] - OFF
2021-03-17 09:06:28.988896+0100: NOTICE: inject FB[0] change
```
With my openCore configuration that doesn't change the model version I don't have this line and the display is working correctly

**Comment by LIPA85** [comment]
Hi, unfortunately I have the same problem above on my MacBook Pro 9,1. Black screen at boot with smbios spoofing. Is there something else to try? Thank you

**Comment by khronokernel** [comment]
Currently unavailable to provide test binaries, however for those more comfortable with OpenCore I do have some things you can try. Regarding debugging OpenCore, we have dedicated docs here:

* https://dortania.github.io/OpenCore-Legacy-Patcher/DEBUG.html

The main thing you'd want is to enable Kext DEBUG and know how to mount the EFI for editing.

### Test 1: AGDP Ignore

For the first test, mount OpenCore's drive and edit the /EFI/OC/config.plist file:

* `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args`:
  * Change `agdpmod=pikera` to `agdpmod=ignore`

### Test 2: No WEG

Disable WhateverGreen in your config.plist:

* Kernel -> Add -> Item 1:
  * Enabled: False

### Test 3: Manual Patch

Disable WhateverGreen in your config.plist and add the following patch to Kernel -> Patch:

```
Arch       |  String | x86_64
Comment    |  String | board-id to board-ix patch
Count      | Integer | 1
Enabled    | Boolean | false
Find       |   Data  | 626f6172642d6964
Identifier |  String | com.apple.driver.AppleGraphicsDevicePolicy
Limit      | Integer | 0
Mask       |   Data  | 
MaxKernel  |  String |
MinKernel  |  String |
Replace    |   Data  | 626f6172642d6978
ReplaceMask|   Data  | 
Skip       | Integer | 0
```

* Note: Specific fields were left blank on purpose

**Comment by dennes544** [comment]
I thought, maybe instead patching board-id to board-ix, we need to override mbp11,2 board-id with mbp9,1’s in driver? So it will think it’s loading mbp11,2, but with mbp9,1’s graphics parameters?

**Comment by khronokernel** [comment]
@dennes544 Add the following to boot-args in OpenCore will do exactly that:

* `shikigva=40`
* `shiki-id=Mac-4B7AC7E43945597E`

The main issue with this is it replaces the board ID throughout macOS and most likely will break OTA updates, since it'll see an unsupported model. Additionally other drivers may break in the patcher such as USB maps

Regarding patching 1 single kext, would be unlikely to do in-memory without breaking the kext's functionality (ie. GPU switching). We try to avoid on-disk patching whenever possible as it breaks a lot of macOS's security including FileVault, SIP, etc

That's why I recommend trying the tests listed above instead

**Comment by dennes544** [comment]
Ok, I will, I have one more question, can I with opencore have multiple configs, and change the on boot (like in clover)? Just now I have config without changing board-id, and mbp9,1 is my work daily driver. Won’t mess it up

**Comment by khronokernel** [comment]
I would recommend just putting OpenCore on a spare USB with a FAT32 partition, and testing the patches that way.

But short answer, no OpenCore does not support config selection

> Just now I have config without changing board-id

Wait do you have a config that's booting correctly? Or am I misreading that

**Comment by dennes544** [comment]
Config without replacing board-id, it’s just do no-compat-check and fix WiFi kext. Of course no ota updates

**Comment by khronokernel** [comment]
@dennes544 Actually Dhinak pointed out a solution to injecting new AGDP data, I will have a kext ready in a bit (half an hour? Maybe)

**Comment by dennes544** [comment]
@khronokernel that would awesome, tired of upgrading via usb

**Comment by khronokernel** [comment]
[AGDP-Override.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6184968/AGDP-Override.kext.zip)

@dennes544 Try this kext

**Comment by dennes544** [comment]
@khronokernel Do i need some boot-args with it, or i can just leave no-compat-check?

**Comment by khronokernel** [comment]
Oh you're supposed to use OpenCore normally, so you don't want `-no_compat_check`
I would recommend the USB method to avoid an unbootable Mac

**Comment by dennes544** [comment]
Ofc i will use USB :) 
Just i will apply SMBIOS to my config, not generated for now

**Comment by khronokernel** [comment]
In case the above kext doesn't work, he's another one overriding AppleMuxControl's plist:

* [AMC-Override.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185022/AMC-Override.kext.zip)

I recommend you try them both together if you still have issues just using AGDP-Override.kext

**Comment by dennes544** [comment]
`<dict>
						<key>Comment</key>
						<string></string>
						<key>PlistPath</key>
						<string>Contents/Info.plist</string>
						<key>Enabled</key>
						<true/>
						<key>MaxKernel</key>
						<string>20.99.99</string>
						<key>MinKernel</key>
						<string>19.0.0</string>
						<key>Arch</key>
						<string>Any</string>
						<key>BundlePath</key>
						<string>AGDP-Override.kext</string>
				</dict>`

Am i doing it right? I dont need Executable path here?

**Comment by khronokernel** [comment]
Yup looks good, it's a plist only kext so no executable

**Comment by dennes544** [comment]
And i need to <Add> section, or <Patch> ?

**Comment by khronokernel** [comment]
Needs to be in `Add` yeah

**Comment by dennes544** [comment]
![E65A0FF3-EFD0-48AC-967B-FE4EFA2E2F32](https://user-images.githubusercontent.com/4429342/112056443-11b78980-8b69-11eb-822d-864e8e7e140b.jpeg)

with adgp kext I get this, without it just boots to black screen, as always

**Comment by dennes544** [comment]
@khronokernel It’s something about prelinked kernel, if I get it right

**Comment by LIPA85** [comment]
@khronokernel i have first tried AGDPoverride alone without success ( I mean black screen), I then installed both AGDP override and AMC ovveride and again.... always black screen. 
I attach the config.plist with both one added to "add" section for troubleshooting
[config.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185199/config.plist.zip)

**Comment by khronokernel** [comment]
@dennes544 
[AGDP-Override.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185233/AGDP-Override.kext.zip)

Try this guy

**Comment by dennes544** [comment]
@LIPA85 you added it wrong place. Its need to be added in Kernel section, not ACPI

**Comment by LIPA85** [comment]
@dennes544 sorry... my fault. I'll correct and give you a feedback in some minutes

**Comment by dhinakg** [comment]
Here's an updated AMC Override: 
[AMC-Override.kext 2.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185254/AMC-Override.kext.2.zip)

**Comment by dennes544** [comment]
@khronokernel , with new agdp black screen, will try new amc as well

**Comment by dennes544** [comment]
Fix for 11,2 or 11,3 board?

**Comment by khronokernel** [comment]
For MacBookPro11,3 = Mac-2BD1B31983FE1663

**Comment by dennes544** [comment]
Both kexts, 11,3 id, still same black screen…

**Comment by LIPA85** [comment]
for me always black screen... with both AMC override and AGDP override (the latest one).
here config.plist updated
[config.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185290/config.plist.zip)

**Comment by khronokernel** [comment]
@dennes544 Try disabling WhateverGreen, forgot to mention removing it

**Comment by dennes544** [comment]
@khronokernel dont have it in my config

**Comment by dennes544** [comment]
can send it to you, if you wish

**Comment by khronokernel** [comment]
Try enabling WhateverGreen then, will need to think of some other fixes to try

**Comment by LIPA85** [comment]
@khronokernel in my configuration I have weathervergreen.... always black screen with or without it.

**Comment by khronokernel** [comment]
So doing some more research, I see the following:

* MacBookPro9,2 kext matches in Big Sur (Mac-4B7AC7E43945597E):

```
./AppleGraphicsPowerManagement.kext/
./AppleGraphicsControl.kext/Contents/PlugIns/AppleMuxControl.kext/
./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/
```

* MacBookPro11,3 kext matches in Big Sur (Mac-2BD1B31983FE1663):

```
./AppleGraphicsPowerManagement.kext/
```

Knowing this, I honestly can only see 1 problematic kext left for us to mess with. Below I've included an override for AppleGraphicsPowerManagement.kext:

* [AGPM-Override.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185628/AGPM-Override.kext.zip)

**Comment by dennes544** [comment]
@khronokernel will try now

**Comment by dennes544** [comment]
And here mbp9,1 not 9,2

**Comment by dennes544** [comment]
@khronokernel Sadly, but still same

**Comment by dennes544** [comment]
![Снимок экрана 2021-03-23 в 02 43 19](https://user-images.githubusercontent.com/4429342/112072086-205e6a80-8b82-11eb-9aeb-200dabd2cd0a.png)
![Снимок экрана 2021-03-23 в 02 42 58](https://user-images.githubusercontent.com/4429342/112072088-20f70100-8b82-11eb-8449-131e53257b0d.png)

@khronokernel , it was misinformation. It does boot, gpu switching actually working, but there some problem, display wakes up only after putting to sleep and then waking up. 

Also not working wifi, and audio and maybe some other issues due to my incomplete config for 11,3. But need to somehow fix display enable after boot

**Comment by khronokernel** [comment]
> display wakes up only after putting to sleep and then waking up.

Hrrmmm, that's not great but points me somewhere. Skylake has a similar bug on hackintoshes which required forcing all displays online. The boot-arg was `igfxonln=1` however requires WhateverGreen to be enabled

Otherwise, not entirely sure what else to try currently, will think a bit more

**Comment by dennes544** [comment]
I will tomorrow try WEG, and will send to you boot log where its boots to disabled screen

**Comment by khronokernel** [comment]
@jbdamiano I saw your comment here:

https://github.com/dortania/OpenCore-Legacy-Patcher/issues/72#issuecomment-805170186

Curious, I wonder will adding `agdpmod=vit9696` and `igfxonln=1` to boot-args work? That should aid in the wake issues with the iGPU, it's a common fix for Skylake hackintoshes. Curious if the same will apply to the MBP9,1

**Comment by jbdamiano** [comment]
@khronokernel I tried the AMC and AGDP patch with WEG configured with agdmod=vit9696. Now it seems that the boot issue is fixed and the wake up too. But I'm not 100% sure because I don't know why the system is not changed to 11,3 it remains 9,1. I have never tested to set the igfxonln=1

**Comment by LIPA85** [comment]
> @jbdamiano I saw your comment here:
> 
> [#72 (comment)](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/72#issuecomment-805170186)
> 
> Curious, I wonder will adding `agdpmod=vit9696` and `igfxonln=1` to boot-args work? That should aid in the wake issues with the iGPU, it's a common fix for Skylake hackintoshes. Curious if the same will apply to the MBP9,1

Hi Khrono, i have just tried the combination above and finally... no black screen after boot! now the only thing is that it seems that we loose the GFX automatic switch  since at boot it starts (and maintain) the Nvidia 650m

**Comment by khronokernel** [comment]
> I tried the AMC and AGDP patch with WEG configured with agdmod=vit9696. Now it seems that the boot issue is fixed and the wake up too.

Awesome!

> . But I'm not 100% sure because I don't know why the system is not changed to 11,3 it remains 9,1

Currently in the patcher, you actually can't see what the "spoofed" SMBIOS is as we only replace the board ID. Easiest way to check is running [dmidecode](https://github.com/acidanthera/dmidecode/releases/) and seeing if `Mac-2BD1B31983FE1663` shows up

@LIPA85 Hrrmm, not great but interesting, can you try the combination @jbdamiano tried? ie. the latest AMC and AGDP-Overrides with `agdmod=vit9696` in boot-args?

**Comment by jbdamiano** [comment]
@LIPA85 you lost the switch because displaypolicyd needs the Nvidia card.

**Comment by LIPA85** [comment]
@khronokernel at the moment I'm booting with both latest AMC and AGDP version and the Config.plist attached
[config.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6192437/config.plist.zip)

**Comment by khronokernel** [comment]
@LIPA85 Did it boot or still black screen?

**Comment by LIPA85** [comment]
boot is ok, sleep/wake also is working just fine. only thing that I lost is the automatic GPU switching.

**Comment by jbdamiano** [comment]
@LIPA85 the automatic switch is block because displaypolicyd is using the Nvidia card. If you kill the process is it working correctly

**Comment by LIPA85** [comment]
> @LIPA85 the automatic switch is block because displaypolicyd is using the Nvidia card. If you kill the process you go back to the intel card

Even if I kill it, It suddenly restarts...

**Comment by jbdamiano** [comment]
@LIPA85 strange because I killed it and it is not restarted And now I'm using the intel card. I'm using the AGDP override and the AMC override version 2

**Comment by khronokernel** [comment]
Hmm still not ideal that the dGPU is stuck enabled until you restart the process, can you 2 test all 3 kexts with `agdpmod=vit9696`?:

* https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185628/AGPM-Override.kext.zip
* https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185254/AMC-Override.kext.2.zip
* https://github.com/dortania/OpenCore-Legacy-Patcher/files/6185233/AGDP-Override.kext.zip

Note they're the same exact kexts from earlier in the thread, just copied them here so easier to grab

**Comment by jbdamiano** [comment]
@khronokernel I have to do a sudo pkill displaypolicyd to recover the dynamic switching.
I tested with the last OCLP by adding the agdpmod=vit9696 and the 3 kexts

Except that the boot and wakeup are working now

**Comment by cgrazy** [comment]
using boot args 'keepsyms=1 debug=0x100 agdpmod=vit9696' and these three kexts, my MBP9,1 is booting and waking up after lid was closed and after 'pmset sleepnow'.

**Comment by khronokernel** [comment]
@cgrazy Awesome, thanks for confirming. Was `sudo pkill displaypolicyd` required for you as well to get the iGPU to activate again or did auto switching work on boot up regardless?

**Comment by cgrazy** [comment]
I've killed nothing ... And there was nothing obviously wrong.

**Comment by khronokernel** [comment]
Oh very nice! Ok so must be a case by case situation. Knowing that, I'm much more confident closing this issue when patchers updated.

Thanks so much to everyone in this issue thread! Really appreciate all the troubleshooting you guys have gone through for us!

**Comment by jbdamiano** [comment]
@cgrazy what graphical card is activated by the system ? The About this Mac Shows the NVIDIA or Intel Card ?

**Comment by cgrazy** [comment]
@jbdamiano it's the NVIDIA

**Comment by jbdamiano** [comment]
@cgrazy So you boot on Nvidia and normally you must be on Intel I have to kill the displaypolicyd to switch back on intel card and after that it is ok how switch is working correctly

@khronokernel Thanks for your patch because now we can use OCLP

**Comment by dennes544** [comment]
@khronokernel `sudo launchctl disable system/com.apple.displaypolicyd` does the trick, you dont have to kill displaypolicyd every reboot, but i think we need to find way, to disable it from opencore (you know apple, it can be automatically reenabled on each update)

**Comment by LIPA85** [comment]
I can also confirm the same situation as @cgrazy and @jbdamiano 
With all the latest 3 kexts and "keepsyms=1 debug=0x100 agdpmod=vit9696'" boot-args the system starts with NVIDIA one.
If I run "sudo pkill displaypolicyd" in terminal it goes back to the intel one... and it stays with that. Then I have tried to launch Photoshop (that usually use the NVIDIA 650m) and it switch to that, after close it returns back to the intel.

For now thank you all for your efforts!

**Comment by dhinakg** [comment]
Instead of killing `displaypolicyd` on boot, can you try this?
[RestrictEvents-1.0.1-DEBUG.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6192810/RestrictEvents-1.0.1-DEBUG.zip)

**Comment by dennes544** [comment]
@dhinakg It might work, but its not blocking `/usr/libexec/displaypolicyd`. I will try it, if won't work, it will need be recompiled with this binary blacklisted

**Comment by dennes544** [comment]
@dhinakg Or your kext already recompiled?

**Comment by dhinakg** [comment]
It's not the stock kext.

**Comment by dennes544** [comment]
@dhinakg didnt work

**Comment by dhinakg** [comment]
Was worth a try, will explore more later.

**Comment by khronokernel** [comment]
As this issue is mostly resolved, I will be closing. However we do plan to keep an issue open for tracking regarding `displaypolicyd` issues: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/116
