### ISSUE TITLE
Specialised OpenCore.efi?

### ISSUE THREAD

**Issue by Bustycat** [dortania/Opencore-Legacy-Patcher#30]
OpenCore.efi inside OpenCore generated by Legacy Patcher is slightly smaller than the one of OpenCore’s release package. I tried to replace it with the release one, yet a warning message for not properly shutting down would pop up after every booting. Does it mean that we could update OpenCore.efi only via Legacy Patcher in the future?

**Comment by khronokernel** [comment]
There are multiple components to OpenCore, not just OpenCore.efi.See here for more info:

* https://dortania.github.io/OpenCore-Post-Install/universal/update.html

We do have plans to add an update function to OpenCore, would just generate a new OpenCore EFI with serials transferred to ensure users get the latest fixes as well. 

Also looked into OpenCore's binaries a bit more, seems I never updated the binaries on main. Will update them shortly

**Comment by Bustycat** [comment]
The other base files are exactly the same so that is why I am curious about OpenCore.efi.
