### ISSUE TITLE
Big Sur 11.2.3 install kernel panic on final reboot after 0.1.7 build + install

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#300]
Used the new release 0.1.7 to build EFI for a MacPro5,1. This EFI boots Catalina 10.15.7 without any problem, but when installing macOS 11.2.3 onto a blank drive for a fresh install I received the following panic on what I believe to be the final reboot of the installer:
![panic](https://p153.p0.n0.cdn.getcloudapp.com/items/geugqADG/da8280f9-d194-4daa-94b2-70b2fe5ca28e.jpg?v=2b04d834e03c645da89eacb36142716f)

After powering down and restarting, the system hung at this point:
![boot hang](https://p153.p0.n0.cdn.getcloudapp.com/items/kpuDw6dr/e56b6310-3589-4e7e-911c-2dbabd3015a2.jpg?v=7bc179bf94acdca201d9a6e9d6377b6b)

**Build ~~Folder~~ Steps (folder missing after reboot):**
```
Building Configuration on model: MacPro5,1
Created build folder

- Adding OpenCore v0.7.0 DEBUG
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.4
- Adding WhateverGreen.kext 1.5.1
- Adding RestrictEvents.kext 1.0.3
- Adding NightShiftEnabler.kext 1.1.0
- Adding SMC-Spoof.kext 1.0.0
- Adding AppleMCEReporterDisabler.kext 1.0.0
- Adding CPUFriend.kext 1.2.4
- Adding AppleALC.kext 1.6.2
- Adding SidecarFixup.kext 1.0.2
- Adding DebugEnhancer.kext 1.0.3
- Fixing PCIe Storage Controller (1) reporting
- Fixing PCIe Storage Controller (2) reporting
- Fixing PCIe Storage Controller (3) reporting
- Found Wireless Device 14E4:43A0 (pci14e4,43a0)
- Adding AirportBrcmFixup.kext 2.1.3
- Adding USB-Map.kext
- Adding AppleGraphicsPowerManagement Override
- Enabling FireWire Boot Support
- Adding IOFireWireFamily.kext 1.0.0
- Adding IOFireWireSBP2.kext 1.0.0
- Adding IOFireWireSerialBusProtocolTransport.kext 1.0.0
- Found dGPU (1): 1002:687F
- Found dGPU (1) at PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
- Adding Mac Pro, Xserve DRM patches
- Enabling NVMe boot support
- Adding OpenCanopy GUI
- Adding ExFatDxeLegacy.efi
- Adding SATA Hibernation Patch
- Enabling Verbose boot
- Enabling DEBUG Kexts
- Enabling DEBUG OpenCore
- Enabling ShowPicker
- Disabling SIP
- Disabling AMFI
- Disabling SecureBootModel
- Setting macOS Monterey Supported SMBIOS
- Spoofing to MacPro7,1
- Using Board ID: Mac-27AD2F918AE68F61
- Using Minimal SMBIOS patching
- Cleaning up files
```

**Hardware (please complete the following information):**
 - OS Running: Works: macOS 10.15.7, Catalina -- Fails: installation of 11.2.3, Big Sur
 - Model Patching: MacPro5,1

**Comment by ylluminate** [comment]
For what it's worth, I attempted installation again with another SSD that was brand new and uninitialized and had the same result with the 11.2.3 install:
![panic repeat](https://p153.p0.n0.cdn.getcloudapp.com/items/RBulWJG4/f9ef40f0-02e8-43b3-bf73-2d09eebf2c50.jpg?v=c107b331ef98981d5c84bc8830ef988b)

**Comment by ylluminate** [comment]
As per @khronokernel Lilu is indeed the issue here as per this commit which broke support: https://github.com/acidanthera/Lilu/commit/1e944292e99817c485e846ab73275521dcbc1ee3

**Comment by dhinakg** [comment]
Please test with https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2998748714/artifacts/67787533

**Comment by ylluminate** [comment]
Confirmed - resolved.
