### ISSUE TITLE
No Night Shift in Monterey on iMac 12,1

### ISSUE THREAD

**Issue by caleb39411** [dortania/OpenCore-Legacy-Patcher#301]
**Describe the bug**
On my iMac 12,1 with an upgraded Metal graphics card, on macOS Monterey Developer Beta 1, Night Shift is not an option in display settings, and is greyed out in Control Centre.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app or .command '...'
2. Enter '....'
3. See error

**Screenshots**
Monterey:
![Screenshot 2021-06-15 at 07 57 27](https://user-images.githubusercontent.com/16021499/122007446-d87d6700-cdaf-11eb-8dfa-d422a43a0767.png)
Big Sur:
![Screenshot 2021-06-15 at 07 51 43](https://user-images.githubusercontent.com/16021499/122007460-db785780-cdaf-11eb-9afa-429ddac719b7.png)
(Also note that the incorrect image for the display is used in Monterey)

**Build Folder**
[OC.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6653533/OC.zip)

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 12.0 Beta (21A5248p), Monterey)
 - Model Patching (ie. iMac12,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](?raw=true) and send the output
[Caleb’s iMac.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6653546/Caleb.s.iMac.zip)

**Additional context**
The GPU has been replaced with a Nvidia Quadro K2100M with patched VBIOS.

**Comment by khronokernel** [comment]
Unfortunately would need to be addressed with the author of NightShiftEnabler:

https://github.com/cdf/NightShiftEnabler
