### ISSUE TITLE
Cannot Open OCLP

### ISSUE THREAD

**Issue by bnaambo** [dortania/OpenCore-Legacy-Patcher#305]
**Describe the bug**
When Opening OCLP terminal spits out errors

**To Reproduce**
1. Open app

**Screenshots**

> bennaambo@Bens-MacBook-Pro ~ % /var/folders/rf/7cvwczz95174_5l39th9wmxm0000gn/T/AppTranslocation/7662D7DD-6966-423E-97B7-C79BD853EEA7/d/OpenCore-Patcher.app/Contents/MacOS/OpenCore-Patcher ; exit;
> Traceback (most recent call last):
>   File "OpenCore-Patcher.command", line 276, in <module>
>   File "OpenCore-Patcher.command", line 29, in __init__
> TypeError: argument of type 'NoneType' is not iterable
> [3689] Failed to execute script OpenCore-Patcher
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> Deleting expired sessions...none found.
> 
> [Process completed]

**Hardware (please complete the following information):**
 - macOS 11.2.3, Big Sur
 - iMac12,1

**Comment by khronokernel** [comment]
Resolved in master
