### ISSUE TITLE
DRM issue

### ISSUE THREAD

**Issue by AntonioJOrtiz64** [dortania/OpenCore-Legacy-Patcher#306]
Apple TV movies or series and Music videos can not displayed.

The same problem happened treating to see a movie in Netflix using safari. If I use Chrome Netflix and Apple TV works fine

macOS big sur 11.4
MacBook Pro 8,1

**Comment by khronokernel** [comment]
Correct, hardware DRM is unsupported on legacy GPUs in newer OSes

**Comment by AntonioJOrtiz64** [comment]
Thank you so much

**Comment by Ausdauersportler** [comment]
If you are interested in some details about the current DRM state for Catalina and Big Sur (and possibly Monterrey) read this [page](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md)

You can assume that the number of supported dGPU will not become bigger with Monterey.
