### ISSUE TITLE
Wifi problem on Macbook PRO 15 Late 2013

### ISSUE THREAD

**Issue by boff64** [dortania/OpenCore-Legacy-Patcher#307]
Hi, there is a problem with Wifi on Macbook Pro 11,2. When I boot from USB, wifi is working, when I install Patched EFI on internal drive and boot from it, wifi as adapter is working but I can't connect to any network I've connected before. Problem is consistent and it works/does not work every time I boot from USB (work)/Internal drive (don't work).

**Comment by khronokernel** [comment]
USB and internal drive's OpenCore should be identical and macOS cannot tell the difference from UEFI space. Please further investigate there's no other variable affecting this
