### ISSUE TITLE
SBM defaults to False in 0.1.9

### ISSUE THREAD

**Issue by jgleigh** [dortania/OpenCore-Legacy-Patcher#308]
Just opened OCLP 0.1.9 and noticed that the default value for SBM is now False which seems backwards. This is on a MacPro5,1 with a Metal GPU (5700 XT).

**Comment by khronokernel** [comment]
With macOS Monterey there seems to be bugs where the machine will corrupt the secure boot manifests and would end in a RecoveryOS cycle. To avoid this issue with users, we opt to disable SecureBootModel by default until either resolved by Apple or work arounds are found

Users can override this in patcher settings
