### ISSUE TITLE
Stuck on Login screen -> Previously It was working fine

### ISSUE THREAD

**Issue by sharad-paghadal** [dortania/OpenCore-Legacy-Patcher#309]
When Terascale2 support was not in main branch, I tried cloning Terascale2 branch and applied patch. It was working perfectly at that time. But now as Terascale2 is merged into Main branch I did fresh install again and tried patching - and resulting this Login loop issue.

Any help?

**Comment by Tiger-AC** [comment]
I am happy to report that I have just fresh installed Big Sur 11.4 with OCLP v0.1.9 on a mid-2011 HD6970 27" iMac and it works fine after applying Post-Install Volume Patch (I enabled Terascale2 in Patcher Settings first, not sure if this makes difference), together with ResXtreme.app to reduce the colour resolution.
The iMessage sluggish issue (the "Catalyst Apps Scrolling Slow" issue) is the only thing really bugs me. This same issue also appears on a Late 2009 C2D 21.5" iMac with GeForce 9400. All other features seem working just fine.

**Comment by khronokernel** [comment]
No information provided:

- Mac Model Patching
- OS patching
- Patcher Version used
- Whether or not you enabled TeraScale 2 patches in patcher settings

Refile issue with proper information
