### ISSUE TITLE
Kernel Panic persists in iMac 11,3 with OCLP 0.1.9 running BS 11.4

### ISSUE THREAD

**Issue by kennycyw** [dortania/OpenCore-Legacy-Patcher#310]
iMac 11.3  RX480 with [USB3 mod](https://forums.macrumors.com/threads/usb-3-wifi-ac-bt4-2-for-imac-27-mid-2010.2269396/) running BS 11.4 with OCLP 0.1.9 (AMD GPU with minimal SMBIOS patch)
On sleeping for a short while, iMac will reboot spontaneously to OCLP BootPicker with disappearance of the BS volume in the Boot volume list.

**Comment by khronokernel** [comment]
Please add all relevant information such as the kernel panic and OpenCore EFI generated to the issue

**Comment by kennycyw** [comment]
![Screenshot 2021-06-17 at 6 00 08 PM](https://user-images.githubusercontent.com/83110946/122487226-54c0b600-d00d-11eb-924a-722c7407fb9a.png)

**Comment by kennycyw** [comment]
The auto-reboot after an indefinite period of sleep still occurs after changing to OCLP 0.2.2 and 0.2.3 nightly build in my iMac 2010 running BS 11.4.

Besides, I did observe the Boot Stalling issues every now and then with OCLP 0.2.2.
It may need a few restarts to get pass the booting process.
More consistently, I boot to Catalina on another internal SSD and then restart to the BS volume with a much higher rate of success. Sometimes, a complete shutdown with cold restart also works.

Currently, I have switched back to OCLP 0.1.6 with full function and deep sleep.
Perhaps others may try this older version for BS instead of downgrading to Mojave 11.2.3.

**Comment by kennycyw** [comment]
Tried OCLP  0.2.3 and 0.2.4 nightly build to boot to Big Sur 11.5 but always hanged at 2nd stage boot. Had to revert to 0.1.6.

**Comment by khronokernel** [comment]
Closing as will not fix, your machine's PCI switch with XHCI mod is unsupported

**Comment by khronokernel** [comment]
To clarify, you may submit a PR of patch sets to the repo and they may be merged. Dortania will not pursue a one off machine due to limited resources and wider scoping issues
