### ISSUE TITLE
sleep doesn't work on my MacPro 5,1 and OCLP

### ISSUE THREAD

**Issue by photogeen** [dortania/OpenCore-Legacy-Patcher#311]
**Describe the bug**
Sleep is not working on my Mac Pro 5,1 and OCLP (last 5 Versions, maybe more).
With the OpenCore package from the macrumors forum my Mac was able to sleep but with OCLP sleep does not work.

**To Reproduce**
1. Wait for the sleep timer or click on the Apple, than on sleep
2. Screen goes black
3. Mac Pro still running even after an hour

**Hardware (please complete the following information):**
 - macOS 11.4 Big Sur
 - MacPro5,1

Is there any way to solve this issue?

**Comment by photogeen** [comment]
Hi, sorry for the poor preperation.

I have used Martin‘s Package in the past and sleep worked with the same specs.
Sadly I didn‘t noted the version which I used before.

I use OCLP for 6 months or so and tried multiple versions but never had any luck with sleep.
Everything else works great and that‘s why I use OCLP - simple and works great!

I will provide the EFI later. I‘m not near my MacPro right now. But I have nothing special configured.
I used the .app on the Mac Pro, activated Verbose, build OpenCore and installed it on the macOS NVMe EFI partition.

The specs are:
- 12 core 3.33GHz
- 32GB RAM
- ASRock RX5500 8GB VRAM - Slot 1
- Samsung 970 EVO 1TB on simple Adapter - Slot 2
- Chelsio N320E SFP+ 10G - Slot 3
- Inateck 4x USB3.0 - Slot 4

Is sleep working for other people with OCLP 1.5 - 1.9 on 4,1 or 5,1?

Thanks for helping ;-)
Eugen

**Comment by khronokernel** [comment]
> Is sleep working for other people with OCLP 1.5 - 1.9 on 4,1 or 5,1?

Correct, no one has reported issues so we believe it's a specific hardware quirk in your setup. That's also why we need the OpenCore EFI generated on your system to verify if any odd logic broke in our app

**Comment by photogeen** [comment]
Here is my EFI partition.
[EFI.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6672097/EFI.zip)

**Comment by photogeen** [comment]
I have found the error. It's not OCLP! It's probably my Chelsio 10G SFP+ PCIe card. I removed it and since then sleep works again.

Can be closed.

Thanks and sorry for the trouble
Eugen

**Comment by dhinakg** [comment]
Thank you for reporting!
