### ISSUE TITLE
imac model not supported and causing issues..

### ISSUE THREAD

**Issue by uzzonfire** [dortania/OpenCore-Legacy-Patcher#313]
**Describe the bug**

I have a problem after disabling the AMD graphics(installing gpu acceleration patches)i cannot log into my computer.. when i enter my password a black screen appears and i am back to the password screen..

**To Reproduce**
1. Steps to reproduce the behavior:after downloading post install volume patches of the wrong model which open core had already selected it..

**Screenshots**
![image](https://user-images.githubusercontent.com/85916364/122561047-f7edeb80-d05e-11eb-960d-7ee2c85c5046.jpeg)
**Build***
Opencore build 0.1.6

**Hardware (please complete the following information):**
 -OS Running (macOS 10.12.6)
 -OS Patching (macOS 11.4,Big Sur)
-[ ]Model Patching mid 2011 (imac21.5)

**Additional context**
This only happened after i installed the GPU accelerating patches of the wrong model which the Opencore legacy patcher had already selected for my imac,(imac 15.1)..but my imac is (imac 21.5) i only realized this after my imac had got into that state and i had to repeat the whole process of installing big sur without the gpu patches..

**Comment by Tiger-AC** [comment]
Your 21.5” mid-2011 iMac model number is iMac12,1 which should have been picked automatically by the OCLP. There is no need for you to change to any other wrong value.
Besides, v0.1.9 is the latest version.

**Comment by uzzonfire** [comment]
Thank you for the help!!

**Comment by uzzonfire** [comment]
https://user-images.githubusercontent.com/85916364/122570287-3ab4c100-d069-11eb-8102-f9fe37fca633.MOV
 After installing the GPU patches I ended up with this..

**Comment by khronokernel** [comment]
Did you enable the TeraScale 2 patches in patcher settings? From the video, looks like you omitted them

**Comment by uzzonfire** [comment]
Sir, i can share the process which i used..

**Comment by khronokernel** [comment]
This isn't a help forum, this is specific to OpenCore Legacy Patcher issues and concerns. I recommend going onto an actual forum if you're having issues

Please respect the time of developers, we can't hold hands of every single users and walk them through the entire process
