### ISSUE TITLE
ISSUE After installing the GPU patches

### ISSUE THREAD

**Issue by uzzonfire** [dortania/OpenCore-Legacy-Patcher#315]
Soon after installing the GPU patches I rebooted my mac and now, when i login the notifications bar is not fully loaded and when i try to use it, i end back to the login screen..https://user-images.githubusercontent.com/85916364/122570869-c9c1d900-d069-11eb-8ee9-f8698058217f.MOV

**Comment by khronokernel** [comment]
Please don't open issues when we already commented on the previous issue which looked to be user error...
