### ISSUE TITLE
Missing module 'requests' 

### ISSUE THREAD

**Issue by jbinder6342** [dortania/OpenCore-Legacy-Patcher#317]
**Describe the bug**
looks like a missing module/file. 

jbinder@Homer-Simpson OpenCore-Legacy-Patcher % ./dist/OpenCore-Patcher 
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 10, in <module>
    from Resources import (Build, CliMenu, Constants, ModelArray, SysPatch,
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "Resources/SysPatch.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by khronokernel** [comment]
Refactored download system with requests usage:
```sh
pip3 install requests
```

Recommend using nightly builds instead of building local as our build server internally should always have compatible binaries:
https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher.app.zip

**Comment by jbinder6342** [comment]
Understood and I like the idea of adding the requirements.txt (could also version  if needed)...  

Maybe extend the workflow auto install of all requirements/constraint's . 

eg. 

diff --git a/.github/workflows/build-app.yml b/.github/workflows/build-app.yml
index c11e750..b35e92e 100644
--- a/.github/workflows/build-app.yml
+++ b/.github/workflows/build-app.yml
@@ -17,6 +17,7 @@ jobs:
       #   run: |
       #     python3 -m pip install -U pip
       #     pip3 install pyinstaller
+      #     pip3 install -r requirments.txt 
 
       - run: pyinstaller OpenCore-Patcher.spec
       - run: ./after_pyinstaller.sh
       -

**Comment by dhinakg** [comment]
We run on a self-hosted runner, so all the requirements are already installed, so it would really just be unnecessary, and since it's for a self-hosted runner the workflow won't work without modifications for any forks anyway.
