### ISSUE TITLE
Corrupted images, videos and animated gifs in Big Sur 11.2.3 on MacPro5,1 + RX580

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#318]
@Andrey1970AppleLife believes that the issue I reported here https://github.com/acidanthera/bugtracker/issues/1701 should be reported here at OCLP for further review. I personally believe this has something to do with WhateverGreen, but I'll do as he asks.

To add to the information, here is the [ioreg output](https://p153.p0.n0.cdn.getcloudapp.com/items/OAuQQP0P/55456be1-a41d-4662-bb73-e2c360e8003c.ioreg).

**Comment by khronokernel** [comment]
Seems Vit's already answered your question:
https://github.com/acidanthera/bugtracker/issues/1701#issuecomment-864616966

**Comment by ylluminate** [comment]
Yeah, I guess it's something we're going to have to keep our eyes on until Apple sorts it out or something else percolates to the top.
