### ISSUE TITLE
Separate configuration support for Big Sur and Monterey

### ISSUE THREAD

**Issue by grigorig** [dortania/OpenCore-Legacy-Patcher#319]
OCLP currently munges support for Big Sur and Monterey together, which is problematic. For instance, a MacBookPro9,1 can perfectly use SIP and SBM on Big Sur. That way, you can use FileVault without any issues, which is one of the features OCLP is advertised with (right in the README). With the "one size fits all" approach however, SIP and SBM need to be disabled since it won't work with Monterey.

OCLP should have separate configurations based on model and target OS version to fix these problems. If that isn't possible near-term, at least the documentation should be updated and point out how to configure OCLP.

**Comment by khronokernel** [comment]
Maintaining a multi boot configuration would be quite a mess as well as end users will be unsure of exactly how their build is configured, see Monterey on month old OCLP configs. To avoid issues, best to leave it up to educated users on how they wish to configure their build with Patcher Settings

Documentation has been adjusted accordingly
