### ISSUE TITLE
iMac14,2 dead after update to 11.1 

### ISSUE THREAD

**Issue by salakis** [dortania/Opencore-Legacy-Patcher#32]
I have managed to install Big Sur on my iMac14,2 (Late 2013, i5) using the patcher, installed just fine, but then I updated to 11.1.
After the reboot, nothing would work. Startup chime is there whenever I try to turn it on, but the screen remains black - pitch black, not even the dim black when the screen is on. SMC / PRAM reset didn't work.
I have used the main branch to create the EFI.

**Comment by khronokernel** [comment]
Unplug the machine for a few minutes and try again, we know the issue and its a bug on Apple's end with 11.0.1 and any updates from it. 11.1 fresh installs should not experience this issue. Exact bug I can't discuss publicly unfortunately.

**Comment by arch-gp-z** [comment]
I had the same issue here. I had to flash the EFI ROM firmware to the chip to revive it by using CH341A programmer with SOP8 clip. Installer with 11.1 bricked my iMac the same as 11.01 in my experience.

**Comment by salakis** [comment]
So unfortunately it didn't help. iMac is still dead. Chime is there, but screen remains off.

**Comment by antid0te** [comment]
Same here, iMac 14,2 is dead too. Nothing worked (pram, nvram, SMC reset). EFI must be corrupted. 
@arch-gp-z can you tell us how did you manage to flash the EFI rom ?
Thanks !

**Comment by arch-gp-z** [comment]
1. iMac opening tool
2. CH341A programmer and SOP8 clip
3. get clean EFI ROM firmware file
4. edit that file, follow video to fix serial number and hash code https://www.youtube.com/watch?v=-O1330jgW9g
5. edit that file, follow video to fix checksum valid https://www.youtube.com/watch?v=poA8HByYqTM
6. use programmer and clip with modified firmware file (.bin) to flash the ROM chip (MX25L6404E, near bottom right corner next to speaker)
7. boot and pram and use Catalina installer to upgrade to latest ROM firmware as firmware from clean one might be old (white boot screen, that old)

good luck

**Comment by arch-gp-z** [comment]
![IMG_0816](https://user-images.githubusercontent.com/76412896/102840531-d6fd6280-444e-11eb-9cdb-d27124b1d6da.JPG)
![IMG_0820](https://user-images.githubusercontent.com/76412896/102840574-e8466f00-444e-11eb-9da6-e75f48b023d9.jpg)
![IMG_0825](https://user-images.githubusercontent.com/76412896/102840592-f0061380-444e-11eb-97f4-c67e9b7e5a7b.jpg)

**Comment by arch-gp-z** [comment]
check this one how to dump/write firmare https://www.blackhillsinfosec.com/dumping-firmware-with-the-ch341a-programmer/

**Comment by antid0te** [comment]
Ok, nice, I think I can handle it.
I am not at home for the moment, but i will try this when i will be back home in few days.
And it gives me time to buy the iMac opening tools and the CH341A programmer and to find the clean EFI ROM firmware file.

I will give updates (success or fail)

Thank you @arch-gp-z

**Comment by arch-gp-z** [comment]
@antid0te you are welcome. hash code starts with C023 for iMac 14.2. I bought clean EFI ROM firmware file from ebay. I can email to you if you get exactly same mode as mine of iMac Core i5 3.2 27-Inch (Late-2013) EMC 2639.

**Comment by salakis** [comment]
Thank you so much @arch-gp-z! Is there any chance that you could send me the EFI firmware file? I indeed have the same iMac. Email would be salakis[at]tuta.io.

**Comment by antid0te** [comment]
Yes i have the same EMC ! My email is antidote.stuffs[at]gmail.com . Thanks you very much @arch-gp-z !

**Comment by toph84** [comment]
Hi, there.

my issue just got referenced here - thank you very much @arch-gp-z 

Same problem with fresh install of 11.1 on my 14.2. Have you @antid0te and @salakis also been successful? I‘m interested in the bin file for my iMac 14.2 as well: supersonic_jet{at}web.de

Happy New Year!

Chris

**Comment by antid0te** [comment]
Hi, 

I successfully reinstall Catalina on my iMac (i will try again Bigsur later).

I just followed @arch-gp-z instructions without any problem (thanks to him). 
I used flashrom utility (on my macbook air, dowloaded with brew) to read/write the UEFI and HexFiend to edit the bin file.

It only cost me 30€ for the iMac adhesive strip and the CH341A programmer and i level up my skills. So, to sum up, i'm very happy.

**Comment by arch-gp-z** [comment]
> Hi,
> 
> I successfully reinstall Catalina on my iMac (i will try again Bigsur later).
> 
> I just followed @arch-gp-z instructions without any problem (thanks to him).
> I used flashrom utility (on my macbook air, dowloaded with brew) to read/write the UEFI and HexFiend to edit the bin file.
> 
> It only cost me 30€ for the iMac adhesive strip and the CH341A programmer and i level up my skills. So, to sum up, i'm very happy.

It would brick it again if you try big sur with patcher but now you can flash it to revive it.

**Comment by arch-gp-z** [comment]
@antid0te for now I’d recommend micopatcher and it’s quite easy to use, just two steps.

**Comment by toph84** [comment]
I have

**Comment by toph84** [comment]
I have also been successful in restoring my iMac‘s 14,2 EFI Firmware following @arch-gp-z guide. Flashing the right file with CH341A & the clip. A remember to reset NVRAM. Thanks!

**Comment by JoshDantzler** [comment]
@arch-gp-z Can I get the EFI firmware file as well? I’m in the same situation as the others I believe and need to follow your steps. Can you email me at: josh_apple_7@icloud.com
Thanks!
