### ISSUE TITLE
Big Sur boot fails after enabling FileVault

### ISSUE THREAD

**Issue by grigorig** [dortania/OpenCore-Legacy-Patcher#323]
**Describe the bug**
On a fresh Big Sur 11.4 installation (onto an external USB SSD) and enabling FileVault, booting macOS fails with OCLP 0.1.9. SIP and SBM are enabled. The system is stuck on the initial black screen with white Apple logo. Enabling verbose mode in OCLP does nothing.

Any idea what to try next?

**To Reproduce**
1. Install Big Sur
2. Enable FileVault
3. Reboot

**Hardware (please complete the following information):**
 - OS: Big Sur 11.4
 - OCLP 0.19
 - MacBookPro9,2

**Comment by khronokernel** [comment]
Enable OpenCore DEBUG in patcher settings and send log:
https://dortania.github.io/OpenCore-Legacy-Patcher/DEBUG.html

**Comment by grigorig** [comment]
Here's the OpenCore DEBUG log.

[opencore-2021-06-22-150858.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6695545/opencore-2021-06-22-150858.txt)

At the end of the file there's a sequence of zero bytes--is this expected?

**Comment by grigorig** [comment]
Any idea what's possibly going wrong here?

**Comment by grigorig** [comment]
Ping. Any idea? I still have the external disk with Big Sur installed, ready to test stuff.

**Comment by khronokernel** [comment]
No one since has been able to replicate your issue, including my own 9,2 machine. Recommend researching yourself, feel free to provide patch sets, as otherwise there's little we can do with UEFI level issues
