### ISSUE TITLE
Avast Premium Security detect trojan MacOs:DangerousSig  when downloading the patcher 

### ISSUE THREAD

**Issue by pbe27** [dortania/OpenCore-Legacy-Patcher#324]
![image](https://user-images.githubusercontent.com/85922927/122954530-ce470400-d37f-11eb-8752-10a7f019c66d.png)

**Comment by khronokernel** [comment]
Binaries are signed and notarized by Apple, source is public. File complaint to the software vendor
![EA4B3457-87BE-4467-8BF9-D2BD863C181E](https://user-images.githubusercontent.com/48863253/122961797-fa439480-d341-11eb-8d24-d6e58e35c0a2.jpeg)
