### ISSUE TITLE
OpenGL patches not installable to boot volume with v. 0.2.0 and 0.2.1 OCLP

### ISSUE THREAD

**Issue by larsvonhier** [dortania/OpenCore-Legacy-Patcher#327]
Post-patching for Nvidia non-metal GPUs does not work from 0.2.0 on for i.e. Big Sur 11.5b3
(up to v0.1.9 it worked correctly i.e. on a GT320 MacBook pro 7,1)

Perhaps the new DL routine for Apple binaries skips/misses the content needed, script afterwards cannot find required files, system boots unaccelerated afterwards...

**Comment by mdgm88** [comment]
Please check the latest changelog before reporting an issue: https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/CHANGELOG.md

If you are on Discord you could try the 0.2.2 nightly.

**Comment by khronokernel** [comment]
mdgm88 is correct, was resolved in 0.2.2
