### ISSUE TITLE
Login loop after updating to 0.2.1

### ISSUE THREAD

**Issue by harrythecoolb** [dortania/OpenCore-Legacy-Patcher#331]
**Describe the bug**
Login loops on my macbook pro 2010 15 inch after updating patches +efi to open core version 2.1
 -macbook pro 15 inch 2010
6gb ram with ssd

**Comment by khronokernel** [comment]
Fixed in 0.2.2

**Comment by harrythecoolb** [comment]
There isn't 0.2.2
