### ISSUE TITLE
Intel HD Graphics 4000 Screen Mirroring 

### ISSUE THREAD

**Issue by onyxong** [dortania/OpenCore-Legacy-Patcher#334]
Mac Mini 2012 Intel HD Graphics 4000 
OS Monterey Beta  Version 12.0
Open Core Patcher 2.2 

Screen Mirroring to Apple TV not working after patching 

**Describe the bug**
A clear and concise description of what the issue is. 

**To Reproduce**
1. Open app or .command '...'
2. Enter '....'
3. See error

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.15.7, Catalina)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. MacPro5,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**

**Comment by khronokernel** [comment]
Hardware DRM playback is currently unsupported. Will update documentation to reflect
