### ISSUE TITLE
Kryptonite eGPU Support with legacy video drivers

### ISSUE THREAD

**Issue by dirkenstein** [dortania/OpenCore-Legacy-Patcher#336]
I have an old MBP late 2011 with a defective AMD dGPU which has been disabled  through both the realmacmods hardware mod and settting: 
nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00

That leaves me with an HD3000 that is not natively supported in Big Sur, but your legacy video patches do provide acceleration (No Metal, obviously).

I'd like to be able to use this MBP with a TB3 eGPU. This requires Kryptonite or purge-wrangler  to support AMD GPUs over TB1. 

I have loaded both Kryptonite.kext and Thunderbolt3Unblocker.kext to allow my RX580 eGPU in a Lenovo BoostStation TB3 enclosure to be recognized via an apple TB3 -> TB2 adapter and an HP zBook eleite TB3 hub.

This works OK in High Sierra.

However, there appears to be an issue in Catalina and Big Sur that stops Kryptonite from working with eGPUs and non-accelerated graphics enabled. 

When booting with the eGPU attached, it is recognized, but WindowServer crashes with:

Assertion failed: (0 && "Attempting to get MTLTexture with no MTLDevice"), function GetMTLTexture, file /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/CoreDisplay/CoreDisplay-237.3/CoreDisplay/Display/DisplaySurface.mm, line 509.

[WindowServer_2021-06-25-044227_Dirks-MacBook-Pro.crash.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6713605/WindowServer_2021-06-25-044227_Dirks-MacBook-Pro.crash.txt)

I can work around this in an unpatched Big Sur by setting -wegnoigpu for WhateverGreen. This obviously disables internal HD3000 graphics, but does let me use my 4K screen fully accelerated.  

There is, however, an issue in that hot-plugging the eGPU is not recognized. Thunderbolt devices are only seen in System Infromation and the IO registry when plugged in from cold boot.

The other issue is that patching to support Legacy HD3000 acceleration seems to break Kryptonite.

Install Kryptonite.kext and Thunderbolt3Unblocker.kext in OpenCore/Lilu. Set -krybeta and krygpu=AMD in boot-args.
Everything works if -wegnoigpu is set in boot-args and you cold-boot with TB devices plugged in.

Wthout -wegnoigpu, WindowServer crashes. 
If hot-plugging eGPU, no ThunderBolt devices observed in the IO Registry.

If patching for  legacy video support,AMD RX580 is listed in PCI devices but no drivers are loaded for it. -wegnoigpu results in boot failure (no graphics devices found, basically).

OS Version:            macOS 11.4 (20F71)
Patched from a dosdude1 Catalina .
MacBookPro8,2 (AMD dGPU hardware disabled due to GPU fault. Only HD3000 is visible in hardware list)

**Comment by khronokernel** [comment]
Hello, I'm unsure what you're requesting from us by opening this issue. As you stated, patching HD3000 support back in breaks all Metal GPUs. This is due to the multiple Skylight and CoreDisplay work-arounds required as well as our IOSurface downgrade

As it stands, it's impossible to have both a Metal and non-Metal GPU with acceleration in Big Sur. Unfortunately your only option is to buy a newer Mac (ie. 2012 series) if you require Big Sur with acceleration from the iGPU and eGPU
