### ISSUE TITLE
You dont check for disk space in your python installer...

### ISSUE THREAD

**Issue by TomLewis** [dortania/OpenCore-Legacy-Patcher#337]
**Describe the bug**
The installer has got to 
```
Product downloaded and installed to /Users/tom/macOS-installer/Install_macOS_11.3-20E232.sparseimage
Making read-only compressed disk image containing Install macOS Big Sur.app...
.............
```
And I was wondering why everything stopped. Got the disk space warning...
I wanted to build this onto a memory stick for another machine NOT to install on this machine, has it installed things to this machine?

How do I clear it all?
How much space do I need?

**To Reproduce**
1. Have about 25GB free disk space
2. Run the installer
3. Gets stuck

**Hardware (please complete the following information):**
 - OS Running  macOS 10.15.7, Catalina
 - OS Patching macOS 11.2.3, Big Sur (I wanted it on memeory stick like the installer says..... Not this machine)
 - Model Patching 10.15.7  but I want it for 10.12,2

**Comment by Ausdauersportler** [comment]
Hi!

I am not sure what you are complaining about? You did not provide any information about the Apple system or OCLP version you are using.

The OCLP app does not download a macOS installer and it is surely not responsible for checking disk space. It is just installing an automatically generated OpenCore version onto an EFI partition (average size of the complete package is about 10 MB, the EFI partition itself has 200 MB).

**Comment by khronokernel** [comment]
installinstallmacos.py is not our program
