### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'country_code' while creating OpenCore for MacBookPro9,2 in current release 0.2.2

### ISSUE THREAD

**Issue by dmuiX** [dortania/OpenCore-Legacy-Patcher#338]
**Describe the bug**
I was trying to create an OpenCore EFI folder for a MacBookPro9,2 with the current release 0.2.2
Following error occurs:

Building Configuration for external model: MacBookPro9,2
Created build folder

- Adding OpenCore v0.7.0 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.4
- Adding WhateverGreen.kext 1.5.1
- Adding SMC-Spoof.kext 1.0.0
- Adding CPUFriend.kext 1.2.4
- Adding SidecarFixup.kext 1.0.2
- Unable to run Wireless hardware detection
- Adding AirportBrcmFixup.kext 2.1.3
- Using known DevicePath PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0)
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 296, in <module>
  File "OpenCore-Patcher.command", line 290, in main_menu
  File "Resources/Utilities.py", line 239, in start
  File "OpenCore-Patcher.command", line 76, in build_opencore
  File "Resources/Build.py", line 845, in build_opencore
  File "Resources/Build.py", line 282, in build_efi
  File "Resources/Build.py", line 242, in wifi_fake_id
AttributeError: 'NoneType' object has no attribute 'country_code'
[2697] Failed to execute script OpenCore-Patcher
Saving session...completed.

**To Reproduce**
1. Open Patcher
2. Select 3 to change to MacBookPro9,2
3. Select 1 to create OpenCore 
4. Error occurs

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running Big Sur on Hackingtosh, Showing MacPro6,1
 - Model Patching MacBookPro9,2

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**

Funny thing is for a MacBook5,2 its working correctly. And older Version 0.1.9 is working correctly, too. In Version 0.2.1 its the same error. The rest versions I haven't checked.

**Comment by dhinakg** [comment]
Please test https://github.com/dortania/OpenCore-Legacy-Patcher/suites/3081432819/artifacts/70303567

**Comment by khronokernel** [comment]
Assuming resolved in master

**Comment by DarkLegacy248** [comment]
Same issue with 8,2 this has not been resolved with 0.2.3.  Any solutions, can I manually put in a country code?
