### ISSUE TITLE
MBP mid 2012 firmware version is old 

### ISSUE THREAD

**Issue by CuchoM** [dortania/Opencore-Legacy-Patcher#34]
The instalation tryed to upgrade the firmware (so bad)
I'd open the macbook and disconnected battery and ssd to solve the boot.
Everything was working fine , even OTA to macOS BS 11.2 beta (20D5029f)

use opencore 0.6.5 files to solve firmware version and all is working fine 
Opencore 0.6.5 was find is this link
https://bitbucket.org/profdrluigi/opencorepkg-beta/downloads/

Could you please update the patcher ?

**Comment by arch-gp-z** [comment]
It happened to my iMac 14.2 late 2013 as well, the installation tried to upgrade the EFI ROM firmare of it (Intel ME version my case) and bricked it. I revived it by programming the EFI chip and resumed the intallation. Then something got interesting, the iMac can run Bir Sur natively even without opencore at all.

I am curious that if you could deactivate opencore (OLP) then Big Sur could run by itself as well. MPB mid 2012 is metal capable as I remeber, so hardware wise it is compatible with Catalina as well as Big Sur.

**Comment by Bustycat** [comment]
> I am curious that if you could deactivate opencore (OLP) then Big Sur could run by itself as well. MPB mid 2012 is metal capable as I remeber, so hardware wise it is compatible with Catalina as well as Big Sur.

It will be stuck into the grey screen without booting OpenCore.

**Comment by MikeBeaton** [comment]
I'm running Big Sur on a MacBook Pro 13" retina late 2012 the way you asked about, @arch-gp-z: I boot through OpenCore when I need to fake the system id to get updates. But once installed, the only required setting to get Big Sur to run by itself is `nvram boot-args="-no_compat_check"`. Obviously whether that works (well) depends on your specific Mac and which patches, if any, it needs to run (correctly).
