### ISSUE TITLE
BiomeSyncd 99% utilization - Monterey 0.2.2 - MBP Late 2013

### ISSUE THREAD

**Issue by alex99r** [dortania/OpenCore-Legacy-Patcher#340]
BiomeSyncd gets to max cpu utilization every 5 mins or so.

- MacBook Pro 11,3 (GT 750M, Haswell 4850HQ)
- macOS Monterey (12.0 Dev Beta 1)
- OCLP 0.2.2 Nightly

Anybody else experiencing this?

Thx!

**Comment by khronokernel** [comment]
This is not a Monterey support forum, use MacRumors or other places generalized for this. Issues tab should be for OCLP issues

**Comment by alex99r** [comment]
Could I have known before posting that this wasn't  OCLP that's causing (or caused on specific OCLP'ed models) the problem before you reply that it isn't? i.e. a fresh install fixed my problem
