### ISSUE TITLE
MacBookPro6,2 

### ISSUE THREAD

**Issue by tahaklkt-osxinfo** [dortania/OpenCore-Legacy-Patcher#342]
Hi. How can I use my hackintosh with this patch ? I have opencore 0.7.1 configuration. I try to root patch with my intel core i5 m430 nvidia gt 330m graphics card and ssd. How can I install this patch to my hackintosh ? Im trying but   Im getting root volume patching isn't supported on this machine. Thanks a lot !

**Comment by khronokernel** [comment]
Hackintoshes are not supported, use forums for more generalized help

**Comment by tahaklkt-osxinfo** [comment]
@khronokernel Do you leave a link for me please ? I can't find them. My another question is how can I run this graphics card with kexts ? How can I find them for Big Sur ?
