### ISSUE TITLE
Icons in system Preferences not showing and Menu Bar distorted (HD 3000)

### ISSUE THREAD

**Issue by Human7900** [dortania/OpenCore-Legacy-Patcher#343]
**Describe the bug**
Icons in system Preferences not showing and Menu Bar distorted (HD 3000)

**To Reproduce**
1. Open app or .command 'System Preferences'
2. Enter '....'
3. See error

**Screenshots**
![Screen Shot 2021-06-26 at 12 56 18 PM](https://user-images.githubusercontent.com/84245065/123505739-6db90f00-d67e-11eb-81d9-d05b66f17497.png)

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.
On a Hackintosh.
**Hardware (please complete the following information):**
 - OS Patching macOS 11.4, Big Sur)
 - Model Patching (ie. MacBookPro 13,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

Black lines appearing way too much.

**Comment by khronokernel** [comment]
Duplicate:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
