### ISSUE TITLE
Adding support for TB3 Titan Ridge to BS 11.5 beta 3 on cMP3, running OCLP 0.1.6

### ISSUE THREAD

**Issue by newkton1** [dortania/OpenCore-Legacy-Patcher#345]
There is a thread at Mac Rumours explaining how to add TB3 support to the classic Mac Pro 5,1. I have made the same firmware and hardware mods to the same card and placed it in  slot 4 of my classic Mac Pro 3,1. The card shows in the Thunderbolt system preference and the Mac boots normally but the card ports are inactive although there is a Thunderbolt controller showing in the PCI system preference with installed driver. The original posts on this project referred to modifying the EFI for open core but this was in the pre-OCLP days and I don't know how to make this modification in OCLP. Is there a small chance that you might add support for Thunderbolt 3 for the cMP 3,1 to the latest patchers? By the way the new GUI looks great.
I enclose a couple of screenshots to demonstrate what I'm talking about.
![Screen Shot 2021-06-27 at 13 47 33](https://user-images.githubusercontent.com/13056263/123535236-89dfad80-d75d-11eb-9670-b9e790da32ae.png)
![Screen Shot 2021-06-27 at 13 47 46](https://user-images.githubusercontent.com/13056263/123535242-8d733480-d75d-11eb-9984-b35a64320cb1.png)
![Screen Shot 2021-06-05 at 11 52 44](https://user-images.githubusercontent.com/13056263/123535172-3705f600-d75d-11eb-897a-02f70b4ec049.png)

**Comment by newkton1** [comment]
Just a little more data
The Thunderbolt ports show in Network Sys Press but are inactive
![Screen Shot 2021-06-27 at 15 47 37](https://user-images.githubusercontent.com/13056263/123535572-a41a8b00-d75f-11eb-8310-66a7ed3507a1.png)

**Comment by khronokernel** [comment]
Unfortunately as no one on the team has the hardware, we're unable to reliably provide a patch set to OCLP as it stands. If you do wish to integrate Thunderbolt support, feel free to PR or provide thorough instructions and documentation similar to how Ausdauersportler was able to aid us with the iMac Metal upgrade patch set we use today with assistance from the [MacRumors thread](https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/)

Note: We are not asking to be sent a generic forum thread on the topic. We need properly documented patch sets with developers we can discuss with for further clarification. We don't wish to provide questionable support, we'd like to be able to backup our patch set logic
