### ISSUE TITLE
Terascale 2 - iMac 12,1 quite perfect, only problem discoloring at transpartent black and transparent white area

### ISSUE THREAD

**Issue by peet1979** [dortania/OpenCore-Legacy-Patcher#346]
First of all thank's a lot for the programmers, who made iMac modell 12,1 working quite perfectly by using OpenCore patches with Big Sur.

Everything is quite perfect after running the patches by enabling Terascale 2 acceleration and setting the color depht to 24 bit with ResXtreme.

Only issue I've experienced is the transparent zones of finder and safari. Discoloring is another shade of transparent black / white, following the mouse pointer on the transparent zone.

The issue is far not tragic, you can live with it, but if there is a solution, it would be perfect.

**Comment by khronokernel** [comment]
Duplicate:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
