### ISSUE TITLE
The post-install volume applied to my Macmini 5,2 was the one for a Macmini 5,1

### ISSUE THREAD

**Issue by jzrodriguez98** [dortania/OpenCore-Legacy-Patcher#347]
**Describe the bug**
Hello to all. I’m trying to apply the post-install patch for TS2 acceleration in a Macmini 5,2 (which has a Radeon HD 6630M) using a nightly build of OCLP I downloaded on Sunday afternoon minutes (around 2:45 pm ET). I installed Big Sur 11.2.3. When I was about to apply the patch, I saw a message saying that I was going to add the Legacy Intel Sandy Bridge Graphics Patch. Is this correct? The message does not make sense since I have a Macmini5,2, not the 5,1 which is the one that has the Intel card. Maybe the app has some coding wrong? Nevertheless, I decided to apply the patch to see what happens. It did not go well: after selecting Y to apply the post-install volume patches, I noticed that when installing the patches the app deleted the AMD and Intel kernel extensions but installed only the Intel kernel extensions, so the app assumed that the gpu card was an Intel gpu instead of a AMD Radeon HD 6630M which was really my card under my Macmini 5,2. After rebooting the computer, the computer was in a loop at the login screen (I entered the password and pressed ENTER, but the system went dark and then brought me back to the login screen). So I guess that the app has a bug /error here.

**To Reproduce**
1. Open OCLP app and select post-install volume patches
2. Select 'Patch Volume'.
3. The next screen shows the following:
"The following patches will be applied"
-Add Legacy Intel Sandy Bridge Graphics Patch
Would you like to continue with Root Volume Patching?(y/n):"
4. After selecting Y to apply the post-install volume patches, I noticed that when installing the patches the app deleted the AMD and Intel kernel extensions but installed only the Intel kernel extensions, so the app assumed that the gpu card was an Intel gpu instead of a AMD Radeon HD 6630M which was really my card under my Macmini 5,2. After rebooting the computer, the computer was in a loop at the login screen (I entered the password and pressed ENTER, but the system went dark and then brought me back to the login screen). So I guess that the app has a bug /error here.

**Screenshots**
![image](https://user-images.githubusercontent.com/10348976/123579270-90921300-d7a5-11eb-8100-33d52cea6dcd.jpeg)
**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 11.2.3 , Big Sur)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. Macmini 5,2)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**

**Comment by khronokernel** [comment]
Macmini5,2 has an HD3000 for internal hardware acceleration, additionally TerScale 2 patches are disabled by default. Enable in patcher settings

**Comment by jzrodriguez98** [comment]
I looked in the literature and the Macmini 5,2 does not make reference to a GMUX IC (see link below). It only says that the Macmini 5,2 has a dedicated Radeon HD 6630M GPU.

https://everymac.com/systems/apple/mac_mini/mac-mini-aluminum-unibody-faq/differences-between-mid-2011-aluminum-unibody-mac-mini-models.html

Internal Differences

Although there are some similarities internally -- all use Intel "Sandy Bridge" processors of differing types and speeds with a 5 GT/s "Direct Media Interface" in lieu of the "traditional" system bus, all support 1333 MHz PC3-10600 DDR3 SO-DIMMs, and all support two 6 Gb/s Serial ATA hard drives, for example -- there are major differences as well.

The most notable internal difference is that the mid-level Mac mini "Core i5" 2.5 (Mid-2011) model has dedicated graphics -- an AMD Radeon HD 6630M graphics processor with 256 MB of dedicated GDDR5 memory -- which results in a substantial improvement in graphics performance. The entry-level and server models, by contrast, only have integrated graphics, specifically an Intel HD Graphics 3000 video processor, that shares memory with the system.

It also is quite notable that the server configuration has a quad core processor rather than dual core processors like the other models. The server model also shipped with dual hard drives and Lion Server pre-installed.

**Comment by jzrodriguez98** [comment]
Could you please this in more detail? > Macmini5,2 has an HD3000 for internal hardware acceleration, additionally TerScale 2 patches are disabled by default. Enable in patcher settings

**Comment by khronokernel** [comment]
The program is not bugged, websites such as those are flawed in the hardware information. Look at your device tree, there's clearly an iGPU present and active headless used for hardware accelerated encode/decode

**Comment by jzrodriguez98** [comment]
I did enable TS2 patches in Patcher settings when building OpenCore for a Macmini5,2.

**Comment by khronokernel** [comment]
You do not build OpenCore with TS2 patches, you root patch with it enabled

**Comment by khronokernel** [comment]
Please use forums and not issues tabs for this kind of discussion
