### ISSUE TITLE
MacBookAir5,2 Brightness Control 11.3+ not working

### ISSUE THREAD

**Issue by datuck** [dortania/OpenCore-Legacy-Patcher#349]
**Description**
After upgrading to Big Sur 11.3 the brightness is maxed and cannot be turned down either by settings, keys, or control center.

**Steps to reproduce the behavior:**

1. Press Brightness Up Key (F5) or Brightness Down key (F6)
2. Nothing happens
3. Navigate to control center and try to change brightness
4. Nothing happens
5. Reset the NVRAM and also reset the SMC by unplugging the battery, pressing the power switch while in powerless state for several seconds, then reboot.
6. Issue persisted. Able to replicate the issue with 11.3, 11.4, 11.5, 12.0.

**Expected behavior**
No issues on 11.2.3.
![Screen Shot 2021-06-28 at 2 13 22 AM](https://user-images.githubusercontent.com/51359198/123611543-904e4380-d7b6-11eb-96e4-5d051e027b4d.png)

**Screenshots**
Brightness slider is locked at full brightness
![image](https://user-images.githubusercontent.com/51359198/120699551-5fa01600-c465-11eb-8b26-46e0e82f26b3.png)

No brightness slider in the display section
![image](https://user-images.githubusercontent.com/51359198/120699768-adb51980-c465-11eb-8fbd-c1632d055a83.png)

![image](https://user-images.githubusercontent.com/51359198/120700465-8c086200-c466-11eb-9b0d-c547d691d24e.png)

**Build Folder**
OCLP 0.21, 0.22, 0.23 (able to replicate on all versions)

**MacBookAir5,2**
- macOS 11.2.3 (Big Sur) - No issues
[MBA52_11.2.3.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6725023/MBA52_11.2.3.zip)
- macOS 11.3, 11.4, 11.5 beta 3 + (Big Sur) - No brightness control
[MBA52_11.5b3.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6724989/MBA52_11.5b3.zip)

**Additional context**
I have been able to replicate the same issue using PatchedSur and OCLP. Appears something changed between 11.2.3 and 11.3 that broke the brightness control.

**Comment by khronokernel** [comment]
Cannot replicate with anyone locally, feel free to research further and provide patch sets however as-is we can't dedicate time for a single user's issue especially when it's not a bug of the patcher itself

**Comment by datuck** [comment]
> Cannot replicate with anyone locally, feel free to research further and provide patch sets however as-is we can't dedicate time for a single user's issue especially when it's not a bug of the patcher itself

Thank you for testing with your MacBookAir5,2! Based on your testing you confirmed that the issue is only with my laptop and not all MacBookAir5,2. Okay to close based on your test results.

**Comment by eudy97** [comment]
> **Description** After upgrading to Big Sur 11.3 the brightness is maxed and cannot be turned down either by settings, keys, or control center.
> 
> **Steps to reproduce the behavior:**
> 
> 1. Press Brightness Up Key (F5) or Brightness Down key (F6)
> 2. Nothing happens
> 3. Navigate to control center and try to change brightness
> 4. Nothing happens
> 5. Reset the NVRAM and also reset the SMC by unplugging the battery, pressing the power switch while in powerless state for several seconds, then reboot.
> 6. Issue persisted. Able to replicate the issue with 11.3, 11.4, 11.5, 12.0.
> 
> **Expected behavior** No issues on 11.2.3. ![Screen Shot 2021-06-28 at 2 13 22 AM](https://user-images.githubusercontent.com/51359198/123611543-904e4380-d7b6-11eb-96e4-5d051e027b4d.png)
> 
> **Screenshots** Brightness slider is locked at full brightness ![image](https://user-images.githubusercontent.com/51359198/120699551-5fa01600-c465-11eb-8b26-46e0e82f26b3.png)
> 
> No brightness slider in the display section ![image](https://user-images.githubusercontent.com/51359198/120699768-adb51980-c465-11eb-8fbd-c1632d055a83.png)
> 
> ![image](https://user-images.githubusercontent.com/51359198/120700465-8c086200-c466-11eb-9b0d-c547d691d24e.png)
> 
> **Build Folder** OCLP 0.21, 0.22, 0.23 (able to replicate on all versions)
> 
> **MacBookAir5,2**
> 
> * macOS 11.2.3 (Big Sur) - No issues
>   [MBA52_11.2.3.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6725023/MBA52_11.2.3.zip)
> * macOS 11.3, 11.4, 11.5 beta 3 + (Big Sur) - No brightness control
>   [MBA52_11.5b3.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6724989/MBA52_11.5b3.zip)
> 
> **Additional context** I have been able to replicate the same issue using PatchedSur and OCLP. Appears something changed between 11.2.3 and 11.3 that broke the brightness control.

Same behavior on 9.2 MacBook Pro.
Keyboard backlight had the same issue but went away after a couple reboots.

Did you managed to find a fix/workaround?

**Comment by datuck** [comment]
> 
> Same behavior on 9.2 MacBook Pro. Keyboard backlight had the same issue but went away after a couple reboots.
> 
> Did you managed to find a fix/workaround?

Still no fix for this, I gave up and sold my MacBook Air and bought a newer one that natively supports Big Sur, etc. I gave up on the OCLP community because the developer wouldn't acknowledge or assist with solution and kept closing all of the bug reports as soon as they were reported instead of trying to help.
