### ISSUE TITLE
iMac14.2 can run Big Sur 11.1 natively without opencore after bricking and reviving

### ISSUE THREAD

**Issue by arch-gp-z** [dortania/Opencore-Legacy-Patcher#35]
iMac 14.2 model is not compatible with Big Sur officially. During the process of installation of 11.01/11.1, iMac was bricked and then was revived by programming EFI ROM chip, then resuming installation of 11.01/11.1. After that Big Sur can run natively even opencore is not active.

**Comment by Bustycat** [comment]
> After that Big Sur can run natively even opencore is not active.

Is the identifier still iMac14,2?

**Comment by arch-gp-z** [comment]
![Screen Shot 2020-12-22 at 1 06 34 am](https://user-images.githubusercontent.com/76412896/102792548-632e6c00-43f4-11eb-8993-66d965415b35.PNG)
![Screen Shot 2020-12-22 at 1 14 56 am](https://user-images.githubusercontent.com/76412896/102792559-6590c600-43f4-11eb-9ddf-6e5f4f73409a.PNG)

**Comment by arch-gp-z** [comment]
Yes it appears that it natively support Big Sur, no opencore at all.

**Comment by dhinakg** [comment]
This is probably due to `-no_compat_check` in NVRAM still lingering. Resetting NVRAM will cause you to end up with the prohibited sign.
