### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Supereze83** [dortania/OpenCore-Legacy-Patcher#350]
**Describe the bug**
A clear and concise description of what the issue is. 

**To Reproduce**
1. Open app or .command '...'
2. Enter '....'
3. See error

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.15.7, Catalina)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. MacPro5,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Additional context**

**Comment by Supereze83** [comment]
When I finish the installation and after running the patcher My iMac goes back to pasword screen once and another

**Comment by jzrodriguez98** [comment]
> When I finish the installation and after running the patcher My iMac goes back to pasword screen once and once again. I can't do anything. I've tried twice on each SSD I have but always the same result.
> 
> 
> 
> Imac mid2011 27inch 
> 
> 2.7 Ghz intel core i5
> 
> 8gb 1333 Mhz ddr3
> 
> Graphics AMD Radeon HD 6770M 512 mb 
> 
> 
> 
> I've been investigating and it turns out that I am not the only one with this problem

Interesting. I had the issue yesterday after trying to patch volume root for TS2 gpu acceleration in my Macmini 5,2.

**Comment by mdgm88** [comment]
You didn't follow the template for how to describe a bug. This doesn't help for troubleshooting as then all those questions have to get asked anyway later.

Most importantly you haven't mentioned which OS this is with? 11.2.3? 11.4? The TS2 GPU Acceleration patch is only available for Big Sur at this time.

Also make sure that when you go to do the post install volume patch that you first go to Patcher Settings and enable TS2.

It would probably be better to discuss these kinds of issues on Discord first and open a bug if it's not something that can get resolved on there.

**Comment by jzrodriguez98** [comment]
I was referring to the loop in the login screen. Anyway, I made a clean install of Big Sur 11.2.3 again and went through the OCLP guide again to perform the steps carefully and this time it booted well in the Macmini 5,2 after applying the post-install volume patches. Cheers.

**Comment by khronokernel** [comment]
Please keep issues tab for OpenCore issues, use forums for general discussions
