### ISSUE TITLE
Mac Monterey Display Brightness error

### ISSUE THREAD

**Issue by Vovapython** [dortania/OpenCore-Legacy-Patcher#352]
I upgraded my mid-2012 mac book Pro to Monterey, and the display brightness is much lower than before, but it says I'm on maximum. Can somebody help??

 - OS Running : macOS 10.15.7, Catalina
 - OS Patching: MacOS 12.0.1 Monterey
 - Model Patching (MacBook Pro 10.1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* ie. `File -> SaveAs`

**Comment by Vovapython** [comment]
In addition to this, when i turn on my Mac, it report this: "Your Mac restarted because of an error. Please wait or press a key to continue."

**Comment by khronokernel** [comment]
Cannot replicate locally or within our team, closing. Feel free to research further yourself and submit patch sets
