### ISSUE TITLE
iMac14,3: only wake up for ethernet network access available

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#353]
**Describe the bug**
I use my iMac late 2013 as a hub for file sharing. It worked perfectly well with Mojave. But I installed Big Sur... and now in System Preferences --> Energy saver, I only see the option "Wake up for ETHERNET network access". It doesn't seem to work over WIFI and that's really annoying to me. 
Is there a workaround please ?

**Screenshots**
![Capture d’écran 2021-06-30 à 01 59 02](https://user-images.githubusercontent.com/86326794/123882323-d9350200-d946-11eb-977f-a3ca38cade40.png)

**Build Folder**
OLP 0.2.2

**Hardware (please complete the following information):**
 - macOS Big Sur 11.4 on iMac14,3

**Comment by khronokernel** [comment]
This was implemented to work around an unfortunate bug in macOS Big Sur+ where wake from sleep degraded network performance by half for many users. If you desire this option still, we've added a patcher setting in the latest commit

**Comment by mat1696** [comment]
Thanks, I'll try to turn the setting on, but if I understand well it will be available in OCLP 0.2.3 as "Patcher setting" (key 5 in OCLP menu) ?

And is there a patcher specific issue or a Big Sur issue that occurs with supported Mac as well ? Because if that's a wide-spread issue I could fill an Appleseed BR from my supported MacBook Air to Apple...
