### ISSUE TITLE
Cannot build without wi-fi card installed

### ISSUE THREAD

**Issue by DarkLegacy248** [dortania/OpenCore-Legacy-Patcher#354]
I have attempted to use version 2.2 and build fails with the error "AttributeError: 'NoneType' object has no attribute 'country_code'". My internal wi-fi card is not working using an external usb as a replacement can the looking for country_code feature be turned off without stopping the build?

Getting this when building:
Building Configuration on model: MacBookPro8,2
Created build folder

- Adding OpenCore v0.7.0 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.4
- Adding WhateverGreen.kext 1.5.1
- Adding NightShiftEnabler.kext 1.1.0
- Adding SMC-Spoof.kext 1.0.0
- Adding CPUFriend.kext 1.2.4
- Adding CatalinaBCM5701Ethernet.kext 1.0.1
- Adding AppleALC.kext 1.6.2
- No 3rd Party NVMe drives found
- Adding AirportBrcmFixup.kext 2.1.3
- Using known DevicePath PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0)
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 296, in <module>
  File "OpenCore-Patcher.command", line 290, in main_menu
  File "Resources/Utilities.py", line 239, in start
  File "OpenCore-Patcher.command", line 76, in build_opencore
  File "Resources/Build.py", line 845, in build_opencore
  File "Resources/Build.py", line 282, in build_efi
  File "Resources/Build.py", line 242, in wifi_fake_id
AttributeError: 'NoneType' object has no attribute 'country_code'
[4298] Failed to execute script OpenCore-Patcher
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Using Early 2011 macbook pro "15. Already installed Big Sur with version 1.7 works great.

**Comment by khronokernel** [comment]
Resolved in 0.2.3, see nightly link in README

**Comment by DarkLegacy248** [comment]
This has not been resolved, It is the exact issue as #338 but using 8,2 on an actual 8,2.

From: Mykola Grymalyuk ***@***.***>
Date: Sunday, 4 July 2021 at 21:40
To: dortania/OpenCore-Legacy-Patcher ***@***.***>
Cc: DarkLegacy248 ***@***.***>, Author ***@***.***>
Subject: Re: [dortania/OpenCore-Legacy-Patcher] Cannot build without wi-fi card installed (#354)

Resolved in 0.2.3, see nightly link in README

**Comment by dhinakg** [comment]
If you're having issues with 0.2.2, send a new traceback

**Comment by DarkLegacy248** [comment]
No this is using 0.2.3 which is reported to be resolved as of that version.  Which it has not been.  The issue remains.

From: Dhinak G ***@***.***>
Date: Tuesday, 6 July 2021 at 13:01
To: dortania/OpenCore-Legacy-Patcher ***@***.***>
Cc: DarkLegacy248 ***@***.***>, Author ***@***.***>
Subject: Re: [dortania/OpenCore-Legacy-Patcher] Cannot build without wi-fi card installed (#354)

If you're having issues with 0.2.2, send a new traceback

**Comment by khronokernel** [comment]
As we requested before, send a new traceback of how it crashes with the latest nightly build

**Comment by DarkLegacy248** [comment]
I redownloaded 0.2.3 and tried it again and this time it does in fact work but it was doing the same as with 0.2.0 through 0.2.2 yesterday. And I was using the 0.2.3 TUI version. Issue I guess is now resolved.  Will wait for full releases on site before attempting to update again.  Thank you.  You all are doing fantastic work.

From: Mykola Grymalyuk ***@***.***>
Date: Wednesday, 7 July 2021 at 16:37
To: dortania/OpenCore-Legacy-Patcher ***@***.***>
Cc: DarkLegacy248 ***@***.***>, Author ***@***.***>
Subject: Re: [dortania/OpenCore-Legacy-Patcher] Cannot build without wi-fi card installed (#354)

As we requested before, send a new traceback of how it crashes with the latest nightly build
