### ISSUE TITLE
Apps not showing on microphone/camera access list in system preferences.

### ISSUE THREAD

**Issue by emilnacool** [dortania/OpenCore-Legacy-Patcher#356]
Hello! I have macbook air mid 2011 with patched big sur everything works fine but sometimes the keyboard light isnt working but the big deal for me is Apps not showing up in Microphone/camera access list in system preferences

I am trying to give apps like Skype and zoom access to my microphone and camera but no apps are showing up in the list System Preferences>Security & Privacy> Privacy.

Please help me to solve these issues i already did clean install.

**Comment by Ausdauersportler** [comment]
Please use Discord to get help and please read first the available online docs - these are at the same spot where you miraculously found the software in the first place.

**Comment by emilnacool** [comment]
> Please use Discord to get help and please read first the available online docs - these are at the same spot where you miraculously found the software in the first place.

What is the discord server to get help?

**Comment by Ausdauersportler** [comment]
Again, read the docs and the download [page](https://github.com/dortania/OpenCore-Legacy-Patcher) line by line. Everything is there. Sorry, I am a little bit tired with this spoon feeding here.

**Comment by mdgm88** [comment]
For camera and microphone access you can see https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-grant-special-permissions-to-apps-ie-camera-access-to-zoom

Github is for reporting bugs, not for help with known limitations.

There are heaps of people posting on Discord and you can usually get a fast response there.

**Comment by dhinakg** [comment]
Covered in existing documentation
