### ISSUE TITLE
QUESTION: Does WiFi WPA2 Enterprise & Windows 10 Bootcamp Work???

### ISSUE THREAD

**Issue by southerndevz** [dortania/OpenCore-Legacy-Patcher#357]
1. Not a bug but questions. I have a MacBook Pro Mid-2012 15 inch Core i7 laptop. 
At work we use a **WPA2 Enterprise** WiFi network, **is it supported?**

2. Secondly, we also use Microsoft Visual Studio, so I dual boot to Windows 10 Bootcamp, i**s installing Bootcamp Windows possible while having Big Sur installed using this patcher?**

**Comment by khronokernel** [comment]
1. Yes
2. See our documentation for recommended usage of OpenCore with Windows:
https://dortania.github.io/OpenCore-Legacy-Patcher/WINDOWS.html
