### ISSUE TITLE
iMac11,3 immutable kernel

### ISSUE THREAD

**Issue by heyyceejayy** [dortania/Opencore-Legacy-Patcher#36]
Seems like no matter what I do, I'm met with immutable kernel, followed by a restart. Tried different installers (High Sierra and Catalina). Have not attempted to use Big Sur yet.

I also have a K4100M flashed to work on macOS, not sure if that would be the issue but I read that some kepler GPUs still work under BigSur. 

Edit: Forgot to mention, used latest version of patcher 0.0.7 at the time of writing.

**Comment by Ivantroniks** [comment]
![IMG_0518](https://user-images.githubusercontent.com/76612048/104414051-cb242e00-552c-11eb-9af8-b3d6509947f3.jpg)
Same MacPro 3.1
GPU: GTX 680 4gb Flashed 
Patcher 0.0.9

**Comment by khronokernel** [comment]
> Seems like no matter what I do, I'm met with immutable kernel, followed by a restart. Tried different installers (High Sierra and Catalina). Have not attempted to use Big Sur yet.

Resolved in main
