### ISSUE TITLE
MacBookPro11,1: Fatal system bugs after a warning box appears

### ISSUE THREAD

**Issue by paoloseril** [dortania/OpenCore-Legacy-Patcher#361]
**Describe the bug**
When I use my Mac for a long time, a warning box would sometimes pop up with a message "The application 'Diagnostics Reporter' is not open anymore.". That would be a no big deal to dismiss until after a few minutes later, multiple fatal problems in my Mac all happened at once:

1. Some third-party applications, such as Brave Browser, Spotify, and Drafts, cannot be opened.
2. The following System preferences do not load when clicked:
    2.1.: Desktop and Screen Saver
    2.2.: Notifications
    2.3.: Sound
    2.4.: Sidecar
3. Safari can be still opened, but when trying to [re]load a webpage, it repeatedly crashes.

**To Reproduce**
Steps to reproduce the behavior (try first with MacBookPro11,1):
1. Use the Mac for a period of time, until that warning box appears.
2. Try opening a number of third-party (and Apple) applications, and the mentioned preferences to see if they really open or not.

**Hardware:**
 - OS Running (macOS 12.0 beta 2, Monterey)
 - Model Patching (MacBookPro11,1)

**Additional context**
Restarting the Mac temporarily resolves the issue.

**Comment by khronokernel** [comment]
Monterey bug
