### ISSUE TITLE
OC makes USB boot disk problem as shown in the figure!

### ISSUE THREAD

**Issue by dupan338** [dortania/OpenCore-Legacy-Patcher#363]
Could you please tell me why there is no item in the U boot I made and it shows NO NAME
![IMG_20210706_072116](https://user-images.githubusercontent.com/72960986/124524010-e1e87500-de2b-11eb-8f8d-0d749cf3c3a1.jpg)

**Comment by khronokernel** [comment]
This project is for legacy Macs, not hackintoshes
