### ISSUE TITLE
Legacy Bluetooth Support dropped in macOS Monterey

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#364]
With macOS Monterey, Apple has rewritten the bluetooth stack with 2 main changes:

* Move Bluetooth Stack from kernelspace to userspace
* Drop legacy support for BCM2046 Bluetooth Modules

Due to this, many legacy Macs have lost bluetooth support outright. Newer modules based off the BCM2070 chipset are not affected as they're designed to retain their firmware, and only BCM2046 need their firmware loaded on each boot.

Within macOS Monterey, Apple stores Bluetooth firmware under `/usr/share/firmware/` and loads these firmwares with a new tool called BlueTool residing under `/usr/sbin/`. Device IDs are hard coded however could be patched to allow a wider array of devices.

## Affected Devices

Currently the following BCM2046 Bluetooth chipsets have lost support:

* 05AC,820F
* 05AC,8210
* 05AC,8213
* 05AC,8215
* 05AC,8216

Additionally, the following models are affected:

* iMac12,x and older
* Macmini4,1 and older
* MacBook7,x and older
* MacBookAir4,1 and older
* MacBookPro8,x and older
* MacPro5,1 and older

## Work Arounds

Currently we recommend users search for native Bluetooth chipsets as we're unsure when we may be able to implement a proper solution. Currently the following chipsets have native support within macOS:

* BCM2070 (Bluetooth 3.0)
* BCM20702 (Bluetooth 4.0)
* BCM20703 (Bluetooth 4.1/4.2)

Additionally the following Wireless Modules have natively supported Bluetooth chipsets bundled in:

* BCM943224
* BCM94331
* BCM94360
* BCM943602

**Comment by HerrSpigot** [comment]
My Bluetooth also doesn’t work anymore on my MacBookAir5,1

**Comment by khronokernel** [comment]
@HerrSpigot Completely unrelated issue, BCM94331 issues present in 2011-2012 machines are isolated to Monterey beta 4. They have no relation to firmware uploading concerns present with BCM2046 chipsets

**Comment by vladimirmm** [comment]
Bluetooth stopped working on my MacBook Pro 9,2 since Monterey Beta 4. Hope it returns to normal operation in beta 5

**Comment by khronokernel** [comment]
@vladimirmm Users reported the below can aid in resolving beta 4's Bluetooth issues:

```sh
sudo killall -9 BlueTool bluetoothd
```

**Comment by vladimirmm** [comment]
> @vladimirmm Users reported the below can aid in resolving beta 4's Bluetooth issues:
> 
> ```shell
> sudo killall -9 BlueTool bluetoothd
> ```

Thanks for your help!
I've tried the command in terminal, inserted my password and then restarted the system, unfortunately it did not work... is there a specific way to insert this command?

**Comment by dhinakg** [comment]
Do not restart, otherwise the process will start again

**Comment by vladimirmm** [comment]
> Do not restart, otherwise the process will start again

Still does not work... but thanks a LOT for your help!

**Comment by vladimirmm** [comment]
Bluetooth still disabled after updating to Monterey Beta 5 on MacBook Pro 9,2 😔

**Comment by khronokernel** [comment]
Please keep discussion related to the BCM2046 issue, this is not a BCM94331 issue thread. Use forums for Apple bugs

**Comment by khronokernel** [comment]
Forgot to close issue
