### ISSUE TITLE
Performance issue (MacBookPro8,2)

### ISSUE THREAD

**Issue by arthedza** [dortania/OpenCore-Legacy-Patcher#366]
### Machine Model

MacBookPro8,2

### Application Version

0.2.2 (Latest Release)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

I can't achieve a graphic acceleration on my MacBook Pro 8,2. I've made already all described [here](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-achieve-gpu-acceleration-on-2011-15-and-17-macbook-pros) but my laptop is very laggy all the same. I saw that the discrete graphic adapter was turned off via hardware level (using the handmade jumpers). Could you help me with this situation? Maybe you need to get some more diagnostic information -- just tell me how can I get it and I will provide it. Or maybe there are could be any other reasons also and it's not about graphic acceleration only. But I'm definitely having a lagging laptop now with probably over high power consumption.

**Comment by khronokernel** [comment]
Did you run the post install patches from OCLP to enable acceleration? If so, please send an IOReg (File -> SaveAs):

https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip

Additionally please verify if the latest OCLP Root Patches experience this issue:

https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip

**Comment by arthedza** [comment]
> Did you run the post install patches from OCLP to enable acceleration? If so, please send an IOReg (File -> SaveAs):
> 
> https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip
> 
> Additionally please verify if the latest OCLP Root Patches experience this issue:
> 
> https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip

Thank you for your quick response. Yeah, I have post-installed patches. I sent you IOReg on khronokernel@icloud.com. I'll try the latest OCLP a bit later.

**Comment by khronokernel** [comment]
Thank you for sending the IOReg, I can see that the graphics drivers doesn't recognize the integrated GPU for whatever reason:

<img width="335" alt="Screen Shot 2021-07-07 at 4 34 16 PM" src="https://user-images.githubusercontent.com/48863253/124836978-32052b80-df41-11eb-9b77-704676723899.png">

Could you run `ls /System/Library/Extensions/ > ~/Desktop/ls-sle.txt` and send the file generated on your desktop? I have a suspicion that the root volume patches either failed to install correctly or have become corrupt in some way, as the Intel HD3000 drivers rarely fail

**Comment by arthedza** [comment]
> ls-sle

I sent it via email

**Comment by khronokernel** [comment]
This seems to be an unfortunate bug with macOS snapshots, as I see it refuses to boot the new patched volume. Please reinstall the OS, root volume patches should work correctly then. If you still experience issues afterwards, just comment and I’ll reopen the issue
