### ISSUE TITLE
[Bug]: Your computer was restarted because of a problem.

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#367]
### Machine Model

MacBookPro11,3

### Application Version

0.2.2 (Latest Release)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Every time the laptop is rebooted, an error message "Your computer was restarted because of a problem" comes up.

**Comment by khronokernel** [comment]
Monterey bug
