### ISSUE TITLE
MacBook Air 4,2 - seems to boots to recovery partition

### ISSUE THREAD

**Issue by beggles** [dortania/Opencore-Legacy-Patcher#37]
Using v0.0.7 in an attempt to install Catalina 10.15.7 to MacBook Air 4,2, booting into picker starts OC (0.6.3) and then reboots into what appears to be the installer, only to give the option to reinstall OS has High Sierra, rather then Catalina?

Build Folder attached for reference.
[Build-Folder.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5744357/Build-Folder.zip)

**Comment by ulf16** [comment]
I can confirm this behavior on a macmini5,3. No matter what I choose as a boot device (High Sierra, High Sierra Recovery, Catalina Recovery) it attempts to boot and instantly reboots after handing over to the OS. After that, the Mac seems to default to booting the native Recovery Volume and avoids another OpenCore boot. This also happens with OpenCore 0.6.5 and 0.6.3.

**Comment by family1232009** [comment]
Can confirm this on a MacBookPro9,2

**Comment by family1232009** [comment]
> Using v0.0.7 in an attempt to install Catalina 10.15.7 to MacBook Air 4,2, booting into picker starts OC (0.6.3) and then reboots into what appears to be the installer, only to give the option to reinstall OS has High Sierra, rather then Catalina?
In config.plist: Misc -> Security -> SecureBootModel - Disabled

**Comment by khronokernel** [comment]
https://github.com/dortania/Opencore-Legacy-Patcher/blob/main/docs/TROUBLESHOOTING.md#infinite-recovery-os-booting

We recommended resetting NVRAM and attempt again
