### ISSUE TITLE
Why 0.2.2, 0.2.1 can't be used, but 0.1.9 can be used

### ISSUE THREAD

**Issue by mjs520** [dortania/OpenCore-Legacy-Patcher#370]
The following error occurred：
Open the software, report an error and exit

Loading...
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 296, in <module>
  File "OpenCore-Patcher.command", line 17, in __init__
  File "Resources/device_probe.py", line 279, in probe
  File "Resources/device_probe.py", line 333, in wifi_probe
  File "Resources/device_probe.py", line 43, in from_ioregistry
  File "<string>", line 9, in __init__
  File "Resources/device_probe.py", line 109, in __post_init__
KeyError: 'spairport_airport_interfaces'
[677] Failed to execute script OpenCore-Patcher
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Is it related to 0.2 change detection logic? Can you fix this problem? Thank you

**Comment by dupan338** [comment]
我也是同样的问题，望解决！

**Comment by dupan338** [comment]
I and his same problem, hope to solve!

**Comment by Ausdauersportler** [comment]
Please try the nightly build (link on main Github page). A speaking title like "Airport Device Detection fails on 0.2.2" would be helpful, too.

**Comment by mjs520** [comment]
> 请尝试每晚构建（Github 主页面上的链接）。像“机场设备检测在 0.2.2 上失败”这样的口语标题也会有帮助。

I don't know what you mean. Could you be more careful, thank you

**Comment by mjs520** [comment]
> Please try the nightly build (link on main Github page). A speaking title like "Airport Device Detection fails on 0.2.2" would be helpful, too.

Now I want to open the software to run, but the version above 0.2 reports an error, and the software automatically exits. I just want to patch hd4000

**Comment by khronokernel** [comment]
@mjs520 Couple things:

1. Do not open blank issues. The Form must be used and should not be edited after the fact
2. This issue was resolved in 0.2.3 no?
3. This is a hackintosh isn't it, no support provided as we previously told you

Keep reporting issues for a hackintosh will have your privileges revoked. This repository is for Legacy Macs only
