### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#372]
### Machine Model

MacPro5,1

### Application Version

0.2.2 (Latest Release)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur, macOS 10.15, Catalina

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

When I use `Startup Disk` (`System Preferences`) to select another macOS install (Catalina) from Big Sur (11.2.3) it is not "sticking" on `Restart...`.  Not sure what is broken in this regard, but clearly something is up.

**Comment by ylluminate** [comment]
For what it's worth, using `control-enter` to at startup seems to make it stick between reboots.

**Comment by khronokernel** [comment]
Out of scope of patcher and not replicable locally, closing
