### ISSUE TITLE
[Bug]: ATI Radeon HD 5770 not being accelerated.

### ISSUE THREAD

**Issue by jaydengamble6** [dortania/OpenCore-Legacy-Patcher#373]
### Machine Model

MacPro5,1

### Application Version

0.2.2 (Latest Release)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

I've turned on 'Enable Terascale 2 Acceleration' and rebooted but I have no transparency, choppy animations, and many programs report no acceleration. Any idea of why this isn't working?

**Comment by khronokernel** [comment]
Currently away at the moment so can't look closely however please verify whether 0.2.3 also experiences this issue. Remember to run post-install patches (TeraScale 2 patches are enabled by default so no setting is provided):
https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip

When I return I'll look into any possible issues in the code and ask some more questions

**Comment by khronokernel** [comment]
Verified locally with a clean install of macOS 11.4 with OpenCore Legacy Patcher v0.2.3 (latest nightly) on a MacPro3,1 with an ATI HD5770:

![Screen Shot 2021-07-07 at 4 26 53 PM](https://user-images.githubusercontent.com/48863253/124836763-c1f6a580-df40-11eb-82fb-e5124bf45de4.png)

I recommend a reinstallation of the OS if you still have issues, as we cannot replicate locally with the exact same GPU and similar machine

**Comment by jaydengamble6** [comment]
@khronokernel I just tried the nightly Patcher and I used Post-Install and now I've got a kernel panic on startup![PXL_20210708_072947672.MP.jpg](https://user-images.githubusercontent.com/75391793/124881463-43911680-dfc7-11eb-87a9-68a939e08579.jpg)

**Comment by khronokernel** [comment]
This is due to a missing `amfi_get_out_of_my_way=0x1`in boot-args, how were you able t patch the root volume for TS2 accel without that? I verified and the code is still active, I tried patching the root volume on a machine and it errored correctly.

Regardless, boot a native OS, disable AMFI in patcher settings and build/install a new OpenCore. This will resolve the issue

**Comment by jaydengamble6** [comment]
@khronokernel Honestly I have no idea how it did, my Mac Pro is weird when it comes to patchers, I'll try it when I get home

**Comment by jaydengamble6** [comment]
@khronokernel Disable AMFI worked and I definitely see what you meant by epilepsy warning.
