### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Vanrodrod** [dortania/OpenCore-Legacy-Patcher#374]
### Machine Model

MacBook8,1

### Application Version

0.2.2 (Latest Release)

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Good evening I just followed the tutorial to install big sur a mac book pro at the end of 2011 with open core legacy patch 0.2.2 at the end of installation black screen with the apple and the white bar full "there is less than a minute left" the mac hangs. I can't do anything big sur won't start. What to do thank you.

**Comment by khronokernel** [comment]
> "there is less than a minute left" the mac hangs

This is not a hang, this is the stage where the machine seals the APFS snapshot. If you shutdown the machine at this point, reinstall and allow the machine to completely install and hit the setup screen. Generally 45min is recommended for that screen as these older machines can be quite slow in cryptography involved with the sealing.

Note, same situation happens on native Macs as well. Its just a slow step with inaccurate time estimate

**Comment by Vanrodrod** [comment]
Thank you for your quick response if I understand correctly when there is less than a minute left a full white bar you still have to pacient for about 45 minutes.



Envoyé de mon iPad
