### ISSUE TITLE
[Bug]: can not select install disk

### ISSUE THREAD

**Issue by cocoflan** [dortania/OpenCore-Legacy-Patcher#375]
### Machine Model

iMac9,1

### Application Version

0.2.2 (Latest Release)

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur, macOS 10.14, Mojave, macOS 10.13, High Sierra

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Did everything as described, but when I start the installation via EFI as described, I see my disks but then I can't choose a disk to install even though my target disk is formatted correctly. 

This version of MACOS cannot be installed on your system when i indicate disk to install.  On Sierra, also tested High Sierra and Big sur.

IMAC 24 early 2009.

Greetings

**Comment by khronokernel** [comment]
OpenCore Legacy Patcher only officially supports Big Sur, closing as user error and little proper information provided. Use forums for discussions
