### ISSUE TITLE
[Bug]: I can't build OC

### ISSUE THREAD

**Issue by Ivantroniks** [dortania/OpenCore-Legacy-Patcher#376]
### Machine Model

MacPro3,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I can't build OC

I add an image:
![Build](https://user-images.githubusercontent.com/76612048/124849390-ed3abe00-df5b-11eb-99fb-90bf4958df46.png)

**Comment by dupan338** [comment]
Hello, where did you download version 0.23? Can you share it with me?

**Comment by Ivantroniks** [comment]
Hi, Download it from here: https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip

**Comment by dupan338** [comment]
> 嗨，从这里下载：[https](https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip) : [//nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip](https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip)

Thank you

**Comment by dhinakg** [comment]
Do you have an NVMe SSD?

**Comment by Ivantroniks** [comment]
I have NVMe

**Comment by dumo** [comment]
Building Configuration on model: MacBookAir6,2
Created build folder

- Adding OpenCore v0.7.0 RELEASE
- Adding config.plist for OpenCore
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 294, in <module>
  File "OpenCore-Patcher.command", line 288, in main_menu
  File "Utilities.py", line 246, in start
  File "OpenCore-Patcher.command", line 76, in build_opencore
  File "Build.py", line 882, in build_opencore
  File "Build.py", line 157, in build_efi
TypeError: Cannot pickle Objective-C objects
[25459] Failed to execute script OpenCore-Patcher
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...33 completed.

**Comment by khronokernel** [comment]
Could you verify the [latest commit](https://github.com/dortania/OpenCore-Legacy-Patcher/commit/9cf19319c552abd96710e748944dd1cfc446c38d) resolves this?
https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip

**Comment by Ivantroniks** [comment]
It's resolved, thank you.


![Build OK](https://user-images.githubusercontent.com/76612048/125177516-b520be80-e199-11eb-84c4-8f45e09cad26.png)
