### ISSUE TITLE
[UI Improvement]: Expand drive selector UI

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#379]
### Machine Model

MacPro5,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

It would be nice to have more verbosity in the drive selector to help identify drives more clearly such as volume names of volumes on the drives, and size. The size should also be expanded for those of us who may have more drives than what actually fit in the drawer (it's not easy to know we need to scroll to the right to get other drives in cases with more drives than fit in the drawer like mine). Here's an example of what is currently seen:

![drives](https://p153.p0.n0.cdn.getcloudapp.com/items/bLukv0N7/3f159f04-a906-4c93-be22-d833b9802bb1.jpg?v=5fd2fde183a97104b58e55f62d371f38)

There are a few more drives to the right of these. Furthermore it is difficult to identify which drive is which without going into Disk Utility and then using the expanded view of the drives/volumes.

**Comment by khronokernel** [comment]
Forgot to close this when we pushed:
https://github.com/dortania/OCLP-GUI/commit/da7edca3ca119798c3f9a8fdeece76cb2eba5108
