### ISSUE TITLE
Won't Turn On after 11.1 udpate

### ISSUE THREAD

**Issue by narfasd** [dortania/Opencore-Legacy-Patcher#38]
After installing Big Sur everything was ok, so I started to update to 11.1, after a few minutes, my imac won't turn on (completely black screen) Any suggestion? Model: iMac 27" 2012.

**Comment by BenSova** [comment]
Disconnect all power, wait a little bit, then try turning it on again.

**Comment by arch-gp-z** [comment]
if power off, pram etc tricks not working, the EFI ROM firmware might get corrupted.

**Comment by BenSova** [comment]
The firmware is already wrong (not necessarily corrupt since it is a good firmware, just not one designed for that model), that's what removing all power should fix, it's worked for every other Mac with open core and macOS trying to install firmware updates.

**Comment by arch-gp-z** [comment]
@BenSova thanks for the correction, yes it shoud be called wrong firmware from different model (iMac15,x), which was flashed into EFI ROM chip. As I know, that is written into the chip so powering off would not work at least not working for me with iMac14,2 and cases were reported working on MacBook Pro by removing battery connector. I mentioned in other comments as well, my iMac14,2 was bricked from that, nothing worked except reflash the ROM chip. I even dumped the wrong firmware from the chip and opened it with UEFITool, the Intel ME version was wrong as well as model ID. A reflash to the EFI ROM chip fixed it in my experience.

**Comment by narfasd** [comment]
Thank you so much for all your comments! I've already tried all the standard procedures (pram, power, nvram, etc.) and nothing work, so I think I'll need to do a reflash of the EFI ROM. If you have any guide that you have followed for this it would be very useful. 
Thanks again!

**Comment by arch-gp-z** [comment]
https://github.com/dortania/Opencore-Legacy-Patcher/issues/32

**Comment by dhinakg** [comment]
Just to confirm, what's the model identifier of your Mac? It may be prudent to add this to the blocklist too.

**Comment by arch-gp-z** [comment]
@dhinakg iMac 27" 2012 as mentioned, so it is iMac13,2. Refer home page, iMac14,x is alrealdy blocklisted.
