### ISSUE TITLE
[Explanation]: AMFI disables permission request dialogues for some applications

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#380]
### Machine Model

MacPro5,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

It would be helpful to users to further understand AMFI disablement ramifications by noting how doing this will stop some apps like Zoom, ManyCam, or other apps that might need microphone and/or webcam access from prompting for access.

If they desire to do this, a manual addition to the TCC database will be required such as something like this for Zoom:
```
# get bundle id:
$ osascript -e 'id of app "zoom.us"'
# output: us.zoom.xos

$ sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceMicrophone','us.zoom.xos',0,2,0,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);"

$ sudo sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access VALUES('kTCCServiceCamera','us.zoom.xos',0,2,0,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);"

```

**Comment by khronokernel** [comment]
Is this not already documented?
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html

**Comment by ylluminate** [comment]
Hmm, well I don't believe that that is really sufficient documentation when it's not in the UI or at least linked to therein. I am of the UX school that information such as this should have at least hints in the UI that will inform the user. Perhaps we can expand the information about each of these in such a way as to link the user to the documentation for more details?

**Comment by khronokernel** [comment]
Feel free to PR
