### ISSUE TITLE
iMac14,3 and OCLP 0.2.3 the new "Enable wake on WLAN" option doesn't work

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#383]
### Machine Model

iMac14,3

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Related to the issue #353.

I tried installing the new OCLP 0.2.3 (bot TUI and GUI version). I enabled the new "Wake on WLAN" option. Then I tried rebooting and even reinstalling macOS Big Sur... but still: System Preferences only show "Wake up for ETHERNET network access"... and I can't wake my iMac over wifi.

So the new option doesn't seem to work... Should I send you some diagnostic files to help investigating ? Wake on WLAN is a really important option to have enabled for me...

**Comment by khronokernel** [comment]
With the TUI, send the build folder generated as well as an [IOReg](https://cdn.discordapp.com/attachments/573338411503714324/673375675184447528/IORegistryExplorer.zip)(File -> SaveAs)

**Comment by mat1696** [comment]
Build folder:
`Building Configuration on model: iMac14,3
Build folder already present, skipping
Deleting old copy of OpenCore folder

- Adding OpenCore v0.7.0 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.4
- Adding WhateverGreen.kext 1.5.1
- Adding SMC-Spoof.kext 1.0.0
- Adding CPUFriend.kext 1.2.4
- Adding FeatureUnlock.kext 1.0.3
- No 3rd Party NVMe drives found
- Found Wireless Device 14E4:43A0
- Adding AirportBrcmFixup.kext 2.1.3
- Setting Wireless Card's Country Code: DE
- Found ARPT device at PciRoot(0x0)/Pci(0x1c,0x2)/Pci(0x0,0x0)
- Enabling Wake on WLAN support
- Adding USB-Map.kext
- Adding AppleGraphicsPowerManagement Override
- Adding AppleGraphicsDevicePolicy Override
- Adding dual GPU patch
- Found GFX0 Device Path: PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)
- Adding OpenCanopy GUI
- Hiding picker and enabling PollAppleHotKeys
- Disabling SecureBootModel
- Setting macOS Monterey Supported SMBIOS
- Spoofing to iMac17,1
- Using Board ID: Mac-DB15BD556843C820
- Using Minimal SMBIOS patching
- Cleaning up files

Your OpenCore EFI for iMac14,3 has been built at:
    /private/var/folders/n9/p_gkk3392fg4ysxlfjflbj1h0000gn/T/_MEICZEr2Y/Build-Folder/OpenCore-Build
`

[iMac de Mathis.ioreg.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6803448/iMac.de.Mathis.ioreg.zip)

Thanks!

**Comment by mat1696** [comment]
It still doesn't seem to work as expected with the latest nightly build... at least the nightly version is too old, but I don't think so...

I opened a new issue #388 as you closed that one.
