### ISSUE TITLE
Delta Update to macOS Monterey 12 beta 3 from beta 2?

### ISSUE THREAD

**Issue by owenzhao** [dortania/OpenCore-Legacy-Patcher#386]
### Machine Model

MacBookAir6,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I was told that one of the benefits of using OLP was the user could update macOS with the official delta update package. However, I couldn't get the system update to show the update package and it seemed no where to download the package either.

I am using macOS Monterey 12 beta 2. For me, what is the best way to update to beta 3?

**Comment by Ausdauersportler** [comment]
Please use the Discord server mentioned on the main Github pages to discuss those non issues. The current update is available only to those who subscribed to the Apple developer macOS  beta program. 
You will be notified by Apple and the software update when the next public beta is available.

**Comment by owenzhao** [comment]
> Please use the Discord server mentioned on the main Github pages to discuss those non issues. The current update is available only to those who subscribed to the Apple developer macOS beta program.
> You will be notified by Apple and the software update when the next public beta is available.

Thank you for the reply. I didn't install the profile as it was shown as the Mac is register in Apple Developer Seed Project. However, after I saw this reply and installed the profile, the system asked me if I wanted to download macOS Monterey 12 again. From the comment of MacRumors forum, this should be the real update.
