### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by stschulze1972** [dortania/OpenCore-Legacy-Patcher#387]
### Machine Model

MacPro5,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I can't build my opencore-package .... 

![image](https://user-images.githubusercontent.com/60463122/125760389-38b14efb-6148-45ca-9ec1-d9ec4aae3c5c.png)

![image](https://user-images.githubusercontent.com/60463122/125760134-bb0dbafc-e5fd-4aaa-b348-fa3f4eb8a8a5.png)

**Comment by khronokernel** [comment]
As our documentation mention, format drive as GUID:
https://dortania.github.io/OpenCore-Legacy-Patcher/BUILD.html
