### ISSUE TITLE
Still no wake on WLAN with 0.2.4 nightly build (TUI version) on iMac14,3

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#388]
### Machine Model

iMac14,3

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Related to the issues #383 and #353 .

I tested out with the nightly TUI build and I still can't enable Wake on WLAN. 

![Capture d’écran 2021-06-30 à 01 59 02](https://user-images.githubusercontent.com/86326794/125849557-813b5665-d59f-4d71-be74-7d1ca7604510.png)

[iMac de Mathis.ioreg.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6825981/iMac.de.Mathis.ioreg.zip)

Sorry... I hope you will be able to fix this soon, and wanted to thank you again for your amazing work with OCLP!!!

**Comment by mat1696** [comment]
I installed macOS 11.5 and the latest patcher version and still not able to enable wake on WLAN… I really need this feature in order to use my iMac with Big Sur, please :)

**Comment by khronokernel** [comment]
You can verify if this commit works:
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/0af93e793660f99845d1951b6bfea7212831f1eb

If still broken, will revert all code and remove the Wake on WLAN setting. Feel free to PR changes however no one else is requesting this feature so dedicating time and resources is difficult on our end

**Comment by mat1696** [comment]
Yes it works with the latest nighty build! Thanks a lot for the incredible job you are doing, that's priceless :)
