### ISSUE TITLE
Can't detect my external drive during installation of patches

### ISSUE THREAD

**Issue by Wolsink89** [dortania/OpenCore-Legacy-Patcher#389]
### Machine Model

MacBookPro8,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

When you are about to install the built patches #1 then #2 install (TUI), it is only detecting my internal Disks both SSD and the Data disk.  No bootable external disk was bring detected

**Comment by Ausdauersportler** [comment]
What is your current problem?

1) You cannot install Big Sur using the prepared USB installer onto an external USB drive?

2) You cannot patch Big Sur on an external USB device?

The OCLP installer/patcher software is designed to 1) install OpenCore and 2) patch the system you currently have booted after a complete installation of Big Sur. 

You cannot cross patch another non booted installation on external disks. The root devices of your current boot system will be shown by the terminal `mount` command.

**Comment by khronokernel** [comment]
User error, format drive as GUID Partition Table
