### ISSUE TITLE
rEFInd with OCLP

### ISSUE THREAD

**Issue by annaclets** [dortania/OpenCore-Legacy-Patcher#391]
### Machine Model

MacBookPro5,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Great work! Using OCLP 0.2.3, I have successfully installed Big Sur 11.4 on my MacBook Pro late 2008 (MacBookPro5,1). Everything works, except for keyboard backlighting.

My system bootloader is rEFInd, which I use for multi-booting macOS, Windows and Linux. I have not copied OCLP to my EFI because I'm afraid - based on my Hackintosh experience - that OpenCore would aggressively take over (do a boot coup) and limit my multi-boot to macOS.

Can I make OCLP simply be a be a boot item for rEFInd? Pls advise.

**Comment by khronokernel** [comment]
As with the OpenCore developers, we have no plans of supporting chain loading through rEFind. This can create many issues and force the usage of hacks within OpenCore

Users may do as they wish however will not be support by us
