### ISSUE TITLE
[Bug]: stuck on a blank screen

### ISSUE THREAD

**Issue by MBA31PORTBRA-2010** [dortania/OpenCore-Legacy-Patcher#392]
### Machine Model

MacBookAir3,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Help! I created disk Monterey using GUI 0.23 legacy patcher; Start a clean install; it loads fine I choose the GUI partition, start the installation until the end; and then, MacBook 3,1 reboots, but now a blank screen appears… and nothing happens…processor is working start to heat, comes back normally, but after a hour nothing happens;

**Comment by Ausdauersportler** [comment]
For easy troubleshooting and discussion with developers, we recommend joining the [OpenCore Patcher Paradise](https://discord.gg/rqdPgH8xSN) Discord.

**Comment by owenzhao** [comment]
Did you just removed the usb drive? Some Macs just remembered where the EFI it booted last. You had to hold Option key and told you Mac to boot from the EFI from the internal disk for once.

**Comment by khronokernel** [comment]
Closing as seems user error, use forum or discord
