### ISSUE TITLE
[Bug]: How to get Mojave booting with OCLP?

### ISSUE THREAD

**Issue by ylluminate** [dortania/OpenCore-Legacy-Patcher#393]
### Machine Model

MacPro5,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 10.14, Mojave

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Have been running Mojave 10.14.6 on OpenCore 0.6 on a MacPro5,1 (4,1 upgraded). Decided I wanted to move to OCLP to have a sane OC environment that's easily updatable before I upgrade the system to Catalina. When I ran OCLP and rebooted the machine, I was greeted with the following:

![uefi picker](https://p153.p0.n0.cdn.getcloudapp.com/items/o0uezWOG/746b9d30-bf2a-4af1-bf5c-7dcd2e96b0ba.jpg?v=51cb5d9081a9f2f72809373ac4e74984)

![opencore](https://p153.p0.n0.cdn.getcloudapp.com/items/E0uAQwJN/96b35629-e73d-46cb-9667-b2fe38fc9ac2.jpg?v=0e6ace9674c953497276c6dea8546eb5)

![failure](https://p153.p0.n0.cdn.getcloudapp.com/items/nOuPyqJZ/eadaf938-ea1b-488c-8ce0-2a27843b7e44.jpg?v=dc78729457a166a744fd8ff2585ff320)

Any thoughts on what may be going on here or how to resolve?

### Any Additional Information

*NOTE: Ignore the wrong (green) hue for the time being. It appears to be an issue generally with OC and has been happening the entire time using it with this monitor. When macOS starts the driver this resolves so I can look into that problem later.

**Comment by dhinakg** [comment]
OCLP does not support Catalina and below

**Comment by ylluminate** [comment]
Oh, hmm, thanks... I thought Catalina and below were functional based on previous discussions in Discord. Then I suppose the only method to coax < Catalina booting is changing the SMBIOS or using `-no_compat_check`?
