### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yahgoo** [dortania/OpenCore-Legacy-Patcher#394]
### Machine Model

MacBookPro9,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 10.15, Catalina

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

After OCLP v0.2.3 download is completed, eset anti-malware cleaned OCLP-CLI due to a variant of Generik.MLJGGMQ trojan

### Any Additional Information

18/7/21, 10:13:11 AM	Real-time file system protection	file	/Users/yahgoo/Downloads/Hackintosh Tools/OpenCore Patcher.app/Contents/Resources/OCLP-CLI	a variant of Generik.MLJGGMQ trojan	cleaned by deleting	yahgoo	Event occurred on a new file created by the application: /Applications/Safari.app/Contents/XPCServices/com.apple.Safari.SandboxBroker.xpc/Contents/MacOS/com.apple.Safari.SandboxBroker (71552DEC3ED106D9CA55299206CDB18F6CB23922).	C246B706F2A201CBE9389AA9BCF7DEC7858D455E	12. 7.2021 02:52:31

**Comment by khronokernel** [comment]
All source code is open sourced and is notarized directly by Apple, file a complaint with your anti virus vendor
