### ISSUE TITLE
[Bug]: TS2 patches spreading over to HS

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#395]
### Machine Model

iMac11,3

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

So, i have TS2 ATI Radeon 5750 1024 mb VRAM, 8 GB RAM, and i installed OCLP (Big Sur) on my mac. I have a 1.5 TB HS partition and a 500 GB Big Sur OC partition aswell as OC EFI installed on internal drive. I patched TS2 patches while in Big Sur, forced display to million colours and was working pretty well. I decided to boot into HS via option menu (Not OC EFI) and when i got it, everything seemed normal. But, when i download SwitchResX on HS aswell, i forced display into billion colors and had the same issue Big Sur did. I have reset my NVRAM via OC EFI, booted into HS and everything is fine. I have not booted into BS yet, but assuming SwitchResX stores values in NVRAM, it looks like billion colors is working, though i have not yet confirmed.

**Comment by Thyssenkrupp234** [comment]
I might boot into BS later on this week to test it out.

**Comment by khronokernel** [comment]
Closing as not an OpenCore Legacy Patcher issue
