### ISSUE TITLE
[Feature request]: Implement Kryptonite for OCLP

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#396]
### Machine Model

MacBookPro11,3

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

It would be nice to get Kryptonite implemented to OCLP, currently, the kext has to be injected manually but there are some problems with it.

### Any Additional Information

Information about Kryptonite: https://github.com/mayankk2308/kryptonite

**Comment by dhinakg** [comment]
We cannot add Kryptonite for legal reasons.

**Comment by khronokernel** [comment]
Cannot implement due to licensing issues, OpenCore Legacy patcher would need to be under GPLv3 license:
https://github.com/mayankk2308/kryptonite/blob/main/LICENSE.md
