### ISSUE TITLE
Universal Control is Disabled [monterey]

### ISSUE THREAD

**Issue by D33D00** [dortania/OpenCore-Legacy-Patcher#399]
### Machine Model

iMac10,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Universal Control preferences are not available under advanced display settings. Universal Control is likely disabled altogether. Monterey Developer Beta 3 (latest version at the time of writing)

**Comment by khronokernel** [comment]
Universal Control has not be released to the public in general even under beta 3, those are simply references in the OS

**Comment by vishnunuk** [comment]
Yes, This is true, Stable version is out. it is disabled.
