### ISSUE TITLE
This version of Mac OS X is not supported on this platform.

### ISSUE THREAD

**Issue by alroberts** [dortania/Opencore-Legacy-Patcher#4]
Hi there,

Not able to get this patcher to work on the Mac Pro 4,1 > 5,1.

- Fresh install of Mojave
- Downloaded this Patcher
- Ran using "option 1"
- Used Opencore Configurator to mount EFI partition
- Rebooted into Recovery Mode
- Blessed the EFI partition for booting
- Boot screen loaded with OS selector, however no OS will boot
- Shows message "This version of Mac OS X is not supported on this platform."

It's possible that I've done something wrong, but considering there are no instructions, this was my best attempt.

Mac Pro (Early 2009) flashed to 5,1.
ATI Radeon RX580
3.46 GHz 6-Core Intel Xeon

Any fix / suggestions?

**Comment by dennes544** [comment]
After you built Opencore, you need to install in to efi partition with option 2 in main menu. After that reboot to OS selector and select "EFI Boot"

**Comment by jaybanger1** [comment]
Yeah you don't need to use opencore configurator at all. Use the patcher, it will create a proper config, mount, and install the open core to your USB stick.

"Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking." -Steve Jobs

**Comment by alroberts** [comment]
Sorry guys, you've lost me at USB stick. My workflow was exactly as above. I've been able to successfully install and boot macOS 11 using this guide...(https://www.youtube.com/watch?v=z2W5DXIxYTs) but I feel that this patcher here is better long term. Using the above method, I was able to update directly via "Software Update" to macOS 11.

I'm just applying the same process, but with the generated OC files from this patcher... so basically, I'm still lost. Is there a complete walkthrough?

**Comment by jaybanger1** [comment]
So you are able to boot into OS 11 Big Sur on your Mac Pro. An you would like to update your EFI partition with the files generated by the patcher got it. That should be easy. You "should" be able to simply be able to download the patcher (on the machine in question) and have it auto generate the EFI files to your existing EFI partition. You will need to have to hold down the option key and select the EFI partition which should then show you the picker and allow you to choose your boot drive. Once that's done you should be able to just boot next time and your Mac Pro will select the correct drive and  boot. Side notes, you will need a video card that supports the Mac boot screen to use to do this at least once.  I am assuming your boot drive is on the internal sata bus. I have personally had trouble booting using the EFI procedure from internal PCI cards.
