### ISSUE TITLE
Mac Mini 6,1 bricked after Big Sur 11.1 Install

### ISSUE THREAD

**Issue by mistykasumi** [dortania/Opencore-Legacy-Patcher#40]
Hi,

I installed opencore 0.6.4 using the script on a Mac Mini 6,1 (late 2012 - Ivy Bridge machine).
As is commonly documented, the installer rebooted and the machine failed to POST (blinking front lights).
However, power-cycling as well as disconnecting the machine for several hours did not help, unlike the success I've had with my laptop.
While I assume/hope that when I remove the PRAM battery the machine will function correctly, perhaps it is better to blacklist those models as well since this is not a trivial recovery process.

**Comment by khronokernel** [comment]
I apologize that this happened to you, I believe it is probably best for us to discontinue the patcher outright. We’re currently quite busy with other projects and can’t focus time to diagnosing these issues, so I’d prefer to avoid these soft bricks if possible.

I’ll add a note to the README, perhaps others can look into the issue more and contribute a solution

**Comment by mistykasumi** [comment]
oh no that's perfectly fine I knew I was dealing with experimental software and I'm actually very happy with the old macbook pro upgrade - everything worked out of the box there and it was a delight. It's just worthy of note at this point that power cycling may not work all the time.

**Comment by trifygri** [comment]
I can confirm the permanent problem using 0.0.7 main on Mac mini Server (Late 2012),  Model Identifier: Macmini6,2. Machine is failing to POST (blinking front lights). No recovery by power cycling or other options. Maybe we can add a more explicit info to the Ivy Bridge README. Suppose I have to flash the old firmware like in #32. Thanks to @arch-gp-z for providing detailed information on this. Not complaining but motivating @dortania to keep up the excellent work 👍🏻 .

**Comment by mistykasumi** [comment]
@trifygri by "other options", do you also mean removing and re-inserting the PRAM battery? the laptop-equivalent of which worked for another laptop of mine.

**Comment by trifygri** [comment]
@mistykasumi no, only non hardware related options. Will try and report back but not short term, sorry.

**Comment by mistykasumi** [comment]
@trifygri I'll likely try this today and report back - just wanted to make sure I don't go through all this effort for something that has been tried already.

**Comment by mistykasumi** [comment]
I'm happy to report that removing the PRAM battery and replacing it worked like a charm! The mac booted into Big Sur 11.1 and it appears all hardware is fully functional.

**Comment by Bustycat** [comment]
Successfully updated OpenCore to 0.6.5 and found my MacBookPro's FW version becomes 429.0.0.0.0. Does it mean that the issue could be resolved by using 0.6.5?
