### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MBA31PORTBRA-2010** [dortania/OpenCore-Legacy-Patcher#400]
### Machine Model

MacBookAir3,1

### Application Version

0.2.2 (Latest Release)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

after create media on Mojave, copying open core to Disk EFI, start Install, choosing disk to install, it starts however going to the end when 12 lasts to finish (12 minutes to "finish") suddenly computer restarts, And Apples Logo with progress bar appears restart twice, but never launches, it stucks at the middle of process...I reboot manually but problems persists..what can I do?

**Comment by Ausdauersportler** [comment]
You already mentioned on Discord your failing SSD shows SMART errors, installation on possibly USB thumb drive  is an questionable idea - why do you believe your endless list of private hardware problems is a software issue of this tool? Discord is the platform to discuss such issues, I bet there are hardware shops nearby where you can get a new SSD.

**Comment by MBA31PORTBRA-2010** [comment]
Sorry, I forget to mention that my Failing SSD is truly new, because this I insist...its 5 months old, however I install windows on a petition , and after desinstalo, after that this problem begun. And as solution for that, my idea to install on USB drive. My apologies. :(

**Comment by khronokernel** [comment]
Closing as local hardware issue, cannot fix
