### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rithondwima** [dortania/OpenCore-Legacy-Patcher#401]
### Machine Model

Macmini5,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I used macMini 5,2 which is used AMD 6630M series. It has glitch on trasnparency, the glitch follow the cursor.

**Comment by sharad-paghadal** [comment]
Hey @rithondwima how did you installed the Monterey on mac mini 5,2? I’m facing error. Does your graphics support added or it’s lagging too much?

**Comment by sharad-paghadal** [comment]
In my case (same MacMini model), even after applying patch - graphics accelerator is not done. No graphics support.
