### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thecircleisround** [dortania/OpenCore-Legacy-Patcher#402]
### Machine Model

Macmini5,2

### Application Version

0.2.2 (Latest Release)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in), Other/Non-Applicable

### What is the Isssue?

After loading Post Install Volume Patches, Messages application will not open.  stderr outputs 

```
Invalid absolute dimension, must be > 0.0. NOTE: This will be a hard-assert soon, please update your call site. 
```

**Comment by Tiger-AC** [comment]
Same problem here (can't launch Messages app) on a mid-2011 27" iMac with HD6970 and a late-2009 21.5" iMac with GeForce9400 running Big Sur 11.5 and OCLP v023/v024.
It seems either the Post-Install Volume Patches have been changed, or the Big Sur 11.5 breaks the Post Install Volume Patches.
I am reverting back to Big Sur 11.4 to see if it makes any difference...

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/405
