### ISSUE TITLE
[Bug]: iMessage crashing and no possibility for Boom3D to get access to the Microphone in privacy settings 

### ISSUE THREAD

**Issue by Elvis-Budingensis** [dortania/OpenCore-Legacy-Patcher#403]
### Machine Model

MacBook8,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

First:

iMessage crashes after launch, no possibility to get it running. console shows:

Jul 24 09:10:45 […] com.apple.xpc.launchd[1]: Coalition Cache Hit: application<com.apple.MobileSMS(501)> [540]
Jul 24 09:10:46[…] com.apple.xpc.launchd[1] (application.com.apple.MobileSMS.1152921500311916037.1152921500311916042[1178]): Service exited with abnormal code: 1

Second: Boom3D needs to get access to the Microphone in the privacy settings. Boom3D wouldn't show up there, so there is nothing to add. It's only possible to run it with the Terminal.app via
tccutil reset Microphone
 /Applications/Boom\ 3D.app/Contents/MacOS/Boom\ 3D &!

**Comment by Ausdauersportler** [comment]
First:
Tried to logout from iCloud and login, again?
If the problem still exists create a new user account and try using this clean account. App errors are not really patcher issues, right?

Second: 
This has been documented already, just in case you never found it before, read [here](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-grant-special-permissions-to-apps-ie-camera-access-to-zoom):

**Comment by Elvis-Budingensis** [comment]
Thank you very much! I'll give it a try.

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/405
