### ISSUE TITLE
[Bug]: MacBook Air 4,2 (HD3000) not recognized any more

### ISSUE THREAD

**Issue by larsvonhier** [dortania/OpenCore-Legacy-Patcher#404]
### Machine Model

MacBookAir4,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

After updating the machine to i.e. macOS 11.5, the root-volume patching cannot be done any more with recent versions of OCLP, claiming an unidentified board number for applying the **HD3000** patch.
Previously the same machine worked fine with macOS 11.4 and patched HD3000 (OpenGL).
Went back to OCLP 0.1.4 and from there the root volume patch still works, macOS 11.5 works fine.
So imho the board number check misses some entry (or entries) for **MacBook 4,2** now.
_Interesting side note: After I applied the 0.1.3 patches, now OCLP 0.2.3 also has no complaints any more and can overwrite the old patches with the recent ones. Machine still works framebuffer/OpenGL-accelerated after that._

**Comment by larsvonhier** [comment]
Same issue with the GUI versions of recent OCLPs.

**Comment by khronokernel** [comment]
> So imho the board number check misses some entry (or entries) for MacBook 4,2 now.

```python
sandy_board_id = [
        "Mac-E43C1C25D4880AD6", # MacBookPro12,1
        "Mac-06F11F11946D27C5", # MacBookPro11,5
        "Mac-9F18E312C5C2BF0B", # MacBookAir7,1
        "Mac-937CB26E2E02BB01", # MacBookAir7,2
        "Mac-35C5E08120C7EEAF", # Macmini7,1
        "Mac-7BA5B2D9E42DDD94", # iMacPro1,1
    ]
 ```

It verifies the board IDs correctly of machines that have been spoofed, assuming user error by not booting OpenCore when patching root volume
