### ISSUE TITLE
macOS 11.5 Messages.app no longer runs on non-Metal Acceleration Patch set

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#405]
With macOS 11.5, Messages.app (and potentially other apps) will no longer open once the non-Metal Acceleration Patches are installed. Current issue is unknown however are still investigating.

### Work-Arounds

Currently downgrading to macOS 11.4 or older is the current recommended solution in the event you cannot upgrade your Mac with a Metal GPU.

Below is a direct link to macOS 11.4's InstallAssistant:

* [11.4 build 20F71 InstallAssistant](http://swcdn.apple.com/content/downloads/55/59/071-00696-A_4T69TQR1VO/9psvjmwyjlucyg708cqjeaiylrvb0xph94/InstallAssistant.pkg)

**Comment by Elvis-Budingensis** [comment]
Thank you. I'll have to leave it be, because downgrading is no option right now.

**Comment by thecircleisround** [comment]
Thanks. Currently downgrading

**Comment by MatsA** [comment]
Hi and thanks for a great job ! Unfortunately the Messages app still don't works with 11.5. Just did a fresh install, formated SSD, on a MacBook Air 4.2, (mid 2011, SSD, 4 Gb memory). Any suggestions ?

**Comment by khronokernel** [comment]
@MatsA Are you certain you used the latest commit (ie. 0.2.4)? If you are certain, I would recommend looking for help on the discord as we've been able to verify with multiple users the latest commit does resolve Catalyst app support. Might be something else broken on your machine than just the SkyLight.framework symlink we fixed

* [OpenCore Legacy Patcher Discord](https://discord.gg/rqdPgH8xSN)

**Comment by MatsA** [comment]
Thanks for your quick response, appreciated. Sorry for my ignorance….. but you are absolutely right, I'm still on 0.2.3... I took the latest release, according to the manual, and thought it was updated.....  Is there a simple way to get the latest 0.2.4 ?

**Comment by khronokernel** [comment]
@MatsA Grab the Nightly link from the repo's README, nightly refers to latest commit builds:

* [GUI Nightly](https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-gui/main/OpenCore-Patcher-GUI.app.zip)
* [TUI Nightly](https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip)

**Comment by MatsA** [comment]
Aha, tested and works like a charm !!
Awesome, thanks.

**Comment by Elvis-Budingensis** [comment]
Yeah, works like charm. Thanks!

**Comment by Elvis-Budingensis** [comment]
Since I upgraded to 11.5.1 (20G80) the problem with iMessage came back. I also upgraded the patcher to 0.2.5, but the problem remains, iMessage crashes.

**Comment by AMorgenthau** [comment]
Unfortunately I have the same problem with MacOS 11.5.2 Build 20G95. I already tried the nightliy build of the patcher to solve this problem, but it has no effect on the Message App.

**Comment by zipracinggg** [comment]
same problem. im using MacOS 11.5.2 on MBP 8,3. Message.app and twitter.app can't be opened. is there any fix yet without downgrading to 11.4? got no time to downgrading rn. thanks

**Comment by AMorgenthau** [comment]
I upgraded to Mac OS 11.6 and applied the nightly OCLP - that solved my problem.
