### ISSUE TITLE
Improvement, permanent PCIe 2.0 on MacPro 3.1

### ISSUE THREAD

**Issue by Ivantroniks** [dortania/OpenCore-Legacy-Patcher#406]
### Machine Model

MacPro3,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Hello with this driver implemented by Joevt loaded with OCLP unlocks PCIe 2.0 speed on port 1 and 2, including non-EFIMAC GPUs and NVMe's  (MacPro 3.1 only)...
I don't know if it will be possible to add it to OCLP...

Here is the driver link https://forums.macrumors.com/threads/opencore-and-the-2008-mac-pro-3-1.2287044/post-30087837

Attach the driver...
[joevtApps-FixPCIeLinkRate-v0.1.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6874914/joevtApps-FixPCIeLinkRate-v0.1.zip)

Before:

![Before 1](https://user-images.githubusercontent.com/76612048/126922380-1eab891b-2c06-4de8-8278-48c28f7f0732.png)

![Before 2](https://user-images.githubusercontent.com/76612048/126922385-830da255-5c2c-4e7a-9f3d-e742e4f62448.png)

After:

![Screen Shot 2021-07-25 at 7 29 43 p m](https://user-images.githubusercontent.com/76612048/126921569-7d34dca6-f265-4e4a-9d3b-0e2a95a2295f.png)

![Screen Shot 2021-07-25 at 7 32 51 p m](https://user-images.githubusercontent.com/76612048/126921559-579b0662-c765-4a48-9921-f3ffcf8724bd.png)

Thanks...

**Comment by tonybernardo** [comment]
What a great find! I knew my 3.1 felt slower somehow.

Is there a guide somewhere as to how I can install this driver? I've already got a very stable Opencore install of 11.5.1.

Thanks

**Comment by joevt** [comment]
My plan is to eventually split the pcitree functionality from the FixPCIeLinkRate functionality so that FixPCIeLinkRate will just do that one thing and be much smaller. FixPCIeLinkRate will remain as a driver. 

Then for the pcitree functionality, it will be a UEFI Shell command. It will use a text file converted from the pciids database so it can be updated.

Later, the pcie code may be used to do Thunderbolt stuff (find hidden Thunderbolt controllers, turn them on, enable PCIe tunnelling, allocate pcie resources). This will be a separate driver.

**Comment by marcpbailey** [comment]
+1

**Comment by khronokernel** [comment]
Apologies for the delayed response but looking further into this project we're not too comfortable integrating as-is into OCLP. Main concerns:

* project has no license
* project has no source

As-is we can't include without requesting written permission from the author. If someone's interested in contacting the author about publishing with source and a permissive license, there should be little issue integrating. Feel free to PR into OCLP
