### ISSUE TITLE
[Bug]: Suddenly there is no Video Output from my perfectly working machine

### ISSUE THREAD

**Issue by sheikhumar93** [dortania/OpenCore-Legacy-Patcher#408]
### Machine Model

MacBookPro9,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

This patcher has been working well with my machine since the past 2 months with the occasional problem with sleep/wake here and there. But yesterday I put my machine to sleep ( by closing the lid ) and since then I have not been able to boot into Big Sur. There is no video output, the Apple logo at the back does not light up and even the keyboard backlighting doesn't work. The Mac is working since I can hear the fan and machine heats up. Only thing I can do is to press R at startup and the machine goes into Big Sur Recovery which gives me an option to re-install Big Sur but then I wouldn't have the appropriate OC files in EFI so probably that wouldn't work as well.

I have tried using a Catalina bootable USB and pressed Option while booting but still nothing happens.

Any ideas what is going wrong over here? I am using the latest version of this patcher.

**Comment by khronokernel** [comment]
This seems to be a local machine issue and not one of our project's as the native boot picker is non-functional, would be considered out of scope. Would attempt to reset NVRAM and such per Apple's instructions, otherwise could go onto our discord and see if anyone there is familiar with the issue
