### ISSUE TITLE
[Bug]: Your model is not supported by this patcher for running unsupported OSes!

### ISSUE THREAD

**Issue by Grandboy46** [dortania/OpenCore-Legacy-Patcher#409]
### Machine Model

MacBook7,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 10.14, Mojave

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

![2A551D32-4B7A-4A38-9A93-FF25B063B340](https://user-images.githubusercontent.com/77637465/127285870-e96a6009-f6e9-4d9f-a545-a935f951e699.jpeg)

It says “Your model is not supported by this patcher” when it actually is supported

### Any Additional Information

My Macbook is a 2015 11 inch MacBook Air. I want to install macos Monterey on it.

**Comment by Ausdauersportler** [comment]
This is because your Mac will be officially supported by Apple with Monterey and does not need any special vehicle to install it. You should check (better: have checked in advance) the Apple website, tech docs and/or marketing material for this.
