### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by corn24** [dortania/OpenCore-Legacy-Patcher#413]
### Machine Model

MacBookPro10,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Since installing beta 4 bluetooth has stopped functioning (line through the icon). Was working with Monetary beta 3 and 0.2.3. Installed 0.2.4 today and issue is still current.

Thanks

**Comment by khronokernel** [comment]
Monterey bug, unrelated to patcher. If issue persists following more betas, we'll dedicate resources into the issue. Feel free to provide patchsets if you're able to resolve

**Comment by TheDave94** [comment]
Just use the BlueToolFixup.kext works fine for me on the same model
