### ISSUE TITLE
[Bug]: Macmini6,2 connected to HDMI TV does not have sound through HDMI

### ISSUE THREAD

**Issue by owenzhao** [dortania/OpenCore-Legacy-Patcher#414]
### Machine Model

Macmini6,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

The sound came out from the internal speaker instead of my TV. 

The issue is almost the same as [Macmini5,1 connected to HDMI TV does not have sound through HDMI](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/159). However, the latter is documented
"GPU Acceleration in Public Beta, see current issues" and mine is as "Everything is supported".

<img width="810" alt="Screen Shot 2021-07-31 at 10 15 32 AM" src="https://user-images.githubusercontent.com/2182896/127725748-96da8244-749a-4a8c-8c60-8f2c64daded0.png">

macOS Monterey 12.0 Beta(21A5294g)

**Comment by owenzhao** [comment]
Here is the info page of my GPU, does that mean it worked?

![Screen Shot 2021-07-31 at 10 17 30 AM](https://user-images.githubusercontent.com/2182896/127725806-be1dfe09-4988-44ac-bf05-c210d9d758f1.png)

**Comment by khronokernel** [comment]
Does this issue occur in Big Sur?

**Comment by owenzhao** [comment]
> Does this issue occur in Big Sur?

I have never installed Big Sur. macOS Catalina 10.15 was the last stable OS that support Mac mini 2012. I just upgraded 10.15 to 12 beta.

The HDMI worked in macOS 10.15 without OLP, as far as I know.

**Comment by Ausdauersportler** [comment]
As far as I can tell from experience and reading the docs OCLP is a tool supported on Big Sur and Monterey. Check the online docs.

**Comment by khronokernel** [comment]
Verify on a stable OS such as Big Sur, have no interest debugging a beta OS

**Comment by owenzhao** [comment]
> Verify on a stable OS such as Big Sur, have no interest debugging a beta OS

If a beta OS is not as intended, there should be no official feedback options for it.

**Comment by educovas** [comment]
He said that it's not an issue with the patcher, it could be from the beta OS. Also, doesn't look like you applied the post install patches. so it doesn't seem to be a bug with the OS as well

**Comment by khronokernel** [comment]
> If a beta OS is not as intended, there should be no official feedback options for it.

Why should we, the developers, have to debug a beta OS with a user who has provided not even the basic of information such as OS build, hardware specs, monitor used, etc. We have Monterey as an option for those who have Monterey specific issues that are not present in Big Sur
