### ISSUE TITLE
Intel HD 4000 Acceleration too slow

### ISSUE THREAD

**Issue by shines75** [dortania/OpenCore-Legacy-Patcher#415]
### Machine Model

MacBookPro9,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

First of all, congratulations for your wonderful patcher!! Unfortunately, though, on my MacBook Pro 15" mid-2012, running either on Big Sur or Monterey patched with OCLP, the Intel HD 4000 is always too slow, making it almost unusable. Could you kindly enhance the graphics acceleration for my mac, in a future version of OCLP? Thanks a lot!!

**Comment by Ausdauersportler** [comment]
1. HD4000 is fully supported on Big Sur
2. HD4000 has been patched back with Monterey for your system. Of course you would need to install those patched after the primary installation.

There is nothing we can do if you ignore the current state of development and the [documentation](https://dortania.github.io/OpenCore-Legacy-Patcher/) provided.

**Comment by shines75** [comment]
Yes, you’re right: I’ve just read the chapter regarding post installation of patches in your documentation. I’ll try later this afternoon, (I’m Italian), with the latest beta of Monterey. See ya

**Comment by shines75** [comment]
Btw, is discrete gpu accelleration (nvidia 650) supported for my mac?

**Comment by shines75** [comment]
Well, I've tried to install the latest version of Big Sur, 11.5.1, with the latest version of OCLP, 0.2.4: what a mess!! Gfx acceleration still sucks, and there seems now way to fix it, since if I try to patch the system volume, your patcher says me there's nothing to patch on my machine!! But that's not all: handoff not working at all and even some problems with iCloud!!! I've definitely to return to Patched-Sur...fuck you, guys!!!!

**Comment by shines75** [comment]
Oh, and I forgot: no audio too. Definitely, it’s a shame! Again, please fuck you, guys!!!

**Comment by khronokernel** [comment]
@-@

**Comment by khronokernel** [comment]
What a fun issue we have here
