### ISSUE TITLE
[Bug]: Archive Scan 0.2.4/OpenCore-Patcher-GUI.app.zip -> Suspicious threats

### ISSUE THREAD

**Issue by 0MiguelAnge0** [dortania/OpenCore-Legacy-Patcher#417]
### Machine Model

MacPro5,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Hi,

First of all, thanks for the dev community as I was stuck on Mojave with my MacPro5.1 which prevents me to run some applications.

I was preparing my set up to run the last GUI release 0.2.4 when I decided to scan the archive before running it. Unfortunately, it appears that several sites have detected some threads as reported below. Not sure if it is a false positive. But quantity found let me be a bit concerned.

Anyone having scanned the archive recently? Obviously I did a full stop until getting more hints...

Regards

MA

![Screen Shot 2021-08-04 at 16 26 02](https://user-images.githubusercontent.com/76682372/128149350-d16850ea-e335-4081-a423-120386c738e1.png)
Please clearly explain the issue

**Comment by Ausdauersportler** [comment]
This is an issue of your non working so called security software (a false positive) and not an issue of OCLP.

**Comment by 0MiguelAnge0** [comment]
> This is an issue of your non working so called security software (a false positive) and not an issue of OCLP.

Hi,

Thanks for your reply.

Find below the URL from where it has been issued. I used to make the check there and it is the first time I got so many warnings.

https://www.virustotal.com/gui/home/url

MA

**Comment by Ausdauersportler** [comment]
The vendors of such software cannot keep track of all tools written and published world wide. So even when having a valid Apple developer certificate in use (as OCLP has) you will get those error messages. Disable the software or add OCLP to a whitelist to avoid the error in future.

**Comment by khronokernel** [comment]
File an issue with the anti virus vendor, all source code is open for our project and we're even signed and notarized by Apple
