### ISSUE TITLE
[Bug]: MacbookPro8,3 - Error patching system volume

### ISSUE THREAD

**Issue by pjmr** [dortania/OpenCore-Legacy-Patcher#418]
### Machine Model

MacBookPro8,3

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Error patching system volume

MacBook Pro with faulty dedicatedGPU disabled using dosdude1 [method](https://forums.macrumors.com/threads/permanently-disable-2011-15-17-macbook-pro-dedicated-gpu-gmux-ic-bypass.2134019/).

!Screenshot 1(https://user-images.githubusercontent.com/9213629/128178091-d044b2f6-56a6-4e5c-86e0-4ed4ecd346f4.png)
!Screenshot 2(https://user-images.githubusercontent.com/9213629/128178099-e755591b-e880-4d5e-82fc-690cba0bc7df.png)

### Any Additional Information

Loading...
- Rerouting payloads location
- Set System Volume patching
- Starting Patch Process
- Determinging Required Patch set for Darwin 20
- Found IGPU: 8086:126
The following patches will be applied:
- Add Legacy Intel Sandy Bridge Graphics Patch
Continuing root patching
- Continuing with Patching
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Apple binaries missing
- Attempting download from following link:
https://github.com/dortania/PatcherSupportPkg/releases/download/0.0.15/11-Big-Sur.zip
- Downloading package
- 4.0MB Downloaded
- Downloading package
- 8.0MB Downloaded
- Downloading package
- 12.0MB Downloaded
- Downloading package
- 16.0MB Downloaded
- Downloading package
- 20.0MB Downloaded
- Downloading package
- 24.0MB Downloaded
- Downloading package
- 28.0MB Downloaded
- Downloading package
- 32.0MB Downloaded
- Downloading package
- 36.0MB Downloaded
- Downloading package
- 40.0MB Downloaded
- Downloading package
- 44.0MB Downloaded
- Downloading package
- 48.0MB Downloaded
- Downloading package
- 52.0MB Downloaded
- Downloading package
- 56.0MB Downloaded
- Downloading package
- 60.0MB Downloaded
- Downloading package
- 64.0MB Downloaded
- Downloading package
- 68.0MB Downloaded
- Downloading package
- 72.0MB Downloaded
- Downloading package
- 76.0MB Downloaded
- Downloading package
- 80.0MB Downloaded
- Downloading package
- 84.0MB Downloaded
- Downloading package
- 88.0MB Downloaded
- Downloading package
- 89.86284160614014MB Downloaded
- Checksum: 51cde71d24484296fe4ca8f70923bda3ba2fea1abf7e8b2ce557acd9ca01a85d
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/tmp/_MEIWqXxVZ/payloads
- Found Root Volume at: disk1s5
- Root Volume is already mounted
- Running patches for MacBookPro8,3
- Installing legacy Sandy Bridge Patches
- Detected supported OS, installing Acceleration Patches
- Installing Sandy Bridge Acceleration Kext patches for Big Sur
- Couldn't find AMDRadeonX4000.kext, skipping
- Couldn't find AMDRadeonX4000HWServices.kext, skipping
- Couldn't find AMDRadeonX5000.kext, skipping
- Couldn't find AMDRadeonX5000HWServices.kext, skipping
- Couldn't find AMDRadeonX6000.kext, skipping
- Couldn't find AMDRadeonX6000Framebuffer.kext, skipping
- Couldn't find AMDRadeonX6000HWServices.kext, skipping
- Couldn't find AppleIntelBDWGraphics.kext, skipping
- Couldn't find AppleIntelBDWGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelCFLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelHD4000Graphics.kext, skipping
- Couldn't find AppleIntelHD5000Graphics.kext, skipping
- Couldn't find AppleIntelICLGraphics.kext, skipping
- Couldn't find AppleIntelICLLPGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelKBLGraphics.kext, skipping
- Couldn't find AppleIntelKBLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelSKLGraphics.kext, skipping
- Couldn't find AppleIntelSKLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelFramebufferAzul.kext, skipping
- Couldn't find AppleIntelFramebufferCapri.kext, skipping
- Couldn't find AppleParavirtGPU.kext, skipping
- Couldn't find GeForce.kext, skipping
- Deleting IOAcceleratorFamily2.kext
- Couldn't find IOGPUFamily.kext, skipping
- Installing General Acceleration Kext patches for Big Sur
- Adding IOAcceleratorFamily2.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000Graphics.kext
- Adding AppleIntelHD3000Graphics.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsGA.plugin
- Adding AppleIntelHD3000GraphicsGA.plugin
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsGLDriver.bundle
- Adding AppleIntelHD3000GraphicsGLDriver.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsVADriver.bundle
- Adding AppleIntelHD3000GraphicsVADriver.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelSNBGraphicsFB.kext
- Adding AppleIntelSNBGraphicsFB.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelSNBVA.bundle
- Adding AppleIntelSNBVA.bundle
- Merging general legacy Frameworks
Process failed with exit code 23
Please file an issue on our Github
Traceback (most recent call last):
  File "OCLP-CLI.command", line 259, in <module>
  File "OCLP-CLI.command", line 160, in __init__
  File "OCLP-CLI.command", line 204, in patch_vol
  File "SysPatch.py", line 610, in start_patch
  File "SysPatch.py", line 67, in find_mount_root_vol
  File "SysPatch.py", line 389, in patch_root_vol
  File "SysPatch.py", line 303, in gpu_accel_legacy_extended
  File "Utilities.py", line 28, in process_status
Exception: Process result: 
.d....og. ./
.d....og. CoreDisplay.framework/
.L....og. CoreDisplay.framework/CoreDisplay -> Versions/Current/CoreDisplay
.d....og. CoreDisplay.framework/Versions/
.d....og. CoreDisplay.framework/Versions/A/
.f....og. CoreDisplay.framework/Versions/A/CoreDisplay
.f....og. CoreDisplay.framework/Versions/A/CoreDisplayOld.dylib
.d....og. IOSurface.framework/
.L....og. IOSurface.framework/IOSurface -> Versions/Current/IOSurface
.d....og. IOSurface.framework/Versions/
.d....og. IOSurface.framework/Versions/A/
.f....og. IOSurface.framework/Versions/A/IOSurface
.f....og. IOSurface.framework/Versions/A/IOSurfaceOld.dylib
.f....og. IOSurface.framework/Versions/A/IOSurfaceSymbolsDiff.txt
.f....og. IOSurface.framework/Versions/A/IOSurfaceSymbolsDiffReverse.txt
.f....og. IOSurface.framework/Versions/A/IOSurfaceSymbolsNew.txt
.f....og. IOSurface.framework/Versions/A/IOSurfaceSymbolsOld.txt
.f....og. IOSurface.framework/Versions/A/IOSurfaceWrapper.m
.d....og. OpenGL.framework/
rsync: delete_file: rmdir "/System/Volumes/Update/mnt1/System/Library/Frameworks/OpenGL.framework/Libraries" failed: Directory not empty (66)
.L....og. OpenGL.framework/OpenGL -> Versions/Current/OpenGL
rsync: delete_file: rmdir "/System/Volumes/Update/mnt1/System/Library/Frameworks/OpenGL.framework/Resources" failed: Directory not empty (66)
.d....og. OpenGL.framework/Versions/
rsync: delete_file: rmdir "/System/Volumes/Update/mnt1/System/Library/Frameworks/OpenGL.framework/Versions/Current" failed: Directory not empty (66)
.d....og. OpenGL.framework/Versions/A/
.f....og. OpenGL.framework/Versions/A/OpenGL
.d....og. OpenGL.framework/Versions/A/Libraries/
.f....og. OpenGL.framework/Versions/A/Libraries/CVMCompiler
.f....og. OpenGL.framework/Versions/A/Libraries/CVMServer
.f....og. OpenGL.framework/Versions/A/Libraries/DumpGPURestart
.f....og. OpenGL.framework/Versions/A/Libraries/ReportGPURestart
.f....og. OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libGL.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libGLU.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libGLVMPlugin.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/libLLVMContainer.dylib
.d....og. OpenGL.framework/Versions/A/Libraries/3425AMD/
.f....og. OpenGL.framework/Versions/A/Libraries/3425AMD/CVMCompiler
.f....og. OpenGL.framework/Versions/A/Libraries/3425AMD/libCoreVMClient.mono.dylib
.f....og. OpenGL.framework/Versions/A/Libraries/3425AMD/libLLVMContainer.dylib
.d....og. OpenGL.framework/Versions/A/Libraries/3600/
.f....og. OpenGL.framework/Versions/A/Libraries/3600/CVMCompiler
.f....og. OpenGL.framework/Versions/A/Libraries/3600/libCoreVMClient.mono.dylib
.d....og. OpenGL.framework/Versions/A/Resources/
.f....og. OpenGL.framework/Versions/A/Resources/CVMSPlugin.exp
.f....og. OpenGL.framework/Versions/A/Resources/CVMSPluginAll.exp
.f....og. OpenGL.framework/Versions/A/Resources/CVMSPluginNoExec.exp
.f....og. OpenGL.framework/Versions/A/Resources/GLByteCodes.i386.bc
.f....og. OpenGL.framework/Versions/A/Resources/GLByteCodes.x86_64.bc
.f....og. OpenGL.framework/Versions/A/Resources/Info.plist
.f....og. OpenGL.framework/Versions/A/Resources/cvmsConfig.plist
.f....og. OpenGL.framework/Versions/A/Resources/version.plist
.d....og. OpenGL.framework/Versions/A/Resources/BridgeSupport/
.f....og. OpenGL.framework/Versions/A/Resources/BridgeSupport/OpenGL.bridgesupport
.d....og. OpenGL.framework/Versions/A/Resources/GLEngine.bundle/
.f....og. OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
.d....og. OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/
.f....og. OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
.d....og. OpenGL.framework/Versions/A/_CodeSignature/
.f....og. OpenGL.framework/Versions/A/_CodeSignature/CodeResources
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]

[1693] Failed to execute script 'OCLP-CLI' due to unhandled exception!

**Comment by the-ez18** [comment]
same here with version 0.2.4 on an iMac11,1
