### ISSUE TITLE
[Bug]:  Graphics issues and no brightness control Macbook Pro 8.1

### ISSUE THREAD

**Issue by Mr-La-Fly** [dortania/OpenCore-Legacy-Patcher#419]
### Machine Model

MacBookPro8,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hello 
I seem to be having some graphics issues
I installed Big Sur 11.5.1 on my mcp 8.1 and i already installed the legacy graphics drivers 
The brightness adjustment is not working and there is some graphical glitching in the control centre and through out the os
Unfortunately the glitches in the os don't show up on the screenshots but to describe it simply i get black squares around the cursor and it is most noticeable on safari start page
![Screenshot 2021-08-04 at 5 11 06 PM](https://user-images.githubusercontent.com/88440483/128188189-119442c4-7d90-4fc4-88b8-8f956e717583.png)

**Comment by khronokernel** [comment]
Our acceleration patch sets should still be in tact with 11.5.1, we have had multiple successful reports of Sandy Bridge graphics working as expected. The issues you listed are likely already described here:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

With regards to brightness control, recommend asking on either our discord or forums. If you find the acceleration patches are in fact broken, feel free to comment and we'll reopen the issue
