### ISSUE TITLE
Suggestion: Bump BIOSVersion to prevent bricking

### ISSUE THREAD

**Issue by stonegray** [dortania/Opencore-Legacy-Patcher#42]
@Bustycat found some [interesting discussion](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/page-325?post=29425353#post-29425353) about bumping the BIOSVersion to prevent firmware updates.  If it works, this seems like a reasonable way to stop the bricking issues if other solutions aren't working.

> Saw a [workaround](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29425353) on Mac Rumors as injecting BIOSVersion to 999.0.0.0.0. Would the patcher developers test further and consider it?
> _Originally posted by @Bustycat in https://github.com/dortania/Opencore-Legacy-Patcher/issues/15#issuecomment-749916544_

While the instructions posted in that thread don't work, the idea seems sound. I went ahead and tried it on my MacBookPro10,1 (which is affected according to #15). The updated version shows up both in the EFI shell (`smbiosview -t 0`) and within macOS 11.0.1, and doesn't appear to cause any issues.

<img width="400" alt="Screen Shot 2021-01-10 at 4 23 44 PM" src="https://user-images.githubusercontent.com/7140974/104135809-3cfb4c80-5360-11eb-9a63-425e48715c79.png">

I had some difficulty finding the correct way to set the version using `config.plist`, and after chasing through the OpenCore source for longer than I care to admit I ended up mounting the EFI partition and hand-editing the `OpenCore.efi` file to make the change.

I want to understand Apple's update process a little more before I pull the trigger and do an OTA update on my machine, but this seems like a promising fix to the bricking.

**Comment by stonegray** [comment]
Update: This is looking good to me, and should be effective at preventing updates both from within the running system and from EFI.

OTA update from 11.0.1 to 11.1 runs perfectly, no hanging.

**Comment by khronokernel** [comment]
https://github.com/acidanthera/OpenCorePkg/pull/179

I added a new quirk to OpenCore for this use case, we've been also able to verify it works on our end. I expect to update the patcher itself sometime this week with 0.6.6
