### ISSUE TITLE
Implement automatic root patching after OS updates

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#421]
With OpenCore Legacy patcher, we currently require users to manually repatch their machine after an OS update. To streamline the process, we should implement a LaunchDaemon that will automatically patch once an OS update finishes.

Requirements:

* [ ] Implement /Library/Dortania to store OCLP-CLI and additional files
* [ ] Implement off-line root patching within OCLP-CLI
* [ ] Implement a new CLI argument that will only patch when root volume has a signed seal
* [ ] Implement a LaunchDaemon to run OCLP-CLI and block user login until process completes

**Comment by traviswparker** [comment]
Is there a reason to put the patches in /System/Library/vs. /Library/? You can add kexts to /Library/Extensions, they just need to be approved in Security Preferences. Or can you not add Apple-signed stuff there? If you can make them work from /Library/ you don't need to modify the SSV snapshot.

**Comment by khronokernel** [comment]
> Is there a reason to put the patches in /System/Library/ vs. /Library/?

@traviswparker The graphics stack in macOS is not solely within kernel space but also has a userspace portion, the `.bundle` files. Unfortunately macOS hard codes where these userspace binaries are present and thus must always be installed in `/System/Library/Extensions`

So while virtually any kernel extensions can be installed in either `/System/Library/Extensions` or `/Library/Extensions`(assuming it's not required for early booting), the .bundle files must be under `/System/Library/Extensions`. There have been research into using `/Library/GPUBundles` however seems Apple deprecated usage of this some time ago. This is most evident in how Nvidia was forced into using `/System/Library/Extensions` for their own graphics stack with macOS High Sierra

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/pull/986
