### ISSUE TITLE
Keyboard ilumation not working[Bug][Catalina]

### ISSUE THREAD

**Issue by richiegongora** [dortania/OpenCore-Legacy-Patcher#422]
### Machine Model

MacBookPro8,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

The keyboard retroilumination does not work, even if you apply the patch again.

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html
