### ISSUE TITLE
[Bug]: MacBookAir4,1 

### ISSUE THREAD

**Issue by s4miii** [dortania/OpenCore-Legacy-Patcher#423]
### Machine Model

MacBookAir4,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

first of all thank you so much because of your great job
in my MacBook Air 2011, I found these bugs

1) in dark mode, when cursor is moving (some apps like safari or system settings) bunch of gray boxes will moving with cursor

2)as you can see, the icons of display and sound + progress bars not showing well
![Screen Shot 2021-08-02 at 11 32 13](https://user-images.githubusercontent.com/29096708/128491892-eda0c5c3-209d-49ab-b06d-6bebe0a65ddc.png)

3)Sometimes, icons are not showing in system settings

4)Three buttons, not showing in the corner of preview window (close, minimize and maximize)
![Screen Shot 2021-08-06 at 14 17 52](https://user-images.githubusercontent.com/29096708/128492314-a4d6b43d-8dce-4edf-9ad7-58fd87314df1.png)

5)most of the time wireless icon and flag icon (changing language) are overlap.

6)some applications like photoshop, after opening not showing till you drag the edge of their windows

7)keyboard's lit not working without LabTick

8)sometimes text editor crashing without any reason

9)in airdrop mode icons not showing well
![Screen Shot 2021-08-06 at 15 14 10](https://user-images.githubusercontent.com/29096708/128498959-6f8d1f45-7d1e-4594-a184-103a4d0cd96e.png)

10)thumbnail of photos not working well, sometimes, it just showing two or three thumbnails.
![Screen Shot 2021-08-06 at 15 15 39](https://user-images.githubusercontent.com/29096708/128499246-620d8516-ac01-48ef-b953-706f430bece7.png)

thanx in advance

**Comment by satmandu** [comment]
MacBookAir4,2 user here, using 0.2.4 to run Big Sur 11.5.1.

I also notice these problems, but they are somewhat mitigated by using dark mode.

Also, Google Maps in Safari crashes, as does the Apple Maps app when searching for an address.

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
