### ISSUE TITLE
[Bug]: Sometime PCI pause at SDXC even PRAM reseted 

### ISSUE THREAD

**Issue by CuchoM** [dortania/OpenCore-Legacy-Patcher#424]
### Machine Model

MacBookPro9,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

I've run an apple device test and did not find any hardware problem, but using OCLP 0.25 with standard settings I got an intermittent problem pausing on PCI at SDXC, there is no card inside de reader but it stops. I don't know how it happens because I've tried single-user boot and reboot and it worked but when happens it's kept in this pause for hours.
Is there any possible solution or it is related to my machine?
Booting from Catalina works normal and fast, I have Catalina, BS 11.5.1, and Monterey on the same SSD. and also WIN11 
![IMG_1688 copy](https://user-images.githubusercontent.com/72659668/128505722-11123468-a7e0-4f52-94f6-cdcca77e52e2.jpg)

**Comment by khronokernel** [comment]
Cannot replicate locally or with our testers, likely local issue on your end. Feel free to continue researching and submit patch sets
