### ISSUE TITLE
[RFE]: MacBook Pro 2013 to 2015 15": sudden shutdown AppleThunderboltNHI.kext, that could be solved with the OCLP: 

### ISSUE THREAD

**Issue by k0017** [dortania/OpenCore-Legacy-Patcher#426]
### Machine Model

MacBookPro11,2

### Application Version

0.2.3 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey and all earlier Versions

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Thousands of MacBook Pro 2013 to 2015 15" have defective Chips, that leads to sudden shutdowns short after login. If the kext AppleThunderboltNHI.kext in System/Library/Extensions is not loaded, the machines all run fine. 

But due to the new MacOS, it is really hard to delete or rename the kext.

https://outluch.wixsite.com/rmbp-crash
https://forums.macrumors.com/threads/big-sur-and-applethunderboltnhi-kext.2267818/
https://gh4ag.github.io/assets/osx/Big_Sur_Shutdowns/big_sur_shutdowns.html

It would be a great opportunity, If someone could develop a parameter in the patcher settings In OCLP to prevent the OS to load the kext.
Thanks to all for your great work!

Ulli Hesse (Germany)

> The solution how to deinstall the extension has been already described here for Catalina and Big Sur and within the thread you cited yourself:
> 
> https://apple.stackexchange.com/questions/372684/how-to-delete-kexts-in-catalina
> 
> This is surely not an OCLP bug, it is a hardware failure of your system and you are asking for a software enhancement of OCLP (I would call it RFE).

You are right, I try to change the label

**Comment by Ausdauersportler** [comment]
The solution has been already describe here for Catalina and Big Sur:

https://apple.stackexchange.com/questions/372684/how-to-delete-kexts-in-catalina

And this is surely not an OCLP bug, it is a hardware failure of your system and you are seeking for a software enhancement of OCLP (I would call it RFE).

**Comment by k0017** [comment]
@Ausdauersportler: I don´t see, how the lable can be changed, I changed the Label to RFE in the header

**Comment by Ausdauersportler** [comment]
Let's wait for the Canadians to chime in. I am not the real expert, but may be it will be somehow possible to disable the defective chip or at least the thunderbolt ports - which would stop macOS from loading installed extensions. This would be nice. But for now you can (easily) delete the kernel extension yourself following the guides.

**Comment by k0017** [comment]
> 
> 
> Let's wait for the Canadians to chime in. I am not the real expert, but may be it will be somehow possible to disable the defective chip or at least the thunderbolt ports - which would stop macOS from loading installed extensions. This would be nice. But for now you can (easily) delete the kernel extension yourself following the guides.

For me and many others, it is not easy and it must be done für every macOS Update. So it really makes sense to integrate this in OCLP

**Comment by khronokernel** [comment]
> Let's wait for the Canadians to chime in

Haha, well I'm a Ukrainian stuck in Canada ;p

With regards to implementing a Thunderbolt disabler into the patcher, I have little issue so long as it's not overly complicated. We have quite a few methods within OCLP for blocking kexts though depends on the personality of the kext (ie. persistent, hot loadable, etc).

I have a MacBookPro9,2 somewhere on the shelf so can test some methods to disable Thunderbolt. It is a gen 1 controller though gen 1 and 2 use the same kext. Will report back in a bit with my findings

**Comment by k0017** [comment]
> 
> I have a MacBookPro9,2 somewhere on the shelf so can test some methods to disable Thunderbolt. It is a gen 1 controller though gen 1 and 2 use the same kext. Will report back in a bit with my findings

iIt would be my pleasure to test it! I am looking forward to it!😀

**Comment by khronokernel** [comment]
Please verify whether the below build works:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/3449891595/artifacts/81879534

Currently it disables the Thunderbolt controller on all MacBookPro11,x machines (2013-2014), if you know of any other models affected do report them and I can integrate into the patcher. If patcher works for you, I can add this as a configurable option in the patcher

**Comment by k0017** [comment]
Hello together,

Yeah, great work, it works without any problem! 

I use now Monterey Beta4 with my MacBook Pro 11,2 without any sudden shutdown, which would occur many times without the Patcher.
This is a great enhancement so many user don’t have to put their MacBooks to the trash.

Please put it as configurable Option in the patcher.

This option should be advertised, so that users who need this function can find it easy.
You could help a lot of users!

Thank you very much!

Greetings!
Ulli Hesse

**Comment by k0017** [comment]
Btw. The patcher has to be installed via another Mac to an USB Stick, because the Mac with the faulty chips doesn’t run long enough to do it. The Option must be available independent of the model the patcher is running on. Greetings Ulli Hesse!

**Comment by Ausdauersportler** [comment]
You do not have a working fall back solution on an external disk? What happens if your main installation becomes corrupted?

**Comment by k0017** [comment]
I do have it, but I thought of other Users, who do not have it, because they don’t know how to do.

**Comment by k0017** [comment]
BTW: The AppleThunderboltNHI.kext is not loaded, as expected.
