### ISSUE TITLE
[Bug]: Legacy GPU Accel Issues: slightly transparent box surrounding mouse in Safari New Window.

### ISSUE THREAD

**Issue by satmandu** [dortania/OpenCore-Legacy-Patcher#427]
### Machine Model

MacBookAir4,2

### Application Version

0.2.4 (Latest Build)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Big Sur is set to Dark Mode, which fixes the issue with buttons not appearing.
When opening a new window in Safari, a slightly transparent box follows the mouse around, leaving a trail.

I of course assume that this is related to the mostly working graphics acceleration patches for older machines.

@ASentientBot, if you want more testers for Legacy GPU patch builds on these Sandy Bridge machines...

(Also, https://maps.google.com in Safari and the Apple Maps app both don't work, which I presume are also related to Legacy GPU on this machine.)

**Comment by khronokernel** [comment]
With regards to the interface elements leaving a trail of black boxes, this is a known issue on Sandy Bridge Mac minis however looks to be affecting some MacBook users (however not all)
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

Google Maps and Apple maps both should work on legacy GPUs, if a bit sluggish, so will update the issue to reflect Sandy Bridge concerns
