### ISSUE TITLE
[Bug]: Boot options are not displayed

### ISSUE THREAD

**Issue by AntonioJOrtiz64** [dortania/OpenCore-Legacy-Patcher#429]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

First of all I want to express my gratitude for such a wonderful job.

With version 0.2.4, both GUI and TUI installed OpenCore on the USB, when restarting the machine again by pressing the option key, the machine continues its boot process arriving directly at the login, at that point the imac does not recognize the keyboard and mouse.

To get the iMac to recognize the mouse and keyboard again I must reboot the machine in recovery mode

I tested this version on a Macbook Pro 8.1 and the boot is normal

Tnaks in advance!!!!

**Comment by khronokernel** [comment]
Cannot replicate locally or with testers, feel free to research further and submit patch sets
