### ISSUE TITLE
Late 2012 (13,2) and late 2013 (14,2) both iMacs dead!!

### ISSUE THREAD

**Issue by mathieulp** [dortania/Opencore-Legacy-Patcher#43]
Hi everyone

I bricked my two iMacs installing BigSur 11.1 Update! It worked well with first release of BigSur, then troubles happened after updating process. I bricked the first one, though it was an hardware issue, tried the second one and did twice the same mistake :-(((

CHIME SOUND, BLACK SCREEN AND NOTHING ELSE...If only I new a simple software could damage my iMacs this way I wouldn't have used this patch!

I've already tried all the standard procedures (pram, power, nvram, etc.) and nothing works.
Please tell me I won't have to open the machine to fix it ?!! Because I won't be able to...

I read about corrupted EFI Rom and it might be my case...I can't believe I broke two iMacs in less than one hour, I feel so stupid now!

Will Apple Genius fix it? Will they charge for it? 

Best regards from Switzerland 
Mateo

**Comment by bayard1965** [comment]
Hi,
Did you backup your bootroms?

Did you read this:
"DO NOT USE, RISKS OF BRICKING YOUR MAC
Currently this patcher implementation can apply a firmware update that breaks your machine. To avoid this, we highly recommend users do not use this patcher until we've resolved this.

Ivy Bridge and Haswell Notes
Currently in Big Sur 11.0.1 and 11.1, there are partial firmware brickings happening during the install stage. The exact issue depends on the CPU model generation:

Ivy Bridge:

Simply power cycling the machine will resolve this issue
Laptops will need to unplug the battery for a bit
To avoid this issue outright, simply shutdown the machine after Big Sur has installed macOS instread of having the installer auto reboot
Haswell:

Power cycling may work however some iMac14,x users have reported needing a firmware reflash
Patcher currently has removed support for these machines till macOS 11.2's release to avoid any unnecessary headaches for users"

**Comment by mathieulp** [comment]
No i didn’t backup the bootroms (didn’t even know it was possible, and if I had how could I restore them?)
No I didn't read the disclaimer...sush a shame I know...

Do powercycling means plugging of the power cable? If so I also tried this with no luck...

**Comment by Ausdauersportler** [comment]
Okay, next summer I pay you a visit on my next MTB over the Alps tour and fix this :-)

There are [guides](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29418234) out where to find a clean BIOS and how to make this fitting for your iMac(s). All this can be done remotely. Only the flashing will need to open both systems and a CH341A clip programmer and a laptop.

**Comment by bayard1965** [comment]
"Do powercycling means plugging of the power cable?"
Not only.
Try SMC reset, with no success insurance.
Unplug power cable.
Wait at least for 15 seconds.
Plug power cable.
Wait at least for 10 seconds.
Press Power button.

**Comment by mathieulp** [comment]
> Hi,
> Did you backup your bootroms?
> 
> Did you read this:
> "DO NOT USE, RISKS OF BRICKING YOUR MAC
> Currently this patcher implementation can apply a firmware update that breaks your machine. To avoid this, we highly recommend users do not use this patcher until we've resolved this.
> 
> Ivy Bridge and Haswell Notes
> Currently in Big Sur 11.0.1 and 11.1, there are partial firmware brickings happening during the install stage. The exact issue depends on the CPU model generation:
> 
> Ivy Bridge:
> 
> Simply power cycling the machine will resolve this issue
> Laptops will need to unplug the battery for a bit
> To avoid this issue outright, simply shutdown the machine after Big Sur has installed macOS instread of having the installer auto reboot
> Haswell:
> 
> Power cycling may work however some iMac14,x users have reported needing a firmware reflash
> Patcher currently has removed support for these machines till macOS 11.2's release to avoid any unnecessary headaches for users"

I tried powercycling my late 2012 iMac but it didn’t solve the problem despite the fact that it’s an ivy bridge cpu, any idea?

**Comment by mathieulp** [comment]
> Okay, next summer I pay you a visit on my next MTB over the Alps tour and fix this :-)
> 
> There are [guides](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29418234) out where to find a clean BIOS and how to make this fitting for your iMac(s). All this can be done remotely. Only the flashing will need to open both systems and a CH341A clip programmer and a laptop.

Come on guys I’m not an engineer, I will never be able to open this glued iMac screen without damaging it...and I won’t even talk about the code and all the geek and electronics stuff

soooooo I’m dead if I understood good...

again, do you think Apple Genius Bar at the Apple store will accept to repair?
