### ISSUE TITLE
Installation without bootscren

### ISSUE THREAD

**Issue by fabriziovignali** [dortania/OpenCore-Legacy-Patcher#431]
### Machine Model

MacPro3,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

Hi everyone,
I have a fleshed rx580, is it possible to install or do I need to buy another gpu?
thank you

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html#booting-with-a-non-flashed-gpu

Use forums for troubleshooting

**Comment by fabriziovignali** [comment]
Thanks

Il gio 12 ago 2021, 06:18 Mykola Grymalyuk ***@***.***> ha
scritto:
