### ISSUE TITLE
[Help]: How to disable the AMD gpu on Big Sur using OCLP

### ISSUE THREAD

**Issue by vtecdohc** [dortania/OpenCore-Legacy-Patcher#433]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

I used to used dosdude's patch normally on Mojave but now on Big Sur I didn't had success using the patch, so Im using the wegnoegpu boot flag, is there any other solution? currently I have no brightness control neither keyboard backlight. is there any light?

**Comment by khronokernel** [comment]
In RecoveryOS:
```
nvram FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-power-prefs=%01%00%00%00
```

https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-switch-gpus-on-2011-15-and-17-macbook-pros

Use forums for troubleshooting
