### ISSUE TITLE
[Bug]: Remote Desktop blank when connecting to certain machines running OCLP

### ISSUE THREAD

**Issue by TheWojtek** [dortania/OpenCore-Legacy-Patcher#434]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Isssue?

Running Apple Remote Desktop to a OCLP-booted and subsequently patched remote machine results in blank RD window on controlling machine once connected to Big Sur 11.5.1 on an iMac 12,1 (21.5" mid-2011).
The mouse movements and clicks are correctly transmitted to the remote machine, therefore it is possible to control it using RD if the machine is physically available, however there is no screen transmitted.

I suspect the video drivers patched to obtain HW acceleration on this iMac to be the culprit, as I use the same OCLP release on a Mac Pro 5,1 with a Metal GPU and do not experience similar issue (remote desktop is visible in ARD).
I run the latest Remote Desktop 3.9.4 from Mac App Store.
<img width="1481" alt="Screen Shot 2021-08-12 at 11 28 20 AM" src="https://user-images.githubusercontent.com/10579189/129173939-0799ceeb-4429-4521-8b98-47ba0696b615.png">

**Comment by khronokernel** [comment]
Known issue on TeraScale 2 Macs, specifically affecting iMacs and Mac minis (MacBook Pros and Mac Pros are unaffected in most cases, as cannot replicate the issue on my MacPro3,1 with HD 5770). You can try downgrading to macOS 11.2.3 where the graphics stack was a bit more stable however unknown when fix may be available:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

You may also want to mess with CoreMediaIO settings such as this one:
```sh
defaults write com.apple.cmio CMIO_Unit_Input_ASC.DoNotUseOpenCL -bool true
```
