### ISSUE TITLE
[Feature]: Store OCLP settings in separate folder

### ISSUE THREAD

**Issue by volsk** [dortania/OpenCore-Legacy-Patcher#436]
### Machine Model

MacPro5,1

### Application Version

Latest Build (nightly)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I regularly upgrade OCLP. I do have some settings I use every time, like disabling SIP. And disabling ShowPicker on a different machine.

It would be great if these settings would be stored outside of the Git folder. In for example `~/.config/oclp`.

**Comment by mat1696** [comment]
I agree, it would be nice.

**Comment by Ausdauersportler** [comment]
You can as of today use the CLI and write a custom script for each of your systems. And I would call it an RFE (request for enhancement) and not a bug.

**Comment by volsk** [comment]
> You can as of today use the CLI and write a custom script for each of your systems. 
I’ll check that functionality. 
> And I would call it an RFE (request for enhancement) and not a bug.
I agree. But it seems I couldn’t change the label.

**Comment by Ribero** [comment]
It would be nice. 
It would be also a nice way to manage a configuration specific to a targeted os. 
I mean : today oclp does not let you choose for which os you want to build the Efi. By default it use settings for the latest version (Monterey) even if you want to install it for big sur. The results is that the default settings for monterey remove features for big sur (ex : FileVault). 
With this new feature it will allow user to save settings and update oclp without taking the risk of having important settings downgraded.

**Comment by khronokernel** [comment]
As Ausdauersportler stated, use the CLI and create your own solutions. With how OCLP-CLI hooks into the GUI, it's currently not possible to load a config

And @Ribero, I have already explained to you why it's fugly to set a specific OS to support
