### ISSUE TITLE
[Bug]: No Sidecar on Big Sur (11.5.2)

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#437]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Sidecar settings don't appear on my 11,3 MBP in Big Sur, but they appear and work on my 9,2 MBP, and strangely enough on my secondary 11,3 that's on Monterey, the Sidecar settings appear and work fine.

**Comment by khronokernel** [comment]
Make sure you're booting through OpenCore when trying to enable Sidecar. You can check in terminal if the kext responsible for Sidecar unlocking is available:

```sh
kextstat | grep "FeatureUnlock"
```

If not present, likely not booting through OpenCore. As all other machines are working fine even including your own, seems to be a local issue and not one of the patcher's

**Comment by Piipperi** [comment]
`Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
`

I am booting via OpenCore thought as macOS Monterey Beta is being offered (since I have enrolled in the beta program), and I have made sure to boot via OC.
