### ISSUE TITLE
The patch seems to break something

### ISSUE THREAD

**Issue by mjs520** [dortania/OpenCore-Legacy-Patcher#438]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

The system destroys some things, causing the latest system to download the full package instead of the incremental package every time it is updated online

**Comment by khronokernel** [comment]
What are the hardware specs? And is this a hackintosh?

**Comment by mjs520** [comment]
> 硬件规格是什么？这是一个hackintosh吗？
This has nothing to do with the hardware system. I am not the only one who has encountered such problems. It should be the defect of the patch itself. I hope it can be repaired.


> What are the hardware specs? And is this a hackintosh?

This has nothing to do with the hardware system. I am not the only one who has encountered such problems. It should be the defect of the patch itself. I hope it can be repaired.

**Comment by khronokernel** [comment]
Well how am I supposed to fix this if I don't know what the hardware is? A MacBookPro11,1 has no root patches so why would it report a broken seal? Better understanding of hardware is needed

**Comment by mjs520** [comment]
> > 硬件规格是什么？这是一个hackintosh吗？
> > This has nothing to do with the hardware system. I am not the only one who has encountered such problems. It should be the defect of the patch itself. I hope it can be repaired.
> 
> > What are the hardware specs? And is this a hackintosh?
> 
> This has nothing to do with the hardware system. I am not the only one who has encountered such problems. It should be the defect of the patch itself. I hope it can be repaired.



> Well how am I supposed to fix this if I don't know what the hardware is? A MacBookPro11,1 has no root patches so why would it report a broken seal? Better understanding of hardware is needed
Caused by hd4000 graphics card patch

**Comment by khronokernel** [comment]
Deltas are not available when you root patch, this is intended functionality as per Apple's documentation
