### ISSUE TITLE
Firmware Bricking thread

### ISSUE THREAD

**Issue by khronokernel** [dortania/Opencore-Legacy-Patcher#44]
With the recent commit to both [this patcher](https://github.com/dortania/Opencore-Legacy-Patcher/commit/50e3e08ff0e4e824c99492b71961c0dcff143cf1) and [OpenCorePkg](https://github.com/acidanthera/OpenCorePkg/commit/dfd459a7f08ed1719b147c48d215d1f292f88634), I added a new quirk to OpenCore that will max out the BIOSVersion property. We've had several reports that this works however we'd still like to have a thread to consolidate things, as we had too many issues to keep track of.

Issues recently closed:

* https://github.com/dortania/Opencore-Legacy-Patcher/issues/43
* https://github.com/dortania/Opencore-Legacy-Patcher/issues/42
* https://github.com/dortania/Opencore-Legacy-Patcher/issues/40
* https://github.com/dortania/Opencore-Legacy-Patcher/issues/38
* https://github.com/dortania/Opencore-Legacy-Patcher/issues/32
* https://github.com/dortania/Opencore-Legacy-Patcher/issues/15

For users with machines that have been bricked, we recommend following [this thread](https://github.com/dortania/Opencore-Legacy-Patcher/issues/32#issuecomment-748698217)

**Comment by mathieulp** [comment]
Please add this to homepage : Power Cycling is useless for bricked iMacs, even Ivy Bridge !!

**Comment by Bustycat** [comment]
README.md still contains

> iMac14,1 # Due to issues with 11.1, currently not supported
> iMac14,2 # Due to issues with 11.1, currently not supported
> iMac14,3 # Due to issues with 11.1, currently not supported

Are they now supported or not?

**Comment by khronokernel** [comment]
@Bustycat Thank you, updated the README.md

**Comment by mathieulp** [comment]
> README.md still contains
> 
> > iMac14,1 # Due to issues with 11.1, currently not supported
> > iMac14,2 # Due to issues with 11.1, currently not supported
> > iMac14,3 # Due to issues with 11.1, currently not supported
> 
> Are they now supported or not?

Sorry but my bricked 13,2 iMac was not listed as not supported!! It is ivy bridge cpu indeed...

**Comment by mathieulp** [comment]
Hi 
I’m tiring to fix my two bricked iMacs. I have opening tools and chip programming tools. 
now I’m looking for clean EFI roms could anyone please supply these?
First imac : A1419 EMC 2639 (late 2013)
2nd : A1419 EMC 2546 (late 2012)
Thanks

**Comment by Ausdauersportler** [comment]
Hi! I already posted this [link](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29418234) once. This guy found a clean rom on ebay. You may also try a google search and may find a download source.

**Comment by MikeBeaton** [comment]
#34 could be merged into this issue too

**Comment by Bab-droid** [comment]
Does this have to do with the "removing opencore" text from the Readme?
I've deleted the whole EFI folder from my internal disk. I was using the 0.0.9 version.
After reseting the nvram my macbook air 2012 isn't booting and I get the forbidden way sign when trying to bootup.
Is there anything I can do?

**Comment by MikeBeaton** [comment]
Not speaking officially on behalf of this project at all, but just speaking as another user:

Can you boot into recovery mode? I think you'd only need to run `nvram boot-args="-no_compat_check"` from the recovery mode command prompt to get back to being able to boot. If recovery mode also won't start, then I think you could use internet recovery mode to get to the same point: start the internet recovery process but don't install the recovery OS, just run the above command when you get to the point where you have an option to start a command shell, then reboot.

You've definitely still got a Mac which you can bring back to life if you're getting the no entry sign!

**Comment by BenSova** [comment]
You probably have Big Sur installed and you can't boot into it with an unsupported Mac. You would have to use a different patcher for that. The "removing opencore" is removing open core if you want to switch back to how it was, this bricking means that your Mac shows zero signs of life other than the display back light being on, but nothing is shown on the display. No boot chime, no boot options (cmd-r, option, shift, etc), no nothing. The prohibited sign would not show on a bricked Mac.

**Comment by MikeBeaton** [comment]
@BenSova I've noticed that the display backlight definitely does not come on, on my MBP when it's really semi-bricked (and requires a battery disconnect to reset it). I use the light on an external USB device to see whether it's powered on or not.

**Comment by MikeBeaton** [comment]
@Bab-droid Just chiming in again quickly, to agree with @BenSova above: if you're on Big Sur, you don't want to remove OpenCore... you want keep it and keep using it! I think Big Sur should _boot_ with just my suggestion above, but depending on your model it will also need some other fixes which OC will provide (and just setting `boot-args` will not), in order for everything to work properly. And even if you have (upgraded) hardware which means you don't need any kexts or patches, you would _definitely_ need to boot via OC to get future OS updates.

**Comment by salakis** [comment]
A bit late to the party, but I was waiting for the parts. My Late 2013 iMac is disassembled, no struggles there, but I simply cannot manage to read the contents of the chip using the CH341A. Is there anything specific I need to keep track of? I am having a hard time properly attaching the clip to the chip and besides, I am not sure about the correct arrangement of pins. My readings are always only containing F or 0.

Thanks a lot in advance if anyone has any suggestions.
