### ISSUE TITLE
Not a problem, just a question.

### ISSUE THREAD

**Issue by vdm-alt** [dortania/OpenCore-Legacy-Patcher#440]
### Machine Model

MacBookPro10,2

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Computers having a damaged or disconnected discrete graphics processor have problems with brightness adjustment and awakening from sleep. DosDude1 for this purpose, a separate patch wrote (demux_10.13_bklt.pkg). In fact, it replaces AppleMuxControl.Kext included in the Applegraphicscontrol.kext. The patch is successfully operating to MacOS Mojave, in systems it does not allow you to make SIP. Personally, I failed to gain access to the folder / System / Library / Extensions /, but OCLP successfully introduces patches. The question is: whether it is impossible to add as an additional feature the possibility of using such a patch for those who need it? Thank you for attention.

**Comment by Ausdauersportler** [comment]
Please use Discord to ask questions and rerun OCLP to enable SIP (patcher settings). This way you can add kernel extensions using the same way as before.

Questions are no OCLP bugs. Your hardware has a bug or malfunction :-) This is more an RFE.

**Comment by khronokernel** [comment]
Feel free to implement, as there doesn't seem to be any documentation on this extension's functionality it's a bit concerning to implement. Feel free to PR and provide the logic for the kext
