### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ehsan58** [dortania/OpenCore-Legacy-Patcher#442]
### Machine Model

MacBookPro9,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Airdrop send & receive  not works i have tested with many iPhones
it's switched on and find from iPhone but when i click on my MBP name its stuck on Waiting...

![Screen Shot 2021-08-16 at 15 55 21](https://user-images.githubusercontent.com/3213169/129556397-454dc105-ba14-4508-9a9a-82198fc1c565.png)

![IMG_5C9EB442897D-1](https://user-images.githubusercontent.com/3213169/129556497-cd683a82-650a-43d8-a5fc-778c94ceeeb5.jpeg)

**Comment by khronokernel** [comment]
macOS bug, not related to OCLP
