### ISSUE TITLE
[Bug]: Final Cut doesn't work

### ISSUE THREAD

**Issue by Giacoste82** [dortania/OpenCore-Legacy-Patcher#444]
### Machine Model

iMac11,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Problems with the opening of Final Cut : I have two versions of this (10.5 and 10.5.2) but I have same problem :

Process:               Final Cut Pro [3231]
Path:                  /Applications/Final Cut Pro.app/Contents/MacOS/Final Cut Pro
Identifier:            com.apple.FinalCut
Version:               10.5 (380212)
Build Info:            ProEditor-38021002010000000~3 (17A130)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Final Cut Pro [3231]
User ID:               501

Date/Time:             2021-08-16 22:21:58.092 +0200
OS Version:            macOS 11.5.1 (20G80)
Report Version:        12
Anonymous UUID:        0CC1AA3C-D911-B7FE-C5E9-4E91B989CB84

Time Awake Since Boot: 19000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [3231]

I don't understand that is a problem of OS after the Open Legacy operations.
Thanks

**Comment by khronokernel** [comment]
You have a non-Metal GPU, Metal-based Applications will break
