### ISSUE TITLE
[Bug]: Graphic Problemsafter turning off the screen to save energy

### ISSUE THREAD

**Issue by Giacoste82** [dortania/OpenCore-Legacy-Patcher#445]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I list a problem that I believe may also be of interest to others : 

after turning off the screen to save energy, after entering the login password, I have problems with the graphic interface that jerks and breaks down the images.
Restarting is the only solution to the problem
Thanks in advance and congratulations on the job

### Any Additional Information

 Nome modello:	iMac
  Identificatore modello:	iMac11,1
  Nome processore:	Intel Core i5 quad-core
  Velocità processore:	2,66 GHz
  Numero di processori:	1
  Numero totale di Core:	4
  Cache L2 (per Core):	256 KB
  Cache L3:	8 MB
  Memoria:	32 GB
  Versione firmware di sistema:	9999.999.999.999.999
  Versione SMC (sistema):	9.9999
  Numero di serie (sistema):	W894860A5PJ
  Hardware UUID:	2C88833E-5AEE-52C5-9C61-3147AE41F47E
  UDID per il provisioning:	2C88833E-5AEE-52C5-9C61-3147AE41F47E

ATI Radeon HD 4850:

  Modello Chipset:	ATI Radeon HD 4850
  Tipo:	GPU
  Bus:	PCIe
  Larghezza canale PCIe:	x16
  VRAM (totale):	512 MB
  Fornitore:	AMD (0x1002)
  ID dispositivo:	0x944a
  ID revisione:	0x0000
  Revisione ROM:	113-B9110C-425
  Versione VBIOS:	113-B91101-009
  Versione driver EFI:	01.00.383
  Monitor:
iMac:
  Tipo di monitor:	LCD
  Risoluzione:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
  Aspetto interfaccia utente:	2560 x 1440
  Profondità buffer fotogrammi:	Colore 30 bit (ARGB2101010)
  Monitor principale:	Sì
  Duplicazione:	Non attiva
  In linea:	Sì
  Regola automaticamente la luminosità:	Sì
  Tipo di connessione:	Interno

**Comment by khronokernel** [comment]
Duplicate:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
