### ISSUE TITLE
[Bug]: USB 3.0 Mode Not Working

### ISSUE THREAD

**Issue by Tockman** [dortania/OpenCore-Legacy-Patcher#447]
### Machine Model

iMac13,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

My NIC (Alfa AWUS 1900) with full USB 3.0 support connects to USB 2.0 only and, therefore, can not provide connection speed more than 2.0 standard presumes. It happens on any of 9 presenting USB 3.0 ports, no matter if I plug it directly or through powered USB hub. I guess it might be fixed with proper port mapping on boot but I'm not strong enough in that theme. Could OCLP solve this problem with USB map kext inject or something else?
![128597722-99d7883a-c7d4-446e-8bb5-0b81f1d6cea4](https://user-images.githubusercontent.com/74548419/129683819-52d9070c-1e42-4efe-8c2d-36e44c7cce95.png)

**Comment by khronokernel** [comment]
macOS Monterey's USB map hasn't changed anything notable compared to Big Sur or even Catalina (ie. dropped maps):
<img width="2032" alt="Screen Shot 2021-08-17 at 7 48 12 PM" src="https://user-images.githubusercontent.com/48863253/129823658-4d424a91-57da-49bc-b0ba-0139470abceb.png">

This seems to be either a hardware or macOS bug, unfortunately not much we can do on our end. Feel free to research further and provide patch sets if you resolve this
