### ISSUE TITLE
Internal speaker is recognised as headphone and not working occasionally 

### ISSUE THREAD

**Issue by paltrowlalic** [dortania/OpenCore-Legacy-Patcher#448]
### Machine Model

iMac12,2

### Application Version

Latest Build (nightly)

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hi, I have had this weird internal speaker issue since upgrading from BigSur to Monterey Beta. Sometimes the internal speaker of the iMac is recognized as a headphone and not working. The only solution is just to restart the machine and it will be recognized as the internal speaker (working) again. Not sure this is related to OCLP (v0.2.2) or just Monterey. Thanks for any help or thoughts.

![img](https://user-images.githubusercontent.com/19687506/129871315-cf798214-44e7-4b91-869d-3fb906ff249c.png)

**Comment by khronokernel** [comment]
Monterey bug, would recommend troubleshooting on forums
