### ISSUE TITLE
Disable SecureBootModel flag doesn't work in GUI

### ISSUE THREAD

**Issue by duilan** [dortania/OpenCore-Legacy-Patcher#452]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

when change the "Disable SecureBootModel" flag setting to build and install Opencore using GUI app.Apparently the value always is false on the print out.

Also checking the generated EFI/config.plist file it seems that it isn't modified.

uncheck both to set sip and SecureBootModel enable
![Captura de Pantalla 2021-08-20 a la(s) 11 47 51](https://user-images.githubusercontent.com/4230964/130272195-3caddb51-88ca-4c8c-b4c6-d08b920dbbb8.png)

SecureBootModel show message "disabling" ( It doesn't matter which flag value you choose )
![Captura de Pantalla 2021-08-20 a la(s) 11 48 31](https://user-images.githubusercontent.com/4230964/130278124-8f194223-ad5e-4723-b94c-fb2d15578fc4.png)

EFI/config.plist - Misc->Security
![Captura de Pantalla 2021-08-20 a la(s) 14 15 14](https://user-images.githubusercontent.com/4230964/130283225-bacab202-ff71-4d72-875d-3ff8b8e8305a.png)

**Comment by khronokernel** [comment]
Resolved: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/f6ef7583eedc706e2bb70550fe847601ef258fcd
