### ISSUE TITLE
[Bug]: Color-Inversing Alternation Flickering on Radeon 6750M with Beta Graphics Acceleration

### ISSUE THREAD

**Issue by mcplayerteam** [dortania/OpenCore-Legacy-Patcher#456]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

macOS Big Sur successfully installed without Metal graphics support, therefore post-install patches were applied. After the restart following post-install patches, the screen rapidly flickers non-stop (with exception of the Apple boot-up logo). The flickering follows the pattern:
- The flickering is simply a fast alternation of normal and inverted colors on the screen
  - Meaning that in one frame the screen looks completely normal, the next frame all colors of the screen are inverted, and the frame after that the screen is back to completely normal, and so on and so forth
- The alternation only happens upon changes on the screen, i.e. it is not periodical, the colors only invert when something on the screen changes
  - I have my digital clock set to display seconds on the menu bar, therefore the screen alternates every second
  - I have Macs Fan Control installed which displays temperature on the menu bar, therefore the screen alternates when the readings refresh
  - Moving the cursor also makes the screen alternate, with slow movements making more frequent alternations due to the refresh rate of the screen keeping up
  - As tested with a secondary monitor, where the menu bar items are not present, the second screen does not alternate when idle
    - It is been tested that the second screen can be manually made to display either normal or inverted colors without flickering as long as it is not used
    - Alternations of the screen are not synchronized, meaning alternations on one screen does not make the other screen alternate
- It should not be an issue from the graphics card nor the screen, as it works perfectly in boot camp windows 11, and that the colors are perfectly inverted instead of irregularly altered

### Any Additional Information

Thank you very much for the macOS Big Sur patch, and also the beta graphics acceleration that makes the system useable. I figured that this flickering issue being highly specific and consistent could mean a relatively simple fix, or a temporary superficial resolution, please let me know if I could provide any further information.

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#erratic-colours-on-ati-terascale-2-gpus-hd5000-hd6000
