### ISSUE TITLE
FileVault on root-patched systems

### ISSUE THREAD

**Issue by Lars-Br** [dortania/OpenCore-Legacy-Patcher#457]
### Machine Model

MacBook5,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

The first version of FileVault (Mac OS X 10.3 to 10.6) encrypted only your user data (home folder), not the system. An attacker with access to the hard drive contents would therefore not be able to read your data (it's encrypted), but would be able to modify the system. The attacker could, e.g., copy your data in encrypted form and modify the system in such a way that it would send your password to a remote server the next time you logged in. They could then use that password to decrypt their copy of your data. 

On later versions of macOS (10.7 to 10.15), FileVault would therefore encrypt both, the system and the data. An attacker with access to the hard drive contents would then not be able to read the data or modify the system (because everything is encrypted).

Current versions of macOS (11 and 12) go back to the old model. Here, FileVault encrypts only the data (which is now on its own volume), the system itself stays unencrypted. However, nowadays the system volume is signed. An attacker with access to the hard drive contents would therefore still not be able to read the data (it's encrypted) or modify the system (because the modification would break the signature and be detected).

That's the reason why Apple does not allow enabling FileVault on machines where the system volume is not signed, e.g. because GPU acceleration patches have been applied. If you could enable FileVault without a signed system volume, the attack against the first version of FileVault described above would work again. The attacker could modify the system (because it's not encrypted) and because there's no signature, the modification would not be detected.

So there is no technical reason why FileVault would need a signed system volume to be able to encrypt your data, but instead, Apple does not want to lull you into a false sense of security. 

However, the first version of FileVault (and the current version if it worked without a signed system volume) is not useless. They still protect your data perfectly against an attacker who simply steals your computer and does not give it back to you, which would be the vast majority of cases. Therefore, it would absolutely make sense to enable FileVault even without a signed system volume.

Because Apple has disabled FileVault on systems without signed system volumes, it would be necessary to patch FileVault and remove the check. When I find the time, I would like to try to find out what has to be changed, but I would be interested to hear what is already known about this. There seem to be at least two checks: You cannot disable the signed system volume as long as FileVault is enabled, and you cannot enable FileVault if you already disabled the signed system volume. What happens if you disable the signed system volume and then boot from another drive (with 10.15 if need be) and encrypt the data volume? Does macOS refuse to boot in that case (third check)?

**Comment by khronokernel** [comment]
> What happens if you disable the signed system volume

Unfortunately you cannot without disabling APFS snapshots and therefore the mechanism to update the OS through system preferences
