### ISSUE TITLE
[Bug]: Unable to wake from sleep, Unable to change brightness. 

### ISSUE THREAD

**Issue by ITSYEJOE** [dortania/OpenCore-Legacy-Patcher#459]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Isssue?

I am on the MacBook pro 8.2, I am unable to wake from sleep, or even change brightness levels. I do not know how to fix this issue, can it be fixed?

**Comment by khronokernel** [comment]
Run post install root volume patches

**Comment by ITSYEJOE** [comment]
> Run post install root volume patches

I did that already. I doesn’t work.

**Comment by tb205gti** [comment]
Same issue here on MackBoobPro8,2. Anything newer than 0.1.7 breaks the booting if the post install patches are applied.
Consider reopening the issue.

**Comment by tb205gti** [comment]
So a verbose boot brings this info before it panics and waits for remote debugger:

dyld: Library Not Loaded: /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
Reference from: /System/Library/Frameworks/MetalPerformanceshaders.framework/Versions/A/Frameowkrs/MPSCore.framework/Versions/A/MPSCore Reason no suitable image found, did find: 
/System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface: code signature in (/System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface) not valid for use in process using Library validation: mapped file has no team ID and is not a platform binary (signed with custom identity or adhoc)

So it looks like the IOSurface.framwork is the culprit for not booting past 016 on MackBookPro8,2.


One thing to note, my MPB ran Catalina using dosdude1's patcher previously, I just updated to BigSur.

**Comment by cukabeka** [comment]
I have this issue, too. Can anyone confirm having a vanilla OCLP BigSur/Monterey install running on a MBP8,2 with display brightness controls working on any OCLP version? I tried it with 0.3.2 to no success.
