### ISSUE TITLE
"immutablekernel" issue and GV Wake Failure - MacBook Pro 9,2 mid-2012 non-Retina Core i5

### ISSUE THREAD

**Issue by vinaypundith** [dortania/Opencore-Legacy-Patcher#46]
I'm trying to update aforementioned laptop to Mac OS 11 Big Sur.

I downloaded the OC LP main repo (as I was not able to run it when I downloaded just the 0.0.9 release), ran the open core[something].command file, had it build a new OpenCore setup, transferred the newly built thing to my systems (Mac OS Catalina v10.15.7, BTW) EFI folder (replacing all the old contents of the EFI folder), then used bless ...... -setBoot to make the system boot from the OpenCore partition.  But instead it gives these errors, crashes, and then boots to the Catalina recovery partition:

[EB| 'LD:LF] FIO: 0, DIR:1, P: <null string>, DP:1
[EB|'B:SBS] SZ: 6211112
[EB|#B:SHA] f4031e1840ae80899574cd5a1feedc6b106d0f87
[EB|'WL:pWLFNV] Err(0xE) @ GV wake-failure
[EB|#WL:DT] 0xCB 0x3C 184 0xCA
[EB|'FS:AGSVH] Err(0xE) @ 'AGU.0
[EB|'LD:LKC] SB -> (System\Library\PrelinkedKernels\immutablekernel)
[EB|'LD:LKC] BPDK -> (System\Library\PrelinkedKernels\immutablekernel.development)
[EB|'LD:LF] FIO: 0, DIR:1, P: System\\Library\\PrelinkedKernels\\immutablekernel.development, DP:0
[EB|'LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\immutablekernel.development)
[EB|'LD:LKC] BPDK, !R -> (System\Library\PrelinkedKernels\immutablekernel)
[EB|'LD:LF] FIO: 0, DIR:1, P: System\\Library\\PrelinkedKernels\\immutablekernel, DP:0

So what have I done wrong? What's an immutablekernel? Also I did not add any prelinkedkernel patches, so why the related errors? Do I need to modify the config.plist configuration created by the OpenCore Legacy Patcher, or exclude some kexts? Tried searching the internet for this error to no avail. Kinda stumped.

I should probably add that the machine that the Legacy Patcher decided to spoof to is a MacBook Pro 11,1.

Thanks in advance.

**Comment by khronokernel** [comment]
Resolved in main
