### ISSUE TITLE
[Bug]: No boot menu on Mac Pro 3,1 w/R9 280

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#465]
### Machine Model

MacPro3,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

OpenCore boot picker doesn't show a display on Mac Pro 3,1, GPU is AMD R9 280 (non-flashed) with Apple Cinema Display 23" plugged into the DVI port.

By just waiting and crossing my fingers I can boot into macOS fine, and there is the traditional macOS boot screen after getting past OpenCore boot menu.

**Comment by Piipperi** [comment]
Also, there are no Audio devices found. I tried patching the System Volume but it said "No Root Patches required for your machine!"

**Comment by Ausdauersportler** [comment]
Oh, this might be one of those endless AMD GPU support stories....

Your AMD GPU needs a GOP vBIOS to enable a boot screen with OpenCore. Check it by loading the vBIOS and searching within the binary code for the TEXT string "GOP" using a HEX editor. Another way to check it is using the Terminal command strings (part of brew) like this: 

`me@iMac` GOP % strings WX4170_GOP.rom | grep GOP
GOP AMD REV: x.x.x.x.x
me@iMac GOP % 
`
There are hidden in the web sites which [scripts](https://www.win-raid.com/t892f16-AMD-and-Nvidia-GOP-update-No-requests-DIY.html) to add the GOP part to your standard BIOS. It can be done manually, too. But this is beyond the scope if this little message.

In case you already have a GOPped vBIOS ignore my answer.

**Comment by khronokernel** [comment]
As Ausdauersportler mentioned, you need a UGA or GOP VBIOS to get display output through OpenCore

**Comment by Piipperi** [comment]
> As Ausdauersportler mentioned, you need a UGA or GOP VBIOS to get display output through OpenCore

This should be in the docs of OpenCore Legacy Patcher then.

**Comment by Piipperi** [comment]
> Is is included in the OpenCore docs. 

I couldn't find the info from OCLP docs tho.
