### ISSUE TITLE
[Bug]: no bluetooth

### ISSUE THREAD

**Issue by brockjohnson74** [dortania/OpenCore-Legacy-Patcher#467]
### Machine Model

MacBookPro5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

is there any why to get bluetooth working

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/364
