### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by tb205gti** [dortania/OpenCore-Legacy-Patcher#469]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

The Automatic TS2 patch breaks MacBookPro8,2 if you have disabled the dgpu in nvram. Problem is that it fails to boot entirely on any release later than 0.1.6. Running newer versions without th TS2 patch is working apart from no backlight control.

Please add an option to not patch for TS2 when running the post patch, like you could in the <0.1.6 versions.

**Comment by khronokernel** [comment]
The affected code you'd wish to disable is here:
https://github.com/dortania/OpenCore-Legacy-Patcher/blob/077af5afb3368025af4436ef1446759111c77a03/Resources/SysPatch.py#L560-L563

I would much prefer there be proper research into the issue, and currently I have zero interest debugging remotely with users. You may further investigate and open a pull request into the repo
