### ISSUE TITLE
v0.25 nightly built can't be opened

### ISSUE THREAD

**Issue by Tiger-AC** [dortania/OpenCore-Legacy-Patcher#470]
### Machine Model

iMac13,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Upgraded from macOS Monterey Beta 5 to 6 with the previous nightly built v0.25 successfully. Downloaded the latest nightly built v0.25 and it just can't open it (I know the right way of opening it the first time by right clicking the app and select Open.). Not sure if this the issue of Beta 6 or the latest v0.25n.
PS. I can still open the previous v0.25n and v0.24.
![Screen Shot 2021-09-01 at 7 59 24 am](https://user-images.githubusercontent.com/82495745/131581792-28b9075f-4c9f-4b7c-a593-8031b3a9757f.png)

**Comment by khronokernel** [comment]
Nothing changed with our signing Certificate with Apple, looking at my email I see the latest nightly was signed fine:

| TUI Signing | GUI Signing |
| :--- | :--- | 
| <img width="866" alt="Screen Shot 2021-08-31 at 4 09 49 PM" src="https://user-images.githubusercontent.com/48863253/131582284-0daedab8-524b-4a8e-8a3e-51c31955b191.png"> | <img width="868" alt="Screen Shot 2021-08-31 at 4 08 59 PM" src="https://user-images.githubusercontent.com/48863253/131582218-140212d9-bfe2-4f3c-b08f-c5664c6851ec.png"> | 

And on the latest Monterey beta, my M1 runs the binary fine. A user on 11.2.3 also tested with no issues. However on my MacPro5,1 running Monterey Beta 6, it does fail. Honestly this seems to be an OS issue parsing newly signed binaries, nothing we can do on our end as even Apple themselves say our application passes notarization

**Comment by Tiger-AC** [comment]
Thx for the reply. I used another iMac (late 2009 21.5" running DosDude1's Catalina) downloaded the latest nightly built v0.25 OCLP, opened once (without any issue), then transferred this app to the late-2012 iMac running beta-6. It now can open it.
