### ISSUE TITLE
Macbook Pro Late 2014 Login screen freeze when waking up. 

### ISSUE THREAD

**Issue by vitaliy-kozlov** [dortania/OpenCore-Legacy-Patcher#472]
### Machine Model

MacBookPro11,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

When macbook going to sleep and waking up after a some time the login screen is freezing with loadling spin. Seems to be that this is some kind of hibernation issue. Also it's not always reproducible and random, but macbook freeze every day.

**Comment by khronokernel** [comment]
Feel free to research further however we have no developers or testers with hibernation issues so cannot test ourselves. PR patches if you do determine the issue to be OCLP
