### ISSUE TITLE
[Bug]: Cannot use wifi on MBP4,1 with Upgraded bcm4322 wifi card

### ISSUE THREAD

**Issue by nicksilverstein** [dortania/OpenCore-Legacy-Patcher#474]
### Machine Model

MacBookPro4,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Isssue?

I cannot use wifi with the upgraded bcm4322 apple airport card in my MacBookPro4,1.

**Comment by khronokernel** [comment]
Monterey is expected to have no support as listed here:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/365

Are you certain this issue occurs in Big Sur or did you mistakenly select it?
