### ISSUE TITLE
[Question]: DRM Support in Big Sur 11.5.2 (MacPro5,1)

### ISSUE THREAD

**Issue by lovelytwo** [dortania/OpenCore-Legacy-Patcher#475]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Just unsure whether or not DRM should work on my configuration, i can't find a clear answer anywhere. I'm running a macpro 5,1 with vega 64, running open core patcher 2.4 on Big Sur 11.5.2

Anything that uses hardware or apple provided drm doesn't seem to work. (Ether red or green keyed overlay shown)
- Apple TV
- Safari

Using this reference it sounds like it should work:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md

As both the following criteria are fur-filled. 
- Only IGPU-free Mac models allow for full DRM content access given a compatible AMD GPU video decoder
- For old CPUs (e.g. Xeons or Quad 2 Quad) and supported AMD GPUs injecting unfairgva with <01 00 00 00> value is required for streaming DRM)

If it should work, what should i do next to work out how to fix it?

Thank-you for your time and all your hard work on such a great project keeping so many macs alive.

**Comment by khronokernel** [comment]
Verify whether 0.2.5 can also replicate:

https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip

I believe this may be linked to the PCI Bridge issue we recently worked around, as Vega and navi GPUs have an extra PCI Bridge in their device path:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/451

**Comment by lovelytwo** [comment]
I can confirm that has fixed the problem with drm. Both AppleTV and Amazon Prime (Safari) work.

I assume the fix was moving device specific options to bootargs?

Curious why the spoofed model was changed from MacPro7,1 to iMacPro1,1?

From what i can tell everything is working: Is any there anything else you would like me to check on this release?

**Comment by khronokernel** [comment]
> Curious why the spoofed model was changed from MacPro7,1 to iMacPro1,1?

Wider OS support, as many use OCLP just to restore boot screen support on 3rd party GPUs
