### ISSUE TITLE
[Issue]: MacBookPro8,2 with disabled AMD GPU stuck on an overheating Apple Screen

### ISSUE THREAD

**Issue by ArsenicVinter** [dortania/OpenCore-Legacy-Patcher#477]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

I have applied Root Volume Patches via OpenCore’s Legacy Patcher (GUI) and now my MacBook Pro doesn’t boot with applied patches

The screen dims a little and stays stuck on the Apple logo, do note my AMD GPU is no longer functional so it’s disabled via nvram. 

It also ramps up its fans within the process and stays stuck, if possible can I boot into Big Sur without my AMD TeraScale (6xxx series) GPU 

### Any Additional Information

MacBookPro 8,2 [Early 2011, 15-inch]
• 8GB 1600Mhz DDR3 RAM
•1 TB Western Digital Blue HDD
• macOS High Sierra 10.13.6 (currently running Big Sur 11.4 via OCLP)
• Intel HD Graphics 3000 series (exclud. AMD Radeon HD 6xxx GPU)

**Comment by Ausdauersportler** [comment]
Please check if this build works: (copied from Discord communication)

https://nightly.link/dortania/OpenCore-Legacy-Patcher/workflows/build-app/main/OpenCore-Patcher-TUI.app.zip
Before patching the root volume, go to Patcher Settings -> Miscellaneous Settings -> Set TeraScale 2 Accel -> False

This would need a new Big Sur installation and a new patch attempt.

**Comment by ArsenicVinter** [comment]
Thank you for the quick response- I’ll test it out and let you know

**Comment by ArsenicVinter** [comment]
![Screenshot 2021-09-07 at 17 51 23](https://user-images.githubusercontent.com/55028438/132347669-3cfa4bcf-2704-4be8-9a17-40829f03350a.png)

Thank you for the response, it helped so much as I was confused of as to what was going on after the Root Patches but disabling the TeraScale Accel in the patcher settings, it booted just fine

Thank you, and overall the UI is pretty fluid and feels native

**Comment by Ausdauersportler** [comment]
You have to understand that the hardware detection of OCLP recognizes your system and finds your GPU and applies all necessary patches. There is no way to find out if a GPU is broken other than reading your NVRAM setting. So your case is quite special, having a GPU and disable it just by software. All the credits go to @khronokernel - he is the guy fixed this special case last night. I just picked it up.

**Comment by ArsenicVinter** [comment]
I give you my many thanks on this case and @khronokernel for the fix
