### ISSUE TITLE
[Bug]: cannot update to opencore 0.7.3 from 0.6.9

### ISSUE THREAD

**Issue by rankawar** [dortania/OpenCore-Legacy-Patcher#478]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

tried to update from opencore 0.7.3 from 0.6.9 on my imacpro1,1

log and info in comments

![Screenshot 2021-09-08 at 10 44 44 PM](https://user-images.githubusercontent.com/16179772/132554507-bb4d2718-9749-444d-8806-7661d0bc3a9c.png)
[opencore-2021-09-08-165921.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7130684/opencore-2021-09-08-165921.txt)

**Comment by khronokernel** [comment]
Please put an extra 2 seconds into checking what repo you opened an issue in, this entire project is dedicated to genuine Macs…
