### ISSUE TITLE
[Bug]: MacPro5,1 panic on boot after update to 11.5.2

### ISSUE THREAD

**Issue by jgimeno** [dortania/OpenCore-Legacy-Patcher#479]
### Machine Model

MacPro5,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

After I updated to 11.5.2 when loging it reboots before arriving to the OS. I tried to make a repair but it still happens.

I include the log:

[opencore-2021-09-08-201827.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7131638/opencore-2021-09-08-201827.txt)

**Comment by khronokernel** [comment]
I see no panic in your log, could you please be a bit more verbose regarding your setup? ie. hardware specs

**Comment by khronokernel** [comment]
Closing as no response
