### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Andr3s83** [dortania/OpenCore-Legacy-Patcher#480]
### Machine Model

Macmini5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

When I open safari or I'm on a screen with a black background in dark mode and I drag the mouse I see some black squares, the screen is a little slow.
I have a 240Gb SSD disk and 16 Gb of RAM.
Mac mini mid 2011 5.1Please clearly explain the issue
.
 Sorry for the lack of professionalism.
 I´m just starting in this world.

**Comment by khronokernel** [comment]
Known issue:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
