### ISSUE TITLE
[Bug]:coreaudio big sur

### ISSUE THREAD

**Issue by javierrl2** [dortania/OpenCore-Legacy-Patcher#481]
### Machine Model

MacBook8,1

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

there is no connection to audiointerface, I have a umc204hd and worked fine with catalina using the patch over coreaudio, but when I'm using logic pro on big sur it does not give any sound. 

the card is recognized by the OS, but I can't use it as an entry audio interface. I try kill coreaudio, reset pram and all that things but nothing worked, maybe there is some issue with coreaudio over bigsur with the pach.

### Any Additional Information

coreaudio issue with audiointerfaces

**Comment by khronokernel** [comment]
This is outside our scope as the MacBook8,1 are already native on Big Sur
