### ISSUE TITLE
[Bug]: Prohibitory Sign After Install - MacBook Mid-2010 (A1342)

### ISSUE THREAD

**Issue by TinyFartBox** [dortania/OpenCore-Legacy-Patcher#483]
![E733654B-6B10-471D-9FF6-703C38ABBFA1](https://user-images.githubusercontent.com/90493114/132936524-6bd8b609-acf0-480b-a96e-6fc2ca5f9513.jpeg)
### Machine Model

MacBook7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

I followed all the directions perfectly and have tried different methods and replicating old ones as well, all with the same outcome.

After installing the software, instead of going right into Big Sur, it takes me to a black screen, with a prohibitory sign, that states support.Apple.com/Mac/Startup

I am booting into EFI USB boot, and then following all appropriate steps. Everything follows like it states it should in the directions and videos, but at the end I always end up at that black screen with a prohibitory sign. 

Please help.

**Comment by AlexSakha** [comment]
![Снимок экрана 2021-09-11 в 23 34 31](https://user-images.githubusercontent.com/74450973/132952076-c0129126-926d-4fbf-a9ec-d1acceae2282.png)
![Снимок экрана 2021-09-11 в 23 37 44](https://user-images.githubusercontent.com/74450973/132952087-a84cac6a-7eb2-4722-b776-ef49a9871b09.png)
Reset NVRAM

**Comment by khronokernel** [comment]
Use forums to troubleshoot
