### ISSUE TITLE
[Issue] How to enable iGPU under Windows 10 on MacBookPro8,2 with disabled dGPU?

### ISSUE THREAD

**Issue by ArsenicVinter** [dortania/OpenCore-Legacy-Patcher#484]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur, Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

So I'm planning to test out Windows 10 out on my 2011 MacBook again, but from past experiences I got it to boot via the normal boot selection screen but the screen goes black after the Intel Graphics are installed and then stays stuck on the splash screen. Will this be any different with OCLP's boot screen or installation method?

Does anyone know any workarounds for this issue or am I at a dead end here?-

**Comment by khronokernel** [comment]
Use forums for troubleshooting
