### ISSUE TITLE
how to switch from "barrykn / big-sur-micropatcher" to OC?

### ISSUE THREAD

**Issue by fxdpz** [dortania/OpenCore-Legacy-Patcher#487]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

My MAC is macbook pro 10.1. I have used "barrykn / big-sur-micropatcher" to install big sur, and I want to switch from "barrykn / big-sur-micropatcher" to OC and install Monterey. I am not sure what procedure I should folllow. Is it possible to Install from usb with OC steps? Any advices?

**Comment by khronokernel** [comment]
Reinstall the OS, use forums for further troubleshooting
