### ISSUE TITLE
[Bug]: Cannot install Windows 10 on Mac Mini 6,1

### ISSUE THREAD

**Issue by Ritchie333** [dortania/OpenCore-Legacy-Patcher#489]
### Machine Model

Macmini6,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I have never had much success installing Windows on any Mac.

For this test, I used a Mac Mini 2012 (Macmini 6,1) with 6GB RAM and a fresh 250GB SSD and a blank 1TB HDD, unformatted.

Following the instructions, I can boot the Windows installer, but get an error "Windows cannot be installed to the hard disk space. Windows must be installed to a partition formatted in NTFS".

If I ignore this and delete all partitions in the disk so the install happens on unpartitioned space, it gets as far as copying files, then fails with the error "Windows could not prepare the computer to boot into the next phase of installation. To install Windows, restart the installation" - this error is presumably because deleting all partitions also deletes the pre-prepared one with OpenCore so the installer has no idea how to boot.

The SSD has previously had Big Sur installed successfully and has no known defects.

**Comment by khronokernel** [comment]
Use forums for Windows issues
