### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Luigi222** [dortania/OpenCore-Legacy-Patcher#490]
### Machine Model

MacBook7,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hi there, not sure I'm in the right place, I've got a Macbook Pro 17 from 2010, I've successfully installed an patched Big Sur on this machine, the thing is, my Imessage App is super sluggish while scrolling and the quick menu on the top right hand conner is also all messed up, has this been solved ? Or is anybody aware of this?

**Comment by Ritchie333** [comment]
From the description, that's a MacBookPro 6,1 (https://everymac.com/ultimate-mac-lookup/?search_keywords=MacBookPro6,1). You need to run the legacy graphics patcher; from your description of issues, it sounds like you haven't. See https://dortania.github.io/OpenCore-Legacy-Patcher/POST-INSTALL.html#applying-post-install-volume-patches

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
