### ISSUE TITLE
[Bug]: Strange behavior after waking from hibernation on MBP 9,2 (but not crashing!)

### ISSUE THREAD

**Issue by NinjaCheetah** [dortania/OpenCore-Legacy-Patcher#491]
### Machine Model

MacBookPro9,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Strange behavior, such as Menu Bar items (seems to be specifically battery, clock and Control Center) never appearing happen after logging in when the Mac has been asleep for a long time. (Seems to be hibernation, since it does the DVD drive test thing when I open it.) A reboot fixes everything.
Other strange behavior I've noticed:
- Systems apps like System Preferences running slowly and eventually crashing or not responding
- Night Shift getting stuck on with no way to disable it (in Control Center (when it appears at least), it says Night Shift is off, same deal with System Preferences)
- Minor performance issues
- Inability to enter password on login screen (requires a force restart as it just spins and spins)

I know there have been some issues with hibernation (by which I mean [this one](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/72)) causing crashing, but I'm not quite sure if this is the same issue or not since macOS never completely crashes and there's no `Sleep Wake Failure`.

**Comment by khronokernel** [comment]
Cannot replicate locally or within our testers, feel free to research further and provide patch sets
