### ISSUE TITLE
non mac metal video cad in 2010 mac pro

### ISSUE THREAD

**Issue by Gnx231** [dortania/OpenCore-Legacy-Patcher#493]
### Machine Model

MacBook5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Is it possible to have a oclp boot screen using a non mac metal video card on my 2010 mac pro?

**Comment by Ausdauersportler** [comment]
Please use the Discord [server](https://discord.gg/XzQj7Uvs) to ask such questions.  
Please consult the OpenCore online docs to understand the OC boot screen. 

You may need to flash GOP ROM on NVIDIA 6xx/AMD 2xx or older. Search the net and use [GopUpdate](https://www.win-raid.com/t892f16-AMD-and-Nvidia-GOP-update-No-requests-DIY.html) in case you are not sure how.

BTW: 
MacBook5,1 or MacPro5,1?
Is a simple question a software Bug?
