### ISSUE TITLE
[Bug]: Brightness control for display and keyboard both do not work. 

### ISSUE THREAD

**Issue by ITSYEJOE** [dortania/OpenCore-Legacy-Patcher#494]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Even after the post install drivers are downloaded, the issue is still a reality. Please clearly explain the issue

**Comment by khronokernel** [comment]
* https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html

Please use forums for troubleshooting
