### ISSUE TITLE
[Bug]: Unable to wake from sleep, Unable to change brightness

### ISSUE THREAD

**Issue by ITSYEJOE** [dortania/OpenCore-Legacy-Patcher#495]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Even after the post install is downloaded, this problem still occurs. please help fix this issue that is widely occurring for many with similar device.

**Comment by khronokernel** [comment]
Excuse you? Please don't clutter our issues tab. Already responded to you:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/494

You are not entitled to the time of our developers, we have zero interest in troubleshooting issues with zero useful info. Use forums please and thank you
