### ISSUE TITLE
Nvidia Kepler Acceleration Support in macOS Monterey

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#498]
With macOS Monterey Beta 7 (21A5522h), Apple dropped support for Nvidia Kepler GPUs. To reimplement support, we will need to use Big Sur .bundle binaries due to issues with dyld extraction.

Current binaries we need to re-add:

```
GeForce.kext            - Present in 12.0 B6
GeForceAIRPlugin.bundle - Missing binary
GeForceGLDriver.bundle  - Missing binary
GeForceMTLDriver.bundle - Missing binary
GeForceVADriver.bundle  - Present in 12.0 B6
NVDAGF100Hal.kext       - Present in 12.0 B6
NVDAGK100Hal.kext       - Present in 12.0 B6
NVDAResman.kext         - Present in 12.0 B6
NVDAStartup.kext        - Present in 12.0 B6
```

* For binaries missing on disk, use 11.0 Beta 6 (20A5364e) as this is the last time Apple shipped .bundles outside of dyld cache

Greater testing will be done once InstallAssistant is seeded, for now users are recommended to stay on 12.0 Beta 6

**Comment by madvinegar** [comment]
Where do you add these binaries?

**Comment by madvinegar** [comment]
Unfortunately I already upgraded to Beta7 and lost acceleration. I have a Nvidia GT740 which was working great up to beta6.
Anyway someone can upload he missing binaries from beta6 so I can add them back to beta7?

**Comment by Ausdauersportler** [comment]
Check the issue again. The missing binaries will be found on Big Sur Beta6 (20A5364e). 
Join the discord server to do trouble shooting and follow the latest over night development.

**Comment by Cuacon2004** [comment]
> Unfortunately I already upgraded to Beta7 and lost acceleration. I have a Nvidia GT740 which was working great up to beta6.
> Anyway someone can upload he missing binaries from beta6 so I can add them back to beta7?

you can create macOS Monterey beta 6 usb installer and downgrade back to beta 6. I'm using GT 730 and i'm lost acceleration

**Comment by madvinegar** [comment]
> > Unfortunately I already upgraded to Beta7 and lost acceleration. I have a Nvidia GT740 which was working great up to beta6.
> > Anyway someone can upload he missing binaries from beta6 so I can add them back to beta7?
> 
> you can create macOS Monterey beta 6 usb installer and downgrade back to beta 6. I'm using GT 730 and i'm lost acceleration. I just downgrade back to beta 6 and everything seems to be fine again

It's not my primary PC. I use it for testing. I can wait for a fix or a workaround if someone can assist.

**Comment by khronokernel** [comment]
This was resolved in mainline yesterday, forgot to close issue

**Comment by LukasAppleFan** [comment]
So we're people able to re add acceleration to Kepler GPUs ?

**Comment by pointum** [comment]
There’s no need to downgrade to Beta 6, if you can’t get Beta 7 to finish booting because of this issue.

Just wanted to clarify the steps in case it helps anyone:

- Boot Beta 7 in Safe Mode by holding Shift during power up.
- Download latest OpenCore-Legacy-Patcher source code.
- Run `OpenCore-Patcher.command`.
- Select “3. Post-Install Volume Patch” and follow instructions.

**Comment by LukasAppleFan** [comment]
Ok thanks

**Comment by cosmiccowboy68** [comment]
Please check out Chris1111 who has a Geforce Kepler patch for Monterey Beta 7 and can confirm this works.
https://github.com/chris1111/Geforce-Kepler-patcher
