### ISSUE TITLE
Macbook Air 5,2 - Big Sur sleep issues

### ISSUE THREAD

**Issue by Bab-droid** [dortania/Opencore-Legacy-Patcher#50]
I can't know for sure what are the steps to test as I don't have Big Sur since long.
Though, I sometimes get a random reboot after I put my macbook to sleep (closing the lid).
I'm not sure if regular Sleep or Safe sleep is the issue, as well as on battery or plugged.

I'll report if I can gather informations

**Comment by Bab-droid** [comment]
Got some crash report, not sure if its the only log I could send

`Sleep Wake failure in EFI

Failure code:: 0x00000000 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2021-01-28 18:43:50.856 +0100
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   32

Data Source:      Stackshots
Shared Cache:     E2B1A630-68DD-30AC-A036-6AC018B154DA slid base address 0x7fff20131000, slide 0x131000

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        keepsyms=1 debug=0x100 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 36s



Process:          swd [345]
Architecture:     x86_64
Footprint:        348 KB
Time Since Fork:  3s
Num samples:      1 (1)

  Thread 0x8ea    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 87585) [0x7fff2045d621] 1
    1  ??? [0x106705454] 1
      1  ??? [0x1067051e8] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 143386) [0x7fff2043001a] 1
         *1  ??? [0xffffff800025f1f6] 1
           *1  ??? [0xffffff8000968cdb] 1
             *1  ??? [0xffffff8000872821] 1
               *1  ??? [0xffffff80002821c9] 1
                 *1  ??? [0xffffff80002b938d] (running) 1

  Binary Images:
        0x7fff2040d000 -     0x7fff2043bfff  libsystem_kernel.dylib (7195.60.75) <4BD61365-29AF-3234-8002-D989D295FDBB>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff20448000 -     0x7fff20482fff  libdyld.dylib (832.7.1)             <2F8A14F5-7CB8-3EDD-85EA-7FA960BBC04E>  /usr/lib/system/libdyld.dylib
`

**Comment by Bab-droid** [comment]
`Sleep Wake failure in EFI

Failure code:: 0x00000000 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2021-02-11 02:36:14.697 +0100
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   32

Data Source:      Stackshots
Shared Cache:     E2B1A630-68DD-30AC-A036-6AC018B154DA slid base address 0x7fff20072000, slide 0x72000

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        keepsyms=1 debug=0x100 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 80s



Process:          swd [330]
Architecture:     x86_64
Footprint:        360 KB
Time Since Fork:  47s
Num samples:      1 (1)

  Thread 0x8a5    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 87585) [0x7fff2039e621] 1
    1  ??? [0x1094e3454] 1
      1  ??? [0x1094e31e8] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 143386) [0x7fff2037101a] 1
         *1  ??? [0xffffff800025f1f6] 1
           *1  ??? [0xffffff8000968cdb] 1
             *1  ??? [0xffffff8000872821] 1
               *1  ??? [0xffffff80002821c9] 1
                 *1  ??? [0xffffff80002b938d] (running) 1

  Binary Images:
        0x7fff2034e000 -     0x7fff2037cfff  libsystem_kernel.dylib (7195.60.75) <4BD61365-29AF-3234-8002-D989D295FDBB>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff20389000 -     0x7fff203c3fff  libdyld.dylib (832.7.1)             <2F8A14F5-7CB8-3EDD-85EA-7FA960BBC04E>  /usr/lib/system/libdyld.dylib
Model: MacBookAir6,2, BootROM 9999.999.999.999.999, 2 processors, Dual-Core Intel Core i5, 2,3 GHz, 8 GB, SMC 2.5f9
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1675.1)
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Air, Apple Inc., 23.4
`

**Comment by Bab-droid** [comment]
Workaround can be used by disabling safe sleep (hibernation). Be carefull at your battery life during regular sleep as you will loose battery life and loose your open documents if you let your mac to long without power.

command is : 
sudo pmset -a hibernatemode 0

**Comment by khronokernel** [comment]
Moving to dedicated issue: https://github.com/dortania/Opencore-Legacy-Patcher/issues/72
