### ISSUE TITLE
[Bug]: how to solve display bar and sound bar correct position?

### ISSUE THREAD

**Issue by razev027** [dortania/OpenCore-Legacy-Patcher#500]
### Machine Model

MacBookPro6,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

sound bar and display bar toggle not showing up. please help to solve this solution.

![Screen Shot 2021-09-22 at 10 33 47 PM](https://user-images.githubusercontent.com/91213541/134387307-238955ce-d6af-469d-a897-1029ac3484df.png)

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by razev027** [comment]
how to solve this issue?? @khronokernel
