### ISSUE TITLE
[Bug]: Can't Post-Install Volume Patch

### ISSUE THREAD

**Issue by Cuacon2004** [dortania/OpenCore-Legacy-Patcher#501]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I can't patch my system. When i click option 2: Post-Install Volume Patch and choose Patch System Volume, it's said "- No Root Patches required for your machine!" while my nvidia kepler gt730 card only display 8M
![Screen Shot 2021-09-23 at 09 05 39](https://user-images.githubusercontent.com/89370079/134444855-892d0fbf-f4a1-4047-972c-5894d729fdb2.png)
SMBIOS: iMac18,3
Grpahics Card: NVIDIA GT 730 2GB GDDR5

**Comment by khronokernel** [comment]
What is the device ID of your GPU? If unsure, go into `Patcher Settings` -> `Dump detected hardware` and send the data generated

**Comment by Cuacon2004** [comment]
> What is the device ID of your GPU? If unsure, go into `Patcher Settings` -> `Dump detected hardware` and send the data generated

Computer(real_model='iMac18,3', real_board_id='Mac-BE088AF8C5EB4FA2', reported_model='iMac18,3', reported_board_id='Mac-BE088AF8C5EB4FA2', gpus=[Intel(vendor_id=32902, device_id=22802, class_code=229376, name='IGPU', model='Intel HD Graphics 630', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x2,0x0)', arch=<Archs.Kaby_Lake: 'Kaby Lake'>), NVIDIA(vendor_id=4318, device_id=4743, class_code=196608, name='GFX0', model='NVIDIA GeForce GT 730', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)', arch=<Archs.Kepler: 'Kepler'>)], igpu=Intel(vendor_id=32902, device_id=22802, class_code=229376, name='IGPU', model='Intel HD Graphics 630', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x2,0x0)', arch=<Archs.Kaby_Lake: 'Kaby Lake'>), dgpu=Intel(vendor_id=32902, device_id=22802, class_code=229376, name='IGPU', model='Intel HD Graphics 630', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x2,0x0)', arch=<Archs.Kaby_Lake: 'Kaby Lake'>), storage=[SATAController(vendor_id=32902, device_id=41218, class_code=67073, name='SAT0', model=None, acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x17,0x0)')], wifi=Broadcom(vendor_id=5348, device_id=17201, class_code=163840, name='ARPT', model=None, acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)', country_code='BR', chipset=<Chipsets.AirPortBrcm4360: 'AirPortBrcm4360 supported'>), cpu=CPU(name='Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz', flags=['FPU', 'VME', 'DE', 'PSE', 'TSC', 'MSR', 'PAE', 'MCE', 'CX8', 'APIC', 'SEP', 'MTRR', 'PGE', 'MCA', 'CMOV', 'PAT', 'PSE36', 'CLFSH', 'DS', 'ACPI', 'MMX', 'FXSR', 'SSE', 'SSE2', 'SS', 'HTT', 'TM', 'PBE', 'SSE3', 'PCLMULQDQ', 'DTES64', 'MON', 'DSCPL', 'VMX', 'SMX', 'EST', 'TM2', 'SSSE3', 'FMA', 'CX16', 'TPR', 'PDCM', 'SSE4.1', 'SSE4.2', 'x2APIC', 'MOVBE', 'POPCNT', 'AES', 'PCID', 'XSAVE', 'OSXSAVE', 'SEGLIM64', 'TSCTMR', 'AVX1.0', 'RDRAND', 'F16C']), oclp_version=None, opencore_version='REL-074-2021-09-21', bluetooth_chipset='BRCM20702 Hub')

**Comment by khronokernel** [comment]
```
NVIDIA(vendor_id=4318, device_id=4743, class_code=196608, name='GFX0', model='NVIDIA GeForce GT 730', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)', arch=<Archs.Kepler: 'Kepler'>)
```
` device_id=4743` translates into `1287`, which we do support in OCLP and we even correct detect with `arch=<Archs.Kepler: 'Kepler'>`. Are you certain you're running 0.2.5's latest build on 12.0 Beta 7 (21A5522h)?

**Comment by Cuacon2004** [comment]
![Screen Shot 2021-09-23 at 09 13 48](https://user-images.githubusercontent.com/89370079/134445448-3172c53e-04ff-4ae2-a803-6a4d0f44b14a.png)
yes, i'm sure and i'm running macOS Monterey beta 7

**Comment by Cuacon2004** [comment]
So how can i fix it ?
