### ISSUE TITLE
[Enchantment]: Add an option to disable iGPU on WIndows

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#502]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I noticed that OCLP 0.2.5 enabled iGPU support for Windows on Macs with dGPU. Knowing how bad the graphics switching can be on Windows, as someone who uses Windows only for gaming, I would not like the iGPU to be on and producing heat, and potentially have games use that instead.

I did dig through the TUI settings for 0.2.5 but there was no setting to enable/disable iGPU on Windows. So I'm hoping this could be an option added in future releases if possible.

**Comment by caleb39411** [comment]
See #203

**Comment by khronokernel** [comment]
> See #203

@caleb39411 Unrelated, this issue is in reference to the GMUX and not overall iGPU/dGPU support
