### ISSUE TITLE
[Bug]: Apps crashing from memory issues in Big Sur

### ISSUE THREAD

**Issue by NinjaCheetah** [dortania/OpenCore-Legacy-Patcher#503]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

This is apparently a well-known issues, and @Ausdauersportler suggested that an issue should be opened for it.
The problem is that apps, mostly background processes, begin to have memory issues, causing them to repeatedly crash, eventually bringing down the entire system. It seems to happen most coming out of sleep but can still happen on a fresh reboot.
The issue can be alleviated using `sudo purge`, however that requires you to either have SSH access or a terminal window open as once this issue starts, it usually prevents new apps from opening. I'm attaching some (trimmed, let me know if any of the info I trimmed is needed) crash reports from apps affected by this.

### Reports
(Zipped so I can send them as `.crash` files)
[CrashLogs.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7221094/CrashLogs.zip)

**Comment by khronokernel** [comment]
Not able to produce locally with any of our testers, feel free to troubleshoot yourself and provide patch sets but as-is there is little we can do without affected hardware locally.

You can attempt to disable Hibernation as that's known to cause memory corruption, but otherwise you'll need to research more yourself

**Comment by NinjaCheetah** [comment]
I have to say that I'm a little skeptical that _nobody_ else is having this issue, since the reason that Ausdauersportler recommended I open this issue because it's a known issue and it's also happening to him.

**Comment by khronokernel** [comment]
Well none of our testers have this issue, so how do you expect us to work on it?

**Comment by Ausdauersportler** [comment]
Just a hint: Happens on Monterey, too!
https://forums.macrumors.com/threads/macos-12-monterey-on-unsupported-macs-thread.2299557/post-30353475

**Comment by NinjaCheetah** [comment]
## Update
While I can't speak for the "Volume hash mismatch" error in Monterey, I can confirm that my issue in Big Sur was due to faulty RAM. If you're experiencing this issue in Big Sur, try other RAM and see if that makes a difference. Hopefully this is helpful to anyone encountering this issue in the future.
