### ISSUE TITLE
Infected with MacOS: Agent-QJ?

### ISSUE THREAD

**Issue by fieldwoods** [dortania/OpenCore-Legacy-Patcher#504]
### Machine Model

MacBook4,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

My Avast informed me that "OpenCore-Patcher-GUI.app.zip (ver. 0.2.5)" is infected with MacOS: Agent-QJ, so I quarantined it and gave up using it for a while. Is this a false positive or is it really infected? I will inform you just in case.

**Comment by ironapple0915** [comment]
It’s a false positive.
