### ISSUE TITLE
What WiFi does it support? Can you tell me more about it

### ISSUE THREAD

**Issue by mjs520** [dortania/OpenCore-Legacy-Patcher#505]
### Machine Model

MacBookPro10,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Version 0.2.5 already supports old WiFi support. Can you explain the specific WiFi support? And does this version 0.2.5 update not require full package installation every time? Thank you

**Comment by khronokernel** [comment]
1. BCM94328, BRCM94322 and Atheros, 
2. no
