### ISSUE TITLE
[Bug]: Macbook Pro Trackpad, Magic Trackpad scroll freeze issue

### ISSUE THREAD

**Issue by dhakchianandan** [dortania/OpenCore-Legacy-Patcher#506]
### Machine Model

MacBookPro11,2

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

After upgrading to Monterey beta 7, Experiencing lags while scrolling the webpage/editors using Macbook Pro Trackpad as well as Magic Trackpad Bluetooth. The scroll behaviour freezes for a second or two and then continues scrolling. It's happening frequently.

**Comment by khronokernel** [comment]
Monterey issue
