### ISSUE TITLE
[Bug]: Kepler acceleration does not work even after patching the volume on Monterey beta 7

### ISSUE THREAD

**Issue by lvalenta** [dortania/OpenCore-Legacy-Patcher#507]
### Machine Model

iMac13,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hi,
patching the volume via 0.2.5 release does not bring back the acceleration on Monterey beta 7 for me on iMac 13,1. I have tried to use GUI, TUI, and also the OpenCore-Patcher.command.

The kexts get installed (and when I reinstall, they get removed and installed again), but it still does not work.

**Comment by khronokernel** [comment]
Run `ls /System/Library/Extensions` and send the output

**Comment by lvalenta** [comment]
Thank you for fast response. Tried running even the current main branch to no avail.
[SLE-ls.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7228609/SLE-ls.txt)

**Comment by khronokernel** [comment]
Are you simply building and installing a new OpenCore EFI or are you installing the Post Install Root Volume patches?

**Comment by lvalenta** [comment]
I've done both. EFI is currently on 0.2.5, too. I'd been using Monterey since beta 3 and upgrading ever since. Tried installing again without any change.
![Snímek obrazovky 2021-09-25 v 0 16 33](https://user-images.githubusercontent.com/3748043/134745161-3e82248d-80c4-4c79-9db9-108a12ff8f89.png)

**Comment by khronokernel** [comment]
<img width="637" alt="Screen Shot 2021-09-24 at 4 18 00 PM" src="https://user-images.githubusercontent.com/48863253/134745230-e1ec0519-3388-43d3-9fd9-74faa0d7ae62.png">

Found the issue, looks to be an issue either with our Root Volume detection or this might actually be an APFS bug with Apple. To verify, please run `diskutil apfs list > ~/Desktop/disk-apfs.txt` and `diskutil apfs list > ~/Desktop/disk.txt`. Please upload both

**Comment by lvalenta** [comment]
[disk-apfs.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7228635/disk-apfs.txt)
[disk.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7228636/disk.txt)

**Comment by lvalenta** [comment]
adding "diskutil list" (maybe you wanted that, too):
[diskutilList.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7228641/diskutilList.txt)

**Comment by khronokernel** [comment]
Yeah this seems to be an Apple bug, as based off Apple's own KDK documentation with Build 21A5522h ([KDK Source](https://download.developer.apple.com/macOS/Kernel_Debug_Kit_12_build_21A5522h/Kernel_Debug_Kit_12_build_21A5522h.dmg)) our current mechanism is very much still officially supported.

Additionally seeing as no one else can replicate this issue, even locally with my own personal machines (MacBookPro8,2, MacBookPro9,2 and MacPro5,1), there's little we can do on our end.

If you can replicate on multiple machines (either yours or others), we can look into it however my current recommendation is to either:

* Reinstall Beta 7 (this will retain data)
* Downgrade to Beta 6, re-attempt with Beta 8
* Do further research yourself to understand why `bless` does not believe `disk2s5` is not your root volume

**Comment by lvalenta** [comment]
Hi,
I’ve tried downgrading to beta 6 (works perfectly), clean install, and now beta 8. Still doesn’t work, still the same error.

i may have found out the reason though. Since beta 3 I’m getting the “disk2s5 hash mismatch”. [More here](https://developer.apple.com/forums/thread/684276) everything works and disk utility recovery check also succeeded. Is there any way how to force the patching process to proceed?

**Comment by khronokernel** [comment]
> Is there any way how to force the patching process to proceed?

No, macOS itself is telling you it cannot seal. The OS **itself**, nothing on the patcher's end

**Comment by lvalenta** [comment]
I see. And is there any other way to install it? I.e. using the Kepler patcher itself? https://github.com/chris1111/Geforce-Kepler-patcher

**Comment by khronokernel** [comment]
Everyone uses the exact same OS framework
