### ISSUE TITLE
[Bug]: Macbook 11,3 stuck at Apple Logo after upgrading to MacOS 12 beta 7 or 8

### ISSUE THREAD

**Issue by myonlylonely** [dortania/OpenCore-Legacy-Patcher#508]
### Machine Model

MacBookPro11,3

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

After upgrading to macOS 12 beta 7, it boot stuck at Apple Logo. It can boot into safe mode. My MacBook 11,3 is with GT 750M Nvidia card.

**Comment by myonlylonely** [comment]
I figured it out. I removed Lilu.kext and it just works.

**Comment by myonlylonely** [comment]
I confirmed under macOS 12 beta 6, it does not require removing Lilu.kext to get it worked.

**Comment by donavanbecker** [comment]
@myonlylonely where is the lilu.kext? I have had this issue too…

**Comment by myonlylonely** [comment]
> @myonlylonely where is the lilu.kext? I have had this issue too…

In the EFI volume, /Volumes/efi/EFI/OC/Kexts/. You should mount the EFI volume in another bootable operating system (In my case, I use Windows), you cannot mount it under macOS safe mode. After delete Lilu.kext, and edit the config.plist file to remove Lilu.kext configuration. After that, I can boot into normal mode. Then I enabled Nvidia card kext under open-core, and restart, because I remove Lilu.kext, the sleep is not working, it cannot go into sleep. So I tried to put the Lilu.kext back in the EFI volume, and add the configuration into the config.plist again, and reboot. And it also boot successfully into normal mode! Hope this helps your case.

**Comment by donavanbecker** [comment]
> > @myonlylonely where is the lilu.kext? I have had this issue too…
> 
> 
> 
> In the EFI volume, /Volumes/efi/EFI/OC/Kexts/. You should mount the EFI volume in another bootable operating system (In my case, I use Windows), you cannot mount it under macOS safe mode. After delete Lilu.kext, and edit the config.plist file to remove Lilu.kext configuration. After that, I can boot into normal mode. Then I enabled Nvidia card kext under open-core, and restart, because I remove Lilu.kext, the sleep is not working, it cannot go into sleep. So I tried to put the Lilu.kext back in the EFI volume, and add the configuration into the config.plist again, and reboot. And it also boot successfully into normal mode! Hope this helps your case.

@khronokernel is this something that is wrong with beta 7? Or patcher?

**Comment by donavanbecker** [comment]
@myonlylonely, just FYI if this happens again in beta 8.... I actually did safe mode and then ran the TUI offline and it actually ran a root patch and that allowed me to load into normal mode.

This might save you a few steps... ha

**Comment by myonlylonely** [comment]
> @myonlylonely, just FYI if this happens again in beta 8.... I actually did safe mode and then ran the TUI offline and it actually ran a root patch and that allowed me to load into normal mode.
> 
> 
> 
> This might save you a few steps... ha

So it seems that I am not the only one. I'm going to reopen the issue.

**Comment by myonlylonely** [comment]
> @myonlylonely, just FYI if this happens again in beta 8.... I actually did safe mode and then ran the TUI offline and it actually ran a root patch and that allowed me to load into normal mode.
> 
> 
> 
> This might save you a few steps... ha

confirmed still stuck at apple logo after upgrading to beta 8

**Comment by khronokernel** [comment]
Issue transferred here:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/522
