### ISSUE TITLE
Allow non-generated, orginal machine ids?

### ISSUE THREAD

**Issue by Bmju** [dortania/Opencore-Legacy-Patcher#51]
I was playing around with trying to get non-`macserial`-generated ids (i.e. my machine's orginal ids) when booting through OpenCore. (And latterly pestering the OC developers with some issues, and one _very_ minor accepted codefix, related to looking into this!)

It seems (at least to me) a good idea not to 'burn through' faked ids, and not to require users (at least, users who don't know how to manually change their config!) to fake more than is necessary.

However the current OCLP config does use `macserial`-generated system ids.

Of course, most OC documentation also assumes `macserial`. The reason I understood it was even possible to use the original machine's ids is that @jacklukem's [OpenCoreAPFSLoader](https://github.com/jacklukem/USBOpenCoreAPFSloader/) is already [set up to do this](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/page-179?post=28952250#post-28952250); i.e. OC already supported this. I have been using @jacklukem's OC config (latterly with some minor updates) to pass through my machine ids, with only the product name (e.g. `Mac15,1`) and matching board id (i.e.`Mac-XXXXXXX`) faked, all through the Big Sur beta process, with no problems at all. (Well, not NO problems, but the firmware flashing problem is completely unrelated to this and now fixed!)

After playing around with @jacklukem's config and also looking at how this part of OC works, then on OC 0.6.6 the following `<PlatformInfo>` config section (**EDIT#1** edited to reflect the comments by @vit9696 below) achieves this (I'm including this for the record, and to reflect my understanding that it wouldn't be that hard to do; also, in case anybody else wants to modify their config based off this section for now):

```
        <key>PlatformInfo</key>
        <dict>
            <key>Automatic</key>
            <true/>
            <key>CustomMemory</key>
            <false/>
            <key>Generic</key>
            <dict>
                <key>AdviseWindows</key>
                <false/>
                <key>MaxBIOSVersion</key>
                <true/>
                <key>MLB</key>
                <string></string>
                <key>ProcessorType</key>
                <integer>0</integer>
                <key>ROM</key>
                <data></data>
                <key>SpoofVendor</key>
                <false/>
                <key>SystemMemoryStatus</key>
                <string>Auto</string>
                <key>SystemProductName</key>
                <string>iMac15,1</string>
                <key>SystemSerialNumber</key>
                <string></string>
                <key>SystemUUID</key>
                <string></string>
            </dict>
            <key>UpdateDataHub</key>
            <false/>
            <key>UpdateNVRAM</key>
            <false/>
            <key>UpdateSMBIOS</key>
            <true/>
            <key>UpdateSMBIOSMode</key>
            <string>Create</string>
        </dict>
```

@BenSova @vit9696 @khronokernel

**Comment by vit9696** [comment]
This config violates OpenCore configuration requirements. You must not omit any field, this is not allowed. Therefore both before and now you should explicitly pass empty options. The only thing that got changed in 0.6.6 is the abandonment on not so adequate failsafe values, but this only applied to incorrect configurations like yours.

**Comment by Bmju** [comment]
Apologies - I have updated to include full, explicit config.

**Comment by Bmju** [comment]
Apologies for adopting the 'missing config values' approach which unfortunately is fairly widespread around the web it seems, including some of the stuff I was looking at to get started on this. (That said, the wording around the optional/compulsory requirements for these specific `PlatformInfo` sections of the OC config was at least arguably a bit hard to read - it seems like I wasn't the only person to think so, as per linked issue above - and has now been updated in the OC docs, so that's all to the good too; and may perhaps explain why specifically this section had some incorrect missing config in it, not just in my config file...)

Anyway, now edited and fixed to follow the long-standing requirement to include all settings, in order to have a supported config, in my issue post above.

If that issue is (hopefully!) not enough to put you off, then I would be very happy to discuss further with a view to doing a PR myself, if there's any interest in this? (Happy to also go onto any suggested channel, if better to thrash out any issues?)

**Comment by dhinakg** [comment]
We don't believe changing the model identifier without changing the serial should be done, as it does have the possibility to mess up iCloud services when a new computer appears with the same serial. Using the current ROM should be fine but unless if you have any evidence to the contrary, we think we should stick with generating the serial and board serial.

**Comment by Bmju** [comment]
Okay, thanks for the response!

I felt that I'd rather continue on with my existing system ids, because:

1. I want my Bootcamp Windows to not think I'm on a different machine; which depends on system uuid, if I've understood correctly.
1. I was also assuming that keeping the same system uuid, system serial number and board serial number would be better for me for with Apple software (e.g. iCloud, iMessage, FaceTime), by also not making it think I had changed machines.

jackluke's booter which I referred to never did fake those ids, and as far as I know has been used by multiple people without any reports of iCloud problems.

If you had the time, I would be very interested in any quick links you could recommend to anything good explaining the real issues here. In the end, you guys have worked on this stuff much longer than I have, so if that's your decision, I totally respect that it represents a lot of established research on this.

Also, yes, I was trying to gather actual evidence either way on this - so if I get anything substantive, I will get back to you! Thanks.

**Comment by Bmju** [comment]
@dhinakg I've done some more research. I can reliably cause the below, and then fix it again! :)

<img width="372" alt="Screenshot 2021-02-03 at 09 03 18" src="https://user-images.githubusercontent.com/25643187/106921969-70818a80-6704-11eb-8ced-99d233e9c1ac.png">

TL/DR: It depends only and 100% on whether the values for system-id and SystemSerialNumber change in the Data Hub:

<img width="595" alt="Screenshot 2021-02-03 at 11 48 22" src="https://user-images.githubusercontent.com/25643187/106922472-01586600-6705-11eb-8017-dee385653904.png">

These can be viewed using IORegistryExplorer at path `IODeviceTree:/efi/platform`.

Now there are some wrinkles. `UpdateDataHub` _does not update these_ unless `ProtocolOverrides/DataHub` = `true` is also set! (https://github.com/acidanthera/bugtracker/issues/1468)

Therefore (I believe!) the existing OCLP config is not giving anybody any problems because it is not setting these - the ids which matter are being left as the original ones!

If you want to truly set the machine to be a new machine, you need to apply that setting - but as soon as I did this, I started immediately getting iCloud problems (as per the image at the top); but only if the Data Hub system-id or SystemSerialNumber either change fro my original (or are missing, which is possible with a misconfigured OC); and no problems at all - even with that OC setting - as long as these two values, only, are unchanged. Note that I have been running OpenCoreAPFSLoader with various different platform names (my real `MacBookPro10,2` when not booting via OC, but also `MacBookPro11,1` and `iMac15,1` when booting via OC) frequently, for months, with no problems at all with all my iCloud services. I have also been using OCLP what has effectively been changing everything else _except_ these two values, again with no problems at all! But as soon as I change the system-id or SystemSerialNumber in the Data Hub, the Mac complains within seconds of login.

**Comment by Bmju** [comment]
OCLP is an excellent project, it summarises and automates a lot of knowledge that I don't have, about how to configure OC to apply all the patches, kexts, etc. necessary to run Big Sur on multiple different unsupported Macs.

Reason for this issue, then? I'd like to have:

<img width="393" alt="Screenshot 2021-02-06 at 19 16 49" src="https://user-images.githubusercontent.com/25643187/107140740-14914e80-691c-11eb-8d8e-b30c332de39f.png">

This is a screen shot from https://appleid.apple.com/account/manage and it's my Mac, with my serial number. It is an unsupported (late 2012 13" retina display) MacBookPro10,2, with Apple perfectly happy to register it as running Big Sur when it's faked as MacBookPro11,1; and I've also used iMac15,1; and I've also regularly swapped between both of them and also to running with no OC, therefore MacBookPro10,2, when I'm not fetching updates; all with no iCloud account problems at all!

Personally, I prefer the config I put in the first post in this issue: let OC auto-detect my IDs, only update SMBIOS (not Data Hub and not NVRAM) with the faked product name (and matching faked board product id Mac-XXXX which OC lloks up internally for you), since that is all that is needed to allow Big Sur updates to come through.

For reasons mentioned above, I'm not convinced that the current settings in OCLP are a great resting place (tell me I'm wrong, but it looks like a partial fake, with the bits that really matter not faked). Also, for reasons mentioned above, I'm not sure that changing OCLP for actually overwrite the Data Hub (thereby truly making people's machines look like new machines) is a great idea, either (since you'd suddenly get a load of users saying "why am I having problems with my iCloud subscription?"!). Really, I'd have thought most users would prefer the same result I've tried to summarise in the screenshot above (basically: my iCloud account just continues to work, and it thinks I'm on the same machine I always was), if there are no problems with doing that; and I tried to present evidence that there are no problems!

Of course, OCLP actually already does allow this, but I am trying to argue it could do it much more cleanly, and without faking any IDs. And that that's a preferable route to more fully faking the machine IDs. (And, really, to leaving things as they are, for reasons as above, IMHO.)

Thanks.

**Comment by startergo** [comment]
> We don't believe changing the model identifier without changing the serial should be done, as it does have the possibility to mess up iCloud services when a new computer appears with the same serial. Using the current ROM should be fine but unless if you have any evidence to the contrary, we think we should stick with generating the serial and board serial.

```
-----------------------------------------------------------------------
System Info
-----------------------------------------------------------------------
Host                           Big-Sur.lan
OS                              Version 11.3 (Build 20E5172i)
Kernel                         Darwin 20.4.0 x86_64
RAM                            128.00 GB
Model Identifier               MacPro5,1
CPU                            Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
Intel Generation               ???
Platform ID                    0x00000000
Board ID                       Mac-7BA5B2D9E42DDD94
FW Version                     9999.0.0.0.0
Serial Number                  
Hardware UUID                  
System ID                      
ROM                            
Board Serial Number            
VDA Decoder                    Fully Supported
```
As you can see changing only the board-id still identifies the Mac model properly so there is no chance of duplicating the SN.
As far as the iMessage keys are concerned the first column remains unchanged and the 3rd row of the second column is different. Apple servers so far accepted this setup.

**Comment by Bmju** [comment]
I just wanted to add a note confirming that the basic ability to get OEM specified values using the generic section is not new in OC 0.6.6. It was just made more clear that it was available, and a rather confusing difference in behaviour between missing and empty values was removed.

The relevant changes to OC, and a discussion of the before and after behaviour, is [here]().

**Comment by Bmju** [comment]
@startergo - I'm rather arguing that changing board id and board name is also not a 'significant' change to the machine's identity - i.e. not one that causes any problems while continuing to use the original serials. I agree that changing just the board-id and not the matching board product name works too. (The main difference being that changing just the board-id requires using `SMBIOS` with Automatic=false, instead of `Generic` with Automatic=true.) And I absolutely agree that the ongoing success, with no problems at all, of the [project](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/) I understand you are involved in, and quoting evidence from (one of the projects linked off the home page of OpenCore, no less!) is more evidence that there is no problem at all with only faking one or both of these bits, and nothing else.

**Comment by Bmju** [comment]
@dhinakg Were there any updates at all, on this?

**Comment by Bmju** [comment]
Update: Thank you for the like, @khronokernel.

To my understanding, there is now an even more preferable 'light spoofing' technique, taking advantage of https://github.com/acidanthera/OpenCorePkg/pull/215 .

This is the approach developed (and used for ages, on lots of machines) by @cdf, [here](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/).

It uses `Automatic=false`, `UpgradeSMBIOS=true`, and in `SMBIOS`:

```
        <key>SMBIOS</key>
        <dict>
            ... all fully specified failsafe values here, except for: ...
            <key>BIOSVersion</key>
            <string>9999.999.999.999.999</string>
            <key>BoardProduct</key>
            <string>{OCLP-generated-as-closest-match-to-real-machine}</string>
        </dict>
```

Possible advantages of @cdf method over @jacklukem method include:
 - All SMBIOS entries are auto-detected and read from actual OEM values, not looked up by OC in its Mac model database for an almost-but-not-quite matching machine
 - Arguably v. minor, but there is no user accessible screen which even shows a changed model name (to the user, it's just still their machine)
 - This is even more extensively tested (i.e. used, by real users) than the @jacklukem method to not cause any problems with Apple and iCloud accounts

**Comment by khronokernel** [comment]
> Were there any updates at all, on this?

Oh apologies, I thought I replied to this thread already.

So yeah, you've swayed our decision on the serials issue. So our current plans:

1. Merge the py3 rewrite into main (Dhinak's leading this project)
2. Rebuild how the USB-Map.kext works(ie. no longer specific maps, one large map where we replace specific sections. Allows for easier maintainability as macOS 12 releases with likely more SMBIOS dropped)
3. Rebuild the serial section to allow for both original and custom serials for those who desire(by default use original serials)
4. Figure out whatever this issue with AppleALC is on legacy Macs and eventually add to patcher(For some users it works, however for most it breaks sleep?)

As you mentioned, we're currently leaning towards cdf's method as there's been more successes with this. Timeline for this is rough and subject to change, so don't want to make any promises for when this will happen

**Comment by Bmju** [comment]
PS In terms of actual real-world differences:

   - SMBIOS copy of FirmwareFeatures flags (as read in-OS e.g. by `dmidecode`) normally do change slightly (so presumably, become slightly wrong) when using `Generic` section spoofing; but stay at OEM installed values when using `SMBIOS` section spoofing, as above, in 0.6.7 onwards
   - Similar points apply to the other SMBIOS tables now cloned from Apple OEM tables in 0.6.7 up when using failsafe values in the `SMBIOS` section (but _not_ if using the `Generic` section)

**Comment by Bmju** [comment]
Thanks!

> Rebuild the serial section to allow for both original and custom serials for those who desire (by default use original serials)

FWIW Will you also change to doing 'all the way to Data Hub' spoofing for the custom serials option? (Am referring to other points I made above - so hope the q. makes sense!)

**Comment by khronokernel** [comment]
> Now there are some wrinkles. UpdateDataHub does not update these unless ProtocolOverrides/DataHub = true is also set! (acidanthera/bugtracker#1468)
> But as soon as I change the system-id or SystemSerialNumber in the Data Hub, the Mac complains within seconds of login.

These 2 points? Hrrmm, that's actually a good question. Since custom serials will no longer be default, we may just have the user decide the majority of settings themselves on what they prefer. Could add a note explaining the tradeoffs of DateHub

**Comment by Bmju** [comment]
NB there are also other [new changes](https://github.com/acidanthera/OpenCorePkg/commit/f3502e7336784ed194b7c423c0881d5366b4d346) in OC to support this working better, too. 😊

Previously, some values got dropped when using `ProtocolOverrides/DataHub=true` (for valid, but hard to understand reasons). These are now work-roundable by using specifically added now `"OEM"` special string values (i.e. not an empty string, but specifically the string `OEM`) in the `Generic` section for certain of these.

The problem with not doing `ProtocolOverrides/DataHub=true` - it is the point I was making above - is that the one bit of the system (the relevant values in the Data Hub section) that really seems to matter to iCloud accounts is the one bit *that is not spoofed at all* without using `ProtocolOverrides/DataHub=true`.

This is a highly misleading situation, where everything you can see looks like you have a thoroughly spoofed machine, but it is only causing no problems at all with iCloud or Apple accounts (i.e. it does not look like a new machine), because hidden away, the very things that matter are not spoofed! Without wanting to put too fine a point on it - I do think that that is very borked!

**Comment by Bmju** [comment]
I do think that the best (and understandable,  not misleading) user experience is either @cdf light spoofing, or full all-the-way-to-data-hub (and using the new OEM detection features) heavy spoofing!

**Comment by Bmju** [comment]
(Forget the new "OEM" special string features - bah! head is spinning now! - as these are only needed for successful all-the-way-to-data-hub when NOT spoofing some part of the IDs. Which is exactly not the case. Sorry! But the reast, that you really should use all-way-to-data-hub spoofing for full spoofing, still applies! Thanks!)

**Comment by Bmju** [comment]
All this means is, you should turn on `ProtocolOverrides/DataHub` when doing all ids spoofing - though when you do, everyone is perhaps not going to want to use it, because the machine will be a new machine on iCloud/Apple accounts. But that is - I hope you will agree - as it _should_ be, in this case!

**Comment by MikeBeaton** [comment]
Apple's IORegistryExplorer tool, from Xcode Additional tools, open IODeviceTree section, and navigate to path  IODeviceTree:/efi/platform to view the (very well hidden) values that I am making such a fuss about.

**Comment by Bmju** [comment]
Apple's IORegistryExplorer tool, from Xcode Additional tools, open IODeviceTree section, and navigate to path  IODeviceTree:/efi/platform to view the (very well hidden) values that I am making such a fuss about.

**Comment by Bmju** [comment]
@khronokernel - Please, could you check, with the tool above, on a full spoof, current, normal OCLP config, and see if you see what I am seeing? That the spoof does not go to those values.

And then with the exact same config.plist, only change `ProtocolOverrides/DataHub` to `true`, and test again. And you will see that the relevant values finally change. And that iCloud starts complaining! (Which it *should* be doing, if the spoof is full.)

(Also: Many, many thanks for agreeing to shift already on what is the main point around here - especially in considering it as the new default. Thank you again, for that! And for the invaluable work going on here!)

**Comment by Bmju** [comment]
@khronokernel - I've just realised something important to mention:

 - This would never have been an issue on non-Apple hardware!

Therefore, I am NOT claiming (which I agree would be impossible) that a method for faking all the serial numbers, which you have used for years on non-Apple hardware, never worked!

I am though, claiming that the same method, if intended to fake all the IDs completely, everywhere, would have never worked on Apple hardware, for reasons as confirmed by @vit9696 [here](https://github.com/acidanthera/bugtracker/issues/1468#issuecomment-772364877), and with very non-obvious implications within OC, for Apple hardware only, discussed [here](https://github.com/acidanthera/bugtracker/issues/1468) and [here](https://github.com/acidanthera/bugtracker/issues/1469).

**Comment by Bmju** [comment]
> Since custom serials will no longer be default, we may just have the user decide the majority of settings themselves on what they prefer. Could add a note explaining the tradeoffs of DateHub

So - on re-reading - I think you _may_ just be saying 'yes'. Point acknowledged?

But I really do want to clarify, and could do with a thumbs up on:

1. `UpdateDataHub=true` _without_ `ProtocolOverrides/DataHub=true` is basically pointless (does effectively nothing, is highly misleading) _on Apple hardware_.

I think that would lead naturally to 2) it makes no sense to continue to offer `UpdateDataHub=true` without `ProtocolOverrides/DataHub=true` as an option, within a tool aimed at the customise-usefully-for-the-user level of OCLP (always with `ProtocolOverrides/DataHub=true`, if it's on at all, is fine of course!); and really then, also, to 3) as I said above:

>I do think that the best (and understandable, not misleading) user experience would be to just offer @cdf style light spoofing and full all-the-way-to-data-hub heavy spoofing!

But I'm just looking for any thumbs up confirming 1...!

@khronokernel @dhinakg 🙏 

Thank you.

**Comment by khronokernel** [comment]
https://github.com/dortania/Opencore-Legacy-Patcher/releases/tag/0.0.11
