### ISSUE TITLE
[Bug]: Your computer has detected a potential problem: eficheck.dump

### ISSUE THREAD

**Issue by pointum** [dortania/OpenCore-Legacy-Patcher#511]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Got a macOS alert message (not full screen) that says “Your computer has detected a potential problem“. And it opens a folder in Finder with `eficheck.dump` file.

~~I suppose it’s because `MacBookPro11,3` now requires patching - #498.~~

$ /usr/libexec/firmwarecheckers/eficheck/eficheck  --integrity-check:
```
EFI Version: MBP112.88Z.F000.B00.2106131836  (Boot ROM Version: 431.140.6.0.0)
Matching allowlist not found in EFIAllowListShipping. Searching in EFIAllowListAll.
Fetching allowlist data update.
Waiting for allowlist data download to complete.
Downloadable allowlist data update is already present on system or cannot be found on server.
Primary allowlist version match not found for version MBP112.88Z.F000.B00.2106131836  (Boot ROM Version: 431.140.6.0.0).
```

System Profiler > Hardware Overview shows:

>   Model Name:	MacBook Pro
>   Model Identifier:	MacBookPro11,3
> ...
>   System Firmware Version:	9999.999.999.999.999
>   SMC Version (system):	9.9999

The firmware version is (as one might expect) not present in Monterey `EFIAllowListShipping.bundle`.

But if I check against Big Sur allow list, the firmware is OK:

$ ./eficheck --integrity-check -h /Volumes/BigSur/usr/libexec/firmwarecheckers/eficheck/EFIAllowListShipping.bundle/allowlists/MBP112.88Z.F000.B00.2106131836.0.ealf

    EFI Version: MBP112.88Z.F000.B00.2106131836  (Boot ROM Version: 431.140.6.0.0)
    Primary allowlist version match found. No changes detected in primary hashes.

Maybe there’s some relevant ignore list that should be updated for `eficheck`?
Or patch Monterey to include firmware info in `EFIAllowListShipping.bundle` from Big Sur?

**Comment by khronokernel** [comment]
Purely cosmetic, due to board ID and BIOS version spoofing

**Comment by pointum** [comment]
No problem, thank you. Might be confusing for some users. May be they’ll find this issue.
