### ISSUE TITLE
BUG Volume slider and screen brightness slider in quick settings menu 

### ISSUE THREAD

**Issue by Goadude** [dortania/OpenCore-Legacy-Patcher#512]
### Machine Model

MacBook7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Display slider and volume slider do not display properly when I press the 2 slider icon in top bar menu 

![Schermafbeelding 2021-09-26 om 12 54 12](https://user-images.githubusercontent.com/91414709/134804799-af917bc4-e51e-475e-bf91-9a9754b45036.png)
.

**Comment by razev027** [comment]
same happen to me. anyone fix this problem then give us solution.

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
