### ISSUE TITLE
[Feature Request]: Restore Instant GPU Switching on MacBook Pro Mid 2009 (MacBookPro5,2)

### ISSUE THREAD

**Issue by HackintoshHD** [dortania/OpenCore-Legacy-Patcher#514]
### Machine Model

MacBookPro5,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I've discovered that the "Instant GPU Switching" / "GPU Switching on the fly" feature of the MacBook Pro Mid 2009 (i.e. the ability to switch between the integrated nVidia GeForce 9400M and the discrete nVidia GeForce 9600M GT instantly without a logoff), that is broken since macOS 10.13.0 High Sierra, can be restored at least under High Sierra and Mojave by replacing

/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleMuxControl.kext

version 3.14.52b52 from macOS 10.12.6 Sierra's Security Update 2019-005 ([download](https://swcdn.apple.com/content/downloads/55/63/061-41803-A_87X0EHD65R/gt50wt0ye0twqkj227l9g7vw2ok4nl72a6/SecUpd2019-005Sierra.pkg), [more details on the necessary steps](https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/page-786?post=30351187#post-30351187)).

At this point, my knowledge on Catalina's and Big Sur's rootless system partition and the modification of kernel extensions is not sufficient to test this modification on Catalina rsp. Big Sur using OpenCore Legacy Patcher. Nonetheless, I'd be more than happy if other MacBookPro5,2 owners would be willing to test the scenario and - in case the result is positive - if the modification could be integrated into OpenCore Legacy Patcher.

Thank you all!

**Comment by kauniss** [comment]
I've got a MBP6,2 (mid 2010). Is this something I can help with, as I've also got the GPU switch issue? 
How do you do this instant GPU switching?

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/61281f597adafc25298ef3a9ab8797197c24f391

**Comment by HackintoshHD** [comment]
Thank you. I'll test the outcome of your commit once it's in the nightlies.

**Comment by HackintoshHD** [comment]
For reasons unknown to me, the OCLP 0.3.0 nightlies I've tested have installed AppleMuxControl.kext **version 3.14.49 from 2017** - at least on my MBP5,2's Big Sur 11.6 installation (please correct me if I'm wrong), which lead to the same results reported in issue #584 (boot freeze with black screen). However, for restoring the Instant GPU Switching feature under High Sierra and Mojave, I've successfully used **AppleMuxControl.kext version 3.14.52b52** that can be extracted from **Sierra's last Security Update 2019-005** (cf. [my post](https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/page-786?post=30351187#post-30351187) for details).

Now - **Caveat** - as already documented in the post, I frankly still don't know whether or not AppleMuxControl.kext version 3.14.52b52 would boot on Catalina, Big Sur and Monterey, as I'm not yet running them on my MBP5,2 and I'm unfortunately not yet familiar with the sealed / signed system partition mechanism and how I could integrate AppleMuxControl.kext into AppleGraphicsControl.kext on such a protected environment.

But maybe it would be worth to test the specific kext version 3.14.52b52 that's known to work under High Sierra and Mojave?

If the OCLP developers would be willing to provide an OCLP build that's using AppleMuxControl.kext version 3.14.52b52 from Sierra's Security Update 2019-005, I'd be more than happy to test it on my MBP5,2.
