### ISSUE TITLE
Does WiFi patch support atheros9485 WiFi

### ISSUE THREAD

**Issue by mjs520** [dortania/OpenCore-Legacy-Patcher#515]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Can I drive atheros9485 WiFi under Monterey 12

**Comment by khronokernel** [comment]
No
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/Resources/PCIIDArray.py#L964-L972
