### ISSUE TITLE
[Bug]: No Diasabling thunderbolt controller option available

### ISSUE THREAD

**Issue by k0017** [dortania/OpenCore-Legacy-Patcher#517]
### Machine Model

MacBookPro11,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

on my MacBookPro11,2 it doesn't matter if oc is already installed or not, there is no option to disable thunderbolt controller. It is automatically done, but it should be better an option to disable the thunderbolt controller. Not all Machines are faulty and the thunderbolt port then shouldn't be disabled.

**Comment by slick-randall71** [comment]
He is using the GUI version, not the terminal version

**Comment by khronokernel** [comment]
TUI and GUI are not settings synced to not overload new users with too many options. Seeing as that was the issue, closing

**Comment by k0017** [comment]
Thanks, I didn't know, that this isn't available in the GUI Version.
