### ISSUE TITLE
[Bug]: High CPU usage (Spotlight)

### ISSUE THREAD

**Issue by newfylox** [dortania/OpenCore-Legacy-Patcher#518]
### Machine Model

MacBookPro8,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Hi guys, not really sure if it's related with your awesome patcher, but sometimes my old MacBook Pro 2011 8,3 goes crazy on heavy CPU usage, making my computer very hot (where the CPU is located) and having my fan always spinning.

When looking at Activity Monitor, I saw that "Spotlight" were causing the problem, using 150% CPU usage without finishing. I had to kill the process and now it works. But it can come back later.

Of course my computer is old and a non-metal GPU, but I don't understand how my Intel Graphics would be the cause of Spotlight heavy usage.

### Any Additional Information

I don't know if it can help but mainly I'm using XCode and Simulator. I have plenty of RAM.

**Comment by khronokernel** [comment]
OS needs indexing and you have a 10 year old machine, high CPU usage is normal until Spotlight finishes indexing
