### ISSUE TITLE
[Bug]: Macbook Pro (15inch, mid 2010)

### ISSUE THREAD

**Issue by kyawsoekhaing** [dortania/OpenCore-Legacy-Patcher#519]
### Machine Model

MacBookPro6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in), Other/Non-Applicable

### What is the Isssue?

I have used Legacy patcher 0.2.5
i can't apply system volume patch
after I applied, keep looping at the login screen.

i can't apply software update either,
after applied , can't boot .

**Comment by khronokernel** [comment]
Use forums for basic troubleshooting, issues tab should be dedicated for more formatted issues
