### ISSUE TITLE
Macbook Pro 6,2 GPU switch issue apparently fixed on OCLP

### ISSUE THREAD

**Issue by kauniss** [dortania/OpenCore-Legacy-Patcher#520]
### Machine Model

MacBookPro6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Issue: MacbookPro6,2 (mid 2010) as we all know, occasionally crashes during GPU switching. As far as I know the best way currently to address this issue with an OCLP Big Sur system, appears to be some kind of combo installation of JackLuke's BigSurBaseSystemFix from his [Big Sur Fixes repository](https://github.com/jacklukem/BigSurfixes), and OCLP, [like so](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/page-455?post=30307771#post-30307771).

Solution: Jack was kind enough to [provide me](https://github.com/jacklukem/BigSurfixes/issues/13#issuecomment-929921902) the kext he used in his BigSurBaseSystemFix for the GPU switch issue, so I could try to replace the particular kext in the OCLP Big Sur EFI, using MountEfi. I did so, restarted and after subjecting my old MacbookPro6,2 to all manners of stress tests, I can happily report that GPU switch crashes appear to have stopped.

**Comment by khronokernel** [comment]
Ah thank you for opening the issue, I had originally planned to implement this but had forgotten. The exact issue is mainly power stepping related, and is resolved when you configure the G-States to never increase to the maximum level.

The author of this fix is fabioroberto and he's documented this previously:
* https://github.com/fabioiop/MBP-2010-GPU-Panic-fix

Will close this issue when implemented

**Comment by kauniss** [comment]
What happened re this implementation? 
In the subsequent release (0.3.1 I believe) it was still necessary for me to mount the EFI and specifically replace the kext (named ‘AGPM-Overwrite’, provided by Jack, as described above). Now, as I installed 0.3.3, after going through all the post-installation patches as usual, my MacbookPro6,2 crashed - and to my surprise it appears I can no longer replace the kext file in the EFI partition (it’s removed altogether)?

Grateful for help
