### ISSUE TITLE
[Bug]: Privacy settings for Microphone and camera showns no entry

### ISSUE THREAD

**Issue by peet1979** [dortania/OpenCore-Legacy-Patcher#521]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hello! Can you help me pls what to do: the microphone and camera privacy settings doesn't show any entry, which applications would like to access camera and microphone.
I've read something in relation with SIP. Can it be enabled if I use OpenCore Patch?
Thank you in advance,
Peter

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html

**Comment by peet1979** [comment]
Thank you for your reply. I've upgraded to Big Sur 11.6 and patched with the newest 0.2.5 TUI app, but it didn't help. I cannot see any entry in the list (lock icon on the left bottom side is opened of course). Any other solution? I've read about tccplus. But I don't know how to install it. Thank you for your help in advance.
