### ISSUE TITLE
[Bug]:  Menu bar causes iMac to Crash, brought to login screen

### ISSUE THREAD

**Issue by Teehee69784** [dortania/OpenCore-Legacy-Patcher#523]
### Machine Model

iMac10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Whenever you click anything on the menu bar, it freezes and then followed by the screen going black, after about 7 seconds you are back to the login page, The macOS version is macOS Monterey beta 8.  This happened after patching the mac with the latest available patches, using the latest GUI Opencore version

I hope you can resolve it!

**Comment by galluslongus** [comment]
same here on MacPro5,1 on BigSur

**Comment by khronokernel** [comment]
Cannot replicate within our team, feel free to troubleshoot further on forums
