### ISSUE TITLE
[Bug]: iMac 15.1 hangs in the middle of the boot after auto-updating to Monterey B8

### ISSUE THREAD

**Issue by VKondakoff** [dortania/OpenCore-Legacy-Patcher#524]
### Machine Model

iMac15,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

Hello!

iMac 15.1 start to hangs in the middle of the boot after auto-updating to Monterey B8:

![IMG_2577](https://user-images.githubusercontent.com/230824/135471571-95ac67a4-beb2-40c8-89ac-984cbc7a1711.JPG)

Here is what I see if I enable verbose mode:
![IMG_2576](https://user-images.githubusercontent.com/230824/135471354-a4c4d793-0a8d-4a42-83eb-7915ff8b84a3.JPG)

![IMG_2575](https://user-images.githubusercontent.com/230824/135471498-4372877b-d787-458b-9830-48c71c92151a.JPG)

![IMG_2574](https://user-images.githubusercontent.com/230824/135471536-22beda82-85a7-4aca-b662-fd6bd4c6d4a6.JPG)

What can I do to fix this? Any glues? There was no such an issue with the previous Monterey betas.
Thanks a lot.

### Any Additional Information

I was trying to enable debug mode to find a log in the EFI Partition, but was unable to find the log (maybe it is not created if the boot was not successful?

**Comment by smoothit76** [comment]
I have this issue too with latest nightly and autoupdate to Monterey B8 on iMac15,1. Without verbose mode eventually the monitor goes to sleep and waking it up just brings up a blank screen rather than the progress screen. Also before it gets to the point where it essentially hangs, the screen flickers/glitches two or three times with another apple logo to the left of the main apple logo if that helps.

**Comment by khronokernel** [comment]
Display bug with Thunderbolt based Macs in Beta 8, issue seen with natively supported machines as well. Revert to Beta 7 or wait for Apple to resolve in newer betas
