### ISSUE TITLE
[Bug]: Wrong AGPM Enabler kext generated for my AMD RX 580 GPU

### ISSUE THREAD

**Issue by MacNB** [dortania/OpenCore-Legacy-Patcher#525]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 10.15, Catalina

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

**Wrong AGPM Enabler kext generated for my AMD RX 580 GPU.**
When selecting Build OpenCore from the TUI menu, I see:
`- Adding AppleGraphicsPowerManagement Override
- Found dGPU (1): 1002:67DF
- Failed to find Device path for dGPU 1`

The generated EFI boots fine. The generated Injector kext (AGPM-Override.kext) has info.plist with **NVIDIA** GPU overrides and not AMD. That is, it has:
![Screenshot 2021-09-30 at 16 55 22](https://user-images.githubusercontent.com/3777537/135490020-1a8b18a5-6689-44e0-9ed4-2946ad58252b.png)

Replacing that AGPM-Override.kext with RadeonBoost.kext solves the problem:
![Screenshot 2021-09-30 at 17 00 38](https://user-images.githubusercontent.com/3777537/135490612-d7a6c8ff-256e-4bba-9adc-00739311f6e2.png)

### Any Additional Information

The MacPro already had OpenCore installed via Martin Lo's package [here](https://forums.macrumors.com/attachments/0-7-3-v2-zip.1850373/).
It booted fine and I then ran OCLP to generated a new EFI and installed that OVER the existing EFI.

So, the questions are:
1. Why does OCLP not detect the device path of the dGPU ?
2. Also, if OCLP found dGPU **1002:67DF** then, can that **Ven-ID:Dev-ID** be used instead to generate the correct AGPM Injector kext ?

Here's a the output of the build process:

`Building Configuration on model: MacPro5,1
Created build folder

- Adding OpenCore v0.7.3 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.6
- Adding WhateverGreen.kext 1.5.3
- Adding RestrictEvents.kext 1.0.5
- Adding SMC-Spoof.kext 1.0.0
- Adding AppleMCEReporterDisabler.kext 1.0.0
- Adding CPUFriend.kext 1.2.4
- Adding AppleALC.kext 1.6.3
- Adding FeatureUnlock.kext 1.0.3
- Adding SurPlus Patch for Race Condition
- Fixing PCIe Storage Controller (1) reporting
- Fixing PCIe Storage Controller (2) reporting
- Found 3rd Party NVMe SSD (1): 1987:5012
- Found NVMe (0) at PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)
- Adding NVMeFix.kext 1.0.9
- Found Wireless Device 168C:30
- Adding corecaptureElCap.kext 1.0.1
- Adding IO80211ElCap.kext 2.0.0
- Adding AppleGraphicsPowerManagement Override
- Found dGPU (1): 1002:67DF
- Failed to find Device path for dGPU 1
- Adding Mac Pro, Xserve DRM patches
- Falling back to boot-args
- Fixing Legacy Bluetooth for macOS Monterey
- Adding BlueToolFixup.kext 2.6.1
- Adding Bluetooth-Spoof.kext 1.0.0
- Adding OpenCanopy GUI
- Adding ExFatDxeLegacy.efi
- Adding SATA Hibernation Patch
- Enabling ShowPicker
- Disabling SIP
- Disabling SecureBootModel
- Adding bootmgfw.efi BlessOverride
- Allowing FileVault on Root Patched systems
- Setting macOS Monterey Supported SMBIOS
- Using Model ID: MacPro7,1
- Using Board ID: Mac-27AD2F918AE68F61
- Using Minimal SMBIOS patching
- Setting Firmware Feature: 8e01c5403
- Cleaning up files

Your OpenCore EFI for MacPro5,1 has been built at:
    /private/var/folders/61/5b228j294l5_p5fpr9fq4nzm0000gn/T/_MEIRiKh7A/Build-Folder/OpenCore-Build

Press [Enter] to go back.`

**Comment by khronokernel** [comment]
AGPM kext is hardware agnostic, it's simply back porting with correct board ID. Has no relevance to hardware detected other than the model itself
> Also, if OCLP found dGPU 1002:67DF then, can that Ven-ID:Dev-ID be used instead to generate the correct AGPM Injector kext ?

You'd need to reverse and write your own AGPM kext then. Far outside the scope of OCLP, for quite little benefit. AGPM mainly benefits mobile devices with constrained temperatures

**Comment by MacNB** [comment]
Thanks for the quick reply.
What is the point of generating and loading the AGPM kext (on a MacPro) that does not have an NVIDIA GPU and so does nothing ?
Was the choice of the Nvidia based on "standard" MacPro configuration rather than what's actually installed ?
For that matter, is there any point in having that kext other than on mobile devices ?
