### ISSUE TITLE
[Compatibility]: 

### ISSUE THREAD

**Issue by kjaychow** [dortania/OpenCore-Legacy-Patcher#527]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 10.11, El Capitan

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Apple Mac Pro "Quad Core" 2.66 (Original) Specs
Identifiers: Mac Pro - MA356LL/A - MacPro1,1* - A1186 - 2113
Year: 2006
https://everymac.com/systems/apple/mac_pro/specs/mac-pro-quad-2.66-specs.html

Upgrade: ATI Radeon HD 5770
OS: El Capitan 10.11.6
(Pikified with pikify3.1: https://forums.macrumors.com/threads/os-x-el-capitan-on-unsupported-macs.1889851/)

Can I install OpenCore Legacy Patcher with macOS Monterey?

**Comment by khronokernel** [comment]
All discussed in our documentation
