### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by soffianmac** [dortania/OpenCore-Legacy-Patcher#529]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

my camera and microphone cannot be use in MS Teams but the green camera light is on. i tried it with Zoom dan Facetime its ok.. i tried to check on the Security and Privacy Setting under > Privacy > Camera and Micrphone, to enable it, but there is no Teams App listed. How can i fix this?

**Comment by larsvonhier** [comment]
Use the tool TCCPlus to set the appropriate permissions for those apps that do not show up under system settings / privacy.

**Comment by soffianmac** [comment]
Thank you very much.. i tried the tool for 3 times and finally my camera and mic works in MS Teams. Thanks again.
