### ISSUE TITLE
generated plist .... OpenCore 0.6.6 .. LauncherOption is not set !? EFI-Protection won't work?

### ISSUE THREAD

**Issue by stschulze1972** [dortania/Opencore-Legacy-Patcher#53]
!--OpenCore 0.6.4 config--

plist shows the above ....i have generated 0.6.6 OC with MacPro 5.1 and MAcBookPro9.2 ...same time ...same "" 

now i confused, if the plist-file contains the 0.6.6 code ....

**Comment by Ausdauersportler** [comment]
This is a comment line below the header of the file - this does not matter. The OC package is 0.6.6 and the config file fits to it. If you feel better you can edit and change it to 0.6.6 :-)

**Comment by stschulze1972** [comment]
mmmhhhhh .....

in these file ....the 

**Misc -> Boot -> LauncherOption = Full**

is not set ..... 

the new setting in OC 0.6.6 to protect EFI can't work ... i think....?!?

OpenCore Guide:
"
OpenCore 0.6.6 or newer(opens new window)
....
config.plist settings:
Misc -> Boot -> LauncherOption = Full
Use Short for Insyde based firmwares, commonly found on laptops
UEFI -> Quirks -> RequestBootVarRouting = True
OpenShell(opens new window)
Bundled with OpenCore
Remember to add this to both EFI/OC/Tools and Misc -> Tools
This is mainly for troubleshooting
#
"

**Comment by khronokernel** [comment]
0.6.6 binary is not from master, it’s a few weeks old. Around the time I added MaxBIOSVersion to OpenCorePkg

**Comment by stschulze1972** [comment]
understand .... please publish the use of pre release 0.6.6 

what i must do to have the opencore master 0.6.6 with efi-protection?

**Comment by BenSova** [comment]
You mean where it won't brick your Mac? Open Core Legacy Patcher is already setup to do that automatically.

**Comment by stschulze1972** [comment]
yes, i will not brick my Bios MBP9,2

and also i wouldn't damage my OpenCore-Installation -> save Launcher ....
