### ISSUE TITLE
Commercial application licences invalid after going from OCLP 0.2.5 to 0.3.0

### ISSUE THREAD

**Issue by larsvonhier** [dortania/OpenCore-Legacy-Patcher#530]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Parallels Desktop* licence claims "changed hardware" and invalidates its licence key after going from OCLP 0.2.5 to 0.3.0 (nightly). Also iCloud needs new account confirmation and sees two machines from then on - both having identical serial numbers.

### Any Additional Information

* we have this problem on a couple of machines: i.e. MacBook Pro 8,2 (Big Sur 11.2.3) / cMP3,1 (Monterey b6) and with various Parallels Desktop versions (15, 17)

Once we revert back to OCLP 0.2.5 both Parallels and iCloud behave "normal" again.
Additional sidenote: We used 0.3.0´s SurPlus feature instead of latebloom where applicable.

**Comment by jgleigh** [comment]
Saw the iCloud issue on my MacPro5,1 as well and assumed it was due to the SMBIOS change, but maybe something else is going on here.

Another incident:
https://forums.macrumors.com/threads/macos-12-monterey-on-unsupported-macs-thread.2299557/post-30379009

**Comment by khronokernel** [comment]
SMBIOS should be unchanged with more recent commits
