### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kamaruszamanjufri** [dortania/OpenCore-Legacy-Patcher#531]
### Machine Model

MacBookAir5,2

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

My antivirus software detected both GUI and CLI got infected for 0.2.4 and 0.2.5 release.

An infected file attempted to run on your device.
Threat name: Trojan.MAC.Generic.108743
Path: /xxx/OpenCore Patcher.app/Contents/Resources/OCLP-CLI
We deleted the file to prevent malicious commands from being executed on your device.

An infected file attempted to run on your device.
Threat name: Trojan.MAC.Generic.108739
Path: /xxx/OpenCore-Patcher.app/Contents/MacOS/OpenCore-Patcher
We deleted the file to prevent malicious commands from being executed on your device.

**Comment by khronokernel** [comment]
Did you check online for other reports or even past issues opened in the repo?
