### ISSUE TITLE
[Bug]: no final start

### ISSUE THREAD

**Issue by floxi15** [dortania/OpenCore-Legacy-Patcher#532]
### Machine Model

MacPro3,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

I installed Big Sur with all the post install patches and stuff and after is loaded the final command to the Efi i can’t start the MacPro from the efi on my install drive
I get to the Boot Picker and select the EFI and enter but after that my screen goes dark and no apple logo no anything… after a while it restarts and that’s it…

Any idea what that can be?

**Comment by khronokernel** [comment]
Use forums for general troubleshooting
