### ISSUE TITLE
[Bug]: Virus Total reports lots of nasties?

### ISSUE THREAD

**Issue by spaceprograms** [dortania/OpenCore-Legacy-Patcher#533]
### Machine Model

iMac14,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

When I download the zip file and submit it to Virus Total the following errors are shown:

Alibaba Trojan:Win32/DangerousSig.faaafd16
Avast MacOS:Agent-QJ [Trj]
AVG MacOS:Agent-QJ [Trj]
BitDefender Trojan.MAC.Generic.108743
Emsisoft Trojan.MAC.Generic.108743 (B)
ESET-NOD32 A Variant Of Generik.NGIARYQ
FireEye Trojan.MAC.Generic.108743
Fortinet PossibleThreat
GData Trojan.MAC.Generic.108743
Ikarus Win32.Outbreak
Kaspersky HEUR:Trojan.Win32.Generic
Lionic Trojan.Win32.Generic.4!c
MAX Malware (ai Score=82)
McAfee-GW-Edition Artemis!PUP
Microsoft Trojan:Script/Sabsik.TE.B!ml

While a few of these appear to be Windows related there are a few Mac ones there too. I am very concerned that uncompressing this zip file will infect my computer. Could you please explain this result (I've never seen so many hits on a file before!).

Thanks

**Comment by Ausdauersportler** [comment]
These are all false positive alarm. 
Close the issue and go ahead.
