### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GitHub3590** [dortania/OpenCore-Legacy-Patcher#534]
### Machine Model

MacBookPro6,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

The Zoom Control is not working.
It's the Zoom control in "System Preferences/Accessability" NOT Zoom.us.
I think it's the fact I don't have a Metal GPU.
Hope someone has a fix.
Thanks!

**Comment by educovas** [comment]
known issue, #108

**Comment by GitHub3590** [comment]
Thanks, maybe a fix is in the works.
