### ISSUE TITLE
[Bug]: Kernel panic after hibernation

### ISSUE THREAD

**Issue by kris545545** [dortania/OpenCore-Legacy-Patcher#539]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

When the machine resumes from hibernation, it kernel panics. I have attached the crash log.

[kernelPanicLog.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7279792/kernelPanicLog.txt)

**Comment by khronokernel** [comment]
Use forums for troubleshooting
