### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joostiphone** [dortania/OpenCore-Legacy-Patcher#540]
### Machine Model

MacBook8,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

When viewing a menu/context menu (in Monterey dark mode) the colors are off, like if the graphics acceleration is not working (I'm not an expert here...). In the photo I took, you can see the grayish area. This happens anywhere where I hit the menu with the cursor. 

![IMG_0496](https://user-images.githubusercontent.com/16277235/135901240-7100f3d9-263a-471f-baa0-074d56bb84e8.jpeg)

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by joostiphone** [comment]
I'm confused, why is this closed already?

**Comment by khronokernel** [comment]
Known issue with non-Metal GPUs. Use forums for troubleshooting

**Comment by joostiphone** [comment]
Okay. Thank you. I've searched for ages honestly, can you guide me in the right direction? I can't find a fix so far. So if you know if there is any I'm open to suggestions.

Thanks again.

**Comment by khronokernel** [comment]
I linked you the issue, there is no fix besides buying a new Mac or using an older OS
