### ISSUE TITLE
[Bug]: iMac 14,2 Can't be Patched with Legacy nVIDIA Drivers

### ISSUE THREAD

**Issue by SephirothFan** [dortania/OpenCore-Legacy-Patcher#542]
### Machine Model

iMac14,2

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hello!  I've been using this patcher as long as it's been available and I really love it!  This is the first unresolvable issue that I've seen so far.  My iMac 14,2 can't be patched with the Post Patcher on GUI or TUI because of an error with SIP being enabled.  I have disabled SIP using the RecoveryOS and the Patcher Settings options in OpenCore.  Everywhere I check, the system is reporting that SIP is disabled, but the Post Patcher still thinks that it's enabled somewhere I can't find.  I mainly need this for the Legacy nVIDIA Patch.

**Comment by khronokernel** [comment]
RecoveryOS is not viable to disable SIP, must be disabled within OCLP, build/install a new config and reboot with the updated config

**Comment by SephirothFan** [comment]
I completely deleted OCLP and rebuilt everything before trying to patch, but it's still giving me the issue.  Is there a guide I could look at to try this again?

**Comment by Ausdauersportler** [comment]
5.  Patcher Settings
2.  Security Settings
2.  Set System Intrgity Protection (SIP
2. Disable SIP
Q
Q
1.  Build OpenCore
2.  Install OpenCore to USB/internal drive

**Comment by SephirothFan** [comment]
I don't know what I did different from yesterday, but I removed OCLP, ran through all the steps again and it worked this time!  Thank you so much; this issue can be closed/deleted!
