### ISSUE TITLE
[Bug]: Airplay only shows black screen

### ISSUE THREAD

**Issue by cengizkursat** [dortania/OpenCore-Legacy-Patcher#544]
### Machine Model

MacBookPro8,3

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Whenever I try to connect to an Airplay 2 compatible display via Airplay, the connection can be established. However, there is no image on the display, just a black screen. I have tried to replicate the issue with multiple displays and the result is the same regardless of the display. I will happily provide more info if necessary and when necessary. Thanks in advance.

**Comment by khronokernel** [comment]
Spent a bit of time on this with a MacBookPro8,2. TL;DR:

* Hardware Accelerated Encode and Decode is functional if dGPU is absent (either with a demux, or `-wegnoegpu`)
* FairPlay 2.x/3.x remains broken
* AirPlaying specific videos (ie. Youtube) is functional
* AirPlay to display remains broken

For MacBookPro8,1 users as well as 8,2/3 with a demux mud, this is a fairly useful patch set so it'll be added in the future. However for others, there is no fix. Feel free to research and submit patch sets, always happy to get more helping hands on developing these.

Additionally updated [documentation](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108) to reflect current status
