### ISSUE TITLE
MacBook Pro 10,1 - No WiFi with BCM94360CS

### ISSUE THREAD

**Issue by learjet60guy** [dortania/Opencore-Legacy-Patcher#55]
Early 2013 MacBook Pro 15" with an upgraded BCM94360CSAX WiFi/BT card. WiFi doesn't work at all when booted via Opencore from USB. "Wi-Fi" does not even appear as a network device in System Preferences or under "Wi-Fi" in System Information. BT seems to work normally. EFI was built, with Opencore Legacy Patcher, to a blank, GUID formatted USB 2.0 drive.

<img width="1756" alt="NoWiFi" src="https://user-images.githubusercontent.com/17993709/107485892-00329900-6b4a-11eb-911f-b944c5a101a2.png">
<img width="1756" alt="YesWiFi" src="https://user-images.githubusercontent.com/17993709/107485896-0163c600-6b4a-11eb-8d4d-66192dee986c.png">

**Comment by whgmkeller** [comment]
Same here. Mid 2012 MacBook Pro 13" with the original WiFi/BT card. I am running Catalina; this is officially supported on my MacBook Pro 2012, but Big Sur not anymore.

I installed OpenCore EFI to internal disk (it's a test system that I use to determine if OpenCore is the way to go for my Mac Pro 5,1). Booting is okay, but Wifi doesn't work. "Wi-Fi" does not even appear as a network device in System Preferences or under "Wi-Fi" in System Information.

Bluetooth is working correctly. Big Sur update shows up.

Cheers, 
Willem
Netherlands

**Comment by whgmkeller** [comment]
See items in System overview/ Wifi (In Dutch but understandable I think); looks like a lot of necessary stuff isn't installed?

Softwareversies:
  CoreWLAN:	13.0 ((null))
  CoreWLANKit:	13.0 ((null))
  Menu-extra:	13.0 ((null))
  Systeeminformatie:	12.0 (1500)
  IO80211-familie:	12.0 (1200.12.2b1)
  Diagnostische info:	1.0 (910)
  AirPort-configuratieprogramma:	Niet geïnstalleerd

**Comment by whgmkeller** [comment]
Just installed Big Sur thru Software Update, and now WIFI is working again :-)
