### ISSUE TITLE
[Bug]: A working solution to fix the annoying macOS EFI error warning

### ISSUE THREAD

**Issue by OKonnel** [dortania/OpenCore-Legacy-Patcher#552]
### Machine Model

iMac14,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

With the latest versions of OCLP, the Mac occasionally raises an EFI-related fatal error warning.
So! I suggest introducing this simple modification by creating the OCLP EFI Build, unless you knowledgeable friends know that in some cases it can cause problems.
In my case it works great
On the advice of [Ausdauersportler](https://github.com/Ausdauersportler), after creating the OCLP EFI Build, I add the **EFICheckDisabler.kext** module (here in attach) in /Volumes/EFI/EFI/OC/Kexts/
and in /Volumes/EFI/EFI/OC/config.plist, in Kernel section, after the line

`	<key>Kernel</key>`
`	<dict>`
`		<key>Add</key>`
`		<array>`

i add:

`			<dict>`
`				<key>Arch</key>`
`				<string>x86_64</string>`
`				<key>BundlePath</key>`
`				<string>EFICheckDisabler.kext</string>`
`				<key>Comment</key>`
`				<string>EFICheckDisabler</string>`
`				<key>Enabled</key>`
`				<true/>`
`				<key>ExecutablePath</key>`
`				<string></string>`
`				<key>MaxKernel</key>`
`				<string></string>`
`				<key>MinKernel</key>`
`				<string></string>`
`				<key>PlistPath</key>`
`				<string>Contents/Info.plist</string>`
`			</dict>`

Obviously all of you OCLP Developers will know if and how to use and possibly improve this suggestion and how to insert it in the OCLP Code for creating the OCLP EFI Build.

[EFICheckDisabler.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7311245/EFICheckDisabler.kext.zip)

**Comment by vit9696** [comment]
@khronokernel why is not merged into RestrictEvents upstream or what is going on here?

**Comment by OKonnel** [comment]
If you read the last 0.3.0 Changelog you will see that Khronokernel he entered it immediately, yesterday. But thanks for your interest and your response. Sincerely OK
