### ISSUE TITLE
Keyboard Backlight not working on MacBook Pro 9,2

### ISSUE THREAD

**Issue by Mambo-beep** [dortania/OpenCore-Legacy-Patcher#553]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Hello,
when I try to activate the keyboard backlight on my MacBook Pro 9,2 an error symbol appears, but my MacBook have support for this function. I also try to activate it over the control center but the button is not pushable. I hope somebody can help me.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
