### ISSUE TITLE
[Bug]: Why is the Bordvendor replaced with rubbish?

### ISSUE THREAD

**Issue by bnaambo** [dortania/OpenCore-Legacy-Patcher#554]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Why Does OCLP replace the Boardvendor with Acidanthera?
That makes apps Like MacFanControl not work under Windows.
Since The Boardvendor is not longer Apple Inc. MacFanControl Says Only Apple Computers are Supported and then Closes.
Please Stop Replacing the Boardvendor with some Rubbish it causes apps which rely on the Vendor string to stop functioning

**Comment by khronokernel** [comment]
We only do so in full SMBIOS spoofs which is neither the default behaviour nor recommended for average use unless requiring Mojave/Catalina support which is experimental.

Allowing the original vendor to be passed through with a full spoof with break Application logic that base hardware specifications off whether in a VM-like state or not. This "rubbish" is there for a reason

Either downgrade your spoof to minimal or don't boot through OCLP
