### ISSUE TITLE
[Feature Request]: Add support to disable BD PROCHOT for MacBooks without battery

### ISSUE THREAD

**Issue by salevdns** [dortania/OpenCore-Legacy-Patcher#555]
### What is the requested feature?

If one needs to remove their battery from their MacBook, for safety reasons (because it is swollen, which happens a lot with older MacBooks) or other reasons, the device can still be used as a stationary Mac with the power cord plugged in.
However, the experience is quite bad to unusable because Apple aggressively throttles down the CPU if the battery is missing.
> The CPU throttling due to missing battery is triggered by the firmware, and it doesn't make any difference what version of macOS (or other OS) you are running.
The reason for this is that the EFI firmware sets on BD PROCHOT which is a CPU register (msr 0x1FC) usually used to tell the CPU that some other component (GPU or whatever) is overheating. This will cause the CPU to throttle even though it is not itself overheating. This is described in [Intel® 64 and IA-32 Architectures Software Developer's Manual Volume 4: Model-Specific Registers](https://software.intel.com/en-us/download/intel-64-and-ia-32-architectures-software-developers-manual-volume-4-model-specific-registers). ([source](https://apple.stackexchange.com/a/380510))

There are however methods to disable BD PROCHOT and restore unthrottled performance with a missing battery which are either EFI or kext based.
I have found various implementations of this, but the ones that look the cleanest and most minimal to me are the ones from @arter97.
I have successfully incorporated [his kext based method](https://github.com/arter97/SimpleMSR) into my OpenCore-Legacy configuration and my MacBookPro11,1 without battery runs unthrottled with no issues whatsoever.

Ideally one would use both the kext method and the [EFI method](https://github.com/arter97/DisablePROCHOT) combined.
The EFI method to have the throttling already disabled at boot level (which also benefits booting any other OSs) and the kext method to keep BD PROCHOT disabled after suspend. 
> Entering ACPI S3 state(suspend) causes the BD PROCHOT MSR bit getting re-enabled. You need to use some userspace tool for disabling BD PROCHOT for such cases. ([source](https://github.com/arter97/DisablePROCHOT))

However, I was not able to get the EFI method to work:
I tried adding [arters DisablePROCHOT.efi](https://github.com/arter97/DisablePROCHOT/releases/tag/v1.0) (which apparently works with rEFInd & Clover) to the drivers directory and config.plist of my OpenCore-Legacy install, but it resulted in a black screen with no boot.
So some adjustments would have to be done to that method.

Of course @arter97 would need to give his permission to use his implementations since they are released with `All rights reserved`, but I am quite confident he would.

I think this feature would be a valuable addition to OpenCore-Legacy since it aligns with the projects goal of extending the lifespan of older Macs.

### Any Additional Information

Kext method by @arter97: https://github.com/arter97/SimpleMSR
EFI method by @arter97: https://github.com/arter97/DisablePROCHOT

Other resources:
https://github.com/balecrim/NoBatteryNoProblem.kext
https://github.com/syscl/CPUTune

**Comment by arter97** [comment]
Hi.

I didn't expect anyone to find it to be seriously useful, it was more like a "eh I'll just push it on GitHub just in case" thing.
I've just pushed commits setting the license to BSD 2-clause, which should be enough.

I'm not using those 2 at the moment. While DisablePROCHOT would still work, I'm not quite sure for SimpleMSR.

Let me know if you guys need anything else :)

Thanks.

**Comment by khronokernel** [comment]
Thank you so much for the quick reply and adjusting the license! Really do appreciate it

I was able to verify SimpleMSR functions in both Big Sur and Monterey, though will be doing some more testing (hibernation, etc) to ensure no strange bugs pop in (as when you pushed the project Mojave was only in Beta)

**Comment by protocold** [comment]
@khronokernel so we only need SimpleMSR without DisablePROCHOT ?

**Comment by protocold** [comment]
@khronokernel Is it possible to write to this register in ACPI just like how we did for gmux power down?

**Comment by salevdns** [comment]
This might be helpful:
https://github.com/tianocore-docs/edk2-UefiDriverWritersGuide/blob/master/appendix_a_edk_ii_file_templates/a1_uefi_driver_template.md

\+ Here are some UEFI drivers from OpenCorePkg for reference:
https://github.com/acidanthera/OpenCorePkg/tree/master/Platform
