### ISSUE TITLE
[Bug]: After Post-Install Patch of Monterey Beta 9 - Carbon Copy Cloner Glacially Slow

### ISSUE THREAD

**Issue by ncmacguy** [dortania/OpenCore-Legacy-Patcher#556]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

My MacBookPro10,1 is running Monterey Beta 9 using OCLP 0.2.5, with the Post-Install Volume Patch applied.

The only issue I have found so far is with Carbon Copy Cloner running its latest beta version 6.0.4-62(7219). All operations run glacially slow with continually displaying the spinning ball.

Prior to installing the Post-Install Volume Patch, CCC performed normally.

Other apps that I have tried after the patch also run normally.

Any idea what might be causing this issue with CCC?

Below is the Terminal output of the Post-Install Patch:

##################################
# OpenCore Legacy Patcher v0.2.5 #
# Selected Model: MacBookPro10,1 #
##################################

This model is supported

1.  Build OpenCore
2.  Install OpenCore to USB/internal drive
3.  Post-Install Volume Patch
4.  Change Model
5.  Patcher Settings
6.  Credits
Q.  Quit

Please select an option: 3

##########################
# Patching System Volume #
##########################
Patches Root volume to fix misc issues such as:

- Metal Graphics Acceleration
  - Intel: Ivy Bridge (4000 series iGPUs)
  - Nvidia: Kepler (600-700)
- Non-Metal Graphics Accelertation
  - Intel: Ironlake - Sandy Bridge
  - Nvidia: Tesla - Fermi (8000-500 series)
  - AMD: TeraScale 1 and 2 (2000-6000 series)
- Audio support for iMac7,1 and iMac8,1
- Wifi support for BCM94328, BCM94322 and Atheros cards

WARNING: Root Volume Patching is still in active development, please
have all important user data backed up. Note when the system volume
is patched, you can no longer have Delta updates.

Supported Options:

1. Patch System Volume
2. Unpatch System Volume (Experimental)
B. Exit
        
Patch System Volume?: 1
- Starting Patch Process
- Determinging Required Patch set for Darwin 21
- Found GPU (0): 8086:166
- Found GPU (1): 10DE:FD5

The following patches will be applied:
- Add Legacy Nvidia Kepler Graphics Patch
- Add Legacy Intel Ivy Bridge Graphics Patch
Would you like to continue with Root Volume Patching?(y/n): y
- Continuing with Patching
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Apple binaries missing
- Attempting download from following link:
https://github.com/dortania/PatcherSupportPkg/releases/download/0.1.3/12-Monterey.zip

- Downloading package
- 168.61026287078857MB Downloaded
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/private/var/folders/yw/g9384g416bg0b4gp0s65pfqc0000gn/T/_MEISLYFMj/payloads
Press [ENTER] to continue
- Found Root Volume at: disk2s3
- Mounting APFS Snapshot as writable
Password:
- Successfully mounted the Root Volume
- Running patches for MacBookPro10,1
- Installing Kepler Patches
- Detected supported OS, installing Acceleration Patches
- Installing Kepler Acceleration Kext patches for Monterey
- Adding GeForce.kext
- Adding GeForceAIRPlugin.bundle
- Adding GeForceGLDriver.bundle
- Adding GeForceMTLDriver.bundle
- Adding GeForceVADriver.bundle
- Adding NVDAGF100Hal.kext
- Adding NVDAGK100Hal.kext
- Adding NVDAResman.kext
- Adding NVDAStartup.kext
- Installing Ivy Bridge Patches
- Detected supported OS, installing Acceleration Patches
- Installing IvyBridge Acceleration Kext patches for Monterey
- Adding AppleIntelFramebufferCapri.kext
- Adding AppleIntelHD4000Graphics.kext
- Adding AppleIntelHD4000GraphicsGLDriver.bundle
- Adding AppleIntelHD4000GraphicsMTLDriver.bundle
- Adding AppleIntelHD4000GraphicsVADriver.bundle
- Adding AppleIntelIVBVA.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelGraphicsShared.bundle
- Adding AppleIntelGraphicsShared.bundle
- Fixing Acceleration in CoreMedia
- Merging Ivy Bridge Frameworks
- Merging Ivy Bridge PrivateFrameworks
Press [ENTER] to continue with cache rebuild: 
- Rebuilding Kernel Cache (This may take some time)
- Successfully built new kernel cache
Press [ENTER] to continue with snapshotting
- Creating new APFS snapshot
- Unmounting Root Volume (Don't worry if this fails)
- Patching complete

Please reboot the machine for patches to take effect

Press [ENTER] to continue

**Comment by khronokernel** [comment]
Root volume patching breaks APFS seal, either downgrade to Big Sur where root patching is not needed for Ivy Bridge or request Carbon Copy Cloner look into supporting broken APFS seals
