### ISSUE TITLE
[Bug]: 13” Mid-2010 MacBook Pro Monterey above Beta 6 installation.

### ISSUE THREAD

**Issue by Hellothereqwerty** [dortania/OpenCore-Legacy-Patcher#557]
### Machine Model

MacBookPro7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

First of all, I can't properly update to any version of Monterey by OTA. When I update, it'll create two extra boot entries. One is called Macintosh HD and the other one is called macOS Installer. Another issue is that it'll create another extra entry if I update or do a clean install of any version of Monterey that is above Beta 6 from a bootable USB.
That extra entry is called macOS Installer. Any of the extra boot entries that are not called macOS Installer will crash instantly, causing the MacBook Pro to reboot. The macOS Installer entry basically says that there was an error verifying the firmware and that I would need to reboot or choose a disk that I can boot from. When I did a clean install of Beta 9, I expected to get to the set-up screen and get on with my day.

### Any Additional Information

![F1256410-5BB5-404E-A442-C97767A1DE4B](https://user-images.githubusercontent.com/92277376/136737014-3dcd1332-b318-4ac4-8dfa-3a1052250f6b.jpeg)
![FE7CF22B-D6E9-4C6C-A743-340AA6982A24](https://user-images.githubusercontent.com/92277376/136737038-875f5d7d-a348-4f22-aabd-4ad25359890e.jpeg)
![19D2ABC9-61C8-4373-8A61-88732BB2E171](https://user-images.githubusercontent.com/92277376/136737042-89a9c136-424d-4f74-90bf-c479d63d5849.jpeg)

**Comment by AlexSakha** [comment]
Hi, maybe it will help you try.And install with this flag, format the disk and install the system all over again.
<key>DummyPowerManagement</key>
			<false/>
			<key>Cpuid1Data</key>
			<data>AAAAAAAAAAAAAACAAAAAAA==</data>
			<key>Cpuid1Mask</key>
			<data>AAAAAAAAAAAAAAAAAAAAAA==</data>
			<key>MaxKernel</key>
			<string></string>
			<key>MinKernel</key>
			<string></string>

**Comment by khronokernel** [comment]
This should be resolved with the VMM branch:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/543

Feel free to test yourself, still going through validation so unknown when we'll merge
