### ISSUE TITLE
[Feature Request]: Patching ACPI to power down defective dGPU on MacBookPro8,2/8,3

### ISSUE THREAD

**Issue by protocold** [dortania/OpenCore-Legacy-Patcher#559]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur, macOS 10.15, Catalina, macOS 10.14, Mojave, macOS 10.13, High Sierra

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

This is for those with a bad dGPU on MBP8,2/8,3 but without demux. I did not create this info but I gathered research on the internet (reference link on the bottom). 

You probably have been using nvram to disable the dGPU:
nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00

However, this just tell the gmux to use iGPU _without_ powering down the defective dGPU, so this continue to consume power and overtime it will create more issue as the dGPU continue to deteriorate. For those comfortable with hardware mod you can remove the R8911 so permanently cut the dGPU power.

For those that dont want the hardware mod, you can do it via software by writing directly into the gmux register and shut down the dGPU power(demux achieved this from within its code):

outb 0x728 1 # Switch select
outb 0x710 2 # Switch display
outb 0x740 2 # Switch DDC
outb 0x750 0 # Power down discrete graphics

But this require Grub previously (you can also run inb and outb command under linux to read/write these register). 

Now, it happens that this can also be done via ACPI patching:
https://www.tonymacx86.com/threads/help-macbook-pro-disable-radeon-gpu-via-dsdt.164458/#post-1041555

The Ask:
Can this ACPI patching be done in OCLP? Is there a slicker implementation under OCLP to write to these addresses? 

Also the dGPU will wake up with the machine after sleep so you need to use AMDGPUWakeHandler.kext to turn it back off (see the 4th link on bottom). Can this be put under OCLP as well? 

Reference:
----------------------------------------------
1) https://www.jeffgeerling.com/blog/2017/fixing-2011-macbook-pro-booting-grey-screen-amd-radeon-video-glitch
2) https://gist.github.com/blackgate/17ac402e35d2f7e0f1c9708db3dc7a44
3) https://help.ubuntu.com/community/MacBookPro8-2/Raring
4) https://forums.macrumors.com/threads/disable-a-failed-amd-gpu-on-a-2011-macbook-pro-grub-solution.2087527/

**Comment by khronokernel** [comment]
Whipped up a quick SSDT for testing. 

* [SSDT-DGPU.aml.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7324215/SSDT-DGPU.aml.zip)
 

Will need this patch in addition:

<details>
<summary>config.plist: ACPI -> Patch</summary>

```xml
			<dict>
				<key>Base</key>
				<string>\_SB.PCI0</string>
				<key>BaseSkip</key>
				<integer>0</integer>
				<key>Comment</key>
				<string>_INI to XINI</string>
				<key>Count</key>
				<integer>1</integer>
				<key>Enabled</key>
				<false/>
				<key>Find</key>
				<data>X0lOSQ==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>WElOSQ==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>RFNEVA==</data>
			</dict>
```
</details>
<br>

Added source code for referencing:

<details>
<summary>ACPI Source</summary>

```c
DefinitionBlock ("", "SSDT", 2, "DRTNIA", "dGPU_OFF", 0x00001000)
{
    External (_SB_.PCI0, DeviceObj)
    External (_SB_.PCI0.XINI, MethodObj) // Rerouted _INI method
    External (OSYS)

    Scope (_SB.PCI0)
    {
        OperationRegion (IOGP, SystemIO, 0x0700, 0x51)
        Field (IOGP, ByteAcc, NoLock, Preserve)
        {
            Offset (0x10), 
            P710,   8, 
            Offset (0x28), 
            P728,   8, 
            Offset (0x40), 
            P740,   8, 
            Offset (0x50), 
            P750,   8
        }

        Method (_INI, 0, NotSerialized)  // _INI: Initialize
        {
            // Call original _INI
            \_SB.PCI0.XINI()
            
            // Disables dGPU
            P728 = One
            P710 = 0x02
            P740 = 0x02
            P750 = Zero
        }
    }
}
```

</details>
<br>
