### ISSUE TITLE
Using OLP on a drive that already has Big Sur

### ISSUE THREAD

**Issue by evasilis** [dortania/Opencore-Legacy-Patcher#56]
Hi there and forgive if my questions sound (read) naive but I am in a completely uncharted territory. Here it goes:

a) Can I just change the EFI to open core on a drive that already has Big Sur on it, that is not install Big Sur again?

b) Can I use as a USB install media the one I already have (no patches on it, nothing just a clean BS bootable installer)?

System Info: MacPro 5.1 - Radeon RX 580 pulse - 48 GB RAM

Thanks for your time!

**Comment by khronokernel** [comment]
A. Yes, so long as no other patcher has modded the root volume
B. Yes

**Comment by evasilis** [comment]
Thanks!
