### ISSUE TITLE
[enhancement] Add support for AMD GCN dGPU used in iMac11,x and iMac12,x models

### ISSUE THREAD

**Issue by Ausdauersportler** [dortania/OpenCore-Legacy-Patcher#562]
### Machine Model

iMac11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur, macOS 10.15, Catalina, macOS 10.14, Mojave, macOS 10.13, High Sierra, macOS 10.12, Sierra

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

This is an RFE:

Lately I tested successfully some other AMD GCN dGPU with different systems of the iMac11,x and iMac12,x family. 

In general all those GCN dGPU (seem to) need the rebuild-device-tree and agdpmod=pikera entry, while the M5100 is like the M4000 different or more difficult, both need the additional CAIL entries in the DeviceProperties section as listed below (this is copied from an iMac12,2 config.plist). I know these entries are equivalent with the radpg=15.

Currently I have tested successfully the M5100 (device-id 6820) and W6170M (device-id 6646) with all macOS versions including High Sierra, Mojave, Catalina, Big Sur, Monterey Beta 9.

other issues:
sleep/wake is broken with native High Sierra as well as with OCLP based Mojave/Catalina/Big Sur/Monterey on iMac12,x only with both cards mentioned above. sleep/wake on iMac11,x is working fine! 
Any idea how to debug this?

note:
using the radpg=15 with AMD Polaris/Ellesmere cards works, too (WX4170 and RX480 mobile tested). So the settings below might be a one size fits all solution. But I am afraid to break a lot of configs out there changing this in general.

### Any Additional Information

                        <key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
                        <dict>
                                <key>shikigva</key>
                                <integer>80</integer>
                                <key>unfairgva</key>
                                <integer>1</integer>
                                <key>rebuild-device-tree</key>
                                <integer>1</integer>
                                <key>agdpmod</key>
                                <string>pikera</string>
                                <key>CAIL,CAIL_DisableDrmdmaPowerGating</key>
                                <data>AQAAAA==</data>
                                <key>CAIL,CAIL_DisableGfxCGPowerGating</key>
                                <data>AQAAAA==</data>
                                <key>CAIL,CAIL_DisableUVDPowerGating</key>
                                <data>AQAAAA==</data>
                                <key>CAIL,CAIL_DisableVCEPowerGating</key>
                                <data>AQAAAA==</data>
                        </dict>

**Comment by khronokernel** [comment]
Added to mainline, forgot to close
