### ISSUE TITLE
[Fix]: 

### ISSUE THREAD

**Issue by graphicessence** [dortania/OpenCore-Legacy-Patcher#563]
### Machine Model

MacPro 5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

Kernel (Core) panics after Hibernation wakes up. 
Suggestion: Add a Hibernation fixup for Lilu to the Kexts. Will fix Sync between RTC.

**Comment by khronokernel** [comment]
Appreciate the feedback, do you happen to know if other MacBookPro5,x are affected by this issue? ie. is this exclusive to the 5,1, or all switchable 5,x or just a blanket 5,x issue?

**Comment by graphicessence** [comment]
@khronokernel 
Here is a kernel panic report. FYI
[Kernel-2021-10-14-151342.panic.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7346274/Kernel-2021-10-14-151342.panic.zip)
IDK if it's can be useful for you.
