### ISSUE TITLE
[Bug]: Airdrop not work on Mac OS Bigsur 11.6 - Macbook pro 8,1

### ISSUE THREAD

**Issue by AfterCool** [dortania/OpenCore-Legacy-Patcher#565]
### Machine Model

MacBook8,1

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hello, 
I have a problem with Airdrop, the Iphone does not see the MacBook but the MacBook sees the Iphone.
Thank you for your help. 
Regards,

**Comment by khronokernel** [comment]
MacBook8,1 already runs Big Sur natively. If this is a MacBook**Pro**8,1, you need to upgrade to a Bluetooth 4.0 chipset
