### ISSUE TITLE
[Bug]: Boot stuck on Apple logo with Monterey B10

### ISSUE THREAD

**Issue by Tiger-AC** [dortania/OpenCore-Legacy-Patcher#573]
### Machine Model

iMac12,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

Can't boot up with the latest OCLP v030n (containing the Bluetooth fix for MontereyB10). Please see the attached photo for details. I've tried resetting NVRAM & re-applying Post-Install Volume Patch.
But it boots up perfectly fine with Big Sur 11.6 on the same disk.
The Monterey B10 was working fine (minus the Bluetooth) with the previous build of OCLP v030.

![IMG_1269](https://user-images.githubusercontent.com/82495745/137555228-cbda852f-78ec-4ba7-8eeb-1449ee95847b.jpeg)

**Comment by khronokernel** [comment]
Verify the latest commit https://github.com/dortania/OpenCore-Legacy-Patcher/commit/a97a32730ab2593a4eeb0b915dad226c9b6ea1dc:

* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/4069250835/artifacts/103444762
