### ISSUE TITLE
[Bug]: MacBook Pro 8.2 After installing the software and restarting, I can't enter the desktop.

### ISSUE THREAD

**Issue by Tuzizhch** [dortania/OpenCore-Legacy-Patcher#575]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

After installing the software and restarting, I can't enter the desktop and always display the system login page.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
