### ISSUE TITLE
[Bug]: Nvidia GT-710 not recognised as metal capable

### ISSUE THREAD

**Issue by volsk** [dortania/OpenCore-Legacy-Patcher#576]
### Machine Model

MacPro5,1

### Application Version

Latest Build (nightly)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

Nvidia GT-710 (Kepler) is not recognised as metal capable. Therefore no hardware acceration.

In Big Sur and earlier this was no problem. As I upgraded OCLP and to Monterey at the same time (I know silly, I don't which of two is the cause. But I know the combination doesn't work.

**Comment by volsk** [comment]
Ah, I missed that note. Thanks. Can you be more specific on where to get more info?
In the change log I've found

_Downgrade Nvidia Kepler Bundles to 11.0 Beta 3
Resolves crashing at high loads, credit to Jackluke for discovery_

Which for me suggest Kepler should still work.

**Comment by Ausdauersportler** [comment]
Monterey: 
To get Kepler support you **now** have to patch the root files system as with all other legacy video cards. So please take a look at the OCLP docs how to apply these post install patches. The patch set will be chosen automaticall (patcher option #3).
