### ISSUE TITLE
[Enhancement]: Deactivate and power down dGPU when booting Linux

### ISSUE THREAD

**Issue by svemonix** [dortania/OpenCore-Legacy-Patcher#578]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

It would be great if OCLP could power down the dGPU when booting Linux (or something else) while keeping the normal behavior with MacOS. The main reasons to do so would be:

- better battery life & less heat/noise
- better support of the iGPU in Linux (drivers, Wayland, etc.) and works out of the box
- Nvidia won't support Kepler past the driver version 470 and Nouveau has poor performance

I'm not sure if this is technically feasible but I thought it was worth asking. I believe others may be interested too.

Thanks!

**Comment by khronokernel** [comment]
This is theortically possible based off our [MacBookPro8,x patch set](https://github.com/dortania/OpenCore-Legacy-Patcher/commit/82fe98a93c73200f93ed9df56766c43c71bfd1e3), however it can't be used as-is.

The main complications (off the top of my head) would be determining the location of the dGPU and GMUX to send power down requests. You'll need to find the values yourself, see our SSDT-DGPU source as well as the associated issue:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/ACPI/Source/SSDT-DGPU.dsl
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/559

As I don't have a machine on-hand, you or some other MacBookPro11,3 users will need to determine the location. The ones in SSDT-DGPU are based off the MacBookPro8,2 for reference.

Once the dGPU does power off, you'll likely hit a second road block in macOS. Specifically that by default, Apple's GMUX driver forces the dGPU to handle brightness control (at least on the 2011 MacBook Pros this is true). So if this also applies to the MacBookPro11,3, this means that we'll need to now back port the AppleMuxControl kext from 10.12 Sierra where the Mud driver does allow the active GPU to handle brightness control.

* This can be simulated by adding `-wegnoegpu` to OCLP's boot-args and seeing if brightness control works, as the Nvidia dGPU will be missing from IOService and so macOS would be forced to rely on the iGPU solely
* Linux does not require any driver hacks for this, brightness control should always work

From OCLP's perspective, our code base is already setup to support additional models without much hassle. So really these 2 issues would need to be resolved:

* Find GMUX and dGPU paths
* Determine if AppleMuxControl needs to be downgraded
* Disable the GMUX from starting after waking in macOS
  * Can easily be resolved by adjusting [AMDGPUWakeHandler](https://github.com/blackgate/AMDGPUWakeHandler/blob/master/AMDGPUWakeHandler/AMDGPUWakeHandler.cpp)

**Comment by khronokernel** [comment]
Well we're open to PRs but as no hardware on hand and Monterey release incoming, this issue will be considered out of scope for the team. However feel free to continue discussing

**Comment by odedia** [comment]
Happy to help out with testing as I have a patched Monterey Macbook Pro 2011 17".
I tried to use this gist which worked before:
https://gist.github.com/cdleon/d1eff7246a25193304284ecec40445b0
However, I can't mount the root volume. Is there a way to do it from OpenCore Legacy?
