### ISSUE TITLE
MaxBIOSVersion to avoid BIOS updates in unofficially supported macOS versions

### ISSUE THREAD

**Issue by stschulze1972** [dortania/Opencore-Legacy-Patcher#58]
hey,

thanks for your great work. My first MBP9,2 works well with generated config.plist.

i have read lots of hours opencore-documentation and generated config.plist for MacBookPro to understand the config-options. 
https://dortania.github.io/docs/latest/Configuration.html
https://dortania.github.io/OpenCore-For-Legacy-Macs/config.plist/macbookpro.html#starting-point

One things is important in my opinion:
"MaxBIOSVersion 
Type: plist boolean
Failsafe: false 
Description: Sets BIOSVersion to 9999.999.999.999.999, recommended for legacy Macs when using Automatic PlatformInfo to avoid BIOS updates in unofficially supported macOS versions. "

Can you insert please the "MaxBIOSVersion-Flag" into the generated config.plist file?

regards

**Comment by khronokernel** [comment]
Hi, we already include this option since this commit in January: https://github.com/dortania/Opencore-Legacy-Patcher/commit/50e3e08ff0e4e824c99492b71961c0dcff143cf1

**Comment by stschulze1972** [comment]
for MacPro ...but not Macbook Pro?!

**Comment by khronokernel** [comment]
Not sure what you mean for Mac Pro only? We have no code that selectively enables it, MaxBIOSVersion is always enabled on OpenCore 0.6.6+ builds(ie. [0.0.9](https://github.com/dortania/Opencore-Legacy-Patcher/releases/tag/0.0.9) and newer)

Also verified on my end, building a MacBookPro9,2 EFI does have it enabled:

<img width="912" alt="Screen Shot 2021-02-12 at 7 27 39 AM" src="https://user-images.githubusercontent.com/48863253/107780346-d0c78c00-6d03-11eb-8e47-fd93958d2848.png">

**Comment by stschulze1972** [comment]
Agree ...regards...works fine ....thanks for your great work
