### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RoagueB** [dortania/OpenCore-Legacy-Patcher#580]
### Machine Model

MacBookPro5,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

After Monterey Beta 10 installation Window-Server crashes after login-in into the desktop.  Crash can be triggered by clicking on any item on the _**right**_ side of the menu bar (e.g. control-center icon).   When window server fails it reverts to log-in screen, where credentials have to be re-entered. After a short time of use (not touching the right side of menu bar) the Window Server will start crashing without any "provocation".   

Additional Information:
Note that "reducing transparency" alleviates crushes triggered by clicking  icons on right side of the menu bar area.
***There is no brightness control nor choice of resolutions available in Display Control Panel; just single choice defaults.

See screen shot of the "back trace" error report:

![Screen Shot 2021-10-15 at 23 10 26](https://user-images.githubusercontent.com/92649714/137601178-4ded9a14-476e-49b2-895c-2132eaeb588a.png)

Thank you for any insight into resolving this issue.

### Any Additional Information

MacBookPro 5,1  (mid 2009) 17 inch, internal Samsung Evo SSD, 8 GB RAM , C2D 3.06 GHz
Graphics: NVIDIA GeForce 9600M GT 512 MB (used at all times) and NVIDIA GeForce 9400M (used if accidentally booted in that configuration)  
Note that MacBookPro 5,2 does not support automatic switching between video cards.

SSD partitioned into three sections, each holding a working operating system.

Container 1:  Monterey Beta10 and BigSur, with the latter's graphics accelerated  (via OCLP 0.3.1 TUI)
Container 2: Catalina (with latest updates - fully functional via Dosdude1's patcher)

**Comment by francois-cherreau** [comment]
Hi @khronokernel, I just installed Monterey on my MacBookPro 8,1 with the latest opencore version, and have the exact same behaviour as the one described in this ticket. It started appearing after the volume patch installation and the only way to recover in installing Monterey again.

I see that this ticket has been raised for MacBookPro 5,2, but Do you think it’s the me same issue ? In that case how could I fix this on my machine ?

Many thanks for any advice…and congratulations for all this great work 😉
