### ISSUE TITLE
[Bug]: iMac13,2 Ethernet card not recognized

### ISSUE THREAD

**Issue by Gorkrul** [dortania/OpenCore-Legacy-Patcher#583]
### Machine Model

iMac13,2

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

original ethernet card is not recognized
![Bildschirmfoto 2021-10-17 um 15 37 19](https://user-images.githubusercontent.com/65006618/137629595-1c85a04e-2129-449b-9d5c-cd19df58e4c6.png)

running windows 11 on the same machine (bootcamp) and the ethernet card is working fine 
1000Mbit/s

### Any Additional Information

Wifi works fine

**Comment by khronokernel** [comment]
Likely a botched macOS environment, you have the same Ethernet chipset as natively supported iMacs. Unless this is a Sandy Bridge or older Mac, Apple's native AppleBCM5701Ethernet.kext driver supports any Mac with VT-D for DMA protection (ie. Ivy Bridge and newer CPUs). And all stock iMac13,x ship with Ivy Bridge CPUs

Nothing we can do on our end, reinstall macOS and troubleshoot further. If you believe this to be a genuine OCLP issue, feel free to comment here with your research and reasoning
