### ISSUE TITLE
MBP5,3 incompatible with OLP v0.0.10

### ISSUE THREAD

**Issue by kommtzeitkonrad** [dortania/Opencore-Legacy-Patcher#59]
Since 4dcebb49068b34a42ddd32455a73c171b65ee2b0 it is not possible to boot OpenCore built from Opencore-Legacy-Patcher on a MacBookPro5,3. It fails to boot with:

```
OC: Failed to allocate absolute path
OCM: Failed to start image – Out of Resources
BS: Failed to start OpenCore image – Out of Resources
BS: Failed to load OpenCore from disk – Out of Resources
```

75587ab3451c47cfe2f99955dc55186ba1f356da did not fix this. Resetting NVRAM also does not help.

**Comment by khronokernel** [comment]
You can attempt to set `LauncherOption` to `Short` or `Disabled`(test in that order), if that doesn't resolve it then I believe this would be considered an OpenCore bug

**Comment by kommtzeitkonrad** [comment]
> You can attempt to set `LauncherOption` to `Short` or `Disabled`(test in that order)

Thanks for your suggestion! :-) Ok, let's be more specific.

This system is used:
- MacBookPro5,3
- Boot-ROM-Version: MBP53.00AC.803
- SMC-Version (System): 1.48f2
- SSD is wiped/empty
- macOS 10.12.6 bootable installer (not natively supported by MBP5,3)
- SMC & NVRAM/PRAM resetted

1. EFI/USB setup:
- Opencore-Legacy-Patcher 0.0.9 / 4dcebb49068b34a42ddd32455a73c171b65ee2b0
- OpenCore 0.6.6 from https://github.com/dortania/Opencore-Legacy-Patcher/commit/50e3e08ff0e4e824c99492b71961c0dcff143cf1
- EFI files: [EFI-MBP53-OLP009-OC066.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5969972/EFI-MBP53-OLP009-OC066.zip)

OpenCore and macOS Sierra installer will boot without any problems.

2. EFI/USB setup:
- Opencore-Legacy-Patcher 0.0.11 / 75587ab3451c47cfe2f99955dc55186ba1f356da
- OpenCore 0.6.6 from https://github.com/dortania/Opencore-Legacy-Patcher/commit/8ed5fd83975080d275b2bda98cfe7494cff10a21
- EFI files: [EFI-MBP53-OLP0011-OC066.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/5969976/EFI-MBP53-OLP0011-OC066.zip)

In all three cases (`Misc:Boot:LauncherOption` set to `Disabled`, `Full` or `Short`) the following verbose output is displayed:

```
OC: Failed to allocate absolute path
OCM: Failed to start image – Out of Resources
BS: Failed to start OpenCore image – Out of Resources 
BS: Failed to load OpenCore from disk – Out of Resources

***********************************************************
This version of Mac OS X is not supported on this platform!
***********************************************************
Reason: Mac-F22587CB
```
When SMC & NVRAM/PRAM are resetted again at this point only an error sign is displayed when booting OpenCore.

**Comment by kommtzeitkonrad** [comment]
> […] then I believe this would be considered an OpenCore bug

You're right! The bug seems to be introduced in https://github.com/acidanthera/OpenCorePkg/commit/1c445a99d653a510b5561b2995735db2d7b3d611.

**Comment by EeksBoks7** [comment]
I am getting this on a desktop server board pls help!

**Comment by kommtzeitkonrad** [comment]
The problem (firmware is not specifying image handle at bootstrap) is fixed in https://github.com/acidanthera/OpenCorePkg/commit/b4449f48dd01703b5766352b6f29717415aff08b.

**Comment by khronokernel** [comment]
Looks good to me, updated in master
