### ISSUE TITLE
[Bug]: GPU Hangs with Intel HD Graphics 3000 randomly

### ISSUE THREAD

**Issue by Doregon** [dortania/OpenCore-Legacy-Patcher#594]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Please take note that **I am reporting this issue from a Hackintosh.** I am aware you do not provide complete support for Hackintoshes, this is also in case real OCLP'd Mac encounter this issue. `MacBookPro8,1` is similar to my setup as it has only an HD3000 and a Sandy Bridge CPU. Feel free to close this issue is it's not reproducible on your test devices and/or if it is misconfiguration on my part. This issue seemed to be common among 2011-2012 Macs back with OS X 10.8 iirc; it was either ignored or patched with a certain version of OS X.

The tl;dr is that when the GPU is under some strain (in my case, opening applications rapidly) or at random, the system freezes. The mouse can still be used and command line access is still available, but WindowServer doesn't respond to anything anymore. In order to fix the freeze, you need to physically force the system off by holding the power button--simply sending `sudo killall -11 WindowServer` or `sudo shutdown now` does not work.

I have attached the output of the following commands. Let me know if I should attach more:
```bash
sudo dmesg
log show | grep CoreDisplay
log show | grep WindowServer
kextstat | grep Graphics
```

This has occurred on the following OS versions:
```
macOS Big Sur 11.3.1 (20E241)
macOS Big Sur 11.5.2 (20G95)
macOS Monterey 12.0 beta 6 (21A5506j)
macOS Monterey 12.0 beta 10 (21A5552a)
macOS Monterey 12.0.1 (21A558)
```
I will install DebugEnhancer once I'm home and see what I can do to cause the issue again to get more detailed logs.

### Any Additional Information

[kextstatgrepgraphics.log](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7383588/kextstatgrepgraphics.log)
[logshowgrepCoreDisplay.log](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7383590/logshowgrepCoreDisplay.log)
[logshowgrepWindowServer.log](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7383591/logshowgrepWindowServer.log)
[sudodmesg.log](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7383593/sudodmesg.log)

**Comment by khronokernel** [comment]
After some more testing we're unable to replicate with an HD3000 equipped demuxed MacBookPro8,2. However feel free to research further yourself and submit patch sets, we'd greatly appreciate the aid
