### ISSUE TITLE
Secure Boot not working on older firmwares

### ISSUE THREAD

**Issue by kommtzeitkonrad** [dortania/Opencore-Legacy-Patcher#60]
It seems that to boot macOS ≥ 10.13 on a MacBookPro5,3 it is needed to set `SecureBootModel` to `Disabled`. Neither setting it to `x86legacy` nor triggering `Booter:Quirks:ProtectSecureBoot`, `Kernel:Quirks:ForceSecureBootScheme` and/or `UEFI:ProtocolOverrides:AppleSecureBoot` does help. Resetting NVRAM also does not help.

**Comment by khronokernel** [comment]
SecureBootModel set to j137/Default doesn't work? That's what the patcher currently uses, as we require it to support native OS updates in Big Sur

Could you elaborate more on what error you face on boot up?

**Comment by kommtzeitkonrad** [comment]
Using Opencore-Legacy-Patcher 0.0.9 (4dcebb49068b34a42ddd32455a73c171b65ee2b0) with OpenCore 0.6.6 and setting `Misc:Security:SecureBootModel` to `j137/Default` works. Thank you very much!
