### ISSUE TITLE
[Bug]: keyboard back light function stoped working

### ISSUE THREAD

**Issue by AJr2021** [dortania/OpenCore-Legacy-Patcher#601]
### Machine Model

MacBookPro6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

after running the system patcher, keyboard light went off, and keyboard back light control keys stoped functioning.

**Comment by emitt234** [comment]
Same happen to me
