### ISSUE TITLE
[Bug]: Monterey RC2 will not boot on MBP11,3, likely related to NVIDIA patches

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#606]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

I updated my secondary 11,3 to Monterey RC2, and with it, to OCLP 0.3.0. After the update was ran I went into safe mode to patch the system drive, which patched fine. But then, when I tried to boot normally, the boot just hangs at about 40 - 45% of the progress bar and fans ramp up.

Going back to safe mode: The scaling now works, and the GT 750m is shown on the About this Mac page. I was suggested to remove the patches, restart and then patch again, but that didn't work either.

My main MacBook Pro 11,3 is also on Monterey RC2, except this MBP has the dGPU disabled as I am using it with an eGPU setup, and it's working totally fine.

**Comment by cukabeka** [comment]
I have this issue with a MBP8,2 when updating from a working big sur install and cant figure out what to do at the stuck bootscreen.
