### ISSUE TITLE
[Bug]: Sleep Wake failure in EFI on MacBook Pro 9,1 (mid 2012)

### ISSUE THREAD

**Issue by BoredFishRE** [dortania/OpenCore-Legacy-Patcher#609]
### Machine Model

MacBookPro9,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Macbook crashes on wake, and causes shutdown. Kernel panic is produced. Sleep Wake failure in EFI. On latest release. Log has been attached.

### Any Additional Information

Sleep Wake failure in EFI

Failure code:: 0x00000000 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2021-10-23 09:18:19.734 -0400
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   32

Data Source:      Stackshots
Shared Cache:     1FB62A50-25C7-3F72-8054-A70CD3CA5953 slid base address 0x7fff2004a000, slide 0x4a000

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        keepsyms=1 debug=0x100

Time Awake Since Boot: 79s

Process:          swd [364]
Architecture:     x86_64
Footprint:        352 KB
Time Since Fork:  2s
Num samples:      1 (1)

  Thread 0x952    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 89917) [0x7fff20373f3d] 1
    1  ??? [0x101a21454] 1
      1  ??? [0x101a211e8] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 146934) [0x7fff20345df6] 1
         *1  ??? [0xffffff80002321f6] 1
           *1  ??? [0xffffff800093f1de] 1
             *1  ??? [0xffffff80008493d1] 1
               *1  ??? [0xffffff80002554ff] 1
                 *1  ??? [0xffffff800028c7fd] (running) 1

  Binary Images:
        0x7fff20322000 -     0x7fff20351fff  libsystem_kernel.dylib (7195.141.6) <78289AAE-61B5-339F-A485-8819BC2388F2>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff2035e000 -     0x7fff20399fff  libdyld.dylib (852.2)               <3DE0178A-0AEE-3D08-AE19-6C6403F69BA1>  /usr/lib/system/libdyld.dylib
Model: MacBookPro9,1, BootROM 9999.999.999.999.999, 4 processors, Quad-Core Intel Core i7, 2.7 GHz, 16 GB, SMC 9.9999
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGT650MItem, NVIDIA GeForce GT 650M, spdisplays_pcie_device, 1 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x435438473353313630424D2E4D3136464544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x435438473353313630424D2E4D3136464544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.8)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: M4-CT512M4SSD2, 512.11 GB
Serial ATA Device: OPTIARC DVD RW AD-5970H
USB Device: USB 3.0 Bus
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by soloofboom** [comment]
> I have seemingly fixed this on my MacBookPro9,1 by setting `ConnectDrivers` to false in the config plist

Without breaking anything else?

**Comment by WashJotson** [comment]
> > I have seemingly fixed this on my MacBookPro9,1 by setting `ConnectDrivers` to false in the config plist
> 
> Without breaking anything else?

Yeah, now have two running Big Sur 11.6.1 seemingly perfectly. Both machines have upgraded ac WiFi and I'm not using any external peripherals with them.

I tried Monterey on one machine and it did not seem to work properly at all; some kind of display/gpu issue, so no brightness; sleep not working and very slow performance. Big Sur seems to work really well though!
