### ISSUE TITLE
Possible to set nvram variable fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs ??

### ISSUE THREAD

**Issue by jacksonium** [dortania/Opencore-Legacy-Patcher#61]
What do i need to do if i want to put the equivalent to this into opencore config.plist? 
Under MacOS: nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00
Under Linux: printf "\x07\x00\x00\x00\x01\x00\x00\x00" > gpu-power-prefs-fa4ce28d-b62f-4c99-9cc3-6815686e30f9

I tried to create a Dictionary fa4ce28d-b62f-4c99-9cc3-6815686e30f9 under NVRAM ADD, then create a child gpu-power-prefs with type DATA and <01000000> and it didnt work.

What i want to achieve is to ensure this nvram variable is set prior to booting, because nvram reset would delete this and I want this to get set again, this is for disabling the faulty AMD GPU on macbook pro 2011 (MacBookPro8,2). Is this even possible?

**Comment by khronokernel** [comment]
Not a current priority, you can PR this functionality into OCLP if desired

**Comment by fromage9747** [comment]
I have a 17 inch mbp 8.3 and also would like this. Any possibility of it happening?

**Comment by fromage9747** [comment]
@jacksonium I have been doing some more testing and fiddling.  I believe the problem is that it needs to be converted to Hexidecimal for OC to be able to use it.  For example, SIP enabled is:
<key>csr-active-config</key>
<data>AAAAAA==</data>

AAAAAA== is equivalent to %00%00%00%00 or 00000000.

So we just need the Hexidecimal format for %01%00%00%00 or 01000000 in order for OC to accept it and use it as a NVRAM variable.

**Comment by fromage9747** [comment]
So after some googling, I found that Hackintool does the conversion. 

![image](https://user-images.githubusercontent.com/23147783/126962467-50b1cfd5-96c8-4c0f-bf0c-88d48f1d8b6e.png)

I am gonna add it to my NVRAM on my Macbook Pro 2011 17" and see how it goes.

**Comment by fromage9747** [comment]
Well I rebooted with the below set and nothing bad happened:

![image](https://user-images.githubusercontent.com/23147783/126964865-33cc1940-8361-4cce-bbbf-8fb9fbbca928.png)

I also have -wegnoegpu added to the boot arguments in OC.

**Comment by jacksonium** [comment]
cool! and nothing bad happened... but more importantly.. did it work tho?

**Comment by fromage9747** [comment]
@jacksonium I tried to do a print out of the NVRAM as per the below: 
sudo nvram -p | grep 'gpu-power-prefs'

From this: https://www.tonymacx86.com/threads/opencore-nvram-problem.296517/

But nothing was returned, just like the OP in that guide did not have anything returned. 

I tested with:
sudo nvram -p | grep 'csr-active-config'

And that does return a value.

I guess it really isn't supported by OC?

If I open up OC and right-click under NVRAM it gives me some values that I can choose from:

![image](https://user-images.githubusercontent.com/23147783/127035003-4c0c7e40-d7de-4e3d-bc73-48cf0d3587e4.png)

If I click to the next section for the gpu-power-prefs, it gives me nothing.

**Comment by protocold** [comment]
now with the power down implemented in OCLP.. Is there a possibility to get this re-investigate? This may be to be looked at upstream but I am not sure. 

The reason is if NVRAM is reset, then the variable is gone.. if OCLP can set this variable this would really complete the fix.

**Comment by protocold** [comment]
@startergo mentioned on this thread below about using one of dosdude's tool as a userspace daemon in Big Sur to re-instate the nvram variable, I havent tried this myself.. 

https://github.com/acidanthera/bugtracker/issues/928
