### ISSUE TITLE
[Bug]: iMac7,1 USB problems on Monterey

### ISSUE THREAD

**Issue by ghost** [dortania/OpenCore-Legacy-Patcher#620]
### Machine Model

iMac7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

On iMac7,1 (2007) with upgraded CPU, USB ports fail to load during boot. Sometimes it will not boot to the USB installation media, and if it boots keyboard and mouse will not be recognized and powered. AppleUSBHostPort::disconnect: persistent enumeration failures is shown during boot. Will try booting Big Sur to see if it persists.

**Comment by thekryz** [comment]
@ghost

> Okay, I did some research and this is actually two problems existing in my configuration. The first is I upgraded to BCM94352HMB wireless and I forgot to deselect the Brcm9360 kext, preventing the system to load. The second is the USB 1.1 controller among these Macs are broken, thus disabling the mouse and keyboard. Using a USB hub solved the problem.

I seem to have a similar issue with my 24" iMac7,1 (upgraded with a T9500 and SSD). The Mac shows the Apple logo when booting, then shows two alternating pictures of what looks like an Apple Mouse with the green "On"-button and ... something else with a green "On"-button. There is a mouse pointer in the corner, but moving the mouse won't do anything.
I was not aware of broken USB-controllers. How exactly did you fix your issue? Just add a USB hub to any of the three USB-ports and connect mouse and keyboard to them? Did you also connect your OpenCore USB drive to the hub or was that on a native port? Or is my issue different from yours?
