### ISSUE TITLE
[Bug]: Mid-2014 Retina MacBook Pro (MacBookPro11,3) After installation it will stuck at Apple Logo with a Progress bar at 30% forever.

### ISSUE THREAD

**Issue by vishnunuk** [dortania/OpenCore-Legacy-Patcher#623]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

1) After installation it will stuck at Apple Logo with a Progress bar at 30% forever.

Actually my Mac is booted and telling me to use VoiceOver.

But the fix for this issue is very simple and mentioned [here](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/522).

To trigger Safe Mode from OpenCore's Picker:
 Press Shift +Enter on the macOS entry
To disable the dGPU for UEFI:

**sudo nvram FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-power-prefs=%01%00%00%00**

Arg can be set to %00%00%00%00

when user has root patched Kepler support back in

2)  Brightness control not working.

When I press the brightness control key nothing happening. 

In Action centre brightness control is disabled. We cannot control it from there. 

3) Apple logo is still glowing even after lid is completely closed

Even After Lid Completely closed Apple logo is glowing and Mac is not turning off or going to sleep.

**Comment by krim404** [comment]
Issue is there again on 0.4.1
