### ISSUE TITLE
[Bug]: Safari window stops refreshing (so e.g. scrolling becomes invisible) - Intel HD 3000

### ISSUE THREAD

**Issue by pond** [dortania/OpenCore-Legacy-Patcher#640]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

First up, I'm astonished at how well Monterey runs on a 2011 15" MBP under OpenCore. It's a remarkable achievement by all concerned. The installation was _very_ easy. I actually started off with Big Sur, but saw quite a lot of graphical glitches with HD 3000 once acceleration was enabled post-install - so I decided "hey, why not!" for Monterey.

Monterey actually seems a lot more stable for graphics and to my surprise seems overall more usable. Some visual bugs from Big Sur persist, but a lot seemed to disappear, at least in my case. However, one kinda killer issue cropped up only in Monterey:

* In Safari, scrolling usually works immediately after a reboot, but after "a while" (and I can't find a causal relationship to e.g. lock screen, sleep, other apps running - it just "happens") scrolling appears to suddenly stop working.
* What's _actually_ happening is that all Safari visual updates don't work, including e.g. animations within web pages; the refresh to the display itself seems broken. Under the hood, things are actually moving around - mouse hover tooltips etc. give that away - and there are ways to force a visual update, such as switching to another app or resizing the Safari window.
* Restarting Safari does not fix the problem. A reboot is required, but the problem recurs within a few minutes.

### Any Additional Information

Behaviour appears to be the same with 6770M acceleration enabled via turning on [ATI TeraScale 2 per docs](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#cannot-login-on-2011-15-and-17-macbook-pros) but I ultimately disabled the dGPU via `nvram ... gpu-power-prefs ...` as I didn't want the power drain given no support for dynamic switching yet, with HD 3000 being fine for the use cases at hand.

I can't find anything alluding to this in the [know issues list](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108#issuecomment-810634088) and although I'm working with the 0.3.1 release build right now as the nightly had trouble patching after enabling TeraScale, I did try the nightly build for ~27th October (UTC) (EDIT: nightly build used for just the iGPU, no TeraScale enabled & dGPU disabled) and the problem persisted with that too.

If it's potentially of use or in any way related as an indication of what might be wrong - because of course, it could be my installation itself that's broken and not a bug in the legacy patcher stack per se - then I do also notice missing icons here and there (but this did also happen in Big Sur) - e.g. if visiting System Preferences -> Accessibility, the large category icons in the left hand pane very briefly show before _most_ but not all suddenly vanish. This may, though, be entirely unrelated.

**Comment by khronokernel** [comment]
Update issue to reflect:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
