### ISSUE TITLE
[Bug]: MacBook Pro 8,1  won’t boot 

### ISSUE THREAD

**Issue by n3xus1** [dortania/OpenCore-Legacy-Patcher#649]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

Mac OS won’t boot with latest GitHub CLI on MBP8,1 
Just hangs 
![60AD8C7D-BE85-4957-97D1-71E5E9FF571F](https://user-images.githubusercontent.com/6356263/139309352-746b569d-c9c7-4e51-b6ab-721737dffa39.jpeg)

**Comment by Elvis-Budingensis** [comment]
Thanks, is there an explanation how to "unpatch"?

**Comment by Ausdauersportler** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/POST-INSTALL.html#post-installation
