### ISSUE TITLE
[Bug]: Bluetooth not working BCM94331PCIEBT4CAX 

### ISSUE THREAD

**Issue by anthony0030** [dortania/OpenCore-Legacy-Patcher#654]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I can't enable bluetooth.

### Any Additional Information

I have a MacBook pro late 2011 with an upgraded nic, AirPort Extreme (BCM94331PCIEBT4CAX)

**Comment by khronokernel** [comment]
Send the build folder OCLP generates as well as the following:

```sh
system_profiler SPUSBDataType > ~/desktop/USB-Data.plist
```

**Comment by Marty56** [comment]
Same bug using V 3.1 of OCLP on a MacBookAir4,2 running Monterey.
Wifi is working.

`  Bluetooth-Controller:
  Adresse:	NULL
  Status:	Aus
  Chipsatz:	BCM_4350C2
  Sichtbar:	Aus
  Firmwareversion:	v0 c0
  Produkt-ID:	0x0001
  Unterstützte Dienste:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  Transport:	USB
  Hersteller-ID:	0x004C (Apple)`

**Comment by anthony0030** [comment]
```system_profiler SPUSBDataType > ~/desktop/USB-Data.plist```


```
2021-10-30 14:38:19.251 system_profiler[2316:11744] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-10-30 14:38:19.253 system_profiler[2316:11744] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-10-30 14:38:19.253 system_profiler[2316:11744] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
```

**Comment by khronokernel** [comment]
When I said run the command, I expect you to send the file generated on the desktop

**Comment by anthony0030** [comment]
I did not realize that it generated a file, I feel STOOPID.

```
USB:

    USB 2.0 Bus:

      Host Controller Driver: AppleUSBEHCIPCI
      PCI Device ID: 0x1c26 
      PCI Revision ID: 0x0005 
      PCI Vendor ID: 0x8086 

        Hub:

          Product ID: 0x2513
          Vendor ID: 0x0424  (SMSC)
          Version: b.b3
          Speed: Up to 480 Mb/s
          Location ID: 0xfd100000 / 1
          Current Available (mA): 500
          Current Required (mA): 2
          Extra Operating Current (mA): 0
          Built-In: Yes

            IR Receiver:

              Product ID: 0x8242
              Vendor ID: 0x05ac (Apple Inc.)
              Version: 0.16
              Speed: Up to 1.5 Mb/s
              Manufacturer: Apple Computer, Inc.
              Location ID: 0xfd110000 / 2
              Current Available (mA): 500
              Current Required (mA): 100
              Extra Operating Current (mA): 0
              Built-In: Yes

    USB 2.0 Bus:

      Host Controller Driver: AppleUSBEHCIPCI
      PCI Device ID: 0x1c2d 
      PCI Revision ID: 0x0005 
      PCI Vendor ID: 0x8086 

        FaceTime HD Camera (Built-in):

          Product ID: 0x8509
          Vendor ID: 0x05ac (Apple Inc.)
          Version: 5.16
          Serial Number: CC2C2J0522DG6LL0
          Speed: Up to 480 Mb/s
          Manufacturer: Apple Inc.
          Location ID: 0xfa200000 / 1
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0
          Built-In: Yes

        Hub:

          Product ID: 0x2513
          Vendor ID: 0x0424  (SMSC)
          Version: b.b3
          Speed: Up to 480 Mb/s
          Location ID: 0xfa100000 / 2
          Current Available (mA): 500
          Current Required (mA): 2
          Extra Operating Current (mA): 0
          Built-In: Yes

            Apple Internal Keyboard / Trackpad:

              Product ID: 0x0253
              Vendor ID: 0x05ac (Apple Inc.)
              Version: 1.18
              Manufacturer: Apple Inc.
              Location ID: 0xfa120000

            BRCM20702 Hub:

              Product ID: 0x4500
              Vendor ID: 0x0a5c  (Broadcom Corp.)
              Version: 1.00
              Manufacturer: Apple Inc.
              Location ID: 0xfa110000

                Broadcom Bluetooth Download Device:

                  Product ID: 0xf007
                  Vendor ID: 0x05ac (Apple Inc.)
                  Version: 1.56
                  Manufacturer: Broadcom Corp
                  Location ID: 0xfa113000


```

[USB-Data.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7446762/USB-Data.plist.zip)

**Comment by anthony0030** [comment]
![kj6vhhc2ty371](https://user-images.githubusercontent.com/13033263/139536524-519efa23-e606-407a-9cb3-6edcd247f659.jpg)

**Comment by Marty56** [comment]
[USB-Data.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7447069/USB-Data.plist.zip)

**Comment by Marty56** [comment]
why is this issue closed? Is there a bugfix?

**Comment by dhinakg** [comment]
![image](https://user-images.githubusercontent.com/17605561/139541641-2d44f238-87bc-43cf-8881-21f36a2c7940.png)
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/dc4238fb097b525db8fd390334b386f5b09e19be

**Comment by anthony0030** [comment]
Where can I download the new nightly version?

**Comment by Ausdauersportler** [comment]
Please use Discord to chat and ask!

**Comment by anthony0030** [comment]
I think I found it https://discord.gg/rqdPgH8xSN

**Comment by AEAEAEAE4343** [comment]
I'm still having this issue on my MacBookPro9.1 running macOS 12.1 RC. I'm using the latest version of OpenCore, which was released a couple of days ago. Wi-Fi is working fine but I can't get Bluetooth to do anything. BT worked normally on Big Sur. 

System Profiler:
```
  Bluetooth-controller:
  Adres:			NULL
  Status:			Uit
  Chipset:			BCM_4350C2
  Detecteerbaar:		Uit
  Firmwareversie:		v0 c0
  Productcode:			0x0001
  Ondersteunde apparaten:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  Transport:			USB
  Fabrikantcode:		0x004C (Apple)
```

I read that killing bluetool and bluetoothd might fix it temporarily, but it doesn't.

**Comment by AEAEAEAE4343** [comment]
By the way, should I make a new issue as this issue is already closed?
