### ISSUE TITLE
[Bug]: iMac14,1 doesn't output signal over mDP to external monitor with OCLP 0.3.0 or above

### ISSUE THREAD

**Issue by dinoholic** [dortania/OpenCore-Legacy-Patcher#661]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

Hello!

iMac14,1 doesn't output signal over mDP to external monitor with OCLP 0.3.0 or 0.3.1. External display works fine with OCLP 0.2.5 and 0.2.4.

Since I don't know any better, I'm diff'ed EFI/OC/config.plist between OCLP 0.2.5. and 0.3.0.
I'll try copying entires from the older config to the newer one bit by bit to see if anything fixes it. Shouldn't take too long since there are only a few differences. Think I'll start with NVRAM entries, then SMBIOS. The rest of the entries (board ids, etc) seem to be connected with the change from spoofed iMac16,1 to iMac17,1.

Please do let me know if anyone has a better idea how to troubleshoot this. Any help would be appreciated!

Thank you for your efforts :)

**Comment by jmakjim** [comment]
Experience same issue for iMac14,1 OCLP 0.3.1 macOS 12.0.1.

Just upgrade from macOS 11.6.1 with Big-Sur-Micropatcher to macOS 12.0.1 with OCLP 0.3.1.

**Comment by khronokernel** [comment]
Does mainline replicate this issue? VMM should remove any display issues

**Comment by Netwy** [comment]
I got my opened issue because it's the same error. I resolved it adding, agdpmod=vit9696 to NVRAM > add > and then look for boot-args
