### ISSUE TITLE
[Bug]:  MacBookPro9,2-  can't change brightness on screen

### ISSUE THREAD

**Issue by Firefoxx81** [dortania/OpenCore-Legacy-Patcher#662]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

after log in in macos my screen are dimmed down and when i press F1 and F2 (dim up down) nothing is happend, when i get into sys pref for screen the options are not for macbookpro screen it´s for a generic screen and the is no settings for backlights.
I found https://www.youtube.com/watch?v=UDev1FdhUr8 for a solution but i don´t understand how to use it, so can you add this fix to OCLP?

**Comment by khronokernel** [comment]
Run Post Install root volume patches to enable GPU acceleration

**Comment by Firefoxx81** [comment]
It´s worked with the Post Installer! Thx for you quick answer!
