### ISSUE TITLE
[Bug]: Fuzzy pixelated edges in macOS Monterey (iMac 14.1

### ISSUE THREAD

**Issue by saeedgolzar** [dortania/OpenCore-Legacy-Patcher#663]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I updated my iMac (Late 2013) to macOS Monterey with opencore. as you can see in attached screenshot screen edges in dock and control center are fuzzy pixelated. how can i fix that?
Sorry for my poor english.

![Screen Shot 2021-10-29 at 11 16 26 PM](https://user-images.githubusercontent.com/23401064/139495559-b8ef741b-1a0b-40ec-a8ea-a7f3c9f6993b.png)

**Comment by khronokernel** [comment]
Apple bug affecting native machines such as MacBookPro11,4, nothing we can do. Wait for Apple to fix
