### ISSUE TITLE
[Bug]: iMac 14,4 Thunderbolt HDMI doesn't work

### ISSUE THREAD

**Issue by Netwy** [dortania/OpenCore-Legacy-Patcher#664]
### Machine Model

iMac14,4

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hi. I just installed macOs Monterey with the OpenCore Legacy Patcher v0.3.1, in the iMac 14,4. The HDMI external monitor/TV isn't working. 
I tried different things, but nothing seems help. if somebody can help me, i attach my config.plist. Thanks 
[config.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7445530/config.plist.zip)

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/661
