### ISSUE TITLE
[Bug]: MacBook 8.1 won't boot with 0.3.2 nightly build, but with 0.3.1 

### ISSUE THREAD

**Issue by Elvis-Budingensis** [dortania/OpenCore-Legacy-Patcher#666]
### Machine Model

MacBook8,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

Built 0.3.2 and patched the Volume. After restart booting stucks with 25% and nothing happens for hours. Booting with 0.3.1 works fine. It also occurs after shutdown and power on, always with 0.3.2 nightly. I attached the Kernel Panics file.

### Any Additional Information

panic(cpu 0 caller 0xffffff80005e5b53): Kernel trap at 0xffffff7f818269cb, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffff9aa36f2eb0, CR3: 0x000000045516b00e, CR4: 0x00000000000626e0
RAX: 0xffffff92a3772ea0, RBX: 0xffffff92a3aef800, RCX: 0x00000000ffff0002, RDX: 0x0000000000001001
RSP: 0xffffffd06e8d3930, RBP: 0xffffffd06e8d3930, RSI: 0x00000000ffff0002, RDI: 0xffffff92a37ce000
R8:  0xffffff80014b1658, R9:  0x0000000000000008, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0x0000000080001003, R15: 0x0000000000000000
RFL: 0x0000000000010293, RIP: 0xffffff7f818269cb, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff9aa36f2eb0, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Panicked task 0xffffff852c1dd120: 7 threads: pid 159: WindowServer
Backtrace (CPU 0), panicked thread: 0xffffff852c1e9b70, Frame : Return Address
0xffffffd06e8d3360 : 0xffffff800049c00d mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd06e8d33b0 : 0xffffff80005f5d85 mach_kernel : _kdp_i386_trap + 0x145
0xffffffd06e8d33f0 : 0xffffff80005e5763 mach_kernel : _kernel_trap + 0x533
0xffffffd06e8d3440 : 0xffffff800043ba60 mach_kernel : _return_from_trap + 0xe0
0xffffffd06e8d3460 : 0xffffff800049c3dd mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd06e8d3580 : 0xffffff800049bb96 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd06e8d35e0 : 0xffffff8000d18649 mach_kernel : _panic + 0x54
0xffffffd06e8d3650 : 0xffffff80005e5b53 mach_kernel : _sync_iss_to_iks + 0x2c3
0xffffffd06e8d37d0 : 0xffffff80005e5838 mach_kernel : _kernel_trap + 0x608
0xffffffd06e8d3820 : 0xffffff800043ba60 mach_kernel : _return_from_trap + 0xe0
0xffffffd06e8d3840 : 0xffffff7f818269cb com.apple.driver.AppleIntelSNBGraphicsFB : __ZN23AppleIntelSNBGraphicsFB13getFBFromPipeEj + 0xd
0xffffffd06e8d3930 : 0xffffff7f81823e49 com.apple.driver.AppleIntelSNBGraphicsFB : __ZN21AppleIntelFramebuffer14setDisplayModeEii + 0xa9
0xffffffd06e8d3990 : 0xffffff7f81c0c88e com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer16doSetDisplayModeEii + 0x128
0xffffffd06e8d3a20 : 0xffffff7f81c0c6f1 com.apple.iokit.IOGraphicsFamily : __ZN13IOFramebuffer17extSetDisplayModeEP8OSObjectPvP25IOExternalMethodArguments + 0x97
0xffffffd06e8d3ab0 : 0xffffff8000c8dd3e mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffffd06e8d3b00 : 0xffffff7f81c13124 com.apple.iokit.IOGraphicsFamily : __ZN23IOFramebufferUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x82
0xffffffd06e8d3b50 : 0xffffff8000c97feb mach_kernel : _is_io_connect_method + 0x3db
0xffffffd06e8d3cb0 : 0xffffff800059f614 mach_kernel : _iokit_server_routine + 0x4e84
0xffffffd06e8d3dc0 : 0xffffff8000476cf9 mach_kernel : _ipc_kmsg_send + 0x449
0xffffffd06e8d3e50 : 0xffffff800048dd89 mach_kernel : _mach_msg_overwrite_trap + 0x2d9
0xffffffd06e8d3ee0 : 0xffffff80005caaf2 mach_kernel : _mach_call_munger64 + 0x272
0xffffffd06e8d3fa0 : 0xffffff800043c246 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.iokit.IOGraphicsFamily(593.0)[D7EBF011-CEEF-3DF8-BD85-6CCE427455B7]@0xffffff7f81bee000->0xffffff7f81c1cfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[5E1B0BE0-4B73-35F5-9126-EB05FBB8BAF5]@0xffffff8002fdd000->0xffffff8003007fff
         com.apple.driver.AppleIntelSNBGraphicsFB(10.0.4)[628D2F1C-66EC-340F-AB0A-576401250CCC]@0xffffff7f8181a000->0xffffff7f8183ffff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[7EF77A11-B2B8-3CCF-9188-597E1279EDAC]@0xffffff8002b37000->0xffffff8002b38fff
            dependency: com.apple.iokit.IOGraphicsFamily(593)[D7EBF011-CEEF-3DF8-BD85-6CCE427455B7]@0xffffff7f81bee000->0xffffff7f81c1cfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[5E1B0BE0-4B73-35F5-9126-EB05FBB8BAF5]@0xffffff8002fdd000->0xffffff8003007fff

Process name corresponding to current thread (0xffffff852c1e9b70): WindowServer
Boot args: keepsyms=1 debug=0x100

Mac OS version:
21A559

Kernel version:
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
Kernel UUID: 19BD4E1B-0268-3EE0-BC66-91F035BC9429
KernelCache slide: 0x0000000000200000
KernelCache base:  0xffffff8000400000
Kernel slide:      0x0000000000210000
Kernel text base:  0xffffff8000410000
__HIB  text base: 0xffffff8000300000
System model name: MacBookPro8,1 *****
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 84240717578
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000139d236a16
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000004f84d29dc 0x0000000000000000
Zone info:
Foreign   : 0xffffff8004fe2000 - 0xffffff8004fef000
Native    : 0xffffff801d2bb000 - 0xffffffa01d2bb000
Readonly  : 0 - 0
Metadata  : 0xfffffff9da3ab000 - 0xfffffff9fa52e000
Bitmaps   : 0xfffffff9fa52e000 - 0xfffffffa0052e000

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/649
