### ISSUE TITLE
[Bug]: Monterey not successful on iMac 14.2 

### ISSUE THREAD

**Issue by vdi-cloud** [dortania/OpenCore-Legacy-Patcher#667]
### Machine Model

iMac14,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

The installation of Monterey on internal drive (NVMe or SSD) was not successful despite several attempts.  Always it got stuck at regardless of whether I upgrade (from Big Sur or Catalina) or do a fresh install. Progress bar does not progress for hours. Power off and on to resume installation brought no other result. 

Just for information: My Mac is upgraded with 3,5 GHz Quad-Core Intel Core i7, internal SSD (Samsung SSD 860 QVO 1TB Media), NVMe (INDMEM SSD DMPG3N 1TB Media) and 32 GB Ram. It has standard GPU (NVIDIA GeForce GT 755M 1 GB).

**Comment by khronokernel** [comment]
Use forums for troubleshooting

**Comment by ktolis** [comment]
same issue on 14.2 with Intel 660 NVMe and nVidia 780M 4GB
