### ISSUE TITLE
[Bug]: Parallels 17 crash on Monterey + OCLP 0.3.1 on MacBook Pro 8.3

### ISSUE THREAD

**Issue by hunvreou** [dortania/OpenCore-Legacy-Patcher#668]
### Machine Model

MacBookPro8,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Parallels 17 crash when started. Was working perfectly on Big Sur and OpenCore 0.3.0 on the same hardware with a MacBook Pro 8.3 with dGPU desactivated. Parallels install crash on the same context on a MacBook Pro 8.2. 

Parallels 17 runs perfectly on an IMac 12,2 with an NVidia GT680. 

### Any Additional Information

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               prl_client_app [4705]
Path:                  /Applications/Parallels Desktop.app/Contents/MacOS/prl_client_app
Identifier:            com.parallels.desktop.console
Version:               17.1.0 (51516)
Build Info:            Parallels-51516.0~17.1.51516.0
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-10-30 13:34:06.1509 +0200
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        3B38DB01-BFB6-1BE3-1B7F-715884B45D11

Sleep/Wake UUID:       01E31B0C-4546-46FF-BE1A-08AB3315C788

Time Awake Since Boot: 3800 seconds
Time Since Wake:       491 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4705]

VM Region Info: 0 is not in any region.  Bytes before following region: 4500619264
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10c420000-10e660000    [ 34.2M] r-x/r-x SM=COW  ...rl_client_app

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	               0x0 ???
1   prl_client_app                	       0x10c5309b9 0x10c420000 + 1116601
2   prl_client_app                	       0x10c530b3c 0x10c420000 + 1116988
3   prl_client_app                	       0x10c993d8a 0x10c420000 + 5717386
4   prl_client_app                	       0x10c994018 CPdCatalogManagerDelegate::CPdCatalogManagerDelegate(QObject*) + 56
5   prl_client_app                	       0x10c5502b6 0x10c420000 + 1245878
6   prl_client_app                	       0x10c4c0703 0x10c420000 + 657155
7   dyld                          	       0x113d3f4fe start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff80d88500c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff80d88500c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff80d88500c start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010e680090  rbx: 0x00006000022665c0  rcx: 0x0000000000000000  rdx: 0x00006000022665c0
  rdi: 0x000000010c530920  rsi: 0x00000000000002db  rbp: 0x00007ff7b3adf830  rsp: 0x00007ff7b3adf808
   r8: 0x0000000000000001   r9: 0xffffffff00000000  r10: 0x00007ff84effeb68  r11: 0x0000000000000000
  r12: 0x0000000000000001  r13: 0x00007ff7b3adfab8  r14: 0x000000010c530920  r15: 0x000000010e756c38
  rip: 0x0000000000000000  rfl: 0x0000000000010206  cr2: 0x0000000000000000
  
Logical CPU:     4
Error Code:      0x00000014 (no mapping for user instruction read)
Trap Number:     14

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x10c420000 -        0x10e65ffff com.parallels.desktop.console (17.1.0) <a51e8bfb-511a-39ab-9146-6f859e347a43> /Applications/Parallels Desktop.app/Contents/MacOS/prl_client_app
       0x113d3a000 -        0x113da5fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld
    0x7ff80d883000 -     0x7ff80d88efff libsystem_pthread.dylib (*) <29a2750e-f31b-3630-8761-242a6bc3e99e> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=585.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=585.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          148K       21 
Kernel Alloc Once                    8K        1 
MALLOC                           191.6M       27 
MALLOC guard page                   16K        4 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        4 
Stack                             9752K        4 
VM_ALLOCATE                         16K        4 
__CTF                               759        1 
__DATA                            32.1M      529 
__DATA_CONST                      28.2M      320 
__DATA_DIRTY                      1595K      206 
__FONT_DATA                          4K        1 
__LINKEDIT                       649.3M       42 
__OBJC_RO                         81.6M        1 
__OBJC_RW                         3120K        2 
__TEXT                           544.1M      541 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                       49.4M        9 
shared memory                      744K       13 
===========                     =======  ======= 
TOTAL                              2.0G     1734 
TOTAL, minus reserved VM space     1.6G     1734 

-----------
Full Report
-----------

{"app_name":"prl_client_app","timestamp":"2021-10-30 13:34:06.00 +0200","app_version":"17.1.0","slice_uuid":"a51e8bfb-511a-39ab-9146-6f859e347a43","build_version":"51516","platform":1,"bundleID":"com.parallels.desktop.console","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"8636F1AD-BBD3-41A1-821D-EA03DD13AAA2","name":"prl_client_app"}
{
  "uptime" : 3800,
  "procLaunch" : "2021-10-30 13:34:05.5885 +0200",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro8,3",
  "procStartAbsTime" : 3898015940518,
  "coalitionID" : 874,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-10-30 13:34:06.1509 +0200",
  "incident" : "8636F1AD-BBD3-41A1-821D-EA03DD13AAA2",
  "bug_type" : "309",
  "pid" : 4705,
  "procExitAbsTime" : 3898577551249,
  "cpuType" : "X86-64",
  "procName" : "prl_client_app",
  "procPath" : "\/Applications\/Parallels Desktop.app\/Contents\/MacOS\/prl_client_app",
  "bundleInfo" : {"CFBundleShortVersionString":"17.1.0","CFBundleVersion":"51516","CFBundleIdentifier":"com.parallels.desktop.console"},
  "buildInfo" : {"ProjectName":"Parallels","SourceVersion":"51516.0","BuildVersion":"17.1.51516.0"},
  "storeInfo" : {"deviceIdentifierForVendor":"F15555AB-DE15-53FB-9796-71549E0C73E0","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.parallels.desktop.console",
  "crashReporterKey" : "3B38DB01-BFB6-1BE3-1B7F-715884B45D11",
  "wakeTime" : 491,
  "sleepWakeUUID" : "01E31B0C-4546-46FF-BE1A-08AB3315C788",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4500619264\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10c420000-10e660000    [ 34.2M] r-x\/r-x SM=COW  ...rl_client_app",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":4705},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4500619264\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10c420000-10e660000    [ 34.2M] r-x\/r-x SM=COW  ...rl_client_app",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":114523,"threadState":{"r13":{"value":140701848173240},"rax":{"value":4536664208,"symbolLocation":37528,"symbol":"typeinfo for CAskUserConsentDelegate"},"rflags":{"value":66054},"cpu":{"value":4},"r14":{"value":4501735712},"rsi":{"value":731},"r8":{"value":1},"cr2":{"value":0},"rdx":{"value":105553152337344},"r10":{"value":140704454011752,"symbolLocation":24,"symbol":"__cxxabiv1::(anonymous namespace)::GlobalStatic<__cxxabiv1::(anonymous namespace)::LibcppMutex>::instance"},"r9":{"value":18446744069414584320},"r15":{"value":4537543736},"rbx":{"value":105553152337344},"trap":{"value":14,"description":"(no mapping for user instruction read)"},"err":{"value":20},"r11":{"value":0},"rip":{"value":0},"rbp":{"value":140701848172592},"rsp":{"value":140701848172552},"r12":{"value":1},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":4501735712}},"queue":"com.apple.main-thread","frames":[{"imageOffset":0,"imageIndex":0},{"imageOffset":1116601,"imageIndex":1},{"imageOffset":1116988,"imageIndex":1},{"imageOffset":5717386,"imageIndex":1},{"imageOffset":5718040,"symbol":"CPdCatalogManagerDelegate::CPdCatalogManagerDelegate(QObject*)","symbolLocation":56,"imageIndex":1},{"imageOffset":1245878,"imageIndex":1},{"imageOffset":657155,"imageIndex":1},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":2}]},{"id":114538,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":114539,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":114548,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4500619264,
    "CFBundleShortVersionString" : "17.1.0",
    "CFBundleIdentifier" : "com.parallels.desktop.console",
    "size" : 35913728,
    "uuid" : "a51e8bfb-511a-39ab-9146-6f859e347a43",
    "path" : "\/Applications\/Parallels Desktop.app\/Contents\/MacOS\/prl_client_app",
    "name" : "prl_client_app",
    "CFBundleVersion" : "51516"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4627603456,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703355645952,
    "size" : 49152,
    "uuid" : "29a2750e-f31b-3630-8761-242a6bc3e99e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703352406016,
  "size" : 15215640576,
  "uuid" : "b5084610-afe4-3485-bade-628c4468b057"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=585.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=585.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          148K       21 \nKernel Alloc Once                    8K        1 \nMALLOC                           191.6M       27 \nMALLOC guard page                   16K        4 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        4 \nStack                             9752K        4 \nVM_ALLOCATE                         16K        4 \n__CTF                               759        1 \n__DATA                            32.1M      529 \n__DATA_CONST                      28.2M      320 \n__DATA_DIRTY                      1595K      206 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       649.3M       42 \n__OBJC_RO                         81.6M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           544.1M      541 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                       49.4M        9 \nshared memory                      744K       13 \n===========                     =======  ======= \nTOTAL                              2.0G     1734 \nTOTAL, minus reserved VM space     1.6G     1734 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61704e71b6f6b8421579caf8"
      },
      "deploymentId" : 240000293
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000064
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6169fcad436117010456880e"
      },
      "deploymentId" : 240000238
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro8,3, BootROM 9999.999.999.999.999, 4 processors, Quad-Core Intel Core i7, 2,4 GHz, 16 GB, SMC 9.9999
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Display: Color LCD, 1920 x 1200 (WUXGA - Widescreen Ultra eXtended Graphics Array), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1333 MHz, 0x859B, 0x435438473353313333394D2E433136464544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1333 MHz, 0x859B, 0x435438473353313333394D2E433136464544
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.2)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Crucial_CT2050MX300SSD1, 2,05 TB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: USB20Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: hub_device
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: composite_device
USB Device: composite_device
USB Device: USB20Bus
USB Device: hub_device
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by khronokernel** [comment]
Outside scope of OCLP, use forums for troubleshooting
