### ISSUE TITLE
[Bug]: Screen flikering on Nvidia GT680 with Microsoft Office 2019

### ISSUE THREAD

**Issue by hunvreou** [dortania/OpenCore-Legacy-Patcher#669]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Running Microsoft Office on my IMac 12,2 upgrade with NVIDIA GT680 GPU on Monterey and OCLP 0.3.1, screen rapidly start to flicker until it completely freeze and force to reboot the Mac. This issue is particularly noticed with Microsoft OpenPoint. No particular issue noticed previously on OpenCore + High Sierra on the same hardware.

**Comment by Ausdauersportler** [comment]
Please check the docs and apply post install patches - your NVIDIA GPU lost support with Monterey!
