### ISSUE TITLE
[Bug]: MBP 11.2 Hangs after login with disconnected external monitor

### ISSUE THREAD

**Issue by dmtrv** [dortania/OpenCore-Legacy-Patcher#670]
### Machine Model

MacBookPro11,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Black screen issue minutes after login, hangs with fans maximum speed. When I connect external monitor and boot system it's stable and runs fine. After unplug HDMI screen immediately goes black, fans turns on and system immediately freeze.

### Any Additional Information

MBP 15 mid 2014 without dedicated GPU, installed custom SDD Intel.

**Comment by khronokernel** [comment]
Are you certain this is a MacBookPro11,2 and not the 11,3 model? Reason I ask is that the MacBookPro11,2 model is the 15" without dGPU, so the Haswell drivers are still present and maintained by Apple

If this is actually the 11,3, ensure you root volume patch the system to re-enable Nvidia Kepler support

**Comment by dmtrv** [comment]
> Are you certain this is a MacBookPro11,2 and not the 11,3 model? Reason I ask is that the MacBookPro11,2 model is the 15" without dGPU, so the Haswell drivers are still present and maintained by Apple
> 
> If this is actually the 11,3, ensure you root volume patch the system to re-enable Nvidia Kepler support

Machine is 11.2 w/o dGPU, Iris Pro only, no patch required.

**Comment by khronokernel** [comment]
After further testing, neither a MacBookPro11,1 or MacBookPro11,2 could replicate this issue. Sounds to be local/hardware related. Feel free to research further and provide a patch set if you find the cause
