### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by drebyone** [dortania/OpenCore-Legacy-Patcher#672]
### Machine Model

MacBookPro5,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Podcast
When I click on p[odcast the app opens for the first timed there notification comes on about your privacy./ the button "Start Listening" does not light up and I can't get it todisap[pear so I can actually start listening to my podcasts

**Comment by Ausdauersportler** [comment]
Metal apps will not run properly in non metal Macs. 
This in no OCLP issue - it is your hardware we cannot change by installing software.

**Comment by khronokernel** [comment]
> Have you verified whether this issue has been opened before? If no, your issue will be closed
> true

Would appreciate if people honestly replied to these and actually verified that Catalyst App issues weren't reported before...

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by sud1** [comment]
> Podcast
When I click on podcast the app opens for the first timed there notification comes on about your privacy./ the button "Start Listening" does not light up and I can't get it to disappear so I can actually start listening to my podcasts
