### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by goseki** [dortania/OpenCore-Legacy-Patcher#674]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I'm using a large 2TB USB connected drive to test install Monterey - All goes well until I attempt to install the newly created OpenCore to the USB drive via the TUI version .. I get this:
An error occurred!
osascript: can't open default scripting component.
Please report this to the devs at GitHub

I've previously used this drive to install BigSur without issue. Yes I reformatted it to prepare it for Monterey.
Dismounting / remounting it has no effect.
It is not urgent I will update by other means but drawing it to your attention as requested.

**Comment by khronokernel** [comment]
Looked into it, looks to be a local issue with macOS. Try to reboot and see if this resolves it, otherwise recommend troubleshooting on forums
