### ISSUE TITLE
[Bug]: MacBookPro9,2 can't change brightness, after post-install patches too

### ISSUE THREAD

**Issue by alamelin** [dortania/OpenCore-Legacy-Patcher#675]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

After installing 12.0.1 on my MBP9,2, I can't change brightness even after twice installed post-install thing.

### Any Additional Information

I saw this bug on macos 11.3+

**Comment by khronokernel** [comment]
> I saw this bug on macos 11.3+

Hardware fault, likely close to dying or already is and Big Sur is straining the hardware further. We have plenty of 9,2 users with no PNLF issues
