### ISSUE TITLE
[Bug]: Bluetooth not working

### ISSUE THREAD

**Issue by eliaspapas** [dortania/OpenCore-Legacy-Patcher#676]
### Machine Model

MacBookPro9,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I can't enable bluetooth.
[USB-Data.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7448362/USB-Data.txt)

### Any Additional Information

MacOS 12.1 beta 1

**Comment by khronokernel** [comment]
Based off the provided USB-Data.txt file, your Bluetooth controller is dead. If the USB stack doesn't report it at all, then your issue hardware based (close to dying and so randomly disappears and/or is properly dead)
