### ISSUE TITLE
[Bug]: "Set Windows GMUX support" setting doesn't work

### ISSUE THREAD

**Issue by Piipperi** [dortania/OpenCore-Legacy-Patcher#677]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

I noticed that the patcher setting "Set Windows GMUX support" does not actually do anything if disabled on both of my dGPU 11,3. Disabling it does show in the menu that it's set to false, but building OpenCore, installing it and then going into Windows, the Intel GPU still shows up in Device Manager.

**Comment by khronokernel** [comment]
It just notifies the firmware that it's always booting a macOS environment so GMUX doesn't need to lock itself to dGPU. Not sure what the issue is if your system's dGPU is already disabled

**Comment by Piipperi** [comment]
> It just notifies the firmware that it's always booting a macOS environment so GMUX doesn't need to lock itself to dGPU. Not sure what the issue is if your system's dGPU is already disabled

So how do I disable the iGPU then? What setting should I change?
