### ISSUE TITLE
[Bug]: Hash Mismatch after installing Monteray

### ISSUE THREAD

**Issue by funk01** [dortania/OpenCore-Legacy-Patcher#678]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

On my Late2013 iMac 21´BigSur runs perfectly and fast(booting from extermal SSD). Now i tried this patcher and Montery, but failed 2 times with the same error in the end. The system boots and installs fine, but after first reboot i get "HASH MISMATCH on volume..." - after this system locks and i had to reinsall BigSur. 

I already found more folks with this issue:
https://forums.macrumors.com/threads/macos-12-monterey-on-unsupported-macs-thread.2299557/page-88
https://developer.apple.com/forums/thread/684276
https://www.reddit.com/r/MacOSBeta/comments/oixpmh/hash_mismatch_detected/

Any idea?
Best,
Jason

**Comment by khronokernel** [comment]
> I already found more folks with this issue:

As you've already noted, this is an APFS bug on Apple's end with regards to hash integrity validation. Nothing we can do on our end, wait for Apple to resolve

**Comment by emax810** [comment]
Hi. No updates here ? Same problem with my MBP 15 late 2013

**Comment by Ausdauersportler** [comment]
Did you read the last comment? It is an Apple bug and you will not get a solution here!

**Comment by emax810** [comment]
I can try to install macOS with previous file systems ?

**Comment by nomadicyeti** [comment]
So, the error message states that I may need to reinstall macOS on the computer. Should I go ahead and do a reinstall, or should I hold out hope that Apple will resolve this?

**Comment by emax810** [comment]
Reinstall macOS not fix this problem. I try with last 12.1 but same problem

**Comment by 559911** [comment]
> 

same problem in 12.2(beta) .I think we can wait Apple fix this problem.

**Comment by 3vidar** [comment]
I have also the same Hash volume issue. I found online a Forum message that says -->

Make sure ExtendedFirmwareFeature has 35bit set

Could someone help me how I can set this to try if this solve the issue? 

THX
