### ISSUE TITLE
[Bug]: resolution problem 

### ISSUE THREAD

**Issue by seunghyeok23** [dortania/OpenCore-Legacy-Patcher#679]
### Machine Model

MacBookPro10,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

MacBook Pro Retina has 4 resolution settings, but after the update, only 2800x1800 resolution is displayed, so the screen looks very small. It's not like that in other YouTube videos, but I only watch my MacBook. Also, I upgraded from Big Sur and others say it's faster or the same, but I'm very slow. Cursor and keyboard are slow..

**Comment by khronokernel** [comment]
> Have you verified whether this issue has been opened before? If no, your issue will be closed
> true

Would appreciate some honesty when filing issues, our issues tab is already filled with this "issue" as well as our own documentation alerts you to this issue. Run Post Install patches
