### ISSUE TITLE
[Bug]: An error occurred loading the update (MacBook8,1) with Monterey release 12.0.1

### ISSUE THREAD

**Issue by tchek** [dortania/OpenCore-Legacy-Patcher#680]
### Machine Model

MacBook8,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

macbook 8,1 on Big Sur (supporting BigSur Natively) trying install Monterey 12.0.1 with OCLP 0.3.1

1. I made a bootable drive with the macOS 12 Installer 12.0.1 ( Downloaded with MDS)  
2. Patched it with OCLP TUI 0.3.1
3. Booted from the EFI
4. Selected the macOS 12 installer
5. Launched the update from over Big Sur

Halfway though the install, I have the message :

 "An error occurred loading the update",  and it stops there.

Try several time but alway the same issue

Thx if there is any lights  ;-)

**Comment by tchek** [comment]
On 11.6.1 (20G224)

**Comment by AdrienDole** [comment]
Have you find anything that might be helpful on the web ? And how did you manage to install Big Sur on 8.1 Mac, with Patched Sur ? Or with OCLP ?

**Comment by AdrienDole** [comment]
Did the error came when 12 minutes were left ?

**Comment by Ausdauersportler** [comment]
Please use Discord or Macrumors to discuss - this is no forum substitute.

**Comment by AdrienDole** [comment]
> Please use Discord or Macrumors to discuss - this is no forum substitute.

How do I can find @tchek on Discord or Macrumors ? I'm not used with those tools

**Comment by Ausdauersportler** [comment]
Check back the main OCLP page. Reading is key!

**Comment by tchek** [comment]
> Did the error came when 12 minutes were left ?

Yes

**Comment by AdrienDole** [comment]
> On 11.6.1 (20G224), but it was the same on 11.6, and the same with all the Monterey beta...

Go on discord, I found a solution for this problem.

**Comment by tchek** [comment]
Great ! I do not use discord. Have a nice day.

**Comment by khronokernel** [comment]
Can attempt to try 0.3.2 (mainline) but otherwise use forums for troubleshooting such as discord
