### ISSUE TITLE
macOS Monterey 12.1 Beta 1 - Airplay Receiver disappeared from Sharing options

### ISSUE THREAD

**Issue by mycroftcanner** [dortania/OpenCore-Legacy-Patcher#683]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Before installing macOS Monterey 12.1 Beta 1 I could use my iMac Late 2013 as an Airplay Receiver... The option has disappeared in System Preferences -> Sharing.

**Comment by khronokernel** [comment]
I've resolved the issue for most models, seems to be an odd issue with patching a comma in AirPlaySupport. However I was not able to confirm the below models still work:

```
iMac13,1, iMac13,2, iMac13,3, iMac14,1, iMac14,2
```

See if this build functions correctly on 12.1:

* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/4264199058/artifacts/110826765
  * Need to be signed into Github to download

Above build is based off this branch:
* https://github.com/dortania/OpenCore-Legacy-Patcher/commit/da32e3bfcf640cf133744d53357e38bf8c40d764

**Comment by khronokernel** [comment]
Moved to dedicated issue:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/701
