### ISSUE TITLE
[Bug]: Set Software Demux

### ISSUE THREAD

**Issue by vdm-alt** [dortania/OpenCore-Legacy-Patcher#684]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Please add the ability to install DeMux Software for MBP 10.x and 11x models operating in UMA mode, with faulty and disabled discrete graphics. explain the issue

**Comment by vdm-alt** [comment]
<img width="571" alt="q1" src="https://user-images.githubusercontent.com/83856941/139868233-cee9e645-6288-4d4a-9bd9-4f3cd7bb3112.png">

**Comment by khronokernel** [comment]
Hello,

Feel free to develop the patch set and submit it to our project. As-is no one on our team have NVIDIA Kepler based MacBooks, so little work can be done. Below is the SSDT you'll need to adjust to correspond with the software demux patch set

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/ACPI/Source/SSDT-DGPU.dsl
