### ISSUE TITLE
SIP, can't re enable SIP on Monterey After patching

### ISSUE THREAD

**Issue by cnorma1** [dortania/OpenCore-Legacy-Patcher#685]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

After Patching the post installation for the HD4000 in this device, System crashes with SIP RE enabled

### Any Additional Information

Used usb loader to reboot Mac and disable SIP

**Comment by khronokernel** [comment]
This is user error, we clearly state in our documentation that SIP and SBM need to be disabled. Additionally the patcher won't even run without SIP disabled

**Comment by orkoden** [comment]
> This is user error, we clearly state in our documentation that SIP and SBM need to be disabled. Additionally the patcher won't even run without SIP disabled

Could you please point me to the place in the documentation? I couldn't find it.
