### ISSUE TITLE
[Bug]: Spotlight indexing issue A1398

### ISSUE THREAD

**Issue by Stefan-CPlanet** [dortania/OpenCore-Legacy-Patcher#687]
### Machine Model

MacBookPro10,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hello, I followed the instructions by BenSova and switched from PatchedSur to OpenCore, and then upgraded to Monteray. Everything seems great so far, except for a single issue, Spotlight indexing.

For example, if I try command+space and search for teamviewer I would get siri search, siri suggestion.. but not the actual TeamViewer app.

I know that before update spotlight indexing was disabled, do I need to manually reanable it somehow?
Thank you

**Comment by khronokernel** [comment]
Out of scope for OCLP, use forums for troubleshooting
