### ISSUE TITLE
[Bug]: Graphical glitches menu bar control center MacBookPro4,1 and 5,5 with Big Sur 11.5.2 and 11.6.1

### ISSUE THREAD

**Issue by RedBearAK** [dortania/OpenCore-Legacy-Patcher#688]
### Machine Model

MacBookPro5,5

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

After installing Big Sur on a MacBookPro4,1 and a MacBookPro5,5 and running the post-install patches, I am seeing numerous graphical glitches in: 

- menu bar (menus disappear, never appear or get "stuck" but still respond to mouse)
- control center (sliders are distorted and slider handle shifted down completely off the slider)
- system preferences (icons disappearing, icons in strange positions) 

Tried to look through the closed issues but didn't see anything obviously related. 

The graphical glitching doesn't seem to appear until after doing the post-install patching on either machine. On the MacBookPro4,1 I updated to Big Sur 11.6.1 after installing 11.5.2. I thought maybe that was causing the glitches but I see pretty much the same thing happening after installing 11.5.2 on a MacBookPro5,5 without doing the 11.6.1 update. 

Is this a known issue and I'm just doing something wrong? 

Also the problem with the menu bar is far worse if I try to use "Reduce transparency" in the Accessibility settings. That causes all the text on the menu bar (including the Apple menu) to disappear.

**Comment by Ausdauersportler** [comment]
Please check the issue #108 - it has already pinned to the top of this page.

The post install patching brings back OpenGL acceleration but obviously breaks at the same time the rendering to some extend. Developers are still working on it but I am afraid the only way out of it is getting a more recent system with a metal GPU.

**Comment by RedBearAK** [comment]
@Ausdauersportler 

I see. 

I haven't had enough time to be sure what difference it makes, but do the post-install patches speed up the system enough to make it worthwhile the put up with the graphical glitches? Or should I start over with a clean install and just not install the patches if I don't want to see the glitches?

**Comment by Ausdauersportler** [comment]
The current consent is: 
Big Sur and Monterey are barely usable without any kind of graphics acceleration. If you use the Mac primarily as a server with no or rare direct graphical login access leave it unpatched, otherwise you will need the patches even for some basic things. Mileage will vary…

**Comment by RedBearAK** [comment]
@Ausdauersportler 

I think you meant “consensus” there. Thanks for the info! 

Closing.
