### ISSUE TITLE
New volume "Update" after OpenCore install

### ISSUE THREAD

**Issue by whgmkeller** [dortania/Opencore-Legacy-Patcher#69]
I installed OC on my MAcbookPro 13" 2012. I now have a volume Update. What is this?

I also updated to Big Sur without ny problems - volume Update stil there.

**Comment by Ausdauersportler** [comment]
This is how Big Sur organizes the data open the disk. Can we agree to reduce traffic here on real issues with the OCLP and pull requests. For all other things I would use the Big Search machines ...

**Comment by whgmkeller** [comment]
Sure - no problem. Thanks.
