### ISSUE TITLE
[Bug]: Inconsistences in preferences

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#690]
### Machine Model

MacBook5,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

Also. I have a question relative to the vmm patches. Because they are only for macOS 11+, you cannot apply them and at the same time do root patches for Mojave/Catalina.
To avoid it I think you should hide one of them.

### Any Additional Information

![immagine](https://user-images.githubusercontent.com/61084118/140077784-220750b0-5a76-41eb-a352-5b04c1bee689.png)
![immagine](https://user-images.githubusercontent.com/61084118/140077874-3a382878-3f31-425a-a2bb-a741a8f1bd31.png)
They are an example of how contrasting settings can coexist.

**Comment by khronokernel** [comment]
A user can root patch without building a new OC. Arbitrarily locking settings behind others wouldn’t make sense

**Comment by tiziodcaio** [comment]
oh yes I agree
