### ISSUE TITLE
[Bug]: iMac 12,2 weird color artifacts

### ISSUE THREAD

**Issue by devbrones** [dortania/OpenCore-Legacy-Patcher#693]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

my setup: iMac 12,2 (stock gpu) with tb 27" display and 24" dp display.

when the login screen appears, colors invert for every frame update. Does not change upon login.
can provide more images if it is needed
![IMG_20211103_210308](https://user-images.githubusercontent.com/34194695/140184270-2c434262-ffdb-4343-b2fe-eff20a56a193.jpg)

**Comment by khronokernel** [comment]
> Have you verified whether this issue has been opened before? If no, your issue will be closed
> true

Would appreciate some honesty when filing issues, this has been filed before many times and is even documented in our guide:
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html
