### ISSUE TITLE
[Bug]: Use Shift+Tab to select Done in widgets

### ISSUE THREAD

**Issue by RedBearAK** [dortania/OpenCore-Legacy-Patcher#694]
### Machine Model

MacBookPro5,5

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

The Dortania OCLP guide has a page talking about Legacy Acceleration issues: 

https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#cannot-press-done-when-editing-a-sidebar-widget

That page has a section talking about the fact that you can't click the "Done" button with the mouse when editing widget settings, and how to use Tab to select the "Done" button so that edited widget settings can be saved. 

Below that is a line that says this trick no longer works in Big Sur 11.3 and later. 

```
Note: This work-around doesn't seem to work in macOS 11.3 and newer
```

This does not appear to be entirely correct. The problem instead seems to be that hitting Tab repeatedly doesn't "cycle" through all the available controls in the window in an endless loop as it normally would in other types of windows and dialogs. If you hit Tab it highlights the settings on the back of the widget, and stops like it hits a wall. 

I tried a simple solution and it works: Shift+Tab moves the focus backward to the "Done" button, where the spacebar can activate it. 

I have confirmed this to work on at least the weather widget, the world clock widget, the calendar widget and the stocks and stocks watchlist widgets. At least with Big Sur 11.5.2 on a MacBookPro5,5. 

Please forward this info to whoever maintains the OCLP guide. Thanks!

**Comment by Ausdauersportler** [comment]
We all maintain the docs, you can edit each page and generate a change request yourself. Give it a try.

**Comment by RedBearAK** [comment]
@Ausdauersportler 

It would have been helpful to include even the briefest instruction for which file to edit. Anyway, see PR #697.

**Comment by brunocastello** [comment]
Came here to say that I am testing the OCLP with a 2011 Mac Mini (Macmini5,1) and Monterey. I could change the weather widget location before applying the legacy graphics patch but after applying it, I am no longer able to edit my weather widget location. The 'Done' button is unclickable. I tried the solution proposed here but it does not work. I need it to show my current location. Currently it shows for the capital of my country (Brasilia, Brazil) instead of (Rio de Janeiro, Brazil).

Any chance this widget has some sort of plist or config file to edit the location manually? So I could copy one from my other 2020 MacBook Air... Just a thought.

**Comment by RedBearAK** [comment]
@brunocastello 

Please get back to me when you can and let me know if the instructions below fixes your issue. If it does, I guess I will have to add this to the docs. This is the only reason that I can think of that would stop you from being able to get to the "Done" button with Shift+Tab: 

Make certain that you have enabled the ability to move between window "controls" like dialog buttons via the Tab key. This is a feature that has for some reason **_always_** been disabled by default in macOS, but I have **_always_** enabled it almost immediately after creating any new user account on a Mac, so I tend to forget that it is not enabled by default. **Without this feature enabled, you probably can't get to the "Done" button with Tab or Shift+Tab.**

Go to **System Preferences** -> **Keyboard** -> **Shortcuts**. At the bottom of the dialog you should see something that says "Use keyboard navigation to move focus between controls." Make sure that box is checked. 

Before Catalina this was a set of two radio buttons where you needed to select the one that said, "All controls." It has changed. 

Here is a screenshot of how it looks in macOS 10.15 and later: 

![macOS-use-keyboard-navigation](https://user-images.githubusercontent.com/64876997/153101650-6544e80c-191e-4ade-9570-36e55d370775.jpg)

**Comment by brunocastello** [comment]
@RedBearAK I did enable it and it does work around the system except on these widgets. No luck...

**Comment by brunocastello** [comment]
I tried something else: I went into accessibility settings, keyboard, and enabled full keyboard access. While it does work on my M1 MacBook Air 2020, it does not on my 2011 Mac Mini, both on latest Monterey. Ufff... at least it was a good idea to try, although I am still unable to change the location of my weather.

**Comment by RedBearAK** [comment]
> @RedBearAK I did enable it and it does work around the system except on these widgets. No luck...

@brunocastello 

That is quite bizarre. I think I was only testing on Big Sur when I discovered the Shift+Tab trick, but I can't imagine why Monterey would be any different in that respect. As long as keyboard navigation is enabled. 

Thanks for reporting back that this did not help you, at least on Monterey. I only have some 2012 Macmini6,1 and 6,2 models, so I can't really test in a similar environment. The 2012 models don't require the legacy patches. I could try on a 2011 MBP8,3 though. I've been just using Big Sur because of issues I had with earlier versions of Monterey. 

The root patches are supposedly reversible with the OCLP app, but I don't know how reliable that process is, even in the latest OCLP. 

You could always just reinstall macOS from a USB device to clear out the root patches. It shouldn't overwrite your user accounts or data unless you choose to erase the drive you're installing onto. If you reinstall or "upgrade" macOS without erasing the drive it should remove all the patches, leaving you with a clean macOS install. Then you can make your changes to the widget, and then re-apply the root patches. Obviously this is a tedious process that takes at least an hour or so, but it would work if nothing else does.

**Comment by brunocastello** [comment]
Thanks anyway. I will probably end up reinstalling. * Argh *
