### ISSUE TITLE
[Bug]: Photo Screensavers don't load

### ISSUE THREAD

**Issue by PolarHacker** [dortania/OpenCore-Legacy-Patcher#695]
### Machine Model

Macmini6,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Screensavers that use photos do not load, either when activated or previewing in System Preferences. Screen is simply black. 

### Any Additional Information

Some screensavers include Photo Wall, Vintage Prints, Photo Mobile, etc. If the Show with clock option is enabled, the clock will display, but the rest of the display will remain black. Tested with FileVault both on and off. Another user on the Discord with a MacBookPro9,1 has the same issue.

**Comment by khronokernel** [comment]
Looks to be an Apple bug, a Polaris equipped Mac Pro replicates the issue reliably. Try to get someone with a native machine and file an issue to Apple.

I was able to briefly replicate on a 14" M1 Pro, but unable to since so unable to file a proper issue.

**Comment by PolarHacker** [comment]
It appears this could be a bug related to Monterey itself and not OCLP. https://discussions.apple.com/thread/253296992

**Comment by mycroftcanner** [comment]
same issue on an iMac14.2 running Monterey 15, 15.1 and 15.2 beta 3
