### ISSUE TITLE
[Bug]: macbook5,1 network recovery issues

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#698]
### Machine Model

MacBook5,1

### Application Version

Latest Build (nightly)

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

When I boot the recovery, the wifi seems to not working. I will try now with cable to see if works

**Comment by khronokernel** [comment]
Legacy wifi cards need root patching, so installed OS is required. Therefore you’ll need Ethernet for RecoveryOS in Monterey

**Comment by tiziodcaio** [comment]
Because monterey is stable now, I suggest to write it better in the documentation, especially for the compatibility page.
