### ISSUE TITLE
Add hardware upgrade detection

### ISSUE THREAD

**Issue by khronokernel** [dortania/Opencore-Legacy-Patcher#70]
Currently in OCLP, we assume all hardware is stock. Problem is for models with upgraded wifi cards and GPUs we need to ensure that we are patching correctly.

Simple solution would be:

* Add wifi card whitelist detection
  * Check APRT Device and probe, since there's few supported models easy enough to detect which cards are used
* Add GPU detection
  * Due to the numerous variations of GPU upgrades we'll likely compare models models shipped with the stock configuration and otherwise add Metal-based card patches

**Comment by Ausdauersportler** [comment]
Hi!

We already put such code into the micropatcher. I can provide some (base shell script code) code on GPU detection. There are only a few NVIDIA Kepler and AMD Polaris & Ellesmere and a handful new AMD GPU (Navi) supported by macOS and only 11,x and 12,x  iMac and the MacPro models can exchange the GPU. This should be easy to catch.

Basically I added such code to my fork of your OCLP some days ago..
