### ISSUE TITLE
[Bug]: airplay to mac

### ISSUE THREAD

**Issue by juliangroen-deliverymatch** [dortania/OpenCore-Legacy-Patcher#700]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Successfully installed the Monterey release on an iMac 12.1. The toggle for 'airplay to Mac' shows up under the sharing pref however I don't seem to be able to connect to the mac as it can't be found by other devices. After some research I did it seems to be possible as multiple people claimed to have it working on this type of iMac. So I presume this is some kind of bug.

**Comment by khronokernel** [comment]
macOS bug, AirPlay to Mac has been verified to work on Metal and non-Metal machines. Use forums for troubleshooting
