### ISSUE TITLE
[Bug]: Not detecting wifi network 

### ISSUE THREAD

**Issue by tckoo1411** [dortania/OpenCore-Legacy-Patcher#703]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

After upgrade to Monterey 12.0.1 the wifi doesn't work any more. I have tried OCLP 0.2.5, 0.3.0 and now 0.3.1 and it doesn't work. I have double check by going into windows 10 and confirmed the wifi card still works. Thanks.
 
![Screenshot 2021-11-06 at 2 25 02 PM](https://user-images.githubusercontent.com/85660271/140600179-5463f6ac-a4e0-4e33-b124-43280d40539c.png)

**Comment by Ausdauersportler** [comment]
You need to apply post install patches to get WiFi working, again. 
Alternatively you may upgrade your Atheros WiFi with a more recent Broadcom card following these [instructions](https://forums.macrumors.com/threads/imac-mid-2011-bluetooth-4-0-internal-upgrade.1780242/post-19717599).

**Comment by tckoo1411** [comment]
> You need to apply post install patches to get WiFi working, again.
> Alternatively you may upgrade your Atheros WiFi with a more recent Broadcom card following these [instructions](https://forums.macrumors.com/threads/imac-mid-2011-bluetooth-4-0-internal-upgrade.1780242/post-19717599).

Got it working. Thanks, will get a replacement wifi blue tooth card. The 2 that i got from ali express wasn't working for it's bluetooth.

**Comment by Ausdauersportler** [comment]
The dead BT is really an issue with aliexpress - you are not the first reporting this problem.
