### ISSUE TITLE
[Question]: Does APFS ROM Patch need to be removed? 

### ISSUE THREAD

**Issue by RedBearAK** [dortania/OpenCore-Legacy-Patcher#704]
### Machine Model

iMac7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

The OCLP guide says that OCLP makes the APFS ROM patch unnecessary for APFS support on machines like the iMac7,1. Which is nice. But the guide doesn't say anything about whether it's safe to use OCLP on a Mac that already has the APFS ROM patch applied. I have two different iMac7,1 models with the patch applied running Mojave with the dosdude1 patcher, and the necessary upgraded CPU. 

Looking for info on whether I should attempt to restore the original ROM firmware before using OCLP on those machines. Or does it not matter?

**Comment by khronokernel** [comment]
OCLP removes any reliance on ROM patching for APFS support. Ideally you should revert to stock, but users have used OCLP with the modded firmware

**Comment by RedBearAK** [comment]
@khronokernel 

Thanks.
