### ISSUE TITLE
[Bug]: BCM943602CDP Randomly fails to load/work under Monterey 12.0.1 using OCLP 0.3.1 on cMP 5,1

### ISSUE THREAD

**Issue by SemoTech** [dortania/OpenCore-Legacy-Patcher#705]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

Running Monterey 12.0.1 via OpenCore Legacy Patcher v0.3.1 on a NVME SSD in a cMP 5,1 with upgraded Wi-Fi/Bluetooth combo card.  

Card is a Broadcom (BCM943602CDP) - APN: 653-00011 - P/N: 661-07505

**Randomly during boots both the USB ports and the Bluetooth/WiFi BCM943602CDP card drivers fail to work/load properly and neither functions!**  Bluetooth shows as disabled in status bar and cannot be enabled. I am forced to use Mouse Keys to shutdown.

Seems to work more often if doing a full shutdown and cold boot, but if the machine reboots it's about 50% reliable.

The Front and Back native USB ports also seems to not allow a USB mouse to power on at the same time...

If I boot into Mojave or Catalina (DosDude pathed), no issues whatsoever with USB or the BCM943602CDP so not a hardware issue.

### Any Additional Information

This is how the BCM943602CDP card is recognized under Bluetooth and WiFi in System Report when seen properly:

![image](https://user-images.githubusercontent.com/1452100/140634650-60d4c5e4-3851-417a-b411-7fcfde80f9f0.png)

![image](https://user-images.githubusercontent.com/1452100/140634708-3a6bdfd4-8c4d-44d3-b7d6-ee988f346b08.png)

**Comment by khronokernel** [comment]
Likely hitting the UHCI controller (USB1.1) issue present on MacPro5,1 and older. Forcing the EHCI controller(USB2.0) will resolve this, use a USB Hub in-between the devices and the Machine's port will work

Use forums for further troubleshooting

**Comment by SemoTech** [comment]
Thanks @khronokernel but I also have a PCIe USB 3.0 card and plugging a USB mouse onto it also failed! 

And what about the BCM943602CDP Bluetooth issue?

Thank you.

**Comment by khronokernel** [comment]
Bluetooth is run over USB, so the UHCI issue is still linked with it

**Comment by SemoTech** [comment]
Got it @khronokernel, so then there is no fix for the cMP 5,1?  

What about and option to somehow disable UHCI controller (USB1.1) at boot, and forcing the EHCI controller(USB2.0)?

I ask since I NEVER had ANY USB issues with Catalina on the same machine, using dosdude1! (I can dual-boot)

Lastly, what Forums specifically were you referring to to discuss the issue?

Thank you.
