### ISSUE TITLE
[Bug]: WIFI endless searching, no WPA Security Password Prompt! v0.3.1 TUI OFFLINE

### ISSUE THREAD

**Issue by nathanb0** [dortania/OpenCore-Legacy-Patcher#706]
### Machine Model

MacBook5,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

No WIFI connection (no WPA password request) 

macbook 5,2 
MacOS Monterey 12.0.1
no WIFI after patching OCLP v0.3.1
Symbol in menubar keeps searching but can't not seem connect

Reinstall several times... Repatitioned HD.... randZero's.... Reinstalled same error.... reset router... puller connections.... pulled HD... 

during installations got white Screen of DEATH. Folder question mark.... Booted from USB wiped HD and fixed but still no WIFI... ALSO can't not patch OCLP v0.3.0 SIP reports off at terminal after Recovery boot and but after login got strange message from (csrutil status) several items switched off an several switch on with a warning message!

HardwareCheck ok! 
installed dosdude1 macOS Mojave as a fallback. "WORKS FINE" WIFI works so as I am here.

**Comment by khronokernel** [comment]
* https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html#cannot-connect-wi-fi-on-monterey-with-legacy-cards

**Comment by nathanb0** [comment]
M,

I have already done that, in more ways than 1 and still not working



Nathan Berg


Please consider the environment before printing my email!

     On Monday, 8 November 2021, 02:53:07 GMT+11, Mykola Grymalyuk ***@***.***> wrote:  
 
 


Closed #706.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
