### ISSUE TITLE
[Bug]: Graphic acceleration for iMac 14,3 (NVIDA GPU) and Monterey

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#708]
### Machine Model

iMac14,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I have tried to boot on macOS Monterey with the latest version of OCLP and it seems that graphic acceleration doesn't work (and animations are very slow). It doesn't seem to be a know issue.
I have an iMac 14,3 with Nvidia Geforce GT 750M

**Comment by khronokernel** [comment]
> Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages
> true

Would appreciate some honesty and effort on the user's part to check the guide:

* https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html

**Comment by mat1696** [comment]
Oh yeah I did it honestly ! But looking at this page https://dortania.github.io/OpenCore-Legacy-Patcher/MONTEREY-DROP.html#previously-broken-hardware it is written « NVIDIA Kepler dGPU Acceleration (**_Resolved in 0.2.5 and newer_**) » so i thought the Graphic Acceleration should be working well since 0.2.5… But apparently I just misunderstood…
