### ISSUE TITLE
MacBookPro10,1 sleep/wake issue

### ISSUE THREAD

**Issue by eduard-comanici** [dortania/Opencore-Legacy-Patcher#71]
Hello,

I've successfully installed Big Sur using OpenCore and everything seems to run pretty smoothly (except for the animations :))

Unfortunately, whenever the laptop is asleep for more than a couple of hours, I always wake it up to the dreaded "Sleep Wake Failure" report.

Do you guys have any ideas?

**Comment by khronokernel** [comment]
Moving to dedicated issue: https://github.com/dortania/Opencore-Legacy-Patcher/issues/72
