### ISSUE TITLE
[Bug]: Content Caching not available

### ISSUE THREAD

**Issue by riiveraluis** [dortania/OpenCore-Legacy-Patcher#710]
### Machine Model

iMac13,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Content Caching is not available in Sharing tab on system preferences. The checkbook is greyed out.

**Comment by khronokernel** [comment]
Unfortunately I fail to see how this is an OCLP created bug, looks to be just an issue with Monterey if it previously worked in Big Sur on an OCLP'd machine
