### ISSUE TITLE
[Bug]: Bluetooth 

### ISSUE THREAD

**Issue by csweering** [dortania/OpenCore-Legacy-Patcher#711]
### Machine Model

Macmini5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I'm running a Mac mini, my mouse, and Keyb. ware working via BT, I can only not switch on the BT, and even my keyb. is working not all kyes are working correctly, I love some assist. I have sone an SMC Reset en NVRAM it's not helping 

[USB-Data.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7498655/USB-Data.txt)

**Comment by khronokernel** [comment]
On/off power cycles should be resolved in mainline

**Comment by csweering** [comment]
On/off power cycles should be resolved in mainline not working
