### ISSUE TITLE
System Integrity Protection - will not disable, under Vs. 0.3.1

### ISSUE THREAD

**Issue by macmanjimmy** [dortania/OpenCore-Legacy-Patcher#712]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

System Integrity Protection - will not disable, under 0.3.1

works fine with 0.2.5

**Comment by khronokernel** [comment]
SIP is a bit mask of multiple values defined in XNU's CSR.h. SIP is never "disabled", instead portions of it are lowered. 0.3.2 clarifies this to mean allowing root volume patching.

0.3.2 additionally allows you to specify a custom bit mask to lower the bits you desire

**Comment by macmanjimmy** [comment]
why does Cocktail state "Disabled" under 0.2.5 and "Enabled" under 0.3.1... Need SIP disabled for cDock to work properly as it does with 0.2.5 not with of 0.3.1, seems like something is amiss to being, even though i am a "NEWB" to all this
