### ISSUE TITLE
[Bug]: Bluetooth won't connect devices or keeps disconnecting

### ISSUE THREAD

**Issue by itsLollo1000** [dortania/OpenCore-Legacy-Patcher#714]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Trying to connect several bluetooth devices including Magic Mouse and Keyboard. Sometimes it is possible to connect mouse and keyboard after deleting them, most of the time it is not possible to connect any devices. They all show up in the bluetooth settings as being able to connect but after pressing connect nothing really happens. 

Now for the Magic Mouse and Keyboard stuff. If I am able to connect them, they stay mostly connected for about 10-15s and then disconnect. Pressing any button reconnects them and same behavior after around another 10-15s. The Mac says mouse connected and then mouse disconnected in the bottom half of the screen. All batteries were check and are at 100%.

### Any Additional Information

Having the BCM_20702B0 Chipset with version v66 c8529. Also check if it shows up under USB Hub and yes it does in USB 2.0 Bus - Hub - Hub - BRCM20702 Hub.

Mouse and keyboard used to work before updating from Mountain Lion to Monterey.

Already tried the Monterey Support Quote from Beta 4
`sudo killall -9 BlueTool bluetoothd`

**Comment by khronokernel** [comment]
> They all show up in the bluetooth settings as being able to connect but after pressing connect nothing really happens.

macOS bug unfortunately, they rewrote the entire Bluetooth stack with Monterey so many users with native Macs are also experiencing odd Bluetooth connection issues. You can try mainline (0.3.2), but otherwise I'd recommend waiting a couple macOS 12.x builds to see how the stack matures
