### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sdahlmann** [dortania/OpenCore-Legacy-Patcher#716]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I have two problems with the Open Legacy Patcher on Mac mini late 2012:

1. Unfortunately, the 3,5mm digital audio connecter for speakers on the Mac does not work. There is no sound coming out. With Mac OS Big Sur and the "Big Sur Patcher" or Mac OS Catalina, the connecter still worked cleanly.

2. At the edges of elements, they fray slightly on the monitor. See picture.

I have make clean install from Mac OS Monterey.

Can you please, possibly fix these errors with a patcher update?

If so, thank you in advance for that.

Otherwise, the patcher works perfectly with Mac OS Monterey 12.0.1.

### Any Additional Information

![8CDB924E-60BD-4C78-9AA7-F5AA53D7EF78](https://user-images.githubusercontent.com/17680074/141022684-97072501-ed90-455f-b23f-eca5fe3c388a.jpeg)

**Comment by khronokernel** [comment]
1. Between Big Sur and Monterey, audio stack was unchanged kernel side. Additionally we don't touch audio on 2012+ models. Apple bug
2. The effect is known as "shimmering", affects native Macs as well such as MacBookPro11,4. Apple bug, nothing we can do

Feel free to troubleshoot 1. further on forums, for 2. you'll just have to hope Apple fixes the issue. HiDPI displays mask the issue as a work-around
