### ISSUE TITLE
[Bug]: MacBookPro5,3 back screen using post-patches

### ISSUE THREAD

**Issue by pakyrs** [dortania/OpenCore-Legacy-Patcher#718]
### Machine Model

MacBookPro5,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

MacBookPro5,3 back screen using post-patches

### Any Additional Information

Installed Monteray and applied post-install patches, the MacBookPro5,3 freezes to a black screen. No apparent error in the log

**Comment by HackintoshHD** [comment]
@pakyrs I had this with OpenCore Legacy Patcher 0.3.1 TUI on a MacBookPro5,2. It doesn't happen anymore with today's OCLP 0.3.2 TUI nightly. As a workaround to get access to the macOS GUI again, you can try the following, which worked on my MBP5,2:

1. Boot your MacBookPro5,3 until its screen turns black.
2. Wait a bit and press the arrow keys - if they return a sound, the MBP has probably successfully completed the boot process and the display is just dimmed to 0 %.
3. If you've successfully passed step 2, close the lid of your MacBookPro5,3 and wait about one minute, until the MBP's fan shuts down and the activity light begins pulsating. Once that has happened, open the lid again and press a key. That should switch on the display again.
