### ISSUE TITLE
Photo app Issue: no Faces scan

### ISSUE THREAD

**Issue by AntonioJOrtiz64** [dortania/OpenCore-Legacy-Patcher#719]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

First of all, thanks for  wanderfull  job.

Photo App do not scan faces, always said 0 photos scanned

Thanks

**Comment by Tiger-AC** [comment]
Same here with the latest Monterey 12.1 beta 2 along with 0.3.1 / latest 0.3.2n.

**Comment by khronokernel** [comment]
Monterey bug, not much we can do
