### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rustyhood** [dortania/OpenCore-Legacy-Patcher#720]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I am unable to to get OpenCore to write to my bootable USB drive, Any suggestions?

**Comment by educovas** [comment]
use forums for troubleshooting
