### ISSUE TITLE
Failed to apply Post-Install Volume Patch for newly installed K3100M, and failed to login afterwards

### ISSUE THREAD

**Issue by Tiger-AC** [dortania/OpenCore-Legacy-Patcher#721]
### Machine Model

iMac12,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Just installed a pre-flashed K3100M for my iMac12,2. To my amazement that it actually turned on and displayed everything including the boot screen. And it worked correctly with High Sierra including the brightness control and external display as a 2nd screen.
But the excitement stopped after booting into OCLP (v 0.3.1 / latest v0.3.2 nightly) Monterey (12.0.1). Each time when I tried to apply the Post-Install Volume Patch for Kepler, it failed with the error messages shown below.
I then booted with Big Sur (11.6.1) and half the menu bar not showing up and was told I don't need to patch anything when trying to run Post-Install Volume Patch.

### Any Additional Information

- Downloading package
- 169.2537136077881MB Downloaded
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/private/var/folders/30/ppvxv7y52xxc0hp8rvgyjn0w0000gn/T/_MEIzfgTdq/payloads
Press [ENTER] to continue
- Found Root Volume at: disk3s5
- Mounting APFS Snapshot as writable
Password:
- Successfully mounted the Root Volume
- Running patches for iMac12,2
- Installing Kepler Patches
- Detected supported OS, installing Acceleration Patches
- Installing Kepler Acceleration Kext patches for Monterey
- Adding GeForce.kext
- Adding GeForceAIRPlugin.bundle
- Adding GeForceGLDriver.bundle
- Adding GeForceMTLDriver.bundle
- Adding GeForceVADriver.bundle
- Adding NVDAGF100Hal.kext
- Adding NVDAGK100Hal.kext
- Adding NVDAResman.kext
- Adding NVDAStartup.kext
- Installing legacy Wireless support
- Merging Wireless CoreSerices patches
- Merging Wireless usr/libexec patches
Press [ENTER] to continue with cache rebuild: 
- Rebuilding Kernel Cache (This may take some time)
- Unable to build new kernel cache

Please report this to Github
Reason for Patch Failure:
Error Domain=KMErrorDomain Code=31 "Error occurred while building a collection: 
    1: One or more binaries has an error which prevented linking.  See other errors.
    2: Could not use 'com.apple.GeForce' because: Cannot find symbol for metaclass pointed to by '__ZN16nvDisplayManager10superClassE'.  Expected symbol '__ZN27IOAccelLegacyDisplayMachine10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN13nvDisplayPipe10superClassE'.  Expected symbol '__ZN24IOAccelLegacyDisplayPipe10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN9nvSurface10superClassE'.  Expected symbol '__ZN20IOAccelLegacySurface10gMetaClassE' to be defined in another kext
com.apple.GeForce specific: 
    1: Cannot find symbol for metaclass pointed to by '__ZN16nvDisplayManager10superClassE'.  Expected symbol '__ZN27IOAccelLegacyDisplayMachine10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN13nvDisplayPipe10superClassE'.  Expected symbol '__ZN24IOAccelLegacyDisplayPipe10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN9nvSurface10superClassE'.  Expected symbol '__ZN20IOAccelLegacySurface10gMetaClassE' to be defined in another kext
" UserInfo={NSLocalizedDescription=Error occurred while building a collection: 
    1: One or more binaries has an error which prevented linking.  See other errors.
    2: Could not use 'com.apple.GeForce' because: Cannot find symbol for metaclass pointed to by '__ZN16nvDisplayManager10superClassE'.  Expected symbol '__ZN27IOAccelLegacyDisplayMachine10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN13nvDisplayPipe10superClassE'.  Expected symbol '__ZN24IOAccelLegacyDisplayPipe10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN9nvSurface10superClassE'.  Expected symbol '__ZN20IOAccelLegacySurface10gMetaClassE' to be defined in another kext
com.apple.GeForce specific: 
    1: Cannot find symbol for metaclass pointed to by '__ZN16nvDisplayManager10superClassE'.  Expected symbol '__ZN27IOAccelLegacyDisplayMachine10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN13nvDisplayPipe10superClassE'.  Expected symbol '__ZN24IOAccelLegacyDisplayPipe10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN9nvSurface10superClassE'.  Expected symbol '__ZN20IOAccelLegacySurface10gMetaClassE' to be defined in another kext
}
checking collections...
Warning: com.apple.driver.KextExcludeList was not found!
updated extension 'com.apple.nvidia.driver.NVDAResman' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/NVDAResman.kext' (mach-o UUID changed from <unknown> to 879FE28C-BC88-3553-B3C7-1CCFAE357D45)
updated extension 'com.apple.nvidia.NVDAStartup' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/NVDAStartup.kext' (mach-o UUID changed from <unknown> to B7E8FE3A-5A44-3EA0-9A3B-345B583BFF31)
updated extension 'com.apple.nvidia.driver.NVDAGF100Hal' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/NVDAGF100Hal.kext' (mach-o UUID changed from <unknown> to 83ECEC97-996E-3E74-A930-5EF165210C51)
updated extension 'com.apple.nvidia.driver.NVDAGK100Hal' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/NVDAGK100Hal.kext' (mach-o UUID changed from <unknown> to CCDFB15A-E29E-38CE-A6C0-732F5648BC28)
updated extension 'com.promise.driver.stex' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/PromiseSTEX.kext' (mach-o UUID changed from <unknown> to AE253556-66D8-38D2-B9D1-179B78F29153)
updated extension 'com.apple.driver.usb.AppleUSBVHCICommonRSM' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/AppleUSBCommon.kext/Contents/PlugIns/AppleUSBVHCICommonRSM.kext' (mach-o UUID changed from <unknown> to 4DA8930B-6C41-3E17-8D1C-5525EA5981B7)
updated extension 'com.apple.GeForce' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/GeForce.kext' (mach-o UUID changed from <unknown> to B907167E-E164-36D8-9E8F-695A72E738F7)
updated extension 'com.apple.driver.AppleMobileDevice' found on disk at '/Library/Apple/System/Library/Extensions/AppleMobileDevice.kext' (mach-o UUID changed from <unknown> to <unknown>)
updated extension 'com.Areca.ArcMSR' found on disk at '/System/Volumes/Update/mnt1/System/Library/Extensions/ArcMSR.kext' (mach-o UUID changed from <unknown> to 01FC5EBD-0A34-3E77-9216-53B89DDD8CE4)
rebuilding release collections: boot, system
rebuilding release collections:
	boot kernel collection
	system kext collection
failed to build release collection:
	One or more binaries has an error which prevented linking.  See other errors.
	Could not use 'com.apple.GeForce' because: Cannot find symbol for metaclass pointed to by '__ZN16nvDisplayManager10superClassE'.  Expected symbol '__ZN27IOAccelLegacyDisplayMachine10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN13nvDisplayPipe10superClassE'.  Expected symbol '__ZN24IOAccelLegacyDisplayPipe10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN9nvSurface10superClassE'.  Expected symbol '__ZN20IOAccelLegacySurface10gMetaClassE' to be defined in another kext
	com.apple.GeForce:
		Cannot find symbol for metaclass pointed to by '__ZN16nvDisplayManager10superClassE'.  Expected symbol '__ZN27IOAccelLegacyDisplayMachine10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN13nvDisplayPipe10superClassE'.  Expected symbol '__ZN24IOAccelLegacyDisplayPipe10gMetaClassE' to be defined in another kextCannot find symbol for metaclass pointed to by '__ZN9nvSurface10superClassE'.  Expected symbol '__ZN20IOAccelLegacySurface10gMetaClassE' to be defined in another kext

Please reboot the machine to avoid potential issues rerunning the patcher
Press [ENTER] to continue

**Comment by Tiger-AC** [comment]
Now I can't even login to Catalina, Big Sur, & Monterey anymore. Every time when I attempting to login, the system log me out immediately. I suspect it may be caused by some sort of kernel panic. But I can't login to check the log files.
The only macOS I can login right now is High Sierra, without OCLP. It runs great with full functionality including brightness control and full brightness at max setting. External display works as well (only connected to one external monitor).

**Comment by Ausdauersportler** [comment]
Big Sur does not need any patching! So do not even try.

Only Monterey needs root volume patching  for Kepler and WiFi.

When changing OCLP do PRAM reset. Try to roll back to pre 0.3.1 and boot into Big Sur to verify it is working, again.

**Comment by Tiger-AC** [comment]
> Big Sur does not need any patching! So do not even try.
> 
> Only Monterey needs root volume patching for Kepler and WiFi.
> 
> When changing OCLP do PRAM reset. Try to roll back to pre 0.3.1 and boot into Big Sur to verify it is working, again.

After booting up with 0.3.0 and reinstall Big Sur (to get rid of any Post-Install Volume Patch), I can now login, and the Messages app works very well with the K3100M card😅
This means there may be some issues starting from 0.3.1. I will try 0.3.1 again and report back.

**Comment by Tiger-AC** [comment]
Just like to report back: I've just successfully installed Big Sur & Monterey with OCLP 0.3.1.
This issue may be related to the previous installed post-install patches with HD6970 interfered with the newly installed K3100M.
