### ISSUE TITLE
[Bug]: intermittent connection to MIDI device

### ISSUE THREAD

**Issue by dirkgently73** [dortania/OpenCore-Legacy-Patcher#723]
### Machine Model

MacBookAir6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (After Logging in)

### What is the Issue?

At boot, the system gets stuck trying to recognize a connected MIDI device.  If I disconnect the MIDI device, it boots fine but then, as I reconnect the MIDI device the connection is intermittent. Actually connection to the MIDI device is lost and a new connection to the same device appears. Usually connection lasts for less than a minute.
The MIDI setup was working fine with Big Sur before the upgrade to Monterey with Opencore.
Many thanks.

**Comment by khronokernel** [comment]
Related:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/716

We don't touch the audio stack at all, if mainline (0.3.2) experiences this issue then it's an Apple/Monterey bug

**Comment by dirkgently73** [comment]
Ok, many thanks.
