### ISSUE TITLE
[Bug]:  SAFARI.... macbook 5,2.... SAFARI Just NOT Working. Using CHROME now!

### ISSUE THREAD

**Issue by nathanb0** [dortania/OpenCore-Legacy-Patcher#724]
### Machine Model

MacBook5,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

SAFARI has ground to a HALT, frozen screens  dont scroll down and streaming doesnt work and its slow.

WORK AROUND to tap the address bar with the mouse seems to remove the lag until the next action.

Is anyone else having SAFARI problems like this.. I would like to know as I am forced to use GOOGLE CHROME, (works well)

**Comment by educovas** [comment]
Know issue, #108
