### ISSUE TITLE
[Bug]: OpenCore Legacy Patcher install issue Big Sur on Mac Pro 3,1

### ISSUE THREAD

**Issue by kinggab** [dortania/OpenCore-Legacy-Patcher#726]
### Machine Model

MacPro3,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I have been following the Mr Macintosh video instructions (posted September 2021) using the 2.4 version of the Open Core patcher.  I want to partition my ssd on my Mac 3,1 which has Yosemite as the OS.  It has the original non metal video card.  Following the instructions to create the usb installer, used TUI and followed the settings adjustments that needed to be made.  USB stick with Big Sur installer and Opencore with EFI made.  Reboot, option and go into the OC EFI to Big Sur recovery and partition the drive and install Big Sur.  Now I have tried this three times, and all have the same result.  Upon final reboot, the computer goes back to the USB OC EFI Recovery.  If I reboot and hold the option button, and select the new partition, it will not open to what should be the Big Sur create admin settings window to set up a user account in the new OS.  I can't figure out what I am doing incorrectly.  I have read the trouble shooting section, and it isn't clear how to rectify this.  To uninstall opencore I would have to go back to my Yosemite partition and remove it from the usb drive, then reset NVRAM and start over?  I could use some advise.  Thanks!

**Comment by khronokernel** [comment]
Use forums for troubleshooting
