### ISSUE TITLE
[Bug]: Unable to start macOS installer

### ISSUE THREAD

**Issue by fabien-p** [dortania/OpenCore-Legacy-Patcher#727]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I'm always stuck at the beginning of the black startup screen of Big Sur installer (20% on the progess bar), even after waiting 2 hours... (since OCLP version 0.0.23), so unable to reach the installer window.

I was able to reach the installer window with OCLP 0.0.22 or lower, and to install Big Sur with this version of OCLP, but with this version the sound through internal speakers doesn't work and isn't available in the pref pane.

### Any Additional Information

Its an iMac 12,2, upgraded with GeForce GTX 780M (vbios updated / Nick[D]vB) and a Broadcom BCM43xx.

**Comment by Ausdauersportler** [comment]
On the iMac GPU thread there are hundreds of (silent) users with Big Sur on iMac12,2 and Kepler cards. Most have already upgraded to OCLP 0.2.5 or later.

Please do a PRAM reset when changing the OC(LP) version and retry. AppleALC works perfectly with my current six iMac11,x and iMac12,x systems. 

I would assume you have a local (hardware?) problem?
GPU, Memory?
Have you tried the system with High Sierra and GPU load tests like UNIGINE Valley?
Did you run any hardware checking programs like ASD? (download links on the GPU thread)

**Comment by khronokernel** [comment]
I assume this is the infamous VBIOS issue seen with older Kepler VBIOS. Issues's been reported many times here. Easy fix is to flash a newer VBIOS by Nick from the iMac MXM MacRumors forum

**Comment by fabien-p** [comment]
ok, thanks for your answers.
I've tried Unigine Valley this morning, with no issues.
I will try to a newer vbios today.

**Comment by fabien-p** [comment]
Many thanks.
I've tried the 780M_BR3 vbios from MacRumors 2011 iMac Graphic card upgrade forum, and I was able to install Big Sur.
The other version available on this forum doesn't work on my iMac...
Everything seems ok, but unfortunately, there's still no sound, except the boot sound.
Only the digital optical out is available in the pref pane.
Do you have an idea?
