### ISSUE TITLE
[Info]: 

### ISSUE THREAD

**Issue by humbertocruz** [dortania/OpenCore-Legacy-Patcher#728]
### Machine Model

Macmini6,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

sorry, it's not a exactly a bug but I haven't found where to report a curious ocorrency
Well, I install MacOS Monterey on a Mac Mini Late 2012, I was aware that the HD4000 video has no accel on default Macos driver and because of that I should start the Post-Install script. The curious fact is that before run the post-install script my monitor LG ultra-wide 2560x1080 resolution connected by HDMI. This HDMI connection is know that have not that resolution on my Mac Mini model, but, with the Monterey default graphics driver, it was working at 2560x1080, very slow, but working.
After the post-script install, the max resolution come back to FHD 1920x1080 and I change the connection to the mini display port to get 2560x1080 again.
Thanks a lot, my old mac mini got new life again and it's fast as a new ;)

**Comment by educovas** [comment]
Driver limitation

> I haven't found where to report a curious ocorrency
There is the OCLP Discord server: https://discord.gg/rqdPgH8xSN
