### ISSUE TITLE
macbook air 5,1 gpu detected as display 4MB

### ISSUE THREAD

**Issue by bhjdhgcehgrehge** [dortania/OpenCore-Legacy-Patcher#729]
### Machine Model

MacBookAir5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Integrated GPU is detected as display 4MB

**Comment by bhjdhgcehgrehge** [comment]
Pls get a workaround for this quickly

**Comment by educovas** [comment]
> Have you verified whether this issue is covered in our guide?

Read the guide please: https://dortania.github.io/OpenCore-Legacy-Patcher/POST-INSTALL.html#applying-post-install-volume-patches
