### ISSUE TITLE
mount_apfs: volume could not be mounted: Resource busy

### ISSUE THREAD

**Issue by doriansgithub** [dortania/OpenCore-Legacy-Patcher#730]
### Machine Model

MacBookPro9,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

mount_apfs: volume could not be mounted: Resource busy

Can't install post install patches.

Computer therefore has no sleep and / or graphics acceleration.

### Any Additional Information

I've tried booting onto the EFI internal and the external USB used to update. Was able to start up in SafeMode from the USB EFI, and still get the same error.

mount_apfs: volume could not be mounted: Resource busy

It's either busy or just can't mount it.  Did diskFirstAid and everything looks fine.

**Comment by khronokernel** [comment]
macOS bug, ensure no over the air updates are being prepared. Nothing we can do. 
Use forums for further troubleshooting
