### ISSUE TITLE
Monitor Resolution Issue

### ISSUE THREAD

**Issue by NightRai** [dortania/OpenCore-Legacy-Patcher#733]
### Machine Model

MacBookPro5,4

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Does Monterey support all UHD and QHD monitors to provide full resolution? I am running Mini DP to HDMI cable on my MacBook Pro 5,4. 

LG 35WN65C gives me 1080p maximum resolution 
LG 34WL85C give me full 3440 * 1440 resolution

Any one experiencing similar issues or have solutions?

**Comment by khronokernel** [comment]
MacBookPro5,4 is maxed at a DisplayPort 1.1 connection, this is a hardware limitation. Please use forums for non-patcher questions

**Comment by NightRai** [comment]
Ya but one monitor guess full UHQ while the other gives 1080p. I will thanks for your reply.

**Comment by AndreasJordanidis** [comment]
9600m gt shouldnt be able to display anything above 2560p unless its 30hz
