### ISSUE TITLE
Photos appeared messed up after update to 11.6.2

### ISSUE THREAD

**Issue by airman1951** [dortania/OpenCore-Legacy-Patcher#734]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

After applied the update to 11.6.2 the photos in Photos app appeared as completely messed up.  The problem occurred some time ago and was fixed.  Unfortunately it is back now.  I boot with the last nightly as well as with 0.2.5 and 0.3.1 with the same results.
![Screenshot 2021-11-16 at 14 42 59](https://user-images.githubusercontent.com/77781242/141998028-94c56e87-c3b8-418a-8450-9c2a4e421a66.png)

**Comment by airman1951** [comment]
The issue has been reported in macrumors forum too.[  ](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-30611161)

**Comment by airman1951** [comment]
https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-30611161

**Comment by educovas** [comment]
Duplicate #108

**Comment by airman1951** [comment]
Well, but why Photos worked fine with 11.6.1 and back to messed up with 11.6.2?  And remember that MBP8,2 with disabled dGPU doesn't have billions of colours but millions only, so the workaround proposed in #108 doesn't make sense.
Anyway, thanks for your support.

**Comment by educovas** [comment]
Acceleration patches were updated to the same code as for Monterey on nightly build

**Comment by airman1951** [comment]
Still me.  I reapplied the acceleration patches with OCLP 0.2.5 and now Photos works fine!  The issue is in the acceleration patches released in the last nightlies.  They work for Monterey but something is wrong for BigSur, at least for legacy GPU. Please reopen the issue.
