### ISSUE TITLE
[Question] Why is OCLP v0.3.1 running an older OC Bootloader? (v0.7.3 vs v0.7.5)

### ISSUE THREAD

**Issue by SemoTech** [dortania/OpenCore-Legacy-Patcher#735]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hello, this is a question, not a bug/issue.

I was running the utility "Hackintool v3.6.5" and under the [Boot] menu it showed the current and latest OC bootloader.

![image](https://user-images.githubusercontent.com/1452100/142032008-13a79c96-f2de-4526-97f9-047586d3bdbf.png)

Subsequently, Hackintool ask me if I wanted the latest OC 0.7.5

![image](https://user-images.githubusercontent.com/1452100/142032264-17c55b5b-7502-42e3-8585-6e7e278b6fec.png)

Any reason OCLP is using the older v0.7.3 of OC and not v0.7.5?  Should I upgrade?

Thanks.

**Comment by khronokernel** [comment]
We're on 0.7.5 in mainline

**Comment by SemoTech** [comment]
Apologies @khronokernel but what do you mean?

I downloaded OCLP v0.31 from the Main Branch and it comes with the older 0.7.3 Botloader.

Is there a different link/download I should use?  Please provide.

Thank you.

**Comment by khronokernel** [comment]
Mainline != release. 

This is a GitHub repo, all source files are public. Thus all changes made in mainline may not be in the latest release as we continue working on the project. Releases are done when we feel the project is ready for a new release with the current changes

**Comment by SemoTech** [comment]
Got it @khronokernel, so it's updated to 0.7.5 but in a "nightly" build, not the current 0.3.1 release, understood!  
Will wait for a new release then.

My thanks for all the hard work!
