### ISSUE TITLE
Leaking Graphic, Slow Safari, Brightness keyes not work,

### ISSUE THREAD

**Issue by HerbJul** [dortania/OpenCore-Legacy-Patcher#737]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

There are several problems
-Safarie reacts very slowly when minimising the window
-The brightness cannot be adjusted
-Grfaik sometimes replays very slowlyPlease clearly explain the issue
Mac cannot be put into sleep mode

**Comment by khronokernel** [comment]
> Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages
> false

**Comment by HerbJul** [comment]
Checked it but it was not mentioned and thus could not fix the problem

**Comment by AndreasJordanidis** [comment]
you did not apply post installation patches
