### ISSUE TITLE
Virtualization disabled when option booting to Boot Camp partition

### ISSUE THREAD

**Issue by Converseallstar95** [dortania/OpenCore-Legacy-Patcher#738]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Historically, and normally (at least with my model MBP), when you have a macOS partition and Boot Camp partition, the only way to get virtualization enabled in Windows is by selecting Windows as the startup disk. When you just hold option at boot, it always shows disabled in Task Manager. When booting through OpenCore it acts as an option boot, thus disabling virtualization. Is there a way OC can add a patch or fix to this? I found a SO thread about how to fix it in rEFInd.

https://apple.stackexchange.com/a/234819

**Comment by khronokernel** [comment]
For requesting rEFind like functionality, you'd be best to file against OpenCorePkg as this is what our backend runs off of for UEFI:
* https://github.com/acidanthera/OpenCorePkg

**Comment by Converseallstar95** [comment]
Ok great; thank you!

**Comment by Converseallstar95** [comment]
> For requesting rEFind like functionality, you'd be best to file against OpenCorePkg as this is what our backend runs off of for UEFI:
> 
> * https://github.com/acidanthera/OpenCorePkg

Thanks @khronokernel but there isn't an issues section on that project for me to request it in?

**Comment by Converseallstar95** [comment]
> It's in the bugtracker:
> https://github.com/acidanthera/bugtracker/issues

Thank you!
