### ISSUE TITLE
Post Install Process requires   Disable AMFI,  nvram boot-args="$(nvram boot-args) amfi_get_out_of_my_way=1"

### ISSUE THREAD

**Issue by megamuteki** [dortania/OpenCore-Legacy-Patcher#739]
### Machine Model

MacPro5,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I am trying to postinstall.
Post Install Process requires   Disable AMFI,  nvram boot-args="$(nvram boot-args) amfi_get_out_of_my_way=1"

I have tried after logled in
sudo nvram boot-args="amfi_get_out_of_my_way=1"

I have tried by recovery mode.
nvram boot-args="amfi_get_out_of_my_way=1"
nvram boot-args="$(nvram boot-args) amfi_get_out_of_my_way=1"
But did not effect.

I can not proceed post install.

**Comment by tiziodcaio** [comment]
Did you used the latest version of the application? Disabling AMFI no more required for patching

**Comment by khronokernel** [comment]
If OCLP determines your GPU is non-Metal, it will enable the library validation patch that negates the reliance of `amfi` argument:
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/resources/defaults.py#L15-L16

Thus enabling `_cs_require_lv`/`Disable Library Validation Enforcement` patch in OCLP during build time:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/resources/build.py#L743-L746

If OCLP is incorrectly detecting the GPU present in your system, please open OCLP's TUI: `Patcher Settings -> Dump detected hardware` and upload the output

**Comment by megamuteki** [comment]
Thanks for your comment despite you being too busy.
Now that you say so, gpu problem occurs in my mind.
I do not use genuine apple GPU card, I use self efied windows gpu card.
Thank you.

**Comment by khronokernel** [comment]
So I see your system has the HD7950 (though your Device ID returns [R7 370 / R9 270/370](https://devicehunt.com/view/type/pci/vendor/1002/device/6811)) which should be Metal compliant.

Additionally you have no unsupported Wifi card present so a bit confused on what root patches were you trying to apply. 

What did OCLP present you with for root patching in the menu? ie. what did it say for hardware needing the root patches?

**Comment by megamuteki** [comment]
Thanks for your Info.
My wifi may  make problem.

I am sorry make you confusion.
I have confuded what gpu requested AMI.

I have tested 5 GPU card.

a.8800GT
Requested
amfi_get_out_of_my_way=1

b.GT120
Requested
amfi_get_out_of_my_way=1

c.HD4870
Requested
amfi_get_out_of_my_way=1

d.HD5770
Requested
amfi_get_out_of_my_way=1

e.HD7950
No root patches required.



[OpenLegacyCoreTest.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7561030/OpenLegacyCoreTest.zip)

**Comment by khronokernel** [comment]
You need to rebuild OpenCore with the GPU installed and install to disk, then reboot. Only then will the changes apply. You cannot use the same OpenCore config for a Metal and non-Metal machine

**Comment by megamuteki** [comment]
Vey thanksful for your follow uo.
I have rebuild OpenCore with the GPU installed and install to disk, then reboot on GPU 8800GT.
But did not proceed to patch.
WiFi card may made probl


-------AftePostInstallMsg-----
The following patches will be applied:
- Add Legacy Nvidia Tesla Graphics Patch
Would you like to continue with Root Volume Patching?(y/n): y
- Continuing with Patching
- Verifying whether Root Patching possible

Cannot patch! Please disable AMFI.
For Hackintoshes, please add amfi_get_out_of_my_way=1 to boot-args

Press [ENTER] to return to the main menu: 


---------Dumped--------
#############################
# Dumping detected hardware #
#############################

Computer(real_model='MacPro5,1', real_board_id='Mac-F221BEC8', reported_model='MacPro5,1', reported_board_id='Mac-F221BEC8', gpus=[NVIDIA(vendor_id=4318, device_id=1600, class_code=196608, name='PXS1', model='NVIDIA GeForce GT 120', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)', arch=<Archs.Tesla: 'Tesla'>)], igpu=None, dgpu=None, storage=[SATAController(vendor_id=32902, device_id=14882, class_code=67073, name='SATA', model=None, acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x1f,0x2)')], wifi=None, cpu=CPU(name='Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz', flags=['FPU', 'VME', 'DE', 'PSE', 'TSC', 'MSR', 'PAE', 'MCE', 'CX8', 'APIC', 'SEP', 'MTRR', 'PGE', 'MCA', 'CMOV', 'PAT', 'PSE36', 'CLFSH', 'DS', 'ACPI', 'MMX', 'FXSR', 'SSE', 'SSE2', 'SS', 'HTT', 'TM', 'PBE', 'SSE3', 'DTES64', 'MON', 'DSCPL', 'VMX', 'EST', 'TM2', 'SSSE3', 'CX16', 'TPR', 'PDCM', 'SSE4.1', 'SSE4.2', 'POPCNT']), oclp_version='0.3.2', opencore_version='REL-075-2021-11-01', bluetooth_chipset='BRCM2046 Hub', third_party_sata_ssd=False)

Press [ENTER] to exit:

**Comment by megamuteki** [comment]
Thanks sir.
Today I have rebuild OpenCore with the GPU installed and install to disk, then reboot on GPU GT120.
Every thing work OK.

Last login: Sat Nov 20 07:10:35 on console
muteki@Mac-Pro ~ % cd Developper   
muteki@Mac-Pro Developper % cd OpenCore-Legacy-Patcher        
muteki@Mac-Pro OpenCore-Legacy-Patcher % python3 ./OpenCore-Patcher.command
- Loading...
- No arguments present, loading TUI
##################################
# OpenCore Legacy Patcher v0.3.2 #
#   Selected Model: MacPro5,1    #
##################################

This model is supported

1.  Build OpenCore
2.  Install OpenCore to USB/internal drive
3.  Post-Install Volume Patch
4.  Change Model
5.  Patcher Settings
6.  Installer Creation
7.  Credits
Q.  Quit

Please select an option: 3

##########################
# Patching System Volume #
##########################
Patches Root volume to fix misc issues such as:

- Metal Graphics Acceleration
  - Intel: Ivy Bridge (4000 series iGPUs)
  - Nvidia: Kepler (600-700)
- Non-Metal Graphics Accelertation
  - Intel: Ironlake - Sandy Bridge
  - Nvidia: Tesla - Fermi (8000-500 series)
  - AMD: TeraScale 1 and 2 (2000-6000 series)
- Audio support for iMac7,1 and iMac8,1
- Wifi support for BCM94328, BCM94322 and Atheros cards

WARNING: Root Volume Patching is still in active development, please
have all important user data backed up. Note when the system volume
is patched, you can no longer have Delta updates.

Supported Options:

1. Patch System Volume
2. Unpatch System Volume
B. Exit
        
Patch System Volume?: 1
- Starting Patch Process
- Determinging Required Patch set for Darwin 21
- Found GPU (0): 10DE:640

The following patches will be applied:
- Add Legacy Nvidia Tesla Graphics Patch
Would you like to continue with Root Volume Patching?(y/n): y
- Continuing with Patching
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Apple binaries missing

# Downloading: 12-Monterey.zip #
################################

169.2623472213745MB Downloaded of 0.0005941390991210938MB
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/Users/muteki/Developper/OpenCore-Legacy-Patcher/payloads
- Found Root Volume at: disk3s5
- Mounting APFS Snapshot as writable
Password:
- Successfully mounted the Root Volume
- Running patches for MacPro5,1
- Installing legacy Nvidia Patches
- Detected supported OS, installing Acceleration Patches
- Installing Nvidia Acceleration Kext patches for Big Sur/Monterey
- Deleting AMDRadeonX4000.kext
- Deleting AMDRadeonX4000HWServices.kext
- Deleting AMDRadeonX5000.kext
- Deleting AMDRadeonX5000HWServices.kext
- Deleting AMDRadeonX6000.kext
- Deleting AMDRadeonX6000Framebuffer.kext
- Deleting AMDRadeonX6000HWServices.kext
- Deleting AppleIntelBDWGraphics.kext
- Deleting AppleIntelBDWGraphicsFramebuffer.kext
- Deleting AppleIntelCFLGraphicsFramebuffer.kext
- Couldn't find AppleIntelHD4000Graphics.kext, skipping
- Deleting AppleIntelHD5000Graphics.kext
- Deleting AppleIntelICLGraphics.kext
- Deleting AppleIntelICLLPGraphicsFramebuffer.kext
- Deleting AppleIntelKBLGraphics.kext
- Deleting AppleIntelKBLGraphicsFramebuffer.kext
- Deleting AppleIntelSKLGraphics.kext
- Deleting AppleIntelSKLGraphicsFramebuffer.kext
- Deleting AppleIntelFramebufferAzul.kext
- Couldn't find AppleIntelFramebufferCapri.kext, skipping
- Deleting AppleParavirtGPU.kext
- Couldn't find GeForce.kext, skipping
- Deleting IOAcceleratorFamily2.kext
- Deleting IOGPUFamily.kext
- Installing General Acceleration Kext patches for Big Sur/Monterey
- Adding IOAcceleratorFamily2.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Adding GeForceGA.bundle
- Adding GeForceTesla.kext
- Adding GeForceTeslaGLDriver.bundle
- Adding GeForceTeslaVADriver.bundle
- Adding NVDANV50HalTesla.kext
- Adding NVDAResmanTesla.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Adding NVDAStartup.kext
- Merging general legacy Frameworks
- Merging Monterey WebKit patch
- Merging general legacy PrivateFrameworks
- Rebuilding Kernel Cache (This may take some time)
- Successfully built new kernel cache
- Creating new APFS snapshot
- Unmounting Root Volume (Don't worry if this fails)
- Patching complete

Please reboot the machine for patches to take effect

Press [ENTER] to continue
