### ISSUE TITLE
Airplay to Mac Not showing up on iMac 14,1 on 12.1 beta 3

### ISSUE THREAD

**Issue by Monkiey** [dortania/OpenCore-Legacy-Patcher#740]
### Machine Model

iMac14,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Airplay to mac is still broken in macOS 12.1 beta 3

**Comment by mycroftcanner** [comment]
It is already fixed in the nightly build... However if someone is looking for a link to the nightly builds I couldn't find it anywhere

**Comment by Tiger-AC** [comment]
not working neither in my iMac12,2 with upgraded K3100M, using the latest v0.3.2n

**Comment by anshar666** [comment]
MacBook Pro 15" mid 2012
intel HD 4000
Nvidia geforce GT 650M
macOS 12.0.1 

trying to get airplay or screen mirroring working.
I can get the Mac connected to the tv but its choppy or super laggy on the tv or won't keep up.

is there any known fix for this or its in the works? 

thanks

**Comment by khronokernel** [comment]
Moved for better documentation:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/783
