### ISSUE TITLE
Implement SATA Disk Vendor Detection

### ISSUE THREAD

**Issue by blahdy** [dortania/OpenCore-Legacy-Patcher#741]
### Machine Model

MacBookPro10,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

There is no check if a sata ssd is third party, which leads to hibernation and trim being broken since thirdparty quirk is disabled. It is also reverted upon OC upgrade in case it was enabled manually.

**Comment by khronokernel** [comment]
If you wish for hardware detection to be implemented for 3rd party drives, please upload an IOReg of a system with a stock Apple drive as well as a one with a 3rd party disk

* https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip?raw=true
  * Usage: File -> SaveAs, upload generated binary

**Comment by blahdy** [comment]
[Archive.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7558721/Archive.zip)
the serv ioreg is from a hack with a native ssd from an ivy air 
the macbook is with a swapped thirdparty ssd
