### ISSUE TITLE
Garage Band won't work on an iMac 14.1 runnin Monterey 15, 15.1 or 15.2 beta 

### ISSUE THREAD

**Issue by mycroftcanner** [dortania/OpenCore-Legacy-Patcher#743]
### Machine Model

iMac14,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Garage Band won't work on an iMac 14.1 runnin Monterey 15, 15.1 or 15.2 beta Please clearly explain the issue

Garage Band will display the following message:

>Unable to initialise graphics. This typically happens when running inside of an unsupported virtual machine environment, or when running on an unsupported Mac.

**Comment by khronokernel** [comment]
> Is this issue with a 3rd party application?
> false

While the application may be made by Apple, it's not a core application. Additionally if you've installed the post install patches for Monterey, your system will have graphics acceleration.
As the application is not bundled on the root volume, dedicating resources to a moving target is difficult. Feel free to research further yourself and provide patch sets however, we appreciate any help we can get
