### ISSUE TITLE
My experience with OCLP on iMac 12.1 running macOS Monterey and minor graphical errors.

### ISSUE THREAD

**Issue by mactito1** [dortania/OpenCore-Legacy-Patcher#748]
### Machine Model

iMac12,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Like many other users, I thank the OCLP team for their great work. My iMac 12.1 had stayed in High Sierra and now thanks to you I enjoy Monterey.

First I went from High Sierra to Big Sur with OCLP (the patch re-enabled Graphics Acceleration) and then via OTA it was updated to Monterey, the initial problem in Big Sur of strange colors I solved by forcing Million Colors on Billions with SwitchResX.

When I did the update to Monterey, the patch re-enabled Graphics Acceleration and Wi-Fi, which were not initially recognized by macOS. (I was connected by LAN and OCLP downloaded the drivers)

So far everything I have tried works without problems.

The only thing that I have noticed as a "bug" is that in the Menu Bar there are color changes when the mouse passes over it, but that is solved by activating "Reduce transparency" in the "Accessibility" section.

Hopefully some future update will allow you to have the option of transparency without bugs.

Once again thanks to the OCLP team for their excellent work.

**Comment by khronokernel** [comment]
Use forums please
