### ISSUE TITLE
Latest OCLP makes mbp10.1 always use dGPU

### ISSUE THREAD

**Issue by blahdy** [dortania/OpenCore-Legacy-Patcher#750]
### Machine Model

MacBookPro10,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

istat states that displaypolicyd is the dependency that requires dGPU to be active on the latest nightly.

previously installed 01.10.21 nightly properly switches gpus based on load.

**Comment by khronokernel** [comment]
Resolved, forgot to close
