### ISSUE TITLE
FaceTime stopped detecting hardware camera

### ISSUE THREAD

**Issue by FXlife** [dortania/OpenCore-Legacy-Patcher#751]
### Machine Model

MacBookPro10,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

It has been 10 days since I installed macOS Monterey by using a clean install as I was on Patched Sur. Everything was okay until this morning, FaceTime is unable to access to the on-device camera. I tried to sudo killall VDCAssistant in terminal, I restarted then shut down manually my computer. I also did reset the NVRAM but the software is telling it is not receiving any feed from the camera.

<img width="1088" alt="Screenshot 2021-11-21 at 15 15 28" src="https://user-images.githubusercontent.com/15075923/142765355-52b7a2fa-e056-427c-9d03-aab0a01fb330.png">

I did use FaceTime several times before that issue. I had received calls from my iPhone in FaceTime. Each time it was opened, it was showing the camera's viewer window. Now, it's just a blank dark window as you see on that picture above. By the way, PhotoBooth is opening and I can see myself on the screen using the built-in camera.

PS: I don't use any external camera or device.

**Comment by HackintoshHD** [comment]
Did you perhaps install VirtualBox on your MacBookPro Late 2012?

**Comment by FXlife** [comment]
I did not. I don't virtualize any OS on my Macbook

**Comment by khronokernel** [comment]
Was unable to replicate internally, assuming local installation issues. Use forums for further troubleshooting
