### ISSUE TITLE
MacPro5,1 not seeing SIP and Secureboot correctly... 

### ISSUE THREAD

**Issue by jbinder6342** [dortania/OpenCore-Legacy-Patcher#753]
### Machine Model

MacPro5,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

On branch -- * main   f840e30f [origin/main] Sync PatcherSupportPkg

with Nvidia GTX780 6GB

I need to set SIP and SBM manually to allow for post-install patching. 
--- 

Building Configuration on model: MacPro5,1
Created build folder

- Adding OpenCore v0.7.5 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.6
- Adding RestrictEvents.kext 1.0.5
- Adding AppleALC.kext 1.6.3
- Adding FeatureUnlock.kext 1.0.4
- Enabling VMM exemption patch
- Enabling HW_BID reroute
- Adding SurPlus Patch for Race Condition
- Fixing PCIe Storage Controller (1) reporting
- Fixing PCIe Storage Controller (2) reporting
- No 3rd Party NVMe drives found
- Found Wireless Device 14E4:43A0
- Adding AirportBrcmFixup.kext 2.1.3
- Setting Wireless Card's Country Code: US
- Found ARPT device at PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)
- Adding AppleALC.kext 1.6.3
- Found dGPU (1): 10DE:1007
- Failed to find Device path for dGPU 1
- Enabling Nvidia Output Patch
- Falling back to boot-args
- Adding OpenCanopy GUI
- Adding ExFatDxeLegacy.efi
- Adding SATA Hibernation Patch
- Enabling Verbose boot
- Enabling ShowPicker
- Adding bootmgfw.efi BlessOverride
- Fixing Content Caching support
- Using Model ID: MacPro5,1
- Using Board ID: Mac-F221BEC8
- Cleaning up files

Your OpenCore EFI for MacPro5,1 has been built at:
    /private/var/folders/b5/41v9qjgx3lvbvccwlnmx5sgc0000gp/T/_MEI3yuffH/Build-Folder/OpenCore-Build

Press [Enter] to continue

**Comment by khronokernel** [comment]
Are you editing the settings at all? By default OCLP should correctly detect the dGPU and thus disable SIP:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/resources/defaults.py#L17-L21

**Comment by jbinder6342** [comment]
nope -- This is default run.   I can edit security settings and turn both off and it works.  

This looks like the issue. 
Found dGPU (1): 10DE:1007
Failed to find Device path for dGPU 1

---- 

#############################
# Dumping detected hardware #
#############################

Computer(real_model='MacPro5,1', real_board_id='Mac-F221BEC8', reported_model='MacPro5,1', reported_board_id='Mac-F221BEC8', gpus=[NVIDIA(vendor_id=4318, device_id=4103, class_code=196608, name='PXS1', model='NVIDIA GeForce GTX 780', acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)', arch=<Archs.Kepler: 'Kepler'>)], igpu=None, dgpu=None, storage=[SATAController(vendor_id=6945, device_id=1554, class_code=67073, name='PXS2', model=None, acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x7,0x0)/Pci(0x0,0x0)'), SATAController(vendor_id=32902, device_id=14882, class_code=67073, name='SATA', model=None, acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x1f,0x2)')], wifi=Broadcom(vendor_id=5348, device_id=17312, class_code=163840, name='ARPT', model=None, acpi_path=None, pci_path='PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)', country_code='US', chipset=<Chipsets.AirportBrcmNIC: 'AirportBrcmNIC supported'>), cpu=CPU(name='Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz', flags=['FPU', 'VME', 'DE', 'PSE', 'TSC', 'MSR', 'PAE', 'MCE', 'CX8', 'APIC', 'SEP', 'MTRR', 'PGE', 'MCA', 'CMOV', 'PAT', 'PSE36', 'CLFSH', 'DS', 'ACPI', 'MMX', 'FXSR', 'SSE', 'SSE2', 'SS', 'HTT', 'TM', 'PBE', 'SSE3', 'PCLMULQDQ', 'DTES64', 'MON', 'DSCPL', 'VMX', 'SMX', 'EST', 'TM2', 'SSSE3', 'CX16', 'TPR', 'PDCM', 'SSE4.1', 'SSE4.2', 'POPCNT', 'AES', 'PCID']), oclp_version='0.3.2', opencore_version='REL-075-2021-11-01', bluetooth_chipset='BRCM20702 Hub', third_party_sata_ssd=True)

**Comment by khronokernel** [comment]
> This looks like the issue.
> Found dGPU (1): 10DE:1007
> Failed to find Device path for dGPU 1

Unrelated

**Comment by jbinder6342** [comment]
confirmed fix on local system. 


James Binder
(408) 761-1403 (c)
(865) 675-0388 (h)
***@***.*** ***@***.***>
