### ISSUE TITLE
Acrobat Reader DC not starting

### ISSUE THREAD

**Issue by adrialopez** [dortania/OpenCore-Legacy-Patcher#754]
### Machine Model

iMac13,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in), Other/Non-Applicable

### What is the Issue?

Acrobat Reader DC stucked on background without starting

### Any Additional Information

Any build is working. tryed the High Sierra and has the same problem

**Comment by khronokernel** [comment]
> Is this issue with a 3rd party application?
> If yes, please move discussions onto forums. We're unable to dedicate time to working on every single application that may be broken in macOS. Only file issues if you have a fix you'd like to add to our project

When you filed the issue, this was shown
