### ISSUE TITLE
Graphics Broken during work AND after hibernate (Radeon HD 4850)

### ISSUE THREAD

**Issue by richy-66** [dortania/OpenCore-Legacy-Patcher#755]
### Machine Model

iMac11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Without special notice my graphic can break completely. The only solution than is a reboot.
This happens (i think with heavier graphics load) during "normal" work suddenly OR after waking the machine up after hibernate. There it happens 100%.
![Bildschirmfoto 2021-11-23 um 08 50 36](https://user-images.githubusercontent.com/64616823/142990152-0025140e-6700-47f0-a5b9-2e06346cf957.png)
![Bildschirmfoto 2021-11-23 um 08 50 28](https://user-images.githubusercontent.com/64616823/142990178-b93cfe4b-e575-4305-a67d-92acc69963aa.png)

**Comment by Ausdauersportler** [comment]
Welcome to the world wide operating club of people experiencing a broken ATI GPU in 2009-2011 iMacs. This is not an OCLP issue, this is a dying GPU. 
But there is a way out of this: Replace your GPU following this [thread](https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/post-17425857).
