### ISSUE TITLE
A Required firmware update could not be installed

### ISSUE THREAD

**Issue by GSteddin** [dortania/OpenCore-Legacy-Patcher#758]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Using the command line Patcher (0.3.1)  I boot into EFI - Run the Monterey Installer and when it reboots to finish I get the error: "A required firmware update could not be installed"

I changed the Setting before building to Patcher Setting > SMBIOS Settings >Set SMBIOS Spoof Level = Moderate

and I still get this error.

![IMG_5380](https://user-images.githubusercontent.com/77550348/143294747-18abd33d-36a4-4bec-9b85-0a73a9b2298c.jpeg)

### Any Additional Information

Thank you VERY much for your work on this running Big Sur on My 5,1 mac has been amazing and I am greedy for Monterey.

**Comment by khronokernel** [comment]
Duplicate, resolved with 0.3.2/VMM spoofing

**Comment by GSteddin** [comment]
are you saying that there is a 0.3.2 version that will fix this? I don't
see it to download.

**Comment by flagersgit** [comment]
0.3.2 is currently not released; right now, it is only available as a nightly for testing purposes. Please see [SOURCE.md](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md) for more information.
