### ISSUE TITLE
Monterey no longer offered with latest nightly

### ISSUE THREAD

**Issue by blahdy** [dortania/OpenCore-Legacy-Patcher#759]
### Machine Model

MacBookPro10,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

When using 0.3.0 Monterey was suggested as an update. No longer the case with the latest nightly.

**Comment by khronokernel** [comment]
We don’t support in-OS upgrades (different from general updates), dangerous and easy for a user to break an install. Only USB installations are supported

**Comment by blahdy** [comment]
but these changes also break updates within Big Sur. I've had a developer beta of 11.6.2 installed and after updating to the latest nightly system updates do not offer the stable release of 6.2 unlike the release version

**Comment by blahdy** [comment]
> We don’t support in-OS upgrades (different from general updates), dangerous and easy for a user to break an install. Only USB installations are supported

or does that mean that a user should use full release usb installers to install minor updates?
