### ISSUE TITLE
Issue when changing monitor settings/ gpu acceleration bugs out

### ISSUE THREAD

**Issue by Gonz1738** [dortania/OpenCore-Legacy-Patcher#760]
### Machine Model

iMac11,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

So this issue happens every time I try to mirror the screen to my monitor. Basically the screen become all distorted and graphical issues happen. Only way to fix it is to restart the iMac. I believe it happens when the graphics restart or like driver reboot.

### Any Additional Information

no

**Comment by Ausdauersportler** [comment]
If you are just reporting your card is showing artifacts/issues under load you should face the bitter truth of having a failing piece of hardware (as thousands if iMac11,x users before).

**Comment by Gonz1738** [comment]
Thanks for the advice. Could I fix this by changing the gpu for one that is
better and that works for my iMac?

**Comment by Ausdauersportler** [comment]
Yes, you can even install a more recent metal AMD or NVIDIA GPU and will experience full support and no patching. Check this [thread](https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/post-17425857) - on the first post there is a list of working cards with pro/con/known issues.

**Comment by educovas** [comment]
That doesn't look like an GPU failing, there is a known bug with AMD TS1 cards that everything gets distorted after waking from sleep or changing screen resolution

Last good OS without this bug is Big Sur 11.2.3

**Comment by Ausdauersportler** [comment]
The only cure remains the same!
