### ISSUE TITLE
Volume Icon doesn't appear in the Finder

### ISSUE THREAD

**Issue by joevt** [dortania/OpenCore-Legacy-Patcher#761]
### Machine Model

iMac14,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Open Core Legacy Patcher installs a .VolumeIcon.icns file to the root directory of the EFI volume, but when the EFI partition is mounted, the icon for the Volume shown in the Finder is unchanged.

I believe the Legacy Patcher should set the custom folder icon flag in the Finder Info for the root directory of the EFI volume. One way to update the Finder Info is to use xattr. see the `setfoldercustomicon` command in https://gist.github.com/joevt/6d7a0ede45106345a39bdfa0ac10ffd6#file-diskutil-sh-L685

**Comment by khronokernel** [comment]
We're mainly following Apple's steps with macOS Installers as well as BootCamp volumes where only the VolumeIcon.icns is placed but not adjusting other entires such as xattr. Additionally the ESP is very rarely meant to be seen by the end user, so no one would notice the icon.

Thank you for the information however we don't believe this is of much importance at this time.
