### ISSUE TITLE
Wi-Fi no password prompt iMac11,3

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#762]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I know this is a known bug to Dortania, but I thought I may aswell report it for the specific mac model. I have patched 12.0.1 (Latest Monterey release) and everything worked as it did in Big Sur. Except the Wi-Fi. Following Mr. Macintosh's guide, I downloaded the TUI (offline) variant due to my computer not having native Wi-Fi support. The OCLP - TUI noted that it would patch the Wi-Fi card, and it sort of did. I can now view networks, (I could not before) although when you press or attempt to connect to a certain network, no password prompt appears. I fixed this issue by booting into my separate HS partition, and reading the guide. I then proceeded to join the network via the "other" option. The reason I am posting this issue, is because the OCLP application claims to patch the Wi-Fi, although partially it is broken. For less advanced users, they may not know which security type their Wi-Fi provider utilizes, and this may be challenging for them. Maybe have it say in the application itself, that Wi-Fi connecting may not work and to read the guide, or something else. I am not sure, just wanted to report this bug to the team. Aside from this, Monterey is a smooth and wonderful experience for me. Thank you so much for your amazing work, and thank you for taking your time to read this. Enjoy your day.

**Comment by educovas** [comment]
Password window is already fixed on 0.3.2 nightly and will be included on next release for normal users.

**Comment by Thyssenkrupp234** [comment]
Just curious, @educovas, when will the next update be released? If you don't know that's fine, just curious. Thanks again.

**Comment by educovas** [comment]
I don't know know when, devs will make a release when nightly is tested enough.
