### ISSUE TITLE
Wifi Fixes

### ISSUE THREAD

**Issue by HerbJul** [dortania/OpenCore-Legacy-Patcher#763]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Found the kexts that solve the wifi problems.

IO80211M
IO80211Catalina

**Comment by educovas** [comment]
MacBookPro9,2 does not need patched WiFi kexts, it already works via spoofing using OpenCore.
Also, those kexts doesn't work on Monterey.
