### ISSUE TITLE
Intel HD 3000 Showing strange shadows

### ISSUE THREAD

**Issue by khashabawy** [dortania/OpenCore-Legacy-Patcher#764]
### Machine Model

MacBookPro8,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

hazard behavior in UI Happens when moving the cursor over menus and specially in Dark regions 

MacBook Pro (13-inch, Early 2011)
Intel HD 3000 512 MB

Screenshots
![File 1](https://user-images.githubusercontent.com/400698/143792927-156e02bc-67d2-4d70-a85e-ccf97ee3388d.jpeg)
![File 2](https://user-images.githubusercontent.com/400698/143792929-241b4071-95b5-41fe-84cd-f5e07d64ccc1.jpeg)
![File 3](https://user-images.githubusercontent.com/400698/143792932-62dd2f11-97ad-4f6c-887e-a9fbec8f5bc8.jpeg)
![File 4](https://user-images.githubusercontent.com/400698/143792933-090a0fd1-2ec9-441a-bf44-4fe87e7cd4e0.jpeg)
:

**Comment by J-Human** [comment]
**Try** going to system preferences, turn on reduce transparency in the accessibility area. That will most likely remove the shimmering, but will not completely remove the bug away from your model.

**Comment by drogerswxm** [comment]
Reducing transparency improves this issue on a iMac 11,1 with a ATI Radeon HD 4850 512 MB but causes other issues with the top menu and in app menus, would be nice to fix it but its not a bit issue to live with.

**Comment by khashabawy** [comment]
> Reducing transparency improves this issue on a iMac 11,1 with a ATI Radeon HD 4850 512 MB but causes other issues with the top menu and in app menus, would be nice to fix it but its not a big issue to live with.

It did not solve the problem at all not even a small effect 😭

**Comment by khashabawy** [comment]
> **Try** [^1] going to system preferences, turn on reduce transparency in the accessibility area. That will most likely remove the shimmering, but will not completely remove the bug away from your model.
> 
> 
> 
> [^1]: This *was* the fix for me, on a MBP 8,1. 

It did not solve the problem at all not even a small effect 😭

**Comment by Plagg06** [comment]
> **Try** [1](#user-content-fn-1-be788d2e8f7baf6547c7320e5dff02cc) going to system preferences, turn on reduce transparency in the accessibility area. That will most likely remove the shimmering, but will not completely remove the bug away from your model.
> 
> ## Footnotes
> 1. This _was_ the fix for me, on a MBP 8,1. [↩](#user-content-fnref-1-be788d2e8f7baf6547c7320e5dff02cc)

This worked on MacBookAir4,2 (mid 2011 13 inch)

**Comment by Plagg06** [comment]
It would be nice though to be able to fix this without losing the Beaty of the menus. If anyone finds a fix or script or patch for this please post here. :)

**Comment by khronokernel** [comment]
Duplicate: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by khashabawy** [comment]
> Duplicate: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

No it is not duplicate , intel hd 3000 is not mentioned in the cosmetics list !!
