### ISSUE TITLE
MBP 5,2 mDP does not connect to External Display with apdpmod=vit9696

### ISSUE THREAD

**Issue by gsshiva** [dortania/OpenCore-Legacy-Patcher#765]
### Machine Model

MacBook5,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

With OCLP 0.3.1 and with Big Sur  I observe the following

-  On MBP 5,2 connecting the Mini Display Port with a mDP->DP cable to two different monitors does not output any signal. 
- On MBP 4,1 connecting a DVI cable does not output any signal.

Reading similar issues reported, I changed the **agdpmod** to _vit9696_ in both **boot-args** and **DeviceProperty**.  Here is the XML fragments from config.plist
`
            <key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
            <dict>
                <key>boot-args</key>
                <string>keepsyms=1 debug=0x100 agdpmod=vit9696</string>
                <key>csr-active-config</key>
                <data>
                AwoAAA==
                </data>
                <key>run-efi-updater</key>
                <string>No</string>
            </dict>
`

`
 <key>DeviceProperties</key>
    <dict>
        <key>Add</key>
        <dict>
            <key>PciRoot(0x0)/Pci(0x8,0x0)</key>
            <dict>
                <key>apple-layout-id</key>
                <integer>90</integer>
                <key>use-apple-layout-id</key>
                <integer>1</integer>
                <key>use-layout-id</key>
                <integer>1</integer>
            </dict>
            <key>PciRoot(0x0)/Pci(0xc,0x0)/Pci(0x0,0x0)</key>
            <dict>
                <key>agdpmod</key>
                <string>vit9696</string>
            </dict>
        </dict>
        <key>Delete</key>
        <dict/>
    </dict>
`

I did not install any Post-Install patches, since the MBP 5,2 has NVIDIA GeForce 9600M GT and MBP 4,1 has the NVIDIA GeForce 8600M GT, which based on the documentation does not require any post install patches.

**Comment by khronokernel** [comment]
> I did not install any Post-Install patches, since the MBP 5,2 has NVIDIA GeForce 9600M GT and MBP 4,1 has the NVIDIA GeForce 8600M GT, which based on the documentation does not require any post install patches.

Where did you read this? Because it's false, you need GPU acceleration for multi display support and Nvidia Tesla cards haven't been natively supported since High Sierra

**Comment by gsshiva** [comment]
It was my ignorance about the NVIDIA graphics cards and somehow thought what was in MBP 4,1 and 5,2 are not Tesla cards. I should have googled. I am applying the post install patch now. Thanks for the quick response.

**Comment by gsshiva** [comment]
The external display works after the post-install patches. Thanks again.
