### ISSUE TITLE
Icons not loading after root patch on various applications

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#767]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

On macOS 12.0.1, after patching the root volume quite a few icons are missing. I did not experience this in macOS Big Sur, (11.2.3), only in 12.0.1. Apparently, #343 is marked as a duplicate of #108, but I do not see the issue there. The problem is that on System Preferences, when you go into a section (lets say screen time) none of the icons load. The model patched was iMac11,3 and application is TUI (Offline) 0.3.1

Thanks.

**Comment by educovas** [comment]
That's a known issue since Big Sur.
Issue is not present on #108. I'll be updating the cosmetic issues list.
