### ISSUE TITLE
Monterey volume icon resetting to High Sierra icon

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#768]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen, Other/Non-Applicable

### What is the Issue?

I installed macOS Monterey on my iMac11,3 using OpenCore Legacy Patcher 0.3.1 TUI (offline). Everything went fine through the installation process. After I rebooted Monterey (after installing GPU accel patches), as usual the bootable disk changes from "Monterey HD" to "Monterey HD - Data". So far the icon is still fine. On reboot after that, I boot into OpenCore EFI, and the Monterey disk's volume icon is replaced with the High Sierra icon. I have 2 partitions on my drive, HS and Monterey, which is probably related to the issue.

**Comment by khronokernel** [comment]
High Sierra corrupts Big Sur and Monterey preboot entries, it's an Apple bug that won't ever be solved as High Sierra is long past it supported life cycle. Simply never boot High Sierra with Big Sur/Monterey installed. This was been a known issue with breaking SecureBoot manifest files destroying signature integrity

**Comment by Thyssenkrupp234** [comment]
I see. Thanks for the info. I probably will still boot High Sierra because it is my backup OS, does this issue only occur if you boot High Sierra with the OC picker? If so, can I replace the Monterey icon with my own Monterey icon? Thanks.
