### ISSUE TITLE
Bluetooth not working on macOS Monterey 12.0.1 - I think it worked on Sur

### ISSUE THREAD

**Issue by Plagg06** [dortania/OpenCore-Legacy-Patcher#769]
### Machine Model

MacBookAir4,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

When I boot WiFi works normally but bluetooth is not working as in macOS detects its there but it won't turn on from System Preferences or from the control center. Here's an image of the system preferences:
![Screen Shot 2021-11-30 at 10 06 20 AM](https://user-images.githubusercontent.com/90144944/144009037-1aa7f050-4d28-433e-a4a6-13c46494aa68.png)

**Comment by khronokernel** [comment]
> Have you verified whether this issue has been opened before? If no, your issue will be closed
> true
