### ISSUE TITLE
macOS Monterey does not recognize other APFS Partitions - as a result I cannot boot into my other macOS'

### ISSUE THREAD

**Issue by Plagg06** [dortania/OpenCore-Legacy-Patcher#770]
### Machine Model

MacBookAir4,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in), Other/Non-Applicable

### What is the Issue?

Open core Legacy patcher doesn't show OS' from other partitions i.e. I have linux mint on the first partition, and macOS High Sierra and macOS Mojave on the third partition, and macOS Monterey on the second partition. But macOS Monterey doesn't even recognize the third APFS partition containing macOS High Sierra and Mojave. See it recognizes the linux partition but it doesn't show in boot menu and it doesn't even recognize the third APFS one. And it doesn't show in System Preferences/Startup Disk. I also tried not using the OCLP by booting from a usb and holding the option key which made It use the old boot menu (the white one) but that one showed the macOS Monterey but it couldn't boot it (expected) and It showed windows which said missing OS (expected), but it didn't show macOS High Sierra and Mojave or Linux mint.. Please help I need all my OS' would erasing the macOS Monterey partition and installing a fresh install of macOS High Sierra fix the boot menu? as shown here:https://dortania.github.io/OpenCore-Legacy-Patcher/UNINSTALL.html
Look at the picture from System Preferences:
![Screen Shot 2021-11-30 at 10 47 38 AM](https://user-images.githubusercontent.com/90144944/144014859-27e7a98f-c080-49a1-bebc-4fa36cd414c4.png)
Look at the picture from terminal diskutil list:
![Screen Shot 2021-11-30 at 10 41 55 AM](https://user-images.githubusercontent.com/90144944/144014306-452beaa9-6036-4428-97d2-443c0c64191e.png)

**Comment by khronokernel** [comment]
macOS bug, we don't mess APFS containers. Additionally ask supported start up volumes are correctly displayed on our test systems
