### ISSUE TITLE
Can't open JPG images with either dimension larger than 256 pixels

### ISSUE THREAD

**Issue by ringbuffer** [dortania/OpenCore-Legacy-Patcher#771]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 10.14, Mojave

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I created two partitions on my internal drive and have maintained Mojave on one partition and installed Big Sur on the other using OpenCore Legacy Patcher. I can boot into either OS but Mojave has a weird problem with JPG images.

More specifically, it seems that JPG images with either dimension larger than 256 pixels can't be opened by any of the following native means:
- Preview.app — Preview app locks up and "Force Quit" is required
- Preview pane in finder — gets stuck on a [throbber icon](https://en.wikipedia.org/wiki/Throbber)
- Quick Look in Finder (pressing space bar to preview an image) — gets stuck on a throbber icon

Other file types (PNG, MP4, ALAC, PDF, TXT, etc.) — and small JPG images! — all seem to work fine still using Quick Look; other image types (e.g., PNG) open fine with Preview.app. All JPG images open fine with 3rd party apps. This problem does not occur in Big Sur.

I've come up with an inelegant workaround which is to delete OpenCore from the internal drive's EFI partition. I can still boot into Big Sur by using the USB installer with OpenCore installed on its EFI partition.

I've tried various combinations of Patcher Settings attempting to fix this but none seem to have had any effect on this issue. The combinations I've tried include all permutations of:
- SIP and SBM enabled/disabled
- "Set TeraScale 2 Accel" enabled/disabled

### Any Additional Information

I am running on the following hardware:
- Macbook Pro 10,1 (Retina, 15-inch, early 2013)
- 2.7 GHz Intel Core i7
- 16 GB RAM
- Intel HD Graphics 4000 1536 MB (integrated)
- NVIDIA GeForce GT 650M (PCIe)

**Comment by khronokernel** [comment]
> This problem does not occur in Big Sur.

So there is no issue for us to resolve? Mojave is natively supported on MacBookPro10,1, while we work on Big Sur and Monterey support for unsupported machines.

Please use forums for troubleshooting

**Comment by Ausdauersportler** [comment]
The more elegant workaround is to reset the PRAM on boot, press alt/option and boot directly into Mojave using he standard EFI boot picker without using OpenCore.
This way you can keep OpenCore installed on the internal drive's EFI partition. It is the way to manage supported and unsupported macOS version in parallel.

**Comment by ringbuffer** [comment]
@khronokernel — my point is that having OpenCore Legacy Patcher on the EFI partition breaks Mojave. I understand that Mojave is natively supported on MacBookPro10,1 but the fact that this software breaks a natively supported config seems like a bug or side effect you would at least want to be aware of.

@Ausdauersportler — thanks for the suggestion. I'll do it this way.

**Comment by parrotgeek1** [comment]
@khronokernel This appears to be caused by an interaction between the SMBIOS and hardware JPEG acceleration. There is/was a kext called NoVPAJpeg to disable it. https://www.insanelymac.com/forum/topic/334881-how-to-fix-quicklook-and-preview-loading-issues-in-mojave/page/7/?tab=comments#comment-2637905

Also WEG is also able to disable it according to this post https://www.tonymacx86.com/threads/jpg-preview-with-no-igpu.290092/ but the instructions are likely very outdated.
