### ISSUE TITLE
iMac13,2 (late 2012 iMac) does not install

### ISSUE THREAD

**Issue by delcomp** [dortania/OpenCore-Legacy-Patcher#773]
### Machine Model

iMac13,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

iMac13,1 (late 2012 iMac) after booting and selecting 'Install macOS Monterey' I get the message 'This copy  of the install macOS Monterey application is damaged, and can't be used to install macOS'. I build the install USB first on the iMac itself, with this result. Then I redid the whole procedure on my recent Mac mini. Same result. Something I'm missing here? The 2012 iMac has been upgraded with an 480GB SSD and 8TB HDD and has a newer Wifi/Bluetooth module to support handoff. Note that the mouse (bluetooth) does not work in the installer, seems like the new WiFi/Bluetooth card is not found.Please clearly explain the issue

**Comment by Ausdauersportler** [comment]
Use another USB device or download again until you get an undamaged installer. 

Install OpenCore to your internal EFI and try booting into it. You should be able to use mouse and keyboard on the OC boot picker.

**Comment by delcomp** [comment]
Used a different USB drive. Redid the whole thing on my Mac mini using one of the mini's direct USB3 ports.
It now stops earlier. I get the white Apple logo, then the status bar. When the bar is about half way the screen changes, Apple log is swapped for a white circle with diagonal bar and a link is shown: support.apple.com/mac/startup
Only option then is power off.
Any advice on what's next?

This morning this iMac was happily running Big Sur, installed with Patched Sur. Now this partition does not boot anymore, I guess the OpenCore install changed the SMBIOS settings. This I might get solved by reinstalling Patched Sur, but then again, I used the USB Drive of that install, will need to build that again. Anyhow, want to install Monterey.

**Comment by Ausdauersportler** [comment]
Please use Discord to discuss those problems This here is the developers platform to keep track of software issues.
