### ISSUE TITLE
External monitor not working

### ISSUE THREAD

**Issue by stevesupremacy** [dortania/OpenCore-Legacy-Patcher#774]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

After installing monterey from catalina using opencore same procedure my external monitor just stopped working and there are no available patches when i try to use post install patching. i dont know how to edit config.plist or where it is either as im a newbie so this is very frustrating. please help

**Comment by nathanb0** [comment]
I have had issues when i have upgraded macOS's. What I do is add a 2nd partition and then clean install the new macOS there then attempt migration from the previous macOS or crippled macOS upgrade. many time migration partly works but better than nothing

**Comment by khronokernel** [comment]
This was already resolved in mainline

**Comment by stevesupremacy** [comment]
> This was already resolved in mainline

Mainline?

**Comment by nathanb0** [comment]
There are many issues, this is not an issue. I resolve issues by holding down the powerbutton and rebooting. I am used to running my macbook this way. Thank you for creating this Opencore patcher!!



Nathan Berg
+61244435833


Please consider the environment before printing my email!

     On Saturday, 22 January 2022, 13:14:36 GMT+11, stevesupremacy ***@***.***> wrote:  
 
 



This was already resolved in mainline


Mainline?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
