### ISSUE TITLE
Windows External Display Not Working Through EFI Installation Tutorial

### ISSUE THREAD

**Issue by abago26** [dortania/OpenCore-Legacy-Patcher#776]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

When trying to use a MiniDisplay Port adapter with my Macbook Pro running the latest copy of Windows 10, I was unable to duplicate nor extend my screen onto the monitor. I have tried different adapters, cables, and monitors but to no success. I am not sure if it is something related to OpenCore or the Windows Installation with the Intel HD 4000 graphics drivers.

**Comment by khronokernel** [comment]
Our project focuses on macOS support, recommend troubleshooting on forums with regards to display output support in UEFI mode
