### ISSUE TITLE
Logic Pro X doesn't show the cursor

### ISSUE THREAD

**Issue by AlvaroAlvarodeAlvaro** [dortania/OpenCore-Legacy-Patcher#778]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

No way to see the cursor in factory Logic Pro X, and other minor issues with graphics (the "back" gesture with two fingers on trackpad has stopped working, either in this 12.1 iMac and 7.1 MacBook Pro
Besides, when I try to open Garage Band, machine says "can't load graphics", so the app doesn't even open
I've tested first with Big Sur and then Monterey, and impossible.
The rest is perfectly ok with Monterey on my old iMac, THANKS FOR THE GREAT JOB

**Comment by khronokernel** [comment]
Use non-Metal builds of these applications or upgrade the GPU in your IMac to a Metal capable model
