### ISSUE TITLE
Incorrect Disk Partition Name When Booting

### ISSUE THREAD

**Issue by owenzhao** [dortania/OpenCore-Legacy-Patcher#779]
### Machine Model

iMac15,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I have an internal SSD and external SSD. The internal was named "iMacHD" and the external was named "12.0.1". I used CCC fully backup (bootable) iMacHD to 12.0.1. So when I booted my Mac, a menu showed:

![IMG_0015](https://user-images.githubusercontent.com/2182896/145233603-3e5007d6-eace-43f1-98bd-c1b38b263c29.JPG)

However, after I choose "EFI Boot", the next menu I saw the "12.0.1" was changed to "iMacHD" with a USB device icon. I think this was incorrect. It should still be named "12.0.1".

![IMG_0016](https://user-images.githubusercontent.com/2182896/145233931-c84ac74a-d720-4574-9f81-80bd7db7d02d.JPG)

**Comment by khronokernel** [comment]
Are you certain the disk labels are correct in that drive's preboot? You can check with the commands I list at the end.

However rendering issues such as this one would need to filed with OpenCorePkg if it's incorrectly reading the disk label as this is what our back end uses:

* https://github.com/acidanthera/OpenCorePkg

```
# Find your Preboot volume
diskutil list

# From the below list, look for the reboot associated with the external drive
/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +255.7 GB   disk5
                                 Physical Store disk4s2
   1:                APFS Volume ⁨Big Sur HD - Data⁩       122.5 GB   disk5s1
   2:                APFS Volume ⁨Preboot⁩                 309.4 MB   disk5s2
   3:                APFS Volume ⁨Recovery⁩                887.8 MB   disk5s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk5s4
   5:                APFS Volume ⁨Big Sur HD⁩              16.2 GB    disk5s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 16.2 GB    disk5s5s
# Mount the Preboot volume
diskutil mount disk5s2

# CD into your Preboot volume
cd /System/Volumes/Preboot

# List all UUIDs
ls
 46923F6E-968E-46E9-AC6D-9E6141DF52FD
 CD844C38-1A25-48D5-9388-5D62AA46CFB8

# Check volume name listed for each entry
cat ./46923F6E-968E-46E9-AC6D-9E6141DF52FD/System/Library/CoreServices/.disk_label.contentDetails
 Big Sur HD%

cat ./CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices/.disk_label.contentDetails
 Catalina HD%
```

**Comment by owenzhao** [comment]
Thank you for your reply. I just tested and the disk label was "iMacHD". However, I believe this it will be better to use disk name instead of disk label here.

<img width="906" alt="截屏2021-12-10 下午1 14 39" src="https://user-images.githubusercontent.com/2182896/145522437-2f6a0655-8eaa-4980-aa2c-82e59a25d2aa.png">

As you can see clearly, what I called incorrect names, one was disk name, the other was disk label. When a Mac boots, and a user hold Option key to force a booting list, OCL Patcher will should "EFI Boot" allow with all bootable partitions. 

As this time, I found that if a disk had already been connected, the disk label was shown. However, if we connect another usb disk, what would be shown was the disk name. So both disk name are disk label were use by OCL Patcher.

I preferred to keep on use disk name instead of disk label. Because disk label were easily duplicated. For example, when I backed up my system with CCC, the destination disk would be label the same, though the disk name was different. So if I have multiple backups, I could not choose them from the disk label. But I could identify them by disk name.
