### ISSUE TITLE
Long boot time due card reader?

### ISSUE THREAD

**Issue by moritzj29** [dortania/OpenCore-Legacy-Patcher#780]
### Machine Model

MacBookAir6,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I'm actually not sure if this is an issue or normal behavior. I see prolonged boot times after installing open core and macOS Monterey, somewhere around 5min. Native on BigSur the boot times were around 1min. (never really measured)

I enabled verbose logging and I saw that a lot of time passed (>30s) during the last two lines of this picture, relating to the memory card reader.
![IMG_8476](https://user-images.githubusercontent.com/18733473/145346098-25717a18-076b-49ac-ac5c-574f938bfb64.jpg)
Just to clarify, there is no SD card mounted (similar issue with SD card present #673 )

Some more time is spent on doing boot tasks afterwards, but I guess this is normal.
On a MacBook5,1 booting is faster, even though it is much older and lacking an SSD.

I'm happy for all your thoughts and efforts you put in this project! I'm especially dazzled by how fast the iMac 5K issue got resolved, this going to be the next one to be upgraded to Monterey

**Comment by khronokernel** [comment]
Unfortunately this SDXC Reader bug is a Monterey bug affecting native Macs as well, though I have only seen reports with PCIe based card readers like those in MacBook Pros and iMacs. Unfortunate that your USB based reader is affected as I believe no Macs Apple currently supports in Monterey uses one.

MacBookAir6,x was the last USB based reader as MacBookAir7,x switched over to PCIe as well.

Not much we can do on our end as this is a legitimate bug. We can re-evaluate in the future if/when Apple resolves PCIe support and USB readers remain broken

**Comment by moritzj29** [comment]
Thanks for your explanation! I can live with it, now that I know it’s really a bug. I don‘t reboot that much anyway 😆

**Comment by parrotgeek1** [comment]
> MacBookAir6,x was the last USB based reader as MacBookAir7,x switched over to PCIe as well.

It appears that at least 7,2 didn't: 
https://linux-hardware.org/index.php?id=usb:05ac-8406

Therefore, this is an Apple bug and should be reported on a 7,2 if it can be reproduced there.
