### ISSUE TITLE
iMac 14,3: unable to modify brightness, disable/enable nightshift and launch screensaver after 2 nights (+ crash later on)

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#782]
### Machine Model

iMac14,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Hello,
I have several problems with OCLP (0.2.5) and macOS Big Sur (latest version) on an iMac 14,3 (with NVIDIA graphics card). Note that I tested with the last version available to date (0.3.1) and the problem is even worse (see part 2).
Note that hibernatemode is set to 0.
All the time, 2 days after restarting the Mac (so after 2 nights in standby) I encounter the following problems:
1. It is impossible to change the brightness with the keyboard keys (or there is a delay of several seconds and the automatic change is very jerky)
2. It is impossible to change the state of nightshift (if it was activated the second night, it will be impossible to deactivate it the next day and vice versa)
3. The system preferences "Monitors" are not responding.
4. I use the "Aerial" screensaver and when it starts, nothing is displayed (only a black screen)

A last bug much more annoying happens sometimes after a few days (and almost systematically with OCLP 0.3.1):
- Either the Mac doesn't wake up from sleep (the colored wheel turns endlessly)
- Or the system crashes little by little (when you wake up the Mac from sleep all the icons in the menu bar have disappeared, then it becomes impossible to open applications and even the dialog box to shut down the Mac, so a forced reboot is mandatory)

It seems to me that I didn't have this problem under macOS 11.4 or 11.5 (but I didn't stay long with these versions, so it's maybe just a coincidence).

I am at your disposal to provide all the necessary diagnostic files to identify and potentially correct this problem, because I have checked and I have not seen any report. 

Thank you very much for all your work

**Comment by khronokernel** [comment]
Unfortunately this sounds like a hardware failure if this happens in Big Sur, as we do not touch the graphics stack at all in Big Sur for iMac14,x. Additionally none of our developers have experienced this, so difficult for us to research.

I would recommend returning to Catalina and extensively test there to ensure no strange oddities there. Otherwise you'd be best to troubleshooting on forums
