### ISSUE TITLE
Hard to Choose Booting Disk with Disk Labels

### ISSUE THREAD

**Issue by owenzhao** [dortania/OpenCore-Legacy-Patcher#784]
### Machine Model

iMac15,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I backed up my Mac with CCC. To secure my data, I had multiple backups. Say I had one inner SSD and one external SSD and one external hard disk. When booting from backups, it was hard to choose which one was the one I wanted to boot.

![IMG_0017](https://user-images.githubusercontent.com/2182896/145528423-461cd494-28c9-4ae8-b4b4-bc3b3a752fec.JPG)

As you can see, both external disks were shown as  "iMacHD" with the same icon.

However, when in previous menu, the disks were shown as names, which were easy to identify.

![IMG_0018](https://user-images.githubusercontent.com/2182896/145528682-457cd46c-e794-42b2-8ebe-2a77386d6b9a.JPG)

So it is better to always use disk name instead.

**Comment by khronokernel** [comment]
Please re-read my message:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/779#issuecomment-990101470

File issue against OpenCorePkg

**Comment by owenzhao** [comment]
> Please re-read my message:
> 
> * [Incorrect Disk Partition Name When Booting #779 (comment)](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/779#issuecomment-990101470)
> 
> File issue against OpenCorePkg

I had already read your reply and tested in my own. Then I carefully filed this as another bug. The reason I chose to file this issue here was that clearly using disk labels here were not wrong, but inappropriate. Both disk names and disk labels could be use here. But using disk names were more suitable. So for me, I thought it was better to choose disk name instead of disk labels. And this could be done with OpenCore Legacy Patcher, instead of OpenCorePkg. That was my opinion.
