### ISSUE TITLE
Login issue after patching with 0.3.1

### ISSUE THREAD

**Issue by cloud9rocks** [dortania/OpenCore-Legacy-Patcher#785]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After patching Big Sur on Early 2011 15inch MacBook Pro, I am not able to login. The screen turns black for few seconds and I can see couple of lines of code and then the login page appears again.  
I used the latest 0.3.1 open core legacy patch.

### Any Additional Information

Once I reinstalled Big Sur and used 0.2.4 the issue went away. Now i can login without any issue.

Question. Can I apply the newer patch. if so which patch version would you recommend?

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#cannot-login-on-2011-15-and-17-macbook-pros
