### ISSUE TITLE
Lilu      dev: @ failed to obtain model information, retrying...

### ISSUE THREAD

**Issue by biho1** [dortania/OpenCore-Legacy-Patcher#787]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Boot sometimes hangs on Apple logo with bar at 30%, mostly when doing a cold boot.

When boot args -v ist set, this error message appears on some boots and loops forever

Lilu      dev: @ failed to obtain model information, retrying...

I replaces the OCLP 0.3.1 Lilu.kext 1.5.6 with the latest 1.5.8 and it seems to work now

Monterey 12.0.1

### Any Additional Information

Tested Systems
iMac12,2 (i7 2600, 16GB, SATA SSD, Nvidia GTX860M GPU)
iMac12,2 (i5 2400, 8GB, SATA HDD, Nvidia GTX860M GPU)
iMac13,1 (i5 3335S, 8GB RAM, SATA SSD, GT640M) all stock except SSD

**Comment by khronokernel** [comment]
You'd be best to file against Lilu as we're not the maintainers of that extension:
* https://github.com/acidanthera/Lilu

**Comment by PaulSke** [comment]
biho1 how did you make the changes in OCLP I too am having the same issue.

**Comment by biho1** [comment]
> biho1 how did you make the changes in OCLP I too am having the same issue.
mount the OCLP EFI partition and the copy the newer liliu.kext 1.5.8 in the EFI/OC/KEXT folder

**Comment by PaulSke** [comment]
Might you be able to direct me on how to mount that partition? Thanks for any info you may have.

**Comment by PaulSke** [comment]
Found it, thank you. Did you need to perform a complete reinstall of MacOS Monterey with the updated EFI or can I just use a drive with an updated boot loader?

**Comment by biho1** [comment]
> Found it, thank you. Did you need to perform a complete reinstall of MacOS Monterey with the updated EFI or can I just use a drive with an updated boot loader?

just replace the file

**Comment by PaulSke** [comment]
Thanks, Ill give this a try!

**Comment by PaulSke** [comment]
That was it, thanks again for all your help. Could not have done it without it.

**Comment by maximedupre** [comment]
Having the same issue with iMac9,1 after following this tutorial https://www.youtube.com/watch?v=go6RTCHv4GA

@biho1 @PaulSke 

Is it possible to provide a little bit more info on how to

> mount the OCLP EFI partition and then copy the newer liliu.kext 1.5.8 in the EFI/OC/KEXT folder

?

My iMac was just printing "Lilu dev: @ failed to obtain model information, retrying..." over and over again, and now I shut it down.

Thanks 😊

**Comment by PaulSke** [comment]
I can layer this evening. Which version of OCLP are you using. I see they updated it to 1.5.8 in the 3.3. But I still had intermittent issues using that version

**Comment by maximedupre** [comment]
Thanks @PaulSke 🙏

The tutorial suggests using the "OpenCore Legacy Patcher 0.3.1 TUI". I'll try again with v3.3 in the meantime and see if I have any success 💪

**Comment by biho1** [comment]
yes, the latest version of OCLP 0.3.3 has lilu.kext 1.5.8, so it should
work out of the box

greetings Thomas

Maxime Dupré ***@***.***> schrieb am Di. 21. Dez. 2021 um
22:53:

**Comment by maximedupre** [comment]
@PaulSke @biho1 

Thanks to both of you 😊 

0.3.3 works well 💪

**Comment by whenmusicattacks** [comment]
same issue every other boot on oclp 0.4.2
