### ISSUE TITLE
MacPro3,1 unable to start after post install patch

### ISSUE THREAD

**Issue by tonybernardo** [dortania/OpenCore-Legacy-Patcher#788]
### Machine Model

MacPro3,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

After applying post install patches, machine no longer boots. On startup goes straight to Recovery. 

Machine was previously booting from HDD. Multiple attempts to install post install patches have same result. 

Machine running a 680 graphics card

**Comment by tonybernardo** [comment]
I should say that on initial startup the machine hard resets and then loads recovery

**Comment by khronokernel** [comment]
Disable SecureBootModel in patcher settings, Reset NVRAM and boot again. This should resolve the recoveryOS loop
