### ISSUE TITLE
Add more support for Macbook4,1

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#789]
### Machine Model

MacBook4,1

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

With the current version of OCLP, it claims to support the Macbook4,1. It does, although it is quite complicated. For example, the latest version that I am running on my macbook right now is 10.7.5 and the OCLP GUI and TUI both do not work. I have not tested the CLI. It also notes that there is no GPU acceleration in 10.9 or newer. So, if one is reading this correctly, if I want GPU acceleration on a newer version of OSX, the highest I can go is 10.8 but w/ no trackpad, no USB and no keyboard? I got this from #126 but he used the RMC to upgrade to Mojave then to Big Sur. In that case, if GPU acceleration was to be worked on, (if that is even possible seeing as the 965 Intel Express chipset is x64 running on x86 drivers), then are Keyboard and mouse actually supported by OpenCore? I would be willing to tr this by building the OC EFI on my iMac11,3 running Monterey patched, and then attempting to boot off of a Mojave or newer install disk. This is sort of just clarification of support, and if this issue stays open I'll do some testing soon. Thanks.

**Comment by Thyssenkrupp234** [comment]
I would also like to note I am running windows 11 64-bit on the machine, (bypassing CPU, TPM and SecureBoot) and it runs a little slow because of the Penryn, but otherwise usable.

**Comment by khronokernel** [comment]
Unfortunately GPU acceleration on GMA series chips is currently out of scope and has very little interest due to the age and affected hardware. 

Feel free to develop patch sets yourself and PR them upstream however as it stands we can't dedicate to such a strenuous task as GPU acceleration for chips that have been unsupported software wise for almost a decade. However you'd be best to discuss on forums about further development

**Comment by Thyssenkrupp234** [comment]
I see. I am not capable at all of creating patch sets, and I see now. Yeah, GMA is an old series. Thanks for your time in the reply.
