### ISSUE TITLE
Stuck at Apple Logo and Progress Bar with mouse after OpenCore boot.

### ISSUE THREAD

**Issue by millzanz** [dortania/OpenCore-Legacy-Patcher#790]
### Machine Model

MacBook5,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I am able to boot to the installer and install Bir Sur on the machine (MacBookAir5,2) it then boots to the Apple Logo with a progress bar; the mouse will flash in the top left corner and then disappear then the progress bar will move a little and will stay like this. 

System will sleep and when woken mouse is able to be seen and moved around, the apple logo with the bar is still there.

I have tried a fresh install and a upgrade from Catalina.  

Any other ideas as how to fix this?

**Comment by khronokernel** [comment]
We don't touch graphics stack in Big Sur for HD4000, recommend troubleshooting on forums
