### ISSUE TITLE
OCLP TUI "is damaged and can’t be opened. You should move it to the Bin"

### ISSUE THREAD

**Issue by Rogier-Ams** [dortania/OpenCore-Legacy-Patcher#791]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I tried OCLP on my patched big sur install (Macmini6,2) but got the dreaded "is damaged and can’t be opened. You should move it to the Bin" error when opening OCLP TUI.

Patched Monterey installer USB from my M1 Machine (where OCLP TUI ran fine) for Macmini6,2. Repartitioned and erased the Mini entirely, did a clean install of Monterey 12.0.1 from the OCLP patched installer USB.

Afterwards, when trying to patch the Mini itself, again got the "is damaged and can’t be opened. You should move it to the Bin" error, no matter how often I redownload a clean .zip from github.

Please advise!

### Any Additional Information

None

**Comment by khronokernel** [comment]
Binaries provided with releases are fine on our test systems, closing as local issue. Use forums for troubleshooting
