### ISSUE TITLE
Swapped @ key

### ISSUE THREAD

**Issue by ElreboCM** [dortania/OpenCore-Legacy-Patcher#793]
### Machine Model

iMac15,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I have installed Monterey 12.01 on my iMac 15,1 using the 15,1 Public Beta2 build from khronokernel.
For some reason the @ key gets swapped on the keyboard (QWERTZ Layout) from alt+l to alt + q.
Instead of the @ sign I am getting a weird character that has a yellow background (see screenshot) 
No other sign seems to be affected. This behaviour is independent from the application the character is typed to.
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/4703830/145772680-fae798e6-25e7-43d7-8185-7cb118d1d3de.png">

**Comment by khronokernel** [comment]
Unable to replicate, likely just a Monterey bug. Test other keyboards and ensure the right keyboard profile is selected in settings. Recommend troubleshooting further on forums
