### ISSUE TITLE
MacbookPro 13,3 getting stuck after login

### ISSUE THREAD

**Issue by ElreboCM** [dortania/OpenCore-Legacy-Patcher#794]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I am trying to use OpenCore - Legacy Patcher for enabling airplay to Mac support on my MacbookPro13,3.
I have set OpenCore to allow native Monterey devices and not to use the picker.
OpenCore is installed on an USB drive.
When booting I get to the login screen.
After entering my password a loading bar shows.
After about 1/3 I getting stuck with  a black screen with an url from apple related to the startup.

**Comment by ElreboCM** [comment]
I have just tested the nightly build. Unfortunately the problems is also there.

**Comment by khronokernel** [comment]
Can you boot the system in verbose as well as upload the Build Folder generated with the TUI?

**Comment by ElreboCM** [comment]
Ok no problem. See photo of last messages from verbose mode and build folder attached.
[OpenCore-Build.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7705139/OpenCore-Build.zip)
![IMG_2429](https://user-images.githubusercontent.com/4703830/145846363-a094bf9d-124a-472c-9456-6a15edd5f29b.jpeg)

**Comment by khronokernel** [comment]
Is this a stock SSD in this machine? Additionally can you upload an IOReg from macOS (without OpenCore):

* https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip
  * File -> SaveAs

**Comment by khronokernel** [comment]
So found the issue, for some reason on 2016-2017 MacBook Pros Apple used off the shelf NVMe drives which report themselves as generic in macOS. However for some reason Apple never blessed them to be used with AppleNVMeController class thus triggering our code to enable enhanced power management.

Affected ID was `pci144D,a804` which would coincide with [Samsung's SM961/PM961/SM963](https://devicehunt.com/view/type/pci/vendor/144D/device/A804). Added an extra device check to OCLP to avoid patching on this controller.
