### ISSUE TITLE
Installation stuck at “less than a minute remaining”

### ISSUE THREAD

**Issue by lilkem** [dortania/OpenCore-Legacy-Patcher#795]
### Machine Model

iMac9,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

When I try to install Big Sur 11.6 on my iMac, it goes to the Apple logo where it gets stuck at less than a minute remaining. I tried to restart the computer and boot from the efi boot then clicking on my hard drive but the progress bar only goes like less than halfway through very slowly before it gets stuck. I hope there’s an easy fix. Thanks!

**Comment by Ausdauersportler** [comment]
This famous last minute can take up to two hours depending on your CPU type. 

Please use Discord or the Macrumors forum to troubleshoot your installation, not this tool which is meant to keep track of software issues, not user issues.
