### ISSUE TITLE
Wifi and Bluetooth issues after changing to BCM943602CDP

### ISSUE THREAD

**Issue by wladkolc** [dortania/OpenCore-Legacy-Patcher#796]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After wireless card replacement i am seeing devices detected in system information. But wifi is switching on/off and bluetooth not work (Bluetooth information not found). When i have installed Windows, it works OK.

Here are photos from these tabs:
![IMG-1127](https://user-images.githubusercontent.com/34405761/145833934-a2d5018a-0df7-43c3-8abe-57a0070424af.jpg)
![IMG-1126](https://user-images.githubusercontent.com/34405761/145833976-3d5b9c13-5487-4c19-a6a4-f8d292e501c6.jpg)

**Comment by khronokernel** [comment]
USB 1.1 controller is unstable with Big Sur and newer, plug the Bluetooth controller into a USB 2.0/3.0 hub to force the USB2.0 controller on the MacPro on for bluetooth. Use forums for further troubleshooting
