### ISSUE TITLE
iMac15,1 Display recognized as 18-inch (7680 x 4320) Built-in Retina display.

### ISSUE THREAD

**Issue by qoli** [dortania/OpenCore-Legacy-Patcher#797]
### Machine Model

iMac15,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

I has read 5k issues(https://github.com/dortania/OpenCore-Legacy-Patcher/issues/359). 
And tried to use the latest OpenCore Build.

macOS recognizes the primary display as 18-inch and provides 8k resolution.
but Display info is right in System report.

![Screen Shot 2021-12-14 at 1 35 33 AM](https://user-images.githubusercontent.com/2818670/145863183-3c35b1fd-1cbc-4c29-a1fd-db7daf657649.jpeg)

### Any Additional Information

System report: 
[iMac.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7705857/iMac.zip)

**Comment by khronokernel** [comment]
That's some strange local issue, OCLP can't even set custom resolutions like that. I assume you've installed some display profiles or transferred over. Recommend resetting NVRAM and verify whether booting Big Sur through OpenCore can replicate this issue as that will indicate whether your local installation is broken or OpenCore is still having issues

Here's the latest build (ensure you're logged in, and Reset NVRAM):

* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/4642225025/artifacts/125866165

**Comment by qoli** [comment]
I follow this comment (https://github.com/dortania/OpenCore-Legacy-Patcher/issues/283#issuecomment-872647687) and remove all EIF files is ok now.

---
