### ISSUE TITLE
Mac OS Monterey 12.1 Delta Update

### ISSUE THREAD

**Issue by sdahlmann** [dortania/OpenCore-Legacy-Patcher#798]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

When I want to update mac OS Monterey from version 12.0.1 to 12.1, I don't see the update in MAC OS "Software Update" with Open Legacy Patcher 0.32 installed. With version 0.31 it was still displayed. On MAC mini 6.2 (late 2012) before the MAC OS update, I updated the patcher to 0.32 and then did the following: 1. Build Open Core, 2. Install OpenCore to USB Internat drive (on internal Samsung SSD 500GB), 3. Reboot MAC, 4. Post-Install Volume Patch. 5. Reboot MAC. After that, MAC OS 12.1 will not be displayed to install. Is there possibly. a problem with the patcher? Can you give me a tip? Many thanks.

**Comment by khronokernel** [comment]
As stated on 0.3.2 release, we’re using the VMM system. If OTA break, then Apple supported virtual machines break as well
Switch to minimal or wait for Apple to resolve

**Comment by sdahlmann** [comment]
Whats you mean with switch to minimal? Is this downgrad the patcher to Version 0.31? Can you explan this. Man thanks.

**Comment by khronokernel** [comment]
As stated in the release, to return to a 0.3.1-like configuration you'd need to set a Minimal level SMBIOS spoof in the TUI's Patcher Settings
