### ISSUE TITLE
WiFi broken after update to Monterey 12.1 final from 12.0.1, using OLP 0.3.1

### ISSUE THREAD

**Issue by juanejot** [dortania/OpenCore-Legacy-Patcher#799]
### Machine Model

MacBookPro5,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

While your guide says the WiFi issue has been resolved, it appears to be back for 12.1 final; the WiFi menu says it’s on, but it sees no networks. Typing in an SSID/password combination says that network is not available.

### Any Additional Information

I also happen to have a couple of Ubuntu-based Linux installations on this laptop, and though they need bcmwl-kernel-source installed to deal with such an old Broadcom chipset, they have continued to work from before the macOS 12.1 installation through after; not a hardware issue.

**Comment by khronokernel** [comment]
Please run this:
```
cat /private/etc/SkyLightPlugins/List.txt
```

What's the output?

**Comment by juanejot** [comment]
Hmm. “`No such file or directory`;” I see only `etc`, `tftpboot`, `tmp` & `var` inside `private`, and none of them have a `SkylightPlugins` directory.
`sudo find / -name SkyLightPlugins` yields nothing either. Sorry; anywhere else to look?

**Comment by khronokernel** [comment]
Oh I see why, you're using 0.3.1. The wifi fix is in 0.3.2

**Comment by juanejot** [comment]
Aha! Hadn’t tried nightlies yet. Will try that, close this issue if successful.

**Comment by juanejot** [comment]
Follow-up: It was indeed that I hadn't seen the 0.3.2 release yet; an entire home network of computers somehow refused to refresh your releases page until *after* our little discussion above. Sorry!

Anyway, it's working as expected (as I write this from it on the WiFi), including the return of GPU rendering I hadn't gotten around to commenting hadn't been there either, yet. Thank you! Off to tweak some stuff to retrieve bootability for my Linux partitions…
