### ISSUE TITLE
Can not run Patcher 0.0.4

### ISSUE THREAD

**Issue by TheMac6ine** [dortania/Opencore-Legacy-Patcher#8]
Hello, 

I tried the new Version of the patcher, but I can not run the OpenCore-Patcher.command. I get a failure that the Opencore-Legacy-Patcher-0.0.4 is corrupted. With 0.0.3 it works. 

Regards

**Comment by porcherie** [comment]
same for 0.0.5. 
The funny thing 0.0.3 works fine...

**Comment by khronokernel** [comment]
When you say corrupted, who's reporting it? macOS's gatekeeper or terminal?

If macOS, try right clicking and opening the file. Should give you a prompt to trust

Not entirely sure why 0.0.3 doesn't have this issue

**Comment by porcherie** [comment]
it's gatekeeper 99%, right click has no effect...I tried with xattr -cr /path to file...but did not work...too lazy to disable SIP.
Before it worked, I'm sure it can be fixed

**Comment by fant0mac** [comment]
Here is a screenshot of what happens (guess it is the same for all 3 of us)
<img width="574" alt="Screenshot 2020-12-04 at 22 08 30" src="https://user-images.githubusercontent.com/75504167/101215188-ac08c580-367d-11eb-9004-b9e858e521fd.png">

**Comment by khronokernel** [comment]
What happens if you cd into the folder and run `python OpenCore-Patcher.command`?

**Comment by khronokernel** [comment]
Able to replicate on my machine if I download it from Github, very odd...

**Comment by porcherie** [comment]
> What happens if you cd into the folder and run `python OpenCore-Patcher.command`?

It's working!! Cool! Thanks

**Comment by khronokernel** [comment]
Great to hear, but I have no clue why it's failing with the .command...

Maybe I should just ship a Docker container of my environment /s

Will need to look into this further

**Comment by fant0mac** [comment]
just wanted to post the same error as porcherie, at the exact same step

**Comment by porcherie** [comment]
I get the error but it creates anyway a build-folder...could someone check if there's everything inside and could be used anyway??
<img width="331" alt="Screenshot 2020-12-04 at 22 31 25" src="https://user-images.githubusercontent.com/50797800/101216870-921cb200-3680-11eb-93f8-92c901c1ec03.png">

**Comment by khronokernel** [comment]
<img width="780" alt="Screen Shot 2020-12-04 at 2 46 05 PM" src="https://user-images.githubusercontent.com/48863253/101217953-76dd8280-363f-11eb-925a-e2e64b64e163.png">

Under System Preferences -> Security and Privacy -> Privacy, enable Terminal as a Developer tool

**Comment by khronokernel** [comment]
<img width="1092" alt="Screen Shot 2020-12-04 at 4 00 53 PM" src="https://user-images.githubusercontent.com/48863253/101223818-24559380-364a-11eb-8afb-8e623ed68202.png">

Tested in VMware on a clean image, working good on my end with latest from master. Zero changes to user preferences besides right click + ok

**Comment by khronokernel** [comment]
So downloading from master works, downloading a release does not...

Reopening till resolved

**Comment by fant0mac** [comment]
Downloading from main worked for me, I could build and install OpenCore on my installer usb.
Thanks!

**Comment by porcherie** [comment]
> <img alt="Screen Shot 2020-12-04 at 2 46 05 PM" width="780" src="https://user-images.githubusercontent.com/48863253/101217953-76dd8280-363f-11eb-925a-e2e64b64e163.png">
> 
> Under System Preferences -> Security and Privacy -> Privacy, enable Terminal as a Developer tool

do I need to be a dev to get that "developer tool" tab? Or how can I get it enabled??

**Comment by porcherie** [comment]
I just enabled terminal in dev tools, the installation worked fine finally, but the at boot I still have the message that this Mac is not compatible. I'm on 0.0.7 and a MacBook Pro 10.2 with upgraded wireless card

**Comment by jaybanger1** [comment]
Sir, the “not compatible” message usually means your not booting from the efi volume. You must boot from EFI and use “the picker” to select the installer or your installation.

**Comment by porcherie** [comment]
> Sir, the “not compatible” message usually means your not booting from the efi volume. You must boot from EFI and use “the picker” to select the installer or your installation.
> […](#)
> Sent from my iPhone
> On Dec 5, 2020, at 3:00 AM, porcherie ***@***.***> wrote: ﻿ I just enabled terminal in dev tools, the installation worked fine finally, but the at boot I still have the message that this Mac is not compatible. I'm on 0.0.7 and a MacBook Pro 10.2 with upgraded wireless card — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This is what I am doing, but unfortunately is not working

**Comment by jaybanger1** [comment]
When you hold down your option key, then choose efi, what options do you have in the picker?

**Comment by porcherie** [comment]
> When you hold down your option key, then choose efi, what options do you have in the picker?
> […](#)

Macintosh hd, install Big Sur & efi

**Comment by fant0mac** [comment]
@porcherie please choose EFI and see what happens next. You should see another menu - depending on where you are in the installation process, you need to boot from the external installer drive or from the internal drive.

My experience with the OpenCore patcher:
_<The following happened in the middle of the night, so the description below might miss some details or the exact order of the events>_
I got Big Sur running on my 2012 rMBP 15" (10.1) using the OpenCore patcher 0.07 (despite Ted's mum's saying: "Nothing good happens after 2 a.m.").

However, at one point during the actual installation of Big Sur, a reboot resulted in an error related to a security violation (not sure 100%, but I think the error message was like in the screenshot below).
![image](https://user-images.githubusercontent.com/75504167/101262376-8394d000-373e-11eb-8427-65a79511a693.png)

IIRC, another reboot let me finish the installation, but in the end I came across the "This Version of MacOS is not supported on this platform". The Mac shut down and after booting again into the EFI, I chose the Macintosh HD and then Big Sur properly started. 

I liked very much that the GPU switching works with running displaypolicyd. I'd really like to understand what makes this work compared to when using the micropatcher, where having displaypolicyd running will always cause the dGPU to start working (might be "Dual GPU patch" mentioned in the changelog)... 

One negative thing I couldn't get rid of though was that my USB3 ports only ever agreed on speeds "up to 480 MBit/s" regardless of what I connected (e.g. external SSDs which used to go with 5 GBit/s). That started working again, when I used the micropatcher's EFI boot to change the NVRAM of the Macbook, but I lost the automatic GPU switching when displaypolicyd is running 🙄 

The second part of this post might be somehow off topic to the issue at hand, sorry about that - let me know if I should better move it somewhere.

**Comment by porcherie** [comment]
> @porcherie please choose EFI and see what happens next. You should see another menu - depending on where you are in the installation process, you need to boot from the external installer drive or from the internal drive.

This what I tried to do many times, but always same result!🙃 I'm gonna wait few more release and try again
