### ISSUE TITLE
0.3.2 can't update ota or recovery monterey 12.1

### ISSUE THREAD

**Issue by Meteo07** [dortania/OpenCore-Legacy-Patcher#801]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hi impossible to update macos monterey to 12.1 after update opencore 0.31 to 0.3.2, "can't install on this disk" and error hachage appear after boot monterey 12.0.1, back to 0.3.1 all is ok, i installed 12.1 succesfully .

sorry if my english is not perfect, i'm french.

best regards.

**Comment by jawadhadi** [comment]
I think it's related to "Note 2" mentioned in release notes of 0.3.2. You need to set spoof level to Minimal or higher. You can customize this using TUI under `Patcher Settings -> SMBIOS Settings -> Set SMBIOS Spoof Level`

> Note 2: macOS 12.1 may not show up initially, this is an Apple bug affecting virtual machines. Either wait for Apple to resolve, or set spoof level to Minimal or higher

**Comment by Meteo07** [comment]
thanks i'll test it, and i have a big probleme with 0.3.1 and 0.3.2: hashes mismatch in volume disk1s5 and crash windowserver  on monterey 12.1, i think i'll downgrade to big sur...

**Comment by jawadhadi** [comment]
I have same "MacBookPro11,1" model as you, and also same issues. I downgraded back to Big Sur, but with 12.1 release I was thinking to give it another try...

**Comment by jawadhadi** [comment]
> thanks i'll test it, and i have a big probleme with 0.3.1 and 0.3.2: hashes mismatch in volume disk1s5 and crash windowserver on monterey 12.1, i think i'll downgrade to big sur...

I have same "MacBookPro11,1" model as you, and also same issues. I downgraded back to Big Sur, but with 12.1 release I was thinking to give it another try...

**Comment by arnaudpladys** [comment]
Same here. I was running 12.0.1 on a late 2013 15" mbp with no issue, tried to perform an OTA update to 12.1, rebooted several times, and now it is stuck on loading after entering password. I've tried re-applying update from a freshly made usb key patched with opencore 0.3.2, still, no success. I cannot boot into macOS. I am basically stuck and think about going back to bigsur if this is a mess like this every time there is an update.

**Comment by Meteo07** [comment]
it seams to be work for me on macbnook air 2014, and macbook pro 2014 : Patcher Settings -> SMBIOS Settings -> Set SMBIOS Spoof Level set it to "minimal" 

reboot, reset nvram and smc, reboot with alt and select uefi... launch silentknight and be sure all is green (i must to updated mrt to 1.85) for the moment, it seams to be ok, wait and see...

**Comment by arnaudpladys** [comment]
Dang.. reset smc/nvram, bam it booted, repatch with 0.3.2 leaving spoof to zero, it works like a charm! 
God damit, all of this for a reset :P !

**Comment by jawadhadi** [comment]
@arnaudpladys are you also facing issues like hash mismatch etc.?

**Comment by Meteo07** [comment]
don't work with macbook air but seams to be ok on macbook pro ....

**Comment by arnaudpladys** [comment]
> @arnaudpladys are you also facing issues like hash mismatch etc.?

What do you mean by that?

**Comment by arnaudpladys** [comment]
> > > @arnaudpladys are you also facing issues like hash mismatch etc.?
> > 
> > 
> > What do you mean by that?
> 
> have you seen an error like this? followed by MacBook slowing down? ![volume-hash-mismatch-error-macos-monterey](https://user-images.githubusercontent.com/2013749/146013965-77c4f149-7b8f-4b83-8346-c19e10fac773.jpg)

Nop, never see something like this.

**Comment by khronokernel** [comment]
Please use forums for troubleshooting, not issues tabs

**Comment by zqyr** [comment]
> Dang.. reset smc/nvram, bam it booted, repatch with 0.3.2 leaving spoof to zero, it works like a charm!
> God damit, all of this for a reset :P !

Is that with MacBook Air?
