### ISSUE TITLE
Wrong SMBIOS Spoof Level default value?

### ISSUE THREAD

**Issue by VKondakoff** [dortania/OpenCore-Legacy-Patcher#802]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

SMBIOS Spoof Level is set to 'None' by default, while the on-screen instructions are telling us the default value is 'Minimal'.
<img width="568" alt="Снимок экрана 2021-12-14 в 14 17 02" src="https://user-images.githubusercontent.com/230824/145993973-fbdd98ca-caa4-43d2-a5d6-92209dd3b995.png">

Here is the default value:
<img width="568" alt="Снимок экрана 2021-12-14 в 14 16 49" src="https://user-images.githubusercontent.com/230824/145994017-0d9ca54a-88c8-46ad-9186-668fdefb1158.png">

What SMBIOS Spoof Level value should I use for iMac 15,1?
Thanks!

**Comment by Ausdauersportler** [comment]
Default method will be selected depending on your hardware. All system with a Polaris/Ellesmere/Vega GPU will use moderate spoofing as before (was the default choice for all systems with OCLP 0.3.1 and older), all other systems will use now the new spoof-less approach (just check the change log of OCLP before loading it).

Normally there is no need to enter this menu and select a value manually. Let the OCLP tool decide.
