### ISSUE TITLE
0.3.2 iMac 15,1 5K failed using TUI, but worked using GUI

### ISSUE THREAD

**Issue by michaeldam** [dortania/OpenCore-Legacy-Patcher#804]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

From 0.3.2 5K resolution support is integrated into the regular builds. I upgraded from 0.3.1. I ran the TUI tool overwriting the EFI, shut down my machine; restarted my machine and verified its resolution. it was still 4K (3840x2180) in 'about my mac'. I repeated the process, same result.
I downloaded the 0.3.2 GUI version. I ran it and shut down. I restarted and the resolution in 'about my Mac' now is at 5K: 5120 x 2880. This is absolutely awesome btw, great work.

**Comment by khronokernel** [comment]
Unrelated to the GUI and TUI, you simply just booted again wiping the existing OC entry from NVRAM but forcefully selecting a new OpenCore entry

0.3.1 forces it's OpenCore.efi entry into NVRAM, while 0.3.2 forces the digs.efi loader into NVRAM. Simply holding option and selecting OpenCore is enough to fix this

Will update release page regarding this

**Comment by michaeldam** [comment]
Odd that rebooting did not make any difference when using the TUI. Twice.
But after using the GUI a reboot did work.
To make sure I'm understood: I rebooted 3 times. Only the third time and after I used the GUI the I have 5K.
