### ISSUE TITLE
OTA updates completely gone after updating to OCLP 0.32

### ISSUE THREAD

**Issue by samplenull** [dortania/OpenCore-Legacy-Patcher#805]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I've tried to update from 11.6 to 12.1. After installing new version of OCLP Software update showing only application updates (like Safari or XCode CL tools). 
I tried to get macOS Monterey From AppStore page, getting error "The requested version of macOS is not available.".

Everything else seems to be working fine as usual. I used all the default settings when build OCLP.

**Comment by khronokernel** [comment]
Read release notes and look at previously filed issues

**Comment by samplenull** [comment]
I couldn't find this issue, i guess I need to use installAssistant manually...
