### ISSUE TITLE
GTX 770 Not working in MacPro3,1 Monterey

### ISSUE THREAD

**Issue by fritzchentastig** [dortania/OpenCore-Legacy-Patcher#806]
### Machine Model

MacPro3,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I have a Graphics Card an Nvidia GTX 770 it does not show the boot loader the boot or macOS, I am getting no Output at all. I wanted to install macOS and then root volume patch it but when I did get no graphics that's hardly possible. 

Am I doing something wrong or is it an issue with OCLP?

**Comment by khronokernel** [comment]
Please use forums for troubleshooting
