### ISSUE TITLE
No OTA updates for 15.1 iMac

### ISSUE THREAD

**Issue by mth75** [dortania/OpenCore-Legacy-Patcher#807]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

My Mac OS 12.0.1 install doesn't show updates (the update for 12.1) under Software update. With the Terminal app "software-update" it is clear that my OpenCore install somehow doesn't report or rather identifies the machine version to the Apple update service.

**Comment by khronokernel** [comment]
Read previously filed issues as well as 0.3.2 release notes

**Comment by mth75** [comment]
I did and I can't find the similar issue?
