### ISSUE TITLE
MacBook Pro fans running throughout 

### ISSUE THREAD

**Issue by Keith-tech1** [dortania/OpenCore-Legacy-Patcher#808]
### Machine Model

MacBook7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

Hi, I have a MacBook Pro mid 2010 I installed Monterey but my Mac fans start running at full speed from startup. Also when the fans run at full speed even when I just have one tab of safari browser.

**Comment by khronokernel** [comment]
You installed a brand new OS, many background processes will still be running thus hammering the CPU. Please use forums for further discussions

**Comment by Keith-tech1** [comment]
It has been like that for 3 weeks now

**Comment by Keith-tech1** [comment]
I have been having that issue for 3 weeks now
