### ISSUE TITLE
Clean install on Monterey 12.1 using 0.3.3 Wifi will not connect

### ISSUE THREAD

**Issue by GSteddin** [dortania/OpenCore-Legacy-Patcher#811]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I really tried to search for the answer to this because I am sure it must be here somewhere, but I can't find it.

I used the TUI of 0.3.3 to create a fresh 12.1 Monterey USB and installed onto a fresh drive.  Boots beautifully except it will not connect to Wifi, with finding the network, or selecting it via "Other"

**Comment by khronokernel** [comment]
Stock wireless module shipped with MacPro5,1, namely BCM94322, require root volume patches with macOS Monterey.

Either run the post install patches or upgrade the module to a BCM94331, BCM943224, BCM94360 or BCM943602 for more native-like experience with OpenCore Legacy Patcher

**Comment by GSteddin** [comment]
That was iT!

You are amazing!!!!

**Comment by tomillo** [comment]
I have the same issue but my card is BCM43xx. My wifi connections shows after Root patching, but it don't connect. Any suggestions?
