### ISSUE TITLE
Upgrade to Monterey 12.1, MBP 11.3 wont boot further with OCLP 0.3.1/2/3 after switch to Apple Logo (but with shift-key boot to safe mode is possible)

### ISSUE THREAD

**Issue by greenflute** [dortania/OpenCore-Legacy-Patcher#812]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

After Upgrade to Monterey 12.1, MBP 11.3 wont boot further with OCLP 0.3.1/2/3 after switch to Apple Logo.

Both OpenCore Debug and Kext Debug are activated, some minor errors were spotted but it goes further until switched to apple logo, but progress bar is frozen at the beginning (non highlight pixel in the bar), after several seconds the fans are going to laud for several seconds then go silent again. Then nothing happens.

If with alt-key at boot and then with shift-key at picker screen, boot to safe mode is possible. Install OCLP to boot disk under safe mode keeps reporting error, it was done by taking the nvme disk out and plugge in another mac using usb-case, and the correct mac-model, nvme-boot are selected.

**Comment by khronokernel** [comment]
Kepler requires post install patches in Monterey:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/522

**Comment by greenflute** [comment]
> Kepler requires post install patches in Monterey:
> 
> * [MacBookPro11,3 GMUX issues with 12.0 Beta 7 and newer #522](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/522)

Super, Thanks, as last resort just tried to patch system in safe mode, exactly it says about legacy nvidia driver, now it boots normally, really appreciate your link :) and great work of OCLP
