### ISSUE TITLE
Menu Bar becomes invisible with Reduce Transparency on

### ISSUE THREAD

**Issue by elmimmo** [dortania/OpenCore-Legacy-Patcher#815]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Checking System Prefences > Accessibility > Display > Reduce Transparency and rebooting makes the Menu Bar and menu commands invisible (menu extras do remain in place).

### Any Additional Information

OpenCore Legacy Patcher v0.3.3 TUI
iMac12,2
macOS Big Sur 11.6.1 (20G224)

**Comment by charly-black** [comment]
Same issue here on mac book pro 13" early 2011 with Intel HD3000

**Comment by educovas** [comment]
Known bug, this bug has been fixed on Monterey but is still broken on Big Sur

**Comment by khronokernel** [comment]
Updated issue for tracking:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
