### ISSUE TITLE
Airplay 2 not working although "Airplay Receiver" activated in "Sharing setting"

### ISSUE THREAD

**Issue by Surf2bikes** [dortania/OpenCore-Legacy-Patcher#816]
### Machine Model

iMac11,3

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I can see the feature in the settings under "sharing"- "Airplay receiver" is now added. However when I activate it, nothing happens. 

### Any Additional Information

Imac 27, late 2010. OPLC 3.2 and MACOS Monterey 12.1. GPU Nvidia Quadro K2100M by Nick[D]vB 2 GB

**Comment by Ausdauersportler** [comment]
According to this page:
https://github.com/acidanthera/FeatureUnlock
AirPlay to Mac does not have such limitation and can work **on H.264 dGPU**s. 

Your system does not have such a dGPU. You need a AMD Polaris dGPU to get it working.

**Comment by Surf2bikes** [comment]
ok - thank you! I was not aware of this requirement. BTW: Do you know issues with same feature and IMAC 14.3? "Airplay Receiver" does not show in "sharing settings".

**Comment by Thyssenkrupp234** [comment]
@Ausdauersportler, would this be valid for my model as well? I have a iMac11,3 with an `ATI Radeon 5750 1024mb`, intel core i7 870 and a 2TB HDD. But it is not AMD Polaris, so I guess not, right? Thanks for any confirmation.

**Comment by Monkiey** [comment]
> ok - thank you! I was not aware of this requirement. BTW: Do you know issues with same feature and IMAC 14.3? "Airplay Receiver" does not show in "sharing settings".
issue mentioned here #783

**Comment by khronokernel** [comment]
If AirPlay to Mac is broken on this machine, I believe this issue would be far deeper and the Kepler GPU would be at fault. Assuming Apple broke Kepler encode/decode even more, little we can do at this moment besides test macOS 12.0.1.

As I have no Kepler hardware locally (my Mac Pro's dead), there's little we can do at this time. However feel free to research further and provide patch sets, we greatly appreciate any extra help we can get.

And as Ausdauersportler suggested, you'd be best to invest in either a newer AMD Polaris GPU or newer Mac if this functionality is required from the machine
