### ISSUE TITLE
11.6.2 installation does not complete

### ISSUE THREAD

**Issue by RobertoCMCosta** [dortania/OpenCore-Legacy-Patcher#817]
Hi, 
Thank you for the answer. 
I upgraded to 0.3.3 and after resetting pram and rebooting, software update found both macOS 12.1 and 11.6.2. However, installing 11.6.2 doesn't work, I mean, I've tried twice, it downloads, proceeds to installation, reboots and continues in 11.6.1.
Any clue? Could it be related to SIP and secure boot disabled? 
Should I download the full installer and update from an external drive?

_Originally posted by @RobertoCMCosta in https://github.com/dortania/OpenCore-Legacy-Patcher/issues/813#issuecomment-995828311_

**Comment by RobertoCMCosta** [comment]
I decided to download the full installer and updated from 11.6.1 to 11.6.2. 
It only took a very long time to finish after 3 or 4 reboots. Sometimes it seemed to installation had hung but it made to the end. 
11.6.2 working fine here, no need to apply post-install patches. 
My system: iMac 11,2 with Nvidia K1100m

**Comment by khronokernel** [comment]
Without proper logs, etc, you'd be best to troubleshoot on forums
