### ISSUE TITLE
MacBookPro11,3 can not install postinstall when booted into safe mode.

### ISSUE THREAD

**Issue by satmandu** [dortania/OpenCore-Legacy-Patcher#819]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I can only boot into macOS 12.1 using safe mode, perhaps due to a hardware issue.  I'm trying to enable the nvidia graphics using post-install, but I cannot do the postinstall because it cannot mount the snapshot from safe mode.  Is there another way?

```
- Binaries downloaded to:
/private/tmp/_MEIbxRmUl/payloads
- Found Root Volume at: disk1s2
- Mounting APFS Snapshot as writable
mount: /System/Volumes/Update/mnt1: invalid file system.
- Failed to mount the Root Volume
- Recommend rebooting the machine and trying to patch again
- Press [ENTER] to exit:
-
```

**Comment by khronokernel** [comment]
> I can only boot into macOS 12.1 using safe mode, perhaps due to a hardware issue. 

This is documented here:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/522

```
- Mounting APFS Snapshot as writable
mount: /System/Volumes/Update/mnt1: invalid file system.
```

This issue would be derived from macOS and not us, as our root volume mounter is based on the same logic as Apple's Kernel Development Kit. You can either attempt to reboot a few times hoping the mount point fixes itself or brute force and reinstall macOS. However you'd be best to troubleshoot further on forums as there's nothing we can do on our end unfortunately.

**Comment by satmandu** [comment]
I was able to resolve this by rebooting again without safe mode, but this time I was able to connect using ssh and install the post-install, which is now working.
