### ISSUE TITLE
missing symbol _CGDisplayRegisterReconfigurationCallback after post-install patches

### ISSUE THREAD

**Issue by GabrielTellez** [dortania/OpenCore-Legacy-Patcher#820]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Fresh installed Monterey 12.1 on a Mac Pro 5,1 with opencore-legacy-patcher 0.33 and post install patches. Installed dropbox but it crashes. When I run it from the command line there is an error: 
```
File "Quartz/CoreGraphics/__init__.pyc", line 55, in _load
File "<_bootstrap_overrides>", line 153, in load_module
ImportError: dlopen(/Applications/Dropbox.app/Contents/Frameworks/python-extensions/Quartz.CoreGraphics._callbacks.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_CGDisplayRegisterReconfigurationCallback'
```

But if the post-install patches are not installed there is no problem and dropbox runs smoothly.

**Comment by Thyssenkrupp234** [comment]
Weird. I wonder if Dropbox somehow relies on the metal back-end. Looks like something to do with Python and this link: https://developer.apple.com/documentation/coregraphics

A little blurb: `Harness the power of Quartz technology to perform lightweight 2D rendering with high-fidelity output. Handle path-based drawing, antialiased rendering, gradients, images, color management, PDF documents, and more.`

**Comment by Thyssenkrupp234** [comment]
Yeah, looks like a python framework requesting Quartz-Coregraphics. Maybe the patches don't support that, not sure. @khronokernel could probably provide more information.

**Comment by khronokernel** [comment]
Moved here for tracking, unlikely to be resolved soon:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

Seeing as you have a Mac Pro with PCIe slots, you'd be best to upgrade to a natively supported Metal GPU

**Comment by maximedupre** [comment]
@khronokernel 

I have an iMac 9,1 with Monterey 12.1 and Dropbox simply won't open. I'm not sure if this is the same issue - I tried opening Dropbox from the command line like OP, but nothing (no output):

```
maxime@imac ~ % open /Applications/Dropbox.app 
maxime@imac ~ % 
```

Should I create a new ticket, or should I provide more info/logs? 

Thank you 😊

**Comment by Thyssenkrupp234** [comment]
hey, @maximedupre, since Mykola is not responding to some issues atm, I will assume he is on vacation or busy, so I will try to answer your question.

First of all, what GPU did you run the patches on? If you have not upgraded to a metal GPU, then there are going to be some problems. Since khronokernel added the similar issue with dropbox, maybe @khronokernel could change it to be with dropbox in general

Until a solution is found, either don't use dropbox or use the online version. I have my iMac11,3 on root TeraScale 2 patches, will update post when tested

**Comment by maximedupre** [comment]
Hey @Thyssenkrupp234, thanks for the reply :)

> First of all, what GPU did you run the patches on? If you have not upgraded to a metal GPU, then there are going to be some problems.

I have no idea 😶 Can you please help me answer this question? Where would I have to look? I just opened the TUI and ran option #3.

> Maybe create a new issue, and try running the application executable itself, probably something like /Applications/Dropbox.app/Contents/MacOS/executablename and see if it shows any error. Dropbox not installed locally, will install ASAP and test w/ TeraScale 2

So I just tried that, and indeed got the same error as OP:

```
maxime@imac ~ % /Applications/Dropbox.app/Contents/MacOS/Dropbox ; exit;
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/cryptography.hazmat.bindings._openssl.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/cryptography.hazmat.bindings._padding.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/objc._objc.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/CoreFoundation._inlines.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/CoreFoundation._CoreFoundation.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/Foundation._Foundation.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/Foundation._inlines.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/psutil._psutil_osx.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/psutil._psutil_posix.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/apex._apex.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/AppKit._inlines.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/AppKit._AppKit.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/FSEvents._callbacks.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/CoreServices._inlines.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/tornado.speedups.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/Quartz.CoreGraphics._inlines.cpython-38-darwin.so'
dropbox: load fq extension '/Applications/Dropbox.app/Contents/Frameworks/python-extensions/Quartz.CoreGraphics._callbacks.cpython-38-darwin.so'
Failed to run Python command:
!! dropbox: fatal python exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/main.pyc", line 54, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/app/machine_anchor.pyc", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/features/file_view_logging/file_view_logger_factory.pyc", line 21, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/features/file_view_logging/file_view_logger_mac.pyc", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/features/file_view_logging/user_file_view_logger_polaris.pyc", line 24, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/harmony/mac/activity_provider_shell.pyc", line 50, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/harmony/mac/accessibility_prompter.pyc", line 40, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/features/accessibility/helpers.pyc", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/ui/cocoa/alert_dialog/alert_dialog.pyc", line 56, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/ui/cocoa/dropbox_controls.pyc", line 113, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "dropbox/client/ui/cocoa/styles.pyc", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "Quartz/__init__.pyc", line 110, in <module>
  File "Quartz/__init__.pyc", line 28, in _load
  File "<frozen zipimport>", line 259, in load_module
  File "Quartz/CoreGraphics/__init__.pyc", line 147, in <module>
  File "Quartz/CoreGraphics/__init__.pyc", line 55, in _load
  File "<_bootstrap_overrides>", line 153, in load_module
ImportError: dlopen(/Applications/Dropbox.app/Contents/Frameworks/python-extensions/Quartz.CoreGraphics._callbacks.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_CGDisplayRegisterReconfigurationCallback'

RUST PANICKING -- "Failed to run Python command!" at "desktop/app/lib/core/bootstrap/src/python.rs":135
[584:4970:20211230,173401.277499:INFO thread_snapshot_mac.cc:243] dropbox: thread 1365 is not a python thread
[584:4970:20211230,173401.278061:INFO thread_snapshot_mac.cc:243] dropbox: thread 1366 is not a python thread
[584:4970:20211230,173401.278131:INFO thread_snapshot_mac.cc:243] dropbox: thread 1367 is not a python thread
[584:4970:20211230,173401.278200:INFO thread_snapshot_mac.cc:243] dropbox: thread 1370 is not a python thread
[584:4970:20211230,173401.278273:INFO thread_snapshot_mac.cc:243] dropbox: thread 1371 is not a python thread
[584:4970:20211230,173401.278345:INFO thread_snapshot_mac.cc:243] dropbox: thread 1375 is not a python thread
[584:4970:20211230,173401.278413:INFO thread_snapshot_mac.cc:243] dropbox: thread 13a7 is not a python thread
zsh: abort      /Applications/Dropbox.app/Contents/MacOS/Dropbox

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Is there anything I can do to make it work? @khronokernel  suggests:

> Seeing as you have a Mac Pro with PCIe slots, you'd be best to upgrade to a natively supported Metal GPU

Can I upgrade to Metal GPU? (I'm not sure what that means 😅 Any pointer would be greatly appreciated)

> Edit: did dropbox work in 12.0.1 or Big Sur? If it is a 12.1 or Monterey specific issue, it could help to know

Never tried on 12.0.1, I went straight to 12.1.0.

**Comment by Thyssenkrupp234** [comment]
Awesome! Looks like you are running a TeraScale 1 GPU, (mine is a TeraScale 2). Basically, apple dropped OpenGL and developed their own firmware known as `metal`. Mojave+ requires a metal GPU, because apple dropped support for old OpenGL based GPUs. With a metal GPU, (i think) you do not need any root patches, and will natively support Mojave+ operating systems. If you are not comfortable with upgrading the GPU, then either wait for the issue to be fixed, try downgrading to macOS Big Sur, or just don't use dropbox and use the online version. Since you have an iMac, [here](https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/) is a guide to upgrading the GPU to metal compatible GPU.

Side note: you need your iMac to be atleast late 2009 to have this work. Good luck!

Cheers!

**Comment by maximedupre** [comment]
Thanks again for the reply @Thyssenkrupp234 and great explanation 👌

> Side note: you need your iMac to be atleast late 2009 to have this work. Good luck!

I have an iMac9,1 (Early 2009), does that mean I will not be able to upgrade to metal?

Am I right then, to think that those are my only options:
* wait for the issue to be fixed on non metal
* downgrade to 12.0.1 (maybe?)
* downgrade to Big Sur

?

Cheers!

**Comment by Thyssenkrupp234** [comment]
Hey! Thanks for that comment, @maximedupre :)

You will not be able to upgrade your GPU via that guide, there is probably another forum thread on upgrading on an early 2009, but with a quick search I couldn't find it. In the case you cannot, then the possible solution in the legacy acceleration issue, ([here](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108)) is to downgrade to 12.0.1.
