### ISSUE TITLE
Unable to patch system volume with GUI after 12.1 update

### ISSUE THREAD

**Issue by b4bass** [dortania/OpenCore-Legacy-Patcher#821]
### Machine Model

MacBookAir5,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

On my MBA 5,2, after updating to 12.1, I was unable to patch my system volume using the 0.3.3 GUI.

The GUI seems to be stuck just after clicking the patch system volume icon. I entered my password succesfully, then, in the new window, I get no text.

Fixed using the text based version.

**Comment by khronokernel** [comment]
Cannot replicate locally, did you kill the GUI too early? OCLP-CLI (which the GUI calls) needs to prepare itself to run so can add a 5 second delay (or more on super slow machines)

Unfortunate byproduct of PyInstaller based applications
