### ISSUE TITLE
Unstable USB connection with iOS Devices

### ISSUE THREAD

**Issue by jz5020** [dortania/OpenCore-Legacy-Patcher#823]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Sometimes after plugging in either my iPad or my iPhone, the USB connection between my Macbook and my iDevice keeps disconnecting and reconnecting roughly every 2 seconds or so. I've had instances where this has only occurred on one USB port before and I have also had the issue with both USB ports at the same time too. I have tried with many different USB cables, several different iDevices, and other USB devices to test the functionality so I have concluded that it would be a software issue as it only occurs after login. Upon following a few online guides, I have found that killing usbd using a terminal has worked and if not, then a device restart works to solve this issue, but I have just experienced this issue too many times on both macOS 12.0 and 12.1 using OCLP. I have a feeling that it could have to do with the charging current or something since on my iPad, the green charging symbol keeps flashing when this bug occurs, but when it is working normally, it just reads "not charging".

**Comment by Grandboy46** [comment]
This is a general issue with macOS not just Monterey. I had the same issue in macOS Mojave without any patchers. Try downgrading back to macOS Mojave and see if you still have the issue. If you do, this is definitely not an issue related to OCLP.

**Comment by khronokernel** [comment]
We do not touch the USB stack on MacBookPro11,x, and it has the same USB Controller as a natively supported MacBookPro11,5. As Grandly mentioned, likely macOS issue

**Comment by Surf2bikes** [comment]
I have the same issue with imac14,3 Monterey 12.1 and IPad IOS 15.2
