### ISSUE TITLE
No Powersaving after Update to MacOs 12.1

### ISSUE THREAD

**Issue by harrykl** [dortania/OpenCore-Legacy-Patcher#824]
### Machine Model

MacBookAir5,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After Update to Monterey 12.1 from 12.0 my Mac do not activate the powersaving if I close the Macbook. In 12.0 everthing worked fine. I installed the Update as OTA-Update

**Comment by GentMAB** [comment]
Did you setup the Spoof Level after updating and did you use the newest OpenCore Patcher? I know with my iMac12,1 it was not going to sleep until I updated the spoof level, then re-installed the patcher and legacy patch, now it properly turned off the display after 15 minutes like it should.

**Comment by harrykl** [comment]
I installed the OpenCore Patcher after updating again an then it works. I have to do this two times.
