### ISSUE TITLE
Discord screen share crashing on TS2 - Monterey

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#826]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

With TeraScale 2 Patches applied in macOS Monterey, everything works quite good since my last experience with Big Sur and 0.2.4. One interesting thing though, with Discord given all the permissions it needs, screen sharing starts then immediately stops/crashes the screen-sharing. I can't remember of this happened in Big Sur, but definitely does not work with Monterey. I would be happy to do any troubleshooting.

### Any Additional Information

Tech specs:

12 GB DDR3 RAM
ATI Radeon 5750 1024mb
intel core i7 870
2 TB Hitachi HDD (7200RPM)

**Comment by khronokernel** [comment]
Related to VNC issue:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
