### ISSUE TITLE
keyboard backlight is not working

### ISSUE THREAD

**Issue by armanbarsam** [dortania/OpenCore-Legacy-Patcher#827]
### Machine Model

MacBook8,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

keyboard backlight is not working. it seems bth buttons are working as backlight decreaser

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html
