### ISSUE TITLE
Using built-in trackpad, cannot scroll within a window while cursor is holding a file

### ISSUE THREAD

**Issue by soundcoderc** [dortania/OpenCore-Legacy-Patcher#828]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

- Open an app such as Finder, Photos, Notes, or Mail (affects all apps, first or third party, with grab-able items in lists).
- Using thumb to click, grab a file, photo, note, email, etc.
- While holding your thumb to grab the file, scroll with your index and middle finger. 

On a native install, the cursor holding the item(s) stays static and the surrounding content scrolls. This is so you can rearrange large folders, move photos around albums, etc.
Here is the correct behavior on MacBookPro16,1 (16" Late 2019)
https://user-images.githubusercontent.com/5464075/146714646-bdbdee6b-58b9-48e1-8a11-5a8e9580949d.mov

On the OCLP setup, the scrolling is ignored and the cursor holding the item(s) moves with your scrolling fingers. Occasionally the correct behavior will begin but then stop suddenly. This makes rearranging folders, photo albums, etc. very difficult.
Here is the broken behavior on MacBookPro11,3 (15" Late 2013)
https://user-images.githubusercontent.com/5464075/146714828-19e5a95e-ef6b-4798-b664-6e9bfd3684ed.mov

The behavior works correctly on the same machine using a Gen 1 Magic Mouse.

**Comment by khronokernel** [comment]
We already explained on Discord, this is a macOS "bug". File issue with Apple on a machine that can replicate.
