### ISSUE TITLE
Prohibition Sign during restart Mac Pro 5.1

### ISSUE THREAD

**Issue by plattenschubse** [dortania/OpenCore-Legacy-Patcher#829]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hi guys, I have successfully installed BigSur with the OCLP. However, not a single restart works. To do this, I have to turn off the computer every time. Only then does BigSur load properly. I installed OCLP on the Samsung 1TB SSD including BigSur. Does anyone know the problem?

**Comment by khronokernel** [comment]
Please use forums for troubleshooting
