### ISSUE TITLE
iMac 21.5" Late 2013 issues

### ISSUE THREAD

**Issue by family1232009** [dortania/Opencore-Legacy-Patcher#83]
Hi, I have some issues with my iMac14,1. 

1) Since OLP 0.0.11, macOS won't boot with the new PlatformInfo section
```
05:202 00:005 AAPL: ***********************************************************
05:208 00:005 AAPL: This version of Mac OS X is not supported on this platform!
05:213 00:005 AAPL: ***********************************************************
05:219 00:005 AAPL: Reason: Mac-031B6874CF7F642A
05:225 00:005 AAPL: Sleeping for 30 seconds before exiting...
```
OpenCore cannot change my BoardID (Mac-031B6874CF7F642A) to Mac-81E3E92DD6088272 for some reason.

![1](https://user-images.githubusercontent.com/44340726/110251521-a5eaf380-7fa2-11eb-9b82-5c6fc84b4960.png)

I have to change my model identifier to iMac14,4 manually as it was in OLP 0.0.10 and older, then macOS boots okay.
![2](https://user-images.githubusercontent.com/44340726/110251701-856f6900-7fa3-11eb-8a35-b0a1ecf19f75.png)

2) With enabled ThirdPartyDrives quirk my iMac has strange behavior when waking up from sleep mode (not hibernation). 
It wakes up, I see the OpenCore boot picker, then I press any key on the keyboard or the power button, and the macOS desktop appears. If I disable ThirdPartyDrives, iMac wakes up normally.

**Comment by khronokernel** [comment]
For a temporary fix to 1, when building select "Use custom serials" when it prompts instead of using original.

However, can you build a DEBUG OpenCore build and send me the logs when using original serials? It'll be generated on the root of the EFI Partition. You can find an updated build of OCLP here:

* https://github.com/dortania/Opencore-Legacy-Patcher/suites/2199098694/artifacts/45394880


For 2, we have ThirdPartDrives quirk enable regardless for some reason. Meant to add a check for legacy machines. [Fixed in main](https://github.com/dortania/Opencore-Legacy-Patcher/commit/90274eef330d1b48ff841b7c8a7335a94408d9fc)

**Comment by khronokernel** [comment]
Additionally, can you send me the current EFI that the patcher built? Wondering if there's some bug in the older version I fixed in main without realizing

**Comment by family1232009** [comment]
> Additionally, can you send me the current EFI that the patcher built? Wondering if there's some bug in the older version I fixed in main without realizing

[EFI iMac14,1.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6097854/EFI.iMac14.1.zip)

**Comment by khronokernel** [comment]
Hmm nope same SMBIOS contents as main, will definitely need the OpenCore logs to get a better idea of what's failing

**Comment by family1232009** [comment]
> Hmm nope same SMBIOS contents as main, will definitely need the OpenCore logs to get a better idea of what's failing

[opencore-2021-03-07-201233.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/6097865/opencore-2021-03-07-201233.txt)

**Comment by khronokernel** [comment]
@family1232009 Can you boot a supported OS *with* OpenCore and run [dmidecode](https://github.com/acidanthera/dmidecode/releases):

```
/path/to/dmidecode > ~/Desktop/dmidecode.txt
```

And please upload this file

**Comment by family1232009** [comment]
@khronokernel Here are the results. 

**dmidecode 1.txt** - with the "Use original serials" option (OLP 0.0.11 and newer)
![1](https://user-images.githubusercontent.com/44340726/110379180-51b24300-8078-11eb-93b5-85467da573a8.png)

**dmidecode 2.txt** - with the old PlatformInfo section (OLP 0.0.10 and older)
![2](https://user-images.githubusercontent.com/44340726/110379320-81f9e180-8078-11eb-9318-ff8e0c72517d.png)

[dmidecode 1.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/6103972/dmidecode.1.txt)
[dmidecode 2.txt](https://github.com/dortania/Opencore-Legacy-Patcher/files/6103973/dmidecode.2.txt)

**Comment by khronokernel** [comment]
> Product Name: Mac-81E3E92DD6088272

So patcher is in-fact doing it's job, successfully replaced the board ID. There must some other checks within boot.efi. Gonna go rip it and examine what else it's checking(ie. Board Chassis, etc)

**Comment by khronokernel** [comment]
@family1232009 Think we've found the culprit, seems boot.efi reads HW_BID first and *then* check the SMBIOS table. Please try the below build:

[OpenCore-RELEASE-v0.6.8.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6104680/OpenCore-RELEASE-v0.6.8.zip)

If it fixes it, will add to the patcher

**Comment by family1232009** [comment]
@khronokernel Yes, it helped. Thanks a lot :)
