### ISSUE TITLE
Restart causes write to real NVRAM 

### ISSUE THREAD

**Issue by joevt** [dortania/OpenCore-Legacy-Patcher#831]
### Machine Model

MacPro3,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I've been using OCLP for a couple weeks. It seems the NVRAM settings (DefaultBackgroundColor, boot-args, etc.) in the config.conf file don't get written to real NVRAM during normal use and that's the way I like it.

However, today while in OpenCore, I clicked the Restart button (triangle) because I didn't want to boot this time with OpenCore. And when the Mac booted, the background color was black instead of gray. Black is the default value OCLP uses for DefaultBackgroundColor but the Apple Startup Manager (hold Option at boot) for MacPro3,1 does not change the text color from black to white to accommodate the new black background color so the text of each item is invisible. Maybe black shouldn't be the default DefaultBackgroundColor for MacPro3,1 if there's no way to change the font color for the Apple Startup Manager.

Also, the boot-args got modified. In the OCLP boot-args, I have maxmem=63488, because the MacPro3,1 does not run at normal speed with 64 GB of RAM (except in Linux). https://forums.macrumors.com/threads/mac-pro-3-1-nvme-support-upgrade-guide-questions.2194878/post-28026180

The problem with maxmem=63488 in boot-args is that it won't allow 32 bit only kernels (10.4 and 10.5) to run. For those I need maxmem=32768 which I have set in the `/Volumes/*/Library/Preferences/SystemConfiguration/com.apple.Boot.plist` file but the boot-args value overrides the boot.plist file value.
 https://forums.macrumors.com/threads/mac-pro-3-1-nvme-support-upgrade-guide-questions.2194878/

OpenCore doesn't support old Mac OSs like 10.4 which is why I was trying to bypass it with the Restart button when I forgot to hold the Option key to get into the Apple Startup Manager.

Am I misinterpreting the functionality? I haven't looked at the code. Maybe OpenCore writes to real NVRAM before booting macOS, but then on shutdown writes the old values? That would cause unnecessary wear of the NVRAM chip which is not a good idea for these old Macs (nvram corruption on MacPro5,1).

**Comment by Thyssenkrupp234** [comment]
On my iMac11,3, the mac boot picker Background color does not change with booting/restarting, whereas on my early 2011 MBP, every time a disk is booted with OC/OCLP, the mac boot picker is turned black. Maybe there is a setting in OCLP to turn this to true/false? If not, that would be a good feature to add to the TUI.

**Comment by joevt** [comment]
@khronokernel  I see you added an option to set `NVRAM.WriteFlash = False`

But why is this necessary if NVRAM already doesn't change when I don't click the OpenCore restart button (my config has NVRAM.WriteFlash = True but the boot-args and DefaultBackgroundColor don't get changed if I don't click the OpenCore restart button and just continue with booting Monterey).
