### ISSUE TITLE
Apple Watch can't unlock iMac

### ISSUE THREAD

**Issue by AntonioJOrtiz64** [dortania/OpenCore-Legacy-Patcher#833]
### Machine Model

iMac14,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Apple Watch can't unlock iMac, In fact, once configured, the system waits every time it is required to be unlocked from the Apple Watch, however, the option never appears on the watch.

**Comment by khronokernel** [comment]
We do not touch the bluetooth or wireless stack on BCM94360 based systems, would be considered a macOS/Apple bug

Troubleshoot further on forums
