### ISSUE TITLE
Quicklook in finder is lagging

### ISSUE THREAD

**Issue by cukabeka** [dortania/OpenCore-Legacy-Patcher#835]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

This is related to a Late2011 MBP 8,2 with a broken GPU but working fine with the OCLP patch on the internal graphics card. 
When previewing any document (txt, pdf, xls…) in finder, the animation is lagging. After hitting the space key, it takes approx. 5s until the preview is shown, same when hitting space again to close the quicklook. 

With xls file previews I had artifacts and black areas on the screen (could not capture this as screenshot though), and the system suspended surprisingly to a black screen and non-backlit keys. when I pressed the power button, I had the same state on the display as before, which would be the equivalent to resuming the system (which is not supported for the MBP82, AFAIK). Maybe interesting for investigating on the sleep mode issue. 

I tried to fix the quicklook issue with the following methods:
-  terminal command: `defaults write -g QLPanelAnimationDuration -float 0; killall Dock`
-  **reduce transparency** in the accessibility settings
-  **reduce motion** in the accessibility settings

But still, the lagging happens.

**Comment by khronokernel** [comment]
Troubleshoot further on forums, non-Metal acceleration patches are still in development:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
