### ISSUE TITLE
MacBook Pro refuses to use preffered mirrorred screen resolution

### ISSUE THREAD

**Issue by ARTCvan** [dortania/OpenCore-Legacy-Patcher#836]
### Machine Model

MacBookPro5,4

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

When I attempt to connect an external monitor via the miniDP port (which has an adapter that converts HDMI to miniDP) on my MacBookPro5,4 it refuses to use the correct mirrorred screen resolution that I have set in System Preferences. Using other apps like SwitchResX won't help. 

I set the resolution to 1920x1080 which is the highest resolution my external monitor supports and it shows the MacBook's 1440x900 resolution on both the laptop and monitor.

I'm running macOS Big Sur 11.6, and also haven't tried other cables, since I know they worked in previous versions of macOS (OS X El Capitan, macOS Mojave and Catalina). I don't have access to other cables or adapters so that is out of the question for now.

I suspect that this might be an issue with the GPU, however I can't confirm that.

Hope you guys can help!

### Any Additional Information

Edit: The monitor is an old Dell S2209W if that helps. Also using a DVI-D to HDMI cable so that might be another issue.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
