### ISSUE TITLE
No Ethernet on MacPro4,1 (MacPro5,1)

### ISSUE THREAD

**Issue by felixalebel** [dortania/OpenCore-Legacy-Patcher#837]
### Machine Model

MacPro4,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

No Ethernet. Both ports.

### Any Additional Information

MacPro4,1 upgraded to MacPro5,1 firmware
12 core 2,66GHz, 128Gb ram. 1TB NVMe
Upgraded Wifi to Broadcom BCM943602CDP

**Comment by khronokernel** [comment]
MacPro4,1 and MacPro5,1 use an Intel 82574L NIC that is supported by Apple's Intel82574L extension located under:
```
/System/Library/Extensions/IONetworkingFamily.kext/Contents/PlugIns/Intel82574L.kext
```
The kext is still currently maintained by Apple in macOS, additionally none of our testers have issues with Networking via this NIC. Best to assume hardware state or driver issue, best to troubleshoot further on forums
