### ISSUE TITLE
Display port no longer working on NVIDIA K5000 GPU

### ISSUE THREAD

**Issue by felixalebel** [dortania/OpenCore-Legacy-Patcher#838]
### Machine Model

MacPro4,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

No output from display port on NVIDIA K5000 4Gb GPU. Only DVI working. 

### Any Additional Information

MacPro4,1  upgraded to 5,1 firmware.
12 core, 128Gb ram, 1TB NVMe

**Comment by khronokernel** [comment]
No proper logging or debug information provided, best to troubleshoot further on forums
