### ISSUE TITLE
Intermittent wifi connection MacPro4,1/5,1 (Broadcom BCM943602CDP)

### ISSUE THREAD

**Issue by felixalebel** [dortania/OpenCore-Legacy-Patcher#839]
### Machine Model

MacPro4,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Wifi internet connection will stop working after a couple hours from being turned on. Similar behavior than seen on the new M1 MBP.

### Any Additional Information

MacPro4,1 upgraded to 5,1
12 core, 128 Gb, 1TB NVMe
Broadcom BCM943602CDP
Monterey 12.1
OCLP 0.3.3

**Comment by khronokernel** [comment]
> Similar behavior than seen on the new M1 MBP.

So wouldn't this be considered an Apple bug and not OCLP? Please keep the issues tab to OCLP issues only, use forums for further troubleshooting
