### ISSUE TITLE
GUI in settings looks incomplete/ weird

### ISSUE THREAD

**Issue by asmadimd** [dortania/OpenCore-Legacy-Patcher#843]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

GUI in setting looks incomplete. Refer image tq
![IMG-20211224-WA0017](https://user-images.githubusercontent.com/43096096/147364748-73406dc9-e6b5-4190-9018-bd4ed3a8c2f1.jpg)

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by asmadimd** [comment]
Is the issue related on the icon resolution? Or just bug bcos of unsupported os?
