### ISSUE TITLE
Airdrop not showing up on Monterey 12.0.1

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#845]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After patching macOS 12.0.1 Monterey on my iMac11,3, Airdrop is not showing up in finder. My mac DOES support airdrop (Native HS installation) but does not seem to support in macOS Monterey with the patches.

Oh, and a quick question, my mac was affected where Wi-Fi w/ WPA2/WPA security methods would not prompt a password on v0.3.1, now on v0.3.3 do I need to re-install the legacy acceleration/Wi-Fi patches, or did OC automatically fix that via the EFI?

Thanks.

### Any Additional Information

Model: Vanilla iMac11,3 (no upgrades)
CPU: Intel core i7 870 (4-cores, 8 threads)
GPU: ATI Radeon 5750 1024mb
(I couldn't find much wifi info) "Wi-Fi  (0x168C, 0x8F)" and Atheros 9280: 4.0.74.0-P2P as firmware version

I think that's it.

**Comment by Thyssenkrupp234** [comment]
Update: I see airdrop controls in Control Center, but still does not show up in finder

**Comment by jz5020** [comment]
I have the same model and the I'm pretty sure the wifi card doesn't support features like airdrop and handoff in the first place.

**Comment by khronokernel** [comment]
> I have the same model and the I'm pretty sure the wifi card doesn't support features like airdrop and handoff in the first place.

This is correct, AirDrop requires Bluetooth 4.0. 

Thyssenkrupp234 - If you've upgraded the Bluetooth without upgrading wifi, this would be considered an unsupported configuration from our perspective. Upgrade to a proper native BCM94331/BCM20702 combo or newer for native AirDrop support

For further support, please use forums

**Comment by Thyssenkrupp234** [comment]
@khronokernel - thanks for all your responses so far, I have not upgraded Bluetooth, as I mentioned this iMac11,3 has absolutely no upgrades, and airdrop works fine in High Sierra. Is there a patch for airdrop support, or currently not researching? Thanks for any info. Airdrop is not a requirement for me, just curious if there is a patch. Thanks!

**Comment by Ausdauersportler** [comment]
You cannot get AirDrop on post High Sierra macOS versions without upgrades get the BT/WiFI hardware!

**Comment by Thyssenkrupp234** [comment]
@Ausdauersportler - I see. Thanks for telling me this. As I said, airdrop is not really a problem for me, so I don't really need to upgrade the BT/WIFI card.

Have a great day
