### ISSUE TITLE
From patched sur

### ISSUE THREAD

**Issue by suletetes** [dortania/OpenCore-Legacy-Patcher#846]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Please clearly explain the issue
Hello I have in installed big sur with patched sur last year and this year I want to install Monterey using open legacy core. I have red I must do clean install please help me out. I need simple explanation in detail so that I can understand. Thank you

**Comment by khronokernel** [comment]
As with the other issue, use forums please

**Comment by suletetes** [comment]
Which forum

**Comment by suletetes** [comment]
I formatted my Mac and installed monterey using opencore legacy some apps like clean my Mac x, disk drill, dash are not working.
