### ISSUE TITLE
Stuck at installation 

### ISSUE THREAD

**Issue by suletetes** [dortania/OpenCore-Legacy-Patcher#847]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Am stuck at installation I need help
![Uploading IMG_20211225_141549.jpg…]()

**Comment by suletetes** [comment]
![IMG_20211225_141549](https://user-images.githubusercontent.com/85356587/147385770-d75a2470-44ec-460d-af81-e73104eb2389.jpg)

**Comment by Ausdauersportler** [comment]
Please join Discord or Macrumors forum the trouble shoot. This is not a user help channel, this is meant to discuss and resolve software issues.
