### ISSUE TITLE
Weird artifacts on macOS Monterey

### ISSUE THREAD

**Issue by hazuan1** [dortania/OpenCore-Legacy-Patcher#848]
### Machine Model

Macmini5,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

i have this weird artifacts in menubar dropdown, left menu on finder, rightclicking anything, safari new tab
how to solve this?

https://user-images.githubusercontent.com/28352591/147398051-1b50f8d2-605f-4e92-83eb-dc63bf9965aa.mp4

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by AndreasJordanidis** [comment]
any Mac with an OpenGL GPU without Metal support, 2011 and earlier will have these artifacts till the hard working legacy acceleration team finds a solution
