### ISSUE TITLE
AFFS Bug with Monterey

### ISSUE THREAD

**Issue by csweering** [dortania/OpenCore-Legacy-Patcher#849]
### Machine Model

Macmini5,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I've got everything working okay, but the last phase of my patching is not possible, due to this error 
- Unable to create a new snapshot
Reason for snapshot failure:
Can't use last-sealed-snapshot or create-snapshot on non-system volume

- This is an APFS bug with Monterey! Perform a clean installation to ensure your APFS volume is built correctly

Because of this error, I cannot get to ride the video drive for running, and so my system reacts extremely slow! Can somebody please help me or give me some advice?

### Any Additional Information

- Loading...
- Detected arguments, switching to CLI mode
- Rerouting payloads location
- Set System Volume patching
- Starting Patch Process
- Determinging Required Patch set for Darwin 21
- Found GPU (0): 8086:126
The following patches will be applied:
![Screenshot 2021-12-27 at 14 21 17](https://user-images.githubusercontent.com/49060543/147477085-38b35d25-ba5f-413e-bcb7-6ef927b23492.png)

- Add Legacy Intel Sandy Bridge Graphics Patch
Continuing root patching
- Continuing with Patching
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Apple binaries missing
################################
# Downloading: 12-Monterey.zip #
################################

4.0MB Downloaded of 0.0MB (641330.89%)
Average Download Speed: 31.4 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

8.0MB Downloaded of 0.0MB (1282661.77%)
Average Download Speed: 33.24 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

12.0MB Downloaded of 0.0MB (1923992.66%)
Average Download Speed: 39.25 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

16.0MB Downloaded of 0.0MB (2565323.55%)
Average Download Speed: 40.67 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

20.0MB Downloaded of 0.0MB (3206654.43%)
Average Download Speed: 41.56 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

24.0MB Downloaded of 0.0MB (3847985.32%)
Average Download Speed: 42.23 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

28.0MB Downloaded of 0.0MB (4489316.21%)
Average Download Speed: 42.61 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

32.0MB Downloaded of 0.0MB (5130647.09%)
Average Download Speed: 42.94 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

36.0MB Downloaded of 0.0MB (5771977.98%)
Average Download Speed: 43.28 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

40.0MB Downloaded of 0.0MB (6413308.87%)
Average Download Speed: 43.59 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

44.0MB Downloaded of 0.0MB (7054639.76%)
Average Download Speed: 43.69 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

48.0MB Downloaded of 0.0MB (7695970.64%)
Average Download Speed: 43.93 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

52.0MB Downloaded of 0.0MB (8337301.53%)
Average Download Speed: 44.07 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

56.0MB Downloaded of 0.0MB (8978632.42%)
Average Download Speed: 44.25 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

60.0MB Downloaded of 0.0MB (9619963.3%)
Average Download Speed: 44.34 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

64.0MB Downloaded of 0.0MB (10261294.19%)
Average Download Speed: 44.35 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

68.0MB Downloaded of 0.0MB (10902625.08%)
Average Download Speed: 44.48 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

72.0MB Downloaded of 0.0MB (11543955.96%)
Average Download Speed: 44.53 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

76.0MB Downloaded of 0.0MB (12185286.85%)
Average Download Speed: 44.65 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

80.0MB Downloaded of 0.0MB (12826617.74%)
Average Download Speed: 44.7 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

84.0MB Downloaded of 0.0MB (13467948.62%)
Average Download Speed: 44.76 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

88.0MB Downloaded of 0.0MB (14109279.51%)
Average Download Speed: 44.83 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

92.0MB Downloaded of 0.0MB (14750610.4%)
Average Download Speed: 44.83 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

96.0MB Downloaded of 0.0MB (15391941.28%)
Average Download Speed: 44.9 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

100.0MB Downloaded of 0.0MB (16033272.17%)
Average Download Speed: 44.33 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

104.0MB Downloaded of 0.0MB (16674603.06%)
Average Download Speed: 44.82 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

108.0MB Downloaded of 0.0MB (17315933.94%)
Average Download Speed: 44.94 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

112.0MB Downloaded of 0.0MB (17957264.83%)
Average Download Speed: 45.02 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

116.0MB Downloaded of 0.0MB (18598595.72%)
Average Download Speed: 45.11 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

120.0MB Downloaded of 0.0MB (19239926.61%)
Average Download Speed: 45.09 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

124.0MB Downloaded of 0.0MB (19881257.49%)
Average Download Speed: 45.12 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

128.0MB Downloaded of 0.0MB (20522588.38%)
Average Download Speed: 45.2 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

132.0MB Downloaded of 0.0MB (21163919.27%)
Average Download Speed: 45.2 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

136.0MB Downloaded of 0.0MB (21805250.15%)
Average Download Speed: 45.2 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

140.0MB Downloaded of 0.0MB (22446581.04%)
Average Download Speed: 45.23 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

144.0MB Downloaded of 0.0MB (23087911.93%)
Average Download Speed: 45.07 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

148.0MB Downloaded of 0.0MB (23729242.81%)
Average Download Speed: 45.09 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

152.0MB Downloaded of 0.0MB (24370573.7%)
Average Download Speed: 45.03 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

156.0MB Downloaded of 0.0MB (25011904.59%)
Average Download Speed: 45.06 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

160.0MB Downloaded of 0.0MB (25653235.47%)
Average Download Speed: 45.07 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

164.0MB Downloaded of 0.0MB (26294566.36%)
Average Download Speed: 45.07 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

168.0MB Downloaded of 0.0MB (26935897.25%)
Average Download Speed: 45.13 MB/s
################################
# Downloading: 12-Monterey.zip #
################################

169.59MB Downloaded of 0.0MB (27191536.54%)
Average Download Speed: 45.14 MB/s
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/tmp/_MEISfEYX8/payloads
- Found Root Volume at: disk2s1
- Root Volume is already mounted
- Running patches for Macmini5,1
- Installing legacy Sandy Bridge Patches
- Detected supported OS, installing Acceleration Patches
- Installing Sandy Bridge Acceleration Kext patches for Big Sur/Monterey
- Couldn't find AMDRadeonX4000.kext, skipping
- Couldn't find AMDRadeonX4000HWServices.kext, skipping
- Couldn't find AMDRadeonX5000.kext, skipping
- Couldn't find AMDRadeonX5000HWServices.kext, skipping
- Couldn't find AMDRadeonX6000.kext, skipping
- Couldn't find AMDRadeonX6000Framebuffer.kext, skipping
- Couldn't find AMDRadeonX6000HWServices.kext, skipping
- Couldn't find AppleIntelBDWGraphics.kext, skipping
- Couldn't find AppleIntelBDWGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelCFLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelHD4000Graphics.kext, skipping
- Couldn't find AppleIntelHD5000Graphics.kext, skipping
- Couldn't find AppleIntelICLGraphics.kext, skipping
- Couldn't find AppleIntelICLLPGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelKBLGraphics.kext, skipping
- Couldn't find AppleIntelKBLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelSKLGraphics.kext, skipping
- Couldn't find AppleIntelSKLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelFramebufferAzul.kext, skipping
- Couldn't find AppleIntelFramebufferCapri.kext, skipping
- Couldn't find AppleParavirtGPU.kext, skipping
- Couldn't find GeForce.kext, skipping
- Deleting IOAcceleratorFamily2.kext
- Couldn't find IOGPUFamily.kext, skipping
- Installing General Acceleration Kext patches for Big Sur/Monterey
- Adding IOAcceleratorFamily2.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000Graphics.kext
- Adding AppleIntelHD3000Graphics.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsGA.plugin
- Adding AppleIntelHD3000GraphicsGA.plugin
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsGLDriver.bundle
- Adding AppleIntelHD3000GraphicsGLDriver.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsVADriver.bundle
- Adding AppleIntelHD3000GraphicsVADriver.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelSNBVA.bundle
- Adding AppleIntelSNBVA.bundle
- Using stock AppleIntelSNBGraphicsFB
- Adding AppleIntelSNBGraphicsFB.kext
- Merging AppleGVA Hardware Accel patches for non-Metal
- Merging general legacy Frameworks
- Merging Monterey WebKit patch
- Merging general legacy PrivateFrameworks
- Rebuilding Kernel Cache (This may take some time)
- Successfully built new kernel cache
- Creating new APFS snapshot
- Unable to create new snapshot
Reason for snapshot failure:
Can't use last-sealed-snapshot or create-snapshot on non system volume

- This is an APFS bug with Monterey! Perform a clean installation to ensure your APFS volume is built correctly

**Comment by khronokernel** [comment]
The logs already tells you what further action is required. Please use forums for further troubleshooting
