### ISSUE TITLE
External display not working.

### ISSUE THREAD

**Issue by il-rollino** [dortania/Opencore-Legacy-Patcher#85]
Hi everyone.

I used OCLP v0.0.15 on a MacBook Pro 10,1 (15" Retina mid 2012), both installing BS 11.2.2 on an empty USB SSD and on internal SSD overwriting the existing BS 11.2.2 installed with Barrykn's micropatcher.
On both attempt I wasn't able to use my 2 external displays: the first one connected with a DisplayPort cable, the second one with HDMI cable via Elgato Thunderbolt2 dock. The 2 displays weren't shown in Preference Panel --> Display neither in System Report.

No difference between using the laptop in clamshell mode or opened or trying to connect just one display or disconnecting and re-connecting the cables.
USB and Ethernet ports on the thunderbolt dock worked correctly.

They both were recognized by the system and worked properly before using OCLP and they got back working after re-installing BS with micropatcher.

In the attached image the specs of the displays (as I wrote before, nothing were shown in the rectangle while using OCLP).

![image](https://user-images.githubusercontent.com/80351311/110514306-76093080-8107-11eb-980d-b7e9656517c6.png)

**Comment by khronokernel** [comment]
Hmm, could you try the 2 below builds and tell me if either seem to have fixed the issue?:

[OpenCore-AGDP=vit9696.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6110491/OpenCore-AGDP.vit9696.zip)
[OpenCore-no-AGDP.zip](https://github.com/dortania/Opencore-Legacy-Patcher/files/6110492/OpenCore-no-AGDP.zip)

Additionally, does the internal display work correctly when the dGPU switches on? ie. manually enabling in settings or running GPU intensive tasks

**Comment by il-rollino** [comment]
Thank you very much for your quick answer.
Yes I switched off the automatic GPU switch, the dGPU was working but the displays didn't.

Anyway with all these 3 builds the displays worked fine, thank you.
Which one do you suggest to use with my system or shall I need to wait a new public build?

(Sorry for all these questions but i'm a noob)

**Comment by khronokernel** [comment]
> Which one do you suggest to use with my system or shall I need to wait a new public build?

Oh awesome! I would recommend using no-AGDP as that's what we'll add the patcher for dual GPU Retina Macs.

Will close this issue when I've updated the patcher

**Comment by khronokernel** [comment]
Fixed in main
