### ISSUE TITLE
Problems with graphics on MBP (mid 2012)

### ISSUE THREAD

**Issue by Ency79** [dortania/OpenCore-Legacy-Patcher#850]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I have installed with open core legacy patcher Monterey with the latest version. After successful setup I have applied the MacOS Update for Monterey and installed it. Then after reboot I couldn't see my graphic card in the system overview . it only displayed 3MB. 

Then I have read again the tutorial and saw that for my model I do not need the post installation patch. But my graphic card was not shown, so I have installed the post patch rebooted the system and then the system recognized my graphic card Intel HD Graphics 4000 1536 MB.

My system is booting normally and works but when I look detailed I see in some programs that the graphic flickers. And also the borders of the Mac OS navigation bar is flickering.

Any suggestion how to fix that???

**Comment by educovas** [comment]
Apple bug, even some supported machines have this issue.

**Comment by Ency79** [comment]
Is there no apple fix for that???

**Comment by educovas** [comment]
No, and I don't think they are going to fix that on Monterey at this point. Maybe on a next release.

**Comment by AndreasJordanidis** [comment]
strange behavior, flickering shouldn't be present on Metal cards, only pixelated edges should
