### ISSUE TITLE
iMac 12.2 lost airdrop in Monterey

### ISSUE THREAD

**Issue by t2pierre** [dortania/OpenCore-Legacy-Patcher#851]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

iMac 12.2 with post-install patch applied
wifi and bluetooth working fine
but no airdrop: not present in finder/go; manuel launch of airdrop app gives "cannot complete because missing element"
looks like wifi card not properperly recognized in my opinion

**Comment by Ausdauersportler** [comment]
Airdrop on any macOS version later than High Sierra needs upgraded hardware with your iMac, take a look at this [thread](https://forums.macrumors.com/threads/imac-mid-2011-bluetooth-4-0-internal-upgrade.1780242/post-19717599).
