### ISSUE TITLE
OCLP not working on internal SSD

### ISSUE THREAD

**Issue by RobertoCMCosta** [dortania/OpenCore-Legacy-Patcher#852]
### Machine Model

iMac13,2 and 11,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

After failing to update from 11.6.1 to 11.6.2 multiple times via software update ending up with wifi and brightness control not working, I decide to do a clean install of Big Sur restoring my data from a TM backup. 
After finishing the installation I installed OCLP 0.3.3 to the internal drive using the TUI app, using the same settings I used to make the install media. 
Booting from the install media EFI, SIP and SSV are enabled, Mac Firmware shows correctly.
Booting from the internal drive where macOS was installed, SIP is partially enabled (unknown configuration) and Mac firmware shows a wrong number.
I repeated the installation of OCPL to the internal drive setting the option with the same result. In between I did NVRAM resets every time I changed boot media.

What am I doing wrong? Should it not work the same as with the USB thumb drive?
Is there any hidden option I'm missing?
I decided to stay with Big Sur to have SIP and SSV on since my iMac is fully supported on this OS.
Any help will be much appreciated.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
