### ISSUE TITLE
Patcher is not notarized

### ISSUE THREAD

**Issue by Lars-Br** [dortania/OpenCore-Legacy-Patcher#853]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

The documentation clearly states that the patcher binary is notarized, e.g. [here](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/599) and [here](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/417).

However, when I download the current release (0.3.3), it is signed, but not notarized.

**Comment by Lars-Br** [comment]
I just noticed that only the offline installer isn't notarized. Is there a reason why the offline installer would not be notarized?

**Comment by khronokernel** [comment]
Currently not interested in maintaining additional applications within our notarization system, as the offline users make up a small subset of our userbase and we're already shipping notarized TUI and GUI variants

Could be reconsidered in the future however right now we'd rather prioritize other projects within OCLP
