### ISSUE TITLE
Photo booth not working 12.1

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#854]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Within photo booth, instead if the iSight showing camera feed, I am met with a black screen. FaceTime works to show video feed, seems to be an issue only related to photo booth

I have checked legacy acceleration pages, #108, cannot find answer anywhere

Sadly, cannot confirm if this issue was present in 12.0.1

sorry if I am mass opening issues (or if it seems like it)

### Any Additional Information

iMac11,3 - no upgrades

ATI Radeon 5750 1024mb - root patched

intel core i7 870

**Comment by Ausdauersportler** [comment]
Update the GPU and all your problems are gone. I am afraid fighting against the metal layer is a lost cause.

**Comment by khronokernel** [comment]
Updated issue to reflect:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by Thyssenkrupp234** [comment]
@Ausdauersportler, I would upgrade my GPU, I know there is a guide for 2009-2011 macs, but I don't really want to risk breaking my computer seeing as this iMac is my only computer, and has all of my work on it. I am also not familiar with mac **hardware and removing/adding/servicing hardware,** I don't want to pay for that to be done, and finally I don't want to pay for another GPU. I don't mind minor issues, though I understand what you mean 😉
