### ISSUE TITLE
MacBook pro10,1 takes too long time to boot in Catalina

### ISSUE THREAD

**Issue by richardkindom** [dortania/OpenCore-Legacy-Patcher#855]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true, false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 10.15, Catalina

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (Before Logging in)

### What is the Issue?

It appears that Catalina updates something and takes rather long time than normal apple boot loader. After login you will find an APFS volume named UPDATE on desktop which occupied around 300KB.
This would repeat after reboot into Catalina.

**Comment by Thyssenkrupp234** [comment]
Yes. Using a bootloader that injects kexts and drivers into the operating system is obviously going to take longer than normal macOS. The APFS volume named "Update" is present in vanilla Catalina installations, and is not an issue regarding OC/OCLP. Either don't use OpenCore Legacy Patcher or wait slightly longer boot times and longer updates.

**Comment by khronokernel** [comment]
As Thyssenkrupp234 commented, these are to be expected. Seeing as Catalina is a natively supported OS, we were unable to dedicate development time to this. However feel free to research further as to what may be causing these extended boot stalls and provide patch sets, we greatly appreciate any additional help.

**Comment by richardkindom** [comment]
hey, I've use max kernel option to disable all kexts loaded in Catalina, well nothing helps. I am stilling looking at it. Thanks.
