### ISSUE TITLE
Install loop

### ISSUE THREAD

**Issue by SimonRenggli1** [dortania/OpenCore-Legacy-Patcher#856]
### Machine Model

MacBook8,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

When I install Big Sur it installs normaly. But when it finishes it brings me back to the recovery tab. When I boot without a Usb stick I get a white screen with a flashing folder and a question mark on the folder

**Comment by khronokernel** [comment]
Use forums for troubleshooting
