### ISSUE TITLE
iMac 15,1 App issues after install Monterey

### ISSUE THREAD

**Issue by imknight** [dortania/OpenCore-Legacy-Patcher#857]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Some apps that can't run include Xcode, Page, Number, Keynote. It seems like all are later to some security policy issue.

Xcode
Application Specific Information:
dlopen(@rpath/libIDEApplicationLoader.dylib, 0x0001): tried:(security policy does not allow @ path expansion)
abort() called

Page
Application Specific Information:
Library not loaded: @rpath/TSKit.framework/Versions/A/TSKit
Referenced from: /Applications/Pages.app/Contents/MacOS/Pages
Reason: tried: '/System/Library/Frameworks/TSKit.framework/Versions/A/TSKit' (no such file), (security policy does not allow @ path expansion)

**Comment by khronokernel** [comment]
We do not touch AMFI, code signature checks or SIP on iMac15,1. Additionally cannot replicate on local iMac15,1, assuming local macOS bug. Use forums for further troubleshooting

**Comment by imknight** [comment]
@khronokernel sorry, which forum do you mean? I try to search there is no discussion enabled for this repo.
