### ISSUE TITLE
Problem launching applications with dock

### ISSUE THREAD

**Issue by Alfio1023** [dortania/OpenCore-Legacy-Patcher#858]
### Machine Model

iMac13,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hello,

I have problems with launching applications with the dock, they don't launch and sometimes the system crashes.

To solve the problem I must reinstall OpenCore-Patcher TUI every time and then restart my mac.

**Comment by Mark-Schell** [comment]
Hello Alfio,

Please check before installing OpenCore-Patcher the next settings into (system control -> security -> privacy

Full Disk Permission for :

Terminal
Open Core-Patcher

And if you use a anti-virus turn it off for a few minutes and after the restart turn it on again.

**Comment by Alfio1023** [comment]
> Hello Alfio,
> 
> Please check before installing OpenCore-Patcher the next settings into (system control -> security -> privacy
> 
> Full Disk Permission for :
> 
> Terminal Open Core-Patcher
> 
> And if you use a anti-virus turn it off for a few minutes and after the restart turn it on again.

Hello,
I tried your method, but it still does not work ...

**Comment by khronokernel** [comment]
With 0.3.4 you can disable FeatureUnlock to mitigate this issue on systems with weakened memory stability

Once 0.3.4 is released, documentation will be updated accordingly

**Comment by Alfio1023** [comment]
Ok thank you, I will try as soon as 0.3.4 is released


Le 15.01.22 à 00:51, Mykola Grymalyuk a écrit :
