### ISSUE TITLE
com.apple.driver.AppleMultitouchDriver panic on MacPro5,1

### ISSUE THREAD

**Issue by Schaefers** [dortania/OpenCore-Legacy-Patcher#859]
### Machine Model

MacPro4,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I installed a BCM94360CD network card in my MacPro 5,1 (flashed from 4,1) which works fine on 10.13.6 - when trying to boot the Monterey installer using OCLP I receive the following panic right after start-up. 

[panic-2021-12-31-143337.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7796423/panic-2021-12-31-143337.txt)

**Comment by khronokernel** [comment]
> Mac OS version:
> 15G22010

This panic log is from 10.11.6, and seems to be booted without OpenCore at all as there are no NVRAM arguments (we always inject `keepsyms=1 debug=0x100` to ensurer better panic logging)

Either hardware fault or user error, not in scope of this project. Please use forums for further troubleshooting
