### ISSUE TITLE
Installer blocked at AppleUSBLegacyRoot after "DSMOS has arrived"

### ISSUE THREAD

**Issue by ZEALORD98** [dortania/OpenCore-Legacy-Patcher#860]
### Machine Model

MacBookPro7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

Hello,

So I tried to install Monterey 12.1 using OpenCore Legacy Patcher 0.3.3 offline TUI on a Macbook Pro mid 2010 the 7.1 model.

After creating the bootable drive to install Monterey patched from, I ran the installer and everything went as expected (following the instruction from this video https://youtu.be/go6RTCHv4GA).

Went with the upgrade option since I already made a clean installation of High Sierra (and the potential need for wifi patches )

So I had the "macOS will be installed in XX minutes" then an apple logo came up on a black screen and with a progress bar. Then verbose info came back and the installer stopped on this line :

000001.616918 AppleUSBLegacyRoot@: AppleUSBLegacyRoot::init: enabling legacy matching

After a while .. thought the installer froze so I tried to reboot and restart the installer and it comes back directly to this line. And now I cant boot from another HDD (with the original High Sierra) to restart everything with different versions. 

Thanks in advance

**Comment by khronokernel** [comment]
> And now I cant boot from another HDD (with the original High Sierra)

If the machine no longer boots a native installation, out of scope for our patcher. Use forums for further troubleshooting
