### ISSUE TITLE
iMac 14,2 slow boot with Monterey 12.1

### ISSUE THREAD

**Issue by terraboss** [dortania/OpenCore-Legacy-Patcher#861]
### Machine Model

iMac14,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

The boot process takes an extremely long time despite installation on a Samsung 970 EVO NVme SSD. On average 7-10 minutes. There is great potential for optimization here! 

If necessary, I'll be happy to upload a video of the Verbose mode to show where it hangs in particular.

Thanks in advance!

**Comment by khronokernel** [comment]
Is there an SD Card plugged into the machine while booting?

**Comment by terraboss** [comment]
No, there is no SD card in the Mac.

**Comment by khronokernel** [comment]
Post the verbose output on what it's stalling on

**Comment by terraboss** [comment]
https://www.youtube.com/watch?v=qKv4s8NMQb4

Thanks for your help. I have uploaded a video of the boot process to YouTube. It takes a few minutes until it is available.

Feel free to let me know if there's anything else you'd like to know.

**Comment by khronokernel** [comment]
> `busy timeout[0]. (60s): 'iMac14,2'`

System's getting hung up on this several times, looks to be an installation issue. Try installing Monterey fresh (new APFS volume is fine) and verify this issue is replicable. Most likely just a KernelCollection bug in macOS, can affect native machines as well.

**Comment by terraboss** [comment]
Thank you. I will give that a try tomorrow. 

I was hoping I could avoid formatting and reinstalling.

**Comment by khronokernel** [comment]
Shouldn't need to format, just create a new APFS volume and install fresh there. The old volume can still be retained

**Comment by terraboss** [comment]
I have only 150 GB of 1 TB free. That will probably be a bit tight for macOS in the long run. :-)

**Comment by terraboss** [comment]
May I know what (for my or a similar configuration) is the boot time on average / normal?

**Comment by terraboss** [comment]
I can confirm, macOS still needs a lot of time to boot. 👎 

I've tested the patch also on my MBP mid 2014 and the machine is not even booting and stucks somewhere at the point, I was noticed about the availability of the VoiceOver feature. Screen was still black with boot loading bar. I've tried two clean installs. 

I'm sorry to say, but your patcher is horrible unreliable. 
[x] Yes, most hardware drivers working well. 
[x] It's a great project at all.
[x] It has a great UI / TUI with an easy to use concept.

But it destroys the boot process at all. :-(

**Comment by khronokernel** [comment]
> I'm sorry to say, but your patcher is horrible unreliable.

Well unreliable for you in your local environment. No one else is able to replicate within our team, and unless you're facing macOS's SDXC bug, you most likely have botched hardware ([non-Apple "blessed" Samsung SSD are known to not be the best](https://github.com/dortania/bugtracker/issues/192), additionally newer OSes generally put more strain on aging hardware). 

> I've tested the patch also on my MBP mid 2014 and the machine is not even booting and stucks somewhere at the point, I was noticed about the availability of the VoiceOver feature. Screen was still black with boot loading bar. I've tried two clean installs.

You did not read the documentation:

* [Booting OpenCore and macOS: MacBookPro11,3 Note](https://dortania.github.io/OpenCore-Legacy-Patcher/BOOT.html)
* [Troubleshooting: Black Screen on MacBookPro11,3 in macOS Monterey](https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html#black-screen-on-macbookpro11-3-in-macos-monterey)

Again looking through this issue as well your comments, this looks to be a local issue either with your systems or yourself. As it stands, we cannot dedicate more development resources for a local issue as we have many other projects within OCLP we need to prioritize. You'd best troubleshoot on forums and determine the root cause of your issue.

Feel free to PR a solution to the repo, we always appreciate extra help as this is a fully unpaid team, taking time out of our days doing this to help the community.

**Comment by terraboss** [comment]
You wrote: "Everything is supported" on this page:
https://dortania.github.io/OpenCore-Legacy-Patcher/MODELS.html#macbook-pro

I then also expect this to be the case. If you already know special cases where certain configurations cause problems or extra steps are necessary, I implore you to communicate these things on this page in the comment column ui. Otherwise, I have to assume that everything works smoothly.

I never had any problems with my Samsung SSD in the iMac either. The problems only appear with your patcher. So you have to point it out accordingly please. SSD swaps are not uncommon as Apple is making a killing on storage prices. I can't see that it's my responsibility to fix this issue, which I believe is technically easy for software developers to fix with a few lines of code. I'm also happy to give a small donation! It is not up to me to set the right priorities. 

Top priority should be: If "Everything is supported" is there, that "Everything is supported" also works.

**Comment by khronokernel** [comment]
Why is there so much entitlement coming from someone who does not pay for my bills, and is complaining that they deserve more? Look, multiple developers internally have upgraded their SSDs, including SATA based systems like MacBookPro9,2, NVMe based systems like iMac14,1, iMac15,1 and MacPro4,1. We have no reason to believe this is a fault of ours that affects everyone's system, as we can neither replicate nor have others reported this to us.

We all have lives we live and we can't just drop everything and dedicate time to a wining child in another continent. If we can replicate it either ourselves or within our testers, we're glad to dedicate more time as it's a legitimate issue affecting others. 

And finally happy new year to yourself, hope the rest of your year is better than the atrocious experience you got from us.
