### ISSUE TITLE
“0:188: execution error: Volume on disk timed out waiting to mount”

### ISSUE THREAD

**Issue by Aranyadev** [dortania/OpenCore-Legacy-Patcher#862]
### Machine Model

iMac14,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After having tried to install the latest OpenCore patcher several times, and the graphics of macOS Monterey still doesn't work properly, I tried yet again, and got this message while trying to install (just after selecting the newly created EFI disk, which is still mounted on the desktop when typing this): 

```
An error occurred!
0:188: execution error: Volume on disk0s1 timed out waiting to mount
 (1)


Please report this to the devs at GitHub.Please clearly explain the issue
```

**Comment by khronokernel** [comment]
This would be considered a macOS or hardware timeout issue if you continue to have issues.

Try a different installation media or different copy of macOS, otherwise best to troubleshoot further on forums
