### ISSUE TITLE
Are there any issues with Monterey or Big Sur on a 10,1 Pro?

### ISSUE THREAD

**Issue by AndreasJordanidis** [dortania/OpenCore-Legacy-Patcher#863]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hi, I know this is probably not meant to be posted here, but Im planning to upgrade my early 2013 15 retina from Catalina to Big Sur or Monterey depending on the amount of issues, are there any big issues or imperfections with either of these OSses?

Thank you

**Comment by Ausdauersportler** [comment]
Happy New Year!

On the Github page Discord is mentioned to discuss such things, can you at least try it?

**Comment by AndreasJordanidis** [comment]
I would if they didn’t kick me out

**Comment by khronokernel** [comment]
Please do not use issues tab for general discussion, use forums

**Comment by AndreasJordanidis** [comment]
where can I find forums?
