### ISSUE TITLE
Windows 10 UEFI Install: "Windows Could Not Prepare the Computer to Boot Into the Next Phase of Installation"

### ISSUE THREAD

**Issue by jtylrr** [dortania/OpenCore-Legacy-Patcher#864]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true, false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 10.14, Mojave

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I'm having trouble following the Windows 10 install guide on my 2011 iMac.. When I go to install it, it tells me that

"Windows Could Not Prepare the Computer to Boot Into the Next Phase of Installation" – it seems like it doesn't know where to boot from after restarting.

I'm thinking this might be because I'm trying to mix regular booting (Mojave) and OpenCore (Windows 10) but I can't be sure

**Comment by khronokernel** [comment]
Please use forums for troubleshooting, we're focused on macOS support primarily and more specifically OCLP-based issues. Windows installer issues would be out of scope
