### ISSUE TITLE
Old versions of apps not compatible w/ Monterey

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#865]
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

On the acceleration page on https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html, there is a download page on archive.org to older versions of apps, like Final Cut Pro. I have a license for it, but crashes on startup due to metal back-end. The non-metal app supplied via archive.org does not launch, though. It says "In order to use “Final Cut Pro”, you need to update to the latest version." with the sub text being "The version of Final Cut Pro installed on this Mac is not compatible with macOS Monterey. Download the latest version from the App Store."

I know this issue is not as important as others, so feel free to close it. There should be a way to force it to launch, right? Maybe editing some PLIST files, I'm not sure. I was able to get it working by manually starting the executable via terminal, but this solution is not perfect. Maybe update this on the acceleration pages?

Any ideas would be appreciated. Thanks!

**Comment by WildChild-SomethingWild** [comment]
The only way to make Final Cut Pro work on Monterey currently is to launch the app by the terminal executable, modifying or replacing the Plist with a higher Final Cut Pro build can work until you reboot your machine. Rebooting will result to make Final Cut Pro not be able to work again until you reinstall the app. (Only for FCP and iMovie)
Logic Pro or others, will work like it should without any problems.

**Comment by Thyssenkrupp234** [comment]
I see. So once I reboot, FCP will not be able to launch via the executable? For all I care, I'll just make a shell script launching the unix executable file if that works every time

@WildChild-SomethingWild

**Comment by WildChild-SomethingWild** [comment]
Exactly, the executable will always work even a after a reboot. Only reinstalling FCP will be required if you edit or replace the Plist of it.
There might be a way but I didn’t dig into that enough since the executable works just fine.

**Comment by Thyssenkrupp234** [comment]
@WildChild-SomethingWild, Thanks for the confirmation! I'm going to go and create the launcher app right now. Compressor also has issues, so I'll go ahead and download that right now. Thank you for your help!
