### ISSUE TITLE
MacBookPro8,2 GPU "issues" on reboot

### ISSUE THREAD

**Issue by TheMorc** [dortania/OpenCore-Legacy-Patcher#866]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hi guys, anyone here who could know what's wrong?
Firstly happy new year to everyone here! I have a MacBookPro8,2 up and running wonderfully with Monterey 12.1, with the dGPU still working but disabled on purpose using the NVRAM flag so that it's not being stressed. But I seem to have a small issue on restarts.

The thing is that if you restart it, it just doesn't switch to the iGPU or something during booting on the progress bar _(just cuts to a black screen on the progress bar, with it not even switching back to it as it usually does and also keyboard backlight turns on as if hidd didn't go to the fallback mode or something..)_. and you have to reset NVRAM and put the gpu-power-prefs flag back to it.
I can confirm that the flag didn't disappear before resetting the NVRAM, because i always thought it disappeared by itself but after checking in single user mode it was there. It happened a few already and the NVRAM reset + adding the flag back fixed it everytime. It doesn't bother me much because I know what I need to do but it would be a bigger issue if I wanted to move this MacBook to someone else in my family.

Maybe i'm only doing something wrong, who knows... Maybe I should reinstall it, send some logs or something else, I don't know..

Also one last thing. Dosdude's patchers were great, I used the Mojave and Catalina patchers and patched Catalina is still installed on a family member's MacBook. It's something like on my hackintosh back in 2020, switching to OpenCore was a quite nicer experience than with Clover on my Hackintosh and OCLP was leaps ahead on these real Macs in comparison with those from dosdude in terms of everything. From downloading the installer, making the USB, adding OC to the USB, booting the installer and installing it. It was just so smooth. Thanks guys again for everything you do!

**Comment by Mark-Schell** [comment]
Mmm strange it looks like your pc doesnt save the kext files correctly.

Maybe you should check the next security settings: (system settings -> security-> privacy)

Open Core Text interface -> Full Disk Permission
Terminal -> Full Disk Permission

If you use a Antivirus turn it off before installing the patches because of false positives.
And check the energy settings in the battery/energy control panel, maybe if you change the energy save modus for the graphic card the issue is resolved.

And if it doesn't work please send some logs from the console ;)

**Comment by khronokernel** [comment]
Best to use forums to troubleshoot
