### ISSUE TITLE
Feedback about MacBook4,1 experience

### ISSUE THREAD

**Issue by Thyssenkrupp234** [dortania/OpenCore-Legacy-Patcher#868]
### Machine Model

MacBook4,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true, false

### What versions of macOS are you seeing the problem on?

macOS 10.14, Mojave

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hey. So far, there have been 2 issues on this github talking about the MacBook4,1, a very interesting model. Issues: #126 and #789. In #126, the user talks about not having any input devices working, and the USB ports not working. I will explain my current setup.

First of all, I downloaded a Mojave installer and created it bootable. I then patched it using [Julian Fairfax/RMC team's macos-patcher](https://gitlab.com/julianfairfax/macos-patcher) and installed Mojave to a partition on the internal. I ran the patches supplied by the macos-patcher tool, and most things worked. I then got some GPU kexts for the GMA GPU (X3100) to improve GPU performance (this is NO full graphics acceleration) and installed those. Installed all available updates and re patched. I am on 10.14.6 with all security updates installed and am now downloading OCLP and building the EFI to see what that will bring. Surprisingly, once booted into Mojave with OC, many of the patches provided by the RMC patcher, are disregarded. For example, I cannot adjust the volume. Despite the iSight supposedly being fixed for this model in a release (or maybe a commit), the iSight appears broken aswell. The GPU kexts I also installed seem to not be registering. 

My last problem is that when attempted to boot Monterey 12.0.1 installer, after some time you are greeted with a prohibited sign. This appears to happen after the gigabyte Ethernet driver is loaded. 

With all that out of the way, OpenCore Legacy Patcher has some issues with the MacBook4,1, but the docs also have false information regarding this model, like the ports and internal trackpad and keyboard not working. If there ever is a plan to add GMA acceleration (or atleast try to), there could be some serious potential with some of these macbook models and the MBA1,1. As for the Monterey install USB not booting, I'll try to take a look at that. Until some of these issues are resolved, like the kexts not working with OpenCore EFI, I will avoid it until then. I know it is hard to workaround these issues, but as shown [here](https://gitlab.com/julianfairfax/macos-patcher/-/tree/master/resources/patch/MacBook4%2C1), there is a dedicated folder of MacBook4,1 patches. Maybe OCLP could implement these patches, and I'll add the X3100 improvement kexts for the GPU.

### Any Additional Information

Sorry for such a beefy issue, just wanted to clearly explain the possibilities of further patch/kext implementation, to better support this model.

Thanks for your time!

**Comment by Thyssenkrupp234** [comment]
Update: [here](https://mega.nz/file/U910hJSD#xPC4pfnceapBpMm3KxrIPE4JaACfwyAU4vHbnxamDO8) is the ZIP I used to install the GMA kexts. I did not manually install the audio drivers from that folder, only the GMA kexts. I can confirm audio now works without booting from OC, but brightness controls do not work on either methods. I use NoSleep to avoid crashing, but the iSight does NOT work on either methods as well.

**Comment by khronokernel** [comment]
Our documentation is based on the assumption the user is running macOS Big Sur or Monterey, any older OSes are not officially supported from our perspective as the many great minds of the past have put great work into these areas (namely dosdude1)

We keep Mojave/Catalina root volume support mainly for developer testing and TeraScale 2 acceleration. We have no plans to support these OSes officially as we'd much rather focus our development time on newer OSes.

Regarding GMA based acceleration, very unlikely. Great minds like Julian have spent quite some time trying to achieve acceleration in unsupported OSes much before the dawn of Metal, and if they were unsuccessful in Mavericks there's little reason to attempt newer OSes.

Finally regarding the additional patches needed for MacBook4,1, we'd rather not add quite so much extra bloat into OCLP for a single model and have to maintain them without understanding the patch sets. However if you've validated patches to work, are certain of their validity as fixes and can explain them, feel free to PR into the repository. Additional help is always greatly appreciated

**Comment by Thyssenkrupp234** [comment]
@khronokernel, thanks for your big reply and explaining. I understand about the GMA acceleration, and the bloat. Since I didn’t create the patches, I can’t really validate them but they are open-sources. If I could find a way to get the patches implemented I could, sadly I am not very familiar with python and shell, more backend JavaScript and HTML. 

I think you should update the documentation (https://Dortania.github.io/OpenCore-Legacy-Patcher/) to show that internal keyboard and trackpad are working, aswell as USB slots. The Monterey boot issue seems to still be present, I will try to look deeper into that. I’ll see what I can do, and maybe Julian can look into it. Thanks for the thorough explanations, I guess I’ll just stay on Monterey on my iMac, and Mojave on my MacBook.

**Comment by DC7IA** [comment]
> I think you should update the documentation (https://Dortania.github.io/OpenCore-Legacy-Patcher/) to show that internal keyboard and trackpad are working, aswell as USB slots.

Thanks for posting this. Looks like I will try it, previously I abandoned the idea entirely. Not easy to use an OS without any input. :)

**Comment by Thyssenkrupp234** [comment]
@DC7IA, yeah lol! Just curious, what Patcher did you use and did you find out how to get GPU acceleration? I found a website “Osafo” that claims to have gotten perfect GPU acceleration on Catalina. But; the RAR is password protected and his email said I need to donate $30 bucks

**Comment by khronokernel** [comment]
> I think you should update the documentation (https://Dortania.github.io/OpenCore-Legacy-Patcher/) to show that internal keyboard and trackpad are working, aswell as USB slots.

Oh interesting, is this applicable with Big Sur? If so, will update the documentation to reflect

**Comment by Thyssenkrupp234** [comment]
@khronokernel, I’ll test that with a big sur installer ASAP. When I attempted Monterey, OpenCore and the installer were on the same drive and booted until an something triggered a prohibited sign. Will try with 11.2.3 aswell as latest big sur installer.

**Comment by Thyssenkrupp234** [comment]
@khronokernel 

Creating the Big Sur 11.2.3 install media. It’s a slow USB because I am on vacation and have limited supplies. Will update when finished.
![image](https://user-images.githubusercontent.com/76831903/147965761-c7c186da-e70e-4ec7-8ec9-6e57f5020128.jpg)

**Comment by Thyssenkrupp234** [comment]
Just another update here. When attempting to boot the Big Sur installer, after about half way it shows this screen:
![image](https://user-images.githubusercontent.com/76831903/147970864-e7917560-b905-4e0a-87be-f03f484133cf.jpg)
Trying verbose mode now. Will update comment when done

**Comment by Thyssenkrupp234** [comment]
Update: when I use verbose mode, everything boots fine until this phase: 
![FFE627D8-5538-48A2-BAA3-450401294A05](https://user-images.githubusercontent.com/76831903/147972391-3630a4a9-b624-47b2-8245-4136e9ce0a38.png)

That hangs for about 20 seconds, (slow USB) and then immediately this shows: 
![B79AAA00-3675-4F6C-ADA6-223189BF3852](https://user-images.githubusercontent.com/76831903/147972453-b376ff3b-7b14-4d9d-a398-df2f30bb1678.jpeg)

I myself cannot read that text, I don’t really know what to make of this. Might try an earlier Big Sur version...

@khronokernel, what do you think?

**Comment by khronokernel** [comment]
Broken USB support, as it cannot transition from UEFI to kernel side rooting. This lines up with what we've previously been told, USB support on the legacy mobile GMA chipset is unstable/non-functional in Big Sur.

**Comment by Thyssenkrupp234** [comment]
Interesting. Anything else you would like me to test? I could try making a partition on the internal and using that... not sure though. Seems to be that the MacBook4,1 is helpless on Big Sur+

If that is so, maybe the docs can explain this? Like recommended to use macOS-Patcher for Catalina and below.

**Comment by khronokernel** [comment]
> If that is so, maybe the docs can explain this? Like recommended to use macOS-Patcher for Catalina and below.

We already don't endorse usage of Mojave/Catalina both in the README.md and root patching:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/README.md
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/resources/cli_menu.py#L571-L584

**Comment by DC7IA** [comment]
> Just curious, what Patcher did you use and did you find out how to get GPU acceleration?

Someone you used for Mojave, but since it is only usable up to Catalina I only tried Catalina.

**Comment by DC7IA** [comment]
> @DC7IA, which big sur version did you try? Monterey and big sur 11.6.2 have not booted successfully
> Trying verbose mode now. Will update comment when done

Didn't try since documentation says no input.

@Thyssenkrupp234

**Comment by Thyssenkrupp234** [comment]
Ok. I’m planning to upgrade to Catalina, you used the same Patcher I used? Did you use “Catalina Unus”? Thanks 

@DC7IA

**Comment by DC7IA** [comment]
> Ok. I’m planning to upgrade to Catalina, you used the same Patcher I used? Did you use “Catalina Unus”? Thanks

If you used this: https://gitlab.com/julianfairfax/macos-patcher/

Then yes, this is what you linked to. It works, just the external screen does not seem to work.

**Comment by julianfairfax** [comment]
Hi,
No idea about anything newer than Catalina, though I may or may not have more to say on that subject at some point soon. What I can tell you is that whatever drivers you're getting from the internet aren't going to improve anything on top of what my patchers install, and neither will ever give you full graphics acceleration. To do so is not currently possible for me to achieve with what is available to us by Apple in any way ever. And iSight won't work on this computer on any version newer than OS X El Capitan. I will look into that again, but I doubt I'll be able to fix it. At a certain point, older drivers just won't work on the newer operating systems with all hardware.
