### ISSUE TITLE
Missing certain onboard keys on Monterey 

### ISSUE THREAD

**Issue by nikefe** [dortania/OpenCore-Legacy-Patcher#869]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

The keys in onboard not working is the letter **U J ; ' M** unless I use onscreen or external keyboard to type it in.
I need HELP please

**Comment by khronokernel** [comment]
Use forums for troubleshooting
