### ISSUE TITLE
Mac Pro 6,1 crash between boot and login

### ISSUE THREAD

**Issue by seinick** [dortania/OpenCore-Legacy-Patcher#872]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I have a Mac Pro 6,1 - "Trash Can" Mac Pro, from 2013. I installed OCLP to enable the AirPlay receiver support after upgrading to Monterey and finding that my 2013 Mac Pro was not supported natively.

Installation to the EFI boot partition on the internal SSD was smooth, and booting from it went smoothly. After Mac OS boots and presents the login screen there is a 5 - 20 second lag and then the machine crashes (shows the typical Mac crash screen). Then reboots. And does it again. To be clear, you do not need to login for the crash to happen... if you login fast enough you might see the desktop before the crash, but you can just not touch the keyboard when it shows the login screen and it will still crash.

I looked at what startup items I have, and used LaunchControl to review the launchd related services and daemons that startup when the machine starts. But after turning a bunch of those off, it still did the same thing.

### Any Additional Information

The machine has 64gb of RAM, stock video card, and it has an upgraded internal SSD upgrade from OWC. It has numerous external devices attached, two displays.

**Comment by khronokernel** [comment]
Quite strange, however we've never had a MacPro6,1 user file before. Are you able to provide a crash or panic log? Would help greatly to narrow down where the issue lies

Additionally could you provide the `Build-Folder` OCLP generates as well as the print messages while it builds?

**Comment by suletetes** [comment]
You have to hold power button and boot into the efi. I experience similar issue.

**Comment by seinick** [comment]
> Quite strange, however we've never had a MacPro6,1 user file before. Are you able to provide a crash or panic log? Would help greatly to narrow down where the issue lies
> 
> Additionally could you provide the `Build-Folder` OCLP generates as well as the print messages while it builds?

I will try to get this done soon. I can only do it while at my desk at the office right now and I’ve been working from home.

**Comment by seinick** [comment]
> You have to hold power button and boot into the efi. I experience similar issue.

I’m not totally clear what you mean. I can boot the machine just fine. Choose which partition to boot from. I just hold option down on the keyboard. The issue is it crashes after boot, after it gets to showing the login screen… but it will crash before I login. So in my perspective it isn’t a boot issue…

**Comment by suletetes** [comment]
I think you have to reset your disk remember u have monterrey on your flash just fresh install. If you have used patched sur you have to fresh install your macos.

**Comment by crystall1nedev** [comment]
Try this: (posted by a user in OCLP Discord)

1. Mount EFI, open `EFI/OC/config.plist`
2. Change `DummyPowerManagement` to `true` in that plist
3. Add [these kexts](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8903172/Archive.zip) to the config (image below)
4. Disable `DummyPowerManagement` again
<img width=75% alt="unknown" src="https://user-images.githubusercontent.com/55281754/173670748-6d82fec5-ef82-48c3-b3a4-1379ecb8ff80.png">

**Comment by khronokernel** [comment]
Resolved with this commit: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/0e270ea47369016a6c94fc2bf8654c103906ca98
