### ISSUE TITLE
Process failed with exit code 9 when installing Post-Volume Install Patches

### ISSUE THREAD

**Issue by TechCodeBlocks** [dortania/OpenCore-Legacy-Patcher#873]
### Machine Model

MacPro3,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

The error occurs when running the post-install volume patches for legacy Nvidia graphics (Tesla). The download progress indicator seems to have an issue but this didn't stop the download from completing.
`################################
# Downloading: 12-Monterey.zip #
################################

12.64MB Downloaded of 0.0MB (2026705.81%)
Average Download Speed: 0.1 MB/s
- Download completed
- Unzipping download...
Process failed with exit code 9
Please file an issue on our Github
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 92, in <module>
  File "OpenCore-Patcher.command", line 20, in __init__
  File "OpenCore-Patcher.command", line 86, in main_menu
  File "utilities.py", line 506, in start
  File "cli_menu.py", line 902, in PatchVolume
  File "sys_patch.py", line 972, in start_patch
  File "sys_patch.py", line 690, in check_files
  File "sys_patch.py", line 724, in download_files
  File "utilities.py", line 48, in process_status
Exception: Process result: 
Archive:  /private/var/folders/2p/g2r0q1m91r53kzs4kb62lz640000gn/T/_MEIXuHyJJ/payloads/Apple.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /private/var/folders/2p/g2r0q1m91r53kzs4kb62lz640000gn/T/_MEIXuHyJJ/payloads/Apple.zip or
        /private/var/folders/2p/g2r0q1m91r53kzs4kb62lz640000gn/T/_MEIXuHyJJ/payloads/Apple.zip.zip, and cannot find /private/var/folders/2p/g2r0q1m91r53kzs4kb62lz640000gn/T/_MEIXuHyJJ/payloads/Apple.zip.ZIP, period.

[497] Failed to execute script 'OpenCore-Patcher' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

**Comment by khronokernel** [comment]
> 12.64MB Downloaded of 0.0MB (2026705.81%)
> Average Download Speed: 0.1 MB/s

Download crapped out early, can you replicate this consistently? Looks to be a local network issue
