### ISSUE TITLE
MacBook Pro 10,1 external display abnormal after close laptop's display

### ISSUE THREAD

**Issue by richardkindom** [dortania/OpenCore-Legacy-Patcher#874]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

My MacBook Pro's external HDMI works fine except that external display shows black screen (but with signal)when I close the laptop's display ( external power plugged).
In Catalina, this works fine.
Could u please help?

**Comment by khronokernel** [comment]
Use forums for troubleshooting

**Comment by richardkindom** [comment]
nobody reponsed in discord. Tooooo sad

**Comment by richardkindom** [comment]
hey guys, the problem is due to that I use RDM to set external display HiDPI. The problem disappeared after using another tool

**Comment by AndreasJordanidis** [comment]
hey, what tool did you use? I also have a 10,1.
thanks in advance

**Comment by richardkindom** [comment]
> hey, what tool did you use? I also have a 10,1.
> 
> thanks in advance

onekey-hidpi
A TUI based tool which requires SIP disabled in Monterey. Good luck

**Comment by AndreasJordanidis** [comment]
thank you
