### ISSUE TITLE
No Content Caching available in new VM instantiation

### ISSUE THREAD

**Issue by mdavis30** [dortania/OpenCore-Legacy-Patcher#875]
### Machine Model

Macmini6,2

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Since updating to the 0.3.3 version, using the VM, the Content Caching is greyed out and no longer available. This is a known issue with MacOS and VMware. Is there something in the patching that can update the OS into thinking it’s not a VM?

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/CHANGELOG.md

Set to Minimal or higher, currently not support via spoofless at this time
