### ISSUE TITLE
MacBookPro 10,1 : Application crash at launch when using Intel HD4000 GPU

### ISSUE THREAD

**Issue by Ribero** [dortania/OpenCore-Legacy-Patcher#876]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Application like Plex Player ([1.39.1.2763-300bb607](https://downloads.plex.tv/plex-desktop/1.39.1.2763-300bb607/macos/Plex-1.39.1.2763-300bb607-x86_64.zip)) is crashing at every launch. 

I suspected it could be related to the GPU and when disabling the macOS settings in the battery section to disable GPU switching and force the use of the discrete nvidia gpu instead of the hd4000 gpu, application starts normally. 

I found a thread on plex forums about this issue and the fact it could be related to the hd4000 driver version : https://forums.plex.tv/t/plex-app-for-mac-crashes-when-opening-macos-catalina/754562/40

The crash seems to be a mix between the HD4000 driver and security update as macOS Security update 2021-008 (Catalina only) seems to improve the situation.

I understand that this issue is related to third party application and I asked the question in Macrumors forums before but as it used to work on BigSur and OCLP before I have a hope that there is something possible on OCLP side to reproduce or help to solve the issue.

### Any Additional Information

Even if it cannot be solved here, at least, other MacBookPro10,1 users will know it’s a known little drawback of using BigSur on this device.

**Comment by khronokernel** [comment]
With macOS Big Sur, we're using the native HD4000 driver stack. Without doing immense damage to the root volume in Big Sur, unlikely to pursue further. If the issue could be determined exactly, potentially could be implemented via bin patching with Lilu but highly unlikely for anyone internally to dedicate quite a bit of time to this issue.

However feel free to research yourself and provide patch sets, we always appreciate more help with the project.
