### ISSUE TITLE
Bluetooth disabled 

### ISSUE THREAD

**Issue by m1ctk** [dortania/OpenCore-Legacy-Patcher#877]
### Machine Model

Macmini5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

All working brilliantly apart from Bluetooth on my 2012 mac mini. Should it work or is this a known issue ?

**Comment by m1ctk** [comment]
All working fine apart from Bluetooth which I can just can't enable. anyone else or is this a know  issue ?

**Comment by khronokernel** [comment]
Bluetooth is working within OCLP usage (including BCM2070 and BCM20702 chipsets), recommend troubleshooting on forums as this would be considered a local issue

**Comment by m1ctk** [comment]
> Bluetooth is working within OCLP usage (including BCM2070 and BCM20702 chipsets), recommend troubleshooting on forums as this would be considered a local issue

What do you mean within OCLP usage ?
