### ISSUE TITLE
What Options do I choose?

### ISSUE THREAD

**Issue by nicksilverstein** [dortania/OpenCore-Legacy-Patcher#881]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

What Options do I choose with a Mac Pro 5,1 2012 with an AMD R9 280x? I cannot figure this out for the life of me. I have used your patcher on MacBook Pros, MacMinis, and MacBooks but, never a Mac Pro. Can you please help me?

**Comment by Ausdauersportler** [comment]
Hello!

Please use the Discord server mentioned on the Github download page for any user help requests. This is for software development issues, only :-)
