### ISSUE TITLE
MacBook Pro 8,2: can’t login to Big Sur after patching the volume with OCLP

### ISSUE THREAD

**Issue by Mudflapper** [dortania/OpenCore-Legacy-Patcher#882]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I used OCLP to install Big Sur on a MacBook Pro 8,2, 8gb ram, Mercury Electra 500gb SSD. Before installation I partitioned the drive in High Sierra so I could keep that OS for old apps and install Big Sur on its own partition so I could boot from either or continue to use high Sierra if Big Sur didn't work well. It installed perfectly.

I used software update to get Big Sur to the very latest version and that went perfectly as well. I can use Big Sur just fine, but of course the UI is slow because I haven’t patched the startup volume yet. 

Everything was going according to plans until after I patched the startup volume and restarted — now I can’t get past the login. I type in my password then hit return, the screen goes black, then I’m back at the login again.

I’ve wiped the startup volume and started the Big Sur install from scratch 3 times but once I patch the startup volume the same thing happens — I hit return or click the arrow after entering my password and it just reloads the login screen again.

I can boot into High Sierra without issue.

I’m hoping someone has seen this before? I've searched troubleshooting, I've Googled and I've searched Reddit for hours but I'm at a loss.

Thanks in advance.

**Comment by Ausdauersportler** [comment]
Instead of wasting time with searching the net or opening an issue here you should have tried at least to read the OCLP online docs, especially this [section](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#working-around-legacy-acceleration-issues).
If you have issues with using OCLP join the Discord server or read and post on the Macrumors Big Sur or Monterey on legacy hardware threads.

**Comment by khronokernel** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#cannot-login-on-2011-15-and-17-macbook-pros

**Comment by Mudflapper** [comment]
Ugh, I can't believe I missed that. I'm so sorry for bugging you. I'll give it a try tomorrow. I'm sure it will work. Thanks so much and again, apologies.
