### ISSUE TITLE
Monterey ASUS BT-400 (BCM20702A0) bluetooth dongle not working any more

### ISSUE THREAD

**Issue by derelvis** [dortania/OpenCore-Legacy-Patcher#883]
### Machine Model

iMac11,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

First of all: many, many thanks for all the great work!!

I am using an ASUS BT-400 (BCM20702A0) bluetooth dongle for quite a while to connect mouse and keyboard to my 27" iMac11,1. This worked in Catalina and Big Sur but does not work any more since upgraded to Monterey. It still gets listed under USB devices but Bluetooth can not be turned on (disabled and greyed out).
![Kontrollzentrum 2022-01-11 16-35-16](https://user-images.githubusercontent.com/17635497/148972965-7ddb4aec-e7b4-4945-a76f-e3dbe434e948.jpg)

I thought this patch might bring it back working but it did not: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/fa89865552dadef0912583526fa3dd93513dcdab

### Any Additional Information

- this is what I can see under USB-Devices
![image](https://user-images.githubusercontent.com/17635497/148970912-7960672f-5e11-4fa6-b6fa-9ab8df41c920.png)

- and the buildin Bluetooth device is inactive - like it should
![image](https://user-images.githubusercontent.com/17635497/148971105-09e39291-89d2-4db0-a21a-d9226a188eae.png)

- and the output of "kmutil showloaded | grep Brcm" and "kmutil showloaded | grep Bluetooth"
![image](https://user-images.githubusercontent.com/17635497/148971289-bd5468c1-376a-4827-b8b2-6af66ed341ea.png)

I already did some tests with the [BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM/) as well (but not very familiar with it). If I copy BlueToolFixup.kext, BrcmFirmwareRepo.kext, BrcmPatchRAM3.kext into /Library/Extensions like described in the "Mac instructions" for BrcmPatchRAM the situation seems to change somehow. But does still not work (can't turn on bluetooth).

Regarding this post https://github.com/acidanthera/bugtracker/issues/1669#issuecomment-858969935 I can see as well that there are at least these two not there anymore: CSRHIDTransitionDriver.kext, IOBluetoothUSBDFU.kext
But there is also a satement three posts below which states "The Bluetooth implementation in Monterey has changed significantly and no longer fits BrcmPatchRAM framework. It's not enough to just get firmware uploaded and inject a kextless driver for device ID matching."

Maybe it is just a "real mac" issue, because the hackintosh world seems to have a working BT-400 with Monterey 12.0.1
as can bee seen at https://github.com/acidanthera/bugtracker/issues/1821.

If you need any more information or have instructions for me, please let me know. Many thanks in advance!

**Comment by protocold** [comment]
I have confirmed this to be an issue and my machine is MacBookPro8,2

You are correct that the hackintosh world have this working under Monterey.. I also wonder why this wont work with "real mac"

**Comment by khronokernel** [comment]
Not promising much with this build but see if this works:

* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/4945820926/artifacts/143338337
  * Must be signed into Github to download

This build simply forces BlueToolFixup regardless of detected hardware, as the internal BCM2046/BCM2070 may be taking over in macOS.

If this build works, please send the SPUSBDataType.txt generated:

```sh
system_profiler SPUSBDataType > ~/Desktop/SPUSBDataType.txt
```

**Comment by derelvis** [comment]
Thank you very much for taking care of this, @khronokernel. Appreciating your help. Thanks for joining @protocold.
I just tested your build but it seems to not have worked, sorry to say that :( 
Only built and installed Open Core, did not reapply root patch as it only says available patches: Graphics Nvidia Kepler.

I created two logs, one before the test and one after applying the new build (order has changed when I compare them):
[SPUSBDataType_before.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7874856/SPUSBDataType_before.txt)
[SPUSBDataType_after.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7874857/SPUSBDataType_after.txt)

Any further advice or hint? Thanks again!

**Comment by protocold** [comment]
I forgot to ask you... did you edit the plist file in additional to adding BlueToolFixup.kext, BrcmFirmwareRepo.kext, BrcmPatchRAM3.kext into the EFI folder? 

I am also confused of which kext we need to put and load, other than BlueToolFixup.kext.

@khronokernel any idea on exactly which kext that we need for Monterey (and which order we should load it in the plist?

**Comment by derelvis** [comment]
@protocold No, I did not edit a plist. Which one did you change?

**Comment by protocold** [comment]
Of course the opencore config.plist

If I understand correctly, if we were to add new kext into the opencore, we need to edit config.plist to reflect that as well!

https://dortania.github.io/OpenCore-Install-Guide/config.plist/

**Comment by derelvis** [comment]
Hm, I am confused. Does that mean you do not use the OpenCore Legacy Patcher but build your own OpenCore "setup" from that guide?
I thought it would be enough to put the kext files into /Library/Extensions like described here:
https://github.com/acidanthera/BrcmPatchRAM/blob/master/README-Mac.md

**Comment by protocold** [comment]
that's not what i meant.

opencore legacy patcher is obviously using opencore and it come as a set of pre-defined/tested configuration (OCLP's config.plist) and kext for the "real mac". 

Now our USB dongle is not part of "real mac", if we were to customize anything on top of OCLP, we should go into its config.plist and make the changes.

**Comment by khronokernel** [comment]
Validated with other users that some 3rd party Bluetooth 4.0 dongles seem to work with OCLP. With the mixed results and no local hardware for testing, going to consider this a "will not prioritize" as there are many other parts of OCLP I need to focus on.

Additionally parsing through Acidanthera's BlueTool issues as well as other forums, Hackintosh users still experience issues regardless. I would highly recommend troubleshooting on forums, and if you're able to resolve please PR. We always greatly appreciate additional aid with OCLP
