### ISSUE TITLE
MacPro5,1 stock keeps getting stuck at apfs_module_start:2568: load: com.apple.filesystem.apfs, v1933.61.1, apfs-1933.61.1

### ISSUE THREAD

**Issue by aig757** [dortania/OpenCore-Legacy-Patcher#884]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I changed the original stock hard drives and proceeded in re-installing BigSur however using the same installer with the same settings the system stops at the following line:

apfs_module_start:2568: load: com.apple.filesystems.apfs, v1933.61.1, apfs-1933.61.1, 2021/11/30

at first I believed it was the wireless or BT however I isolated the items and still cant proceed installing

HELP!!!

**Comment by khronokernel** [comment]
Use forums for troubleshooting
