### ISSUE TITLE
iMac 11,2 Graphical Glitches

### ISSUE THREAD

**Issue by PikachuFanCoder** [dortania/OpenCore-Legacy-Patcher#885]
### Machine Model

iMac11,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

When I login at first everything is fine, but then. The backgrounds of apps and drop down menus have like a painting glitch when the mouse moves around within it. Then when it sleeps then I wake it, every image like the password box glitches out and once I log back in, the mouse leaves a glitchy trail. Also this is after I used the graphics acceleration.

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by hauzmann** [comment]
> ### Machine Model
> iMac11,2
> 
> ### Application Version
> Latest Release
> 
> ### Application Variant
> TUI (Text User Interface)
> 
> ### Have you verified whether this issue has been opened before? If no, your issue will be closed
> true
> 
> ### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages
> true
> 
> ### Is this issue with a 3rd party application?
> false
> 
> ### What versions of macOS are you seeing the problem on?
> macOS 12, Monterey, macOS 11, Big Sur
> 
> ### Where does this issue happen?
> Within macOS (Before Logging in), Within macOS (After Logging in)
> 
> ### What is the Issue?
> When I login at first everything is fine, but then. The backgrounds of apps and drop down menus have like a painting glitch when the mouse moves around within it. Then when it sleeps then I wake it, every image like the password box glitches out and once I log back in, the mouse leaves a glitchy trail. Also this is after I used the graphics acceleration.
> 
> ### Any Additional Information
> _No response_

I had the same problems with my iMac12,1.

Running this command totally solved this for me:
defaults write -g ASB_BlurBeta -bool true

No glitches al all and beautiful blur background.
