### ISSUE TITLE
MacBook not booting up to login screen with Monterey 12.2 Beta 2

### ISSUE THREAD

**Issue by TEJLJR** [dortania/OpenCore-Legacy-Patcher#887]
### Machine Model

MacBookPro7,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

After installing macOS 12.2 Beta 2 via OTA, I repatched my machine and rebooted. But it would get stuck at 40% and just sit there. The login screen would not show up. Rebooting multiple times did not hrlp.

**Comment by khronokernel** [comment]
We already validated 12.2 Beta 2 with 0.3.4:
![Screen_Shot_2022-01-14_at_8 03 45_PM](https://user-images.githubusercontent.com/48863253/149826111-becbc2f0-567a-4a6a-abd5-463b5fcb4805.png)

You shouldn't be running Betas with release builds especially with regards to non-Metal acceleration patches, [running from source](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md) with 0.3.4 has been validated to work for several users.
