### ISSUE TITLE
The display brightness does not work on Windows 10 dual boot with Monterey with OCLP 0.3.3

### ISSUE THREAD

**Issue by winphil** [dortania/OpenCore-Legacy-Patcher#888]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

The display brightness does not work on Windows 10 dual boot with Monterey. It worked with Big Sur but when I upgraded to Monterey those keys stopped working in Windows 10. I followed Mr. Mackintosh video and everything else is working fine except the screen brilliance. There's no way to adjust the screen brilliance except I boot back into Monterey and adjust the screen brilliance there then reboot into windows 10. So every time I want to adjust the brilliance in windows 10 I have to reboot into Monterey, adjust it there then booth back into Windows 10.

**Comment by khronokernel** [comment]
I assume you've verified that booting Windows 10 without OpenCore does not replicate this issue?

**Comment by winphil** [comment]
> On Jan 17, 2022, at 12:30 PM, Mykola Grymalyuk ***@***.***> wrote:
> 
> I assume you've verified that booting Windows 10 without OpenCore does not replicate this issue?
> 
> 

Yes sir, when I was on Big Sur without OCLP it worked fine. When I updated to Monterey using OCLP this problem started. I went back to Big Sur and it worked fine, as soon as I upgraded to Monterey the problem starts.

Rgds

**Comment by khronokernel** [comment]
So Monterey is causing this issue, not OpenCore? If you boot from a clean state (completely shut off), manually select Windows with Option (not OpenCore) and boot exclusively that, do you continue to have issues?

**Comment by winphil** [comment]
Sent from Mail for Windows From: Mykola GrymalyukSent: Monday, January 17, 2022 1:46 PMTo: dortania/OpenCore-Legacy-PatcherCc: winphil; AuthorSubject: Re: [dortania/OpenCore-Legacy-Patcher] The display brightness does not work on Windows 10 dual boot with Monterey with OCLP 0.3.3 (Issue #888) So Monterey is causing this issue, not OpenCore? If you boot from a clean state (completely shut off), manually select Windows with Option (not OpenCore) and boot exclusively that, do you continue to have issues?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>I cannot get to boot directly into windows 10 without OCLP, the computer boots to OCLP first then I can select either windows 10 or macos Monterey. Even when I hold down option it still boot into OCLP. Rgds

**Comment by MartinKuhl** [comment]
You can boot directly to Win10 if you press ALT while the boot sound is playing. 
I can confirm this issue.
I have MacBookPro11,3 too and the issue is only present while I am booting Windows by OCLP. 
If I boot Windows directly, I am able to adjust the screen brightness. Btw. I am using Windows 11.

**Comment by khronokernel** [comment]
Can you try to disable the Windows GMUX option in Patcher Settings and rebuild OpenCore?
* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/4977711152/artifacts/145296414
  * Need to be signed into Github to download

Settings -> Developer Settings -> Windows GMUX

**Comment by winphil** [comment]
> On Jan 18, 2022, at 5:31 PM, Mykola Grymalyuk ***@***.***> wrote:
> 
> Can you try to disable the Windows GMUX option in Patcher Settings and rebuild OpenCore?

Hello Mykola & Martin, I disabled the Windows GMUX option in in Patcher Settings and rebuilt OpenCore and the issue has been fixed. Thank you very much for your timely response.

Rgds

**Comment by MartinKuhl** [comment]
For me it's not working. I changed the settings and rebuild OpenCore but after a reboot the changed option is changed back to true. In general I like the feature of switching which GPU has to be used. I there another option the enable the brightness keys instead of these?

**Comment by khronokernel** [comment]
> For me it's not working. I changed the settings and rebuild OpenCore but after a reboot the changed option is changed back to true

OCLP settings do not reflect the current booted settings, they reflect what will be built.
> I there another option the enable the brightness keys instead of these?

Feel free to research yourself, but we're primarily a macOS patcher focused project. We don't have affected hardware locally, nor are we too interested in shifting development time away from other issues and into Windows

This issue will be closed once troubleshooting page has been updated
