### ISSUE TITLE
Can't launch Chrome and other third party apps, crashing at first start.

### ISSUE THREAD

**Issue by DA5EMC** [dortania/OpenCore-Legacy-Patcher#889]
### Machine Model

MacBook5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 10.15, Catalina

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Use v0.7.1 OC whiteout this problem, but at all other releases after some third part apps don't start and get to crash. Direct after the crash I can run the app after starting it again. DosDude1 fix this problem at his patcher, but I don't know more. Hope you can help and fix this issue in future, thank at all.

**Comment by khronokernel** [comment]
> Currently OpenCore Legacy Patcher officially supports patching to run macOS Big Sur and Monterey installs. For older OSes, OpenCore may function however support is currently not provided from Dortania.

We don't support Mojave or Catalina for public use. Use dosdude1's patcher as it was developed with Catalina in mind
