### ISSUE TITLE
Add Backlight patches for modded Nvidia GPUs in iMac10,x-12,x

### ISSUE THREAD

**Issue by grzegorz914** [dortania/Opencore-Legacy-Patcher#89]
Hi

I have modified iMac 11,3 with Nvidia GTX765 (modded flash) and BCM94360CD WiFi/BT, this hardware are not recognized automatically by the patcher, will install and enable WiFi.kext and not install AppleBacklighFixup.kext and not add needed patche to config.plist, permanently enable Nvidia and WiFi in patcher settings not solve this problem.

After put manually BacklightControl.kext plus enable it and Disable WiFi.kext and add this to DeviceProperties config.plist the BackLight control start working on this iMac.

```
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>@0,backlight-control</key>
				<data>AQAAAA==</data>
				<key>@0,built-in</key>
				<data>AQAAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>@0,backlight-control</key>
				<data>AQAAAA==</data>
				<key>@0,built-in</key>
				<data>AQAAAA==</data>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>
```

**Comment by khronokernel** [comment]
> this hardware are not recognized automatically by the patcher

I assume you're booting with OpenCore already correct? If ExposeSensitiveData is set too low it's not possible for us to detect what the original Mac model was and enable the additional patches of the model. So when you manually select iMac11,3 in the patcher, the hardware detection algorithms is not used. If this the case?

If so, then I can add a toggle for the Nvidia patching logic we have here: 

https://github.com/dortania/Opencore-Legacy-Patcher/blob/main/Resources/build.py#L181-L193

**Comment by grzegorz914** [comment]
Yes,

I boot from OC and and is not possible to create correct setup with modified hardware even if we enable in patcher settings option “Assume Metal GPU Always”, “Assume Upgraded WiFi Always”.

Optimal will by add possibility to select which hardware is modified before start build OC.

**Comment by grzegorz914** [comment]
with OCLP 0.22 same problem as reported before

**Comment by khronokernel** [comment]
Please test 0.0.23, previous versions had a typo with DeviceProperty pathing(`PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)` vs `PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)`)
Resolved here a few days ago:
https://github.com/dortania/OpenCore-Legacy-Patcher/commit/bdc8c2a4fc38cac8ddf9e7f95c72e6b791a791ef

Latest build:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2519367622/artifacts/54553850

**Comment by grzegorz914** [comment]
0.023 and 0.1 not work

the part is not added to config.plist, after add this manually all working correct:

```
<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>@0,backlight-control</key>
				<data>AQAAAA==</data>
				<key>@0,built-in</key>
				<data>AQAAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>@0,backlight-control</key>
				<data>AQAAAA==</data>
				<key>@0,built-in</key>
				<data>AQAAAA==</data>
			</dict>
```
