### ISSUE TITLE
unexpected black screens and won't shutdown nor reboot only force shutdown macOS 12.1

### ISSUE THREAD

**Issue by leonardojat** [dortania/OpenCore-Legacy-Patcher#890]
### Machine Model

MacBookPro11,2

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

keep getting unexpected random reboots and black screens on mac os 12.1 on my MacBook pro late 2013 retina which is not an isolated case because a came across a user of open-core with same model computer and OS having the same issue

**Comment by khronokernel** [comment]
Please use forums for troubleshooting

**Comment by dhairyasenjaliya** [comment]
how you solve?
