### ISSUE TITLE
macOS Installer cannot be found by the EFI when on an external drive (via an update)

### ISSUE THREAD

**Issue by mat1696** [dortania/OpenCore-Legacy-Patcher#894]
### Machine Model

iMac14,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hi,
I don't know if this is related to issue #878 (tried to figure it out to not make a duplicate if that's a know limitation, but I'm not a developer, so quite difficult for me to understand exactly what's going on), but I'm currently testing macOS Monterey on my iMac 14,3. It is installed on an external ssd and works well. The problem is: I cannot update this version through my iMac:
I go to System Preferences, the download starts, prepares, then the Mac reboots and then things get complicated. If I hold the option key down, I see the "macOS Installer" volume. However, when I select the EFI Boot to use OCLP I cannot see this macOS Installer anymore (even if I press the space bar), so no possibility to install any update... I don't know it that's a known issue/limitation (wasn't able to find out) or if that could get fixed in the future?
I currently have Big Sur on my internal fusion drive (so that it works more "natively" without post-install patch) and wanted to test a little more Monterey before installing it on my main drive...

Thanks you in advance :=)

**Comment by khronokernel** [comment]
Use forums for troubleshooting
