### ISSUE TITLE
MacPro5,1 don't load OpenCore with Radeon Vega 54

### ISSUE THREAD

**Issue by ebauger** [dortania/OpenCore-Legacy-Patcher#895]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true, false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

Try with Install macOS 12.1 too.

I tried to boot with the default build and install on the usb drive or others partitions.

Try reboot on USB drive with the Option key and no boot at all on a Mojave partition previously work.

- I disconnected all the SATA and others PCI(E) card;
- put a new SATA SSD Drive for the clean install on the first SATA;
- One Radeon RX Vega 64 on the first PCIe Slot;

Seem the OpenCore Build don't load with the Vega 64

Any others solutions?

### Any Additional Information

Dump Hardware Infos from the OCLP 0.3.3
```
Computer(real_model='MacPro5,1', real_board_id='Mac-F221BEC8', reported_model='MacPro5,1',
reported_board_id='Mac-F221BEC8', gpus=[AMD(vendor_id=4098, device_id=26751,
class_code=196608, name='display', model='Radeon RX Vega 64', acpi_path=None,
pci_path='PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)', arch=<Archs.Vega:
'Vega'>)], igpu=None, dgpu=None, storage=[SATAController(vendor_id=32902, device_id=14882,
class_code=67073, name='SATA', model=None,
acpi_path='IOACPIPlane:/_SB/PCI0@0/SATA@1f0002', pci_path='PciRoot(0x0)/Pci(0x1f,0x2)')],
wifi=Broadcom(vendor_id=5348, device_id=17195, class_code=163840, name='ARPT', model=None,
acpi_path='IOACPIPlane:/_SB/PCI0@0/RP06@1c0005/ARPT@0',
pci_path='PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)', country_code='X0', chipset=
<Chipsets.AirPortBrcm4331: 'AirPortBrcm4331 supported'>), cpu=CPU(name='Intel(R) Xeon(R)
CPU X5650 @ 2.67GHz', flags=['FPU', 'VME', 'DE', 'PSE', 'TSC', 'MSR', 'PAE', 'MCE', 'CX8',
'APIC', 'SEP', 'MTRR', 'PGE', 'MCA', 'CMOV', 'PAT', 'PSE36', 'CLFSH', 'DS', 'ACPI', 'MMX', 'FXSR', 'SSE',
'SSE2', 'SS', 'HTT', 'TM', 'PBE', 'SSE3', 'PCLMULQDQ', 'DTES64', 'MON', 'DSCPL', 'VMX', 'SMX', 'EST',
'TM2', 'SSSE3', 'CX16', 'TPR', 'PDCM', 'SSE4.1', 'SSE4.2', 'POPCNT', 'AES', 'PCID']),
oclp_version=None, opencore_version=None, bluetooth_chipset='BRCM2046 Hub',
third_party_sata_ssd=True)
```

**Comment by khronokernel** [comment]
Use forums for troubleshooting. Note that OCLP on Mac Pros won't boot Mojave with SMBIOS spoofing (MacPro7,1 spoofed SMBIOS requires Catalina or newer)
