### ISSUE TITLE
problems with keyboard backlight 

### ISSUE THREAD

**Issue by Schmagauke** [dortania/OpenCore-Legacy-Patcher#896]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

keyboard backlight doesn't work anymore - tryed several things to fix like SMC Reset or something else - but doesn't fix this problem.
F5/F6 without function (just an icon "(-)" shown)

### Any Additional Information

MBP 15" late 2011, 16 GB RAM

**Comment by educovas** [comment]
https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#keyboard-backlight-broken
