### ISSUE TITLE
MacBookPro10.2 freezing sometimes with Monteray

### ISSUE THREAD

**Issue by DerWebschreiner** [dortania/OpenCore-Legacy-Patcher#897]
### Machine Model

MacBookPro10,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

The MacBook has sometimes a blck screen when opening the display. The display backlight is working but the screen stays black. I have to force a reboot by holding power button. After first reboot it stocks on boot at about 30%. Ich have to shutdown the MacBook und reboot by holding ALT key. After that the MacBook starts normal.

**Comment by dkrizic** [comment]
I have an old MacBook (white, plastic) here. It freezes constantly with any OS and the reason is: Overheating, because the thermal system does not work anymore. Maybe you have the same problem.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
