### ISSUE TITLE
stuck after migration assistant

### ISSUE THREAD

**Issue by TabSel** [dortania/OpenCore-Legacy-Patcher#901]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I installed macOS 12.1 and ran the post install to patch GPU. Everything went fine, I was able to run the Apple Migration Assistant in order to “clone” my 2018 MacBookPro running Monterey.

however, after Migration Assistant, the system doesn’t boot anymore - panic: kext log loading fileset KC(s). When booting in safe mode, I get a Migration Assistant Popup saying that the system needs to restart for completion. No way to exit and run OCLP’s post install, so I’m stuck now.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
