### ISSUE TITLE
We Should Show Beta Downloads with Warnings.

### ISSUE THREAD

**Issue by owenzhao** [dortania/OpenCore-Legacy-Patcher#902]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I just tried the new "Create macOS Installer". When choosing "Download macOS Installer", below menu was shown.

<img width="462" alt="sc" src="https://user-images.githubusercontent.com/2182896/150660369-c198a98c-0825-4bc4-a65a-db1eacf5c58b.png">

However, the last version macOS 12.2 (21D5039d) was not the one I wanted. It was 12.2 beta 2. The latest should be 12.2(21D48). 

I knew that I must installed a profile to get the latest version.  However, I suggested to give some warnings when downloading a beta OS. As for me, I would rather to wait for some days for the open download.

**Comment by khronokernel** [comment]
I had believed I resolved this earlier today, apparently had not pushed it from my machine:
* https://github.com/dortania/OpenCore-Legacy-Patcher/commit/33eef9b87f3fcce75e597eadf34cdda064200ae7
