### ISSUE TITLE
Booting from "Kanex Thunderbolt Gigabit Ethernet + USB 3.0 Adapter" works, with help

### ISSUE THREAD

**Issue by RedBearAK** [dortania/OpenCore-Legacy-Patcher#903]
### Machine Model

MacBookPro8,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

This isn't actually a bug report, technically. I just want to document the fact that it is possible to "boot" from a macOS system drive attached to a Kanex Thunderbolt Gigabit Ethernet + USB 3.0 Adapter. The only catch is that you need some other USB device, or perhaps even a FireWire device, with the OCLP EFI boot folder to boot into the drive selector screen. But from then on it works fine to have the macOS system drive attached to the Thunderbold to USB 3.0 adapter. 

I discovered this works after accidentally leaving the drive attached to the Thunderbolt adapter while installing from another USB drive that was directly attached to the Mac (MacBookPro8,3 - 2011 17-inch MBP with Thunderbolt 1 port). This model has only USB 2.0 ports without the Thunderbolt to USB 3.0 adapter. 

Of course I was a bit confused that I kept having to intervene at the boot picker screen and choose "EFI boot" every time it would reboot. I got through the whole install and then installed OCLP on the new drive before removing the installer USB and realizing the drive attached to the Thunderbolt adapter wouldn't show up at the boot picker screen by itself (which is normal, Thunderbolt-attached drives, or at least drives attached to Thunderbolt adapters, are not officially supported as boot drives by macOS). But once you use the "EFI boot" from another directly-attached USB (OCLP) boot device, you can then pick the drive attached to the Thunderbolt adapter and run macOS from it. 

I don't know how widely known it is that this sort of thing will work. But it's pretty neat. 

I also can't say for sure if it really makes that much of a difference, even if the external drive is an SSD. Right now the drive I'm using is just a 2.5-inch SATA drive, so its max speed is barely any faster than USB 2.0 can theoretically handle. But an NVMe m.2 drive in a USB 3.1 enclosure might be able to have significantly better performance while attached to the Thunderbolt USB 3.0 adapter. I may try it and come back with an update.

**Comment by khronokernel** [comment]
Seems you've found by accident one of the new features in OCLP 0.4.1 ;p
> Add XHCI Boot Support to pre-UEFI 2.0 Macs
* <https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/CHANGELOG.md>

OCLP will automagically detect whether there's any XHCI (USB 3.0) controllers present during the build, and thus add the appropriate firmware drivers into the configuration allowing for USB 3.0 support in UEFI. And as you noticed, this does require OCLP to be on a native volume to load in first.

There are other similar settings in OCLP like NVMe boot for system not natively supporting NVMe in the firmware, as well as FireWire boot (Apple disabled support on Catalina and newer):

<img width="362" alt="Screen Shot 2022-01-22 at 8 19 35 PM" src="https://user-images.githubusercontent.com/48863253/150663463-34282bba-272a-4e6a-9c17-aec106964fb0.png">
