### ISSUE TITLE
Bluetooth Mouse not working after wake from sleep (5k iMac late 2014)

### ISSUE THREAD

**Issue by kolbicz** [dortania/OpenCore-Legacy-Patcher#904]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

i disabled hybernation mode because it caused issues in my case and im aware of this issue here: https://github.com/dortania/Opencore-Legacy-Patcher/issues/72 and i used sudo pmset -a hibernatemode 0 which most of the time works fine.

but sometimes when the iMac wakes from sleep, it shows me the disk selector screen and seems to reboot, but it actually doesn't do a full boot. sometimes i get then a glitched logon screen but this resolves then after some seconds.

however - sometimes when i logon then, my mouse is missing (magic mouse).

i discovered that when i plug an usb mouse, i get a cursor back and can use the mac. i also discovered then, that disabling and re-enabling bluetooth brings my magic mouse back. 

as a workaround i use blueutil from brew and reenable bluetooth over terminal: blueutil -p 0 and blueutil -p 1

are there any logs than i can provide to analyse this issue further? thanks

**Comment by khronokernel** [comment]
Use forums for troubleshooting
