### ISSUE TITLE
Can't install post volume patch, MBP late 2011

### ISSUE THREAD

**Issue by broli95** [dortania/OpenCore-Legacy-Patcher#905]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Can't install the post volume patches on my MBP late 2011, I installed Monterey 12.2 from the GUI app, disabled dGPU to avoid issues when trying to login and tried to install the patches right after but I can't, I'll provide a screenshot with the error.
![Screenshot 2022-01-23 at 21 12 12](https://user-images.githubusercontent.com/22918304/150696296-d45d5125-df33-4b09-84fe-467131b000f4.png)

**Comment by khronokernel** [comment]
Is this replicable with macOS 12.1? Additionally could you provide the full output of the patch?

**Comment by broli95** [comment]
> Is this replicable with macOS 12.1? Additionally could you provide the full output of the patch?

I installed directly from High Sierra to Monterey 12.2 so I don't know if it's replicable. Also I'll provide the full output later but with the TUI app since I don't know how to expand the GUI window.

**Comment by khronokernel** [comment]
Its just a text window, just copy paste it

**Comment by broli95** [comment]
> Its just a text window, just copy paste it

I tried command+c before taking a screenshot but it didn't do anything, that's why I was saying that I don't know how to expand it

**Comment by khronokernel** [comment]
Validated my MacBookPro8,2 (faulty dGPU as well) with a clean installation of 12.2, no issues with a normal 0.4.1 installation. 

I would recommend doing a clean installation of 12.1 (as that's the current official release), additionally if you can try to avoid having High Sierra and Big Sur/Monterey on the same drive. High Sierra is known to corrupt APFS snapshots and .im4m signatures in snapshot based OSes.

Otherwise best to troubleshoot further on forums.

| Root Patching | Installed |
| :--- | :--- |
| ![Screen Shot 2022-01-23 at 1 38 28 PM](https://user-images.githubusercontent.com/48863253/150697336-e8e6deae-c34f-4380-8f8f-ef8db5e2908e.png) | ![Screen Shot 2022-01-23 at 1 40 32 PM](https://user-images.githubusercontent.com/48863253/150697340-f35aa79f-7337-450d-9744-9dda941fa4dd.png) |

**Comment by khronokernel** [comment]
> I tried command+c before taking a screenshot but it didn't do anything, that's why I was saying that I don't know how to expand it

Also regarding this, you press Cmd + A to select all in the text window

**Comment by broli95** [comment]
> > I tried command+c before taking a screenshot but it didn't do anything, that's why I was saying that I don't know how to expand it
> 
> Also regarding this, you press Cmd + A to select all in the text window

Sorry I didn't specify, I selected all text with CMD+A and then I tried copying with CMD+C but as I said nothing happened.
Anyway one more question, if I install Monterey 12.1 and I want to update to 12.2 can I do it from the preferences menu? And if I can, do I have to install the post volume patch again? I'm asking because I installed Monterey 12.0 a few weeks ago, updated to 12.1 from the settings but the video driver stopped working, I tried installing the post volume patch again (Opencore legacy 0.3.3) but my Mac got corrupted and had to wipe everything.

**Comment by broli95** [comment]
Btw here's the full output taken from the TUI:

################################
# Downloading: 12-Monterey.zip #
################################

169.6MB Downloaded of 169.6MB (100.0%)
Average Download Speed: 37.09 MB/s
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/private/var/folders/9m/jksdnlld75x6g1yzqp9svbzw0000gn/T/_MEIxHM1fH/payloads
- Found Root Volume at: disk2s5
- Root Volume is already mounted
- Running patches for MacBookPro8,2
- Installing legacy TeraScale 2 Patches
- Detected supported OS, installing Acceleration Patches
- Installing basic TeraScale 2 Framebuffer Kext patches for generic OS
- Found conflicting kext, Deleting Root Volume's AMD2400Controller.kext
Password:
- Adding AMD2400Controller.kext
- Found conflicting kext, Deleting Root Volume's AMD2600Controller.kext
- Adding AMD2600Controller.kext
- Found conflicting kext, Deleting Root Volume's AMD3800Controller.kext
- Adding AMD3800Controller.kext
- Found conflicting kext, Deleting Root Volume's AMD4600Controller.kext
- Adding AMD4600Controller.kext
- Found conflicting kext, Deleting Root Volume's AMD4800Controller.kext
- Adding AMD4800Controller.kext
- Found conflicting kext, Deleting Root Volume's AMD5000Controller.kext
- Adding AMD5000Controller.kext
- Found conflicting kext, Deleting Root Volume's AMD6000Controller.kext
- Adding AMD6000Controller.kext
- Found conflicting kext, Deleting Root Volume's AMDLegacyFramebuffer.kext
- Adding AMDLegacyFramebuffer.kext
- Found conflicting kext, Deleting Root Volume's AMDLegacySupport.kext
- Adding AMDLegacySupport.kext
- Found conflicting kext, Deleting Root Volume's AMDRadeonVADriver.bundle
- Adding AMDRadeonVADriver.bundle
- Found conflicting kext, Deleting Root Volume's AMDRadeonVADriver2.bundle
- Adding AMDRadeonVADriver2.bundle
- Found conflicting kext, Deleting Root Volume's AMDShared.bundle
- Adding AMDShared.bundle
- Found conflicting kext, Deleting Root Volume's ATIRadeonX2000.kext
- Adding ATIRadeonX2000.kext
- Found conflicting kext, Deleting Root Volume's ATIRadeonX2000GA.plugin
- Adding ATIRadeonX2000GA.plugin
- Found conflicting kext, Deleting Root Volume's ATIRadeonX2000GLDriver.bundle
- Adding ATIRadeonX2000GLDriver.bundle
- Found conflicting kext, Deleting Root Volume's ATIRadeonX2000VADriver.bundle
- Adding ATIRadeonX2000VADriver.bundle
- Installing legacy Sandy Bridge Patches
- Detected supported OS, installing Acceleration Patches
- Installing Sandy Bridge Acceleration Kext patches for Big Sur/Monterey
- Couldn't find AMDRadeonX4000.kext, skipping
- Couldn't find AMDRadeonX4000HWServices.kext, skipping
- Couldn't find AMDRadeonX5000.kext, skipping
- Couldn't find AMDRadeonX5000HWServices.kext, skipping
- Couldn't find AMDRadeonX6000.kext, skipping
- Couldn't find AMDRadeonX6000Framebuffer.kext, skipping
- Couldn't find AMDRadeonX6000HWServices.kext, skipping
- Couldn't find AppleIntelBDWGraphics.kext, skipping
- Couldn't find AppleIntelBDWGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelCFLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelHD4000Graphics.kext, skipping
- Couldn't find AppleIntelHD5000Graphics.kext, skipping
- Couldn't find AppleIntelICLGraphics.kext, skipping
- Couldn't find AppleIntelICLLPGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelKBLGraphics.kext, skipping
- Couldn't find AppleIntelKBLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelSKLGraphics.kext, skipping
- Couldn't find AppleIntelSKLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelFramebufferAzul.kext, skipping
- Couldn't find AppleIntelFramebufferCapri.kext, skipping
- Couldn't find AppleParavirtGPU.kext, skipping
- Couldn't find GeForce.kext, skipping
- Deleting IOAcceleratorFamily2.kext
- Couldn't find IOGPUFamily.kext, skipping
- Installing General Acceleration Kext patches for Big Sur/Monterey
- Adding IOAcceleratorFamily2.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000Graphics.kext
- Adding AppleIntelHD3000Graphics.kext
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsGA.plugin
- Adding AppleIntelHD3000GraphicsGA.plugin
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsGLDriver.bundle
- Adding AppleIntelHD3000GraphicsGLDriver.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelHD3000GraphicsVADriver.bundle
- Adding AppleIntelHD3000GraphicsVADriver.bundle
- Found conflicting kext, Deleting Root Volume's AppleIntelSNBVA.bundle
- Adding AppleIntelSNBVA.bundle
- Using stock AppleIntelSNBGraphicsFB
- Adding AppleIntelSNBGraphicsFB.kext
- Merging AppleGVA Hardware Accel patches for non-Metal
- Merging DropboxHack SkyLightPlugins
- Merging general legacy Frameworks
- Merging Monterey WebKit patch
- Merging general legacy PrivateFrameworks
- Rebuilding Kernel Cache (This may take some time)
- Unable to build new kernel cache

Please report this to Github
Reason for Patch Failure:
Error Domain=KMErrorDomain Code=71 "Unable to resolve dependencies: 'com.apple.driver.AppleBluetoothMultitouch' names a dependency on 'com.apple.driver.IOBluetoothHIDDriver', which was not found." UserInfo={NSLocalizedDescription=Unable to resolve dependencies: 'com.apple.driver.AppleBluetoothMultitouch' names a dependency on 'com.apple.driver.IOBluetoothHIDDriver', which was not found.}
checking collections...
Warning: com.apple.driver.KextExcludeList was not found!
updated kernel binaries (macho-o UUID changed from CE183058-7EF1-399E-9CFE-1417E98BCB84 to 93729D02-FE6F-355B-BA76-BA930AA7103F)
rebuilding release collections: boot, system
rebuilding release collections:
	boot kernel collection
	system kext collection
failed to build release collection:
	Unable to resolve dependencies: 'com.apple.driver.AppleBluetoothMultitouch' names a dependency on 'com.apple.driver.IOBluetoothHIDDriver', which was not found.



Please reboot the machine to avoid potential issues rerunning the patcher
Press [ENTER] to continue

**Comment by khronokernel** [comment]
The 2 errors posted are completely different regarding dependancy issues, your installation is botched.
>  if I install Monterey 12.1 and I want to update to 12.2 can I do it from the preferences menu?

Yes native OS updates are supported. Install 12.1 and update to 12.2 as you see fit

**Comment by broli95** [comment]
> The 2 errors posted are completely different regarding dependancy issues, your installation is botched.
> 
> > if I install Monterey 12.1 and I want to update to 12.2 can I do it from the preferences menu?
> 
> Yes native OS updates are supported. Install 12.1 and update to 12.2 as you see fit

Ok so this is what I did:
1) Downloaded and installed the macos installer from the gui app on an external hdd drive
2) installed oclp on it
3) started the installation by launching the efi partition of the hdd drive
4) installed oclp on the internal hdd
5) disable dGPU
6) tried to install the post volume patch right after

Did I do anything wrong?

**Comment by broli95** [comment]
Little update: I had an update available in the preferences menu, tried installing the post volume right after and it worked! Apparently I had a RC version installed.
