### ISSUE TITLE
Waiting for remote debugger connection - on cold power cycle (all ok on reboot)

### ISSUE THREAD

**Issue by timboo7** [dortania/OpenCore-Legacy-Patcher#906]
### Machine Model

iMac14,2

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

![IMG_3025](https://user-images.githubusercontent.com/97058166/150755521-dda8e048-76f2-4a65-86be-c6e2459159b0.jpeg)
When powering down the iMac & unplugging the power cable, the iMac fails to boot - see attached image.  This also happened on 3.3 TUI. If I perform a reboot all works ok.

**Comment by khronokernel** [comment]
Looks to be an issue with APFS rooting, either hardware is slowly failing or simply a macOS bug. Seeing as hardware state is affected (ie. reboot has a different effect), it's safe to assume the boot drive is having issues

Use forums for further troubleshooting

**Comment by timboo7** [comment]
I have more information - the issue does not occur in Catalina. The problem seem to occurs after installing video drivers
