### ISSUE TITLE
Hide OpenCore Picker on 0.4.1

### ISSUE THREAD

**Issue by ramonenghaw** [dortania/OpenCore-Legacy-Patcher#907]
### Machine Model

iMac10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hello, in previous versions of opencore it was possible to hide the Opencore boot screen, in version 0.4.1 I can't find the option "Hide OpenCore Picker", what happened?Please clearly explain the issue

**Comment by Ausdauersportler** [comment]
Try searching the setting, again! 
This tool is meant to report serious malfunctions of the software, not of the ....

**Comment by khronokernel** [comment]
Please don't abuse Github issues unless for legitimate issues with the software. We have a discord server for this very reason...
<img width="362" alt="Screen Shot 2022-01-24 at 5 32 47 PM" src="https://user-images.githubusercontent.com/48863253/150888239-259d4035-a6f8-4b83-9da2-acc6c7075bbc.png">
