### ISSUE TITLE
Audio jack is not working

### ISSUE THREAD

**Issue by armanbarsam** [dortania/OpenCore-Legacy-Patcher#908]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

The audio jack is not working.
even after plugging the audio jack, audio is playing from speakers.

**Comment by khronokernel** [comment]
Validated 3.5mm jack detection is functioning correctly in Monterey on MacBookPro8,x. Use forums to troubleshoot

![Screen Shot 2022-01-25 at 11 39 18 AM](https://user-images.githubusercontent.com/48863253/151038693-aa94fff1-3879-411f-bc68-9f603b33a404.png)
