### ISSUE TITLE
Blank selection for Existing Installers Dialogue

### ISSUE THREAD

**Issue by nebosphere19** [dortania/OpenCore-Legacy-Patcher#909]
### Machine Model

MacBook5,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Just getting started and trying to select the installer that the Patcher downloaded to my Applications folder. The dialogue box, where it should be showing the Big Sur installer I selected in the previous step, is blank! 
![Screen Shot 2022-01-25 at 11 33 49 AM](https://user-images.githubusercontent.com/79610240/151018869-e76f9ea0-b746-4e27-b291-ce5ea2790fa2.png)

**Comment by nebosphere19** [comment]
![Screen Shot 2022-01-25 at 11 34 50 AM](https://user-images.githubusercontent.com/79610240/151019045-6ecd618b-1d6a-4772-97d9-438d729018c1.png)

**Comment by khronokernel** [comment]
Can you try this with the TUI? Should report more debug info regarding how it failed to parse installer info

**Comment by nebosphere19** [comment]
Sure, here's the output:

> Select an option: 2
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 6, in <module>
  File "main.py", line 22, in __init__
  File "main.py", line 97, in main_menu
  File "utilities.py", line 524, in start
  File "cli_menu.py", line 1239, in download_macOS
  File "cli_menu.py", line 1278, in find_local_installer
  File "installer.py", line 15, in list_local_macOS_installers
  File "pathlib.py", line 1414, in exists
  File "pathlib.py", line 1222, in stat
PermissionError: [Errno 13] Permission denied: '/Applications/StartLauncher.app/Contents/Resources/createinstallmedia'
[3132] Failed to execute script 'OpenCore-Patcher' due to unhandled exception!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...27 completed.

[Process completed]

**Comment by khronokernel** [comment]
Hm might I ask what `StartLauncher.app` is? Quite strange it's using the exact pathing as a macOS installer, as well as throwing a permission error (we never start the binaries, just check if they exist):
<https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/resources/installer.py#L7-L35>

Should be fairly simple to resolve, just strange situation I wouldn't expect. Will send a build here for you to verify shortly

**Comment by nebosphere19** [comment]
ok - thanks. Yeah, very weird. I actually added permissions to everything in that app, and then it started throwing similar errors about a file in Appplications/Xerox/.... added permissions to that too, and now I get the list. SO WEIRD.

**Comment by khronokernel** [comment]
This build should resolve that strange issue:
* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/5058729470/artifacts/150061502

You'll need to be signed into GitHub to download

**Comment by nebosphere19** [comment]
Thank you!
