### ISSUE TITLE
ASUS BT-400 Continuity (Request)

### ISSUE THREAD

**Issue by Techgeek2011** [dortania/OpenCore-Legacy-Patcher#910]
### Machine Model

MacBook5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Hi, I am a very happy OpenCore Legacy Patcher user, but I do have a request:

Please make the post install patch automatically enable continuity if someone has a Bluetooth 4.0 dongle. 

Thanks In advance 

Anonymus

**Comment by khronokernel** [comment]
Duplicate:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/883

**Comment by Techgeek2011** [comment]
I’m sorry, but that’s not my issue, my issue is continuity doesn’t work, thank you in advance

**Comment by khronokernel** [comment]
Oh the dongle's functional in Monterey?

**Comment by Techgeek2011** [comment]
> Oh the dongle's functional in Monterey?

Yes, I just want to know if you could help me get continuity working?

**Comment by khronokernel** [comment]
Not promising much but you can try this build of OCLP:
* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/5059535297/artifacts/150108623
Note that you'll need to be signed into Github to download

**Comment by Techgeek2011** [comment]
> Not promising much but you can try this build of OCLP:
> 
> * https://github.com/dortania/OpenCore-Legacy-Patcher/suites/5059535297/artifacts/150108623
> 
> 
> 
> Note that you'll need to be signed into Github to download

Update: I clicked it on my phone, and it sadly gave a 404 error

**Comment by khronokernel** [comment]
> Note that you'll need to be signed into Github to download

**Comment by Techgeek2011** [comment]
> > Note that you'll need to be signed into Github to download


I forgot that, it's now downloaded, and I will try it when my Mac finishes updating! Thanks!

**Comment by Techgeek2011** [comment]
> > > Note that you'll need to be signed into Github to download
> 
> 
> I forgot that, it's now downloaded, and I will try it when my Mac finishes updating! Thanks!

Update: it sadly didn't work, so you have any other ideas? Thanks in advance

**Comment by khronokernel** [comment]
Could you send the following:

* Run the OCLP app I sent previously, go to `Settings -> Developer Settings -> Developer Debug` and send the model dump info (just copy into a text file)
* Build OCLP again but copy the info it prints during the build, copy into another txt file
* Send the Build Folder it generated (just zip it and send here)

Additionally, how are you determining Continuity Support?

**Comment by Techgeek2011** [comment]
> Could you send the following:
> 
> 
> 
> * Run the OCLP app I sent previously, go to `Settings -> Developer Settings -> Developer Debug` and send the model dump info (just copy into a text file)
> 
> * Build OCLP again but copy the info it prints during the build, copy into another txt file
> 
> * Send the Build Folder it generated (just zip it and send here)
> 
> 
> 
> Additionally, how are you determining Continuity Support?

1: I really am tech savvy, but I can't understand you 
2: by continuity support, I mean handoff and airdrop

**Comment by Techgeek2011** [comment]
> > Could you send the following:
> > 
> > 
> > 
> > * Run the OCLP app I sent previously, go to `Settings -> Developer Settings -> Developer Debug` and send the model dump info (just copy into a text file)
> > 
> > * Build OCLP again but copy the info it prints during the build, copy into another txt file
> > 
> > * Send the Build Folder it generated (just zip it and send here)
> > 
> > 
> > 
> > Additionally, how are you determining Continuity Support?
> 
> 1: I really am tech savvy, but I can't understand you 
> 2: by continuity support, I mean handoff and airdrop 

Oh! I think I get it, I will send it after work later

**Comment by Techgeek2011** [comment]
@khronokernel what is a "build folder"?

**Comment by khronokernel** [comment]
Apologies but if you're not a familiar debugging this yourself, I'm unfortunately not interested in walking you through the entire process. I have many more important projects within OCLP I need to focus on.

You'd best troubleshoot on forums, feel free to PR to the repo if you're able to resolve your issues. Always appreciate extra aid with OCLP

**Comment by Techgeek2011** [comment]
> Apologies but if you're not a familiar debugging this yourself, I'm unfortunately not interested in walking you through the entire process. I have many more important projects within OCLP I need to focus on.
> 
> 
> 
> You'd best troubleshoot on forums, feel free to PR to the repo if you're able to resolve your issues. Always appreciate extra aid with OCLP

Thank you, but I do have 2 more important questions:
1; why did you ban Gaming York YT From your discord server?
 2: Does the early 2013 15" MBP Need post install patches?
