### ISSUE TITLE
OLCP not working for 12.2

### ISSUE THREAD

**Issue by sarathchandradamineni** [dortania/OpenCore-Legacy-Patcher#913]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already discussed this is a pather bug and not a macOS bug on forums and discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Issue?

I just updated my Macbook 10,1 to Monterey 12.2.
On my system, OLCP does not work with 12.2 yet.

**Comment by khronokernel** [comment]
No debugging information provided, closing. Use forums for troubleshooting
