### ISSUE TITLE
Opencore 0.4.1 stops responding after downloading macos Monterey.

### ISSUE THREAD

**Issue by ramonenghaw** [dortania/OpenCore-Legacy-Patcher#915]
### Machine Model

iMac10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already discussed this is a pather bug and not a macOS bug on forums and discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 10.13, High Sierra

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hello, I'm on macos high sierra, after the download of macos monterey reaches 100%, opencore stops responding.

**Comment by khronokernel** [comment]
How long did you wait? The installer is quite massive, it needs to decompress it and can take about 5-10min on slower machines

Additionally have you verified if this occurs on the TUI variant?

**Comment by ramonenghaw** [comment]
Hello, you really need to wait around 1-2 minutes, but the app is in "not responding" status, you may need to add a disclaimer on the download screen.

Do you work on OpenCore development? Is there a forecast to translate it into Brazilian Portuguese? I could help.
