### ISSUE TITLE
How to upgrade macos monterey from 12.1 to 12.2

### ISSUE THREAD

**Issue by Coselmann** [dortania/OpenCore-Legacy-Patcher#917]
### Machine Model

Macmini6,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already discussed this is a pather bug and not a macOS bug on forums and discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Please clearly explain the issueUpdate does not show up for me in system preferences and I tried it via terminal. My computer does not detect update.

**Comment by khronokernel** [comment]
> Have you already discussed this is a pather bug and not a macOS bug on forums and discord servers?

> false
