### ISSUE TITLE
Post Install Patch for Ivy Bridge Intel HD 4000 not working

### ISSUE THREAD

**Issue by mxswift** [dortania/OpenCore-Legacy-Patcher#918]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already discussed this is a pather bug and not a macOS bug on forums and discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hello, on my MacBookPro9,2 (Mid 2012 Non-Retina), after doing a clean installation of Monterey using OCLP (0.4.1) GUI/TUI and running the post install patches for graphics acceleration for Ivy Bridge (Intel HD 4000), this patch doesn't seem to work on my machine. It seems that the kext may be failing to load (?) as I see a busy timeout[0], (60s) 'AppleIntelCapriController' on the verbose boot screen (which makes the boot up take a while).

After the login screen, I get partial acceleration (no blur, choppy animations). 

Attached are screenshots of the Desktop with some more information along with my kernel DMESG log and OpenCore logs pulled from the boot drive's EFI.

![Screen Shot 2022-01-28 at 8 59 54 PM](https://user-images.githubusercontent.com/23565336/151642990-9cd17eea-78e8-49eb-aee4-585eb195c88b.png)

[opencore-2022-01-29-014718.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7962792/opencore-2022-01-29-014718.txt)

[DMESG.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7962796/DMESG.txt)

Please let me know if you need more information!
Thank you,

**Comment by mxswift** [comment]
I forgot to mention that I tried clearing the NVRAM and resetting the SMC but that did not solve the issue.

**Comment by khronokernel** [comment]
We had validated macOS 12.2 a bit ago and validated 12.3 Beta just yesterday:
![Screen Shot 2022-01-28 at 7 47 41 PM](https://user-images.githubusercontent.com/48863253/151644420-b603f85e-7cab-4cc2-96d1-0fe9ac58bdb5.png)

In addition to this, many users on our discord have reported no issues with any of our acceleration patches. It seems your local system is having issues, either due to hardware state or OS installation. Would be best to run a clean installation, otherwise troubleshoot further on forums.
