### ISSUE TITLE
Get stuck on install mac os big sur

### ISSUE THREAD

**Issue by heiscostly** [dortania/OpenCore-Legacy-Patcher#920]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already discussed this is a pather bug and not a macOS bug on forums and discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Am trying to install mac os bigsur on my mac pro mid 2012 with 8gb ram 128ssd, intel core i7 processor with 2.9gh and this where i get stuck and it shows the error screen
![C02489AD-E553-43C5-80CD-5E9F3B1421F8_1_102_o](https://user-images.githubusercontent.com/39498038/151654959-55778241-6fda-4bd4-8da8-679572487db5.jpeg)
![C2D14AE3-DAF8-4E20-982A-805A0C6DAF03_1_102_o](https://user-images.githubusercontent.com/39498038/151654961-f3f9e1cf-a04e-4332-8d6d-352c221a02d3.jpeg)

![E8863E39-4447-4219-A22F-A11B2E665516_1_105_c](https://user-images.githubusercontent.com/39498038/151654953-50ba2a1b-a68f-4f50-ae32-71dd92570fa9.jpeg)

**Comment by khronokernel** [comment]
Use forums for troubleshooting
