### ISSUE TITLE
Reporting three bugs

### ISSUE THREAD

**Issue by ramonenghaw** [dortania/OpenCore-Legacy-Patcher#923]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I'm reporting three bugs that happen in Monterey on iMac Late 2009 10.1.

1st - In system preferences: in General - The Automatic appearance option does not work, it does not automatically switch to dark mode. It only works when selecting light mode or dark mode.
![Captura de Tela 2022-01-29 às 13 46 21](https://user-images.githubusercontent.com/71452954/151669474-bc09b54f-3ed7-4076-9481-b47dd0d96cf6.png)

2nd - In the accessibility menu, some icons do not appear.
![Captura de Tela 2022-01-29 às 13 47 51](https://user-images.githubusercontent.com/71452954/151669527-9ede8b1c-84d4-4f98-bd3e-419455a5edf8.png)

3rd - The screen capture controls in Quicktime are invisible, when placing the mouse cursor in the direction of the buttons it is possible to notice that they are there, but invisible.

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
