### ISSUE TITLE
Changing serials to update MacOS

### ISSUE THREAD

**Issue by elesto** [dortania/OpenCore-Legacy-Patcher#925]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Hi, I dont know where else to put this but I have a question. I have the ability to modify the BIOS chip on my MBP 11,1 laptop and I can change the serial and mainboard serial ect. If I change to a newer device serial will I be able to update to Monterey and get future updates with no issues even without opencore? Does a mac need anything else to support updating? There is no need to mention that modifying bios chips are not advised.

**Comment by khronokernel** [comment]
macOS has zero reliance on serial numbers for OS support. Logic is based off the SMBIOS's `model` and `board-id`. If you're modifying the firmware this much, you'll be bound to break many drivers expecting specific hardware configurations to match pre-defined assumptions.

Our patcher supports model spoofing (optional), and has the correct patch sets needed for supporting in-memory SMBIOS masking. Additionally we support stock firmwares, zero modding is ever needed from the end user.

If you have no interest in using OCLP, buy a new Mac. Random hex edits in your BIOS will lead to potentially bricked systems.
