### ISSUE TITLE
[Suggestion] Allow disabling launch agents/daemons

### ISSUE THREAD

**Issue by elesto** [dortania/OpenCore-Legacy-Patcher#926]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

My reasoning is as follows: We are here because we are running outdated unsupported hardware, and that comes with issues such as battery life and performance. Also there is the privacy argument; people want to decide what runs on their hardware. To solve this issue, I have found this great [guide](https://gist.github.com/pwnsdx/1217727ca57de2dd2a372afdd7a0fc21) on github. The problem is with every new version of osx it gets harder and harder to do. Currently if you want a speedy lean osx install you have to disable SIP among other things and I dont have to go into details on why thats dangerous. 

OCLP would be able to provide a safe and reliable solution for advanced users to slim down their new os and give extra years to old hardware.

My suggestion is adding an option when building opencore to import a users custom txt file with each new line being a launchAgent to disable when opencore works its magic. The same for launchDaemons.

This is obviously a very advanced option and I understand that it can and will break parts of osx, BUT it is important not to baby users who want to tinker and prolong their hardware. 

I am optimistic for support for this and If you have an alternative please mention it.

**Comment by khronokernel** [comment]
So based off this "magic" OCLP has, you'd like us to:

- Disable a large majority of OS functionality
- Research viable methods into this "disabling" approach
- Have us develop and implement a system to do so
- Validate and support this system on an on-going basis for yourself and others

I have zero interest in supporting a half assed system made up on the spot. However feel free to research and implement this on your own time, but please keep Github Issues to valid issues with the project itself. We have to dedicate time away from our personal lives to both parse and reply to these issues, please respect the time of developers. 

If you need a space to brain storm these ideas, feel free to use forums.
