### ISSUE TITLE
"You shutdown your computer because of a problem" after startup

### ISSUE THREAD

**Issue by okla** [dortania/OpenCore-Legacy-Patcher#927]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After installing MacOS 12.2, every time I reboot or shutdown + startup there is a warning "You shutdown your computer because of a problem" right after login.

**Comment by khronokernel** [comment]
Use forums for troubleshooting

**Comment by AndreasJordanidis** [comment]
could be a hibernation crash, but I think that's only an issue with 9x and 10x

**Comment by okla** [comment]
@khronokernel can you please point where the forums are?

**Comment by okla** [comment]
@AndreasJordanidis do you know how can I check it?

**Comment by AndreasJordanidis** [comment]
in console, crash reports
