### ISSUE TITLE
EFI Boot is missing?

### ISSUE THREAD

**Issue by Rubl80** [dortania/OpenCore-Legacy-Patcher#928]
### Machine Model

MacBook6,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

The EFI Boot option is missing, after build and creating a new MacOS installer.

I Reboot machine while holding Option, but I only get the Monterey Install option. No EFI Boot option.

Any idea why that is?

### What steps have you taken to troubleshoot this?

I have tried several times to create a new installer, but no luck.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
