### ISSUE TITLE
Keyboard Backlight fixed with Touché {Touch Bar for old Macs}

### ISSUE THREAD

**Issue by AndreasJordanidis** [dortania/OpenCore-Legacy-Patcher#929]
### Machine Model

MacBook5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

false

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I didn't know where to post this, but my friend TechGeek, has come up with a solution to broken keyboard backlight on OpenGL GPU Macs 2011 and older, he's running Big Sur on a 5,1 13'' MacBook.

By installing an app called Touché https://redsweater.com/touche/
(which brings Touch Bar on to older than 2016 Macs), opening it, and then clicking on the keyboard backlight keys in the app, it'll for some reason unlock the physical keyboard backlight keys and the backlight control in control center on 2008-2011 MacBooks which completely fixes the keyboard backlight issue, which normally requires Lab Tick, which doesn't enable physical backlight keys and control center backlight control in Big Sur and Monterey.

Thank you for reading, and sorry for not posting this elsewhere, I have not been told where the forums are.

### What steps have you taken to troubleshoot this?

Installed an app called Touché https://redsweater.com/touche/

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/pull/732#issuecomment-1024800358

**Comment by AndreasJordanidis** [comment]
oh, I didn't know there was already a fix,, two days ago...
