### ISSUE TITLE
After updating Monterey 12.1 to 12.2 the maps app don't show any graphics/maps - same by opening pdf-files

### ISSUE THREAD

**Issue by Schmagauke** [dortania/OpenCore-Legacy-Patcher#931]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After updating to Monterey 12.2 and post-install volume patch the system runs smooth.

But the "maps" app don't show any map-graphics, same issue at the app "where is" - just a grey screen.

pdf-files don't show any graphics too. In preview the graphics are shown but by opening the files the graphics are gone ??

Can't find something to fix this problems.

### What steps have you taken to troubleshoot this?

unpatch the install-volume doesn't fix the issue

**Comment by introns-bungles** [comment]
This could be related to the experimental nature of the Non-Metal GPU patches. As I have the same issue on a iMac12,2 with an ATI 6xxx GPU.

See: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by Ausdauersportler** [comment]
No, this is not the experimental state of the patches, it is the simple fact the patches only bring back OpenGL support while a lot of Apple and third party apps are now relying on the more recent with Mojave introduced Metal framework.

Patches do not enable magically a metal-layer and so support will stay at this level, the gap will become even bigger and bigger, more and more apps will not work properly regardless how much work in the OpenGL patches will be spent. 

The only option is to change the GPU (MacPro and iMac11,x and iMac12,x) or buying a more recent Metal GPU equipped Mac.

**Comment by introns-bungles** [comment]
This was in no way meant to be rude, maybe I misphrased `These patches however are in heavy development` as experimental. Thank you for the amazing work you guys are doing and for clarifying the limitations of said patches.

**Comment by Ausdauersportler** [comment]
It was not taken that way, I just wanted to clarify that better patches will never solve the lack of a real metal driver for older pre 2012 GPU.

**Comment by Schmagauke** [comment]
Thank you for your posts.

In case with the pdf-Issue - if I open the pdf-files with another app for example with color-sync (from system utility folder) or goodnotes - then it workes fine - all graphics are shown - so I think it shouldn't be a problem with the hardware or am I wrong ?

**Comment by Ausdauersportler** [comment]
Third try:

It is an issue with your hardware, your GPU does not support the metal framework and apps using it will fail on your hardware and no patch will ever solve this.

But you can try to replace one by one all new apps with older ones or other apps not showing such a problem and not needing a new metal GPU.

You should have read the OLCP online docs and especially the section about legacy graphics patches before opening an issue here. This platform Is not meant to provide user help. Please use forums as mentioned on the OCLP GitHub page.

**Comment by Schmagauke** [comment]
OK - thanks for your third friendly post and sorry for my question here.
