### ISSUE TITLE
it starts to install and after 12 mn... error

### ISSUE THREAD

**Issue by thierry-laval** [dortania/OpenCore-Legacy-Patcher#932]
### Machine Model

MacBookAir6,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Macbook Air 6,2 from 2013

The USB key has been filled with the software and the EFI partition...

I did boot on it, I upgrade from Big Sur but... it starts to install and after 12 mn error ... I tried 3 times and same thing... 

### What steps have you taken to troubleshoot this?

I tried again to make my usb keys, cleanly, formatting/installing macos monterey/installing the efi boot.

I tried again but same problem... 

Would you have an idea
![IMG_5498](https://user-images.githubusercontent.com/46448224/151780099-22f64ae1-bf09-4642-a1b8-a802955fda13.JPG)
?

**Comment by khronokernel** [comment]
Use forums for troubleshooting
