### ISSUE TITLE
macOS Monterey frozen

### ISSUE THREAD

**Issue by ejcupcake1234alt** [dortania/OpenCore-Legacy-Patcher#933]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I started up macOS, after a few minutes it froze. and these are the Problem Details And System Configuration:

panic(cpu 2 caller 0xffffff8020bd78d3): Kernel trap at 0xffffff7fb8d21509, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0xffffffd0449ce000, CR3: 0x0000000024fde000, CR4: 0x00000000001626e0
RAX: 0x0000000000008000, RBX: 0x0000000016ad0000, RCX: 0x000000000000e138, RDX: 0xffffffa03f6b6ec9
RSP: 0xffffffd07ecb3d90, RBP: 0xffffffd07ecb3dc0, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffffd07ecb3c40, R9:  0x0000000000000000, R10: 0x0000000000000008, R11: 0x000000000000000a
R12: 0x0000000000000014, R13: 0x0000000000007fec, R14: 0xffffffd0449ae000, R15: 0xffffff903d95a000
RFL: 0x0000000000010297, RIP: 0xffffff7fb8d21509, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffffd0449ce000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 1

Panicked task 0xffffff86a3e63670: 193 threads: pid 0: kernel_task
Backtrace (CPU 2), panicked thread: 0xffffff86a4dc7540, Frame : Return Address
0xffffffd07ecb37c0 : 0xffffff8020a87ddd mach_kernel : _handle_debugger_trap + 0x41d
0xffffffd07ecb3810 : 0xffffff8020be7d15 mach_kernel : _kdp_i386_trap + 0x145
0xffffffd07ecb3850 : 0xffffff8020bd74e3 mach_kernel : _kernel_trap + 0x533
0xffffffd07ecb38a0 : 0xffffff8020a27a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd07ecb38c0 : 0xffffff8020a881ad mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffd07ecb39e0 : 0xffffff8020a87966 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffd07ecb3a40 : 0xffffff80213160b9 mach_kernel : _panic + 0x54
0xffffffd07ecb3ab0 : 0xffffff8020bd78d3 mach_kernel : _sync_iss_to_iks + 0x2c3
0xffffffd07ecb3c30 : 0xffffff8020bd75b8 mach_kernel : _kernel_trap + 0x608
0xffffffd07ecb3c80 : 0xffffff8020a27a60 mach_kernel : _return_from_trap + 0xe0
0xffffffd07ecb3ca0 : 0xffffff7fb8d21509 com.apple.driver.AppleIntelHD4000Graphics : __ZN20IGHardwareRingBuffer15dumpBatchBufferER14debugRegistersP20ResourceCacheElement + 0x117
0xffffffd07ecb3dc0 : 0xffffff7fb8d2000d com.apple.driver.AppleIntelHD4000Graphics : __ZN20IGHardwareRingBuffer16dumpHangAnalysisEv + 0x165
0xffffffd07ecb3e00 : 0xffffff7fb9b65c58 com.apple.iokit.IOAcceleratorFamily2 : __ZN19IOAccelFIFOChannel27restartEv + 0x10a
0xffffffd07ecb3e50 : 0xffffff7fb9b742ae com.apple.iokit.IOAcceleratorFamily2 : __ZN20IOAccelEventMachine215restart_channelEv + 0xf6
0xffffffd07ecb3e90 : 0xffffff7fb9b73a3e com.apple.iokit.IOAcceleratorFamily2 : __ZN20IOAccelEventMachine218hardwareErrorEventEv + 0x206
0xffffffd07ecb3ed0 : 0xffffff8021258d13 mach_kernel : __ZN22IOInterruptEventSource12checkForWorkEv + 0x163
0xffffffd07ecb3f20 : 0xffffff802125756e mach_kernel : __ZN10IOWorkLoop15runEventSourcesEv + 0x13e
0xffffffd07ecb3f60 : 0xffffff8021256b97 mach_kernel : __ZN10IOWorkLoop10threadMainEv + 0x37
0xffffffd07ecb3fa0 : 0xffffff8020a2718e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(462.4.1)[73899B24-CF1D-3468-AF75-F6E62058E2A4]@0xffffff7fb9b61000->0xffffff7fb9bcafff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[11A5AE25-9819-386C-ABF0-088AA250EC30]@0xffffff802216c000->0xffffff802218dfff
            dependency: com.apple.iokit.IOGraphicsFamily(593)[A327B1FD-1BF3-3D02-A4E5-20A37ED0493E]@0xffffff7fb9cee000->0xffffff7fb9d1cfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[023CD3FF-4EFC-3455-89C2-FF8BD98013EB]@0xffffff80235d5000->0xffffff80235fffff
            dependency: com.apple.iokit.IOReportFamily(47)[097D0056-1E44-3A97-8AD8-8D0F6B76113E]@0xffffff8023611000->0xffffff8023613fff
            dependency: com.apple.iokit.IOSurface(302.9)[8F577265-9368-32C8-B7AE-071532EE9337]@0xffffff8023744000->0xffffff8023760fff
         com.apple.driver.AppleIntelHD4000Graphics(16.0.4)[B3E3DB58-1997-33A2-B839-68A2D70655E6]@0xffffff7fb8d0c000->0xffffff7fb8d6bfff
            dependency: com.apple.iokit.IOAcceleratorFamily2(462.4.1)[73899B24-CF1D-3468-AF75-F6E62058E2A4]@0xffffff7fb9b61000->0xffffff7fb9bcafff
            dependency: com.apple.iokit.IOGraphicsFamily(593)[A327B1FD-1BF3-3D02-A4E5-20A37ED0493E]@0xffffff7fb9cee000->0xffffff7fb9d1cfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[023CD3FF-4EFC-3455-89C2-FF8BD98013EB]@0xffffff80235d5000->0xffffff80235fffff
            dependency: com.apple.iokit.IOSurface(302.9)[8F577265-9368-32C8-B7AE-071532EE9337]@0xffffff8023744000->0xffffff8023760fff

Process name corresponding to current thread (0xffffff86a4dc7540): kernel_task
Boot args: keepsyms=1 debug=0x100 -revasset

Mac OS version:
21C52

Kernel version:
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Kernel UUID: E32C293C-7D8B-327C-A335-6AAD250A4881
KernelCache slide: 0x0000000020800000
KernelCache base:  0xffffff8020a00000
Kernel slide:      0x0000000020810000
Kernel text base:  0xffffff8020a10000
__HIB  text base: 0xffffff8020900000
System model name: MacBookPro9,2 (Mac-6F01561E16C75D06)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 368731845478
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000055da21851d
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000343912466 0x0000000000000000
Zone info:
Foreign   : 0xffffff80253df000 - 0xffffff80253ec000
Native    : 0xffffff803d67b000 - 0xffffffa03d67b000
Readonly  : 0xffffff850a347000 - 0xffffff86a3cdb000
Metadata  : 0xffffffee857e2000 - 0xffffffeea5965000
Bitmaps   : 0xffffffeea5965000 - 0xffffffeeab965000

This only happens like 1/50 times i start-up.

### What steps have you taken to troubleshoot this?

none.

**Comment by khronokernel** [comment]
Use forums for troubleshooting
