### ISSUE TITLE
Monterey Installer stops at 12 minutes from the end with "An error occurred while loading the update" with Opencore legacy patcher 0.4.1

### ISSUE THREAD

**Issue by StanleyLubrick** [dortania/OpenCore-Legacy-Patcher#934]
### Machine Model

MacBookPro9,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 10.15, Catalina

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

After booting on the EFI, I launch the Monterey update and accept all the terms. The update begins during a few minutes and the stops at 12 minutes from the end with the following message "An error occurred while loading the update".

**Comment by khronokernel** [comment]
Use forums for troubleshooting

**Comment by StanleyLubrick** [comment]
I'm sorry, can you point me to the right forum please ?
