### ISSUE TITLE
Beta Blur in-affective on macOS Monterey Beta 21D5039d

### ISSUE THREAD

**Issue by Manveer-Singh-99** [dortania/OpenCore-Legacy-Patcher#935]
### Machine Model

iMac11,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After enabling Beta Blur,  logged out and logged in back again but saw no change. The wierd graphics glitches still kept happening. I even restarted but no change.

### What steps have you taken to troubleshoot this?

Rebuilt opencore and installed it to both internal and external drive.

**Comment by khronokernel** [comment]
No hardware specs provided, use forums for troubleshooting
