### ISSUE TITLE
AirPlay Receiver unavailable with macOS 12.2 and iMac14,x

### ISSUE THREAD

**Issue by marcpbailey** [dortania/OpenCore-Legacy-Patcher#937]
### Machine Model

iMac14,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in), Other/Non-Applicable

### What is the Issue?

Apologies for opening a new issue. Attempted to post new information on #702 - which consolidates #683,  #701, #740 - but comments were locked overnight by @khronokernel  (thank you so much for your work).
Still, this is new data and I felt it might help people to know this remains an issue with the latest releases, not just with 12.1 beta.

### What steps have you taken to troubleshoot this?

Confirmed #702 condition exists for these combinations:

iMac14,2, Monterey 12.1, OCLP 0.3.3
iMac14,2, Monterey 12.1, OCLP 0.4.1
iMac14,2, Monterey 12.2, OCLP 0.4.1

![Screen Shot 2022-02-02 at 1 37 54 pm](https://user-images.githubusercontent.com/39522686/152084921-b96d39cc-12dc-47a2-be93-2219299d5cea.png)

**Comment by khronokernel** [comment]
Feel free to discuss your personal findings on forums, however issue #783 is mainly for developer tracking. AirPlay to Mac will remain broken for as long as the page size does not include the entire blacklist, and that's entirely up to macOS on the segments loaded.

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/783

Unless the situation has changed or has been resolved, rather keep project issues for more important concerns.
