### ISSUE TITLE
No HiDPI on MacOS 12.2

### ISSUE THREAD

**Issue by waterlou** [dortania/OpenCore-Legacy-Patcher#938]
### Machine Model

MacBookPro10,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Was using OpenCore patcher on Mac OS 12.1 without problem, after update to 12.2, no HiDPI is available to the system, so only 2880x1800 resolution is available.  I've tried to add back hiDPI setting using RDM, but not working.

### What steps have you taken to troubleshoot this?

1. Update system to 12.2 from 12.1 with bulletin software update
2. After update, HiDPI settings are gone
3. Resetting PRAM no changes
4. Updated OpenCore to latest version no changes

**Comment by khronokernel** [comment]
* https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html#no-graphics-acceleration

Use forums for troubleshooting
