### ISSUE TITLE
While installing OpenCore Legacy Patcher monterey, the system reboots 12 minutes before and won't load.

### ISSUE THREAD

**Issue by mehmetsukrumumbucoglu** [dortania/OpenCore-Legacy-Patcher#940]
### Machine Model

iMac13,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hello, I have a problem that I ask for your help. I have a mac with iMac version 13.1. I will use this mac to develop flutter. And I need macOs monterey version. I prepared a USB flash memory that will use OpenCore Legacy Patcher version 0.3.1 and Monterey Installer version 12.0.1. Just as we explained in the video, I tried to install it on iMac, the installation starts after selecting the hard disk. The installation starts at 17 minutes, but after a certain point, the iMac restarts itself before the time is up. I also tried it on MacPro5.1, the machine restarts after 12 minutes. Despite trying many times, I could not succeed. What could be the source of this problem? As we explained in the video, I do exactly the same steps, but I fail. Please help me. I've been dealing with it for a week.

**Comment by khronokernel** [comment]
Use forums for troubleshooting

**Comment by mehmetsukrumumbucoglu** [comment]
Which forum can I use?
