### ISSUE TITLE
Finder and Dock lock up when changing some settings

### ISSUE THREAD

**Issue by elesto** [dortania/OpenCore-Legacy-Patcher#943]
### Machine Model

MacBookPro11,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I cant figure out how to reproduce this but it has happened to me twice in a few days. When I change the Accent colour and/or the Highlight colour and/or select "Automatically hide and show the menu bar" in preferences. The finder and dock will lock up. I wont be able to view the dock or use multi touch gestures to switch desktops, essentially I am stuck in whatever app I was currently using.

### What steps have you taken to troubleshoot this?

The first time I had to reboot and that fixed it. The second time I used my shortcut shortcut to open terminal and "killall Finder" that didnt fix it so I "killall Dock" and it was fixed.

**Comment by khronokernel** [comment]
11,1 uses the Haswell graphics stack which is still used by native Macs, little reason to believe this is an OCLP issue. Troubleshoot on forums

> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

And please answer these honestly, respect our time
