### ISSUE TITLE
Macbook pro 2014 16inch screen size is 2880x 1800

### ISSUE THREAD

**Issue by knjnko** [dortania/OpenCore-Legacy-Patcher#944]
### Machine Model

MacBookPro11,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen, Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

I am using a macbookpro 2014 16inch.
I get a screen size of 2880x1880.
And I have to press shift key to start it.

### What steps have you taken to troubleshoot this?

not yet.

**Comment by khronokernel** [comment]
* https://dortania.github.io/OpenCore-Legacy-Patcher/TROUBLESHOOTING.html#no-graphics-acceleration

> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
true

And answer these honestly, please respect our time. Github issues are not your personal support centre
