### ISSUE TITLE
iMessage not sync properly with iCloud

### ISSUE THREAD

**Issue by Tiger-AC** [dortania/OpenCore-Legacy-Patcher#945]
### Machine Model

iMac10,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

First of all, I'd like thank all the developers for finally fixing the "Catalyst Scrolling" issue for non-metal Macs, much appreciated.
I've tried this new iMessage "Catalyst Scrolling" fix on Catalina, Big Sur, and Monterey. All works now. However some of the photos/videos are not able to be downloaded and also won't go back to the old messages whereby the little iCloud sync gear icon keeps spinning forever if I scroll down the messages trying to view earlier ones.

update-1: The sync issue is now only limited to the old messages with Big Sur and Monterey, after turning off the testing iMac for around 10 hours. The most recent photos/videos have shown up under all macOS.

update-2: I've just tested on an iMac13,2 (metal GPU) running Monterey with OCLP v 0.4.1 under a different account and the issue is the same: can't go back to view old messages: stuck on a spinning gear trying to sync with iCloud.

### What steps have you taken to troubleshoot this?

Tried quitting the iMessage app and restarting, different macOS, changing SMBIOS from non to minimal,  NVRAM reset. But the symptom is very consistent and persistent.

**Comment by splaquet** [comment]
Since these new(est) OCLP versions has you log back into many of your iCloud sessions again... have you checked on your iOS device, ensuring that messages toggle is flipped on for sharing Messages with your computer?

I've had this issue SO many times.  So many that I have a difficult time forgetting to check my mobile device settings... because it's easy to forget, being a different device and all.

**Comment by Tiger-AC** [comment]
Thx for the reply. It works with Catalina, meaning I can go back to view old/older messages. The issue only occurs when running Big Sur & Monterey.

**Comment by Tiger-AC** [comment]
It seems the Messages app is not sending out iCloud sync request when scrolling back to the top of the message pane.

**Comment by Tiger-AC** [comment]
Well, I've finally found a solution to go back to the old messages: use <Page Up> key to fetch old messages in iCloud Instead of using mouse to scroll back. If you don't have the <Page Up> key, use <Fn> + <Up Arrow> keys instead.

This issue may not be OCLP related at all. Sorry for the confusions created by me.
