### ISSUE TITLE
Only boots in safe mode - post install patch fails

### ISSUE THREAD

**Issue by slothyjunior** [dortania/OpenCore-Legacy-Patcher#946]
### Machine Model

MacPro5,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After OCLP macOS installer run, will not boot into Monterey. After mac loading screen, goes black.

Will however load in safe mode.

When Installing OpenCore, the following error is received:

####################
# Copying OpenCore #
####################

An error occurred!
0:188: execution error: Volume on disk1s1 failed to mount
If you think the volume is supported but damaged, try the "readOnly" option
 (1)

Please report this to the devs at GitHub.

Press [Enter] to go back.
Traceback (most recent call last):
  File "gui_main.py", line 594, in <lambda>
  File "gui_main.py", line 638, in install_oc_process
  File "install.py", line 171, in install_opencore
  File "utilities.py", line 545, in start
EOFError: EOF when reading a line

### What steps have you taken to troubleshoot this?

I have tried to install the Post Install Root Patch first and then after reboot retried installing OpenCore but the same error occurs.

**Comment by khronokernel** [comment]
With regards to Single User Mode, macOS does not allow the FAT32 Kernel Space driver to mount therefore limiting any way to mount and edit FAT32 out of box. Unsure why you need to install OpenCore internally to perform root patching, documentation never states

Use forums for troubleshooting please
