### ISSUE TITLE
IMac 12.2  Mid 2011 with ATI HD4670 Terrascale 1  after a while Grafik turns bad

### ISSUE THREAD

**Issue by freddey** [dortania/OpenCore-Legacy-Patcher#947]
### Machine Model

iMac12,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

After Installation of Monterey following the guide https://www.youtube.com/watch?v=go6RTCHv4GA
Creating a boot stick. Preparing with open legacy Patcher, Installing Monterey. Starting for the first time. Installing Post install with Open legacy patcher. Reboot. 
After Reboot everything seems fine. After a while of working Screen turns in 1's and 0's or shows parts of windows or turn partly black. When moving over with the mouse again it comes partly back. See the pictures!
https://user-images.githubusercontent.com/35611268/152696928-290f5048-3670-4f39-9dcb-4ccd163812b8.jpeg

When creating the patched Hardrive with open legacy Patcher it shows the following:

################################
# Downloading: 12-Monterey.zip #
################################

142.5MB Downloaded of 142.5MB (100.0%)
Average Download Speed: 15.25 MB/s
- Download completed
- Unzipping download...
- Renaming folder
- Binaries downloaded to:
/private/var/folders/r5/y6w61kl93g9fjy50vtzhrykr0000gp/T/_MEILtYRbH/payloads
- Found Root Volume at: disk1s5
- Mounting APFS Snapshot as writable
Password:
- Mounted APFS Snapshot as writable at: /System/Volumes/Update/mnt1
- Successfully mounted the Root Volume
- Running patches for iMac12,2
- Installing legacy TeraScale 1 Patches
- Detected supported OS, installing Acceleration Patches
- Installing TeraScale 1 Acceleration Kext patches for Big Sur/Monterey
- Deleting AMDRadeonX4000.kext
- Deleting AMDRadeonX4000HWServices.kext
- Deleting AMDRadeonX5000.kext
- Deleting AMDRadeonX5000HWServices.kext
- Deleting AMDRadeonX6000.kext
- Deleting AMDRadeonX6000Framebuffer.kext
- Deleting AMDRadeonX6000HWServices.kext
- Deleting AMD7000Controller.kext
- Deleting AMD8000Controller.kext
- Deleting AMD9000Controller.kext
- Deleting AMD9500Controller.kext
- Deleting AMD10000Controller.kext
- Deleting AppleIntelBDWGraphics.kext
- Deleting AppleIntelBDWGraphicsFramebuffer.kext
- Deleting AppleIntelCFLGraphicsFramebuffer.kext
- Couldn't find AppleIntelHD4000Graphics.kext, skipping
- Deleting AppleIntelHD5000Graphics.kext
- Deleting AppleIntelICLGraphics.kext
- Deleting AppleIntelICLLPGraphicsFramebuffer.kext
- Deleting AppleIntelKBLGraphics.kext
- Deleting AppleIntelKBLGraphicsFramebuffer.kext
- Deleting AppleIntelSKLGraphics.kext
- Deleting AppleIntelSKLGraphicsFramebuffer.kext
- Deleting AppleIntelFramebufferAzul.kext
- Couldn't find AppleIntelFramebufferCapri.kext, skipping
- Deleting AppleParavirtGPU.kext
- Couldn't find GeForce.kext, skipping
- Deleting IOGPUFamily.kext
- Installing General Acceleration Kext patches for Big Sur/Monterey
- Found conflicting kext, Deleting Root Volume's IOAcceleratorFamily2.kext
- Adding IOAcceleratorFamily2.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Adding AMD2400Controller.kext
- Adding AMD2600Controller.kext
- Adding AMD3800Controller.kext
- Adding AMD4600Controller.kext
- Adding AMD4800Controller.kext
- Adding AMD5000Controller.kext
- Adding AMD6000Controller.kext
- Found conflicting kext, Deleting Root Volume's AMDFramebuffer.kext
- Adding AMDFramebuffer.kext
- Adding AMDLegacyFramebuffer.kext
- Adding AMDLegacySupport.kext
- Found conflicting kext, Deleting Root Volume's AMDRadeonVADriver.bundle
- Adding AMDRadeonVADriver.bundle
- Found conflicting kext, Deleting Root Volume's AMDRadeonVADriver2.bundle
- Adding AMDRadeonVADriver2.bundle
- Adding AMDRadeonX3000.kext
- Adding AMDRadeonX3000GLDriver.bundle
- Found conflicting kext, Deleting Root Volume's AMDShared.bundle
- Adding AMDShared.bundle
- Found conflicting kext, Deleting Root Volume's AMDSupport.kext
- Adding AMDSupport.kext
- Adding ATIRadeonX2000.kext
- Adding ATIRadeonX2000GA.plugin
- Adding ATIRadeonX2000GLDriver.bundle
- Adding ATIRadeonX2000VADriver.bundle
- Installing legacy Sandy Bridge Patches
- Detected supported OS, installing Acceleration Patches
- Installing Sandy Bridge Acceleration Kext patches for Big Sur/Monterey
- Couldn't find AMDRadeonX4000.kext, skipping
- Couldn't find AMDRadeonX4000HWServices.kext, skipping
- Couldn't find AMDRadeonX5000.kext, skipping
- Couldn't find AMDRadeonX5000HWServices.kext, skipping
- Couldn't find AMDRadeonX6000.kext, skipping
- Couldn't find AMDRadeonX6000Framebuffer.kext, skipping
- Couldn't find AMDRadeonX6000HWServices.kext, skipping
- Couldn't find AppleIntelBDWGraphics.kext, skipping
- Couldn't find AppleIntelBDWGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelCFLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelHD4000Graphics.kext, skipping
- Couldn't find AppleIntelHD5000Graphics.kext, skipping
- Couldn't find AppleIntelICLGraphics.kext, skipping
- Couldn't find AppleIntelICLLPGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelKBLGraphics.kext, skipping
- Couldn't find AppleIntelKBLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelSKLGraphics.kext, skipping
- Couldn't find AppleIntelSKLGraphicsFramebuffer.kext, skipping
- Couldn't find AppleIntelFramebufferAzul.kext, skipping
- Couldn't find AppleIntelFramebufferCapri.kext, skipping
- Couldn't find AppleParavirtGPU.kext, skipping
- Couldn't find GeForce.kext, skipping
- Deleting IOAcceleratorFamily2.kext
- Couldn't find IOGPUFamily.kext, skipping
- Installing General Acceleration Kext patches for Big Sur/Monterey
- Adding IOAcceleratorFamily2.kext
- Found conflicting kext, Deleting Root Volume's IOSurface.kext
- Adding IOSurface.kext
- Adding AppleIntelHD3000Graphics.kext
- Adding AppleIntelHD3000GraphicsGA.plugin
- Adding AppleIntelHD3000GraphicsGLDriver.bundle
- Adding AppleIntelHD3000GraphicsVADriver.bundle
- Adding AppleIntelSNBVA.bundle
- Using stock AppleIntelSNBGraphicsFB
- Adding AppleIntelSNBGraphicsFB.kext
- Merging AppleGVA Hardware Accel patches for non-Metal
- Merging DropboxHack SkyLightPlugins
- Merging general legacy Frameworks
- Merging Monterey WebKit patch
- Merging general legacy PrivateFrameworks
- Installing legacy Wireless support
- Merging Wireless CoreSerices patches
- Merging Wireless usr/libexec patches
- Merging Wireless SkyLightPlugins
- Rebuilding Kernel Cache (This may take some time)
- Successfully built new kernel cache
- Creating new APFS snapshot
- Unmounting Root Volume (Don't worry if this fails)
- Patching complete

Please reboot the machine for patches to take effect
![66586409621__91B91E4A-0A07-4ED4-81B5-9FC46132D01D]

Press [ENTER] to continue

### What steps have you taken to troubleshoot this?

I Tried to fix it with "Broken Background Blurs", but did not help. 

I wondered why when installing the patch many kext where not found and if this is the mistake? So maybe the script for patching the Harddrive don't work properly?

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Comment by freddey** [comment]
Please help what can I do? in #108 it is not adressed or I don't find a solution. Sorry I wrote an Issue for the first time.

**Comment by khronokernel** [comment]
Known issue on TeraScale 1, that's what the issue describes. Buy a newer GPU or downgrade to 11.2.3 or older
