### ISSUE TITLE
After i boot I can’t get into recovery, 

### ISSUE THREAD

**Issue by Sami8612** [dortania/OpenCore-Legacy-Patcher#949]
### Machine Model

MacBookPro7,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

It stays on the apple logo with the loading bar at the bottom. What do i do? It’s been like that for about an hour. this is what I have - OpenCore Legacy Patcher v0.4.2 ## Selected Model: MacBookPro11,2 and im on BigSur version 11.6.4Please clearly explain the issue

### What steps have you taken to troubleshoot this?

I disable the dGPU for UEFI:
sudo nvram FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-power-prefs=%01%00%00%00

then restarted trying to go back in to the install. But still stuck on the apple logo with less then 5% in the loading bar and nothing moving for hours.

**Comment by khronokernel** [comment]
Use forums for troubleshooting

**Comment by Sami8612** [comment]
where is that?
