### ISSUE TITLE
Cannot get the update monetery. and my current big sur has few graphics issue

### ISSUE THREAD

**Issue by zakirsajib** [dortania/OpenCore-Legacy-Patcher#952]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Please clearly explain the issue

I cannot get the update monetery OS from big sur.

I am using opencore 0.4.2 and current os is big sur 11.6.2. 

And also there is a graphics issue on control panel: **Display and sound slider.** 
Please See this screenshot. 

[https://www.awesomescreenshot.com/image/22009913?key=90395ddb07dba0d86939cea9db496be6](url)

### What steps have you taken to troubleshoot this?

None. No idea what to do to fix.

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

> I cannot get the update monetery OS from big sur.

Upgrades must be done via USB to avoid breaking installs. Use forums for troubleshooting
