### ISSUE TITLE
Apple Mail continuously crashes after installation of GPG Suite

### ISSUE THREAD

**Issue by myfrankops** [dortania/OpenCore-Legacy-Patcher#953]
### Machine Model

MacBookPro9,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Apple Mail keeps crashing. This was specifically noted after installation of GPG Suite. 

### What steps have you taken to troubleshoot this?

Tried to uninstall GPG Suite.

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true

Please answer honestly and respect our time, use forums for troubleshooting
