### ISSUE TITLE
My imac 2014 doesn't seen new mac os updates anymore 

### ISSUE THREAD

**Issue by Goadude** [dortania/OpenCore-Legacy-Patcher#954]
### Machine Model

iMac15,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true, false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I saw on youtube that there was an update for mac os monterey .
So i went to the apple logo and then to about this mac and then software update but it did not show a new update.
I also tried it with a terminal command but als no update

i also tride system settings and then software update, but no update

i am on 12.2 and there is an update for 12.2.1

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true

Please answer these honestly and respect our time...

**Comment by Goadude** [comment]
Sorry ,but i did check it.
I don't understand , my other apple computers (2010 and 2013) see the
update but not my 2014 imac alle have the opencore patcher
Thank you for your great work , i love your patcher

Op vr 11 feb. 2022 om 21:03 schreef Mykola Grymalyuk <
***@***.***>:
