### ISSUE TITLE
Keyboard Backlight doesn't work on the latest nightly build (0.4.1, TUI Offline) 

### ISSUE THREAD

**Issue by ArsenicVinter** [dortania/OpenCore-Legacy-Patcher#955]
### Machine Model

MacBookPro8,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (Before Logging in), Within macOS (After Logging in)

### What is the Issue?

So I've gotten the latest preview of OCLP 0.4.1 (TUI, Offline Variant) on my MacBookPro8,2 (Early 2011 15"). The keyboard backlight and other Non-Metal fixes is what I hoped for and after root patching, the brightness sliders were fixed and so were the icons that were missing before (in apps like System Preferences) but the Keyboard Backlight still remains unusable. I was told to use LabTick until the issue is looked into in the Paradise Discord server, but I wanted to let the devs know here as well. Any help is appreciated.

![Screenshot 2022-02-12 at 22 40 29](https://user-images.githubusercontent.com/55028438/153722053-84539286-7ef6-47c4-94eb-174b61c5b4fc.png)

### What steps have you taken to troubleshoot this?

I've tried Unpatching the Root Volume and then patching it but still a no-go. I've also tried patching it without unpatching it

**Comment by Thyssenkrupp234** [comment]
> Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

As stated in the acceleration pages, MacBookPro8,2/8,3 cannot get keyboard brightness control from the keyboard keys itself. You need LabTick. Also, 0.4.1 is not the latest version, rather 0.4.2 is the latest. Please don’t open issues if the docs already talk about the problem. Thanks.

**Comment by ArsenicVinter** [comment]
It’s been fixed now yes, and thanks for the response
