### ISSUE TITLE
Boot does not load system without USB stick, and post install patch fails

### ISSUE THREAD

**Issue by ivent** [dortania/OpenCore-Legacy-Patcher#958]
### Machine Model

Macmini6,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hello first congratulations for the incredible work, I did the installation and it worked perfectly, but my mac mini only starts with the pendrive if I remove the system gives an error, of ? support.apple.com/startup ai when I put the flash drive it starts normally, I tried to do the post install patch operation but I get the following error code:

**####################
# Copying OpenCore #
####################

An error occurred!
0:188: execution error: Volume on disk0s1 failed to mount
Perhaps the operation is not supported (kDAReturnUnsupported)
If you think the volume is supported but damaged, try the "readOnly" option
 (1)

Please report this to the devs at GitHub.

Press [Enter] to go back.
Traceback (most recent call last):
  File "gui_main.py", line 594, in <lambda>
  File "gui_main.py", line 638, in install_oc_process
  File "install.py", line 171, in install_opencore
  File "utilities.py", line 545, in start
EOFError: EOF when reading a line**

So if you can help me to solve this problem, thank you, the dock design also has a small blur in the corners but that's it for the most part everything is working ok.

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true


Answer these honestly and respect the time of developers please

**Comment by ivent** [comment]
@khronokernel  Thanks for the answer I'm sorry to take up your precious time, but I checked https://github.com/dortania/OpenCore-Legacy-Patcher/issues/946 your answer before writing mine and I was honest when I said yes that it was a patcher bug as I had already done it in previous versions of bigsur and I had no problem, but my problem is that I'm stuck I can only start the system with the built-in flash drive, if there is a solution to run the post install without this error, please help me if it will still be solved in a new version, but the fact is that no solution was presented, only one justification and I did the formatting from scratch as shown in the open tutorial, so my question is different from @slothyjunior's what motivated me to open this new call, sorry if I didn't understand your explanation correctly is that I'm from Brazil and I'm using the translation.
