### ISSUE TITLE
Post install Volume patcher messes up partitions on 3T fusion disk on iMac13. Late 2012

### ISSUE THREAD

**Issue by develVannessa** [dortania/OpenCore-Legacy-Patcher#959]
### Machine Model

iMac13,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

First thanks for providing a way to make my iMac live longer with the new nifty features on Monterey. I had 12.3 beta1 installed without any problem with the patcher 0.36 version. I updated with 0.42 and tried to install 12.3 beta 2 which failed using the „installed openCore Legacy Patcher on local disk“, 
1- failed using MacOS update „update failed“
2- failed using a USB stick - still using OCL patcher GUI 
- install on 12.3b2 on USB, build patcher install patcher on USB
- Reboot „alt“ and EFI boot with „alt“
- Choose installl macOS volume
- Install runs OK
- Once logged in: open OCL patcher to run the post-install volume patcher
- Reboot …. And grey-white screen with flashing folder with interrogation point
- Reboot with „ALt“ only sees macIntosch HD which evidently when select sends the „circle with cross in“

So computer does not boot after applying the volume patcher (3T fusion)

### What steps have you taken to troubleshoot this?

Restart in recovery mode
- diskutil GUI sees 2 volumes: MacIntosch HD and Update that are sharing the same partition (2 different volumes though)
- Both verify OK in GUI
- Open Terminal
- Run command-line diskutil list 
- Sees 2 volumes: disk1 internal, physical with EFI and apple_APFS container , disk3 synthesized which contains HD data, -reboot etc… but does not contain a GUID partition table

So I tried to go back to some fundamentals
— I reset my Fusion disk - reinstalled good old Catalina with security updates (old habit) and then install OCL patcher and lastest 12.2.1 no problem with then patching after the install. 
All this using a USB external so that apart from the App all is external prior to patching 
- then updated to 12.3b2 and same issues: installs fine even has universal control. Then Patch applied - reboot and again funky flashing folder with interrogation mark. 
- Reboot with ALT … and only sees a MacIntisch HD which when selected cannot boot and shows a circle with a cross inside.
-reboot in recovery mode and in commanding diskutil:
There is an unnamed volume which when verifyVolume is run shows at the time of verifying the superblocks:
Error: apfs_sb at apfs_fs_index (4): apfs_incompatible_features has unsupported flag: (0x20) Volume superblock is invalid

**Comment by develVannessa** [comment]
Oops iMac 27in late 2012 *iMac13,2* not iMac13,1 sorry

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true

Please answer these honestly and respect the time of developers

**Comment by develVannessa** [comment]
Then: tried to check YES
Managed to check NO because I could not access the forum…
