### ISSUE TITLE
DRM Fix

### ISSUE THREAD

**Issue by FusionLA** [dortania/OpenCore-Legacy-Patcher#96]
Please add the DRM fix.

To the config.plist:
Add to the NVRAM boot -args
shikigva=128 unfairgva=1 -wegtree

Thank you

**Comment by khronokernel** [comment]
Hi, could elaborate a bit more on the hardware this requires? I assume you're regarding Mac Pro users however I'd like to verify this is correct.

**Comment by Ausdauersportler** [comment]
Perfect,  this is the current setting useful for all Macs with upgrades AMD Polaris and later GPU with Big Sur!
I would have posted the same RFC later.

current machines: iMac 11,x and iMac 12,x with AMD GPU, Mac Pro 3,1-5,1 with AMD GPU
