### ISSUE TITLE
Discord - please remove the phone number requirement

### ISSUE THREAD

**Issue by Cueball** [dortania/OpenCore-Legacy-Patcher#961]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

I'd like to interact a little more with the community; in particular to ensure that a handful of issues I've encountered are actually issues with the patcher before I make a formal bug report.

To do that, it's all too clear that one must use Discord. Setting aside that I hate Discord with the fire of 10,000 suns, I can't sign into Discord without first being asked for a username, then a captcha, then my email, then verify my email (on the _same_ device a la magic emails - gah!) then another captcha, then a request for my phone number. **You do not need my phone number. Ever.**

At that point I gave up. This is actually the second time I've tried - I forgot how bad it was last time and got sharply reminded of why I haven't engaged before now.

[I've been testing various beta macOS releases since 10.0 DP4, so I'm not exactly new at this...]

### What steps have you taken to troubleshoot this?

N/A

**Comment by khronokernel** [comment]
* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/gui/gui_main.py#L389-L397

Phone number's a little Easter egg ;p

**Comment by Cueball** [comment]
You've missed the point.

I'm talking about _signing up for Discord_.

**And. Discord. Wants. My. Phone. Number.**

Why?
