### ISSUE TITLE
Login Loop after install the Post Install Root Patch on Monterey on MacBook 8,2

### ISSUE THREAD

**Issue by mcmaxcosta** [dortania/OpenCore-Legacy-Patcher#962]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Hello, I had High Sierra and I have updated my Macbook to Monterey using Opencore-patcher 0.4.2 version, every time I install the Post Install Root Patch and reboot, my Macbook asks for login, then it gets in a loop keeping asking for login over and over.
The only way that I found to stop this is by updating again to Monterey, then it is back to normal, but the Macbook gets slow with some features not working properly, like the video card and standby function.
Can anybody help? Thank you.

### What steps have you taken to troubleshoot this?

I have tried the procedure of reinstall the Post Install Root Patch several times after I updated to Monterey to be able to use the Macbook, but every time I get in a loop with login window.

**Comment by khronokernel** [comment]
> Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages
> true

> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true

Would appreciate answer these honestly:

* https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#cannot-login-on-2011-15-and-17-macbook-pros

Respect the time of developers, we have documentation and a discord server for a reason

**Comment by artdevgame** [comment]
@mcmaxcosta I have this issue too. Did you resolve it?

**Comment by artdevgame** [comment]
Thanks @mcmaxcosta. Sorry, your message may look a little out of context on the GitHub thread. I realised immediately after posting that khronokernel also mentioned the solution and deleted the message - but I forgot that GitHub sends emails out too.

Thank you for responding. Hopefully it's clear to others that find their way onto this thread.
