### ISSUE TITLE
Stuck on BRICKED Prohibitory SIGN!

### ISSUE THREAD

**Issue by Gethubj** [dortania/OpenCore-Legacy-Patcher#963]
### Machine Model

MacPro3,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 10.11, El Capitan

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

![F4D63090-17F9-4D64-9187-5D64F65CCA26](https://user-images.githubusercontent.com/99230467/154197159-a47d4052-07d7-4bf9-a7ff-34b4208cef1f.jpeg)

I stuck on this screen every time I try to boot the macOS Monterey 12.2.

Steps to reproduce:
1- Hold OPTION key to enter the boot menu.
2- pick EF boot.
3- pick install macOS Monterey.
4- stuck on this screen

Even if I choose the usb to boot from the boot menu. I stuck on same screen.

PLEASE HELP!

### What steps have you taken to troubleshoot this?

1- I tried to search on all issues here to find a solution and I couldn’t!
2- I tried to change the UBS flash drive with another one and still same issue remains.
3- I tried to install Big Sur macOS and same issue remains.

i really don’t know how to fix it and I believe you will help me with that to get macOS Monterey installed successfully on my machine.

OCLP: 0.4.2

Thank you so much in advance!

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true

Please answer these honestly and respect the time of developers

**Comment by Gethubj** [comment]
> > Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> > true
> 
> Please answer these honestly and respect the time of developers

Hey, I am absolutely honestly!!!! I went there to check how to fix it before coming here! If you have a topic about that you can sent it me plz to help instead closing my ticket! Thanks for understanding.

**Comment by jochenpa** [comment]
Hi

Have you read this:?
https://dortania.github.io/OpenCore-Legacy-Patcher/MODELS.html

MacPro3,1
- Potential boot issues with built-in USB 1.1 ports (recommend using a USB 2.0 hub or dedicated USB PCIe controller)
- Potential boot issues with stock Bluetooth card, recommend removing to avoid kernel panics

... hope it helps.

Jochen

**Comment by Gethubj** [comment]
> Hi
> 
> Have you read this:? https://dortania.github.io/OpenCore-Legacy-Patcher/MODELS.html
> 
> MacPro3,1
> 
> * Potential boot issues with built-in USB 1.1 ports (recommend using a USB 2.0 hub or dedicated USB PCIe controller)
> * Potential boot issues with stock Bluetooth card, recommend removing to avoid kernel panics
> 
> ... hope it helps.
> 
> Jochen

![8779A2C3-069D-48FC-BCB5-645C5DF75503](https://user-images.githubusercontent.com/99230467/154347444-8170bb20-63f2-4e49-98d6-2d7c6d9e203a.jpeg)


Hi Jochen,

I truly appreciate your reply. Thank you very much.

I have tried to boot from an external hard desk and it was downloading Monterey progress almost 75% and suddenly the machine shutdown and again stuck on the screen with prohibition sign. Nothing can do with that absolutely!!!! I tried (command + R) and ( shift + alt + command + R ) and ( option ) nothing of those methods worked to resume or repeat the installation!!!

please help 🙏🙏🙏🙏🙏
