### ISSUE TITLE
0.4.3 (build 14/02/22 TUI) on iMac 12,2 - Messages not working

### ISSUE THREAD

**Issue by t2pierre** [dortania/OpenCore-Legacy-Patcher#965]
### Machine Model

iMac12,2

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

false

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

false

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

issue with Messages
App is opening but showing no windows and menus won't open
(perfectly working when back to official 0.4.2 release)

**Comment by khronokernel** [comment]
Ref: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/3a9d97131d165efd9201a1dfcb77877c40e731e8
