### ISSUE TITLE
Post install patch is not allowed do to unsupported board id.

### ISSUE THREAD

**Issue by pgeremia** [dortania/OpenCore-Legacy-Patcher#967]
### Machine Model

MacBookPro8,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

1. I performed an upgrade to the latest MacOS using an installer USB
2. Once install completed I installed the boot loader to the hard drive.
3. After that I tried to patch the volume.  Below is the output.

1. Patch System Volume
2. Unpatch System Volume
B. Exit
        
Patch System Volume?: 1
- Found GPU (0): 8086:126
- Starting Patch Process
- Determining Required Patch set for Darwin 21

The following patches will be applied:
- Add Legacy Intel Sandy Bridge Graphics Patch
- Add legacy Audio Control
Would you like to continue with Root Volume Patching?(y/n): y
- Continuing with Patching
- Verifying whether Root Patching possible

Cannot patch! Please disable AMFI.
For Hackintoshes, please add amfi_get_out_of_my_way=1 to boot-args

Cannot patch! Board ID not supported by AppleIntelSNBGraphicsFB
Detected Board ID: Mac-6F01561E16C75D06
Please ensure your Board ID is listed below:
- Mac-E43C1C25D4880AD6 (MacBookPro12,1)
- Mac-06F11F11946D27C5 (MacBookPro11,5)
- Mac-9F18E312C5C2BF0B (MacBookAir7,1)
- Mac-937CB26E2E02BB01 (MacBookAir7,2)
- Mac-35C5E08120C7EEAF (Macmini7,1)
- Mac-7BA5B2D9E42DDD94 (iMacPro1,1)
- Mac-94245B3640C91C81 (MacBookPro8,1)
- Mac-94245A3940C91C80 (MacBookPro8,2)
- Mac-942459F5819B171B (MacBookPro8,3)
- Mac-C08A6BB70A942AC2 (MacBookAir4,1)
- Mac-742912EFDBEE19B3 (MacBookAir4,2)
- Mac-8ED6AF5B48C039E1 (Macmini5,1)
- Mac-4BC72D62AD45599E (Macmini5,2)
- Mac-7BA5B2794B2CDB12 (Macmini5,3)
- Mac-942B5BF58194151B (iMac12,1)
- Mac-942B59F58194171B (iMac12,2)
- Mac-94245AF5819B141B (AAPL_MacBookPro8,3)
- Mac-942B5B3A40C91381 (AAPL_iMac12,2)

It is saying that my system is not supported.

### What steps have you taken to troubleshoot this?

I pulled a hardware dump and it looks like REAL vs REPORTED hardware ID is different.  Any ideas why?

I assume that is the issue?  How can this be resolved?

Here is the hardware dump:

Computer(real_model='MacBookPro8,1', real_board_id='Mac-94245B3640C91C81', reported_model='MacBookPro8,1', reported_board_id='Mac-6F01561E16C75D06', gpus=[Intel(vendor_id=32902, device_id=294, class_code=196608, name='IGPU', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/IGPU@20000', pci_path='PciRoot(0x0)/Pci(0x2,0x0)', arch=<Archs.Sandy_Bridge: 'Sandy Bridge'>)], igpu=Intel(vendor_id=32902, device_id=294, class_code=196608, name='IGPU', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/IGPU@20000', pci_path='PciRoot(0x0)/Pci(0x2,0x0)', arch=<Archs.Sandy_Bridge: 'Sandy Bridge'>), dgpu=None, storage=[SATAController(vendor_id=32902, device_id=7171, class_code=67073, name='SATA', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/SATA@1f0002', pci_path='PciRoot(0x0)/Pci(0x1f,0x2)')], usb_controllers=[EHCIController(vendor_id=32902, device_id=7213, class_code=787232, name='EHC2', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/EHC2@1a0007', pci_path='PciRoot(0x0)/Pci(0x1a,0x7)'), EHCIController(vendor_id=32902, device_id=7206, class_code=787232, name='EHC1', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/EHC1@1d0007', pci_path='PciRoot(0x0)/Pci(0x1d,0x7)'), UHCIController(vendor_id=32902, device_id=7212, class_code=787200, name='UHC5', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/UHC5@1a0000', pci_path='PciRoot(0x0)/Pci(0x1a,0x0)'), UHCIController(vendor_id=32902, device_id=7207, class_code=787200, name='UHC1', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/UHC1@1d0000', pci_path='PciRoot(0x0)/Pci(0x1d,0x0)')], wifi=Broadcom(vendor_id=5348, device_id=17201, class_code=163840, name='ARPT', model=None, acpi_path='IOACPIPlane:/_SB/PCI0@0/RP02@1c0001/ARPT@0', pci_path='PciRoot(0x0)/Pci(0x1c,0x1)/Pci(0x0,0x0)', country_code='US', chipset=<Chipsets.AirPortBrcm4360: 'AirPortBrcm4360 supported'>), cpu=CPU(name='Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz', flags=['FPU', 'VME', 'DE', 'PSE', 'TSC', 'MSR', 'PAE', 'MCE', 'CX8', 'APIC', 'SEP', 'MTRR', 'PGE', 'MCA', 'CMOV', 'PAT', 'PSE36', 'CLFSH', 'DS', 'ACPI', 'MMX', 'FXSR', 'SSE', 'SSE2', 'SS', 'HTT', 'TM', 'PBE', 'SSE3', 'PCLMULQDQ', 'DTES64', 'MON', 'DSCPL', 'VMX', 'EST', 'TM2', 'SSSE3', 'CX16', 'TPR', 'PDCM', 'SSE4.1', 'SSE4.2', 'x2APIC', 'POPCNT', 'AES', 'PCID', 'XSAVE', 'OSXSAVE', 'TSCTMR', 'AVX1.0']), oclp_version='0.4.2', opencore_version='REL-077-2022-01-10', bluetooth_chipset='BRCM20702 Hub', third_party_sata_ssd=True)

I also read through the forums and from what I read I do not need to disable AMFI.  Then why does the patcher say I do?

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug on our discord servers?
> true

Please answer these honestly and respect the time of developers

**Comment by pgeremia** [comment]
Sorry I was in a huge rush this morning and did some quick checking of the tickets but did not have time to get to discord.  I am also a developer and I appreciate all feedback no matter what.  Being arrogant really does no good and just turns people off to your project.  I DO NOT appreciate these responses I get from you.  This is not the first time.

**Comment by khronokernel** [comment]
Oh apologies, I didn't realize Github Issues are your personal help centre where you're entitled to the time of developers. We have a discord server for a reason, why should unpaid developers be required to troubleshoot every single issue filed when realistically they're 99% user error? Troubleshoot first, file later.

We've spent thousands of collected hours working on this project, a bit of respect would be appreciated. You don't pay our rent, so you have no right to just jump in here and skip actually troubleshooting on our discord server. We have this system set up for a reason.
