### ISSUE TITLE
Airplay Receiver option disappeared after upgrade to Monterey 12.3 beta 3 (MacBookPro13,3 and iMac17,1)

### ISSUE THREAD

**Issue by hbierau** [dortania/OpenCore-Legacy-Patcher#968]
### Machine Model

Other/Non-Applicable

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Previous, with OCLP following the procedure described [in this video](https://www.youtube.com/watch?v=sO0yc3_hOE8), I had successfully activated the Airplay receiver feature both on my MacbookPro13,3 and my iMac17,1 (both of which would not be supported natively by Monterey because these models are considered too old). The feature was working fine, however, after upgrading to Monterey 12.3 beta 3, the feature had disappeared. For example, the option cannot be found anymore in the System Prefernces/Sharing menu and the other Mac, respectively, is not visible anymore in the Screen Mirroring options. I reran the OCLP procedure on both Macs after upgrading, however to no avail. Any ideas?

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

Re-running, after the upgrade to the latest Monterey beta, the same OCLP procedure as I originally performed to unlock the Airplay to Mac feature (procedure described [in this video](https://www.youtube.com/watch?v=sO0yc3_hOE8))

**Comment by khronokernel** [comment]
Resolved in 0.4.3:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/957

**Comment by hbierau** [comment]
> Resolved in 0.4.3:
> 
> * [Airplay to Mac is not showing up on native model iMac 18,3 after upgrading to 12.3 beta 2 #957](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/957)

Sorry for the newbie question: the latest downloadable release I can find is 0.4.2.
Is 0.4.3. already available? if yes, where could I download it? or do I need to wait until it becomes "officially" released?

**Comment by khronokernel** [comment]
0.4.3 references the latest commit, you can either compile it manually, use the autogenerated binaries from Github Actions:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/SOURCE.md

However these binaries are in "beta" and have not been validated for proper release, so generally stay on the latest release if you're not a tinkerer
