### ISSUE TITLE
MacBook 5,1 requires a firmware upgrade to proceed

### ISSUE THREAD

**Issue by airman1951** [dortania/OpenCore-Legacy-Patcher#97]
Done with 0.0.18.  Is the problem related to the non-APFS native support ?
![IMG_0147](https://user-images.githubusercontent.com/77781242/111033023-82df9a00-840f-11eb-9bd1-5bcd05c1633d.jpg)

**Comment by airman1951** [comment]
I forgot to attach the EFI build folder.
[Build-Folder.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6134952/Build-Folder.zip)

**Comment by khronokernel** [comment]
@airman1951 I think I see the issue, can you try to rebuild your EFI however before building select `Patcher Settings` -> `Set SMBIOS Mode` -> `Moderate`. This should ensure the APFS bit is flipped for macOS

If this fixes it, will add proper detection in the patcher for models without native APFS support

**Comment by Ausdauersportler** [comment]
You are so fast fixing and closing this: 

I get the same error message on APFS supported machines (iMac12,x) if I use the SMBIOS (manual) spoofing with the BoardProduct to Mac-7BA5B2D9E42DDD94

We had an internal little task force how to come around this whitout using automatic mode and we found this to work properly. I attached plist containing the PlatformInfo part, only.

This sees (as of now) to be the golden way to be used with legacy Macs.

[light.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6135342/light.plist.zip)

There is always a flip side of the coin: 

Using the SystemProductName changes the output of system calls to detect hardware like` sysctl -n hw.model`. To do a real proper system identification one could decode the serial number as Apple does in the `About this Mac` box.

**Comment by khronokernel** [comment]
PlatformFeature is a complicated and semi-undocumented bit mask so it's not really ideal to have 1 hardcoded value across SMBIOS as macOS will expect certain features. Hard coding the features for every model seems quite excessive, as we'd need to update them with nearly every BIOS update issued to that machine if we want to ensure consistency.

I'd prefer the model either has the latest BIOS update or use use Moderate patching and have a note in the troubleshooting page regarding this error. 

> Using the SystemProductName changes the output of system calls to detect hardware like sysctl -n hw.model. To do a real proper system identification one could decode the serial number as Apple does in the About this Mac box.

Why not simply grep the OpenCore version? ie. `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:oem-product`

If you're referring to people using custom OpenCore builds outside of the patcher where ExposeSensitiveData isn't set to the correct bit then that seems like an edge case within an edge case. We could call [macserial's decode function](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macserial/FORMAT.md) however this doesn't get around the issue of custom serials. If a user truly replaces the whole SMBIOS table and doesn't expose any of the original variables, it's impossible for the patcher to realistically decode.

Do you know of any other way to reliably get the original model?

**Comment by Ausdauersportler** [comment]
Regarding the Platform feature might have been a direct communication between @cdf and some OpenCore developers (if I am not completely mistaken) and you can find this [post](https://forums.macrumors.com/threads/opencore-on-the-mac-pro.2207814/post-29652490).

I was discussing the perfect spoofing method with @cdf and @bmju (the minimal usage of SMBOIS variables, avoiding automatic mode, get the best results in terms of functionality) - the plist I sent over is the result of our efforts. Tests were made on iMac12,2 and 11,3 only but we believe that this settings opens the way to get this:

- install unsupported macOS versions using an USB installer (createinstallmedia)
- install unsupported macOS versions using the stock Apple installer app directly starting of the latest supported macOS version (in my case High Sierra)
- getting OTA update with Mojave, Catalina, and Big Sur
- getting full software support with Apple apps like Final Cut Pro X when using one of these new AMD GPUs.

on all machines you target with your OCLP right now.

The nvram call solves a lot. Thanks a lot, sometimes one is trapped in a box.

And yes, if a user truly hides his system data we would not be able to do any detection at all. My assumption was we would use on legacy Macs the SMBIOS manual mode to avoid any discussions about the usage of serial number and to keep the migration from one OCLP to a newer one really simple - using the automatic mode gives you on any run a new set of serials. We had this talking about the migration strategy before. 

No. Unfortunately I do not know a reliably way to find put the original Mac model in any possible case. If there is such a method Apple could easily implement it in his macOS installer programs :-)
