### ISSUE TITLE
Bluethoote not working  

### ISSUE THREAD

**Issue by HerbJul** [dortania/OpenCore-Legacy-Patcher#970]
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

  Bluetooth-Controller:
  Adresse:	NULL
  Status:	Aus
  Chipsatz:	BCM_4350C2
  Sichtbar:	Aus
  Firmwareversion:	v0 c0
  Produkt-ID:	0x0001
  Unterstützte Dienste:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  Transport:	USB
  Hersteller-ID:	0x004C (Apple)

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

install latest Update of Monterey 12.2.1

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?
> false

**Comment by funjoker** [comment]
I'm using Mac mini Late 2012 with Monterey 12.2.1 and OCLP 0.4.2. Bluetooth in general works.
Tho I can not connect my iPhone to it, which seems to be Monterey bug.
https://discussions.apple.com/thread/253303612
