### ISSUE TITLE
Freeze during wake when using igpu

### ISSUE THREAD

**Issue by salihinki** [dortania/OpenCore-Legacy-Patcher#971]
### Machine Model

MacBookPro8,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Graphics switching works on my late 2011 MacBook pro (hd3000/hd6770m), but when using integrated graphics macOS freezes after 1-2 seconds while waking from sleep

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

[DMESG.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8102918/DMESG.txt)
[opencore-2022-02-19-185753.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8102921/opencore-2022-02-19-185753.txt)

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?
> true

Please answer these honestly and respect the time of developers

**Comment by salihinki** [comment]
I apologize if I overlooked something but I checked the guide and asked on discord. (I'm not very well-versed at this stuff, sorry)
Is there a way to fix the wake behavior that I'm missing?

**Comment by AndreasJordanidis** [comment]
you'll have to join the discord and attempt to ask them a question.
Theres a tiny chance you'll get an answer here compared to a somewhat bigger ,If you ask on discord.
