### ISSUE TITLE
Wrong OpenCore boot entry name (shows up as Windows)

### ISSUE THREAD

**Issue by alcroito** [dortania/OpenCore-Legacy-Patcher#972]
### Machine Model

MacBookPro11,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Hi,

On a Macbook Pro 15 Late 2013, after updating from Big sur 11.6.2 to Monterey 12.2.1 using a USB stick and latest stable OCLP 0.4.2, I tried installing OpenCore onto the internal drive EFI partition so i can boot without a USB stick.

At the last guide step, after installing OC to the internal drive and rebooting, while keeping Option pressed at boot time, I see two boot entries: 1) macOS  2) Windows with an OpenCore item.

Choosing the first one fails to boot with the do not park sign (expected I believe).
Choosing Windows, properly boots macOS via OpenCore.

I had a bootcamp partition installed before OpenCore, and it is still accessible if I keep ESC pressed while choosing the OpenCore entry (via the faulty 'Windows' boot entry).

Is there a way to rename the boot entry to OpenCore, or something other than Windows?

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

![IMG_5248](https://user-images.githubusercontent.com/252084/154822814-7229c031-3e02-43ac-8c94-c17b875d0d21.jpg)

**Comment by khronokernel** [comment]
If Windows' boot loader sits inside the same EFI partition as OpenCore, this will happen. You can create a separate EFI partition for OpenCore to avoid this:
* https://dortania.github.io/OpenCore-Legacy-Patcher/WINDOWS.html

However this is the logic of your MacBook's firmware, and can only really be remedied via a dedicated partition for OpenCore. For uninstalling OC from that EFI partition, see here:

* https://dortania.github.io/OpenCore-Legacy-Patcher/UNINSTALL.html

Once removed, just make a new FAT32 partition and install OpenCore onto there
