### ISSUE TITLE
OCB: LoadImage failed - Unsupported

### ISSUE THREAD

**Issue by creatorai21** [dortania/OpenCore-Legacy-Patcher#974]
### Machine Model

MacBook8,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

**ocb loadimage failed - unsupported**

I'm using Macbook early 2015. This error shows up while booting after building opencore.

After thinking many days spent for a 16gb USB, thought this method would work and didn't expect this error.

Hope someone can solve is ASAP!

Thanks

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

![IMG20220222204115](https://user-images.githubusercontent.com/90631980/155176227-dd160206-eb52-45ac-9888-ec7d7fb91459.jpg)

**Comment by khronokernel** [comment]
LoadImage would usually be related to faulty storage, I assume this USB is a bit aged
> Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?
> true

Also please answer these honestly and respect the time of developers. Our server is there for a reason

**Comment by creatorai21** [comment]
I have already asked in discord didn't found any help and I bout new USB just for this!
