### ISSUE TITLE
Stuck in insteller

### ISSUE THREAD

**Issue by Timguy7** [dortania/OpenCore-Legacy-Patcher#975]
### Machine Model

MacBookPro11,2

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

true

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

Loading Mac installer it get stuck!

**Comment by khronokernel** [comment]
Zero logs, debug info, etc. Issues are not for personal help secessions. Use forums or discord for troubleshooting
