### ISSUE TITLE
OCB: LoadImage failed - Unsupported in MacBook 8,1

### ISSUE THREAD

**Issue by creatorai21** [dortania/OpenCore-Legacy-Patcher#976]
I have already asked in discord didn't found any help and I bought new USB just for this!

_Originally posted by @creatorai21 in https://github.com/dortania/OpenCore-Legacy-Patcher/issues/974#issuecomment-1048440383_

**Comment by creatorai21** [comment]
Don't close issue without consent, OCLP not working for my MacBook 8,1. Better remove it as supported Mac in docs or fix this issue.

**Comment by khronokernel** [comment]
> Better remove it as supported Mac in docs or fix this issue.

Your local system is having issues, not OCLP entirely. We have no reason to believe this is an OCLP-wide issue, I already told you where the fault lies (the USB itself).

Now please stop opening duplicate issues
