### ISSUE TITLE
Final Cut Pro crashes on startup | Motion doesn't render | Compressor is unstable and crashes often

### ISSUE THREAD

**Issue by mattio-github** [dortania/OpenCore-Legacy-Patcher#977]
### Machine Model

iMac12,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I am using an **AMD Radeon HD 6750M 512MB VRAM (TeraScale 2)**, which **doesn't support Metal**, and as such, Final Cut Pro refuses to open, it just bounces on the dock, shows the version number and crashes.

Motion doesn't crash on startup, but the window in which you do the work (Preview render window) is not visible; the items in the frame are there and i can interact with them, but i can't see them, which defeats the entire purpose of the program.
Any kind of particle simulation (Emitters, Presets, Ecc...) crashes the program and it is unstable in general (sometimes clicking a button will crash the program).

Compressor _works_, but if you feed it any FCP or MOTN project, it will never render the file and be stuck on the "Loading Project..." screen. 
It is also kinda unstable (sometimes clicking the "Add..." text will crash the program)

I don't expect this issue to be resolved (since Metal is so deeply integrated in these programs that i think it would be impossible to make it work without rewriting the whole thing), but i opened this issue just to document my experience with this patcher, everything else in the system works perfectly fine.

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

I have tried **EVERY SINGLE VERSION** supported by Big Sur, and every one of them shows the same behavior, logs below:

**Crash Final Cut Pro**
Process:               Final Cut Pro [1666]
Path:                  /Applications/Final Cut Pro.app/Contents/MacOS/Final Cut Pro
Identifier:            com.apple.FinalCut
Version:               10.5.2 (382785)
Build Info:            ProEditor-38278005011000000~2 (17C49)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Final Cut Pro [1666]
User ID:               501

Date/Time:             2022-02-22 19:38:02.368 +0100
OS Version:            macOS 11.6.4 (20G417)
Report Version:        12
Anonymous UUID:        28B5293B-0FF4-4233-BEC4-6C6B2E7CBEDA

Time Awake Since Boot: 4500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1666]

VM Regions Near 0x10:
--> 
    __TEXT                      107f06000-107ff6000    [  960K] r-x/r-x SM=COW  /Applications/Final Cut Pro.app/Contents/MacOS/Final Cut Pro

**Crash Motion**
Process:               Motion [1530]
Path:                  /Applications/Motion.app/Contents/MacOS/Motion
Identifier:            com.apple.motionapp
Version:               5.5.1 (382785)
Build Info:            Motion-38278005011000000~2 (17C49)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Motion [1530]
User ID:               501

Date/Time:             2022-02-22 19:27:27.980 +0100
OS Version:            macOS 11.6.4 (20G417)
Report Version:        12
Anonymous UUID:        28B5293B-0FF4-4233-BEC4-6C6B2E7CBEDA

Time Awake Since Boot: 3900 seconds

System Integrity Protection: enabled

Crashed Thread:        2  com.apple.helium.rq.gpu-ru0.vs0

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1530]

**Comment by khronokernel** [comment]
Your system has a socketed GPU, we recommend upgrading it for Metal support:
* https://forums.macrumors.com/threads/2011-imac-graphics-card-upgrade.1596614/?post=17425857#post-17425857
