### ISSUE TITLE
White screen (without apple logo) after installing Big Sur 

### ISSUE THREAD

**Issue by mrkids** [dortania/OpenCore-Legacy-Patcher#979]
### Machine Model

MacBookAir2,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Issue?

I am using the GUI 0.4.2 offline package.  It was going well after creating the usb and rebooting into the Big Sur installer, after the installer complete the installation and it should get into the login page, however it turns into the white screen (without apple logo) and freeze there for 4 to 5 hours. 

I have tried hard reboot it or retry the process again, it always stop there with white screen (without apple logo).
![WhatsApp Image 2022-02-24 at 13 31 22](https://user-images.githubusercontent.com/41146586/155464069-1c4d5a72-42a8-4740-9daf-fe84794cfb5e.jpeg)

**Comment by khronokernel** [comment]
> Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?
> true

Please answer these honestly, discord server is there for a reason. I see zero discussion of your model or yourself
