### ISSUE TITLE
Download stopped

### ISSUE THREAD

**Issue by robertnicjoo** [dortania/OpenCore-Legacy-Patcher#981]
### Machine Model

iMac14,3

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey, Other/Non-Applicable

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

Download stopped on 73.84% 

![Screen Shot 2022-02-25 at 21 10 19](https://user-images.githubusercontent.com/8672823/155729813-2ee9322e-632f-4150-9edd-464971e3c447.png)

Is there direct link for downloads instead of using this GUI?

**Comment by khronokernel** [comment]
I fail to see how this is an OCLP issue? Either:
* Network Instability
* Disk Space issue

You've provided zero debug information, and see no reason to believe we need to investigate further on our end. Please don't use issues for these things.

> Is there direct link for downloads instead of using this GUI?

* https://github.com/corpnewt/gibMacOS

**Comment by AndreasJordanidis** [comment]
> I fail to see how this is an OCLP issue? Either:
> 
> * Network Instability
> * Disk Space issue
> 
> You've provided zero debug information, and see no reason to believe we need to investigate further on our end. Please don't use issues for these things.
> 
> > Is there direct link for downloads instead of using this GUI?
> 
> * https://github.com/corpnewt/gibMacOS

im also having this problem, 40mbs stable download speed, ssd is completely fine and has 80gigs free. it is either that or apples fault
