### ISSUE TITLE
Black interface elements even with Display colour profile enabled

### ISSUE THREAD

**Issue by breitburg** [dortania/OpenCore-Legacy-Patcher#982]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

There are black elements in "Podcasts" app even with "Display" colour profile.

![Screenshot 2022-02-26 at 16 56 20](https://user-images.githubusercontent.com/25728414/155845915-8dd57a56-5a2a-450a-b6f6-b0012d17b88b.png)

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

Switching to "Display" colour profile.

**Comment by khronokernel** [comment]
Updated wording:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
