### ISSUE TITLE
Continue button is missing in Stocks app

### ISSUE THREAD

**Issue by breitburg** [dortania/OpenCore-Legacy-Patcher#983]
### Machine Model

MacBookPro8,1

### Application Version

Latest Build (nightly)

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

At the Stocks app there should be a button to continue, but there isn't:

![Screenshot 2022-02-26 at 22 19 59](https://user-images.githubusercontent.com/25728414/155856551-21398ac9-a028-449f-a5cb-08281aebcf8b.png)

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108
