### ISSUE TITLE
SD Card MacBookpro7,1 not working

### ISSUE THREAD

**Issue by MTYEAGLESCOUT** [dortania/OpenCore-Legacy-Patcher#984]
### Machine Model

MacBook7,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

false

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

SD Card Reader not being detected.

**Comment by khronokernel** [comment]
I assume duplicate:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/978
