### ISSUE TITLE
Issue with OpenCore-Patcher-GUI.app.zip 0.4.5

### ISSUE THREAD

**Issue by uvesten** [dortania/OpenCore-Legacy-Patcher#989]
### Machine Model

MacBookPro8,2

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

It seems that the latest release (0.4.5) is broken, at least the GUI package. I've downloaded it twice on two different machines, and I get the error ~ "The application is damaged. You should move it to the bin"

### What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.

Download the GUI version from https://github.com/dortania/OpenCore-Legacy-Patcher/releases/download/0.4.5/OpenCore-Patcher-GUI.app.zip, try to open it (ctrl-click / right click makes no difference)

**Comment by uvesten** [comment]
Additional info: I've tried opening the app on two different _Intel_ macs, both running 12.3.1. One machine is running OCLP, the other not

**Comment by khronokernel** [comment]
Local issue, not sure how you filed an issue regardless. Issues are supposed to be disabled. Please use the discord as we state in the README...
