### ISSUE TITLE
Late 2012 MBP

### ISSUE THREAD

**Issue by surenmunoo** [dortania/OpenCore-Legacy-Patcher#99]
**Describe the bug**
After installing OCLP 0.0.17 onto Late 2012 MBP EFI partition and a reboot is done the Mac starts and only shows a black screen. on force reboot hold the option key and manually select EFI Folder it freezes the MBP there. Had to revert EFI back to folder created in OCLP 0.0.12 for it to boot again 

**To Reproduce**
1. Open app or .command '...'
2. Enter '....'
3. See error

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.15.7, Catalina)
 - OS Patching (ie. macOS 11.2.3, Big Sur)
 - Model Patching (ie. MacPro5,1)

**Additional context**

**Comment by khronokernel** [comment]
Test with the following build:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2251244784/artifacts/46812002

0.0.17 has a bug with Vaulted configurations

**Comment by surenmunoo** [comment]
Thanks I will try with this

**Comment by khronokernel** [comment]
Reported resolved on discord, closing
